//! Generate `lean/axeyum-creal` — the Lake package that publishes this
//! repository's constructed-real development as **Lean source a third party can
//! `import`**.
//!
//! # Why a generator and not a hand-written package
//!
//! The `creal` development is 3,600-odd declarations this kernel admitted
//! through `Kernel::add_declaration`. Hand-writing any of it in Lean would put a
//! second, unchecked copy of the mathematics in the tree: the published `.lean`
//! would then be a *claim about* the kernel rather than a *projection of* it,
//! and the two could drift silently. So every byte of the package — the module
//! sources, the axiom audit, the manifest, even the `lean-toolchain` — is
//! written by this program from the live kernel, and `--check` fails if what is
//! committed is not what this program would write today.
//!
//! # What Next Ten item 3 asked for, and what the wire route could not do
//!
//! The replay census (ADR-1661) already hands pinned Lean's *kernel* the
//! `lean4export` NDJSON stream and grades every declaration by name. It reports
//! 3,542 of `creal`'s 3,617 accepted: 49 are `Theorem`s whose type is not a
//! proposition (`Lean.Environment.addDeclCore` refuses those as theorems) and 26
//! are ordinary `Prop`-valued theorems whose dependency closure reaches one of
//! the 49, so the *stream* cannot carry them either.
//!
//! Lean **source** has a way out that the wire format does not: a `Type`-valued
//! proof is a perfectly good `def`. So the 49 are emitted as `def`s carrying a
//! doc comment that names the reason, the 26 stop being blocked, and the source
//! route publishes strictly more of the development than the wire route can.
//! The census's own numbers are the floor this package is measured against.
//!
//! # The rendering rules, stated once
//!
//! | kernel declaration | Lean command | why |
//! |---|---|---|
//! | `Definition` | `def` | same thing |
//! | `Theorem`, type in `Prop` | see `--proof-spelling` | a proof |
//! | `Theorem`, type NOT in `Prop` | `def` + doc comment | Lean refuses a `theorem` whose type is not a proposition; the modulus is data (`creal/uniform_convergence.rs`) |
//! | `Opaque` | `opaque` | never re-spelled: it has no value to unfold |
//! | `Axiom` | `axiom` | there are none in `creal`, and the manifest says so |
//! | `Inductive` | `inductive` | Lean regenerates the constructors and the recursor |
//! | `Constructor`, `Recursor` | *(none)* | regenerated by Lean from the `inductive` |
//! | anything else | **exclusion** | listed by name and reason in `EXCLUSIONS.json`; never `sorry`, never an axiom, never silently dropped |
//!
//! Nothing here reads a list of names: `Prop`-ness is decided by asking the
//! kernel to infer the type's sort, exactly as `tests/support/replay_census.rs`
//! does, and the coverage classification is computed against
//! `kernel.environment()`, which is the whole population.
//!
//! # Usage
//!
//! ```text
//! cargo run --release -p axeyum-lean-kernel --example render_creal_library -- \
//!     --out lean/axeyum-creal --facts artifacts/facts --toolchain lean-toolchain
//! cargo run --release -p axeyum-lean-kernel --example render_creal_library -- \
//!     --out lean/axeyum-creal --facts artifacts/facts --toolchain lean-toolchain --check
//! ```
//!
//! `--check` regenerates into memory and diffs against what is on disk, so
//! drift between the kernel and the committed package is a gate failure and not
//! a discovery someone makes later. See ADR-1675.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use axeyum_lean_kernel::{
    Declaration, ExprId, ExprNode, Kernel, LevelNode, NameId, build_creal_prelude, on_a_deep_stack,
};

/// Printed with every count, so a measurement artifact or an ADR pins this
/// generator's numbers by value rather than by a document transcribing them.
const MARKER: &str = "AXEYUM-CREAL-LIBRARY";

/// The Lean module that carries the whole development.
const CARRIER_MODULE: &str = "Axeyum.Creal.Carrier";
/// The Lean module that runs the axiom audit.
const AXIOMS_MODULE: &str = "Axeyum.Creal.Axioms";
/// The module a user imports.
const ROOT_MODULE: &str = "Axeyum.Creal";
/// The positive control for the axiom audit. Deliberately a **separate**
/// library target: it declares an `axiom`, and nothing a user imports may.
const CONTROL_MODULE: &str = "Tests.AxiomControl";

/// Headline results the ledger credits to `creal`. This list is **not** the
/// source of the audit sample — the sample is derived from every fact whose
/// `formal.kernel_theorem` names a declaration in the built environment. It is
/// a *coverage control* on that derivation: if the derived sample stopped
/// containing these, the derivation broke and the generator must fail rather
/// than emit a smaller audit that still passes.
const HEADLINE_CONTROL: &[&str] = &[
    // IVT, approximate and exact.
    "CReal.ivt_approx",
    "CReal.ivt_exact_root",
    // EVT.
    "CReal.evt_approx_max",
    // FTC, both directions.
    "CReal.hasDerivative_antiderivative",
    "CReal.integral_eq_antideriv_diff",
    // MVT and Rolle.
    "CReal.mvt_interiorExtremum",
    "CReal.rolle_interiorExtremum",
    // The constants.
    "CReal.e",
    "CReal.pi",
];

/// How a `Prop`-valued `Theorem` is spelled in the emitted source.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum ProofSpelling {
    /// `theorem` — the strongest statement about the artefact.
    Theorem,
    /// `def` — ADR-0517/0518: Lean's *elaborator* refuses to unfold a `theorem`
    /// while reducing, so a development whose type-checking must compute
    /// through a proof cannot be elaborated from source with `theorem`
    /// spelling. Lean's *kernel* is indifferent.
    Def,
}

impl ProofSpelling {
    fn as_str(self) -> &'static str {
        match self {
            Self::Theorem => "theorem",
            Self::Def => "def",
        }
    }
}

/// Why a declaration this kernel admitted is not a command in the package.
#[derive(Clone, Debug, PartialEq, Eq)]
enum Coverage {
    /// A top-level Lean command carries it.
    Command,
    /// Lean regenerates it from the named `inductive` command.
    RegeneratedByLean(String),
    /// Not carried, with the reason. Listed in `EXCLUSIONS.json`.
    Excluded(String),
}

struct Args {
    out: PathBuf,
    facts: PathBuf,
    toolchain: PathBuf,
    check: bool,
    spelling: ProofSpelling,
}

fn parse_args() -> Args {
    let mut out = PathBuf::from("lean/axeyum-creal");
    let mut facts = PathBuf::from("artifacts/facts");
    let mut toolchain = PathBuf::from("lean-toolchain");
    let mut check = false;
    let mut spelling = ProofSpelling::Def;
    let mut argv = std::env::args().skip(1);
    while let Some(arg) = argv.next() {
        match arg.as_str() {
            "--out" => out = PathBuf::from(argv.next().expect("--out needs a path")),
            "--facts" => facts = PathBuf::from(argv.next().expect("--facts needs a path")),
            "--toolchain" => {
                toolchain = PathBuf::from(argv.next().expect("--toolchain needs a path"));
            }
            "--check" => check = true,
            "--proof-spelling" => {
                spelling = match argv.next().as_deref() {
                    Some("theorem") => ProofSpelling::Theorem,
                    Some("def") => ProofSpelling::Def,
                    other => panic!("--proof-spelling takes `theorem` or `def`, got {other:?}"),
                };
            }
            other => panic!("unknown argument {other}"),
        }
    }
    Args {
        out,
        facts,
        toolchain,
        check,
        spelling,
    }
}

fn main() {
    let args = parse_args();
    // The `creal` build needs a deep stack (`artifacts/kernel-stack-envelope.tsv`).
    let code = on_a_deep_stack(move || run(&args));
    std::process::exit(code);
}

/// One rendered package: relative path -> bytes.
type Package = BTreeMap<String, String>;

struct Census {
    declarations: usize,
    definitions: usize,
    prop_theorems: usize,
    type_valued_theorems: BTreeMap<String, NameId>,
    opaques: usize,
    axioms: Vec<String>,
    inductives: usize,
    constructors: usize,
    recursors: usize,
    quotients: Vec<String>,
}

fn is_a_proposition(kernel: &mut Kernel, ty: ExprId) -> bool {
    let Ok(sort) = kernel.infer(ty) else {
        return false;
    };
    let sort = kernel.whnf(sort);
    let ExprNode::Sort(level) = *kernel.expr_node(sort) else {
        return false;
    };
    matches!(kernel.level_node(level), LevelNode::Zero)
}

/// Classify the whole environment. The population is `kernel.environment()`, so
/// this is a census and not a sample.
fn census(kernel: &mut Kernel) -> Census {
    let rows: Vec<(NameId, String, &'static str, Option<ExprId>)> = kernel
        .environment()
        .iter()
        .map(|(name, decl)| {
            let (kind, theorem_ty) = match decl {
                Declaration::Definition { .. } => ("definition", None),
                Declaration::Theorem { ty, .. } => ("theorem", Some(*ty)),
                Declaration::Opaque { .. } => ("opaque", None),
                Declaration::Axiom { .. } => ("axiom", None),
                Declaration::Inductive { .. } => ("inductive", None),
                Declaration::Constructor { .. } => ("constructor", None),
                Declaration::Recursor { .. } => ("recursor", None),
                Declaration::Quotient { .. } => ("quotient", None),
            };
            (*name, kernel.lean_name(*name), kind, theorem_ty)
        })
        .collect();

    let mut out = Census {
        declarations: rows.len(),
        definitions: 0,
        prop_theorems: 0,
        type_valued_theorems: BTreeMap::new(),
        opaques: 0,
        axioms: Vec::new(),
        inductives: 0,
        constructors: 0,
        recursors: 0,
        quotients: Vec::new(),
    };
    for (name, rendered, kind, theorem_ty) in rows {
        match kind {
            "definition" => out.definitions += 1,
            "opaque" => out.opaques += 1,
            "axiom" => out.axioms.push(rendered),
            "inductive" => out.inductives += 1,
            "constructor" => out.constructors += 1,
            "recursor" => out.recursors += 1,
            "quotient" => out.quotients.push(rendered),
            "theorem" => {
                let ty = theorem_ty.expect("a theorem carries a type");
                if is_a_proposition(kernel, ty) {
                    out.prop_theorems += 1;
                } else {
                    out.type_valued_theorems.insert(rendered, name);
                }
            }
            _ => unreachable!("every declaration kind is classified"),
        }
    }
    out
}

/// Every `formal.kernel_theorem` the fact ledger names, in sorted order.
///
/// Read from the ledger rather than listed here: the audit sample must be what
/// the ledger CREDITS, not what someone remembered to type.
fn ledger_kernel_theorems(facts_dir: &Path) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    let entries = std::fs::read_dir(facts_dir)
        .unwrap_or_else(|e| panic!("the fact ledger must be readable at {facts_dir:?}: {e}"));
    for entry in entries {
        let path = entry.expect("a readable directory entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let text = std::fs::read_to_string(&path).expect("a readable fact");
        let value: serde_json::Value = match serde_json::from_str(&text) {
            Ok(value) => value,
            // The schema gate (`scripts/validate-facts.py`) owns fact validity;
            // this generator must not become a second, weaker copy of it.
            Err(_) => continue,
        };
        if let Some(name) = value
            .get("formal")
            .and_then(|f| f.get("kernel_theorem"))
            .and_then(serde_json::Value::as_str)
        {
            names.insert(name.to_owned());
        }
    }
    assert!(
        !names.is_empty(),
        "the fact ledger yielded no `formal.kernel_theorem` at all -- that is a broken read, \
         not an empty ledger"
    );
    names
}

/// Retag the rendered source: give every `Type`-valued theorem the `def`
/// keyword and a doc comment saying why.
///
/// Text surgery over generated text, with a live guard: the return value is the
/// number of declaration heads actually rewritten, and the caller requires it
/// to equal the number of `Type`-valued theorems the kernel found. A rename in
/// the module writer that moved a declaration head off column zero would make
/// this return the wrong number and fail the generator, rather than silently
/// emitting a `theorem` Lean refuses.
fn retag_type_valued(source: &str, subjects: &BTreeMap<String, NameId>, from: &str) -> (String, usize) {
    let mut out = String::with_capacity(source.len() + subjects.len() * 200);
    let mut rewritten = 0usize;
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    for line in source.split_inclusive('\n') {
        if let Some(rest) = line.strip_prefix(from)
            && let Some(rest) = rest.strip_prefix(' ')
        {
            let head: &str = rest
                .split([' ', '\n'])
                .next()
                .unwrap_or("")
                .split(".{")
                .next()
                .unwrap_or("");
            if let Some((subject, _)) = subjects.get_key_value(head) {
                assert!(
                    seen.insert(subject.as_str()),
                    "declaration head `{from} {subject}` appears twice at column zero"
                );
                out.push_str(TYPE_VALUED_DOC);
                out.push_str("def ");
                out.push_str(rest);
                rewritten += 1;
                continue;
            }
        }
        out.push_str(line);
    }
    (out, rewritten)
}

const TYPE_VALUED_DOC: &str = "/-- Admitted by the Axeyum kernel as a **theorem**, published here as a `def`.\n\
     Its type is not in `Prop`: the convergence rate / continuity modulus it\n\
     carries is *data*, because `Exists.rec` cannot eliminate into `Type`\n\
     (`creal/uniform_convergence.rs`). `Lean.Environment.addDeclCore` refuses a\n\
     `theorem` whose type is not a proposition, and the `lean4export` wire route\n\
     therefore cannot carry it at all (ADR-1661); Lean source can, as this.\n\
     The term is unchanged and Lean's kernel checks it. -/\n";

/// The declaration heads the emitted source actually carries, read back from
/// the text so the count is a property of the artefact and not of the intent.
fn declaration_heads(source: &str) -> BTreeSet<String> {
    let mut heads = BTreeSet::new();
    for line in source.lines() {
        for keyword in ["def ", "theorem ", "opaque ", "axiom ", "inductive "] {
            if let Some(rest) = line.strip_prefix(keyword) {
                let head = rest
                    .split([' ', '\n'])
                    .next()
                    .unwrap_or("")
                    .split(".{")
                    .next()
                    .unwrap_or("");
                if !head.is_empty() {
                    heads.insert(head.to_owned());
                }
                break;
            }
        }
    }
    heads
}

#[allow(clippy::too_many_lines)]
fn run(args: &Args) -> i32 {
    let started = std::time::Instant::now();
    let mut kernel = Kernel::new();
    build_creal_prelude(&mut kernel).expect("the CReal development must build");
    let build_seconds = started.elapsed().as_secs_f64();

    let census = census(&mut kernel);
    let roots: Vec<NameId> = kernel.environment().iter().map(|(name, _)| *name).collect();

    // ------------------------------------------------------------------
    // Render, twice, and require the two to be byte-identical. Determinism
    // is a public API promise (CLAUDE.md); a generated package that is not
    // byte-stable makes `--check` a coin flip.
    // ------------------------------------------------------------------
    kernel.set_render_proofs_as_def(args.spelling == ProofSpelling::Def);
    let first = kernel.render_lean_prelude_module(CARRIER_MODULE, &roots);
    let second = kernel.render_lean_prelude_module(CARRIER_MODULE, &roots);
    assert_eq!(
        first.source(),
        second.source(),
        "two renderings of one kernel must be byte-identical"
    );
    let carrier_file = first.file_name();

    let (carrier_source, rewritten) = retag_type_valued(
        first.source(),
        &census.type_valued_theorems,
        args.spelling.as_str(),
    );
    assert_eq!(
        rewritten,
        census.type_valued_theorems.len(),
        "every `Type`-valued theorem must be retagged as a `def`; the module writer's \
         declaration-head shape has moved"
    );

    // ------------------------------------------------------------------
    // Coverage: every declaration is a command, regenerated by Lean, or a
    // listed exclusion. Nothing is silently dropped.
    // ------------------------------------------------------------------
    let heads = declaration_heads(&carrier_source);
    let mut coverage: BTreeMap<String, Coverage> = BTreeMap::new();
    let mut emitted_inductives: BTreeSet<NameId> = BTreeSet::new();
    for (&name, decl) in kernel.environment().iter() {
        if matches!(decl, Declaration::Inductive { .. }) && heads.contains(&kernel.lean_name(name))
        {
            emitted_inductives.insert(name);
        }
    }
    let emitted_inductive_names: BTreeSet<String> = emitted_inductives
        .iter()
        .map(|&name| kernel.lean_name(name))
        .collect();
    // A constructor names its inductive in the declaration; a `Recursor` does
    // not carry one, so its owner is read off the name the kernel generated it
    // under (`X.rec`), which is the same rule `Kernel::name_of_rec` uses in the
    // other direction. Anything that does not fit becomes an exclusion rather
    // than a guess.
    let owners: BTreeMap<NameId, String> = kernel
        .environment()
        .iter()
        .filter_map(|(&name, decl)| match decl {
            Declaration::Constructor { inductive, .. } => {
                Some((name, kernel.lean_name(*inductive)))
            }
            Declaration::Recursor { .. } => {
                let rendered = kernel.lean_name(name);
                rendered
                    .strip_suffix(".rec")
                    .map(|owner| (name, owner.to_owned()))
            }
            _ => None,
        })
        .collect();
    let mut excluded: Vec<(String, String)> = Vec::new();
    for (&name, _) in kernel.environment().iter() {
        let rendered = kernel.lean_name(name);
        let verdict = if heads.contains(&rendered) {
            Coverage::Command
        } else if let Some(owner) = owners.get(&name) {
            if emitted_inductive_names.contains(owner) {
                Coverage::RegeneratedByLean(owner.clone())
            } else {
                Coverage::Excluded(format!(
                    "its inductive `{owner}` is not emitted as an `inductive` command"
                ))
            }
        } else if census.quotients.contains(&rendered) {
            Coverage::Excluded(
                "Lean's built-in quotient package is not available in a `prelude` module"
                    .to_owned(),
            )
        } else {
            Coverage::Excluded("no top-level command carries it".to_owned())
        };
        if let Coverage::Excluded(reason) = &verdict {
            excluded.push((rendered.clone(), reason.clone()));
        }
        coverage.insert(rendered, verdict);
    }
    let commands = coverage
        .values()
        .filter(|c| **c == Coverage::Command)
        .count();
    let regenerated = coverage
        .values()
        .filter(|c| matches!(c, Coverage::RegeneratedByLean(_)))
        .count();

    // ------------------------------------------------------------------
    // The audit sample: derived from the ledger, controlled on the headlines.
    // ------------------------------------------------------------------
    let ledger = ledger_kernel_theorems(&args.facts);
    let present: BTreeSet<String> = kernel
        .environment()
        .iter()
        .map(|(&name, _)| kernel.lean_name(name))
        .collect();
    let sample: Vec<String> = ledger
        .iter()
        .filter(|name| present.contains(*name))
        .filter(|name| coverage.get(*name).is_some_and(|c| *c == Coverage::Command))
        .cloned()
        .collect();
    assert!(
        !sample.is_empty(),
        "the derived audit sample is empty; `#print axioms` over nothing would pass over nothing"
    );
    let missing_headlines: Vec<&str> = HEADLINE_CONTROL
        .iter()
        .copied()
        .filter(|h| !sample.iter().any(|s| s == h))
        .collect();
    assert!(
        missing_headlines.is_empty(),
        "the derived audit sample lost headline results {missing_headlines:?}; the derivation \
         is broken and a smaller audit that still passed would be worse than none"
    );

    let package = assemble(
        args,
        &carrier_file,
        &carrier_source,
        &sample,
        &census,
        &excluded,
        commands,
        regenerated,
    );

    println!(
        "{MARKER} declarations={} commands={commands} regenerated={regenerated} excluded={} \
         definitions={} prop_theorems={} type_valued_theorems={} opaques={} axioms={} \
         inductives={} spelling={} audit_sample={} carrier_bytes={} build_seconds={build_seconds:.1}",
        census.declarations,
        excluded.len(),
        census.definitions,
        census.prop_theorems,
        census.type_valued_theorems.len(),
        census.opaques,
        census.axioms.len(),
        census.inductives,
        args.spelling.as_str(),
        sample.len(),
        carrier_source.len(),
    );
    for (name, reason) in &excluded {
        println!("{MARKER} exclusion {name} -- {reason}");
    }

    if args.check {
        let mut drift = Vec::new();
        for (relative, want) in &package {
            let path = args.out.join(relative);
            match std::fs::read_to_string(&path) {
                Ok(found) if found == *want => {}
                Ok(found) => drift.push(format!(
                    "{relative}: committed {} bytes, generator writes {} bytes",
                    found.len(),
                    want.len()
                )),
                Err(error) => drift.push(format!("{relative}: {error}")),
            }
        }
        if drift.is_empty() {
            println!("{MARKER} check OK -- {} files match", package.len());
            return 0;
        }
        eprintln!(
            "{MARKER} check FAILED -- the committed package is not what this kernel renders today:"
        );
        for row in &drift {
            eprintln!("  {row}");
        }
        eprintln!("  regenerate with: cargo run --release -p axeyum-lean-kernel --example render_creal_library");
        return 1;
    }

    for (relative, contents) in &package {
        let path = args.out.join(relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("the package directory must be creatable");
        }
        std::fs::write(&path, contents).expect("the package file must be writable");
    }
    println!("{MARKER} wrote {} files to {}", package.len(), args.out.display());
    0
}

#[allow(clippy::too_many_arguments)]
fn assemble(
    args: &Args,
    carrier_file: &str,
    carrier_source: &str,
    sample: &[String],
    census: &Census,
    excluded: &[(String, String)],
    commands: usize,
    regenerated: usize,
) -> Package {
    let pin = std::fs::read_to_string(&args.toolchain)
        .expect("the repository's `lean-toolchain` must be readable");
    let pin = pin.trim().to_owned();

    let mut package = Package::new();
    package.insert(carrier_file.to_owned(), carrier_source.to_owned());
    package.insert("lean-toolchain".to_owned(), format!("{pin}\n"));
    package.insert(".gitignore".to_owned(), ".lake/\n".to_owned());
    package.insert("lakefile.lean".to_owned(), lakefile());
    package.insert(
        format!("{}.lean", ROOT_MODULE.replace('.', "/")),
        root_module(census, commands, regenerated, excluded.len()),
    );
    package.insert(
        format!("{}.lean", AXIOMS_MODULE.replace('.', "/")),
        axioms_module(sample),
    );
    package.insert(
        format!("{}.lean", CONTROL_MODULE.replace('.', "/")),
        control_module(),
    );
    package.insert(
        "EXCLUSIONS.json".to_owned(),
        exclusions_json(excluded, args.spelling),
    );
    package.insert(
        "MANIFEST.json".to_owned(),
        manifest_json(census, commands, regenerated, excluded.len(), sample.len(), &pin, args.spelling),
    );
    package.insert("README.md".to_owned(), readme(census, commands, sample.len()));
    package
}

fn lakefile() -> String {
    format!(
        "\
-- GENERATED by `crates/axeyum-lean-kernel/examples/render_creal_library.rs`.
-- Do not edit: `scripts/check-lean-creal-library.sh` regenerates this file and
-- fails on any difference.
import Lake
open Lake DSL

/-!
`Axeyum.Creal` -- this repository's constructed reals, as Lean source.

No Mathlib dependency, and none is possible yet: the development is emitted in
`prelude` mode because it declares its own `Eq`, `And`, `Or`, `Exists`, `True`
and `False`, which would collide with `Init`. A Mathlib-facing version needs the
`CReal` <-> `Real` bridge the carrier-correspondence ledger specifies
(ADR-1665, row `CC:creal-real`); see ADR-1675.

`Audit` is a separate target from `Axeyum` because it is a *claim*, not a
development: it runs `#print axioms` over every result the fact ledger credits.
`Tests` is separate again because it declares an `axiom` -- the positive control
that proves the audit can fail -- and nothing a user imports may.
-/

package «axeyum-creal» where
  leanOptions := #[
    ⟨`autoImplicit, false⟩
  ]

@[default_target]
lean_lib Axeyum where
  roots := #[`{ROOT_MODULE}, `{CARRIER_MODULE}]

@[default_target]
lean_lib Audit where
  roots := #[`{AXIOMS_MODULE}]

lean_lib Tests where
  roots := #[`{CONTROL_MODULE}]
"
    )
}

fn root_module(census: &Census, commands: usize, regenerated: usize, excluded: usize) -> String {
    format!(
        "\
-- GENERATED by `crates/axeyum-lean-kernel/examples/render_creal_library.rs`.
-- Do not edit.
--
-- Axeyum.Creal -- the constructed reals as a Bishop setoid of regular sequences
-- with explicit moduli (ADR-0512). Import this module to get the whole
-- development: {commands} Lean commands carrying {declarations} kernel
-- declarations ({regenerated} of them regenerated by Lean from an `inductive`
-- command), {excluded} excluded.
--
-- This module is `prelude`: the development declares its own `Eq`, `And`, `Or`,
-- `Exists`, `True` and `False`, so it cannot coexist with `Init` in one
-- environment. A file that imports it must be `prelude` too.
--
-- Every proof term here was admitted by the Axeyum kernel through
-- `Kernel::add_declaration` and carries an empty `Kernel::axiom_footprint`.
-- `Axeyum.Creal.Axioms` re-establishes that on the Lean side with
-- `#print axioms`.
prelude
import {CARRIER_MODULE}
",
        declarations = census.declarations,
    )
}

fn axioms_module(sample: &[String]) -> String {
    let mut out = String::new();
    out.push_str(
        "\
-- GENERATED by `crates/axeyum-lean-kernel/examples/render_creal_library.rs`.
-- Do not edit.
--
-- THE AXIOM AUDIT. One `#print axioms` per result the fact ledger credits to
-- the constructed reals -- the sample is derived from every fact whose
-- `formal.kernel_theorem` names a declaration in the built environment, never
-- hand-listed, and the generator fails if that derivation stops covering the
-- headline results (IVT, EVT, FTC both directions, MVT, Rolle, `e`, `pi`).
--
-- Every line this module prints must read `does not depend on any axioms`.
-- `scripts/check-lean-creal-library.sh` enforces that, enforces a floor on how
-- many lines there are, and requires the positive control in
-- `Tests/AxiomControl.lean` to print the opposite -- so a `#print axioms` that
-- had stopped traversing could not pass.
--
-- `#guard_msgs` is NOT used here and cannot be: it lives in `Lean.Elab`, which
-- is unreachable from a `prelude` module, and `prelude` is forced by the
-- development's own `Eq`/`And`/`Or`. Measured on the pin, 2026-09-05: a
-- `#guard_msgs` in a `prelude` module is a parse error (`expected token`),
-- while `#print axioms` works because it is a builtin command elaborator.
prelude
",
    );
    let _ = writeln!(out, "import {CARRIER_MODULE}");
    out.push('\n');
    for name in sample {
        let _ = writeln!(out, "#print axioms {name}");
    }
    out
}

fn control_module() -> String {
    format!(
        "\
-- GENERATED by `crates/axeyum-lean-kernel/examples/render_creal_library.rs`.
-- Do not edit.
--
-- THE POSITIVE CONTROL for the axiom audit, and the reason this is a separate
-- Lake target: it declares an `axiom`, and nothing a user imports may.
--
-- `Axeyum.Creal.Axioms` asserts that every audited result reports `does not
-- depend on any axioms`. On its own that assertion is consistent with
-- `#print axioms` having silently stopped traversing into imported proofs -- in
-- which case an audit resting on a `sorryAx` would still look clean. This
-- module makes that failure mode visible: `axeyumCrealAudit_control` rests on a
-- declared axiom THROUGH an imported theorem, so `#print axioms` must name that
-- axiom. The gate requires that line, and fails without it.
prelude
import {CARRIER_MODULE}

axiom axeyumCrealAudit_controlAxiom : CReal.Equiv CReal.zero CReal.zero

theorem axeyumCrealAudit_control : CReal.Equiv CReal.zero CReal.zero :=
  CReal.Equiv.trans CReal.zero CReal.zero CReal.zero
    axeyumCrealAudit_controlAxiom (CReal.Equiv.refl CReal.zero)

#print axioms axeyumCrealAudit_control
"
    )
}

fn exclusions_json(excluded: &[(String, String)], spelling: ProofSpelling) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    let _ = writeln!(
        out,
        "  \"generated_by\": \"crates/axeyum-lean-kernel/examples/render_creal_library.rs\","
    );
    let _ = writeln!(out, "  \"proof_spelling\": \"{}\",", spelling.as_str());
    let _ = writeln!(
        out,
        "  \"note\": \"A declaration the Axeyum kernel admitted that the published package does not carry as a Lean command. Never emitted as `sorry` and never as an axiom: it is listed here or it is in the package.\","
    );
    let _ = writeln!(out, "  \"count\": {},", excluded.len());
    out.push_str("  \"exclusions\": [");
    for (index, (name, reason)) in excluded.iter().enumerate() {
        if index > 0 {
            out.push(',');
        }
        let _ = write!(
            out,
            "\n    {{ \"name\": {}, \"reason\": {} }}",
            json_string(name),
            json_string(reason)
        );
    }
    if excluded.is_empty() {
        out.push_str("]\n}\n");
    } else {
        out.push_str("\n  ]\n}\n");
    }
    out
}

#[allow(clippy::too_many_arguments)]
fn manifest_json(
    census: &Census,
    commands: usize,
    regenerated: usize,
    excluded: usize,
    audit_sample: usize,
    pin: &str,
    spelling: ProofSpelling,
) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    let _ = writeln!(
        out,
        "  \"generated_by\": \"crates/axeyum-lean-kernel/examples/render_creal_library.rs\","
    );
    let _ = writeln!(out, "  \"carrier\": \"creal\",");
    let _ = writeln!(out, "  \"lean_toolchain_pin\": {},", json_string(pin));
    let _ = writeln!(out, "  \"proof_spelling\": \"{}\",", spelling.as_str());
    let _ = writeln!(out, "  \"kernel_declarations\": {},", census.declarations);
    let _ = writeln!(out, "  \"lean_commands\": {commands},");
    let _ = writeln!(out, "  \"regenerated_by_lean\": {regenerated},");
    let _ = writeln!(out, "  \"excluded\": {excluded},");
    let _ = writeln!(out, "  \"definitions\": {},", census.definitions);
    let _ = writeln!(out, "  \"prop_theorems\": {},", census.prop_theorems);
    let _ = writeln!(
        out,
        "  \"type_valued_theorems\": {},",
        census.type_valued_theorems.len()
    );
    let _ = writeln!(out, "  \"opaques\": {},", census.opaques);
    let _ = writeln!(out, "  \"kernel_axioms\": {},", census.axioms.len());
    let _ = writeln!(out, "  \"inductives\": {},", census.inductives);
    let _ = writeln!(out, "  \"constructors\": {},", census.constructors);
    let _ = writeln!(out, "  \"recursors\": {},", census.recursors);
    let _ = writeln!(out, "  \"audit_sample\": {audit_sample},");
    out.push_str("  \"type_valued_theorem_names\": [");
    for (index, name) in census.type_valued_theorems.keys().enumerate() {
        if index > 0 {
            out.push(',');
        }
        let _ = write!(out, "\n    {}", json_string(name));
    }
    out.push_str("\n  ]\n}\n");
    out
}

fn readme(census: &Census, commands: usize, audit_sample: usize) -> String {
    format!(
        "\
<!-- GENERATED by `crates/axeyum-lean-kernel/examples/render_creal_library.rs`. Do not edit. -->
# `axeyum-creal` — the constructed reals, as a Lean library

A Lake package on this repository's pinned Lean cross-check toolchain, with no
Mathlib dependency. Every declaration in it was admitted by the Axeyum kernel
through `Kernel::add_declaration` and rendered from that kernel by a generator;
nothing here was written by hand.

| | |
|---|---|
| kernel declarations | {declarations} |
| Lean commands emitted | {commands} |
| `Prop`-valued theorems | {prop_theorems} |
| `Type`-valued theorems (published as `def`) | {type_valued} |
| definitions | {definitions} |
| kernel axioms in the development | {axioms} |
| results audited by `#print axioms` | {audit_sample} |

## Using it

```lean
prelude
import Axeyum.Creal

-- The intermediate value theorem, constructively: for a function with a
-- continuity modulus and a sign change, a point where the value is within any
-- stated accuracy of zero.
#check CReal.ivt_approx
```

Your file must be `prelude`. The development declares its own `Eq`, `And`,
`Or`, `Exists`, `True` and `False`, so it cannot share an environment with
Lean's `Init`. Bridging to Lean core (and then to Mathlib's `Real`) is the
`CReal` ↔ `Real` row of the carrier-correspondence ledger, ADR-1665, and is
not in this version.

## What is checked, and by whom

* **Axeyum's kernel** admitted every term here, and reports an empty
  `Kernel::axiom_footprint` for the whole carrier.
* **Lean's kernel** re-checks every term when you build the package.
* **`Axeyum.Creal.Axioms`** runs `#print axioms` over the {audit_sample}
  results this repository's fact ledger credits to the constructed reals. Every
  line must read `does not depend on any axioms`.
* **`Tests/AxiomControl.lean`** is the positive control: it rests on a declared
  axiom and `#print axioms` must say so, which is what makes the audit above
  capable of failing.

Gate: `scripts/check-lean-creal-library.sh`. Decision: ADR-1675.
",
        declarations = census.declarations,
        prop_theorems = census.prop_theorems,
        type_valued = census.type_valued_theorems.len(),
        definitions = census.definitions,
        axioms = census.axioms.len(),
    )
}

fn json_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
