//! Coordinatised Euclidean geometry: theorems as ideal-membership questions,
//! settled by a **Nullstellensatz cofactor certificate**.
//!
//! [`crate::geometry`] decides positional predicates at *concrete* rational
//! coordinates. This module states them at **symbolic** coordinates: every point
//! is a pair of indeterminates, every predicate is a polynomial in
//! [`crate::mvpoly::MvPoly`] that vanishes exactly on the configurations
//! satisfying it. A theorem
//!
//! ```text
//! h₁ = 0, …, hₙ = 0   (hypotheses)      ⟹   c = 0   (conclusion)
//! ```
//!
//! then becomes the question "does `c` lie in the ideal generated by the `hᵢ`?",
//! and [`crate::groebner_cert`] answers it with an **identity**
//!
//! ```text
//! c = Σᵢ uᵢ · hᵢ
//! ```
//!
//! that a checker re-derives with polynomial addition and multiplication alone.
//! At any common zero of the hypotheses the right-hand side is `0`, so `c` is
//! `0` — regardless of how the `uᵢ` were found, and simultaneously for **every**
//! configuration. That is the whole proof.
//!
//! # Non-degeneracy is explicit, or the theorem is false
//!
//! Mechanised geometry's characteristic failure is a proof that silently holds
//! only away from degenerate configurations — the collinear "triangle", the
//! coincident vertices. Many classical theorems' conclusions are not in the plain
//! hypothesis ideal at all; they are in the **saturation** of that ideal by the
//! non-degeneracy conditions. So a condition `d ≠ 0` is admitted here only by
//! being *named* and turned into a generator via the Rabinowitsch trick: a fresh
//! variable `z` and the generator `d·z − 1`. The certificate then reads
//!
//! ```text
//! c = Σᵢ uᵢ · hᵢ + w · (d·z − 1)
//! ```
//!
//! and specialising `z := 1/d` — legitimate exactly when `d ≠ 0` — kills the last
//! term. The condition is therefore visible in the artifact rather than assumed
//! in prose, and [`certify`] reports the **smallest** set of conditions that makes
//! the reduction succeed, so a theorem that needs none says so.
//!
//! # What a certificate does and does not establish
//!
//! The identity is an identity in `ℚ[coordinates, z…]`, hence valid over every
//! field of characteristic zero. Two things it does **not** do:
//!
//! - It says nothing about configurations where a saturating `d` vanishes. Those
//!   are exactly where these theorems can be false, which is why
//!   [`DegenerateWitness`] exists and is checked.
//! - It does not certify that a polynomial *means* the geometric predicate it is
//!   named after. That link is the coordinatisation, and it is an assumption.

use std::collections::{BTreeMap, BTreeSet};

use axeyum_ir::Rational;

use crate::groebner::MonomialOrder;
use crate::groebner_cert::{CofactorOutcome, DeclineReason, Limits, reduce_many_with_cofactors};
use crate::linear_elim::eliminate;
use crate::mvpoly::MvPoly;

/// A point of the plane at symbolic coordinates.
///
/// The coordinates are arbitrary polynomials rather than bare variables so that
/// *constructed* points (a midpoint, a centroid) are ordinary points with no
/// extra variables and no extra hypotheses: the construction is carried out in
/// the coefficient field instead of being asserted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pt {
    /// The abscissa.
    pub x: MvPoly,
    /// The ordinate.
    pub y: MvPoly,
}

impl Pt {
    /// A point at two fresh indeterminates `<name>x` and `<name>y`.
    #[must_use]
    pub fn free(name: &str) -> Pt {
        Pt {
            x: MvPoly::var(&format!("{name}x")),
            y: MvPoly::var(&format!("{name}y")),
        }
    }

    /// A point at explicit rational coordinates.
    #[must_use]
    pub fn fixed(x: Rational, y: Rational) -> Pt {
        Pt {
            x: MvPoly::constant(x),
            y: MvPoly::constant(y),
        }
    }

    /// Componentwise difference, `None` on coefficient overflow.
    #[must_use]
    pub fn sub(&self, other: &Pt) -> Option<Pt> {
        Some(Pt {
            x: self.x.sub(&other.x)?,
            y: self.y.sub(&other.y)?,
        })
    }

    /// Componentwise sum, `None` on coefficient overflow.
    #[must_use]
    pub fn add(&self, other: &Pt) -> Option<Pt> {
        Some(Pt {
            x: self.x.add(&other.x)?,
            y: self.y.add(&other.y)?,
        })
    }

    /// Scale both coordinates by an exact rational.
    #[must_use]
    pub fn scale(&self, factor: Rational) -> Option<Pt> {
        let constant = MvPoly::constant(factor);
        Some(Pt {
            x: self.x.mul(&constant)?,
            y: self.y.mul(&constant)?,
        })
    }
}

/// The scalar cross product `first × second`. Zero exactly when the two vectors
/// are parallel.
#[must_use]
pub fn det(first: &Pt, second: &Pt) -> Option<MvPoly> {
    first.x.mul(&second.y)?.sub(&first.y.mul(&second.x)?)
}

/// The Euclidean inner product `first · second`. Zero exactly when the two
/// vectors are orthogonal.
#[must_use]
pub fn dot(first: &Pt, second: &Pt) -> Option<MvPoly> {
    first.x.mul(&second.x)?.add(&first.y.mul(&second.y)?)
}

/// `|AB|²`, the squared distance — a polynomial, unlike the distance itself.
#[must_use]
pub fn dist_sq(from: &Pt, to: &Pt) -> Option<MvPoly> {
    let delta = to.sub(from)?;
    dot(&delta, &delta)
}

/// `A`, `B`, `C` are collinear: the signed area of the triangle vanishes.
#[must_use]
pub fn collinear(first: &Pt, second: &Pt, third: &Pt) -> Option<MvPoly> {
    det(&second.sub(first)?, &third.sub(first)?)
}

/// Line `AB` is parallel to line `CD`.
#[must_use]
pub fn parallel(from: &Pt, to: &Pt, other_from: &Pt, other_to: &Pt) -> Option<MvPoly> {
    det(&to.sub(from)?, &other_to.sub(other_from)?)
}

/// Line `AB` is perpendicular to line `CD`.
#[must_use]
pub fn perpendicular(from: &Pt, to: &Pt, other_from: &Pt, other_to: &Pt) -> Option<MvPoly> {
    dot(&to.sub(from)?, &other_to.sub(other_from)?)
}

/// `|AB| = |CD|`, stated on squared distances so it stays polynomial.
#[must_use]
pub fn equidistant(from: &Pt, to: &Pt, other_from: &Pt, other_to: &Pt) -> Option<MvPoly> {
    dist_sq(from, to)?.sub(&dist_sq(other_from, other_to)?)
}

/// The midpoint of `AB`, constructed rather than asserted.
#[must_use]
pub fn midpoint(from: &Pt, to: &Pt) -> Option<Pt> {
    from.add(to)?.scale(Rational::new(1, 2))
}

/// The centroid of `ABC`, constructed rather than asserted.
#[must_use]
pub fn centroid(first: &Pt, second: &Pt, third: &Pt) -> Option<Pt> {
    first.add(second)?.add(third)?.scale(Rational::new(1, 3))
}

/// `A = B` as two coordinate equations.
#[must_use]
pub fn same_point(first: &Pt, second: &Pt) -> Option<[MvPoly; 2]> {
    Some([first.x.sub(&second.x)?, first.y.sub(&second.y)?])
}

/// A named polynomial that a configuration must make **zero**: a hypothesis or a
/// conclusion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Constraint {
    /// Stable identifier, used in the serialised certificate.
    pub id: String,
    /// What the polynomial says geometrically. Prose, for a reader.
    pub description: String,
    /// The polynomial itself.
    pub poly: MvPoly,
}

impl Constraint {
    /// Convenience constructor.
    #[must_use]
    pub fn new(id: &str, description: &str, poly: MvPoly) -> Constraint {
        Constraint {
            id: id.to_string(),
            description: description.to_string(),
            poly,
        }
    }
}

/// A named polynomial that a configuration must make **nonzero**: a
/// non-degeneracy condition.
///
/// The same shape as [`Constraint`] and deliberately a distinct type — confusing
/// "must vanish" with "must not vanish" is precisely the mistake this module is
/// built to make impossible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Condition {
    /// Stable identifier, used in the serialised certificate.
    pub id: String,
    /// What the condition excludes, e.g. "A, B and D are not collinear".
    pub description: String,
    /// The polynomial required to be nonzero.
    pub poly: MvPoly,
}

impl Condition {
    /// Convenience constructor.
    #[must_use]
    pub fn new(id: &str, description: &str, poly: MvPoly) -> Condition {
        Condition {
            id: id.to_string(),
            description: description.to_string(),
            poly,
        }
    }
}

/// A concrete rational configuration that satisfies every hypothesis, **violates**
/// a named non-degeneracy condition, and **falsifies** a conclusion.
///
/// This is the negative control, and it is mandatory for every condition the
/// certificate actually uses. A theorem whose degenerate case cannot be broken
/// did not need the condition, and [`certify`] would not have used it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DegenerateWitness {
    /// The [`Condition::id`] this configuration violates.
    pub condition_id: String,
    /// What the configuration is, in prose.
    pub description: String,
    /// Every coordinate variable of the problem, at an exact rational value.
    pub assignment: BTreeMap<String, Rational>,
}

/// A concrete rational configuration satisfying every hypothesis **and** every
/// non-degeneracy condition, at which the conclusions must hold.
///
/// Not part of the proof — the certificate settles all instances at once — but it
/// is an independent read on whether the polynomials say what their names claim.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenericWitness {
    /// What the configuration is, in prose.
    pub description: String,
    /// Every coordinate variable of the problem, at an exact rational value.
    pub assignment: BTreeMap<String, Rational>,
}

/// A geometry theorem stated as polynomials.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeometryProblem {
    /// Stable identifier; also the certificate file's stem.
    pub id: String,
    /// One-line human title.
    pub title: String,
    /// The theorem in prose, including its non-degeneracy conditions.
    pub statement: String,
    /// What each free coordinate variable denotes, e.g. `("ax", "A.x")`.
    pub coordinate_gloss: Vec<(String, String)>,
    /// Equations the configuration is assumed to satisfy.
    pub hypotheses: Vec<Constraint>,
    /// Polynomials the configuration is assumed **not** to annihilate.
    pub nondegeneracy: Vec<Condition>,
    /// Equations to be established.
    pub conclusions: Vec<Constraint>,
    /// Degenerate counterexamples, one per condition expected to be needed.
    pub degenerate_witnesses: Vec<DegenerateWitness>,
    /// Non-degenerate sanity configurations.
    pub generic_witnesses: Vec<GenericWitness>,
}

/// One saturating non-degeneracy condition, with the fresh variable that inverts
/// it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Saturation {
    /// The [`Condition::id`] being saturated by.
    pub condition_id: String,
    /// The condition's prose.
    pub description: String,
    /// The fresh inverse variable `z`.
    pub var: String,
    /// The condition polynomial `d`; the generator is `d·z − 1`.
    pub condition: MvPoly,
}

/// A conclusion together with its cofactors against the generator list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CertifiedConclusion {
    /// The conclusion's identifier.
    pub id: String,
    /// The conclusion's prose.
    pub description: String,
    /// The conclusion polynomial, which the identity reproduces.
    pub poly: MvPoly,
    /// One cofactor per generator, positionally aligned with
    /// [`GeometryCertificate::generators`].
    pub cofactors: Vec<MvPoly>,
}

/// The artifact: an identity per conclusion over an explicit generator list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeometryCertificate {
    /// Stable identifier.
    pub id: String,
    /// One-line human title.
    pub title: String,
    /// The theorem in prose.
    pub statement: String,
    /// What each coordinate variable denotes.
    pub coordinate_gloss: Vec<(String, String)>,
    /// The coordinate variables, sorted; saturation variables are **not** here.
    pub coordinates: Vec<String>,
    /// The hypotheses, in generator order.
    pub hypotheses: Vec<Constraint>,
    /// The saturating conditions actually used, in generator order after the
    /// hypotheses. Empty when the conclusion lies in the plain hypothesis ideal.
    pub saturations: Vec<Saturation>,
    /// `hypotheses` polynomials followed by `condition·var − 1` for each
    /// saturation. The cofactors are aligned with this list.
    pub generators: Vec<MvPoly>,
    /// The conclusions, each with its cofactors.
    pub conclusions: Vec<CertifiedConclusion>,
    /// Degenerate counterexamples for the conditions used.
    pub degenerate_witnesses: Vec<DegenerateWitness>,
    /// Non-degenerate sanity configurations.
    pub generic_witnesses: Vec<GenericWitness>,
}

/// The result of attempting to certify a [`GeometryProblem`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProofOutcome {
    /// An identity per conclusion, over the smallest condition subset found.
    Certified(Box<GeometryCertificate>),
    /// Every subset of the stated conditions was tried and at least one
    /// conclusion still had a nonzero remainder. Nothing is claimed: the theorem
    /// may need a condition that was not stated, or may be false.
    NotInSaturatedIdeal {
        /// The identifier of a conclusion that did not reduce to zero, using the
        /// full condition set.
        conclusion_id: String,
        /// Its nonzero remainder modulo the full generator set.
        remainder: MvPoly,
    },
    /// Nothing is claimed, with the reason recorded — see [`GeometryDecline`].
    Declined(GeometryDecline),
}

/// Why [`certify`] produced no certificate.
///
/// The distinction that matters most here is inside
/// [`GeometryDecline::Reduction`]: a tripped ceiling is a statement about the
/// budget and an overflow is a statement about `i128`, and a frontier theorem
/// that "declines" is uninterpretable until they are told apart.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GeometryDecline {
    /// The cofactor-tracked reduction stopped; the inner reason says whether a
    /// ceiling tripped or the exact arithmetic left the `i128` range.
    Reduction(DeclineReason),
    /// More non-degeneracy conditions than the subset enumeration admits (the
    /// power set of more than 16 conditions is not searched).
    TooManyConditions,
    /// A stated [`DegenerateWitness`] did not in fact break the theorem, so the
    /// certificate's negative control would have been decorative. This is a
    /// refusal, not a resource limit.
    UnverifiedWitness,
    /// [`certify_by_linear_elimination`] cleared the unknowns, but the
    /// determinant it multiplied through by is not a product of the *stated*
    /// non-degeneracy conditions, so there is no way to divide it back out inside
    /// the original generator list.
    ///
    /// Not a resource limit either: it says the theorem needs a side condition
    /// nobody wrote down, or that the elimination picked a decomposition whose
    /// determinant is not the geometric one. Both are worth seeing rather than
    /// timing out over.
    UndividableMultiplier,
}

/// The prefix of the fresh inverse variables introduced by saturation.
///
/// Uppercase deliberately: `'Z' < 'a'` as bytes, so under `lex` — with the
/// alphabetically-*first* variable most significant — the inverse variables rank
/// above every coordinate and `Buchberger`'s algorithm eliminates them first.
/// [`geometry_limits`] now defaults to `grevlex`, where the name only breaks ties
/// between equal-degree monomials and the effect is smaller. Either way this is a
/// performance choice: ideal membership does not depend on the order, which is
/// exactly why the order was safe to change.
pub const INVERSE_PREFIX: &str = "Zinv";

/// Ceilings sized for the coordinate systems classical plane theorems produce.
///
/// Calibrated against the committed corpus (release build, 2026-08-15): the most
/// expensive reduction that *succeeds* is `rhombus-diagonals-perpendicular` at
/// 21 s, and the most expensive that correctly reports a nonzero remainder is its
/// own empty-condition attempt at 0.7 s. The ceilings leave that reduction real
/// headroom on every axis — see [`crate::geometry_corpus::corpus`] — while
/// staying small enough that a theorem outside this route's reach declines in
/// minutes rather than never; [`crate::geometry_corpus::frontier`] has the one
/// that does.
///
/// # Why the order is `DegRevLex`
///
/// `lex` is the best order for *elimination* and the worst for computing a basis,
/// and ideal membership needs no elimination — so the theory says `grevlex`, and
/// the theory was checked rather than quoted. Two measurements settled it, both
/// reproducible with
/// `cargo run -p axeyum-cas --release --example geometry_order_audit`:
///
/// - **The order cannot move a condition set here.** The audit runs *every*
///   condition subset of every corpus theorem under both orders, and under both
///   orders every subset is **decided** — `in ideal` or `not in ideal`, never
///   declined. `certify` reports the smallest subset that succeeds, and
///   "succeeds" is budget-relative only when some smaller subset declines; with
///   every subset decided, the reported set is smallest *absolutely*, and no
///   change of order can move it. That mattered because those conditions are
///   hypotheses in the fact ledger's `formal.statement`: a silent move would have
///   changed what six proved facts claim.
/// - **The certificates are byte-identical.** All six artifacts that predate the
///   switch re-serialize identically under `grevlex` — the emitter reported *6
///   unchanged, 1 written*, the one being the newly reachable rhombus. The switch
///   changed no evidence at all, only the cost of producing it: 1.2–2.4× faster
///   on the six theorems both orders certify.
///
/// What the switch *did* change is reach: `rhombus-diagonals-perpendicular`
/// declined under `lex` after 287.8 s on the `ReductionSteps` ceiling and
/// certifies under `grevlex` in 21 s. It is in the corpus because of this line.
#[must_use]
pub fn geometry_limits() -> Limits {
    Limits {
        reduction_steps: 50_000,
        pair_iterations: 2_000,
        basis_size: 200,
        poly_terms: 8_000,
        order: MonomialOrder::DegRevLex,
    }
}

/// Certify a geometry theorem, using as **few** non-degeneracy conditions as
/// possible.
///
/// Subsets of `problem.nondegeneracy` are tried in order of increasing size (and,
/// within a size, in ascending index order), so the reported condition set is
/// smallest by cardinality among the subsets the budget could decide, and it is
/// deterministic. The empty subset is tried first: a theorem that is an outright
/// ideal identity is reported as needing nothing, which is a materially stronger
/// statement and one this module refuses to obscure.
///
/// A subset that [declines](CofactorOutcome::Declined) is skipped, so in
/// principle a theorem could certify with more conditions than it strictly needs.
/// That direction is conservative — a certificate using a condition it did not
/// need proves a *weaker* theorem — and the identity is checked independently
/// either way. The dangerous direction, claiming no condition is needed when one
/// is, cannot arise: it would require the empty-subset reduction to produce an
/// identity that the checker then re-derives.
///
/// Every [`DegenerateWitness`] naming a condition that ended up **unused** is
/// dropped from the certificate, and every witness naming a used condition is
/// verified before the certificate is returned; a witness that does not in fact
/// break the theorem makes this return
/// [`GeometryDecline::UnverifiedWitness`] rather than
/// emitting an artifact whose negative control is decorative.
#[must_use]
pub fn certify(problem: &GeometryProblem, limits: Limits) -> ProofOutcome {
    let count = problem.nondegeneracy.len();
    if count > 16 {
        return ProofOutcome::Declined(GeometryDecline::TooManyConditions);
    }
    let targets: Vec<MvPoly> = problem
        .conclusions
        .iter()
        .map(|conclusion| conclusion.poly.clone())
        .collect();

    let mut subsets: Vec<Vec<usize>> = (0u32..(1u32 << count))
        .map(|mask| {
            (0..count)
                .filter(|index| mask & (1 << index) != 0)
                .collect::<Vec<usize>>()
        })
        .collect();
    subsets.sort_by(|left, right| left.len().cmp(&right.len()).then_with(|| left.cmp(right)));

    // The outcome of the LAST subset tried, which is the full condition set;
    // that is the informative diagnostic when nothing certifies.
    let mut last_failure =
        ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));

    for subset in &subsets {
        let Some((saturations, generators)) = build_generators(problem, subset) else {
            // Overflow while building a saturation generator. Skip this subset
            // rather than dropping the condition, which would prove a stronger
            // statement than the input allows.
            last_failure =
                ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));
            continue;
        };
        let outcomes = reduce_many_with_cofactors(&generators, &targets, limits);
        let mut cofactor_sets = Vec::with_capacity(targets.len());
        let mut all_zero = true;
        for (conclusion, outcome) in problem.conclusions.iter().zip(outcomes.iter()) {
            match outcome {
                CofactorOutcome::Reduced {
                    cofactors,
                    remainder,
                } => {
                    if remainder.is_zero() {
                        cofactor_sets.push(cofactors.clone());
                    } else {
                        all_zero = false;
                        last_failure = ProofOutcome::NotInSaturatedIdeal {
                            conclusion_id: conclusion.id.clone(),
                            remainder: remainder.clone(),
                        };
                        break;
                    }
                }
                CofactorOutcome::Declined(reason) => {
                    all_zero = false;
                    last_failure = ProofOutcome::Declined(GeometryDecline::Reduction(*reason));
                    break;
                }
            }
        }
        if !all_zero {
            continue;
        }
        let certificate = assemble(problem, saturations, generators, cofactor_sets);
        return match verify_witnesses(problem, &certificate) {
            Ok(certificate) => ProofOutcome::Certified(Box::new(certificate)),
            Err(()) => ProofOutcome::Declined(GeometryDecline::UnverifiedWitness),
        };
    }

    last_failure
}

/// The largest power of a non-degeneracy condition
/// [`certify_by_linear_elimination`] will divide out of a multiplier.
///
/// A ceiling rather than a natural bound: dividing by a condition polynomial
/// strictly lowers the multiplier's degree, so the loop terminates on its own for
/// any non-constant condition. This stops a constant one from spinning.
const MAX_INVERSE_POWER: u32 = 32;

/// Certify a geometry theorem by **linear elimination** instead of by Gröbner
/// search, keeping the certificate in the original generators.
///
/// # Why this route exists
///
/// Classical constructions determine their points by *linear* systems: the
/// circumcentre is the intersection of two perpendicular bisectors, the
/// orthocentre of two altitudes, and each of those is one linear equation per
/// coordinate over `ℚ[vertex coordinates]`. Handing those hypotheses to
/// `Buchberger`'s algorithm asks it to rediscover Cramer's rule by monomial
/// reduction, which for `euler-line` it does not manage: the `geometry-frontier`
/// lane measured the basis still growing after 65 S-pairs with 528 queued and the
/// backlog tripling per doubling.
///
/// [`crate::linear_elim`] does the solve directly and returns
///
/// ```text
/// multiplier · conclusion  =  residue  +  Σᵢ uᵢ · hypothesisᵢ
/// ```
///
/// where `multiplier` is a product of the systems' determinants.
///
/// # How the certificate stays in the original generators
///
/// Nothing here changes the generator list: it is the hypotheses followed by
/// `d·z − 1` per condition, exactly as [`certify`] builds it, and the artifact is
/// the same [`GeometryCertificate`] checked by the same
/// [`crate::geometry_check::check_certificate`], which shares no code with either
/// route. The elimination is *untrusted search* for the cofactor vector — the
/// adjugate identity `adj(M)·(M·u + k) = det(M)·u + adj(M)·k` expresses
/// `det(M)·uⱼ` as a polynomial free of the unknowns plus a combination of the
/// **original** rows, so substituting it into the conclusion produces cofactors
/// against those rows and nothing else.
///
/// The `multiplier` is then divided back out **inside the ideal**, not
/// symbolically. For a condition `d` with `dᴺ` dividing the multiplier, the
/// Rabinowitsch generator `g = d·z − 1` gives `(d·z)ᴺ = (1 + g)ᴺ`, hence
///
/// ```text
/// 1  =  zᴺ·dᴺ  −  g·Σ_{i=1..N} C(N,i)·g^{i−1}
/// ```
///
/// and multiplying the elimination identity by `zᴺ` and subtracting yields
/// cofactors for the conclusion itself. For `N = 1` this collapses to the
/// familiar shape the search route produces, where the saturation generator's
/// cofactor is minus the conclusion; `euler-line` has `N = 2` and gets
/// `−conclusion·(1 + d·z)`.
///
/// If the multiplier is **not** a product of the stated conditions (times a
/// nonzero rational), this returns
/// [`GeometryDecline::UndividableMultiplier`] rather than inventing a condition.
///
/// # Minimality
///
/// Condition subsets are tried smallest-first, exactly as in [`certify`]. Here
/// every subset test is *decided* — factoring a multiplier by exact division
/// always terminates and always answers — so the reported set is smallest among
/// the subsets this route can use. Whether it is smallest **absolutely** is a
/// separate question about ideal membership, and it is answered by the degenerate
/// counterexample: a configuration satisfying every hypothesis, keeping every
/// condition of a subset nonzero, and falsifying the conclusion proves that
/// subset insufficient outright, with no budget in the argument at all.
///
/// # The handover
///
/// `handover` bounds the general ideal-membership work spent on whatever the
/// elimination could **not** remove. `None` refuses it outright: the elimination
/// must settle the conclusion by itself, which makes this route cost
/// microseconds and never inherit the cost it exists to avoid. `Some(limits)`
/// lets the residue — free of the eliminated unknowns, so a materially smaller
/// question — go to [`reduce_many_with_cofactors`], which is what a theorem that
/// is only *partly* linear needs.
#[must_use]
pub fn certify_by_linear_elimination(
    problem: &GeometryProblem,
    handover: Option<Limits>,
) -> ProofOutcome {
    let count = problem.nondegeneracy.len();
    if count > 16 {
        return ProofOutcome::Declined(GeometryDecline::TooManyConditions);
    }
    let mut subsets: Vec<Vec<usize>> = (0u32..(1u32 << count))
        .map(|mask| {
            (0..count)
                .filter(|index| mask & (1 << index) != 0)
                .collect::<Vec<usize>>()
        })
        .collect();
    subsets.sort_by(|left, right| left.len().cmp(&right.len()).then_with(|| left.cmp(right)));

    let hypotheses: Vec<MvPoly> = problem
        .hypotheses
        .iter()
        .map(|hypothesis| hypothesis.poly.clone())
        .collect();

    let mut last_failure = ProofOutcome::Declined(GeometryDecline::UndividableMultiplier);

    for subset in &subsets {
        let Some((saturations, generators)) = build_generators(problem, subset) else {
            last_failure =
                ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));
            continue;
        };
        let mut cofactor_sets = Vec::with_capacity(problem.conclusions.len());
        let mut settled = true;
        for conclusion in &problem.conclusions {
            match linear_cofactors(&hypotheses, &generators, &saturations, conclusion, handover) {
                Ok(cofactors) => cofactor_sets.push(cofactors),
                Err(outcome) => {
                    last_failure = outcome;
                    settled = false;
                    break;
                }
            }
        }
        if !settled {
            continue;
        }
        // Every saturation must carry a nonzero cofactor somewhere, or the
        // certificate advertises a weaker theorem than it proved and the
        // independent checker rejects it. Smallest-first ordering makes this
        // unreachable for a single condition, but not for two.
        let all_used = saturations.iter().enumerate().all(|(slot, _)| {
            cofactor_sets
                .iter()
                .any(|cofactors| !cofactors[problem.hypotheses.len() + slot].is_zero())
        });
        if !all_used {
            last_failure = ProofOutcome::Declined(GeometryDecline::UndividableMultiplier);
            continue;
        }
        let certificate = assemble(problem, saturations, generators, cofactor_sets);
        return match verify_witnesses(problem, &certificate) {
            Ok(certificate) => ProofOutcome::Certified(Box::new(certificate)),
            Err(()) => ProofOutcome::Declined(GeometryDecline::UnverifiedWitness),
        };
    }

    last_failure
}

/// Certify by whichever route reaches the theorem: linear elimination first,
/// then the Gröbner search.
///
/// # Why that order, and why it does not disturb anything
///
/// The linear route is tried first because it is the *cheap* one — with no
/// handover it is pure adjugate arithmetic, microseconds, and it either settles
/// the conclusion outright or gets out of the way. The Gröbner route is second
/// because it is the general one. Trying the expensive route first would mean
/// `euler-line` never reaches the cheap one at all: its Gröbner reduction does
/// not return inside any budget anyone has been willing to wait for.
///
/// The order is safe for the same reason the `grevlex` switch was, and it was
/// checked the same way rather than argued: on the seven theorems that predate
/// this route, the linear pass declines on six (its multiplier is not a product
/// of the stated conditions) and produces the *identical* empty certificate on
/// Varignon, so `emit_geometry_certificates` reports them all unchanged, byte for
/// byte. What the order changes is reach, not evidence.
///
/// The one thing it can change is a **condition set**, and that has to be said
/// out loud because condition sets are hypotheses in the fact ledger. The linear
/// route's multiplier is an artifact of the decomposition it chose, so it may
/// need to invert a condition the Gröbner route would not have used — a *weaker*
/// theorem, conservative in the safe direction, and detectable: the degenerate
/// counterexample in the certificate decides whether the condition is genuinely
/// required, with no budget in the argument (see
/// [`certify_by_linear_elimination`]).
#[must_use]
pub fn certify_any_route(problem: &GeometryProblem, limits: Limits) -> ProofOutcome {
    match certify_by_linear_elimination(problem, None) {
        certified @ ProofOutcome::Certified(_) => certified,
        _ => certify(problem, limits),
    }
}

/// The cofactor vector for one conclusion under one condition subset, or the
/// outcome that explains why there is none.
fn linear_cofactors(
    hypotheses: &[MvPoly],
    generators: &[MvPoly],
    saturations: &[Saturation],
    conclusion: &Constraint,
    handover: Option<Limits>,
) -> Result<Vec<MvPoly>, ProofOutcome> {
    let overflow = || ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));
    let Some(elimination) = eliminate(hypotheses, &conclusion.poly) else {
        return Err(overflow());
    };

    let mut cofactors = vec![MvPoly::zero(); generators.len()];
    for (slot, cofactor) in elimination.cofactors.iter().enumerate() {
        cofactors[slot] = cofactor.clone();
    }

    // What linear algebra could not remove goes to the general route, over a
    // system that is now free of the eliminated unknowns. For `euler-line` the
    // residue is zero and this never runs.
    if !elimination.residue.is_zero() {
        // A zero residue is short-circuited rather than reduced, and that is not
        // bookkeeping: reducing even the zero polynomial computes a Gröbner basis
        // of the generators, which is exactly the divergent computation this route
        // exists to avoid.
        let Some(limits) = handover else {
            return Err(ProofOutcome::NotInSaturatedIdeal {
                conclusion_id: conclusion.id.clone(),
                remainder: elimination.residue.clone(),
            });
        };
        let outcomes = reduce_many_with_cofactors(
            generators,
            std::slice::from_ref(&elimination.residue),
            limits,
        );
        match &outcomes[0] {
            CofactorOutcome::Reduced {
                cofactors: extra,
                remainder,
            } => {
                if !remainder.is_zero() {
                    return Err(ProofOutcome::NotInSaturatedIdeal {
                        conclusion_id: conclusion.id.clone(),
                        remainder: remainder.clone(),
                    });
                }
                for (slot, share) in extra.iter().enumerate() {
                    let Some(sum) = cofactors[slot].add(share) else {
                        return Err(overflow());
                    };
                    cofactors[slot] = sum;
                }
            }
            CofactorOutcome::Declined(reason) => {
                return Err(ProofOutcome::Declined(GeometryDecline::Reduction(*reason)));
            }
        }
    }

    match invert_multiplier(
        &conclusion.poly,
        &elimination.multiplier,
        saturations,
        hypotheses.len(),
        cofactors,
    ) {
        Some(cofactors) => Ok(cofactors),
        None => Err(ProofOutcome::Declined(
            GeometryDecline::UndividableMultiplier,
        )),
    }
}

/// Turn `multiplier · conclusion = Σ cofactorsᵢ·generatorᵢ` into
/// `conclusion = Σ cofactorsᵢ′·generatorᵢ`, using the Rabinowitsch generators as
/// the inverses they are.
///
/// `None` when the multiplier does not factor into the stated conditions and a
/// nonzero rational — which is a statement about the theorem, not about a budget.
fn invert_multiplier(
    conclusion: &MvPoly,
    multiplier: &MvPoly,
    saturations: &[Saturation],
    hypotheses: usize,
    mut cofactors: Vec<MvPoly>,
) -> Option<Vec<MvPoly>> {
    let one = MvPoly::constant(Rational::integer(1));
    let mut remaining = multiplier.clone();
    for (slot, saturation) in saturations.iter().enumerate() {
        if saturation.condition.total_degree() == 0 {
            continue;
        }
        let mut power = 0u32;
        while power < MAX_INVERSE_POWER {
            match remaining.exact_div(&saturation.condition) {
                Some(quotient) => {
                    remaining = quotient;
                    power += 1;
                }
                None => break,
            }
        }
        if power == 0 {
            continue;
        }
        let inverse = MvPoly::var(&saturation.var);
        let scale = inverse.pow(power)?;
        for cofactor in &mut cofactors {
            *cofactor = cofactor.mul(&scale)?;
        }
        // `1 = zᴺ·dᴺ − g·Σ_{i=1..N} C(N,i)·g^{i−1}` with `g = d·z − 1`.
        let generator = saturation.condition.mul(&inverse)?.sub(&one)?;
        let mut series = MvPoly::zero();
        let mut power_of_generator = one.clone();
        for index in 1..=power {
            let coefficient = binomial(power, index)?;
            series = series
                .add(&power_of_generator.mul(&MvPoly::constant(Rational::integer(coefficient)))?)?;
            if index < power {
                power_of_generator = power_of_generator.mul(&generator)?;
            }
        }
        let addend = remaining.mul(conclusion)?.mul(&series)?.neg()?;
        let index = hypotheses + slot;
        cofactors[index] = cofactors[index].add(&addend)?;
    }

    if remaining.total_degree() > 0 {
        return None;
    }
    let leftover = remaining.evaluate(&BTreeMap::new())?;
    if leftover.is_zero() {
        return None;
    }
    let reciprocal = MvPoly::constant(Rational::integer(1).checked_div(leftover)?);
    for cofactor in &mut cofactors {
        *cofactor = cofactor.mul(&reciprocal)?;
    }
    Some(cofactors)
}

/// `C(n, k)` in `i128`, `None` on overflow.
fn binomial(n: u32, k: u32) -> Option<i128> {
    let k = k.min(n.checked_sub(k)?);
    let mut result: i128 = 1;
    for step in 0..k {
        result = result.checked_mul(i128::from(n - step))?;
        result = result.checked_div(i128::from(step) + 1)?;
    }
    Some(result)
}

/// Generators for one condition subset: the hypotheses, then `d·z − 1` per
/// condition, in the subset's ascending index order. `None` on coefficient
/// overflow while forming a saturation generator.
fn build_generators(
    problem: &GeometryProblem,
    subset: &[usize],
) -> Option<(Vec<Saturation>, Vec<MvPoly>)> {
    let mut generators: Vec<MvPoly> = problem
        .hypotheses
        .iter()
        .map(|hypothesis| hypothesis.poly.clone())
        .collect();
    let mut saturations = Vec::with_capacity(subset.len());
    for (slot, &index) in subset.iter().enumerate() {
        let condition = &problem.nondegeneracy[index];
        let var = format!("{INVERSE_PREFIX}{slot}");
        let generator = condition
            .poly
            .mul(&MvPoly::var(&var))
            .and_then(|product| product.sub(&MvPoly::constant(Rational::integer(1))))?;
        generators.push(generator);
        saturations.push(Saturation {
            condition_id: condition.id.clone(),
            description: condition.description.clone(),
            var,
            condition: condition.poly.clone(),
        });
    }
    Some((saturations, generators))
}

fn assemble(
    problem: &GeometryProblem,
    saturations: Vec<Saturation>,
    generators: Vec<MvPoly>,
    cofactor_sets: Vec<Vec<MvPoly>>,
) -> GeometryCertificate {
    let used: BTreeSet<String> = saturations
        .iter()
        .map(|saturation| saturation.condition_id.clone())
        .collect();
    let conclusions = problem
        .conclusions
        .iter()
        .zip(cofactor_sets)
        .map(|(conclusion, cofactors)| CertifiedConclusion {
            id: conclusion.id.clone(),
            description: conclusion.description.clone(),
            poly: conclusion.poly.clone(),
            cofactors,
        })
        .collect();
    let mut coordinates: BTreeSet<String> = BTreeSet::new();
    for constraint in problem.hypotheses.iter().chain(problem.conclusions.iter()) {
        coordinates.extend(constraint.poly.variables());
    }
    for condition in &problem.nondegeneracy {
        coordinates.extend(condition.poly.variables());
    }
    GeometryCertificate {
        id: problem.id.clone(),
        title: problem.title.clone(),
        statement: problem.statement.clone(),
        coordinate_gloss: problem.coordinate_gloss.clone(),
        coordinates: coordinates.into_iter().collect(),
        hypotheses: problem.hypotheses.clone(),
        saturations,
        generators,
        conclusions,
        degenerate_witnesses: problem
            .degenerate_witnesses
            .iter()
            .filter(|witness| used.contains(witness.condition_id.as_str()))
            .cloned()
            .collect(),
        generic_witnesses: problem.generic_witnesses.clone(),
    }
}

/// Refuse a certificate whose negative controls do not actually break the
/// theorem, or whose generic witnesses do not satisfy it.
fn verify_witnesses(
    problem: &GeometryProblem,
    certificate: &GeometryCertificate,
) -> Result<GeometryCertificate, ()> {
    for saturation in &certificate.saturations {
        if !certificate
            .degenerate_witnesses
            .iter()
            .any(|witness| witness.condition_id == saturation.condition_id)
        {
            return Err(());
        }
    }
    for witness in &certificate.degenerate_witnesses {
        let Some(condition) = problem
            .nondegeneracy
            .iter()
            .find(|condition| condition.id == witness.condition_id)
        else {
            return Err(());
        };
        for hypothesis in &problem.hypotheses {
            match hypothesis.poly.evaluate(&witness.assignment) {
                Some(value) if value.is_zero() => {}
                _ => return Err(()),
            }
        }
        match condition.poly.evaluate(&witness.assignment) {
            Some(value) if value.is_zero() => {}
            _ => return Err(()),
        }
        let broken = problem.conclusions.iter().any(|conclusion| {
            matches!(conclusion.poly.evaluate(&witness.assignment), Some(value) if !value.is_zero())
        });
        if !broken {
            return Err(());
        }
    }
    for witness in &problem.generic_witnesses {
        for hypothesis in &problem.hypotheses {
            match hypothesis.poly.evaluate(&witness.assignment) {
                Some(value) if value.is_zero() => {}
                _ => return Err(()),
            }
        }
        for saturation in &certificate.saturations {
            match saturation.condition.evaluate(&witness.assignment) {
                Some(value) if !value.is_zero() => {}
                _ => return Err(()),
            }
        }
        for conclusion in &problem.conclusions {
            match conclusion.poly.evaluate(&witness.assignment) {
                Some(value) if value.is_zero() => {}
                _ => return Err(()),
            }
        }
    }
    Ok(certificate.clone())
}

#[cfg(test)]
mod tests {
    use super::{
        Condition, Constraint, DegenerateWitness, GenericWitness, GeometryCertificate,
        GeometryDecline, GeometryProblem, ProofOutcome, Pt, certify, certify_any_route,
        certify_by_linear_elimination, collinear, geometry_limits, midpoint, parallel,
        perpendicular,
    };
    use crate::mvpoly::MvPoly;
    use axeyum_ir::Rational;
    use std::collections::BTreeMap;

    /// Re-expand `Σ uᵢ·gᵢ` and compare it with the conclusion, without any of the
    /// machinery that produced the cofactors. This is what the independent
    /// checker does; a route that cannot pass it has produced nothing.
    fn identity_recombines(certificate: &GeometryCertificate) {
        for conclusion in &certificate.conclusions {
            let mut combined = MvPoly::zero();
            for (cofactor, generator) in conclusion.cofactors.iter().zip(&certificate.generators) {
                combined = combined
                    .add(&cofactor.mul(generator).expect("product"))
                    .expect("sum");
            }
            assert_eq!(
                combined, conclusion.poly,
                "the identity must reproduce {}",
                conclusion.id
            );
        }
    }

    fn assign(pairs: &[(&str, i128)]) -> BTreeMap<String, Rational> {
        pairs
            .iter()
            .map(|(name, value)| ((*name).to_string(), Rational::integer(*value)))
            .collect()
    }

    fn quadrilateral() -> [Pt; 4] {
        [Pt::free("a"), Pt::free("b"), Pt::free("c"), Pt::free("d")]
    }

    fn parallelogram_hypotheses(points: &[Pt; 4]) -> Vec<Constraint> {
        vec![
            Constraint::new(
                "ab-parallel-dc",
                "AB ∥ DC",
                parallel(&points[0], &points[1], &points[3], &points[2]).expect("polynomial"),
            ),
            Constraint::new(
                "bc-parallel-ad",
                "BC ∥ AD",
                parallel(&points[1], &points[2], &points[0], &points[3]).expect("polynomial"),
            ),
        ]
    }

    fn flat_condition(points: &[Pt; 4]) -> Condition {
        Condition::new(
            "abd-not-collinear",
            "A, B, D are not collinear",
            collinear(&points[0], &points[1], &points[3]).expect("polynomial"),
        )
    }

    /// The simplest theorem with a genuine side condition: a parallelogram's
    /// diagonals bisect each other, which is FALSE when the four points are
    /// collinear.
    #[test]
    fn the_parallelogram_needs_exactly_one_condition() {
        let points = quadrilateral();
        let diagonal_ac = midpoint(&points[0], &points[2]).expect("midpoint");
        let diagonal_bd = midpoint(&points[1], &points[3]).expect("midpoint");
        let problem = GeometryProblem {
            id: "parallelogram-diagonals-bisect".into(),
            title: "diagonals of a parallelogram bisect each other".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![
                Constraint::new(
                    "midpoints-agree-x",
                    "the diagonals share an abscissa",
                    diagonal_ac.x.sub(&diagonal_bd.x).expect("difference"),
                ),
                Constraint::new(
                    "midpoints-agree-y",
                    "the diagonals share an ordinate",
                    diagonal_ac.y.sub(&diagonal_bd.y).expect("difference"),
                ),
            ],
            degenerate_witnesses: vec![DegenerateWitness {
                condition_id: "abd-not-collinear".into(),
                description: "four collinear points".into(),
                assignment: assign(&[
                    ("ax", 0),
                    ("ay", 0),
                    ("bx", 1),
                    ("by", 0),
                    ("cx", 2),
                    ("cy", 0),
                    ("dx", 5),
                    ("dy", 0),
                ]),
            }],
            generic_witnesses: vec![GenericWitness {
                description: "the unit square".into(),
                assignment: assign(&[
                    ("ax", 0),
                    ("ay", 0),
                    ("bx", 1),
                    ("by", 0),
                    ("cx", 1),
                    ("cy", 1),
                    ("dx", 0),
                    ("dy", 1),
                ]),
            }],
        };
        let ProofOutcome::Certified(certificate) = certify(&problem, geometry_limits()) else {
            panic!("the parallelogram must certify");
        };
        assert_eq!(
            certificate.saturations.len(),
            1,
            "the collinearity condition is genuinely needed"
        );
        assert_eq!(certificate.generators.len(), 3);
        for conclusion in &certificate.conclusions {
            let mut combined = MvPoly::zero();
            for (cofactor, generator) in conclusion.cofactors.iter().zip(&certificate.generators) {
                combined = combined
                    .add(&cofactor.mul(generator).expect("product"))
                    .expect("sum");
            }
            assert_eq!(
                combined, conclusion.poly,
                "the identity must reproduce {}",
                conclusion.id
            );
        }
    }

    /// A degenerate witness that does not actually break the theorem must not
    /// produce a certificate: the negative control is load-bearing, not
    /// decorative.
    #[test]
    fn a_counterexample_that_does_not_break_the_theorem_blocks_the_certificate() {
        let points = quadrilateral();
        let diagonal_ac = midpoint(&points[0], &points[2]).expect("midpoint");
        let diagonal_bd = midpoint(&points[1], &points[3]).expect("midpoint");
        let problem = GeometryProblem {
            id: "parallelogram-diagonals-bisect".into(),
            title: "diagonals of a parallelogram bisect each other".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![Constraint::new(
                "midpoints-agree-x",
                "the diagonals share an abscissa",
                diagonal_ac.x.sub(&diagonal_bd.x).expect("difference"),
            )],
            // Collinear, so the condition IS violated, but the diagonals happen
            // to bisect each other here, so it is not a counterexample.
            degenerate_witnesses: vec![DegenerateWitness {
                condition_id: "abd-not-collinear".into(),
                description: "collinear but not a counterexample".into(),
                assignment: assign(&[
                    ("ax", 0),
                    ("ay", 0),
                    ("bx", 1),
                    ("by", 0),
                    ("cx", 2),
                    ("cy", 0),
                    ("dx", 1),
                    ("dy", 0),
                ]),
            }],
            generic_witnesses: Vec::new(),
        };
        assert_eq!(
            certify(&problem, geometry_limits()),
            ProofOutcome::Declined(GeometryDecline::UnverifiedWitness),
            "a decorative counterexample must block the certificate, and say why"
        );
    }

    /// Contrast: Varignon's parallelogram needs NO condition at all, because the
    /// conclusion is a polynomial identity with an empty generator list.
    #[test]
    fn varignon_needs_no_condition() {
        let points = quadrilateral();
        let mid_ab = midpoint(&points[0], &points[1]).expect("midpoint");
        let mid_bc = midpoint(&points[1], &points[2]).expect("midpoint");
        let mid_cd = midpoint(&points[2], &points[3]).expect("midpoint");
        let mid_da = midpoint(&points[3], &points[0]).expect("midpoint");
        let problem = GeometryProblem {
            id: "varignon".into(),
            title: "Varignon".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: Vec::new(),
            nondegeneracy: Vec::new(),
            conclusions: vec![Constraint::new(
                "pq-parallel-sr",
                "PQ ∥ SR",
                parallel(&mid_ab, &mid_bc, &mid_da, &mid_cd).expect("polynomial"),
            )],
            degenerate_witnesses: Vec::new(),
            generic_witnesses: Vec::new(),
        };
        let ProofOutcome::Certified(certificate) = certify(&problem, geometry_limits()) else {
            panic!("Varignon must certify");
        };
        assert!(certificate.saturations.is_empty());
        assert!(certificate.generators.is_empty());
        assert!(
            certificate.conclusions[0].poly.is_zero(),
            "Varignon's conclusion is the zero polynomial outright"
        );
    }

    /// A false "theorem" must not certify: the diagonals of a parallelogram are
    /// not in general perpendicular.
    #[test]
    fn a_false_conclusion_does_not_certify() {
        let points = quadrilateral();
        let problem = GeometryProblem {
            id: "false".into(),
            title: "false".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![Constraint::new(
                "diagonals-perpendicular",
                "AC ⟂ BD, which is false",
                perpendicular(&points[0], &points[2], &points[1], &points[3]).expect("polynomial"),
            )],
            degenerate_witnesses: Vec::new(),
            generic_witnesses: Vec::new(),
        };
        assert!(
            !matches!(
                certify(&problem, geometry_limits()),
                ProofOutcome::Certified(_)
            ),
            "a false conclusion must never certify"
        );
    }

    /// The theorem the linear route exists for. Two 2×2 systems, a zero residue,
    /// and an identity in the ORIGINAL generators — which is what makes it a
    /// certificate rather than a verdict.
    #[test]
    fn the_linear_route_certifies_euler_line() {
        let problem = crate::geometry_corpus::corpus()
            .into_iter()
            .find(|problem| problem.id == "euler-line")
            .expect("euler-line is in the corpus");
        let ProofOutcome::Certified(certificate) = certify_by_linear_elimination(&problem, None)
        else {
            panic!("the linear route must reach euler-line without any Gröbner handover");
        };
        assert_eq!(
            certificate.saturations.len(),
            1,
            "one condition: A, B, C not collinear"
        );
        assert_eq!(
            certificate.generators.len(),
            5,
            "four hypotheses plus d·z − 1"
        );
        for (index, hypothesis) in certificate.hypotheses.iter().enumerate() {
            assert_eq!(
                certificate.generators[index], hypothesis.poly,
                "generator {index} must be the stated hypothesis `{}` unchanged -- a route that \
                 substituted solved forms into the generator list would prove a different theorem",
                hypothesis.id
            );
        }
        identity_recombines(&certificate);
    }

    /// The signature Rabinowitsch shape, generalised to a squared multiplier.
    ///
    /// The Gröbner route's saturated certificates come out with the saturation
    /// generator's cofactor equal to **minus the conclusion**, which is the `N = 1`
    /// case of `1 = zᴺdᴺ − g·Σ C(N,i)g^{i−1}`. `euler-line`'s multiplier is
    /// `4·collinear(A,B,C)²`, so `N = 2` and the cofactor must be
    /// `−conclusion·(1 + d·z)`. Asserting the exact polynomial is what turns "the
    /// division works" into something that would fail loudly if the binomial
    /// series were off by a term.
    #[test]
    fn the_squared_multiplier_produces_the_expected_rabinowitsch_cofactor() {
        let problem = crate::geometry_corpus::corpus()
            .into_iter()
            .find(|problem| problem.id == "euler-line")
            .expect("euler-line is in the corpus");
        let ProofOutcome::Certified(certificate) = certify_by_linear_elimination(&problem, None)
        else {
            panic!("euler-line must certify");
        };
        let saturation = &certificate.saturations[0];
        let expected = certificate.conclusions[0]
            .poly
            .mul(
                &saturation
                    .condition
                    .mul(&MvPoly::var(&saturation.var))
                    .expect("d·z")
                    .add(&MvPoly::constant(Rational::integer(1)))
                    .expect("1 + d·z"),
            )
            .expect("product")
            .neg()
            .expect("negation");
        assert_eq!(
            certificate.conclusions[0].cofactors[certificate.hypotheses.len()],
            expected,
            "the saturation cofactor must be −conclusion·(1 + d·z)"
        );
    }

    /// A false conclusion must not certify on this route either, and the reason
    /// must not be a lucky decline: the elimination happily produces an identity
    /// for `multiplier · target`, and it is the *residue* that has to stay
    /// nonzero.
    #[test]
    fn the_linear_route_refuses_a_false_conclusion() {
        let points = quadrilateral();
        let problem = GeometryProblem {
            id: "false".into(),
            title: "false".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![Constraint::new(
                "diagonals-perpendicular",
                "AC ⟂ BD, which is false",
                perpendicular(&points[0], &points[2], &points[1], &points[3]).expect("polynomial"),
            )],
            degenerate_witnesses: Vec::new(),
            generic_witnesses: Vec::new(),
        };
        for handover in [None, Some(geometry_limits())] {
            assert!(
                !matches!(
                    certify_by_linear_elimination(&problem, handover),
                    ProofOutcome::Certified(_)
                ),
                "a false conclusion must never certify, handover = {}",
                handover.is_some()
            );
        }
    }

    /// A multiplier that is not a product of the **stated** conditions must
    /// decline, not invent one.
    ///
    /// This is the soundness-relevant half of the route. The elimination will
    /// cheerfully hand back `det·target = Σ uᵢhᵢ` for whatever determinant its
    /// decomposition produced; dividing that determinant out is only legitimate
    /// where it is nonzero, and the only place this module is allowed to get that
    /// permission is a condition the problem declares. Thales is the case in the
    /// corpus: the elimination clears its residue with a two-term multiplier, and
    /// that polynomial is nobody's declared condition.
    #[test]
    fn a_multiplier_outside_the_stated_conditions_declines() {
        let problem = crate::geometry_corpus::corpus()
            .into_iter()
            .find(|problem| problem.id == "thales-right-angle-in-semicircle")
            .expect("thales is in the corpus");
        assert_eq!(
            certify_by_linear_elimination(&problem, None),
            ProofOutcome::Declined(GeometryDecline::UndividableMultiplier),
            "the route must refuse to divide by a polynomial no condition licenses"
        );
        // And the theorem is nonetheless true and unconditional, which the
        // Gröbner route establishes — so the decline above is a limitation of the
        // route, not a statement about the theorem.
        let ProofOutcome::Certified(certificate) = certify(&problem, geometry_limits()) else {
            panic!("thales certifies on the general route");
        };
        assert!(certificate.saturations.is_empty());
    }

    /// `certify_any_route` must not disturb what the Gröbner route already
    /// proves. This is the assertion behind "7 unchanged, 1 written".
    #[test]
    fn the_route_selector_reproduces_the_groebner_certificate_exactly() {
        let mut compared = 0usize;
        for problem in crate::geometry_corpus::corpus() {
            // `euler-line` is the one the Gröbner route does not return on, so it
            // is excluded here by construction rather than by convenience.
            if problem.id == "euler-line" || problem.id == "rhombus-diagonals-perpendicular" {
                continue;
            }
            let combined = certify_any_route(&problem, geometry_limits());
            let direct = certify(&problem, geometry_limits());
            assert_eq!(
                combined, direct,
                "{}: the route selector changed an existing certificate",
                problem.id
            );
            compared += 1;
        }
        assert!(compared >= 5, "compared only {compared} theorems");
    }
}
