//! Coordinatised Euclidean geometry: theorems as ideal-membership questions,
//! settled by a **Nullstellensatz cofactor certificate**.
//!
//! [`crate::geometry`] decides positional predicates at *concrete* rational
//! coordinates. This module states them at **symbolic** coordinates: every point
//! is a pair of indeterminates, every predicate is a polynomial in
//! [`crate::mvpoly::MvPoly`] that vanishes exactly on the configurations
//! satisfying it. A theorem
//!
//! ```text
//! h₁ = 0, …, hₙ = 0   (hypotheses)      ⟹   c = 0   (conclusion)
//! ```
//!
//! then becomes the question "does `c` lie in the ideal generated by the `hᵢ`?",
//! and [`crate::groebner_cert`] answers it with an **identity**
//!
//! ```text
//! c = Σᵢ uᵢ · hᵢ
//! ```
//!
//! that a checker re-derives with polynomial addition and multiplication alone.
//! At any common zero of the hypotheses the right-hand side is `0`, so `c` is
//! `0` — regardless of how the `uᵢ` were found, and simultaneously for **every**
//! configuration. That is the whole proof.
//!
//! # Non-degeneracy is explicit, or the theorem is false
//!
//! Mechanised geometry's characteristic failure is a proof that silently holds
//! only away from degenerate configurations — the collinear "triangle", the
//! coincident vertices. Many classical theorems' conclusions are not in the plain
//! hypothesis ideal at all; they are in the **saturation** of that ideal by the
//! non-degeneracy conditions. So a condition `d ≠ 0` is admitted here only by
//! being *named* and turned into a generator via the Rabinowitsch trick: a fresh
//! variable `z` and the generator `d·z − 1`. The certificate then reads
//!
//! ```text
//! c = Σᵢ uᵢ · hᵢ + w · (d·z − 1)
//! ```
//!
//! and specialising `z := 1/d` — legitimate exactly when `d ≠ 0` — kills the last
//! term. The condition is therefore visible in the artifact rather than assumed
//! in prose, and [`certify`] reports the **smallest** set of conditions that makes
//! the reduction succeed, so a theorem that needs none says so.
//!
//! # What a certificate does and does not establish
//!
//! The identity is an identity in `ℚ[coordinates, z…]`, hence valid over every
//! field of characteristic zero. Two things it does **not** do:
//!
//! - It says nothing about configurations where a saturating `d` vanishes. Those
//!   are exactly where these theorems can be false, which is why
//!   [`DegenerateWitness`] exists and is checked.
//! - It does not certify that a polynomial *means* the geometric predicate it is
//!   named after. That link is the coordinatisation, and it is an assumption.

use std::collections::{BTreeMap, BTreeSet};

use axeyum_ir::Rational;

use crate::cofactor_ansatz::{AnsatzLimits, AnsatzOutcome, cofactors_by_ansatz};
use crate::groebner::MonomialOrder;
use crate::groebner_cert::{CofactorOutcome, DeclineReason, Limits, reduce_many_with_cofactors};
use crate::linear_elim::{LinearBlock, LinearElimination, detect_linear_blocks, eliminate_blocks};
use crate::mvpoly::MvPoly;

/// A point of the plane at symbolic coordinates.
///
/// The coordinates are arbitrary polynomials rather than bare variables so that
/// *constructed* points (a midpoint, a centroid) are ordinary points with no
/// extra variables and no extra hypotheses: the construction is carried out in
/// the coefficient field instead of being asserted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pt {
    /// The abscissa.
    pub x: MvPoly,
    /// The ordinate.
    pub y: MvPoly,
}

impl Pt {
    /// A point at two fresh indeterminates `<name>x` and `<name>y`.
    #[must_use]
    pub fn free(name: &str) -> Pt {
        Pt {
            x: MvPoly::var(&format!("{name}x")),
            y: MvPoly::var(&format!("{name}y")),
        }
    }

    /// A point at explicit rational coordinates.
    #[must_use]
    pub fn fixed(x: Rational, y: Rational) -> Pt {
        Pt {
            x: MvPoly::constant(x),
            y: MvPoly::constant(y),
        }
    }

    /// Componentwise difference, `None` on coefficient overflow.
    #[must_use]
    pub fn sub(&self, other: &Pt) -> Option<Pt> {
        Some(Pt {
            x: self.x.sub(&other.x)?,
            y: self.y.sub(&other.y)?,
        })
    }

    /// Componentwise sum, `None` on coefficient overflow.
    #[must_use]
    pub fn add(&self, other: &Pt) -> Option<Pt> {
        Some(Pt {
            x: self.x.add(&other.x)?,
            y: self.y.add(&other.y)?,
        })
    }

    /// Scale both coordinates by an exact rational.
    #[must_use]
    pub fn scale(&self, factor: Rational) -> Option<Pt> {
        let constant = MvPoly::constant(factor);
        Some(Pt {
            x: self.x.mul(&constant)?,
            y: self.y.mul(&constant)?,
        })
    }
}

/// The scalar cross product `first × second`. Zero exactly when the two vectors
/// are parallel.
#[must_use]
pub fn det(first: &Pt, second: &Pt) -> Option<MvPoly> {
    first.x.mul(&second.y)?.sub(&first.y.mul(&second.x)?)
}

/// The Euclidean inner product `first · second`. Zero exactly when the two
/// vectors are orthogonal.
#[must_use]
pub fn dot(first: &Pt, second: &Pt) -> Option<MvPoly> {
    first.x.mul(&second.x)?.add(&first.y.mul(&second.y)?)
}

/// `|AB|²`, the squared distance — a polynomial, unlike the distance itself.
#[must_use]
pub fn dist_sq(from: &Pt, to: &Pt) -> Option<MvPoly> {
    let delta = to.sub(from)?;
    dot(&delta, &delta)
}

/// `A`, `B`, `C` are collinear: the signed area of the triangle vanishes.
#[must_use]
pub fn collinear(first: &Pt, second: &Pt, third: &Pt) -> Option<MvPoly> {
    det(&second.sub(first)?, &third.sub(first)?)
}

/// Line `AB` is parallel to line `CD`.
#[must_use]
pub fn parallel(from: &Pt, to: &Pt, other_from: &Pt, other_to: &Pt) -> Option<MvPoly> {
    det(&to.sub(from)?, &other_to.sub(other_from)?)
}

/// Line `AB` is perpendicular to line `CD`.
#[must_use]
pub fn perpendicular(from: &Pt, to: &Pt, other_from: &Pt, other_to: &Pt) -> Option<MvPoly> {
    dot(&to.sub(from)?, &other_to.sub(other_from)?)
}

/// `|AB| = |CD|`, stated on squared distances so it stays polynomial.
#[must_use]
pub fn equidistant(from: &Pt, to: &Pt, other_from: &Pt, other_to: &Pt) -> Option<MvPoly> {
    dist_sq(from, to)?.sub(&dist_sq(other_from, other_to)?)
}

/// `A`, `B`, `C`, `D` lie on a common circle **or** on a common line.
///
/// The classical concyclicity determinant, with the fourth column of ones
/// eliminated by subtracting the first row:
///
/// ```text
/// | ax ay ax²+ay² 1 |          | bx−ax  by−ay  |B|²−|A|² |
/// | bx by bx²+by² 1 |  =  −det | cx−ax  cy−ay  |C|²−|A|² |
/// | cx cy cx²+cy² 1 |          | dx−ax  dy−ay  |D|²−|A|² |
/// | dx dy dx²+dy² 1 |
/// ```
///
/// Stated this way it needs **no centre and no radius variable**: the circle is
/// not constructed, only the coincidence is asserted, so a theorem about points
/// on a circle costs no extra unknowns and no extra hypotheses. The sign carried
/// by the row reduction is dropped — a polynomial and its negative have the same
/// zero set and generate the same ideal.
///
/// The "or on a common line" is not a wart to be conditioned away. A line is a
/// circle through the point at infinity, the determinant vanishes on both strata,
/// and a theorem that holds on the circle stratum and fails on the line stratum
/// would simply not certify against this hypothesis. Where the line stratum is
/// genuinely harmless the weaker hypothesis proves the stronger theorem.
#[must_use]
pub fn concyclic(first: &Pt, second: &Pt, third: &Pt, fourth: &Pt) -> Option<MvPoly> {
    let row = |point: &Pt| -> Option<[MvPoly; 3]> {
        let delta = point.sub(first)?;
        let lift = dot(point, point)?.sub(&dot(first, first)?)?;
        Some([delta.x, delta.y, lift])
    };
    let rows = [row(second)?, row(third)?, row(fourth)?];
    // Laplace along the first row of the 3x3, with exact rational coefficients.
    let minor = |skip: usize| -> Option<MvPoly> {
        let columns: Vec<usize> = (0..3).filter(|index| *index != skip).collect();
        rows[1][columns[0]]
            .mul(&rows[2][columns[1]])?
            .sub(&rows[1][columns[1]].mul(&rows[2][columns[0]])?)
    };
    let positive = rows[0][0]
        .mul(&minor(0)?)?
        .add(&rows[0][2].mul(&minor(2)?)?)?;
    positive.sub(&rows[0][1].mul(&minor(1)?)?)
}

/// The midpoint of `AB`, constructed rather than asserted.
#[must_use]
pub fn midpoint(from: &Pt, to: &Pt) -> Option<Pt> {
    from.add(to)?.scale(Rational::new(1, 2))
}

/// The centroid of `ABC`, constructed rather than asserted.
#[must_use]
pub fn centroid(first: &Pt, second: &Pt, third: &Pt) -> Option<Pt> {
    first.add(second)?.add(third)?.scale(Rational::new(1, 3))
}

/// `A = B` as two coordinate equations.
#[must_use]
pub fn same_point(first: &Pt, second: &Pt) -> Option<[MvPoly; 2]> {
    Some([first.x.sub(&second.x)?, first.y.sub(&second.y)?])
}

/// A named polynomial that a configuration must make **zero**: a hypothesis or a
/// conclusion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Constraint {
    /// Stable identifier, used in the serialised certificate.
    pub id: String,
    /// What the polynomial says geometrically. Prose, for a reader.
    pub description: String,
    /// The polynomial itself.
    pub poly: MvPoly,
}

impl Constraint {
    /// Convenience constructor.
    #[must_use]
    pub fn new(id: &str, description: &str, poly: MvPoly) -> Constraint {
        Constraint {
            id: id.to_string(),
            description: description.to_string(),
            poly,
        }
    }
}

/// A named polynomial that a configuration must make **nonzero**: a
/// non-degeneracy condition.
///
/// The same shape as [`Constraint`] and deliberately a distinct type — confusing
/// "must vanish" with "must not vanish" is precisely the mistake this module is
/// built to make impossible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Condition {
    /// Stable identifier, used in the serialised certificate.
    pub id: String,
    /// What the condition excludes, e.g. "A, B and D are not collinear".
    pub description: String,
    /// The polynomial required to be nonzero.
    pub poly: MvPoly,
}

impl Condition {
    /// Convenience constructor.
    #[must_use]
    pub fn new(id: &str, description: &str, poly: MvPoly) -> Condition {
        Condition {
            id: id.to_string(),
            description: description.to_string(),
            poly,
        }
    }
}

/// An exact element of `ℚ(i)`, the field a certificate's negative controls have
/// to live in once the theorem is one about characteristic zero.
///
/// # Why the rationals are not enough
///
/// A cofactor identity has rational coefficients, so it holds in **every**
/// `ℚ`-algebra — the theorem a certificate proves is a theorem of every field of
/// characteristic zero, `ℂ` included, and never merely of the real plane. Its
/// negative controls must therefore be able to live there too, or the ledger
/// tests a *different* theorem than the one it files.
///
/// The gap is not hypothetical and `simson-line` is where it opened. Its
/// conditions are `|BC|² ≠ 0` and friends, and over `ℝ` that is exactly `B ≠ C`,
/// so any single collapse leaves two side lines equal, two feet equal, and the
/// conclusion trivially true — over `ℝ` each condition is redundant. Over an
/// algebraically closed field it is not, because `x² + y²` has the isotropic
/// directions `(1, ±i)`: a nonzero vector can have zero square length, one foot
/// becomes free along an isotropic line while the other two stay pinned, and the
/// conclusion fails. The configuration that shows this has Gaussian coordinates
/// and no rational one can replace it, because over `ℝ` it does not exist.
///
/// So a witness carries an optional imaginary part, [`ProofOutcome::Certified`]
/// verifies it here, and the independent checker replays it. A witness with no
/// imaginary part is an ordinary rational one and serialises unchanged.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Gaussian {
    /// The real part.
    pub real: Rational,
    /// The coefficient of `i`.
    pub imaginary: Rational,
}

impl Gaussian {
    /// `a + b·i`.
    #[must_use]
    pub fn new(real: Rational, imaginary: Rational) -> Gaussian {
        Gaussian { real, imaginary }
    }

    /// A rational, embedded.
    #[must_use]
    pub fn rational(real: Rational) -> Gaussian {
        Gaussian {
            real,
            imaginary: Rational::zero(),
        }
    }

    /// Whether this is `0`. Both components must vanish; `ℚ(i)` is a field, so
    /// there are no nonzero elements of zero "size" to confuse this with.
    #[must_use]
    pub fn is_zero(&self) -> bool {
        self.real.is_zero() && self.imaginary.is_zero()
    }

    /// Exact sum, `None` on coefficient overflow.
    #[must_use]
    pub fn checked_add(self, other: Gaussian) -> Option<Gaussian> {
        Some(Gaussian {
            real: self.real.checked_add(other.real)?,
            imaginary: self.imaginary.checked_add(other.imaginary)?,
        })
    }

    /// Exact product `(a+bi)(c+di) = (ac−bd) + (ad+bc)i`, `None` on overflow.
    #[must_use]
    pub fn checked_mul(self, other: Gaussian) -> Option<Gaussian> {
        let real = self
            .real
            .checked_mul(other.real)?
            .checked_sub(self.imaginary.checked_mul(other.imaginary)?)?;
        let imaginary = self
            .real
            .checked_mul(other.imaginary)?
            .checked_add(self.imaginary.checked_mul(other.real)?)?;
        Some(Gaussian { real, imaginary })
    }
}

/// Evaluate a polynomial at a `ℚ(i)`-point.
///
/// The rational path stays [`MvPoly::evaluate`] — this is a second code path and
/// is deliberately not routed through the first, so a certificate whose witnesses
/// are all rational is checked by exactly the arithmetic it was before.
#[must_use]
pub fn evaluate_gaussian(poly: &MvPoly, point: &BTreeMap<String, Gaussian>) -> Option<Gaussian> {
    let mut total = Gaussian::rational(Rational::zero());
    for (monomial, coefficient) in poly.terms() {
        let mut value = Gaussian::rational(*coefficient);
        for (name, power) in monomial.powers() {
            let base = *point.get(name)?;
            for _ in 0..power {
                value = value.checked_mul(base)?;
            }
        }
        total = total.checked_add(value)?;
    }
    Some(total)
}

/// A concrete configuration that satisfies every hypothesis, **violates** a named
/// non-degeneracy condition, and **falsifies** a conclusion.
///
/// This is the negative control, and it is mandatory for every condition the
/// certificate actually uses. A theorem whose degenerate case cannot be broken
/// did not need the condition, and [`certify`] would not have used it.
///
/// Coordinates are rational by default and may carry an imaginary part; see
/// [`Gaussian`] for why the option has to exist, and
/// [`DegenerateWitness::point`] for how the two halves combine.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DegenerateWitness {
    /// The [`Condition::id`] this configuration violates.
    pub condition_id: String,
    /// What the configuration is, in prose.
    pub description: String,
    /// Every coordinate variable of the problem, at an exact rational value.
    pub assignment: BTreeMap<String, Rational>,
    /// The imaginary part of any coordinate that has one. Empty for a rational
    /// witness, which is the common case and the one that serialises unchanged.
    pub imaginary: BTreeMap<String, Rational>,
}

impl DegenerateWitness {
    /// A purely rational witness.
    #[must_use]
    pub fn rational(
        condition_id: &str,
        description: &str,
        assignment: BTreeMap<String, Rational>,
    ) -> DegenerateWitness {
        DegenerateWitness {
            condition_id: condition_id.to_string(),
            description: description.to_string(),
            assignment,
            imaginary: BTreeMap::new(),
        }
    }

    /// Whether any coordinate has a nonzero imaginary part.
    #[must_use]
    pub fn is_gaussian(&self) -> bool {
        self.imaginary.values().any(|value| !value.is_zero())
    }

    /// The configuration as a `ℚ(i)`-point, `None` if the two halves disagree
    /// about which variables exist.
    ///
    /// An imaginary part naming a variable the real part does not is rejected
    /// rather than defaulted, because a typo there would silently move the
    /// witness to a different point and the checker would confirm the wrong one.
    #[must_use]
    pub fn point(&self) -> Option<BTreeMap<String, Gaussian>> {
        if self
            .imaginary
            .keys()
            .any(|name| !self.assignment.contains_key(name))
        {
            return None;
        }
        Some(
            self.assignment
                .iter()
                .map(|(name, real)| {
                    let imaginary = self
                        .imaginary
                        .get(name)
                        .copied()
                        .unwrap_or_else(Rational::zero);
                    (name.clone(), Gaussian::new(*real, imaginary))
                })
                .collect(),
        )
    }
}

/// A concrete rational configuration satisfying every hypothesis **and** every
/// non-degeneracy condition, at which the conclusions must hold.
///
/// Not part of the proof — the certificate settles all instances at once — but it
/// is an independent read on whether the polynomials say what their names claim.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenericWitness {
    /// What the configuration is, in prose.
    pub description: String,
    /// Every coordinate variable of the problem, at an exact rational value.
    pub assignment: BTreeMap<String, Rational>,
}

/// A geometry theorem stated as polynomials.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeometryProblem {
    /// Stable identifier; also the certificate file's stem.
    pub id: String,
    /// One-line human title.
    pub title: String,
    /// The theorem in prose, including its non-degeneracy conditions.
    pub statement: String,
    /// What each free coordinate variable denotes, e.g. `("ax", "A.x")`.
    pub coordinate_gloss: Vec<(String, String)>,
    /// Equations the configuration is assumed to satisfy.
    pub hypotheses: Vec<Constraint>,
    /// Polynomials the configuration is assumed **not** to annihilate.
    pub nondegeneracy: Vec<Condition>,
    /// Equations to be established.
    pub conclusions: Vec<Constraint>,
    /// Degenerate counterexamples, one per condition expected to be needed.
    pub degenerate_witnesses: Vec<DegenerateWitness>,
    /// Non-degenerate sanity configurations.
    pub generic_witnesses: Vec<GenericWitness>,
}

/// One saturating non-degeneracy condition, with the fresh variable that inverts
/// it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Saturation {
    /// The [`Condition::id`] being saturated by.
    pub condition_id: String,
    /// The condition's prose.
    pub description: String,
    /// The fresh inverse variable `z`.
    pub var: String,
    /// The condition polynomial `d`; the generator is `d·z − 1`.
    pub condition: MvPoly,
}

/// A conclusion together with its cofactors against the generator list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CertifiedConclusion {
    /// The conclusion's identifier.
    pub id: String,
    /// The conclusion's prose.
    pub description: String,
    /// The conclusion polynomial, which the identity reproduces.
    pub poly: MvPoly,
    /// One cofactor per generator, positionally aligned with
    /// [`GeometryCertificate::generators`].
    pub cofactors: Vec<MvPoly>,
}

/// The artifact: an identity per conclusion over an explicit generator list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeometryCertificate {
    /// Stable identifier.
    pub id: String,
    /// One-line human title.
    pub title: String,
    /// The theorem in prose.
    pub statement: String,
    /// What each coordinate variable denotes.
    pub coordinate_gloss: Vec<(String, String)>,
    /// The coordinate variables, sorted; saturation variables are **not** here.
    pub coordinates: Vec<String>,
    /// The hypotheses, in generator order.
    pub hypotheses: Vec<Constraint>,
    /// The saturating conditions actually used, in generator order after the
    /// hypotheses. Empty when the conclusion lies in the plain hypothesis ideal.
    pub saturations: Vec<Saturation>,
    /// `hypotheses` polynomials followed by `condition·var − 1` for each
    /// saturation. The cofactors are aligned with this list.
    pub generators: Vec<MvPoly>,
    /// The conclusions, each with its cofactors.
    pub conclusions: Vec<CertifiedConclusion>,
    /// Degenerate counterexamples for the conditions used.
    pub degenerate_witnesses: Vec<DegenerateWitness>,
    /// Non-degenerate sanity configurations.
    pub generic_witnesses: Vec<GenericWitness>,
}

/// The result of attempting to certify a [`GeometryProblem`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProofOutcome {
    /// An identity per conclusion, over the smallest condition subset found.
    Certified(Box<GeometryCertificate>),
    /// Every subset of the stated conditions was tried and at least one
    /// conclusion still had a nonzero remainder. Nothing is claimed: the theorem
    /// may need a condition that was not stated, or may be false.
    NotInSaturatedIdeal {
        /// The identifier of a conclusion that did not reduce to zero, using the
        /// full condition set.
        conclusion_id: String,
        /// Its nonzero remainder modulo the full generator set.
        remainder: MvPoly,
    },
    /// Nothing is claimed, with the reason recorded — see [`GeometryDecline`].
    Declined(GeometryDecline),
}

/// Why [`certify`] produced no certificate.
///
/// The distinction that matters most here is inside
/// [`GeometryDecline::Reduction`]: a tripped ceiling is a statement about the
/// budget and an overflow is a statement about `i128`, and a frontier theorem
/// that "declines" is uninterpretable until they are told apart.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GeometryDecline {
    /// The cofactor-tracked reduction stopped; the inner reason says whether a
    /// ceiling tripped or the exact arithmetic left the `i128` range.
    Reduction(DeclineReason),
    /// More non-degeneracy conditions than the subset enumeration admits (the
    /// power set of more than 16 conditions is not searched).
    TooManyConditions,
    /// A stated [`DegenerateWitness`] did not in fact break the theorem, so the
    /// certificate's negative control would have been decorative. This is a
    /// refusal, not a resource limit.
    UnverifiedWitness,
    /// [`certify_by_linear_elimination`] cleared the unknowns, but the
    /// determinant it multiplied through by is not a product of the *stated*
    /// non-degeneracy conditions, so there is no way to divide it back out inside
    /// the original generator list.
    ///
    /// Not a resource limit either: it says the theorem needs a side condition
    /// nobody wrote down, or that the elimination picked a decomposition whose
    /// determinant is not the geometric one. Both are worth seeing rather than
    /// timing out over.
    UndividableMultiplier,
    /// The problem's **own** committed counterexample satisfies every hypothesis,
    /// keeps every stated non-degeneracy condition nonzero, and falsifies a
    /// conclusion. The theorem as stated is false, and no budget, order or
    /// algorithm changes that.
    ///
    /// This can only be reported because the subset search is pruned by the
    /// committed witnesses ([`searchable_subsets`]): with every subset including
    /// the full one refuted, there is nothing left to search, and saying so is far
    /// more useful than reporting whatever the last futile reduction did.
    RefutedByOwnWitness,
}

/// The prefix of the fresh inverse variables introduced by saturation.
///
/// Uppercase deliberately: `'Z' < 'a'` as bytes, so under `lex` — with the
/// alphabetically-*first* variable most significant — the inverse variables rank
/// above every coordinate and `Buchberger`'s algorithm eliminates them first.
/// [`geometry_limits`] now defaults to `grevlex`, where the name only breaks ties
/// between equal-degree monomials and the effect is smaller. Either way this is a
/// performance choice: ideal membership does not depend on the order, which is
/// exactly why the order was safe to change.
pub const INVERSE_PREFIX: &str = "Zinv";

/// Ceilings sized for the coordinate systems classical plane theorems produce.
///
/// Calibrated against the committed corpus (release build, 2026-08-15): the most
/// expensive reduction that *succeeds* is `rhombus-diagonals-perpendicular` at
/// 21 s, and the most expensive that correctly reports a nonzero remainder is its
/// own empty-condition attempt at 0.7 s. The ceilings leave that reduction real
/// headroom on every axis — see [`crate::geometry_corpus::corpus`] — while
/// staying small enough that a theorem outside this route's reach declines in
/// minutes rather than never; [`crate::geometry_corpus::frontier`] has the one
/// that does.
///
/// # Why the order is `DegRevLex`
///
/// `lex` is the best order for *elimination* and the worst for computing a basis,
/// and ideal membership needs no elimination — so the theory says `grevlex`, and
/// the theory was checked rather than quoted. Two measurements settled it, both
/// reproducible with
/// `cargo run -p axeyum-cas --release --example geometry_order_audit`:
///
/// - **The order cannot move a condition set here.** The audit runs *every*
///   condition subset of every corpus theorem under both orders, and under both
///   orders every subset is **decided** — `in ideal` or `not in ideal`, never
///   declined. `certify` reports the smallest subset that succeeds, and
///   "succeeds" is budget-relative only when some smaller subset declines; with
///   every subset decided, the reported set is smallest *absolutely*, and no
///   change of order can move it. That mattered because those conditions are
///   hypotheses in the fact ledger's `formal.statement`: a silent move would have
///   changed what six proved facts claim.
/// - **The certificates are byte-identical.** All six artifacts that predate the
///   switch re-serialize identically under `grevlex` — the emitter reported *6
///   unchanged, 1 written*, the one being the newly reachable rhombus. The switch
///   changed no evidence at all, only the cost of producing it: 1.2–2.4× faster
///   on the six theorems both orders certify.
///
/// What the switch *did* change is reach: `rhombus-diagonals-perpendicular`
/// declined under `lex` after 287.8 s on the `ReductionSteps` ceiling and
/// certifies under `grevlex` in 21 s. It is in the corpus because of this line.
#[must_use]
pub fn geometry_limits() -> Limits {
    Limits {
        reduction_steps: 50_000,
        pair_iterations: 2_000,
        basis_size: 200,
        poly_terms: 8_000,
        order: MonomialOrder::DegRevLex,
    }
}

/// Every condition subset of `problem`, smallest first, with the ones a committed
/// counterexample already **refutes** dropped.
///
/// # Why the pruning is sound, and why it is not merely an optimisation
///
/// A conclusion lies in the saturated ideal of a subset `S` only if it vanishes at
/// every common zero of those generators. So one configuration that satisfies
/// every hypothesis, keeps every condition of `S` nonzero — extending to a zero of
/// the Rabinowitsch generators by `z := 1/d` — and **falsifies** a conclusion
/// refutes `S` outright. Skipping it costs nothing: no search could have succeeded
/// there, whatever its budget, order or algorithm.
///
/// The point is not the time saved, though on `simson-line` it is the difference
/// between one elimination and seven futile ones. It is that ADR-0460's failure —
/// a minimality claim that is really a claim about the producer's own
/// decomposition — cannot arise for a subset that was never *searched*. A subset
/// this function drops is refuted by a fact about the theorem; a subset the search
/// rejects is rejected by a fact about the search. Making the first set as large
/// as the committed evidence allows shrinks the second, which is exactly the
/// direction ADR-0460 asks for.
///
/// The refutation is checked over `ℚ(i)` for the same reason the negative controls
/// are: the identity being searched for has rational coefficients and is therefore
/// a statement about every field of characteristic zero, so a `ℚ(i)` counterexample
/// is a genuine obstruction to it. A rational witness embeds unchanged.
#[must_use]
pub fn searchable_subsets(problem: &GeometryProblem) -> Vec<Vec<usize>> {
    let count = problem.nondegeneracy.len();
    let mut subsets: Vec<Vec<usize>> = (0u32..(1u32 << count))
        .map(|mask| {
            (0..count)
                .filter(|index| mask & (1 << index) != 0)
                .collect::<Vec<usize>>()
        })
        .collect();
    subsets.sort_by(|left, right| left.len().cmp(&right.len()).then_with(|| left.cmp(right)));
    subsets.retain(|subset| !subset_is_refuted(problem, subset));
    subsets
}

/// Whether a committed counterexample refutes this condition subset outright.
///
/// `subset` indexes `problem.nondegeneracy`. A `true` answer is **decided**, with
/// no budget, monomial order or algorithm in it: the conclusion cannot lie in the
/// saturated ideal of a generator set that has a common zero falsifying it. So a
/// caller may use this to prune a search ([`searchable_subsets`] does) or to
/// report a subset as settled without running a reduction at all, which is what
/// makes an audit of a theorem like `simson-line` affordable.
#[must_use]
pub fn subset_is_refuted(problem: &GeometryProblem, subset: &[usize]) -> bool {
    problem.degenerate_witnesses.iter().any(|witness| {
        let Some(point) = witness.point() else {
            return false;
        };
        let vanishes = |poly: &MvPoly| {
            matches!(evaluate_gaussian(poly, &point), Some(value) if value.is_zero())
        };
        let survives = |poly: &MvPoly| {
            matches!(evaluate_gaussian(poly, &point), Some(value) if !value.is_zero())
        };
        problem
            .hypotheses
            .iter()
            .all(|hypothesis| vanishes(&hypothesis.poly))
            && subset
                .iter()
                .all(|&index| survives(&problem.nondegeneracy[index].poly))
            && problem
                .conclusions
                .iter()
                .any(|conclusion| survives(&conclusion.poly))
    })
}

/// Certify a geometry theorem, using as **few** non-degeneracy conditions as
/// possible.
///
/// Subsets of `problem.nondegeneracy` are tried in order of increasing size (and,
/// within a size, in ascending index order), so the reported condition set is
/// smallest by cardinality among the subsets the budget could decide, and it is
/// deterministic. The empty subset is tried first: a theorem that is an outright
/// ideal identity is reported as needing nothing, which is a materially stronger
/// statement and one this module refuses to obscure.
///
/// Subsets a committed counterexample already refutes are skipped without being
/// searched at all — see [`searchable_subsets`], and note that the skip strictly
/// improves the minimality claim rather than weakening it.
///
/// A subset that [declines](CofactorOutcome::Declined) is skipped, so in
/// principle a theorem could certify with more conditions than it strictly needs.
/// That direction is conservative — a certificate using a condition it did not
/// need proves a *weaker* theorem — and the identity is checked independently
/// either way. The dangerous direction, claiming no condition is needed when one
/// is, cannot arise: it would require the empty-subset reduction to produce an
/// identity that the checker then re-derives.
///
/// Every [`DegenerateWitness`] naming a condition that ended up **unused** is
/// dropped from the certificate, and every witness naming a used condition is
/// verified before the certificate is returned; a witness that does not in fact
/// break the theorem makes this return
/// [`GeometryDecline::UnverifiedWitness`] rather than
/// emitting an artifact whose negative control is decorative.
#[must_use]
pub fn certify(problem: &GeometryProblem, limits: Limits) -> ProofOutcome {
    let count = problem.nondegeneracy.len();
    if count > 16 {
        return ProofOutcome::Declined(GeometryDecline::TooManyConditions);
    }
    let targets: Vec<MvPoly> = problem
        .conclusions
        .iter()
        .map(|conclusion| conclusion.poly.clone())
        .collect();

    let subsets = searchable_subsets(problem);
    // Nothing left to search means the FULL condition set is refuted by the
    // problem's own counterexample: the theorem as stated is false, and no
    // budget, order or algorithm changes that. Saying so beats reporting
    // whatever the last futile reduction happened to do.
    if subsets.is_empty() {
        return ProofOutcome::Declined(GeometryDecline::RefutedByOwnWitness);
    }

    // The outcome of the LAST subset tried, which is the full condition set;
    // that is the informative diagnostic when nothing certifies.
    let mut last_failure =
        ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));

    for subset in &subsets {
        let Some((saturations, generators)) = build_generators(problem, subset) else {
            // Overflow while building a saturation generator. Skip this subset
            // rather than dropping the condition, which would prove a stronger
            // statement than the input allows.
            last_failure =
                ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));
            continue;
        };
        let outcomes = reduce_many_with_cofactors(&generators, &targets, limits);
        let mut cofactor_sets = Vec::with_capacity(targets.len());
        let mut all_zero = true;
        for (conclusion, outcome) in problem.conclusions.iter().zip(outcomes.iter()) {
            match outcome {
                CofactorOutcome::Reduced {
                    cofactors,
                    remainder,
                } => {
                    if remainder.is_zero() {
                        cofactor_sets.push(cofactors.clone());
                    } else {
                        all_zero = false;
                        last_failure = ProofOutcome::NotInSaturatedIdeal {
                            conclusion_id: conclusion.id.clone(),
                            remainder: remainder.clone(),
                        };
                        break;
                    }
                }
                CofactorOutcome::Declined(reason) => {
                    all_zero = false;
                    last_failure = ProofOutcome::Declined(GeometryDecline::Reduction(*reason));
                    break;
                }
            }
        }
        if !all_zero {
            continue;
        }
        let certificate = assemble(problem, saturations, generators, cofactor_sets);
        return match verify_witnesses(problem, &certificate) {
            Ok(certificate) => ProofOutcome::Certified(Box::new(certificate)),
            Err(()) => ProofOutcome::Declined(GeometryDecline::UnverifiedWitness),
        };
    }

    last_failure
}

/// The largest power of a non-degeneracy condition
/// [`certify_by_linear_elimination`] will divide out of a multiplier.
///
/// A ceiling rather than a natural bound: dividing by a condition polynomial
/// strictly lowers the multiplier's degree, so the loop terminates on its own for
/// any non-constant condition. This stops a constant one from spinning.
const MAX_INVERSE_POWER: u32 = 32;

/// Certify a geometry theorem by **linear elimination** instead of by Gröbner
/// search, keeping the certificate in the original generators.
///
/// # Why this route exists
///
/// Classical constructions determine their points by *linear* systems: the
/// circumcentre is the intersection of two perpendicular bisectors, the
/// orthocentre of two altitudes, and each of those is one linear equation per
/// coordinate over `ℚ[vertex coordinates]`. Handing those hypotheses to
/// `Buchberger`'s algorithm asks it to rediscover Cramer's rule by monomial
/// reduction, which for `euler-line` it does not manage: the `geometry-frontier`
/// lane measured the basis still growing after 65 S-pairs with 528 queued and the
/// backlog tripling per doubling.
///
/// [`crate::linear_elim`] does the solve directly and returns
///
/// ```text
/// multiplier · conclusion  =  residue  +  Σᵢ uᵢ · hypothesisᵢ
/// ```
///
/// where `multiplier` is a product of the systems' determinants.
///
/// # How the certificate stays in the original generators
///
/// Nothing here changes the generator list: it is the hypotheses followed by
/// `d·z − 1` per condition, exactly as [`certify`] builds it, and the artifact is
/// the same [`GeometryCertificate`] checked by the same
/// [`crate::geometry_check::check_certificate`], which shares no code with either
/// route. The elimination is *untrusted search* for the cofactor vector — the
/// adjugate identity `adj(M)·(M·u + k) = det(M)·u + adj(M)·k` expresses
/// `det(M)·uⱼ` as a polynomial free of the unknowns plus a combination of the
/// **original** rows, so substituting it into the conclusion produces cofactors
/// against those rows and nothing else.
///
/// The `multiplier` is then divided back out **inside the ideal**, not
/// symbolically. For a condition `d` with `dᴺ` dividing the multiplier, the
/// Rabinowitsch generator `g = d·z − 1` gives `(d·z)ᴺ = (1 + g)ᴺ`, hence
///
/// ```text
/// 1  =  zᴺ·dᴺ  −  g·Σ_{i=1..N} C(N,i)·g^{i−1}
/// ```
///
/// and multiplying the elimination identity by `zᴺ` and subtracting yields
/// cofactors for the conclusion itself. For `N = 1` this collapses to the
/// familiar shape the search route produces, where the saturation generator's
/// cofactor is minus the conclusion; `euler-line` has `N = 2` and gets
/// `−conclusion·(1 + d·z)`.
///
/// If the multiplier is **not** a product of the stated conditions (times a
/// nonzero rational), this returns
/// [`GeometryDecline::UndividableMultiplier`] rather than inventing a condition.
///
/// # Minimality
///
/// Condition subsets are tried smallest-first, exactly as in [`certify`], and the
/// ones a committed counterexample refutes are not tried at all
/// ([`searchable_subsets`]).
///
/// Every subset test this route *does* run is *decided* — factoring a multiplier
/// by exact division always terminates and always answers — so the reported set is
/// smallest among the subsets this route can use. ADR-0460 is the reason that
/// sentence is not the end of it: "decided" was true of `pappus-hexagon`'s
/// three-condition answer too, and that answer was wrong, because the test was
/// about the theorem *under a decomposition the producer chose*. Two things guard
/// it now, and neither is a disclosure. `licensed_blocks` makes the decomposition
/// a function of the subset, so the test stops being about a fixed choice; and the
/// pruning above settles as many subsets as the committed evidence can by
/// **refutation**, which is a fact about the theorem and about nothing the
/// producer picked. What remains searched is the residue of subsets that no
/// counterexample refutes, and on those the honest claim is still "smallest this
/// route reached".
///
/// # The handover
///
/// `handover` bounds the general ideal-membership work spent on whatever the
/// elimination could **not** remove. `None` refuses it outright: the elimination
/// must settle the conclusion by itself, which makes this route cost
/// microseconds and never inherit the cost it exists to avoid. `Some(limits)`
/// lets the residue — free of the eliminated unknowns, so a materially smaller
/// question — go to [`reduce_many_with_cofactors`], which is what a theorem that
/// is only *partly* linear needs.
#[must_use]
pub fn certify_by_linear_elimination(
    problem: &GeometryProblem,
    handover: Option<Limits>,
) -> ProofOutcome {
    let count = problem.nondegeneracy.len();
    if count > 16 {
        return ProofOutcome::Declined(GeometryDecline::TooManyConditions);
    }
    let subsets = searchable_subsets(problem);
    // Nothing left to search means the FULL condition set is refuted by the
    // problem's own counterexample: the theorem as stated is false, and no
    // budget, order or algorithm changes that. Saying so beats reporting
    // whatever the last futile reduction happened to do.
    if subsets.is_empty() {
        return ProofOutcome::Declined(GeometryDecline::RefutedByOwnWitness);
    }

    let hypotheses: Vec<MvPoly> = problem
        .hypotheses
        .iter()
        .map(|hypothesis| hypothesis.poly.clone())
        .collect();

    let mut last_failure = ProofOutcome::Declined(GeometryDecline::UndividableMultiplier);

    for subset in &subsets {
        let Some((saturations, generators)) = build_generators(problem, subset) else {
            last_failure =
                ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));
            continue;
        };
        let mut cofactor_sets = Vec::with_capacity(problem.conclusions.len());
        let mut settled = true;
        let conditions: Vec<MvPoly> = subset
            .iter()
            .map(|&index| problem.nondegeneracy[index].poly.clone())
            .collect();
        for conclusion in &problem.conclusions {
            match linear_cofactors(
                &hypotheses,
                &generators,
                &saturations,
                &conditions,
                conclusion,
                handover,
            ) {
                Ok(cofactors) => cofactor_sets.push(cofactors),
                Err(outcome) => {
                    last_failure = outcome;
                    settled = false;
                    break;
                }
            }
        }
        if !settled {
            continue;
        }
        // Every saturation must carry a nonzero cofactor somewhere, or the
        // certificate advertises a weaker theorem than it proved and the
        // independent checker rejects it. Smallest-first ordering makes this
        // unreachable for a single condition, but not for two.
        let all_used = saturations.iter().enumerate().all(|(slot, _)| {
            cofactor_sets
                .iter()
                .any(|cofactors| !cofactors[problem.hypotheses.len() + slot].is_zero())
        });
        if !all_used {
            last_failure = ProofOutcome::Declined(GeometryDecline::UndividableMultiplier);
            continue;
        }
        let certificate = assemble(problem, saturations, generators, cofactor_sets);
        return match verify_witnesses(problem, &certificate) {
            Ok(certificate) => ProofOutcome::Certified(Box::new(certificate)),
            Err(()) => ProofOutcome::Declined(GeometryDecline::UnverifiedWitness),
        };
    }

    last_failure
}

/// Certify by whichever route reaches the theorem: linear elimination first,
/// then the Gröbner search.
///
/// # Why that order, and why it does not disturb anything
///
/// The linear route is tried first because it is the *cheap* one — with no
/// handover it is pure adjugate arithmetic, microseconds, and it either settles
/// the conclusion outright or gets out of the way. The Gröbner route is second
/// because it is the general one. Trying the expensive route first would mean
/// `euler-line` never reaches the cheap one at all: its Gröbner reduction does
/// not return inside any budget anyone has been willing to wait for.
///
/// The order is safe for the same reason the `grevlex` switch was, and it was
/// checked the same way rather than argued: on the seven theorems that predate
/// this route, the linear pass declines on six (its multiplier is not a product
/// of the stated conditions) and produces the *identical* empty certificate on
/// Varignon, so `emit_geometry_certificates` reports them all unchanged, byte for
/// byte. What the order changes is reach, not evidence.
///
/// The one thing it can change is a **condition set**, and that has to be said
/// out loud because condition sets are hypotheses in the fact ledger. The linear
/// route's multiplier is an artifact of the decomposition it chose, so it may
/// need to invert a condition the Gröbner route would not have used — a *weaker*
/// theorem, conservative in the safe direction, and detectable: the degenerate
/// counterexample in the certificate decides whether the condition is genuinely
/// required, with no budget in the argument (see
/// [`certify_by_linear_elimination`]).
/// # Why the handover is enabled here
///
/// It was `None` — "the elimination must settle the conclusion by itself" — for
/// as long as every theorem the route reached had a *zero* residue. `pappus-hexagon`
/// is the first that does not: eliminating `AE ∩ BD` leaves 48 terms that are in
/// the ideal of the six untouched hypotheses and are not going anywhere by
/// linear algebra alone.
///
/// Enabling it is safe for a reason stronger than measurement, though it is
/// measured too. The handover refuses to run at all when the elimination consumed
/// **no block** (see `linear_cofactors`), so a theorem this route cannot start on
/// still declines untouched and reaches Buchberger exactly as before. That is
/// what keeps the six theorems whose determinant no condition licenses — Thales
/// and friends — on the identity already committed for them, rather than on a
/// second one this route happened to find. `emit_geometry_certificates` reports
/// **8 unchanged** across the switch.
#[must_use]
pub fn certify_any_route(problem: &GeometryProblem, limits: Limits) -> ProofOutcome {
    match certify_by_linear_elimination(problem, Some(limits)) {
        certified @ ProofOutcome::Certified(_) => certified,
        _ => certify(problem, limits),
    }
}

/// The cofactor vector for one conclusion under one condition subset, or the
/// outcome that explains why there is none.
fn linear_cofactors(
    hypotheses: &[MvPoly],
    generators: &[MvPoly],
    saturations: &[Saturation],
    conditions: &[MvPoly],
    conclusion: &Constraint,
    handover: Option<Limits>,
) -> Result<Vec<MvPoly>, ProofOutcome> {
    let overflow = || ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));
    let blocks = licensed_blocks(
        detect_linear_blocks(hypotheses, &conclusion.poly),
        conditions,
    );
    let Some(elimination) = eliminate_blocks(hypotheses, &conclusion.poly, blocks) else {
        return Err(overflow());
    };

    let mut cofactors = vec![MvPoly::zero(); generators.len()];
    for (slot, cofactor) in elimination.cofactors.iter().enumerate() {
        cofactors[slot] = cofactor.clone();
    }

    // What linear algebra could not remove goes to the general route — over the
    // generators the blocks did **not** consume, which is the whole point of
    // handing it over at all. For `euler-line` the residue is zero and this never
    // runs.
    if !elimination.residue.is_zero() {
        // A zero residue is short-circuited rather than reduced, and that is not
        // bookkeeping: reducing even the zero polynomial computes a Gröbner basis
        // of the generators, which is exactly the divergent computation this route
        // exists to avoid.
        // The handover exists to finish what the elimination *started*. With no
        // block consumed the elimination did nothing at all, so handing the whole
        // target over would silently turn this into a second general-purpose route
        // — one that could certify a corpus theorem by a different identity than
        // the one already committed. It declines instead, and `certify_any_route`
        // hands the problem to Buchberger as before.
        if elimination.blocks.is_empty() {
            return Err(ProofOutcome::NotInSaturatedIdeal {
                conclusion_id: conclusion.id.clone(),
                remainder: elimination.residue.clone(),
            });
        }
        let Some(limits) = handover else {
            return Err(ProofOutcome::NotInSaturatedIdeal {
                conclusion_id: conclusion.id.clone(),
                remainder: elimination.residue.clone(),
            });
        };
        settle_residue(
            hypotheses,
            generators,
            &elimination,
            conclusion,
            limits,
            &mut cofactors,
        )?;
    }

    match invert_multiplier(
        &conclusion.poly,
        &elimination.multiplier,
        saturations,
        hypotheses.len(),
        cofactors,
    ) {
        Some(cofactors) => Ok(cofactors),
        None => Err(ProofOutcome::Declined(
            GeometryDecline::UndividableMultiplier,
        )),
    }
}

/// Hand whatever linear algebra could not remove to a general ideal-membership
/// route, and fold the cofactors it returns into `cofactors`.
///
/// Extracted from [`linear_cofactors`] because it is a different question: that
/// function decides *what to eliminate*, this one decides *who finishes the rest*.
fn settle_residue(
    hypotheses: &[MvPoly],
    generators: &[MvPoly],
    elimination: &LinearElimination,
    conclusion: &Constraint,
    limits: Limits,
    cofactors: &mut [MvPoly],
) -> Result<(), ProofOutcome> {
    let overflow = || ProofOutcome::Declined(GeometryDecline::Reduction(DeclineReason::Overflow));
    // Narrowing is not an optimisation; without it the handover recomputes
    // the basis this route existed to avoid. Measured on `pappus-hexagon`:
    // the elimination clears three 2×2 blocks in milliseconds and leaves a
    // 720-term residue free of `xx…zy`, and reducing that against all eight
    // hypotheses — six of which are precisely the ones just consumed, and
    // every one of which mentions a variable the residue no longer has — does
    // not return. Against the two the blocks did not touch it is a two-
    // generator question.
    //
    // There is deliberately no fallback to the full generator list. That is
    // the route's contract: linear algebra takes the linear part, the general
    // route takes what is left of the *rest*, and if that is not enough this
    // route declines so `certify_any_route` can hand the whole problem to
    // Buchberger. A fallback would reintroduce the hang on exactly the
    // theorems the narrowing was for.
    //
    // Two passes, hypotheses-only first. The saturation generators `d·z − 1`
    // are what the *multiplier* needs, not what the residue needs, and they
    // are the worst possible input to `Buchberger`'s algorithm — a fresh
    // variable in every one of them. On `pappus-hexagon` the residue reduces
    // against the two unconsumed hypotheses in a single S-pair, while the same
    // reduction with three Rabinowitsch generators added does not return; so
    // reaching for them only when the cheap pass fails is the difference
    // between a subset search that finishes and one that does not.
    let consumed: BTreeSet<usize> = elimination
        .blocks
        .iter()
        .flat_map(|block| block.rows.iter().copied())
        .collect();
    let bare: Vec<usize> = (0..hypotheses.len())
        .filter(|index| !consumed.contains(index))
        .collect();
    let saturated: Vec<usize> = (0..generators.len())
        .filter(|index| !consumed.contains(index))
        .collect();
    let passes: Vec<&Vec<usize>> = if bare == saturated {
        vec![&bare]
    } else {
        vec![&bare, &saturated]
    };

    let mut settled = false;
    let mut last: Option<ProofOutcome> = None;
    for kept in passes {
        let narrowed: Vec<MvPoly> = kept
            .iter()
            .map(|&index| generators[index].clone())
            .collect();
        // Bounded-degree linear algebra first, Buchberger only if it comes
        // back `NotInDegree`. This is not a micro-optimisation: on
        // `pappus-hexagon`'s single-condition subset the residue is 48 terms
        // of degree 4 over six quadrics, `crate::cofactor_ansatz` settles it
        // in ~25 ms with every coefficient ±1, and Buchberger did not return
        // on the same input after 7.5 minutes without returning. Ordering it
        // second would mean the subset search never reaches the answer.
        match cofactors_by_ansatz(&narrowed, &elimination.residue, AnsatzLimits::geometry()) {
            AnsatzOutcome::Solved {
                cofactors: extra, ..
            } => {
                for (slot, share) in kept.iter().zip(extra.iter()) {
                    let Some(sum) = cofactors[*slot].add(share) else {
                        return Err(overflow());
                    };
                    cofactors[*slot] = sum;
                }
                settled = true;
                break;
            }
            AnsatzOutcome::NotInDegree(_) | AnsatzOutcome::Declined(_) => {}
        }
        let outcomes = reduce_many_with_cofactors(
            &narrowed,
            std::slice::from_ref(&elimination.residue),
            limits,
        );
        match &outcomes[0] {
            CofactorOutcome::Reduced {
                cofactors: extra,
                remainder,
            } => {
                if !remainder.is_zero() {
                    last = Some(ProofOutcome::NotInSaturatedIdeal {
                        conclusion_id: conclusion.id.clone(),
                        remainder: remainder.clone(),
                    });
                    continue;
                }
                for (slot, share) in kept.iter().zip(extra.iter()) {
                    let Some(sum) = cofactors[*slot].add(share) else {
                        return Err(overflow());
                    };
                    cofactors[*slot] = sum;
                }
                settled = true;
                break;
            }
            CofactorOutcome::Declined(reason) => {
                last = Some(ProofOutcome::Declined(GeometryDecline::Reduction(*reason)));
            }
        }
    }
    if !settled {
        return Err(last.unwrap_or_else(|| ProofOutcome::NotInSaturatedIdeal {
            conclusion_id: conclusion.id.clone(),
            remainder: elimination.residue.clone(),
        }));
    }
    Ok(())
}

/// Keep only the blocks whose determinant the current condition subset
/// **licenses** — that is, whose determinant is a nonzero rational times a
/// product of powers of the subset's conditions.
///
/// This is the difference between a route that reports the smallest subset it can
/// *use* and one that reports the smallest subset the theorem *needs*. The block
/// detector picks its decomposition from the shape of the generators, knowing
/// nothing about which conditions the caller is currently inverting; its
/// multiplier is then whatever that decomposition produced, and
/// [`invert_multiplier`] can only divide it by declared conditions. Filtering
/// first means each subset is tested against the elimination *it* can pay for,
/// instead of every subset inheriting the full decomposition's multiplier and
/// failing for a reason that has nothing to do with the theorem.
///
/// `pappus-hexagon` is the case that shows the difference is not cosmetic.
/// Unfiltered, the detector always finds all three intersection blocks, the
/// multiplier is the product of all three conditions, and every proper subset
/// declines on [`GeometryDecline::UndividableMultiplier`] — so the route reports
/// three conditions. Filtered, the one-condition subset keeps one block, and the
/// theorem certifies with **one** condition, which is the minimal set: the
/// committed degenerate counterexample refutes the empty subset outright.
fn licensed_blocks(blocks: Vec<LinearBlock>, conditions: &[MvPoly]) -> Vec<LinearBlock> {
    blocks
        .into_iter()
        .filter(|block| factors_into(&block.determinant, conditions))
        .collect()
}

/// Does `polynomial` factor into the `conditions` and a nonzero rational?
///
/// Repeated exact division, to a fixed point: exact division always terminates
/// and always answers, so this is *decided* for every input — there is no budget
/// anywhere in it.
fn factors_into(polynomial: &MvPoly, conditions: &[MvPoly]) -> bool {
    // The zero polynomial divides by everything and is never a nonzero rational,
    // so the fixed point below is never reached: `exact_div(0, d)` is `Some(0)`
    // forever. It cannot arise from a block determinant, which
    // `detect_linear_blocks` guarantees nonzero — but "cannot arise" is exactly
    // the reasoning that leaves a loop unguarded, and the unit test below hung
    // the suite when this guard was missing.
    if polynomial.is_zero() {
        return false;
    }
    let mut remaining = polynomial.clone();
    let mut progressed = true;
    while progressed {
        progressed = false;
        for condition in conditions {
            if condition.total_degree() == 0 {
                continue;
            }
            while let Some(quotient) = remaining.exact_div(condition) {
                remaining = quotient;
                progressed = true;
            }
        }
    }
    !remaining.is_zero() && remaining.total_degree() == 0
}

/// Turn `multiplier · conclusion = Σ cofactorsᵢ·generatorᵢ` into
/// `conclusion = Σ cofactorsᵢ′·generatorᵢ`, using the Rabinowitsch generators as
/// the inverses they are.
///
/// `None` when the multiplier does not factor into the stated conditions and a
/// nonzero rational — which is a statement about the theorem, not about a budget.
fn invert_multiplier(
    conclusion: &MvPoly,
    multiplier: &MvPoly,
    saturations: &[Saturation],
    hypotheses: usize,
    mut cofactors: Vec<MvPoly>,
) -> Option<Vec<MvPoly>> {
    let one = MvPoly::constant(Rational::integer(1));
    let mut remaining = multiplier.clone();
    for (slot, saturation) in saturations.iter().enumerate() {
        if saturation.condition.total_degree() == 0 {
            continue;
        }
        let mut power = 0u32;
        while power < MAX_INVERSE_POWER {
            match remaining.exact_div(&saturation.condition) {
                Some(quotient) => {
                    remaining = quotient;
                    power += 1;
                }
                None => break,
            }
        }
        if power == 0 {
            continue;
        }
        let inverse = MvPoly::var(&saturation.var);
        let scale = inverse.pow(power)?;
        for cofactor in &mut cofactors {
            *cofactor = cofactor.mul(&scale)?;
        }
        // `1 = zᴺ·dᴺ − g·Σ_{i=1..N} C(N,i)·g^{i−1}` with `g = d·z − 1`.
        let generator = saturation.condition.mul(&inverse)?.sub(&one)?;
        let mut series = MvPoly::zero();
        let mut power_of_generator = one.clone();
        for index in 1..=power {
            let coefficient = binomial(power, index)?;
            series = series
                .add(&power_of_generator.mul(&MvPoly::constant(Rational::integer(coefficient)))?)?;
            if index < power {
                power_of_generator = power_of_generator.mul(&generator)?;
            }
        }
        let addend = remaining.mul(conclusion)?.mul(&series)?.neg()?;
        let index = hypotheses + slot;
        cofactors[index] = cofactors[index].add(&addend)?;
    }

    if remaining.total_degree() > 0 {
        return None;
    }
    let leftover = remaining.evaluate(&BTreeMap::new())?;
    if leftover.is_zero() {
        return None;
    }
    let reciprocal = MvPoly::constant(Rational::integer(1).checked_div(leftover)?);
    for cofactor in &mut cofactors {
        *cofactor = cofactor.mul(&reciprocal)?;
    }
    Some(cofactors)
}

/// `C(n, k)` in `i128`, `None` on overflow.
fn binomial(n: u32, k: u32) -> Option<i128> {
    let k = k.min(n.checked_sub(k)?);
    let mut result: i128 = 1;
    for step in 0..k {
        result = result.checked_mul(i128::from(n - step))?;
        result = result.checked_div(i128::from(step) + 1)?;
    }
    Some(result)
}

/// Generators for one condition subset: the hypotheses, then `d·z − 1` per
/// condition, in the subset's ascending index order. `None` on coefficient
/// overflow while forming a saturation generator.
fn build_generators(
    problem: &GeometryProblem,
    subset: &[usize],
) -> Option<(Vec<Saturation>, Vec<MvPoly>)> {
    let mut generators: Vec<MvPoly> = problem
        .hypotheses
        .iter()
        .map(|hypothesis| hypothesis.poly.clone())
        .collect();
    let mut saturations = Vec::with_capacity(subset.len());
    for (slot, &index) in subset.iter().enumerate() {
        let condition = &problem.nondegeneracy[index];
        let var = format!("{INVERSE_PREFIX}{slot}");
        let generator = condition
            .poly
            .mul(&MvPoly::var(&var))
            .and_then(|product| product.sub(&MvPoly::constant(Rational::integer(1))))?;
        generators.push(generator);
        saturations.push(Saturation {
            condition_id: condition.id.clone(),
            description: condition.description.clone(),
            var,
            condition: condition.poly.clone(),
        });
    }
    Some((saturations, generators))
}

fn assemble(
    problem: &GeometryProblem,
    saturations: Vec<Saturation>,
    generators: Vec<MvPoly>,
    cofactor_sets: Vec<Vec<MvPoly>>,
) -> GeometryCertificate {
    let used: BTreeSet<String> = saturations
        .iter()
        .map(|saturation| saturation.condition_id.clone())
        .collect();
    let conclusions = problem
        .conclusions
        .iter()
        .zip(cofactor_sets)
        .map(|(conclusion, cofactors)| CertifiedConclusion {
            id: conclusion.id.clone(),
            description: conclusion.description.clone(),
            poly: conclusion.poly.clone(),
            cofactors,
        })
        .collect();
    let mut coordinates: BTreeSet<String> = BTreeSet::new();
    for constraint in problem.hypotheses.iter().chain(problem.conclusions.iter()) {
        coordinates.extend(constraint.poly.variables());
    }
    for condition in &problem.nondegeneracy {
        coordinates.extend(condition.poly.variables());
    }
    GeometryCertificate {
        id: problem.id.clone(),
        title: problem.title.clone(),
        statement: problem.statement.clone(),
        coordinate_gloss: problem.coordinate_gloss.clone(),
        coordinates: coordinates.into_iter().collect(),
        hypotheses: problem.hypotheses.clone(),
        saturations,
        generators,
        conclusions,
        degenerate_witnesses: problem
            .degenerate_witnesses
            .iter()
            .filter(|witness| used.contains(witness.condition_id.as_str()))
            .cloned()
            .collect(),
        generic_witnesses: problem.generic_witnesses.clone(),
    }
}

/// Refuse a certificate whose negative controls do not actually break the
/// theorem, or whose generic witnesses do not satisfy it.
fn verify_witnesses(
    problem: &GeometryProblem,
    certificate: &GeometryCertificate,
) -> Result<GeometryCertificate, ()> {
    for saturation in &certificate.saturations {
        if !certificate
            .degenerate_witnesses
            .iter()
            .any(|witness| witness.condition_id == saturation.condition_id)
        {
            return Err(());
        }
    }
    for witness in &certificate.degenerate_witnesses {
        let Some(condition) = problem
            .nondegeneracy
            .iter()
            .find(|condition| condition.id == witness.condition_id)
        else {
            return Err(());
        };
        // Over `ℚ(i)`, which is the field the cofactor identity is a theorem of.
        // A rational witness embeds with a zero imaginary part and is decided by
        // exactly the arithmetic it was before.
        let Some(point) = witness.point() else {
            return Err(());
        };
        for hypothesis in &problem.hypotheses {
            match evaluate_gaussian(&hypothesis.poly, &point) {
                Some(value) if value.is_zero() => {}
                _ => return Err(()),
            }
        }
        match evaluate_gaussian(&condition.poly, &point) {
            Some(value) if value.is_zero() => {}
            _ => return Err(()),
        }
        let broken = problem.conclusions.iter().any(|conclusion| {
            matches!(evaluate_gaussian(&conclusion.poly, &point), Some(value) if !value.is_zero())
        });
        if !broken {
            return Err(());
        }
    }
    for witness in &problem.generic_witnesses {
        for hypothesis in &problem.hypotheses {
            match hypothesis.poly.evaluate(&witness.assignment) {
                Some(value) if value.is_zero() => {}
                _ => return Err(()),
            }
        }
        for saturation in &certificate.saturations {
            match saturation.condition.evaluate(&witness.assignment) {
                Some(value) if !value.is_zero() => {}
                _ => return Err(()),
            }
        }
        for conclusion in &problem.conclusions {
            match conclusion.poly.evaluate(&witness.assignment) {
                Some(value) if value.is_zero() => {}
                _ => return Err(()),
            }
        }
    }
    Ok(certificate.clone())
}

#[cfg(test)]
mod tests {
    use super::{
        Condition, Constraint, DegenerateWitness, GenericWitness, GeometryCertificate,
        GeometryDecline, GeometryProblem, ProofOutcome, Pt, certify, certify_any_route,
        certify_by_linear_elimination, collinear, detect_linear_blocks, factors_into,
        geometry_limits, licensed_blocks, midpoint, parallel, perpendicular, same_point,
    };
    use crate::mvpoly::MvPoly;
    use axeyum_ir::Rational;
    use std::collections::BTreeMap;

    /// Re-expand `Σ uᵢ·gᵢ` and compare it with the conclusion, without any of the
    /// machinery that produced the cofactors. This is what the independent
    /// checker does; a route that cannot pass it has produced nothing.
    fn identity_recombines(certificate: &GeometryCertificate) {
        for conclusion in &certificate.conclusions {
            let mut combined = MvPoly::zero();
            for (cofactor, generator) in conclusion.cofactors.iter().zip(&certificate.generators) {
                combined = combined
                    .add(&cofactor.mul(generator).expect("product"))
                    .expect("sum");
            }
            assert_eq!(
                combined, conclusion.poly,
                "the identity must reproduce {}",
                conclusion.id
            );
        }
    }

    // -------------------------------------------------------------------
    // `same_point`. Before this it had no test anywhere in the crate --
    // and it is not dead code: `axeyum-py`'s `cas.certify.geometry` module
    // (`crates/axeyum-py/src/cas/certify/geometry.rs`) exposes it directly
    // to Python callers, with no coverage there either. It is the "A = B"
    // hypothesis/conclusion builder any degenerate-configuration argument
    // needs, so a sign or component swap here would silently encode the
    // wrong equation for every geometry theorem that states two
    // constructed points coincide.
    // -------------------------------------------------------------------

    #[test]
    fn same_point_of_identical_fixed_points_is_the_zero_pair() {
        let a = Pt::fixed(Rational::integer(2), Rational::integer(3));
        let b = Pt::fixed(Rational::integer(2), Rational::integer(3));
        let [dx, dy] = same_point(&a, &b).expect("no overflow");
        assert!(dx.is_zero());
        assert!(dy.is_zero());
    }

    #[test]
    fn same_point_of_distinct_fixed_points_is_nonzero_in_the_differing_component() {
        // A = (2, 3), B = (5, 3): the x-component of the pair must be the exact
        // constant -3, and the y-component exactly zero -- not merely "nonzero
        // somewhere", which a swapped-component bug could still satisfy.
        let a = Pt::fixed(Rational::integer(2), Rational::integer(3));
        let b = Pt::fixed(Rational::integer(5), Rational::integer(3));
        let [dx, dy] = same_point(&a, &b).expect("no overflow");
        assert_eq!(dx, MvPoly::constant(Rational::integer(-3)));
        assert!(dy.is_zero());
    }

    #[test]
    fn same_point_is_componentwise_subtraction_not_a_swap() {
        // This is the negative-fixture half: a component-swap bug (returning
        // [A.y - B.y, A.x - B.x]) would pass the identical-point test above
        // and would even pass a same-shape asymmetric case by coincidence
        // half the time, so the check must pin which polynomial is which.
        let a = Pt::free("a");
        let b = Pt::free("b");
        let [dx, dy] = same_point(&a, &b).expect("no overflow");
        assert_eq!(dx, a.x.sub(&b.x).expect("no overflow"));
        assert_eq!(dy, a.y.sub(&b.y).expect("no overflow"));
        assert_ne!(dx, dy);
    }

    #[test]
    fn same_point_vanishes_exactly_when_the_symbolic_points_are_assigned_equal_coordinates() {
        let a = Pt::free("a");
        let b = Pt::free("b");
        let [dx, dy] = same_point(&a, &b).expect("no overflow");

        let equal_assignment = assign(&[("ax", 7), ("ay", -4), ("bx", 7), ("by", -4)]);
        assert_eq!(dx.evaluate(&equal_assignment), Some(Rational::integer(0)));
        assert_eq!(dy.evaluate(&equal_assignment), Some(Rational::integer(0)));

        let unequal_assignment = assign(&[("ax", 7), ("ay", -4), ("bx", 7), ("by", 1)]);
        assert_eq!(dx.evaluate(&unequal_assignment), Some(Rational::integer(0)));
        assert_eq!(
            dy.evaluate(&unequal_assignment),
            Some(Rational::integer(-5))
        );
    }

    fn assign(pairs: &[(&str, i128)]) -> BTreeMap<String, Rational> {
        pairs
            .iter()
            .map(|(name, value)| ((*name).to_string(), Rational::integer(*value)))
            .collect()
    }

    fn quadrilateral() -> [Pt; 4] {
        [Pt::free("a"), Pt::free("b"), Pt::free("c"), Pt::free("d")]
    }

    fn parallelogram_hypotheses(points: &[Pt; 4]) -> Vec<Constraint> {
        vec![
            Constraint::new(
                "ab-parallel-dc",
                "AB ∥ DC",
                parallel(&points[0], &points[1], &points[3], &points[2]).expect("polynomial"),
            ),
            Constraint::new(
                "bc-parallel-ad",
                "BC ∥ AD",
                parallel(&points[1], &points[2], &points[0], &points[3]).expect("polynomial"),
            ),
        ]
    }

    fn flat_condition(points: &[Pt; 4]) -> Condition {
        Condition::new(
            "abd-not-collinear",
            "A, B, D are not collinear",
            collinear(&points[0], &points[1], &points[3]).expect("polynomial"),
        )
    }

    /// A counterexample that survives the FULL condition set says the theorem is
    /// false, and the certifier must say that rather than report a reduction.
    ///
    /// Written because [`GeometryDecline::RefutedByOwnWitness`] is only reachable
    /// through [`searchable_subsets`] emptying out, which no corpus theorem does —
    /// a variant nothing can return is decoration, and this repository has shipped
    /// several. The fixture is the parallelogram with its counterexample moved off
    /// the degeneracy locus: `A=(0,0)`, `B=(1,0)`, `C=(1,1)`, `D=(0,1)` is a unit
    /// square, so `abd-not-collinear` holds, and `C` is moved to `(2,2)` so the
    /// diagonals no longer bisect. Every hypothesis still holds, so it refutes the
    /// full set.
    #[test]
    fn a_counterexample_surviving_every_condition_declines_as_a_refutation() {
        let points = quadrilateral();
        let diagonal_ac = midpoint(&points[0], &points[2]).expect("midpoint");
        let diagonal_bd = midpoint(&points[1], &points[3]).expect("midpoint");
        // `A=(0,0)`, `B=(2,0)`, `D=(0,3)`, `C=(5,3)`: `AB ∥ DC` holds (both
        // horizontal), `A, B, D` are a genuine triangle so the condition holds
        // too, and the diagonals' midpoints are `(5/2, 3/2)` and `(1, 3/2)`, so
        // the conclusion fails.
        let refuting = assign(&[
            ("ax", 0),
            ("ay", 0),
            ("bx", 2),
            ("by", 0),
            ("cx", 5),
            ("cy", 3),
            ("dx", 0),
            ("dy", 3),
        ]);
        let problem = GeometryProblem {
            id: "refuted-fixture".into(),
            title: "a stated theorem its own witness refutes".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: vec![
                parallelogram_hypotheses(&points)
                    .into_iter()
                    .next()
                    .expect("at least one hypothesis"),
            ],
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![Constraint::new(
                "midpoints-agree-x",
                "the diagonals share an abscissa",
                diagonal_ac.x.sub(&diagonal_bd.x).expect("difference"),
            )],
            degenerate_witnesses: vec![DegenerateWitness::rational(
                "abd-not-collinear",
                "not degenerate at all, and it breaks the conclusion",
                refuting.clone(),
            )],
            generic_witnesses: Vec::new(),
        };
        // The fixture only means something if the witness really does satisfy the
        // hypotheses, survive the condition and break the theorem, so assert all
        // three first. The hypothesis check earns its place: the first draft of
        // this fixture violated `AB ∥ DC`, which makes the witness refute nothing,
        // and the symptom was a slow search rather than a clear failure.
        for hypothesis in &problem.hypotheses {
            assert!(
                hypothesis
                    .poly
                    .evaluate(&refuting)
                    .expect("assigned")
                    .is_zero(),
                "the witness must satisfy `{}`, or it refutes nothing",
                hypothesis.id
            );
        }
        assert!(
            !problem.nondegeneracy[0]
                .poly
                .evaluate(&refuting)
                .expect("assigned")
                .is_zero(),
            "the witness must KEEP the condition nonzero, or it refutes nothing"
        );
        assert!(
            !problem.conclusions[0]
                .poly
                .evaluate(&refuting)
                .expect("assigned")
                .is_zero(),
            "the witness must break the conclusion"
        );
        assert_eq!(
            certify(&problem, geometry_limits()),
            ProofOutcome::Declined(GeometryDecline::RefutedByOwnWitness)
        );
        assert_eq!(
            certify_by_linear_elimination(&problem, None),
            ProofOutcome::Declined(GeometryDecline::RefutedByOwnWitness)
        );
    }

    /// The simplest theorem with a genuine side condition: a parallelogram's
    /// diagonals bisect each other, which is FALSE when the four points are
    /// collinear.
    #[test]
    fn the_parallelogram_needs_exactly_one_condition() {
        let points = quadrilateral();
        let diagonal_ac = midpoint(&points[0], &points[2]).expect("midpoint");
        let diagonal_bd = midpoint(&points[1], &points[3]).expect("midpoint");
        let problem = GeometryProblem {
            id: "parallelogram-diagonals-bisect".into(),
            title: "diagonals of a parallelogram bisect each other".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![
                Constraint::new(
                    "midpoints-agree-x",
                    "the diagonals share an abscissa",
                    diagonal_ac.x.sub(&diagonal_bd.x).expect("difference"),
                ),
                Constraint::new(
                    "midpoints-agree-y",
                    "the diagonals share an ordinate",
                    diagonal_ac.y.sub(&diagonal_bd.y).expect("difference"),
                ),
            ],
            degenerate_witnesses: vec![DegenerateWitness {
                condition_id: "abd-not-collinear".into(),
                imaginary: BTreeMap::new(),
                description: "four collinear points".into(),
                assignment: assign(&[
                    ("ax", 0),
                    ("ay", 0),
                    ("bx", 1),
                    ("by", 0),
                    ("cx", 2),
                    ("cy", 0),
                    ("dx", 5),
                    ("dy", 0),
                ]),
            }],
            generic_witnesses: vec![GenericWitness {
                description: "the unit square".into(),
                assignment: assign(&[
                    ("ax", 0),
                    ("ay", 0),
                    ("bx", 1),
                    ("by", 0),
                    ("cx", 1),
                    ("cy", 1),
                    ("dx", 0),
                    ("dy", 1),
                ]),
            }],
        };
        let ProofOutcome::Certified(certificate) = certify(&problem, geometry_limits()) else {
            panic!("the parallelogram must certify");
        };
        assert_eq!(
            certificate.saturations.len(),
            1,
            "the collinearity condition is genuinely needed"
        );
        assert_eq!(certificate.generators.len(), 3);
        for conclusion in &certificate.conclusions {
            let mut combined = MvPoly::zero();
            for (cofactor, generator) in conclusion.cofactors.iter().zip(&certificate.generators) {
                combined = combined
                    .add(&cofactor.mul(generator).expect("product"))
                    .expect("sum");
            }
            assert_eq!(
                combined, conclusion.poly,
                "the identity must reproduce {}",
                conclusion.id
            );
        }
    }

    /// A degenerate witness that does not actually break the theorem must not
    /// produce a certificate: the negative control is load-bearing, not
    /// decorative.
    #[test]
    fn a_counterexample_that_does_not_break_the_theorem_blocks_the_certificate() {
        let points = quadrilateral();
        let diagonal_ac = midpoint(&points[0], &points[2]).expect("midpoint");
        let diagonal_bd = midpoint(&points[1], &points[3]).expect("midpoint");
        let problem = GeometryProblem {
            id: "parallelogram-diagonals-bisect".into(),
            title: "diagonals of a parallelogram bisect each other".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![Constraint::new(
                "midpoints-agree-x",
                "the diagonals share an abscissa",
                diagonal_ac.x.sub(&diagonal_bd.x).expect("difference"),
            )],
            // Collinear, so the condition IS violated, but the diagonals happen
            // to bisect each other here, so it is not a counterexample.
            degenerate_witnesses: vec![DegenerateWitness {
                condition_id: "abd-not-collinear".into(),
                imaginary: BTreeMap::new(),
                description: "collinear but not a counterexample".into(),
                assignment: assign(&[
                    ("ax", 0),
                    ("ay", 0),
                    ("bx", 1),
                    ("by", 0),
                    ("cx", 2),
                    ("cy", 0),
                    ("dx", 1),
                    ("dy", 0),
                ]),
            }],
            generic_witnesses: Vec::new(),
        };
        assert_eq!(
            certify(&problem, geometry_limits()),
            ProofOutcome::Declined(GeometryDecline::UnverifiedWitness),
            "a decorative counterexample must block the certificate, and say why"
        );
    }

    /// Contrast: Varignon's parallelogram needs NO condition at all, because the
    /// conclusion is a polynomial identity with an empty generator list.
    #[test]
    fn varignon_needs_no_condition() {
        let points = quadrilateral();
        let mid_ab = midpoint(&points[0], &points[1]).expect("midpoint");
        let mid_bc = midpoint(&points[1], &points[2]).expect("midpoint");
        let mid_cd = midpoint(&points[2], &points[3]).expect("midpoint");
        let mid_da = midpoint(&points[3], &points[0]).expect("midpoint");
        let problem = GeometryProblem {
            id: "varignon".into(),
            title: "Varignon".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: Vec::new(),
            nondegeneracy: Vec::new(),
            conclusions: vec![Constraint::new(
                "pq-parallel-sr",
                "PQ ∥ SR",
                parallel(&mid_ab, &mid_bc, &mid_da, &mid_cd).expect("polynomial"),
            )],
            degenerate_witnesses: Vec::new(),
            generic_witnesses: Vec::new(),
        };
        let ProofOutcome::Certified(certificate) = certify(&problem, geometry_limits()) else {
            panic!("Varignon must certify");
        };
        assert!(certificate.saturations.is_empty());
        assert!(certificate.generators.is_empty());
        assert!(
            certificate.conclusions[0].poly.is_zero(),
            "Varignon's conclusion is the zero polynomial outright"
        );
    }

    /// A false "theorem" must not certify: the diagonals of a parallelogram are
    /// not in general perpendicular.
    #[test]
    fn a_false_conclusion_does_not_certify() {
        let points = quadrilateral();
        let problem = GeometryProblem {
            id: "false".into(),
            title: "false".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![Constraint::new(
                "diagonals-perpendicular",
                "AC ⟂ BD, which is false",
                perpendicular(&points[0], &points[2], &points[1], &points[3]).expect("polynomial"),
            )],
            degenerate_witnesses: Vec::new(),
            generic_witnesses: Vec::new(),
        };
        assert!(
            !matches!(
                certify(&problem, geometry_limits()),
                ProofOutcome::Certified(_)
            ),
            "a false conclusion must never certify"
        );
    }

    /// The theorem the linear route exists for. Two 2×2 systems, a zero residue,
    /// and an identity in the ORIGINAL generators — which is what makes it a
    /// certificate rather than a verdict.
    #[test]
    fn the_linear_route_certifies_euler_line() {
        let problem = crate::geometry_corpus::corpus()
            .into_iter()
            .find(|problem| problem.id == "euler-line")
            .expect("euler-line is in the corpus");
        let ProofOutcome::Certified(certificate) = certify_by_linear_elimination(&problem, None)
        else {
            panic!("the linear route must reach euler-line without any Gröbner handover");
        };
        assert_eq!(
            certificate.saturations.len(),
            1,
            "one condition: A, B, C not collinear"
        );
        assert_eq!(
            certificate.generators.len(),
            5,
            "four hypotheses plus d·z − 1"
        );
        for (index, hypothesis) in certificate.hypotheses.iter().enumerate() {
            assert_eq!(
                certificate.generators[index], hypothesis.poly,
                "generator {index} must be the stated hypothesis `{}` unchanged -- a route that \
                 substituted solved forms into the generator list would prove a different theorem",
                hypothesis.id
            );
        }
        identity_recombines(&certificate);
    }

    /// **Each** of Pappus's three non-degeneracy conditions suffices on its own.
    ///
    /// The committed certificate uses `ae-meets-bd`, because the subset search is
    /// deterministic and that is the first singleton it tries. That alone would
    /// leave open whether the other two were doing any work, and the answer is
    /// that they are not — this theorem has three minimal condition sets, each a
    /// singleton, related by the symmetry exchanging `(B,E)` with `(C,F)`.
    ///
    /// Saying so as a certificate rather than as a search that failed to refute is
    /// what makes it a fact about ℚ rather than about the primes an exhaustive
    /// finite-field sweep happened to cover. Each restricted problem below states
    /// exactly one condition and carries exactly the counterexample for it, so
    /// `certify_by_linear_elimination` has no other subset available and the
    /// resulting identity is re-expanded here against the original generators.
    #[test]
    fn each_pappus_condition_alone_certifies() {
        let full = crate::geometry_corpus::corpus()
            .into_iter()
            .find(|problem| problem.id == "pappus-hexagon")
            .expect("pappus-hexagon is in the corpus");
        assert_eq!(full.nondegeneracy.len(), 3, "three conditions are stated");
        let mut certified = 0usize;
        for index in 0..full.nondegeneracy.len() {
            let condition = full.nondegeneracy[index].clone();
            let id = condition.id.clone();
            let restricted = GeometryProblem {
                nondegeneracy: vec![condition],
                degenerate_witnesses: full
                    .degenerate_witnesses
                    .iter()
                    .filter(|witness| witness.condition_id == id)
                    .cloned()
                    .collect(),
                ..full.clone()
            };
            assert_eq!(
                restricted.degenerate_witnesses.len(),
                1,
                "`{id}` must keep its own counterexample"
            );
            let ProofOutcome::Certified(certificate) =
                certify_by_linear_elimination(&restricted, Some(geometry_limits()))
            else {
                panic!("`{id}` alone must certify pappus-hexagon");
            };
            assert_eq!(certificate.saturations.len(), 1);
            assert_eq!(certificate.saturations[0].condition_id, id);
            for (slot, hypothesis) in certificate.hypotheses.iter().enumerate() {
                assert_eq!(
                    certificate.generators[slot], hypothesis.poly,
                    "generator {slot} must be the stated hypothesis `{}` unchanged",
                    hypothesis.id
                );
            }
            identity_recombines(&certificate);
            certified += 1;
        }
        assert_eq!(
            certified, 3,
            "every stated condition must have been tried on its own"
        );
    }

    /// The signature Rabinowitsch shape, generalised to a squared multiplier.
    ///
    /// The Gröbner route's saturated certificates come out with the saturation
    /// generator's cofactor equal to **minus the conclusion**, which is the `N = 1`
    /// case of `1 = zᴺdᴺ − g·Σ C(N,i)g^{i−1}`. `euler-line`'s multiplier is
    /// `4·collinear(A,B,C)²`, so `N = 2` and the cofactor must be
    /// `−conclusion·(1 + d·z)`. Asserting the exact polynomial is what turns "the
    /// division works" into something that would fail loudly if the binomial
    /// series were off by a term.
    #[test]
    fn the_squared_multiplier_produces_the_expected_rabinowitsch_cofactor() {
        let problem = crate::geometry_corpus::corpus()
            .into_iter()
            .find(|problem| problem.id == "euler-line")
            .expect("euler-line is in the corpus");
        let ProofOutcome::Certified(certificate) = certify_by_linear_elimination(&problem, None)
        else {
            panic!("euler-line must certify");
        };
        let saturation = &certificate.saturations[0];
        let expected = certificate.conclusions[0]
            .poly
            .mul(
                &saturation
                    .condition
                    .mul(&MvPoly::var(&saturation.var))
                    .expect("d·z")
                    .add(&MvPoly::constant(Rational::integer(1)))
                    .expect("1 + d·z"),
            )
            .expect("product")
            .neg()
            .expect("negation");
        assert_eq!(
            certificate.conclusions[0].cofactors[certificate.hypotheses.len()],
            expected,
            "the saturation cofactor must be −conclusion·(1 + d·z)"
        );
    }

    /// A false conclusion must not certify on this route either, and the reason
    /// must not be a lucky decline: the elimination happily produces an identity
    /// for `multiplier · target`, and it is the *residue* that has to stay
    /// nonzero.
    #[test]
    fn the_linear_route_refuses_a_false_conclusion() {
        let points = quadrilateral();
        let problem = GeometryProblem {
            id: "false".into(),
            title: "false".into(),
            statement: "test fixture".into(),
            coordinate_gloss: Vec::new(),
            hypotheses: parallelogram_hypotheses(&points),
            nondegeneracy: vec![flat_condition(&points)],
            conclusions: vec![Constraint::new(
                "diagonals-perpendicular",
                "AC ⟂ BD, which is false",
                perpendicular(&points[0], &points[2], &points[1], &points[3]).expect("polynomial"),
            )],
            degenerate_witnesses: Vec::new(),
            generic_witnesses: Vec::new(),
        };
        for handover in [None, Some(geometry_limits())] {
            assert!(
                !matches!(
                    certify_by_linear_elimination(&problem, handover),
                    ProofOutcome::Certified(_)
                ),
                "a false conclusion must never certify, handover = {}",
                handover.is_some()
            );
        }
    }

    /// A determinant that is not a product of the **stated** conditions is never
    /// used as a multiplier — and, with a handover available, the route must not
    /// quietly become a second general-purpose prover instead.
    ///
    /// This is the soundness-relevant half of the route, and it now has two
    /// mechanisms rather than one. `licensed_blocks` refuses the block up front,
    /// because dividing a determinant out is only legitimate where it is nonzero
    /// and the only place this module may get that permission is a condition the
    /// problem declares. `invert_multiplier` still refuses at the far end, so a
    /// decomposition that slipped through the filter cannot produce a certificate.
    ///
    /// Thales is the case in the corpus: the elimination would clear its residue
    /// with a two-term multiplier, and that polynomial is nobody's declared
    /// condition.
    ///
    /// The `Some(handover)` half is the one that protects the *committed*
    /// evidence. Thales's conclusion is in the hypothesis ideal outright, so a
    /// handover handed the whole untouched target would very likely prove it —
    /// by a different identity than the certificate already in
    /// `artifacts/geometry-certificates/`. The empty-block guard is what keeps
    /// "the linear route finishes what the elimination started" a rule rather
    /// than a hope.
    #[test]
    fn an_unlicensed_determinant_is_never_used_as_a_multiplier() {
        let problem = crate::geometry_corpus::corpus()
            .into_iter()
            .find(|problem| problem.id == "thales-right-angle-in-semicircle")
            .expect("thales is in the corpus");
        let hypotheses: Vec<MvPoly> = problem
            .hypotheses
            .iter()
            .map(|hypothesis| hypothesis.poly.clone())
            .collect();
        let conditions: Vec<MvPoly> = problem
            .nondegeneracy
            .iter()
            .map(|condition| condition.poly.clone())
            .collect();
        let detected = detect_linear_blocks(&hypotheses, &problem.conclusions[0].poly);
        assert!(
            !detected.is_empty(),
            "the detector does find a block here; the point is that it is refused"
        );
        assert!(
            licensed_blocks(detected, &conditions).is_empty(),
            "no stated condition licenses that determinant"
        );
        for handover in [None, Some(geometry_limits())] {
            assert!(
                !matches!(
                    certify_by_linear_elimination(&problem, handover),
                    ProofOutcome::Certified(_)
                ),
                "the linear route must not certify thales, handover = {}",
                handover.is_some()
            );
        }
        // And the theorem is nonetheless true and unconditional, which the
        // Gröbner route establishes — so the decline above is a limitation of the
        // route, not a statement about the theorem.
        let ProofOutcome::Certified(certificate) = certify(&problem, geometry_limits()) else {
            panic!("thales certifies on the general route");
        };
        assert!(certificate.saturations.is_empty());
    }

    /// `factors_into` is the whole licensing rule, so it is tested on its own
    /// rather than only through a theorem.
    #[test]
    fn licensing_accepts_powers_and_rational_multiples_and_nothing_else() {
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let condition = x.sub(&y).expect("polynomial");
        let four = MvPoly::constant(Rational::integer(4));
        assert!(factors_into(&condition, std::slice::from_ref(&condition)));
        assert!(factors_into(
            &four.mul(&condition).expect("polynomial"),
            std::slice::from_ref(&condition)
        ));
        assert!(factors_into(
            &condition.pow(3).expect("polynomial"),
            std::slice::from_ref(&condition)
        ));
        assert!(
            factors_into(&four, std::slice::from_ref(&condition)),
            "a nonzero rational needs no condition at all"
        );
        assert!(
            !factors_into(
                &x.add(&y).expect("polynomial"),
                std::slice::from_ref(&condition)
            ),
            "x + y is not a power of x − y"
        );
        assert!(
            !factors_into(
                &condition.mul(&x).expect("polynomial"),
                std::slice::from_ref(&condition)
            ),
            "a leftover factor is not licensed just because part of it is"
        );
        assert!(
            !factors_into(&MvPoly::zero(), std::slice::from_ref(&condition)),
            "the zero polynomial is not a nonzero rational"
        );
    }

    /// `certify_any_route` must not disturb what the Gröbner route already
    /// proves. This is the assertion behind "7 unchanged, 1 written".
    #[test]
    fn the_route_selector_reproduces_the_groebner_certificate_exactly() {
        // Theorems the Gröbner route cannot be *run* on here. `euler-line` and
        // `pappus-hexagon` do not return on it inside any budget anyone waits for
        // — that is why they exist on the linear route at all — and the rhombus
        // returns but takes 21 s in release, which is not a unit test.
        //
        // The hazard this list carries is worth naming: a new divergent theorem
        // added to the corpus and *not* added here makes this test hang rather
        // than fail, and a hang reads like a slow machine. The count assertion
        // below is derived from the corpus so the list cannot silently shrink,
        // but nothing can make "does not return" cheap to probe.
        const UNREACHED_BY_BUCHBERGER: [&str; 5] = [
            "euler-line",
            "rhombus-diagonals-perpendicular",
            "pappus-hexagon",
            // `simson-line` joined the corpus on 2026-08-15 and walked straight
            // into the hazard the paragraph above names. Fourteen coordinates and
            // three Rabinowitsch generators: the reduction is bounded by
            // `geometry_limits` so it does terminate, but it had not returned
            // after 90 s in release when the run was killed, which is not a unit
            // test. Leaving it off this list did not FAIL the test, it stalled
            // it — and a stall reads like a slow machine rather than a defect,
            // which is exactly what the warning above predicted and exactly how
            // it presented.
            "simson-line",
            // `tetrahedron-medians-concurrent` joined the corpus on 2026-09-05
            // from `geometry_beyond` and did exactly what the paragraph above
            // predicts: the debug crate sweep sat in this test for an hour with
            // one core spinning and no failure. Its search costs 769 s in
            // release on the certifier's route (the linear-block detector is
            // scoped per conclusion and each per-axis conclusion sees one of
            // the three coordinates); the theorem is re-checked from its
            // committed artifact by `geometry_certificate_artifacts` instead.
            "tetrahedron-medians-concurrent",
        ];
        let corpus = crate::geometry_corpus::corpus();
        let expected = corpus.len() - UNREACHED_BY_BUCHBERGER.len();
        let mut compared = 0usize;
        for problem in corpus {
            if UNREACHED_BY_BUCHBERGER.contains(&problem.id.as_str()) {
                continue;
            }
            let combined = certify_any_route(&problem, geometry_limits());
            let direct = certify(&problem, geometry_limits());
            assert_eq!(
                combined, direct,
                "{}: the route selector changed an existing certificate",
                problem.id
            );
            compared += 1;
        }
        assert_eq!(
            compared, expected,
            "every corpus theorem the Gröbner route reaches must be compared"
        );
        assert!(compared >= 5, "compared only {compared} theorems");
    }
}
