//! Cofactor-tracking ideal reduction: Gröbner reduction that emits a **witness**.
//!
//! [`groebner`](crate::groebner) decides ideal membership — `ideal_contains`
//! returns a bare `bool`. A bare `bool` is not evidence: a consumer that wants to
//! turn "`1` lies in the ideal generated by these polynomials" into a refutation
//! has to trust `Buchberger`'s algorithm, the `lex` leading-term selection, the
//! `MvPoly` canonicalization and every exact-rational operation underneath.
//!
//! This module runs the same algorithm while carrying, alongside every
//! polynomial, its **representation in the original generators**. The result is
//! an identity
//!
//! ```text
//! target  =  Σᵢ cofactorᵢ · generatorᵢ  +  remainder
//! ```
//!
//! that a checker can re-derive with nothing but polynomial addition and
//! multiplication — no Gröbner machinery, no monomial order, no S-polynomials.
//! The consumer of that identity (`crates/axeyum-solver/src/cas_certificate.rs`)
//! shares no code with this module: it re-expands the generators from the
//! original terms, multiplies through, and confirms the identity itself. A bug
//! anywhere in here can therefore lose a refutation but cannot manufacture one.
//!
//! # Why the identity is the whole certificate
//!
//! Suppose the identity above holds as polynomials and `remainder` is the
//! constant `c`. In any model where every `generatorᵢ` evaluates to `0`, the
//! right-hand side evaluates to `c`, so `target` evaluates to `c` — regardless of
//! what the variables denote and regardless of how the cofactors were found. With
//! `target = 1` and `c = 0` this is `1 = 0`; with `target` a hypothesis known to
//! be non-negative and `c < 0` it is `0 ≤ target = c < 0`. Both are contradictions
//! whose justification is a *polynomial identity*, which is decidable by
//! expansion.
//!
//! # Bounds
//!
//! Every loop is bounded by an explicit, caller-supplied [`Limits`] step count
//! rather than a clock, so the same input always produces the same outcome
//! (determinism is a public API promise). Exceeding a bound, or any `i128`/`u32`
//! overflow in the exact rational arithmetic, yields [`CofactorOutcome::Declined`]
//! — never a guessed answer.

use crate::groebner::{
    Exponents, leading_term, monomial_divides, monomial_lcm, monomial_quotient, single_term,
};
use crate::mvpoly::MvPoly;
use axeyum_ir::Rational;

/// Deterministic step ceilings for one cofactor-tracked computation.
///
/// These are step *counts*, not durations. `Dickson`'s lemma already guarantees
/// termination; these bounds exist so a caller on a latency-sensitive path (the
/// solver's fast dispatch) can bound the work without a wall clock.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Limits {
    /// Maximum term-cancelling steps across *all* reductions in one call.
    pub reduction_steps: u64,
    /// Maximum S-pairs processed by the `Buchberger` loop.
    pub pair_iterations: u64,
    /// Maximum size the intermediate basis may reach.
    pub basis_size: usize,
    /// Maximum monomials in any single intermediate polynomial (a cofactor
    /// included). Cofactors are the artifact that must stay small enough to check.
    pub poly_terms: usize,
}

impl Limits {
    /// Ceilings sized for an interactive dispatch path: large enough for the
    /// small systems that arise from a handful of asserted equations, small
    /// enough that a pathological input costs microseconds rather than seconds.
    #[must_use]
    pub fn fast() -> Limits {
        Limits {
            reduction_steps: 20_000,
            pair_iterations: 4_000,
            basis_size: 64,
            poly_terms: 512,
        }
    }
}

impl Default for Limits {
    fn default() -> Limits {
        Limits::fast()
    }
}

/// The outcome of a cofactor-tracked reduction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CofactorOutcome {
    /// `target = Σ cofactors[i] · generators[i] + remainder`, exactly, with one
    /// cofactor per generator in the caller's order.
    Reduced {
        /// One cofactor per generator, positionally aligned with the input slice.
        cofactors: Vec<MvPoly>,
        /// The normal form of `target` modulo a Gröbner basis of the generators.
        /// Zero exactly when `target` lies in the ideal.
        remainder: MvPoly,
    },
    /// A ceiling tripped or an exact coefficient left the `i128` range. Nothing
    /// is claimed about ideal membership.
    Declined,
}

/// A polynomial carried together with its representation in the generators:
/// the invariant is `poly == Σ rep[i] · generators[i]`.
#[derive(Debug, Clone)]
struct Tracked {
    poly: MvPoly,
    rep: Vec<MvPoly>,
}

/// A running step budget shared by every loop in one call.
struct Budget {
    reduction_steps: u64,
    limits: Limits,
}

impl Budget {
    fn spend_reduction(&mut self) -> Option<()> {
        self.reduction_steps = self.reduction_steps.checked_sub(1)?;
        Some(())
    }

    fn capped(&self, poly: &MvPoly) -> Option<()> {
        (poly.term_count() <= self.limits.poly_terms).then_some(())
    }
}

/// Reduce `target` modulo a Gröbner basis of `generators`, returning the
/// remainder **and** cofactors that witness the reduction.
///
/// The returned identity `target = Σ cofactors[i]·generators[i] + remainder` is
/// exact. `remainder` is zero exactly when `target` lies in the ideal generated
/// by `generators` (reduction modulo a Gröbner basis is the ideal-membership
/// test — Cox–Little–O'Shea §2.9), but a *nonzero* remainder is useful in its own
/// right: when it is a constant `c`, the identity says `target ≡ c` modulo the
/// ideal, i.e. `target` takes the value `c` at every common zero of the
/// generators.
///
/// Zero generators are permitted and get a zero cofactor. An empty generator list
/// yields `target` itself as the remainder.
#[must_use]
pub fn reduce_with_cofactors(
    generators: &[MvPoly],
    target: &MvPoly,
    limits: Limits,
) -> CofactorOutcome {
    match reduce_with_cofactors_inner(generators, target, limits) {
        Some((cofactors, remainder)) => CofactorOutcome::Reduced {
            cofactors,
            remainder,
        },
        None => CofactorOutcome::Declined,
    }
}

/// Cofactors witnessing `1 ∈ ideal(generators)` — a weak-Nullstellensatz
/// certificate that the generators have **no common zero over any field
/// containing ℚ** (in particular none over ℝ, hence none over ℤ).
///
/// Returns `Reduced { remainder, .. }` with `remainder` zero on success. A
/// nonzero remainder means `1` is not in the ideal, which is *not* a claim that
/// the system is satisfiable — only that this route says nothing.
#[must_use]
pub fn unit_ideal_cofactors(generators: &[MvPoly], limits: Limits) -> CofactorOutcome {
    reduce_with_cofactors(generators, &MvPoly::constant(Rational::integer(1)), limits)
}

fn reduce_with_cofactors_inner(
    generators: &[MvPoly],
    target: &MvPoly,
    limits: Limits,
) -> Option<(Vec<MvPoly>, MvPoly)> {
    if generators.len() > limits.basis_size {
        return None;
    }
    let mut budget = Budget {
        reduction_steps: limits.reduction_steps,
        limits,
    };
    let basis = tracked_groebner_basis(generators, &mut budget)?;
    let start = Tracked {
        poly: target.clone(),
        rep: zero_rep(generators.len()),
    };
    let (remainder, quotients) = reduce_tracked(&start, &basis, &mut budget)?;
    // `target = remainder + Σ quotients[j]·basis[j]` and `basis[j] = Σ rep[i]·gen[i]`,
    // so the cofactor of generator `i` is `Σ_j quotients[j]·basis[j].rep[i]`.
    let mut cofactors = zero_rep(generators.len());
    for (quotient, element) in quotients.iter().zip(basis.iter()) {
        if quotient.is_zero() {
            continue;
        }
        for (slot, share) in cofactors.iter_mut().zip(element.rep.iter()) {
            if share.is_zero() {
                continue;
            }
            let product = quotient.mul(share)?;
            budget.capped(&product)?;
            *slot = slot.add(&product)?;
            budget.capped(slot)?;
        }
    }
    Some((cofactors, remainder.poly))
}

fn zero_rep(len: usize) -> Vec<MvPoly> {
    vec![MvPoly::zero(); len]
}

/// `Buchberger`'s algorithm with every basis element carrying its representation
/// in the original generators. The basis is **not** trimmed to the reduced
/// Gröbner basis: trimming would have to re-derive representations for no gain,
/// and reduction to zero modulo any Gröbner basis is already the membership test.
fn tracked_groebner_basis(generators: &[MvPoly], budget: &mut Budget) -> Option<Vec<Tracked>> {
    let mut basis: Vec<Tracked> = Vec::with_capacity(generators.len());
    for (index, generator) in generators.iter().enumerate() {
        if generator.is_zero() {
            continue;
        }
        budget.capped(generator)?;
        let mut rep = zero_rep(generators.len());
        rep[index] = MvPoly::constant(Rational::integer(1));
        basis.push(Tracked {
            poly: generator.clone(),
            rep,
        });
    }
    if basis.is_empty() {
        return Some(Vec::new());
    }

    let mut pairs: Vec<(usize, usize)> = Vec::new();
    for higher in 1..basis.len() {
        for lower in 0..higher {
            pairs.push((lower, higher));
        }
    }
    // A FIFO queue over a `Vec` with an explicit cursor: deterministic order,
    // no allocation churn from the front.
    let mut cursor = 0usize;
    let mut iterations: u64 = 0;
    while cursor < pairs.len() {
        let (lower, higher) = pairs[cursor];
        cursor += 1;
        iterations += 1;
        if iterations > budget.limits.pair_iterations {
            return None;
        }
        let s_poly = tracked_s_polynomial(&basis[lower], &basis[higher], budget)?;
        let (remainder, quotients) = reduce_tracked(&s_poly, &basis, budget)?;
        if remainder.poly.is_zero() {
            continue;
        }
        // `remainder.rep` already accounts for the subtractions: `reduce_tracked`
        // returns it in terms of the generators, not the basis.
        let _ = &quotients;
        let new_index = basis.len();
        for existing in 0..new_index {
            pairs.push((existing, new_index));
        }
        basis.push(remainder);
        if basis.len() > budget.limits.basis_size {
            return None;
        }
    }
    Some(basis)
}

/// The S-polynomial of two tracked elements, with its representation derived from
/// theirs: `S = f·A − g·B` implies `S.rep = f·A.rep − g·B.rep`.
fn tracked_s_polynomial(first: &Tracked, second: &Tracked, budget: &mut Budget) -> Option<Tracked> {
    let (first_mono, first_coeff) = leading_term(&first.poly)?;
    let (second_mono, second_coeff) = leading_term(&second.poly)?;
    let lcm = monomial_lcm(&first_mono, &second_mono);
    let first_factor = single_term(
        &monomial_quotient(&lcm, &first_mono),
        Rational::integer(1).checked_div(first_coeff)?,
    )?;
    let second_factor = single_term(
        &monomial_quotient(&lcm, &second_mono),
        Rational::integer(1).checked_div(second_coeff)?,
    )?;
    let poly = first_factor
        .mul(&first.poly)?
        .sub(&second_factor.mul(&second.poly)?)?;
    budget.capped(&poly)?;
    let mut rep = Vec::with_capacity(first.rep.len());
    for (left, right) in first.rep.iter().zip(second.rep.iter()) {
        let combined = first_factor.mul(left)?.sub(&second_factor.mul(right)?)?;
        budget.capped(&combined)?;
        rep.push(combined);
    }
    Some(Tracked { poly, rep })
}

/// Multivariate division of `target` by `basis`, tracking both the per-basis
/// quotients and the remainder's representation in the original generators.
///
/// Maintains the invariant `target.poly = current + remainder + Σ q[j]·basis[j].poly`
/// and returns `(remainder, q)` once `current` is zero. The returned remainder's
/// `rep` is `target.rep − Σ q[j]·basis[j].rep`, which is exactly its
/// representation in the generators.
fn reduce_tracked(
    target: &Tracked,
    basis: &[Tracked],
    budget: &mut Budget,
) -> Option<(Tracked, Vec<MvPoly>)> {
    let leads: Vec<(Exponents, Rational)> = basis
        .iter()
        .map(|element| leading_term(&element.poly))
        .collect::<Option<Vec<_>>>()?;

    let mut quotients = vec![MvPoly::zero(); basis.len()];
    let mut remainder = MvPoly::zero();
    let mut current = target.poly.clone();
    while !current.is_zero() {
        budget.spend_reduction()?;
        let (lead_mono, lead_coeff) = leading_term(&current)?;
        let mut cancelled = false;
        for (index, (element_mono, element_coeff)) in leads.iter().enumerate() {
            if !monomial_divides(element_mono, &lead_mono) {
                continue;
            }
            let quotient_mono = monomial_quotient(&lead_mono, element_mono);
            let quotient_coeff = lead_coeff.checked_div(*element_coeff)?;
            let factor = single_term(&quotient_mono, quotient_coeff)?;
            current = current.sub(&factor.mul(&basis[index].poly)?)?;
            budget.capped(&current)?;
            quotients[index] = quotients[index].add(&factor)?;
            budget.capped(&quotients[index])?;
            cancelled = true;
            break;
        }
        if !cancelled {
            let lead = single_term(&lead_mono, lead_coeff)?;
            remainder = remainder.add(&lead)?;
            budget.capped(&remainder)?;
            current = current.sub(&lead)?;
        }
    }

    // `remainder = target − Σ q[j]·basis[j]`, so subtract the same combination
    // from `target`'s representation to get the remainder's.
    let mut rep = target.rep.clone();
    for (quotient, element) in quotients.iter().zip(basis.iter()) {
        if quotient.is_zero() {
            continue;
        }
        for (slot, share) in rep.iter_mut().zip(element.rep.iter()) {
            if share.is_zero() {
                continue;
            }
            let product = quotient.mul(share)?;
            budget.capped(&product)?;
            *slot = slot.sub(&product)?;
            budget.capped(slot)?;
        }
    }
    Some((
        Tracked {
            poly: remainder,
            rep,
        },
        quotients,
    ))
}

#[cfg(test)]
mod tests {
    use super::{CofactorOutcome, Limits, reduce_with_cofactors, unit_ideal_cofactors};
    use crate::mvpoly::MvPoly;
    use axeyum_ir::Rational;

    /// Re-derive `Σ cofactors[i]·generators[i] + remainder` independently of the
    /// tracking machinery and confirm it equals `target`. This mirrors what the
    /// solver-side checker does, so a broken invariant fails here first.
    fn recombine(generators: &[MvPoly], cofactors: &[MvPoly], remainder: &MvPoly) -> MvPoly {
        let mut acc = remainder.clone();
        for (cofactor, generator) in cofactors.iter().zip(generators.iter()) {
            acc = acc
                .add(&cofactor.mul(generator).expect("product"))
                .expect("sum");
        }
        acc
    }

    fn int(value: i128) -> MvPoly {
        MvPoly::constant(Rational::integer(value))
    }

    #[test]
    fn unit_ideal_certificate_recombines() {
        // x + y − 3 = 0 and x·y − 5 = 0 force x² + y² = 9 − 10 = −1, so adding
        // x² + y² = 1 makes the system inconsistent: 1 lies in the ideal.
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let generators = vec![
            x.add(&y).unwrap().sub(&int(3)).unwrap(),
            x.mul(&y).unwrap().sub(&int(5)).unwrap(),
            x.mul(&x)
                .unwrap()
                .add(&y.mul(&y).unwrap())
                .unwrap()
                .sub(&int(1))
                .unwrap(),
        ];
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = unit_ideal_cofactors(&generators, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(remainder.is_zero(), "1 must reduce to 0: {remainder:?}");
        assert_eq!(cofactors.len(), generators.len());
        let combined = recombine(&generators, &cofactors, &remainder);
        assert_eq!(combined, int(1), "Σ cᵢ·gᵢ must be exactly 1");
    }

    #[test]
    fn a_consistent_system_does_not_contain_the_unit() {
        // x − 1 = 0 and y − 2 = 0 have the common zero (1, 2).
        let generators = vec![
            MvPoly::var("x").sub(&int(1)).unwrap(),
            MvPoly::var("y").sub(&int(2)).unwrap(),
        ];
        let CofactorOutcome::Reduced { remainder, .. } =
            unit_ideal_cofactors(&generators, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(!remainder.is_zero(), "1 is not in a proper ideal");
    }

    #[test]
    fn reduction_to_a_constant_recombines() {
        // Modulo (x + y − 3, x·y − 5), the polynomial x² + y² is the constant −1.
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let generators = vec![
            x.add(&y).unwrap().sub(&int(3)).unwrap(),
            x.mul(&y).unwrap().sub(&int(5)).unwrap(),
        ];
        let target = x.mul(&x).unwrap().add(&y.mul(&y).unwrap()).unwrap();
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = reduce_with_cofactors(&generators, &target, Limits::fast())
        else {
            panic!("declined");
        };
        assert_eq!(remainder, int(-1), "x² + y² ≡ −1 mod the ideal");
        assert_eq!(recombine(&generators, &cofactors, &remainder), target);
    }

    #[test]
    fn empty_generators_leave_the_target_alone() {
        let target = MvPoly::var("x");
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = reduce_with_cofactors(&[], &target, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(cofactors.is_empty());
        assert_eq!(remainder, target);
    }

    #[test]
    fn zero_generators_get_zero_cofactors() {
        let generators = vec![MvPoly::zero(), MvPoly::var("x").sub(&int(1)).unwrap()];
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = reduce_with_cofactors(&generators, &MvPoly::var("x"), Limits::fast())
        else {
            panic!("declined");
        };
        assert_eq!(remainder, int(1));
        assert!(cofactors[0].is_zero(), "the zero generator is unused");
        assert_eq!(
            recombine(&generators, &cofactors, &remainder),
            MvPoly::var("x")
        );
    }

    #[test]
    fn a_tight_budget_declines_rather_than_guessing() {
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let generators = vec![
            x.add(&y).unwrap().sub(&int(3)).unwrap(),
            x.mul(&y).unwrap().sub(&int(5)).unwrap(),
            x.mul(&x)
                .unwrap()
                .add(&y.mul(&y).unwrap())
                .unwrap()
                .sub(&int(1))
                .unwrap(),
        ];
        let starved = Limits {
            reduction_steps: 1,
            ..Limits::fast()
        };
        assert_eq!(
            unit_ideal_cofactors(&generators, starved),
            CofactorOutcome::Declined
        );
    }

    /// Three variables, degree 3: the shape the Rado symbolic-parameter work
    /// needs. `x + y + z = 0`, `x·y + y·z + z·x = 0` and `x·y·z = 1` are the
    /// elementary symmetric functions of the roots of `t³ − 1`, so adding
    /// `x³ + y³ + z³ = 4` (the true value is 3) is inconsistent.
    #[test]
    fn three_variable_cubic_system_is_refuted_with_a_witness() {
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let z = MvPoly::var("z");
        let cube = |v: &MvPoly| v.pow(3).unwrap();
        let generators = vec![
            x.add(&y).unwrap().add(&z).unwrap(),
            x.mul(&y)
                .unwrap()
                .add(&y.mul(&z).unwrap())
                .unwrap()
                .add(&z.mul(&x).unwrap())
                .unwrap(),
            x.mul(&y).unwrap().mul(&z).unwrap().sub(&int(1)).unwrap(),
            cube(&x)
                .add(&cube(&y))
                .unwrap()
                .add(&cube(&z))
                .unwrap()
                .sub(&int(4))
                .unwrap(),
        ];
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = unit_ideal_cofactors(&generators, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(remainder.is_zero());
        assert_eq!(recombine(&generators, &cofactors, &remainder), int(1));
    }
}
