//! Cofactor-tracking ideal reduction: Gröbner reduction that emits a **witness**.
//!
//! [`groebner`](crate::groebner) decides ideal membership — `ideal_contains`
//! returns a bare `bool`. A bare `bool` is not evidence: a consumer that wants to
//! turn "`1` lies in the ideal generated by these polynomials" into a refutation
//! has to trust `Buchberger`'s algorithm, the `lex` leading-term selection, the
//! `MvPoly` canonicalization and every exact-rational operation underneath.
//!
//! This module runs the same algorithm while carrying, alongside every
//! polynomial, its **representation in the original generators**. The result is
//! an identity
//!
//! ```text
//! target  =  Σᵢ cofactorᵢ · generatorᵢ  +  remainder
//! ```
//!
//! that a checker can re-derive with nothing but polynomial addition and
//! multiplication — no Gröbner machinery, no monomial order, no S-polynomials.
//! The consumer of that identity (`crates/axeyum-solver/src/cas_certificate.rs`)
//! shares no code with this module: it re-expands the generators from the
//! original terms, multiplies through, and confirms the identity itself. A bug
//! anywhere in here can therefore lose a refutation but cannot manufacture one.
//!
//! # Why the identity is the whole certificate
//!
//! Suppose the identity above holds as polynomials and `remainder` is the
//! constant `c`. In any model where every `generatorᵢ` evaluates to `0`, the
//! right-hand side evaluates to `c`, so `target` evaluates to `c` — regardless of
//! what the variables denote and regardless of how the cofactors were found. With
//! `target = 1` and `c = 0` this is `1 = 0`; with `target` a hypothesis known to
//! be non-negative and `c < 0` it is `0 ≤ target = c < 0`. Both are contradictions
//! whose justification is a *polynomial identity*, which is decidable by
//! expansion.
//!
//! # Bounds
//!
//! Every loop is bounded by an explicit, caller-supplied [`Limits`] step count
//! rather than a clock, so the same input always produces the same outcome
//! (determinism is a public API promise). Exceeding a bound, or any `i128`/`u32`
//! overflow in the exact rational arithmetic, yields [`CofactorOutcome::Declined`]
//! — never a guessed answer.
//!
//! The decline carries a [`DeclineReason`], and the distinction it draws is not
//! cosmetic. A *ceiling* says the caller asked for less work than the problem
//! needs: raise the budget and try again. An *overflow* says the exact
//! arithmetic left the `i128` range, which no budget changes. Reporting both as
//! one value made a whole class of measurement impossible — a lane investigating
//! why `euler-line` produced nothing could not tell whether it was looking at a
//! cost problem or a width problem, and had to record "not established" in place
//! of a result. One enum makes that measurement free.

use crate::groebner::{
    Exponents, MonomialOrder, leading_term_in, monomial_divides, monomial_lcm, monomial_quotient,
    single_term,
};
use crate::mvpoly::MvPoly;
use axeyum_ir::Rational;

/// Deterministic step ceilings for one cofactor-tracked computation.
///
/// These are step *counts*, not durations. `Dickson`'s lemma already guarantees
/// termination; these bounds exist so a caller on a latency-sensitive path (the
/// solver's fast dispatch) can bound the work without a wall clock.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Limits {
    /// Maximum term-cancelling steps across *all* reductions in one call.
    pub reduction_steps: u64,
    /// Maximum S-pairs processed by the `Buchberger` loop.
    pub pair_iterations: u64,
    /// Maximum size the intermediate basis may reach.
    pub basis_size: usize,
    /// Maximum monomials in any single intermediate polynomial (a cofactor
    /// included). Cofactors are the artifact that must stay small enough to check.
    pub poly_terms: usize,
    /// The monomial order leading terms are selected by.
    ///
    /// A knob rather than a constant because it is the single largest lever on
    /// the cost of a basis, and because which setting wins is a *measurement*:
    /// `grevlex` is the standard recommendation for plain ideal membership, and
    /// this field is what makes the comparison runnable on the corpus instead of
    /// argued from the literature. It cannot change a verdict — only whether one
    /// is reached inside the ceilings.
    pub order: MonomialOrder,
}

impl Limits {
    /// Ceilings sized for an interactive dispatch path: large enough for the
    /// small systems that arise from a handful of asserted equations, small
    /// enough that a pathological input costs microseconds rather than seconds.
    #[must_use]
    pub fn fast() -> Limits {
        Limits {
            reduction_steps: 20_000,
            pair_iterations: 4_000,
            basis_size: 64,
            poly_terms: 512,
            order: MonomialOrder::Lex,
        }
    }
}

impl Default for Limits {
    fn default() -> Limits {
        Limits::fast()
    }
}

/// Why a cofactor-tracked computation stopped without an answer.
///
/// Exactly one of these is a statement about the *budget* and one is a statement
/// about the *arithmetic*: [`DeclineReason::is_ceiling`] separates them. A
/// ceiling is worth retrying with a larger [`Limits`]; an overflow is not.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DeclineReason {
    /// The shared [`Limits::reduction_steps`] budget ran out.
    ReductionSteps,
    /// The [`Limits::pair_iterations`] budget ran out in `Buchberger`'s loop.
    PairIterations,
    /// The generator list, or the intermediate basis, exceeded
    /// [`Limits::basis_size`].
    BasisSize,
    /// A single intermediate polynomial or cofactor exceeded
    /// [`Limits::poly_terms`] monomials.
    PolyTerms,
    /// An exact coefficient left the `i128` range (or a `u32` exponent
    /// overflowed). The only non-ceiling failure this module can produce: every
    /// other `None` on these paths is guarded by a ceiling above.
    Overflow,
}

impl DeclineReason {
    /// Whether this decline is a tripped budget rather than an arithmetic
    /// failure — i.e. whether a larger [`Limits`] could change the answer.
    #[must_use]
    pub fn is_ceiling(self) -> bool {
        !matches!(self, DeclineReason::Overflow)
    }
}

/// The outcome of a cofactor-tracked reduction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CofactorOutcome {
    /// `target = Σ cofactors[i] · generators[i] + remainder`, exactly, with one
    /// cofactor per generator in the caller's order.
    Reduced {
        /// One cofactor per generator, positionally aligned with the input slice.
        cofactors: Vec<MvPoly>,
        /// The normal form of `target` modulo a Gröbner basis of the generators.
        /// Zero exactly when `target` lies in the ideal.
        remainder: MvPoly,
    },
    /// The computation stopped without an answer, with the reason recorded.
    /// Nothing is claimed about ideal membership either way.
    Declined(DeclineReason),
}

/// A polynomial carried together with its representation in the generators:
/// the invariant is `poly == Σ rep[i] · generators[i]`.
#[derive(Debug, Clone)]
struct Tracked {
    poly: MvPoly,
    rep: Vec<MvPoly>,
}

/// A running step budget shared by every loop in one call, together with the
/// reason the first failure occurred.
struct Budget {
    reduction_steps: u64,
    limits: Limits,
    /// The first decline reason recorded; later failures do not overwrite it,
    /// because the first one is the cause and the rest are consequences.
    reason: Option<DeclineReason>,
}

impl Budget {
    fn new(limits: Limits) -> Budget {
        Budget {
            reduction_steps: limits.reduction_steps,
            limits,
            reason: None,
        }
    }

    /// Record `reason` and yield `None`, for a ceiling detected inline.
    fn decline<T>(&mut self, reason: DeclineReason) -> Option<T> {
        self.reason.get_or_insert(reason);
        None
    }

    /// Pass a value through, attributing a `None` from the exact arithmetic to
    /// [`DeclineReason::Overflow`].
    ///
    /// Every `?` on an `MvPoly` or [`Rational`] operation in this module goes
    /// through here, which is what makes the ceiling/overflow split exhaustive
    /// rather than a guess about which failure came first.
    fn arith<T>(&mut self, value: Option<T>) -> Option<T> {
        if value.is_none() {
            self.reason.get_or_insert(DeclineReason::Overflow);
        }
        value
    }

    /// The recorded reason. Only called after a `None` has propagated, so a
    /// reason has always been recorded; the fallback keeps the function total.
    fn reason(&self) -> DeclineReason {
        self.reason.unwrap_or(DeclineReason::Overflow)
    }

    /// Forget the recorded reason, so the next target in a shared-budget call
    /// reports its own cause rather than its predecessor's.
    fn reset_reason(&mut self) {
        self.reason = None;
    }

    fn spend_reduction(&mut self) -> Option<()> {
        match self.reduction_steps.checked_sub(1) {
            Some(left) => {
                self.reduction_steps = left;
                Some(())
            }
            None => self.decline(DeclineReason::ReductionSteps),
        }
    }

    fn capped(&mut self, poly: &MvPoly) -> Option<()> {
        if poly.term_count() <= self.limits.poly_terms {
            Some(())
        } else {
            self.decline(DeclineReason::PolyTerms)
        }
    }
}

/// Reduce `target` modulo a Gröbner basis of `generators`, returning the
/// remainder **and** cofactors that witness the reduction.
///
/// The returned identity `target = Σ cofactors[i]·generators[i] + remainder` is
/// exact. `remainder` is zero exactly when `target` lies in the ideal generated
/// by `generators` (reduction modulo a Gröbner basis is the ideal-membership
/// test — Cox–Little–O'Shea §2.9), but a *nonzero* remainder is useful in its own
/// right: when it is a constant `c`, the identity says `target ≡ c` modulo the
/// ideal, i.e. `target` takes the value `c` at every common zero of the
/// generators.
///
/// Zero generators are permitted and get a zero cofactor. An empty generator list
/// yields `target` itself as the remainder.
#[must_use]
pub fn reduce_with_cofactors(
    generators: &[MvPoly],
    target: &MvPoly,
    limits: Limits,
) -> CofactorOutcome {
    let mut budget = Budget::new(limits);
    match reduce_with_cofactors_inner(generators, target, &mut budget) {
        Some((cofactors, remainder)) => CofactorOutcome::Reduced {
            cofactors,
            remainder,
        },
        None => CofactorOutcome::Declined(budget.reason()),
    }
}

/// Cofactors witnessing `1 ∈ ideal(generators)` — a weak-Nullstellensatz
/// certificate that the generators have **no common zero over any field
/// containing ℚ** (in particular none over ℝ, hence none over ℤ).
///
/// Returns `Reduced { remainder, .. }` with `remainder` zero on success. A
/// nonzero remainder means `1` is not in the ideal, which is *not* a claim that
/// the system is satisfiable — only that this route says nothing.
#[must_use]
pub fn unit_ideal_cofactors(generators: &[MvPoly], limits: Limits) -> CofactorOutcome {
    reduce_with_cofactors(generators, &MvPoly::constant(Rational::integer(1)), limits)
}

/// Reduce **several** targets modulo one Gröbner basis of `generators`, sharing
/// the basis computation across all of them.
///
/// Semantically identical to calling [`reduce_with_cofactors`] once per target;
/// the difference is that `Buchberger`'s algorithm runs once rather than `n`
/// times, which is what makes a search over many candidate polynomials
/// affordable. The step budget is shared across the whole call, so the work is
/// still bounded by one deterministic ceiling.
///
/// Returns one outcome per target, positionally aligned. A single
/// [`CofactorOutcome::Declined`] does not poison the others — only the target
/// whose reduction exhausted the shared budget declines, and every target after
/// it declines too, deterministically.
#[must_use]
pub fn reduce_many_with_cofactors(
    generators: &[MvPoly],
    targets: &[MvPoly],
    limits: Limits,
) -> Vec<CofactorOutcome> {
    if generators.len() > limits.basis_size {
        return vec![CofactorOutcome::Declined(DeclineReason::BasisSize); targets.len()];
    }
    let mut budget = Budget::new(limits);
    let Some(basis) = tracked_groebner_basis(generators, &mut budget) else {
        return vec![CofactorOutcome::Declined(budget.reason()); targets.len()];
    };
    targets
        .iter()
        .map(|target| {
            // Each target reports its own cause: the step budget is shared, so a
            // later target may legitimately decline on a ceiling an earlier one
            // consumed, and that is what it should say.
            budget.reset_reason();
            let start = Tracked {
                poly: target.clone(),
                rep: zero_rep(generators.len()),
            };
            match reduce_tracked(&start, &basis, &mut budget).and_then(|(remainder, quotients)| {
                let cofactors = combine(&quotients, &basis, generators.len(), &mut budget)?;
                Some((cofactors, remainder.poly))
            }) {
                Some((cofactors, remainder)) => CofactorOutcome::Reduced {
                    cofactors,
                    remainder,
                },
                None => CofactorOutcome::Declined(budget.reason()),
            }
        })
        .collect()
}

/// `Σ_j quotients[j] · basis[j].rep[i]` for each generator `i` — the cofactor of
/// each original generator implied by a set of per-basis quotients.
fn combine(
    quotients: &[MvPoly],
    basis: &[Tracked],
    generators: usize,
    budget: &mut Budget,
) -> Option<Vec<MvPoly>> {
    let mut cofactors = zero_rep(generators);
    for (quotient, element) in quotients.iter().zip(basis.iter()) {
        if quotient.is_zero() {
            continue;
        }
        for (slot, share) in cofactors.iter_mut().zip(element.rep.iter()) {
            if share.is_zero() {
                continue;
            }
            let product = budget.arith(quotient.mul(share))?;
            budget.capped(&product)?;
            *slot = budget.arith(slot.add(&product))?;
            budget.capped(slot)?;
        }
    }
    Some(cofactors)
}

fn reduce_with_cofactors_inner(
    generators: &[MvPoly],
    target: &MvPoly,
    budget: &mut Budget,
) -> Option<(Vec<MvPoly>, MvPoly)> {
    if generators.len() > budget.limits.basis_size {
        return budget.decline(DeclineReason::BasisSize);
    }
    let basis = tracked_groebner_basis(generators, budget)?;
    let start = Tracked {
        poly: target.clone(),
        rep: zero_rep(generators.len()),
    };
    let (remainder, quotients) = reduce_tracked(&start, &basis, budget)?;
    // `target = remainder + Σ quotients[j]·basis[j]` and `basis[j] = Σ rep[i]·gen[i]`,
    // so the cofactor of generator `i` is `Σ_j quotients[j]·basis[j].rep[i]`.
    let cofactors = combine(&quotients, &basis, generators.len(), budget)?;
    Some((cofactors, remainder.poly))
}

fn zero_rep(len: usize) -> Vec<MvPoly> {
    vec![MvPoly::zero(); len]
}

/// `Buchberger`'s algorithm with every basis element carrying its representation
/// in the original generators. The basis is **not** trimmed to the reduced
/// Gröbner basis: trimming would have to re-derive representations for no gain,
/// and reduction to zero modulo any Gröbner basis is already the membership test.
fn tracked_groebner_basis(generators: &[MvPoly], budget: &mut Budget) -> Option<Vec<Tracked>> {
    let mut basis: Vec<Tracked> = Vec::with_capacity(generators.len());
    for (index, generator) in generators.iter().enumerate() {
        if generator.is_zero() {
            continue;
        }
        budget.capped(generator)?;
        let mut rep = zero_rep(generators.len());
        rep[index] = MvPoly::constant(Rational::integer(1));
        basis.push(Tracked {
            poly: generator.clone(),
            rep,
        });
    }
    if basis.is_empty() {
        return Some(Vec::new());
    }

    let mut pairs: Vec<(usize, usize)> = Vec::new();
    for higher in 1..basis.len() {
        for lower in 0..higher {
            pairs.push((lower, higher));
        }
    }
    // A FIFO queue over a `Vec` with an explicit cursor: deterministic order,
    // no allocation churn from the front.
    let mut cursor = 0usize;
    let mut iterations: u64 = 0;
    while cursor < pairs.len() {
        let (lower, higher) = pairs[cursor];
        cursor += 1;
        iterations += 1;
        if iterations > budget.limits.pair_iterations {
            return budget.decline(DeclineReason::PairIterations);
        }
        let s_poly = tracked_s_polynomial(&basis[lower], &basis[higher], budget)?;
        let (remainder, quotients) = reduce_tracked(&s_poly, &basis, budget)?;
        if remainder.poly.is_zero() {
            continue;
        }
        // `remainder.rep` already accounts for the subtractions: `reduce_tracked`
        // returns it in terms of the generators, not the basis.
        let _ = &quotients;
        let new_index = basis.len();
        for existing in 0..new_index {
            pairs.push((existing, new_index));
        }
        basis.push(remainder);
        if basis.len() > budget.limits.basis_size {
            return budget.decline(DeclineReason::BasisSize);
        }
    }
    Some(basis)
}

/// The S-polynomial of two tracked elements, with its representation derived from
/// theirs: `S = f·A − g·B` implies `S.rep = f·A.rep − g·B.rep`.
fn tracked_s_polynomial(first: &Tracked, second: &Tracked, budget: &mut Budget) -> Option<Tracked> {
    // Basis elements are never zero, so a `None` from `leading_term` here is
    // unreachable; routing it through `arith` keeps the attribution total.
    let order = budget.limits.order;
    let (first_mono, first_coeff) = budget.arith(leading_term_in(order, &first.poly))?;
    let (second_mono, second_coeff) = budget.arith(leading_term_in(order, &second.poly))?;
    let lcm = monomial_lcm(&first_mono, &second_mono);
    let first_inverse = budget.arith(Rational::integer(1).checked_div(first_coeff))?;
    let first_factor = budget.arith(single_term(
        &monomial_quotient(&lcm, &first_mono),
        first_inverse,
    ))?;
    let second_inverse = budget.arith(Rational::integer(1).checked_div(second_coeff))?;
    let second_factor = budget.arith(single_term(
        &monomial_quotient(&lcm, &second_mono),
        second_inverse,
    ))?;
    let first_scaled = budget.arith(first_factor.mul(&first.poly))?;
    let second_scaled = budget.arith(second_factor.mul(&second.poly))?;
    let poly = budget.arith(first_scaled.sub(&second_scaled))?;
    budget.capped(&poly)?;
    let mut rep = Vec::with_capacity(first.rep.len());
    for (left, right) in first.rep.iter().zip(second.rep.iter()) {
        let left_scaled = budget.arith(first_factor.mul(left))?;
        let right_scaled = budget.arith(second_factor.mul(right))?;
        let combined = budget.arith(left_scaled.sub(&right_scaled))?;
        budget.capped(&combined)?;
        rep.push(combined);
    }
    Some(Tracked { poly, rep })
}

/// Multivariate division of `target` by `basis`, tracking both the per-basis
/// quotients and the remainder's representation in the original generators.
///
/// Maintains the invariant `target.poly = current + remainder + Σ q[j]·basis[j].poly`
/// and returns `(remainder, q)` once `current` is zero. The returned remainder's
/// `rep` is `target.rep − Σ q[j]·basis[j].rep`, which is exactly its
/// representation in the generators.
fn reduce_tracked(
    target: &Tracked,
    basis: &[Tracked],
    budget: &mut Budget,
) -> Option<(Tracked, Vec<MvPoly>)> {
    let order = budget.limits.order;
    let leads: Vec<(Exponents, Rational)> = budget.arith(
        basis
            .iter()
            .map(|element| leading_term_in(order, &element.poly))
            .collect::<Option<Vec<_>>>(),
    )?;

    let mut quotients = vec![MvPoly::zero(); basis.len()];
    let mut remainder = MvPoly::zero();
    let mut current = target.poly.clone();
    while !current.is_zero() {
        budget.spend_reduction()?;
        let (lead_mono, lead_coeff) = budget.arith(leading_term_in(order, &current))?;
        let mut cancelled = false;
        for (index, (element_mono, element_coeff)) in leads.iter().enumerate() {
            if !monomial_divides(element_mono, &lead_mono) {
                continue;
            }
            let quotient_mono = monomial_quotient(&lead_mono, element_mono);
            let quotient_coeff = budget.arith(lead_coeff.checked_div(*element_coeff))?;
            let factor = budget.arith(single_term(&quotient_mono, quotient_coeff))?;
            let scaled = budget.arith(factor.mul(&basis[index].poly))?;
            current = budget.arith(current.sub(&scaled))?;
            budget.capped(&current)?;
            quotients[index] = budget.arith(quotients[index].add(&factor))?;
            budget.capped(&quotients[index])?;
            cancelled = true;
            break;
        }
        if !cancelled {
            let lead = budget.arith(single_term(&lead_mono, lead_coeff))?;
            remainder = budget.arith(remainder.add(&lead))?;
            budget.capped(&remainder)?;
            current = budget.arith(current.sub(&lead))?;
        }
    }

    // `remainder = target − Σ q[j]·basis[j]`, so subtract the same combination
    // from `target`'s representation to get the remainder's.
    let mut rep = target.rep.clone();
    for (quotient, element) in quotients.iter().zip(basis.iter()) {
        if quotient.is_zero() {
            continue;
        }
        for (slot, share) in rep.iter_mut().zip(element.rep.iter()) {
            if share.is_zero() {
                continue;
            }
            let product = budget.arith(quotient.mul(share))?;
            budget.capped(&product)?;
            *slot = budget.arith(slot.sub(&product))?;
            budget.capped(slot)?;
        }
    }
    Some((
        Tracked {
            poly: remainder,
            rep,
        },
        quotients,
    ))
}

#[cfg(test)]
mod tests {
    use super::{
        CofactorOutcome, DeclineReason, Limits, reduce_with_cofactors, unit_ideal_cofactors,
    };
    use crate::groebner::MonomialOrder;
    use crate::mvpoly::MvPoly;
    use axeyum_ir::Rational;

    /// Re-derive `Σ cofactors[i]·generators[i] + remainder` independently of the
    /// tracking machinery and confirm it equals `target`. This mirrors what the
    /// solver-side checker does, so a broken invariant fails here first.
    fn recombine(generators: &[MvPoly], cofactors: &[MvPoly], remainder: &MvPoly) -> MvPoly {
        let mut acc = remainder.clone();
        for (cofactor, generator) in cofactors.iter().zip(generators.iter()) {
            acc = acc
                .add(&cofactor.mul(generator).expect("product"))
                .expect("sum");
        }
        acc
    }

    fn int(value: i128) -> MvPoly {
        MvPoly::constant(Rational::integer(value))
    }

    #[test]
    fn unit_ideal_certificate_recombines() {
        // x + y − 3 = 0 and x·y − 5 = 0 force x² + y² = 9 − 10 = −1, so adding
        // x² + y² = 1 makes the system inconsistent: 1 lies in the ideal.
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let generators = vec![
            x.add(&y).unwrap().sub(&int(3)).unwrap(),
            x.mul(&y).unwrap().sub(&int(5)).unwrap(),
            x.mul(&x)
                .unwrap()
                .add(&y.mul(&y).unwrap())
                .unwrap()
                .sub(&int(1))
                .unwrap(),
        ];
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = unit_ideal_cofactors(&generators, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(remainder.is_zero(), "1 must reduce to 0: {remainder:?}");
        assert_eq!(cofactors.len(), generators.len());
        let combined = recombine(&generators, &cofactors, &remainder);
        assert_eq!(combined, int(1), "Σ cᵢ·gᵢ must be exactly 1");
    }

    #[test]
    fn a_consistent_system_does_not_contain_the_unit() {
        // x − 1 = 0 and y − 2 = 0 have the common zero (1, 2).
        let generators = vec![
            MvPoly::var("x").sub(&int(1)).unwrap(),
            MvPoly::var("y").sub(&int(2)).unwrap(),
        ];
        let CofactorOutcome::Reduced { remainder, .. } =
            unit_ideal_cofactors(&generators, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(!remainder.is_zero(), "1 is not in a proper ideal");
    }

    #[test]
    fn reduction_to_a_constant_recombines() {
        // Modulo (x + y − 3, x·y − 5), the polynomial x² + y² is the constant −1.
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let generators = vec![
            x.add(&y).unwrap().sub(&int(3)).unwrap(),
            x.mul(&y).unwrap().sub(&int(5)).unwrap(),
        ];
        let target = x.mul(&x).unwrap().add(&y.mul(&y).unwrap()).unwrap();
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = reduce_with_cofactors(&generators, &target, Limits::fast())
        else {
            panic!("declined");
        };
        assert_eq!(remainder, int(-1), "x² + y² ≡ −1 mod the ideal");
        assert_eq!(recombine(&generators, &cofactors, &remainder), target);
    }

    #[test]
    fn empty_generators_leave_the_target_alone() {
        let target = MvPoly::var("x");
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = reduce_with_cofactors(&[], &target, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(cofactors.is_empty());
        assert_eq!(remainder, target);
    }

    #[test]
    fn zero_generators_get_zero_cofactors() {
        let generators = vec![MvPoly::zero(), MvPoly::var("x").sub(&int(1)).unwrap()];
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = reduce_with_cofactors(&generators, &MvPoly::var("x"), Limits::fast())
        else {
            panic!("declined");
        };
        assert_eq!(remainder, int(1));
        assert!(cofactors[0].is_zero(), "the zero generator is unused");
        assert_eq!(
            recombine(&generators, &cofactors, &remainder),
            MvPoly::var("x")
        );
    }

    #[test]
    fn a_tight_budget_declines_rather_than_guessing() {
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let generators = vec![
            x.add(&y).unwrap().sub(&int(3)).unwrap(),
            x.mul(&y).unwrap().sub(&int(5)).unwrap(),
            x.mul(&x)
                .unwrap()
                .add(&y.mul(&y).unwrap())
                .unwrap()
                .sub(&int(1))
                .unwrap(),
        ];
        let starved = Limits {
            reduction_steps: 1,
            ..Limits::fast()
        };
        assert_eq!(
            unit_ideal_cofactors(&generators, starved),
            CofactorOutcome::Declined(DeclineReason::ReductionSteps),
            "a starved budget must decline as a ceiling, not as an overflow"
        );
    }

    /// The other half of the split: an exact coefficient that leaves the `i128`
    /// range declines as [`DeclineReason::Overflow`], with every ceiling in
    /// `Limits::fast()` untouched.
    ///
    /// This is the control that makes the distinction load-bearing rather than
    /// documentary. Reducing `x²` modulo `x − c` produces `c²` as the constant
    /// term, so a `c` above `2^64` overflows on the second reduction step while
    /// the step, pair, basis and term budgets are all barely used.
    #[test]
    fn an_overflowing_coefficient_declines_as_overflow_not_as_a_ceiling() {
        let huge = int(1_000_000_000_000_000_000_000_000_000_000);
        let generators = vec![MvPoly::var("x").sub(&huge).unwrap()];
        let target = MvPoly::var("x").mul(&MvPoly::var("x")).unwrap();
        let outcome = reduce_with_cofactors(&generators, &target, Limits::fast());
        assert_eq!(outcome, CofactorOutcome::Declined(DeclineReason::Overflow));
        let CofactorOutcome::Declined(reason) = outcome else {
            panic!("expected a decline");
        };
        assert!(!reason.is_ceiling(), "an overflow is not a budget problem");

        // The same shape with a small coefficient reduces fine, so the decline
        // above is about the width and nothing else.
        let small = int(3);
        let generators = vec![MvPoly::var("x").sub(&small).unwrap()];
        let CofactorOutcome::Reduced { remainder, .. } =
            reduce_with_cofactors(&generators, &target, Limits::fast())
        else {
            panic!("declined on a small coefficient");
        };
        assert_eq!(remainder, int(9));
    }

    /// Three variables, degree 3: the shape the Rado symbolic-parameter work
    /// needs. `x + y + z = 0`, `x·y + y·z + z·x = 0` and `x·y·z = 1` are the
    /// elementary symmetric functions of the roots of `t³ − 1`, so adding
    /// `x³ + y³ + z³ = 4` (the true value is 3) is inconsistent.
    #[test]
    fn three_variable_cubic_system_is_refuted_with_a_witness() {
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let z = MvPoly::var("z");
        let cube = |v: &MvPoly| v.pow(3).unwrap();
        let generators = vec![
            x.add(&y).unwrap().add(&z).unwrap(),
            x.mul(&y)
                .unwrap()
                .add(&y.mul(&z).unwrap())
                .unwrap()
                .add(&z.mul(&x).unwrap())
                .unwrap(),
            x.mul(&y).unwrap().mul(&z).unwrap().sub(&int(1)).unwrap(),
            cube(&x)
                .add(&cube(&y))
                .unwrap()
                .add(&cube(&z))
                .unwrap()
                .sub(&int(4))
                .unwrap(),
        ];
        let CofactorOutcome::Reduced {
            cofactors,
            remainder,
        } = unit_ideal_cofactors(&generators, Limits::fast())
        else {
            panic!("declined");
        };
        assert!(remainder.is_zero());
        assert_eq!(recombine(&generators, &cofactors, &remainder), int(1));
    }

    /// The monomial order must be a **cost** knob and nothing else: on the same
    /// system it must reach the same ideal-membership verdict, and the cofactor
    /// identity it emits must recombine exactly under either setting.
    ///
    /// This is the control that makes `grevlex` safe to switch on. The two
    /// orders genuinely disagree about which term leads (see
    /// `grevlex_breaks_ties_by_the_smaller_last_exponent` in `groebner`), so the
    /// bases here are different objects; only the answer is shared.
    #[test]
    fn the_monomial_order_changes_the_basis_but_not_the_verdict() {
        let x = MvPoly::var("x");
        let y = MvPoly::var("y");
        let z = MvPoly::var("z");
        // x + y + z = 0, x·y + y·z + z·x = 0, x·y·z = 1: the elementary
        // symmetric functions of the roots of t^3 - 1. Then x^3 + y^3 + z^3 = 3.
        let generators = vec![
            x.add(&y).unwrap().add(&z).unwrap(),
            x.mul(&y)
                .unwrap()
                .add(&y.mul(&z).unwrap())
                .unwrap()
                .add(&z.mul(&x).unwrap())
                .unwrap(),
            x.mul(&y).unwrap().mul(&z).unwrap().sub(&int(1)).unwrap(),
        ];
        let cube = |v: &MvPoly| v.mul(v).unwrap().mul(v).unwrap();
        let target = cube(&x)
            .add(&cube(&y))
            .unwrap()
            .add(&cube(&z))
            .unwrap()
            .sub(&int(3))
            .unwrap();

        for order in [MonomialOrder::Lex, MonomialOrder::DegRevLex] {
            let limits = Limits {
                order,
                ..Limits::fast()
            };
            let CofactorOutcome::Reduced {
                cofactors,
                remainder,
            } = reduce_with_cofactors(&generators, &target, limits)
            else {
                panic!("declined under {order:?}");
            };
            assert!(
                remainder.is_zero(),
                "x^3 + y^3 + z^3 - 3 is in the ideal under {order:?}"
            );
            assert_eq!(
                recombine(&generators, &cofactors, &remainder),
                target,
                "the cofactor identity must be exact under {order:?}"
            );
        }

        // And a polynomial that is NOT in the ideal stays out under both.
        let outside = cube(&x).add(&cube(&y)).unwrap().add(&cube(&z)).unwrap();
        for order in [MonomialOrder::Lex, MonomialOrder::DegRevLex] {
            let limits = Limits {
                order,
                ..Limits::fast()
            };
            let CofactorOutcome::Reduced { remainder, .. } =
                reduce_with_cofactors(&generators, &outside, limits)
            else {
                panic!("declined under {order:?}");
            };
            assert!(!remainder.is_zero(), "x^3 + y^3 + z^3 is not in the ideal");
            assert_eq!(remainder, int(3), "and its normal form is the constant 3");
        }
    }
}
