//! Simplicial homology over ℤ, built on the existing integer Smith normal form.
//!
//! # What this module computes
//!
//! [`SimplicialComplex`] is an abstract simplicial complex: a set of faces
//! (vertex-id lists) closed under taking non-empty subsets, built from a list
//! of maximal simplices and stored one `BTreeSet<Vec<usize>>` per dimension so
//! iteration order is deterministic (lexicographic on sorted vertex lists).
//!
//! [`boundary_matrix`] builds the integer boundary matrix `d_k : C_k -> C_{k-1}`
//! (rows indexed by `(k-1)`-simplices in their `BTreeSet` order, columns by
//! `k`-simplices, entries `+/-1` by the standard alternating-face-removal sign
//! convention, `0` elsewhere). [`homology`] runs [`crate::normalforms::smith_normal_form`]
//! on every `d_k` for `k` from `0` to `dim + 1` and reads off, for each `k`:
//!
//! - the Betti number `b_k = n_k - rank(d_k) - rank(d_{k+1})` (rank-nullity
//!   applied twice: `n_k - rank(d_k)` is the cycle space `Z_k`, and
//!   `rank(d_{k+1})` is the boundary space `B_k` sitting inside it);
//! - the torsion coefficients of `H_k`, which are the invariant factors of
//!   `d_{k+1}` strictly greater than `1` (the standard structure theorem:
//!   `H_k = Z^{b_k} (+) direct-sum of Z/d_i` for those `d_i`).
//!
//! # What is certified, and what is not
//!
//! [`HomologyCertificate::verify`] re-derives every claim from the complex
//! alone, independently of [`homology`]'s search:
//!
//! - (a) rebuilds every `d_k` directly from the complex and checks
//!   `d_{k-1} . d_k = 0` for every consecutive pair (`compose_is_zero`);
//! - checks the certificate's recorded boundary matrices actually equal the
//!   freshly rebuilt ones (`boundaries_match`), so a certificate cannot swap in
//!   a boundary matrix unrelated to the complex it claims to describe;
//! - (b) for every recorded Smith triple `(U, D, V)`, checks `U . d_k . V = D`
//!   by matrix multiplication, `U` and `V` unimodular (`det = +/-1` via
//!   [`Matrix::determinant`]), and `D` diagonal with the invariant-factor
//!   divisibility chain (`smith_factorizations_hold`, reusing
//!   [`crate::normalforms`]'s own certified guards `certify_product_equals`,
//!   `is_unimodular`, `certifies_smith_shape` rather than re-implementing
//!   them);
//! - (c) recomputes every Betti number and torsion list from the `D`s alone and
//!   compares to the recorded values (`betti_and_torsion_match`);
//! - (d) checks the recorded Euler characteristic equals the complex's own
//!   `euler_characteristic()` **and** the alternating sum of the recomputed
//!   Betti numbers (`euler_characteristic_matches`).
//!
//! What is **not** certified: `verify` trusts [`Matrix::determinant`]'s cofactor
//! expansion and the crate's `equal` zero-test (both are certified elsewhere in
//! this crate, not re-derived here), and it trusts that the caller passed the
//! `SimplicialComplex` the certificate actually claims to describe -- a
//! certificate for one complex checked against an unrelated complex with the
//! same face counts by coincidence would only be caught by the boundary-match
//! guard, not by the simplex-count guard alone.
//!
//! # Cost profile
//!
//! Every step is exact integer arithmetic (`i128` internally, via
//! `smith_normal_form`); there is no floating point anywhere in the certified
//! path. The unimodularity check re-used from `normalforms` is cofactor
//! determinant, `O(n!)` in the size of `U`/`V` (as large as the simplex count
//! at that dimension), so this module inherits that crate's small-dimension
//! intent. Tested here up to the 9-vertex, 18-triangle Klein bottle
//! triangulation (27 edges, so the largest `U`/`V` computed is `27 x 27`);
//! `cargo test -p axeyum-cas --lib homology::` was not separately timed under
//! `--release`, so no wall-clock number is claimed here -- treat this as
//! untested past a few dozen simplices per dimension until measured.

use std::collections::{BTreeMap, BTreeSet};

use crate::normalforms::{
    certifies_smith_shape, certify_product_equals, int_entry, is_unimodular, smith_normal_form,
};
use crate::{CasExpr, Matrix, ZeroTest, equal};

/// An abstract simplicial complex over vertex ids `0..`, closed under taking
/// faces, built from a list of maximal simplices.
///
/// Faces are stored one `BTreeSet<Vec<usize>>` per dimension (dimension `k`
/// holds each `(k+1)`-vertex face as a sorted, deduplicated `Vec<usize>`), so
/// iteration order -- and therefore the row/column order of every boundary
/// matrix built from it -- is deterministic.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SimplicialComplex {
    faces: BTreeMap<usize, BTreeSet<Vec<usize>>>,
}

impl SimplicialComplex {
    /// Build the complex generated by a list of maximal simplices: every
    /// simplex's vertex list is sorted and deduplicated, then every non-empty
    /// subset of it is inserted as a face at the subset's own dimension
    /// (`subset.len() - 1`). An empty maximal simplex (after dedup) is
    /// skipped.
    ///
    /// Simplices with more than 62 distinct vertices are rejected (`None`):
    /// the subset enumeration below is a `1u64 << n` bitmask walk and does not
    /// attempt to support larger faces.
    #[must_use]
    pub fn from_maximal_simplices(maximal: &[Vec<usize>]) -> Option<SimplicialComplex> {
        let mut faces: BTreeMap<usize, BTreeSet<Vec<usize>>> = BTreeMap::new();
        for simplex in maximal {
            let mut verts = simplex.clone();
            verts.sort_unstable();
            verts.dedup();
            let n = verts.len();
            if n == 0 {
                continue;
            }
            if n > 62 {
                return None;
            }
            for mask in 1u64..(1u64 << n) {
                let mut subset = Vec::with_capacity(mask.count_ones() as usize);
                for (i, &vertex) in verts.iter().enumerate() {
                    if mask & (1u64 << i) != 0 {
                        subset.push(vertex);
                    }
                }
                let dim = subset.len() - 1;
                faces.entry(dim).or_default().insert(subset);
            }
        }
        Some(SimplicialComplex { faces })
    }

    /// The highest dimension carrying at least one face, or `0` if the
    /// complex has none at all.
    #[must_use]
    pub fn max_dimension(&self) -> usize {
        self.faces.keys().next_back().copied().unwrap_or(0)
    }

    /// Every face at `dim`, in the complex's canonical (sorted) order. Empty
    /// if the complex has no faces at that dimension.
    #[must_use]
    pub fn simplices(&self, dim: usize) -> Vec<Vec<usize>> {
        self.faces
            .get(&dim)
            .map(|set| set.iter().cloned().collect())
            .unwrap_or_default()
    }

    /// The number of faces at `dim` (`n_k` in the standard notation).
    #[must_use]
    pub fn count(&self, dim: usize) -> usize {
        self.faces.get(&dim).map_or(0, BTreeSet::len)
    }

    /// `sum_k (-1)^k * n_k`, the alternating sum of face counts by dimension.
    #[must_use]
    pub fn euler_characteristic(&self) -> i128 {
        let mut total: i128 = 0;
        for (&dim, set) in &self.faces {
            let count = set.len() as i128;
            total += if dim % 2 == 0 { count } else { -count };
        }
        total
    }
}

/// The integer boundary matrix `d_k : C_k -> C_{k-1}`: rows are the
/// `(k-1)`-simplices of `complex` in its canonical order (zero rows if
/// `k == 0`), columns are the `k`-simplices (zero columns if `complex` has
/// none at dimension `k`). Entry `(row, col)` is `(-1)^l` where the `row`-th
/// `(k-1)`-simplex is obtained by deleting the `l`-th vertex (0-indexed, in
/// the sorted vertex list) of the `col`-th `k`-simplex, and `0` if that
/// `(k-1)`-simplex is not a face of it at all (which cannot happen for `l` in
/// range, since the complex is closed under faces, but the lookup is written
/// generally rather than assumed).
///
/// Returns `None` only if `rows * cols` overflows `usize` (never for the
/// complex sizes this module is intended for).
#[must_use]
pub fn boundary_matrix(complex: &SimplicialComplex, k: usize) -> Option<Matrix> {
    let cols_simplices = complex.simplices(k);
    let rows_simplices = if k == 0 {
        Vec::new()
    } else {
        complex.simplices(k - 1)
    };
    let row_index: BTreeMap<Vec<usize>, usize> = rows_simplices
        .iter()
        .cloned()
        .enumerate()
        .map(|(i, face)| (face, i))
        .collect();
    let rows = rows_simplices.len();
    let cols = cols_simplices.len();
    let mut data = vec![CasExpr::zero(); rows.checked_mul(cols)?];
    for (col_idx, simplex) in cols_simplices.iter().enumerate() {
        for l in 0..simplex.len() {
            let mut face = simplex.clone();
            face.remove(l);
            if let Some(&row_idx) = row_index.get(&face) {
                let sign = if l % 2 == 0 { 1 } else { -1 };
                data[row_idx * cols + col_idx] = CasExpr::int(sign);
            }
        }
    }
    Matrix::new(rows, cols, data)
}

/// Whether every entry of `matrix` is certifiably zero via the crate's
/// zero-test.
fn is_zero_matrix(matrix: &Matrix) -> bool {
    for row in 0..matrix.rows() {
        for col in 0..matrix.cols() {
            let Some(entry) = matrix.get(row, col) else {
                return false;
            };
            if !matches!(
                equal(entry, &CasExpr::zero()),
                ZeroTest::Certified { equal: true, .. }
            ) {
                return false;
            }
        }
    }
    true
}

/// The number of nonzero diagonal entries of `d` (its rank, since `d` is a
/// Smith-form diagonal matrix), or `None` if a diagonal entry is not an
/// integer-valued constant.
fn diagonal_rank(d: &Matrix) -> Option<usize> {
    let limit = d.rows().min(d.cols());
    let mut rank = 0usize;
    for i in 0..limit {
        if int_entry(d, i, i)? != 0 {
            rank += 1;
        }
    }
    Some(rank)
}

/// The invariant factors of `d` (a Smith-form diagonal matrix) strictly
/// greater than `1`, in diagonal order (already ascending by the divisibility
/// chain), or `None` if a diagonal entry is not an integer-valued constant.
fn torsion_factors(d: &Matrix) -> Option<Vec<i128>> {
    let limit = d.rows().min(d.cols());
    let mut factors = Vec::new();
    for i in 0..limit {
        let value = int_entry(d, i, i)?;
        if value > 1 {
            factors.push(value);
        }
    }
    Some(factors)
}

/// One recorded Smith factorization `U * d_k * V = D` of the boundary matrix
/// `d_k`, at a fixed dimension `k` (kept alongside the certificate rather than
/// as a bare tuple so `verify` can rebuild `d_k` independently and compare it
/// to the recorded `boundary`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SmithData {
    /// The boundary matrix `d_k` this triple factors.
    pub boundary: Matrix,
    /// The left unimodular transform.
    pub u: Matrix,
    /// The Smith diagonal form.
    pub d: Matrix,
    /// The right unimodular transform.
    pub v: Matrix,
}

/// A checkable certificate of the simplicial homology of a [`SimplicialComplex`]
/// over ℤ: Betti numbers and torsion coefficients at every dimension, backed by
/// a recorded Smith factorization of every boundary matrix. Call [`verify`]
/// (`HomologyCertificate::verify`) to re-derive the claims independently of
/// [`homology`], the producer.
///
/// [`verify`]: HomologyCertificate::verify
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HomologyCertificate {
    /// The highest dimension `k` for which the complex has any `k`-simplex.
    pub max_dimension: usize,
    /// `n_k` for `k` in `0..=max_dimension`.
    pub simplex_counts: BTreeMap<usize, usize>,
    /// The recorded Smith factorization of `d_k` for `k` in
    /// `0..=(max_dimension + 1)`.
    pub smith: BTreeMap<usize, SmithData>,
    /// `b_k` for `k` in `0..=max_dimension`.
    pub betti: BTreeMap<usize, usize>,
    /// The torsion coefficients of `H_k` (invariant factors of `d_{k+1}`
    /// greater than `1`), for `k` in `0..=max_dimension`.
    pub torsion: BTreeMap<usize, Vec<i128>>,
    /// `complex.euler_characteristic()` at the time the certificate was built.
    pub euler_characteristic: i128,
}

/// The result of a successful [`HomologyCertificate::verify`]: every value
/// re-derived independently from the complex, not merely copied from the
/// certificate under test.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HomologyReport {
    /// The highest dimension `k` for which the complex has any `k`-simplex.
    pub max_dimension: usize,
    /// `b_k`, recomputed from the recorded Smith diagonals.
    pub betti: BTreeMap<usize, usize>,
    /// The torsion coefficients of `H_k`, recomputed from the recorded Smith
    /// diagonals.
    pub torsion: BTreeMap<usize, Vec<i128>>,
    /// The complex's own Euler characteristic.
    pub euler_characteristic: i128,
}

/// Compute the simplicial homology of `complex` over ℤ: the Betti numbers and
/// torsion coefficients at every dimension from `0` to `complex.max_dimension()`,
/// backed by a Smith factorization of every boundary matrix `d_k` for `k` in
/// `0..=(complex.max_dimension() + 1)`.
///
/// Returns `None` if any boundary matrix fails to reduce to Smith form (an
/// `i128` overflow or the iteration cap in [`crate::normalforms::smith_normal_form`];
/// not expected for the complex sizes this module targets), or if the
/// rank-nullity arithmetic would produce a negative Betti number (which would
/// mean a boundary matrix was not actually built from a complex closed under
/// faces -- a bug, not a legitimate `unknown`).
#[must_use]
pub fn homology(complex: &SimplicialComplex) -> Option<HomologyCertificate> {
    let max_dim = complex.max_dimension();

    let mut simplex_counts = BTreeMap::new();
    for k in 0..=max_dim {
        simplex_counts.insert(k, complex.count(k));
    }

    let mut smith = BTreeMap::new();
    for k in 0..=(max_dim + 1) {
        let boundary = boundary_matrix(complex, k)?;
        let (u, d, v) = smith_normal_form(&boundary)?;
        smith.insert(k, SmithData { boundary, u, d, v });
    }

    let rank_at = |k: usize| -> Option<usize> {
        smith
            .get(&k)
            .map_or(Some(0), |triple| diagonal_rank(&triple.d))
    };

    let mut betti = BTreeMap::new();
    for k in 0..=max_dim {
        let n_k = *simplex_counts.get(&k)? as i128;
        let r_k = rank_at(k)? as i128;
        let r_k1 = rank_at(k + 1)? as i128;
        let b = n_k - r_k - r_k1;
        let b = usize::try_from(b).ok()?;
        betti.insert(k, b);
    }

    let mut torsion = BTreeMap::new();
    for k in 0..=max_dim {
        let coefficients = match smith.get(&(k + 1)) {
            Some(triple) => torsion_factors(&triple.d)?,
            None => Vec::new(),
        };
        torsion.insert(k, coefficients);
    }

    Some(HomologyCertificate {
        max_dimension: max_dim,
        simplex_counts,
        smith,
        betti,
        torsion,
        euler_characteristic: complex.euler_characteristic(),
    })
}

/// Guard (simplex counts): every recorded `n_k` matches `complex.count(k)`.
fn simplex_counts_match(
    certificate: &HomologyCertificate,
    complex: &SimplicialComplex,
) -> Result<(), String> {
    for k in 0..=certificate.max_dimension {
        let actual = complex.count(k);
        let Some(&claimed) = certificate.simplex_counts.get(&k) else {
            return Err(format!(
                "certificate has no recorded simplex count at dimension {k}"
            ));
        };
        if actual != claimed {
            return Err(format!(
                "simplex count mismatch at dimension {k}: complex has {actual}, certificate claims {claimed}"
            ));
        }
    }
    Ok(())
}

/// Rebuild `d_k` for every `k` in `0..=(max_dimension + 1)` directly from
/// `complex`, independently of anything recorded in a certificate.
fn rebuild_boundaries(
    complex: &SimplicialComplex,
    max_dimension: usize,
) -> Result<BTreeMap<usize, Matrix>, String> {
    let mut rebuilt = BTreeMap::new();
    for k in 0..=(max_dimension + 1) {
        let boundary = boundary_matrix(complex, k)
            .ok_or_else(|| format!("could not rebuild the boundary matrix at dimension {k}"))?;
        rebuilt.insert(k, boundary);
    }
    Ok(rebuilt)
}

/// Guard (boundary provenance): the certificate's recorded `d_k` at every
/// dimension is entrywise equal to the one just rebuilt from the complex --
/// without this, a certificate could carry a valid Smith factorization of a
/// boundary matrix that has nothing to do with `complex`.
fn boundaries_match(
    certificate: &HomologyCertificate,
    rebuilt: &BTreeMap<usize, Matrix>,
) -> Result<(), String> {
    for (k, boundary) in rebuilt {
        let Some(triple) = certificate.smith.get(k) else {
            return Err(format!(
                "certificate is missing a Smith triple at dimension {k}"
            ));
        };
        if !certify_product_equals(boundary, &triple.boundary) {
            return Err(format!(
                "recorded boundary matrix at dimension {k} does not match the one rebuilt from the complex"
            ));
        }
    }
    Ok(())
}

/// Guard (a): `d_{k-1} . d_k = 0` for every consecutive pair of rebuilt
/// boundary matrices.
fn compositions_are_zero(
    rebuilt: &BTreeMap<usize, Matrix>,
    max_dimension: usize,
) -> Result<(), String> {
    for k in 1..=(max_dimension + 1) {
        let lower = rebuilt
            .get(&(k - 1))
            .ok_or_else(|| format!("no rebuilt boundary at dimension {}", k - 1))?;
        let upper = rebuilt
            .get(&k)
            .ok_or_else(|| format!("no rebuilt boundary at dimension {k}"))?;
        let product = lower
            .mul(upper)
            .ok_or_else(|| format!("d_{} . d_{k} failed to multiply", k - 1))?;
        if !is_zero_matrix(&product) {
            return Err(format!("d_{} . d_{k} is not the zero matrix", k - 1));
        }
    }
    Ok(())
}

/// Guard (b): every recorded Smith triple is a genuine factorization --
/// `U * d_k * V = D`, `U` and `V` unimodular, `D` in Smith normal form (the
/// full divisibility chain, not merely diagonal). Reuses
/// [`crate::normalforms`]'s own certified guards rather than re-implementing
/// them.
fn smith_factorizations_hold(certificate: &HomologyCertificate) -> Result<(), String> {
    for (k, triple) in &certificate.smith {
        let product = triple
            .u
            .mul(&triple.boundary)
            .and_then(|partial| partial.mul(&triple.v))
            .ok_or_else(|| format!("U * d_{k} * V failed to multiply"))?;
        if !certify_product_equals(&product, &triple.d) {
            return Err(format!("U * d_{k} * V != D at dimension {k}"));
        }
        if !is_unimodular(&triple.u) {
            return Err(format!(
                "U at dimension {k} is not unimodular (det != +/-1)"
            ));
        }
        if !is_unimodular(&triple.v) {
            return Err(format!(
                "V at dimension {k} is not unimodular (det != +/-1)"
            ));
        }
        if !certifies_smith_shape(&triple.d) {
            return Err(format!(
                "D at dimension {k} is not in Smith normal form (not diagonal, or the divisibility chain fails)"
            ));
        }
    }
    Ok(())
}

/// The recomputed Betti numbers and torsion coefficients from
/// [`betti_and_torsion_match`].
type BettiAndTorsion = (BTreeMap<usize, usize>, BTreeMap<usize, Vec<i128>>);

/// Guard (c): recompute every Betti number and torsion list from the recorded
/// `D`s alone and compare to what the certificate claims.
fn betti_and_torsion_match(
    certificate: &HomologyCertificate,
    complex: &SimplicialComplex,
) -> Result<BettiAndTorsion, String> {
    let diag_rank = |k: usize| -> Result<usize, String> {
        match certificate.smith.get(&k) {
            Some(triple) => diagonal_rank(&triple.d)
                .ok_or_else(|| format!("non-integer diagonal entry in D at dimension {k}")),
            None => Ok(0),
        }
    };

    let mut betti = BTreeMap::new();
    for k in 0..=certificate.max_dimension {
        let n_k = complex.count(k) as i128;
        let r_k = diag_rank(k)? as i128;
        let r_k1 = diag_rank(k + 1)? as i128;
        let recomputed = n_k - r_k - r_k1;
        let Ok(recomputed) = usize::try_from(recomputed) else {
            return Err(format!(
                "recomputed a negative Betti number at dimension {k}"
            ));
        };
        let Some(&claimed) = certificate.betti.get(&k) else {
            return Err(format!(
                "certificate has no recorded Betti number at dimension {k}"
            ));
        };
        if recomputed != claimed {
            return Err(format!(
                "betti number mismatch at dimension {k}: recomputed {recomputed}, certificate claims {claimed}"
            ));
        }
        betti.insert(k, recomputed);
    }

    let mut torsion = BTreeMap::new();
    for k in 0..=certificate.max_dimension {
        let recomputed = match certificate.smith.get(&(k + 1)) {
            Some(triple) => torsion_factors(&triple.d)
                .ok_or_else(|| format!("non-integer diagonal entry in D at dimension {}", k + 1))?,
            None => Vec::new(),
        };
        let claimed = certificate.torsion.get(&k).cloned().unwrap_or_default();
        if recomputed != claimed {
            return Err(format!(
                "torsion mismatch at dimension {k}: recomputed {recomputed:?}, certificate claims {claimed:?}"
            ));
        }
        torsion.insert(k, recomputed);
    }

    Ok((betti, torsion))
}

/// Guard (d): the recorded Euler characteristic equals the complex's own
/// `euler_characteristic()`, and the alternating sum of the recomputed Betti
/// numbers equals it too.
fn euler_characteristic_matches(
    certificate: &HomologyCertificate,
    complex: &SimplicialComplex,
    betti: &BTreeMap<usize, usize>,
) -> Result<i128, String> {
    let computed = complex.euler_characteristic();
    if computed != certificate.euler_characteristic {
        return Err(format!(
            "recorded euler characteristic {} does not match the complex's {computed}",
            certificate.euler_characteristic
        ));
    }
    let alternating_sum: i128 = betti
        .iter()
        .map(|(&k, &b)| if k % 2 == 0 { b as i128 } else { -(b as i128) })
        .sum();
    if alternating_sum != computed {
        return Err(format!(
            "alternating sum of Betti numbers {alternating_sum} does not equal the euler characteristic {computed}"
        ));
    }
    Ok(computed)
}

impl HomologyCertificate {
    /// Re-derive every claim in this certificate from `complex` alone,
    /// independently of [`homology`], the producer. See the module
    /// documentation for exactly which guards this runs and what each one
    /// would miss if it were absent.
    ///
    /// # Errors
    ///
    /// Returns a distinct, descriptive `Err(String)` for whichever guard
    /// fails first: a simplex-count mismatch, a boundary matrix that does not
    /// match the complex, a non-zero consecutive boundary composition, a
    /// broken Smith factorization (bad product, non-unimodular transform, or
    /// a `D` that is not actually in Smith form), a Betti-number or torsion
    /// mismatch, or an Euler-characteristic mismatch.
    pub fn verify(&self, complex: &SimplicialComplex) -> Result<HomologyReport, String> {
        simplex_counts_match(self, complex)?;
        let rebuilt = rebuild_boundaries(complex, self.max_dimension)?;
        boundaries_match(self, &rebuilt)?;
        compositions_are_zero(&rebuilt, self.max_dimension)?;
        smith_factorizations_hold(self)?;
        let (betti, torsion) = betti_and_torsion_match(self, complex)?;
        let euler_characteristic = euler_characteristic_matches(self, complex, &betti)?;
        Ok(HomologyReport {
            max_dimension: self.max_dimension,
            betti,
            torsion,
            euler_characteristic,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{
        HomologyCertificate, SimplicialComplex, boundaries_match, boundary_matrix,
        compositions_are_zero, euler_characteristic_matches, homology, rebuild_boundaries,
    };
    use crate::{CasExpr, Matrix};
    use std::collections::BTreeMap;

    fn complex_of(maximal: &[&[usize]]) -> SimplicialComplex {
        let owned: Vec<Vec<usize>> = maximal.iter().map(|s| s.to_vec()).collect();
        SimplicialComplex::from_maximal_simplices(&owned).expect("valid complex")
    }

    fn betti_vec(certificate: &HomologyCertificate) -> Vec<usize> {
        (0..=certificate.max_dimension)
            .map(|k| certificate.betti[&k])
            .collect()
    }

    fn torsion_at(certificate: &HomologyCertificate, k: usize) -> Vec<i128> {
        certificate.torsion.get(&k).cloned().unwrap_or_default()
    }

    /// Multiply every entry of row `row` of `matrix` by `factor`, leaving
    /// every other row untouched. Test-only forging helper: this multiplies
    /// the determinant by `factor` exactly, so it is a reliable way to break
    /// unimodularity (unlike bumping a single entry, whose effect on the
    /// determinant depends on that entry's cofactor and can coincidentally be
    /// zero).
    fn scale_row(matrix: &Matrix, row: usize, factor: i128) -> Matrix {
        let rows = matrix.rows();
        let cols = matrix.cols();
        let mut data = Vec::with_capacity(rows * cols);
        for r in 0..rows {
            for c in 0..cols {
                let entry = matrix.get(r, c).expect("in bounds").clone();
                if r == row {
                    let CasExpr::Const(value) = entry else {
                        panic!("expected an integer constant entry");
                    };
                    data.push(CasExpr::int(value.numerator() * factor));
                } else {
                    data.push(entry);
                }
            }
        }
        Matrix::new(rows, cols, data).expect("shape preserved")
    }

    // ---- evaluation tests at concrete complexes ----

    #[test]
    fn a_point_has_betti_one_zero() {
        let complex = complex_of(&[&[0]]);
        let certificate = homology(&complex).expect("homology of a point");
        assert_eq!(certificate.max_dimension, 0);
        assert_eq!(betti_vec(&certificate), vec![1]);
        assert_eq!(torsion_at(&certificate, 0), Vec::<i128>::new());
        assert_eq!(certificate.euler_characteristic, 1);
        let report = certificate.verify(&complex).expect("certificate verifies");
        assert_eq!(report.betti[&0], 1);
    }

    #[test]
    fn an_interval_is_contractible_betti_one_zero() {
        let complex = complex_of(&[&[0, 1]]);
        let certificate = homology(&complex).expect("homology of an interval");
        assert_eq!(betti_vec(&certificate), vec![1, 0]);
        assert_eq!(certificate.euler_characteristic, 1);
        certificate.verify(&complex).expect("certificate verifies");
    }

    #[test]
    fn a_triangle_boundary_circle_has_betti_one_one() {
        // The boundary of a triangle: three edges, no filled 2-face.
        let complex = complex_of(&[&[0, 1], &[1, 2], &[0, 2]]);
        let certificate = homology(&complex).expect("homology of a circle");
        assert_eq!(betti_vec(&certificate), vec![1, 1]);
        assert_eq!(torsion_at(&certificate, 0), Vec::<i128>::new());
        assert_eq!(torsion_at(&certificate, 1), Vec::<i128>::new());
        assert_eq!(certificate.euler_characteristic, 0);
        certificate.verify(&complex).expect("certificate verifies");
    }

    #[test]
    fn a_tetrahedron_boundary_sphere_has_betti_one_zero_one() {
        // The boundary of a tetrahedron: four 2-faces, no filled 3-simplex.
        let complex = complex_of(&[&[0, 1, 2], &[0, 1, 3], &[0, 2, 3], &[1, 2, 3]]);
        let certificate = homology(&complex).expect("homology of a 2-sphere");
        assert_eq!(betti_vec(&certificate), vec![1, 0, 1]);
        assert_eq!(certificate.euler_characteristic, 2);
        certificate.verify(&complex).expect("certificate verifies");
    }

    #[test]
    fn two_disjoint_circles_have_betti_two_two() {
        let complex = complex_of(&[&[0, 1], &[1, 2], &[0, 2], &[3, 4], &[4, 5], &[3, 5]]);
        let certificate = homology(&complex).expect("homology of two circles");
        assert_eq!(betti_vec(&certificate), vec![2, 2]);
        assert_eq!(certificate.euler_characteristic, 0);
        certificate.verify(&complex).expect("certificate verifies");
    }

    /// The standard 7-vertex triangulation of the torus (14 triangles using
    /// every edge of `K7`): `{i, i+1, i+3}` and `{i, i+2, i+3}` mod 7. Checked
    /// separately (outside this crate, in Python) to be a closed orientable
    /// surface of Euler characteristic 0 -- genus 1, the torus.
    #[test]
    fn the_seven_vertex_torus_has_betti_one_two_one_no_torsion() {
        let faces: &[&[usize]] = &[
            &[0, 1, 3],
            &[0, 1, 5],
            &[0, 2, 3],
            &[0, 2, 6],
            &[0, 4, 5],
            &[0, 4, 6],
            &[1, 2, 4],
            &[1, 2, 6],
            &[1, 3, 4],
            &[1, 5, 6],
            &[2, 3, 5],
            &[2, 4, 5],
            &[3, 4, 6],
            &[3, 5, 6],
        ];
        let complex = complex_of(faces);
        assert_eq!(complex.count(0), 7);
        assert_eq!(complex.count(1), 21);
        assert_eq!(complex.count(2), 14);
        let certificate = homology(&complex).expect("homology of the torus");
        assert_eq!(betti_vec(&certificate), vec![1, 2, 1]);
        assert_eq!(torsion_at(&certificate, 0), Vec::<i128>::new());
        assert_eq!(torsion_at(&certificate, 1), Vec::<i128>::new());
        assert_eq!(torsion_at(&certificate, 2), Vec::<i128>::new());
        assert_eq!(certificate.euler_characteristic, 0);
        certificate.verify(&complex).expect("certificate verifies");
    }

    /// The standard 6-vertex triangulation of the real projective plane (the
    /// antipodal quotient of the icosahedron): 10 triangles, 15 edges, 6
    /// vertices. `H_1 = Z/2`, so `b = (1, 0, 0)` with a torsion coefficient of
    /// `2` at dimension 1.
    #[test]
    fn the_six_vertex_projective_plane_has_betti_one_zero_zero_and_z_mod_2() {
        let faces: &[&[usize]] = &[
            &[0, 1, 2],
            &[0, 1, 4],
            &[0, 2, 3],
            &[0, 3, 5],
            &[0, 4, 5],
            &[1, 2, 5],
            &[1, 3, 4],
            &[1, 3, 5],
            &[2, 3, 4],
            &[2, 4, 5],
        ];
        let complex = complex_of(faces);
        assert_eq!(complex.count(0), 6);
        assert_eq!(complex.count(1), 15);
        assert_eq!(complex.count(2), 10);
        let certificate = homology(&complex).expect("homology of RP^2");
        assert_eq!(betti_vec(&certificate), vec![1, 0, 0]);
        assert_eq!(torsion_at(&certificate, 0), Vec::<i128>::new());
        assert_eq!(torsion_at(&certificate, 1), vec![2]);
        assert_eq!(torsion_at(&certificate, 2), Vec::<i128>::new());
        assert_eq!(certificate.euler_characteristic, 1);
        certificate.verify(&complex).expect("certificate verifies");
    }

    /// A 9-vertex, 18-triangle triangulation of the Klein bottle: a 3x3 grid
    /// of squares (each split into two triangles) with the columns wrapped
    /// normally and the rows wrapped with a reflection, the standard
    /// square-with-a-twist presentation. Checked separately (in Python) to be
    /// a closed non-orientable surface of Euler characteristic 0.
    /// `H_1 = Z (+) Z/2`, so `b = (1, 1, 0)` with a torsion coefficient of `2`
    /// at dimension 1.
    #[test]
    fn the_nine_vertex_klein_bottle_has_betti_one_one_zero_and_z_plus_z_mod_2() {
        let faces: &[&[usize]] = &[
            &[0, 1, 3],
            &[0, 1, 6],
            &[0, 2, 5],
            &[0, 2, 7],
            &[0, 3, 5],
            &[0, 6, 7],
            &[1, 2, 4],
            &[1, 2, 8],
            &[1, 3, 4],
            &[1, 6, 8],
            &[2, 4, 5],
            &[2, 7, 8],
            &[3, 4, 6],
            &[3, 5, 8],
            &[3, 6, 8],
            &[4, 5, 7],
            &[4, 6, 7],
            &[5, 7, 8],
        ];
        let complex = complex_of(faces);
        assert_eq!(complex.count(0), 9);
        assert_eq!(complex.count(1), 27);
        assert_eq!(complex.count(2), 18);
        let certificate = homology(&complex).expect("homology of the Klein bottle");
        assert_eq!(betti_vec(&certificate), vec![1, 1, 0]);
        assert_eq!(torsion_at(&certificate, 0), Vec::<i128>::new());
        assert_eq!(torsion_at(&certificate, 1), vec![2]);
        assert_eq!(torsion_at(&certificate, 2), Vec::<i128>::new());
        assert_eq!(certificate.euler_characteristic, 0);
        certificate.verify(&complex).expect("certificate verifies");
    }

    // ---- boundary matrix and complex-builder sanity ----

    #[test]
    fn boundary_matrix_of_a_triangle_has_the_alternating_sign_convention() {
        let complex = complex_of(&[&[0, 1, 2]]);
        // d_2: rows = edges (0,1),(0,2),(1,2); cols = the one triangle [0,1,2].
        let d2 = boundary_matrix(&complex, 2).expect("d_2 exists");
        assert_eq!(d2.rows(), 3);
        assert_eq!(d2.cols(), 1);
        // Row order is the BTreeSet's sorted order: (0,1) < (0,2) < (1,2).
        assert_eq!(d2.get(0, 0), Some(&CasExpr::int(1))); // remove vertex 2 -> (0,1), l=2, sign +1
        assert_eq!(d2.get(1, 0), Some(&CasExpr::int(-1))); // remove vertex 1 -> (0,2), l=1, sign -1
        assert_eq!(d2.get(2, 0), Some(&CasExpr::int(1))); // remove vertex 0 -> (1,2), l=0, sign +1
    }

    #[test]
    fn euler_characteristic_matches_the_alternating_face_count() {
        let complex = complex_of(&[&[0, 1, 2]]);
        // 3 vertices - 3 edges + 1 face = 1 (a filled triangle is contractible).
        assert_eq!(complex.euler_characteristic(), 1);
    }

    // ---- forged-certificate controls: verify must refuse each, with a
    // distinct reason, and a genuine certificate for the same complex must
    // still be admitted (so the refusal is not "always no"). ----

    #[test]
    fn verify_refuses_a_wrong_torsion_coefficient() {
        let faces: &[&[usize]] = &[
            &[0, 1, 2],
            &[0, 1, 4],
            &[0, 2, 3],
            &[0, 3, 5],
            &[0, 4, 5],
            &[1, 2, 5],
            &[1, 3, 4],
            &[1, 3, 5],
            &[2, 3, 4],
            &[2, 4, 5],
        ];
        let complex = complex_of(faces);
        let genuine = homology(&complex).expect("homology of RP^2");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        forged.torsion.insert(0, vec![3]); // RP^2 has no torsion in H_0 at all
        let err = forged
            .verify(&complex)
            .expect_err("wrong torsion must be refused");
        assert!(
            err.contains("torsion"),
            "reason should name torsion, got: {err}"
        );
    }

    /// ADVERSARIAL. Forge only `D`, leaving `U`, `V`, and the recorded
    /// boundary all genuine: `U * d_1 * V` no longer equals the forged `D`,
    /// even though the forged `D` is still a perfectly well-formed Smith
    /// diagonal (diagonal, non-negative, a valid divisibility chain). Without
    /// this specific check, `(U, D', V)` for any `D'` satisfying the shape
    /// and unimodularity guards alone would be admitted -- confirmed by
    /// mutation: disabling only the product-equality check left every other
    /// test in this module green.
    #[test]
    fn verify_refuses_a_forged_diagonal_that_breaks_the_product_identity() {
        let complex = complex_of(&[&[0, 1], &[1, 2], &[0, 2]]); // the circle
        let genuine = homology(&complex).expect("homology of a circle");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        let triple = forged.smith.get_mut(&1).expect("d_1 triple exists");
        // The genuine D for this d_1 is diag(1, 1, 0) (rank 2); diag(1, 1, 1)
        // is ALSO a valid Smith diagonal (divisibility chain 1 | 1 | 1) but is
        // not what U * d_1 * V actually equals.
        let forged_d = Matrix::from_rows(vec![
            vec![CasExpr::int(1), CasExpr::int(0), CasExpr::int(0)],
            vec![CasExpr::int(0), CasExpr::int(1), CasExpr::int(0)],
            vec![CasExpr::int(0), CasExpr::int(0), CasExpr::int(1)],
        ])
        .expect("3x3");
        triple.d = forged_d;
        let err = forged
            .verify(&complex)
            .expect_err("a D not equal to U * d_1 * V must be refused");
        assert!(err.contains("!= D"), "got: {err}");
    }

    #[test]
    fn verify_refuses_a_non_unimodular_transform() {
        let complex = complex_of(&[&[0, 1], &[1, 2], &[0, 2]]); // the circle
        let genuine = homology(&complex).expect("homology of a circle");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        let triple = forged.smith.get_mut(&1).expect("d_1 triple exists");
        // d_1 is 3x3 (rows = vertices, cols = edges) so U is 3x3; double row 0,
        // which multiplies det(U) by exactly 2, so it can no longer be
        // +/-1 regardless of U's specific entries. Recompute D as the ACTUAL
        // product `U' * d_1 * V` with the forged `U'`, so the
        // product-equality guard is trivially satisfied and this isolates the
        // unimodularity guard specifically (rather than tripping the
        // product-mismatch guard first, which a bare entry bump would: the
        // product changes along with `U`).
        triple.u = scale_row(&triple.u, 0, 2);
        triple.d = triple
            .u
            .mul(&triple.boundary)
            .and_then(|partial| partial.mul(&triple.v))
            .expect("conformable");
        let err = forged
            .verify(&complex)
            .expect_err("non-unimodular U must be refused");
        assert!(
            err.contains("unimodular"),
            "reason should name unimodularity, got: {err}"
        );
    }

    /// The `V` counterpart of `verify_refuses_a_non_unimodular_transform`:
    /// `U`'s unimodularity check does not also cover `V`. Confirmed by
    /// mutation: disabling only the `V` unimodularity check left every other
    /// test in this module green, so without a dedicated fixture that guard
    /// was unexercised.
    #[test]
    fn verify_refuses_a_non_unimodular_right_transform() {
        let complex = complex_of(&[&[0, 1], &[1, 2], &[0, 2]]); // the circle
        let genuine = homology(&complex).expect("homology of a circle");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        let triple = forged.smith.get_mut(&1).expect("d_1 triple exists");
        // d_1 is 3x3 so V is 3x3 too; double column 0 of V by scaling row 0 of
        // its TRANSPOSE-equivalent operation is awkward on this API, so scale
        // V directly via the same row-scaling helper applied to V (V need not
        // be square-symmetric for this: scaling any one row of a square
        // matrix multiplies its determinant by that factor, regardless of
        // which matrix it is).
        triple.v = scale_row(&triple.v, 0, 2);
        triple.d = triple
            .u
            .mul(&triple.boundary)
            .and_then(|partial| partial.mul(&triple.v))
            .expect("conformable");
        let err = forged
            .verify(&complex)
            .expect_err("non-unimodular V must be refused");
        assert!(
            err.contains("unimodular"),
            "reason should name unimodularity, got: {err}"
        );
    }

    /// ADVERSARIAL. Forge `D` and `V` TOGETHER via a column permutation `P`
    /// (`V' = V * P`, `D' = D * P`): `U * d_1 * V' = D'` still holds exactly
    /// (a permutation is unimodular, so `V'` is genuinely unimodular too), so
    /// every guard except the SHAPE check is satisfied by construction --
    /// `D'` is still diagonal and non-negative, but reordering `diag(1, 1, 0)`
    /// to `diag(1, 0, 1)` puts a nonzero invariant factor after a `0`, which
    /// breaks the divisibility-chain convention the Smith form is stated
    /// over. Confirmed by mutation: disabling only the shape check left every
    /// other test in this module green (the two non-unimodular-transform
    /// tests above are both caught by their OWN unimodularity check before
    /// shape is even reached, so neither exercises this guard).
    #[test]
    fn verify_refuses_a_diagonal_with_a_broken_divisibility_chain() {
        let complex = complex_of(&[&[0, 1], &[1, 2], &[0, 2]]); // the circle
        let genuine = homology(&complex).expect("homology of a circle");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        let triple = forged.smith.get_mut(&1).expect("d_1 triple exists");
        // The genuine D for this d_1 is diag(1, 1, 0); P swaps positions 1
        // and 2 (0-indexed), a permutation matrix (unimodular).
        let permutation = Matrix::from_rows(vec![
            vec![CasExpr::int(1), CasExpr::int(0), CasExpr::int(0)],
            vec![CasExpr::int(0), CasExpr::int(0), CasExpr::int(1)],
            vec![CasExpr::int(0), CasExpr::int(1), CasExpr::int(0)],
        ])
        .expect("3x3");
        triple.v = triple.v.mul(&permutation).expect("conformable");
        triple.d = triple.d.mul(&permutation).expect("conformable");
        let err = forged
            .verify(&complex)
            .expect_err("a broken divisibility chain must be refused");
        assert!(
            err.contains("Smith normal form"),
            "reason should name the shape violation, got: {err}"
        );
    }

    #[test]
    fn verify_refuses_a_dropped_face() {
        // The tetrahedron boundary (a 2-sphere) minus one of its four
        // triangles: a disk, which is contractible (b = 1, 0), not a sphere.
        let complex = complex_of(&[&[0, 1, 2], &[0, 1, 3], &[0, 2, 3], &[1, 2, 3]]);
        let genuine = homology(&complex).expect("homology of the 2-sphere");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let dropped = complex_of(&[&[0, 1, 2], &[0, 1, 3], &[0, 2, 3]]);
        let err = genuine
            .verify(&dropped)
            .expect_err("a certificate for the sphere must be refused against a disk");
        assert!(
            err.contains("simplex count") || err.contains("boundary matrix"),
            "reason should name the simplex-count or boundary mismatch, got: {err}"
        );
    }

    #[test]
    fn verify_refuses_a_wrong_betti_number() {
        let complex = complex_of(&[&[0, 1]]); // an interval, b = (1, 0)
        let genuine = homology(&complex).expect("homology of an interval");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        forged.betti.insert(0, 2); // an interval has exactly one component
        let err = forged
            .verify(&complex)
            .expect_err("wrong betti number must be refused");
        assert!(
            err.contains("betti"),
            "reason should name the betti mismatch, got: {err}"
        );
    }

    /// ADVERSARIAL, and NOT subsumed by `verify_refuses_a_dropped_face`:
    /// forge only the `simplex_counts` summary field, leaving every Smith
    /// triple (and so every boundary matrix) exactly as the genuine
    /// certificate recorded them for `complex`. A dropped-face certificate
    /// is refused via a boundary-matrix shape mismatch regardless of whether
    /// `simplex_counts_match` runs at all (confirmed: deleting that guard's
    /// check left every existing test green, because it and
    /// `boundaries_match` were both watching the SAME forgery). This fixture
    /// is the one construction that isolates `simplex_counts_match`: nothing
    /// else in the certificate is wrong, so only this guard can catch it.
    #[test]
    fn verify_refuses_a_forged_simplex_count_with_every_boundary_genuine() {
        let complex = complex_of(&[&[0, 1]]); // an interval
        let genuine = homology(&complex).expect("homology of an interval");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        forged.simplex_counts.insert(0, 3); // the interval has 2 vertices, not 3
        let err = forged
            .verify(&complex)
            .expect_err("a forged simplex count must be refused");
        assert!(
            err.contains("simplex count"),
            "reason should name the simplex-count mismatch, got: {err}"
        );
    }

    /// ADVERSARIAL. Forge only the recorded `euler_characteristic` field,
    /// leaving every Smith triple, Betti number, and torsion list genuine.
    #[test]
    fn verify_refuses_a_forged_euler_characteristic() {
        let complex = complex_of(&[&[0, 1]]); // an interval, euler characteristic 1
        let genuine = homology(&complex).expect("homology of an interval");
        assert!(
            genuine.verify(&complex).is_ok(),
            "genuine certificate must verify"
        );

        let mut forged = genuine.clone();
        forged.euler_characteristic = 7;
        let err = forged
            .verify(&complex)
            .expect_err("a forged euler characteristic must be refused");
        assert!(
            err.contains("euler characteristic"),
            "reason should name the euler characteristic mismatch, got: {err}"
        );
    }

    // ---- guard-level mutation-testing controls: each of these pins the
    // effect a specific guard has, so deleting that guard from `verify`
    // demonstrably kills the corresponding test above (see the module's
    // final report for which guards were exercised this way by hand). ----

    #[test]
    fn boundaries_match_refuses_an_unrelated_recorded_boundary() {
        let complex = complex_of(&[&[0, 1], &[1, 2], &[0, 2]]); // circle
        let other = complex_of(&[&[0, 1]]); // interval, different shape entirely
        let mut certificate = homology(&complex).expect("homology of a circle");
        // Swap in the interval's d_1 at dimension 1, an unrelated boundary.
        let interval_d1 = boundary_matrix(&other, 1).expect("interval d_1");
        certificate.smith.get_mut(&1).expect("d_1 exists").boundary = interval_d1;
        let rebuilt = rebuild_boundaries(&complex, certificate.max_dimension).expect("rebuilds");
        let err = boundaries_match(&certificate, &rebuilt)
            .expect_err("an unrelated boundary matrix must be refused");
        assert!(err.contains("does not match"), "got: {err}");
    }

    /// Direct unit test of `compositions_are_zero`, isolated from `verify`.
    ///
    /// This guard checks a property of the COMPLEX alone (rebuilt boundary
    /// matrices), not of anything a certificate claims -- and every
    /// `SimplicialComplex` reachable through the public
    /// `from_maximal_simplices` constructor is closed under faces by
    /// construction, which makes `d_{k-1} . d_k = 0` an unconditional
    /// mathematical fact for it. So no certificate forgery over a genuinely
    /// constructed complex can trip this guard (confirmed: disabling it while
    /// `boundary_matrix`'s sign convention stays correct left every other
    /// test in this module green). What it defends against is a bug in
    /// `boundary_matrix` itself: a `boundaries_match` round-trip alone would
    /// NOT catch a sign-convention bug that stayed consistent between
    /// production and verification (both call the same, equally-buggy
    /// `boundary_matrix`), which is exactly why `verify` also checks this
    /// mathematical identity directly rather than only comparing against
    /// what was recorded. This test exercises the guard function itself with
    /// two hand-built matrices whose product is not zero, standing in for
    /// that kind of bug.
    #[test]
    fn compositions_are_zero_refuses_a_genuinely_non_zero_composition() {
        let mut rebuilt: BTreeMap<usize, Matrix> = BTreeMap::new();
        rebuilt.insert(0, Matrix::new(1, 1, vec![CasExpr::int(1)]).expect("1x1"));
        rebuilt.insert(1, Matrix::new(1, 1, vec![CasExpr::int(1)]).expect("1x1"));
        let err = compositions_are_zero(&rebuilt, 0)
            .expect_err("a nonzero d_0 . d_1 product must be refused");
        assert!(err.contains("is not the zero matrix"), "got: {err}");

        // POSITIVE CONTROL: a genuinely zero composition is admitted, so the
        // guard is not simply refusing everything.
        let mut zero_rebuilt: BTreeMap<usize, Matrix> = BTreeMap::new();
        zero_rebuilt.insert(0, Matrix::new(1, 1, vec![CasExpr::int(0)]).expect("1x1"));
        zero_rebuilt.insert(1, Matrix::new(1, 1, vec![CasExpr::int(1)]).expect("1x1"));
        assert!(compositions_are_zero(&zero_rebuilt, 0).is_ok());
    }

    /// Direct unit test of `euler_characteristic_matches`'s SECOND check
    /// (the alternating-sum-of-Betti-numbers comparison), isolated from
    /// `verify`.
    ///
    /// Given the earlier guards already pass, the alternating sum of the
    /// recomputed Betti numbers equaling the complex's Euler characteristic
    /// is the Euler-Poincare formula -- a mathematical theorem, not a claim a
    /// certificate forgery can falsify once every per-dimension Betti number
    /// has independently been confirmed correct (confirmed by mutation:
    /// disabling only this check left every other test in this module
    /// green). This test instead calls the guard function directly with a
    /// hand-built `betti` map that is simply arithmetically inconsistent with
    /// the genuine certificate's own (correct) `euler_characteristic`, the
    /// way a bug in the rank-nullity arithmetic upstream might produce.
    #[test]
    fn euler_characteristic_matches_refuses_an_inconsistent_betti_alternating_sum() {
        let complex = complex_of(&[&[0, 1]]); // an interval, euler characteristic 1
        let genuine = homology(&complex).expect("homology of an interval");

        let mut wrong_betti = BTreeMap::new();
        wrong_betti.insert(0, 1);
        wrong_betti.insert(1, 1); // alternating sum 1 - 1 = 0, not 1
        let err = euler_characteristic_matches(&genuine, &complex, &wrong_betti)
            .expect_err("an inconsistent alternating sum must be refused");
        assert!(err.contains("alternating sum"), "got: {err}");

        // POSITIVE CONTROL: the genuine betti numbers ARE admitted.
        let mut right_betti = BTreeMap::new();
        right_betti.insert(0, 1);
        right_betti.insert(1, 0);
        assert!(euler_characteristic_matches(&genuine, &complex, &right_betti).is_ok());
    }
}
