//! Matrix groups over ℚ (and ℤ): deciding **finiteness**, and the order when
//! finite, with a certificate for either verdict.
//!
//! # Why this module is not [`crate::matgroup`]
//!
//! [`crate::matgroup`] handles matrix groups over `𝔽ₚ`, where the group is
//! finite by construction and a faithful permutation action exists. Over ℚ
//! neither holds: the group generated by `[[1,1],[0,1]]` is infinite, and
//! there is no finite set of points to act on. So the question here is first
//! *is it finite at all*, and only then *what is its order*.
//!
//! # The route
//!
//! Both verdicts hang on one classical lemma.
//!
//! **Minkowski's lemma.** For an odd prime `p`, the kernel of
//! `GL(n, ℤ₍ₚ₎) → GL(n, 𝔽ₚ)` is torsion-free. (If `A = I + p^k B` with
//! `B ≢ 0 mod p` and `k ≥ 1`, then for a prime `q ≠ p` the expansion of
//! `A^q` has `q·p^k·B` as its lowest term, which is nonzero mod `p^(k+1)`;
//! and for `q = p` the next terms carry `p^(2k+1)` and `p^(pk)`, both
//! divisible by `p^(k+2)` when `p ≥ 3` and `k ≥ 1`, so `A^p ≠ I` as well.
//! Odd `p` is essential: `-I` is in the kernel for `p = 2`.)
//!
//! Pick an odd prime `p` dividing no denominator of any generator entry and
//! leaving every generator's determinant a unit mod `p`. Then every product
//! of generators and inverses stays in `GL(n, ℤ₍ₚ₎)`, reduction mod `p` is a
//! group homomorphism `G → Ḡ` inside `GL(n, 𝔽ₚ)`, and `Ḡ` is exactly the
//! group generated by the reduced generators — an `𝔽ₚ` matrix group, whose
//! order `N` [`crate::matgroup`] already computes and certifies.
//!
//! Now:
//!
//! - If `G` is finite, Minkowski makes the reduction injective on it, so
//!   `|G| = N`. Enumerating `G` by closure over ℚ and finding exactly `N`
//!   elements therefore *is* the order computation, with the closure check
//!   done in exact rational arithmetic.
//! - If the closure produces `N + 1` distinct elements, `G` cannot be finite
//!   (a finite `G` would have `|G| = N`). So **overflowing the budget is a
//!   proof of infiniteness**, not a failure — see
//!   [`InfiniteRoute::MinkowskiOverflow`].
//! - If the closure *halts* at fewer than `N` elements, that contradicts
//!   `|G| = N` and is a bug in this file, not a fact about `G`. It is
//!   reported as [`RationalMatrixGroupError::MinkowskiContradiction`] rather
//!   than declined or silently accepted as a smaller order.
//!
//! Two cheaper infiniteness routes run first, because they need no prime at
//! all. If `M` has finite order `k` then `M^k = I`, so the minimal
//! polynomial divides `x^k − 1`, which is squarefree; `M` is therefore
//! diagonalizable with root-of-unity eigenvalues, giving `|tr M| ≤ n` and
//! `|det M| = 1`. Either inequality failing at any word in the generators
//! proves that word has infinite order
//! ([`InfiniteRoute::TraceExceedsDimension`],
//! [`InfiniteRoute::DeterminantNotUnit`]). These are checked on every
//! element the closure walk produces, so "a short word" is covered without
//! a separate search.
//!
//! # The bound
//!
//! [`minkowski_bound`] is the explicit product formula for `M(n)` — every
//! finite subgroup of `GL(n, ℚ)` has order dividing it (`M(1) = 2`,
//! `M(2) = 24`, `M(3) = 48`, `M(4) = 5760`). It is used twice: as the
//! element budget's ceiling, and as an independent infiniteness test — `N`
//! not dividing `M(n)` proves `G` infinite
//! ([`InfiniteRoute::ReducedOrderNotDividingMinkowski`]) without enumerating
//! anything.
//!
//! # Reuse
//!
//! [`crate::matgroup::MatrixGroup`] computes and certifies `N`;
//! [`crate::matgroup::determinant_mod_p`] checks the unit condition;
//! [`crate::ntheory::is_prime`] and [`crate::ntheory::mod_inverse`] do the
//! modular arithmetic. Nothing in `matgroup.rs` or the `permgroup` files is
//! modified. The exact ℚ linear algebra here is a few dozen lines over
//! `BigRational` because `crate::Matrix` stores symbolic `CasExpr` entries
//! (a different problem, and a private module) and every
//! [`crate::matgroup`] primitive is mod `p`.
//!
//! # Out of scope
//!
//! Conjugating an arbitrary finite group into `GL(n, ℤ)`, classifying the
//! finite subgroups of `GL(n, ℚ)`, matrix groups over number fields, and any
//! structure theory of the infinite case (rank, arithmeticity, the Tits
//! alternative). A group this module cannot place lands in
//! [`RationalGroupVerdict::Declined`] with its cause.

use std::collections::{BTreeMap, BTreeSet};

use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::{Signed, Zero};

use crate::matgroup::{FpMatrix, MAX_POINTS, MatrixGroup, MatrixGroupError, determinant_mod_p};
use crate::ntheory::{is_prime, mod_inverse};

/// An `n × n` matrix over ℚ, stored row-major.
pub type QMatrix = Vec<Vec<BigRational>>;

/// The largest closure the finiteness walk will build before declining.
/// `M(4) = 5760` fits, `M(5) = 11520` does not — a group in dimension 5 or
/// above whose reduced order exceeds this declines rather than running for
/// an unbounded time.
pub const MAX_ELEMENTS: usize = 8_192;

/// The odd primes tried, in order, as the reduction modulus. A prime is
/// usable when it divides no entry denominator, leaves every generator's
/// determinant invertible mod `p`, and keeps the `𝔽ₚ` vector action's point
/// count inside [`crate::matgroup::MAX_POINTS`]. `2` is excluded on purpose:
/// Minkowski's lemma is false at `p = 2`.
pub const CANDIDATE_PRIMES: [i128; 9] = [3, 5, 7, 11, 13, 17, 19, 23, 29];

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// A reason [`classify_rational_matrix_group`] refused its input outright.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RationalMatrixGroupError {
    /// `n == 0`: no vector space, no group.
    InvalidDimension,
    /// A generator is not `n × n`.
    DimensionMismatch {
        /// Index into the generator list.
        generator_index: usize,
        /// The required row/column count.
        expected: usize,
        /// The generator's actual row count.
        rows: usize,
        /// The generator's actual (first-row) column count, or `expected`
        /// when the matrix has no rows.
        cols: usize,
    },
    /// A generator has determinant `0` over ℚ, so it is not invertible and
    /// generates no group.
    SingularGenerator {
        /// Index into the generator list.
        generator_index: usize,
    },
    /// The exact closure over ℚ halted at strictly fewer elements than the
    /// mod-`p` reduction's order. Minkowski's lemma forbids this, so it is
    /// a defect in this module rather than a fact about the input, and it
    /// is raised loudly instead of being declined or reported as a smaller
    /// order. Never observed.
    MinkowskiContradiction {
        /// The reduction modulus.
        prime: i128,
        /// The order of the reduction.
        reduced_order: u128,
        /// The number of distinct elements the ℚ closure produced.
        closure_size: usize,
    },
}

/// Why [`classify_rational_matrix_group`] could place the group neither as
/// finite nor as infinite. A decline claims nothing; it always names a
/// cause.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RationalGroupDecline {
    /// No prime in [`CANDIDATE_PRIMES`] was usable. Each entry records the
    /// prime and why it failed.
    NoUsablePrime {
        /// One `(prime, reason)` pair per candidate tried.
        tried: Vec<(i128, PrimeRejection)>,
    },
    /// A usable prime was found and the reduction has order
    /// `reduced_order`, but that exceeds [`MAX_ELEMENTS`], so the exact
    /// closure over ℚ was not attempted. The group is finite of that order
    /// or infinite; this module does not say which.
    ReducedOrderTooLarge {
        /// The reduction modulus.
        prime: i128,
        /// The order of the reduction.
        reduced_order: u128,
        /// [`MAX_ELEMENTS`].
        budget: usize,
    },
}

/// Why one candidate prime was not usable as the reduction modulus.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PrimeRejection {
    /// The `𝔽ₚ` vector action's point count exceeds
    /// [`crate::matgroup::MAX_POINTS`], so that action would be refused.
    TooManyPoints,
    /// Some entry's denominator is divisible by `p`, so the generator is
    /// not `p`-integral and does not reduce.
    NonIntegralEntry {
        /// Index into the generator list.
        generator_index: usize,
    },
    /// The reduced generator is singular mod `p`, so its inverse is not
    /// `p`-integral and the reduction is not defined on the whole group.
    SingularReduction {
        /// Index into the generator list.
        generator_index: usize,
    },
    /// [`crate::matgroup::MatrixGroup::from_generators`] refused the reduced
    /// generators.
    FpEncoding(MatrixGroupError),
}

// ---------------------------------------------------------------------------
// Exact ℚ linear algebra
// ---------------------------------------------------------------------------

fn zero() -> BigRational {
    BigRational::new(BigInt::from(0), BigInt::from(1))
}

fn one() -> BigRational {
    BigRational::new(BigInt::from(1), BigInt::from(1))
}

/// The `n × n` identity over ℚ.
fn identity(n: usize) -> QMatrix {
    (0..n)
        .map(|i| {
            (0..n)
                .map(|j| if i == j { one() } else { zero() })
                .collect()
        })
        .collect()
}

/// `left * right`, both `n × n` over ℚ.
fn mat_mul(left: &QMatrix, right: &QMatrix) -> QMatrix {
    let n = left.len();
    let mut out = vec![vec![zero(); n]; n];
    for i in 0..n {
        for k in 0..n {
            if left[i][k].is_zero() {
                continue;
            }
            for j in 0..n {
                let term = &left[i][k] * &right[k][j];
                out[i][j] = &out[i][j] + &term;
            }
        }
    }
    out
}

/// The exact determinant over ℚ, by Gaussian elimination with a nonzero
/// pivot search.
fn det_q(matrix: &QMatrix) -> BigRational {
    let n = matrix.len();
    if n == 0 {
        return one();
    }
    let mut m = matrix.clone();
    let mut det = one();
    for col in 0..n {
        let Some(pivot_row) = (col..n).find(|&r| !m[r][col].is_zero()) else {
            return zero();
        };
        if pivot_row != col {
            m.swap(pivot_row, col);
            det = -det;
        }
        let pivot = m[col][col].clone();
        det = &det * &pivot;
        for row in (col + 1)..n {
            if m[row][col].is_zero() {
                continue;
            }
            let factor = &m[row][col] / &pivot;
            // `row > col`, so split to borrow the pivot row and the target
            // row mutably at once (the same shape `matgroup::determinant_mod_p`
            // uses).
            let (upper, lower) = m.split_at_mut(row);
            let pivot_row_ref = &upper[col];
            let target_row = &mut lower[0];
            for (t, pv) in target_row.iter_mut().zip(pivot_row_ref.iter()).skip(col) {
                let delta = &factor * pv;
                *t = &*t - &delta;
            }
        }
    }
    det
}

/// The trace over ℚ.
fn trace_q(matrix: &QMatrix) -> BigRational {
    matrix
        .iter()
        .enumerate()
        .fold(zero(), |acc, (i, row)| &acc + &row[i])
}

fn check_shape(n: usize, generators: &[QMatrix]) -> Result<(), RationalMatrixGroupError> {
    if n == 0 {
        return Err(RationalMatrixGroupError::InvalidDimension);
    }
    for (gi, mat) in generators.iter().enumerate() {
        if mat.len() != n {
            return Err(RationalMatrixGroupError::DimensionMismatch {
                generator_index: gi,
                expected: n,
                rows: mat.len(),
                cols: mat.first().map_or(n, Vec::len),
            });
        }
        for row in mat {
            if row.len() != n {
                return Err(RationalMatrixGroupError::DimensionMismatch {
                    generator_index: gi,
                    expected: n,
                    rows: mat.len(),
                    cols: row.len(),
                });
            }
        }
        if det_q(mat).is_zero() {
            return Err(RationalMatrixGroupError::SingularGenerator {
                generator_index: gi,
            });
        }
    }
    Ok(())
}

/// The product of `generators[i]` for `i` in `word`, left to right, starting
/// from the identity.
fn word_value(n: usize, generators: &[QMatrix], word: &[usize]) -> Option<QMatrix> {
    let mut acc = identity(n);
    for &i in word {
        let g = generators.get(i)?;
        acc = mat_mul(&acc, g);
    }
    Some(acc)
}

// ---------------------------------------------------------------------------
// The Minkowski bound
// ---------------------------------------------------------------------------

/// The Minkowski bound `M(n)`: the product over primes `ℓ` of `ℓ` raised to
/// the sum over `k ≥ 0` of `⌊n / (ℓ^k (ℓ−1))⌋`. Every finite subgroup of
/// `GL(n, ℚ)` has order dividing it.
///
/// `M(0) = 1`, `M(1) = 2`, `M(2) = 24`, `M(3) = 48`, `M(4) = 5760`,
/// `M(5) = 11520`.
///
/// ```
/// use axeyum_cas::matgroup_q::minkowski_bound;
/// use num_bigint::BigInt;
/// assert_eq!(minkowski_bound(2), BigInt::from(24));
/// assert_eq!(minkowski_bound(4), BigInt::from(5760));
/// ```
pub fn minkowski_bound(n: usize) -> BigInt {
    let mut bound = BigInt::from(1);
    if n == 0 {
        return bound;
    }
    // Only primes `ℓ` with `ℓ − 1 ≤ n` contribute: above that every floor
    // term is zero.
    let mut ell: usize = 2;
    while ell <= n + 1 {
        if is_prime(i128::try_from(ell).unwrap_or(i128::MAX)) {
            let mut exponent: u32 = 0;
            let mut denom: usize = ell - 1;
            loop {
                let term = n / denom;
                if term == 0 {
                    break;
                }
                exponent += u32::try_from(term).unwrap_or(u32::MAX);
                let Some(next) = denom.checked_mul(ell) else {
                    break;
                };
                denom = next;
            }
            bound *= BigInt::from(ell).pow(exponent);
        }
        ell += 1;
    }
    bound
}

// ---------------------------------------------------------------------------
// Reduction mod p
// ---------------------------------------------------------------------------

fn bigint_mod_p(value: &BigInt, p: i128) -> i128 {
    let m = value % BigInt::from(p);
    let r = i128::try_from(m).unwrap_or(0);
    if r < 0 { r + p } else { r }
}

/// The entrywise reduction of `matrix` mod `p`, or `None` when some entry's
/// denominator is divisible by `p` (the matrix is not `p`-integral).
fn reduce_matrix_mod_p(matrix: &QMatrix, p: i128) -> Option<FpMatrix> {
    let mut out = Vec::with_capacity(matrix.len());
    for row in matrix {
        let mut new_row = Vec::with_capacity(row.len());
        for entry in row {
            let den = bigint_mod_p(entry.denom(), p);
            if den == 0 {
                return None;
            }
            let num = bigint_mod_p(entry.numer(), p);
            let inv = mod_inverse(den, p)?;
            new_row.push((num * inv).rem_euclid(p));
        }
        out.push(new_row);
    }
    Some(out)
}

/// The number of points of the `𝔽ₚ` vector action, or `None` on overflow.
fn vector_action_points(p: i128, n: usize) -> Option<usize> {
    let p_usize = usize::try_from(p).ok()?;
    p_usize.checked_pow(u32::try_from(n).ok()?)?.checked_sub(1)
}

/// A usable reduction modulus and the certified `𝔽ₚ` group it produced.
struct ChosenPrime {
    prime: i128,
    group: MatrixGroup,
}

/// Tries every candidate prime in order, returning the first usable one
/// together with the certified `𝔽ₚ` group its reduced generators build.
fn choose_prime(
    n: usize,
    generators: &[QMatrix],
) -> Result<ChosenPrime, Vec<(i128, PrimeRejection)>> {
    let mut tried = Vec::new();
    for &p in &CANDIDATE_PRIMES {
        match vector_action_points(p, n) {
            Some(points) if points <= MAX_POINTS => {}
            _ => {
                tried.push((p, PrimeRejection::TooManyPoints));
                continue;
            }
        }
        let mut reduced = Vec::with_capacity(generators.len());
        let mut rejected = None;
        for (gi, mat) in generators.iter().enumerate() {
            let Some(red) = reduce_matrix_mod_p(mat, p) else {
                rejected = Some(PrimeRejection::NonIntegralEntry {
                    generator_index: gi,
                });
                break;
            };
            if determinant_mod_p(&red, p) == Some(0) {
                rejected = Some(PrimeRejection::SingularReduction {
                    generator_index: gi,
                });
                break;
            }
            reduced.push(red);
        }
        if let Some(reason) = rejected {
            tried.push((p, reason));
            continue;
        }
        match MatrixGroup::from_generators(p, n, reduced) {
            Ok(group) => return Ok(ChosenPrime { prime: p, group }),
            Err(err) => tried.push((p, PrimeRejection::FpEncoding(err))),
        }
    }
    Err(tried)
}

// ---------------------------------------------------------------------------
// The closure walk
// ---------------------------------------------------------------------------

/// What the exact closure over ℚ found.
enum Closure {
    /// The walk closed: every listed element's product with every generator
    /// is already listed. The list is sorted and distinct.
    Closed(Vec<QMatrix>),
    /// The walk produced more than `budget` distinct elements; the carried
    /// words have pairwise distinct values.
    Exceeded(Vec<Vec<usize>>),
    /// A single element of the group was proved to have infinite order.
    InfiniteOrderElement(InfiniteRoute),
}

/// Breadth-first closure from the identity under right multiplication by the
/// generators, stopping at `budget + 1` distinct elements, and testing every
/// new element's trace and determinant against the root-of-unity bounds.
fn closure_walk(n: usize, generators: &[QMatrix], budget: usize) -> Closure {
    let n_as_rational = BigRational::new(BigInt::from(n), BigInt::from(1));
    let mut seen: BTreeMap<QMatrix, Vec<usize>> = BTreeMap::new();
    let identity_matrix = identity(n);
    seen.insert(identity_matrix.clone(), Vec::new());
    let mut frontier: Vec<(QMatrix, Vec<usize>)> = vec![(identity_matrix, Vec::new())];
    while !frontier.is_empty() {
        let mut next = Vec::new();
        for (mat, word) in &frontier {
            for (gi, g) in generators.iter().enumerate() {
                let product = mat_mul(mat, g);
                if seen.contains_key(&product) {
                    continue;
                }
                let mut new_word = word.clone();
                new_word.push(gi);
                let det = det_q(&product);
                if det.abs() != one() {
                    return Closure::InfiniteOrderElement(InfiniteRoute::DeterminantNotUnit {
                        word: new_word,
                        determinant: det,
                    });
                }
                let tr = trace_q(&product);
                if tr.abs() > n_as_rational {
                    return Closure::InfiniteOrderElement(InfiniteRoute::TraceExceedsDimension {
                        word: new_word,
                        trace: tr,
                    });
                }
                seen.insert(product.clone(), new_word.clone());
                if seen.len() > budget {
                    return Closure::Exceeded(seen.into_values().collect());
                }
                next.push((product, new_word));
            }
        }
        frontier = next;
    }
    Closure::Closed(seen.into_keys().collect())
}

// ---------------------------------------------------------------------------
// Certificates
// ---------------------------------------------------------------------------

/// A checkable certificate that the group generated by `generators` is
/// finite of order `reduced_order`, with `elements` its full element list.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FiniteRationalGroupCertificate {
    /// The dimension.
    pub n: usize,
    /// The generators, over ℚ.
    pub generators: Vec<QMatrix>,
    /// The odd prime the reduction used.
    pub prime: i128,
    /// The order of the mod-`prime` reduction — equal to the order of the
    /// group over ℚ by Minkowski's lemma.
    pub reduced_order: u128,
    /// Every element of the group, sorted and distinct.
    pub elements: Vec<QMatrix>,
    /// [`minkowski_bound`] at `n`, carried so `verify` cross-checks the
    /// divisibility instead of trusting the producer.
    pub minkowski_bound: BigInt,
}

/// How an [`InfiniteRationalGroupCertificate`] proves infiniteness.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum InfiniteRoute {
    /// The word's value has determinant of absolute value other than `1`.
    /// A finite-order matrix satisfies `det(M)^k = 1` with `det(M)` in ℚ,
    /// forcing `det(M) = ±1`.
    DeterminantNotUnit {
        /// Generator indices, multiplied left to right.
        word: Vec<usize>,
        /// The determinant of that product.
        determinant: BigRational,
    },
    /// The word's value has `|tr| > n`. A finite-order matrix has all
    /// eigenvalues roots of unity, so `|tr| ≤ n`.
    TraceExceedsDimension {
        /// Generator indices, multiplied left to right.
        word: Vec<usize>,
        /// The trace of that product.
        trace: BigRational,
    },
    /// The reduction's order does not divide `M(n)`. A finite `G` would
    /// have order equal to the reduction's (Minkowski) and dividing `M(n)`
    /// (the Minkowski bound), so `G` is infinite.
    ReducedOrderNotDividingMinkowski {
        /// The odd reduction modulus.
        prime: i128,
        /// The order of the reduction.
        reduced_order: u128,
        /// `M(n)`.
        minkowski_bound: BigInt,
    },
    /// More distinct elements were exhibited over ℚ than the reduction has.
    /// A finite `G` would have exactly as many.
    MinkowskiOverflow {
        /// The odd reduction modulus.
        prime: i128,
        /// The order of the reduction.
        reduced_order: u128,
        /// Words in the generators whose values are pairwise distinct, more
        /// of them than `reduced_order`.
        witnesses: Vec<Vec<usize>>,
    },
}

/// A checkable certificate that the group generated by `generators` is
/// infinite.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InfiniteRationalGroupCertificate {
    /// The dimension.
    pub n: usize,
    /// The generators, over ℚ.
    pub generators: Vec<QMatrix>,
    /// Which argument this certificate makes.
    pub route: InfiniteRoute,
}

/// Why a [`RationalGroupVerdict`] failed to verify.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RationalGroupFailure {
    /// `n == 0`, or a generator is not `n × n`, or a generator is singular.
    MalformedGenerators,
    /// `prime` is not an odd prime.
    ///
    /// This is the one guard whose two certificates need it for different
    /// reasons, and only one of them needs it for soundness. A
    /// [`FiniteRationalGroupCertificate`] does not: its element-list checks
    /// are complete on their own (see
    /// [`FiniteRationalGroupCertificate::verify`]), and only surjectivity of
    /// the reduction is used, which holds at every modulus where the
    /// reduction is defined. An [`InfiniteRationalGroupCertificate`]'s
    /// [`InfiniteRoute::MinkowskiOverflow`] and
    /// [`InfiniteRoute::ReducedOrderNotDividingMinkowski`] routes *do*:
    /// both argue "a finite `G` would have `|G| = |Ḡ|`", which is
    /// Minkowski's INJECTIVITY, and that is false at `2` — the group
    /// generated by `-I` has order 2 and reduces to the trivial group mod
    /// `2`, so the overflow route at `p = 2` would call a finite group
    /// infinite. `an_overflow_certificate_at_the_even_prime_is_refused`
    /// exhibits exactly that certificate.
    PrimeNotOdd {
        /// The offending modulus.
        prime: i128,
    },
    /// A generator does not reduce mod `prime`, or reduces to a singular
    /// matrix.
    ReductionUndefined {
        /// Index into the generator list.
        generator_index: usize,
    },
    /// The `𝔽ₚ` encoding of the reduced generators could not be rebuilt.
    FpGroupNotRebuildable,
    /// The rebuilt `𝔽ₚ` group's own certificates do not verify.
    FpCertificateInvalid,
    /// The rebuilt `𝔽ₚ` group's order is not the claimed `reduced_order`.
    ReducedOrderWrong {
        /// The order the certificate claims.
        claimed: u128,
        /// The order recomputed from the reduced generators.
        recomputed: u128,
    },
    /// The carried bound is not `M(n)`.
    MinkowskiBoundWrong,
    /// `reduced_order` does not divide `M(n)`, so it cannot be a finite
    /// group's order.
    OrderDoesNotDivideMinkowskiBound,
    /// The element list has a repeat, or is not sorted.
    ElementsNotDistinct,
    /// The element list does not have `reduced_order` entries.
    ElementCountWrong {
        /// `reduced_order`.
        claimed: u128,
        /// The list length.
        listed: usize,
    },
    /// The identity is not in the element list.
    IdentityMissing,
    /// A generator is not in the element list.
    GeneratorMissing {
        /// Index into the generator list.
        generator_index: usize,
    },
    /// Some listed element times some generator is not listed, so the list
    /// is not closed.
    NotClosed {
        /// Index into the element list.
        element_index: usize,
        /// Index into the generator list.
        generator_index: usize,
    },
    /// A witness word names a generator index that does not exist.
    WordOutOfRange,
    /// The infiniteness route's own inequality does not hold: the
    /// determinant is a unit after all, or `|tr| ≤ n`, or the reduced order
    /// divides `M(n)`.
    RouteInequalityFails,
    /// The overflow route's witness values are not pairwise distinct.
    WitnessesNotDistinct,
    /// The overflow route exhibits at most `reduced_order` distinct
    /// elements, which is consistent with a finite group.
    WitnessCountTooSmall {
        /// The number of distinct witness values.
        distinct: usize,
        /// The order of the reduction.
        reduced_order: u128,
    },
}

/// Rebuilds and verifies the mod-`prime` reduction, returning the certified
/// `𝔽ₚ` group. Shared by both certificates so the two cannot drift.
fn verify_reduction(
    n: usize,
    generators: &[QMatrix],
    prime: i128,
    claimed_order: u128,
) -> Result<MatrixGroup, RationalGroupFailure> {
    if prime <= 2 || !is_prime(prime) {
        return Err(RationalGroupFailure::PrimeNotOdd { prime });
    }
    let mut reduced = Vec::with_capacity(generators.len());
    for (gi, mat) in generators.iter().enumerate() {
        let red =
            reduce_matrix_mod_p(mat, prime).ok_or(RationalGroupFailure::ReductionUndefined {
                generator_index: gi,
            })?;
        if determinant_mod_p(&red, prime) == Some(0) {
            return Err(RationalGroupFailure::ReductionUndefined {
                generator_index: gi,
            });
        }
        reduced.push(red);
    }
    let group = MatrixGroup::from_generators(prime, n, reduced)
        .map_err(|_| RationalGroupFailure::FpGroupNotRebuildable)?;
    if group.action_certificate().verify().is_err() {
        return Err(RationalGroupFailure::FpCertificateInvalid);
    }
    if group
        .permutation_group()
        .order_certificate()
        .verify()
        .is_err()
    {
        return Err(RationalGroupFailure::FpCertificateInvalid);
    }
    if group.order() != claimed_order {
        return Err(RationalGroupFailure::ReducedOrderWrong {
            claimed: claimed_order,
            recomputed: group.order(),
        });
    }
    Ok(group)
}

impl FiniteRationalGroupCertificate {
    /// Re-derives the whole claim from this certificate's own fields.
    ///
    /// Nothing stored is taken on trust: the reduction is recomputed from
    /// the ℚ generators, the `𝔽ₚ` group is rebuilt and its own certificates
    /// verified, [`minkowski_bound`] is recomputed, and the element list is
    /// checked to be a sorted, distinct, identity-containing,
    /// generator-containing and generator-closed set of exactly
    /// `reduced_order` matrices.
    ///
    /// **Those checks are already complete, and Minkowski's lemma is not
    /// among them.** A finite set `S` containing the identity and closed
    /// under right multiplication by the generators contains every word in
    /// the generators, so it contains the monoid they generate, which — being
    /// finite — is the group `G` they generate. Hence `G` is finite and
    /// `|G| ≤ |S|`. Reduction mod `prime` is defined on all of `S` (every
    /// element is a product of `p`-integral matrices) and maps `G` *onto* the
    /// rebuilt `𝔽ₚ` group, so `|Ḡ| ≤ |G|`. With `|S| = |Ḡ| = reduced_order`
    /// the three collapse: `S = G` and `|G| = reduced_order`. Only
    /// SURJECTIVITY of the reduction is used. Minkowski's injectivity is what
    /// the *producer* needs, to know the budget it may stop at; the checker
    /// does not inherit that dependency.
    ///
    /// # Errors
    ///
    /// [`RationalGroupFailure`], naming the first check that failed.
    pub fn verify(&self) -> Result<(), RationalGroupFailure> {
        check_shape(self.n, &self.generators)
            .map_err(|_| RationalGroupFailure::MalformedGenerators)?;
        verify_reduction(self.n, &self.generators, self.prime, self.reduced_order)?;
        if self.minkowski_bound != minkowski_bound(self.n) {
            return Err(RationalGroupFailure::MinkowskiBoundWrong);
        }
        if (&self.minkowski_bound % BigInt::from(self.reduced_order)) != BigInt::from(0) {
            return Err(RationalGroupFailure::OrderDoesNotDivideMinkowskiBound);
        }
        // Sorted and strictly increasing is distinctness and determinism in
        // one pass.
        if !self.elements.windows(2).all(|w| w[0] < w[1]) {
            return Err(RationalGroupFailure::ElementsNotDistinct);
        }
        if u128::try_from(self.elements.len()).unwrap_or(u128::MAX) != self.reduced_order {
            return Err(RationalGroupFailure::ElementCountWrong {
                claimed: self.reduced_order,
                listed: self.elements.len(),
            });
        }
        let set: BTreeSet<&QMatrix> = self.elements.iter().collect();
        let id = identity(self.n);
        if !set.contains(&id) {
            return Err(RationalGroupFailure::IdentityMissing);
        }
        for (gi, g) in self.generators.iter().enumerate() {
            if !set.contains(g) {
                return Err(RationalGroupFailure::GeneratorMissing {
                    generator_index: gi,
                });
            }
        }
        for (ei, e) in self.elements.iter().enumerate() {
            for (gi, g) in self.generators.iter().enumerate() {
                if !set.contains(&mat_mul(e, g)) {
                    return Err(RationalGroupFailure::NotClosed {
                        element_index: ei,
                        generator_index: gi,
                    });
                }
            }
        }
        Ok(())
    }

    /// The group's order.
    pub fn order(&self) -> u128 {
        self.reduced_order
    }
}

impl InfiniteRationalGroupCertificate {
    /// Re-derives infiniteness from this certificate's own fields.
    ///
    /// # Errors
    ///
    /// [`RationalGroupFailure`], naming the first check that failed.
    pub fn verify(&self) -> Result<(), RationalGroupFailure> {
        check_shape(self.n, &self.generators)
            .map_err(|_| RationalGroupFailure::MalformedGenerators)?;
        let n_as_rational = BigRational::new(BigInt::from(self.n), BigInt::from(1));
        match &self.route {
            InfiniteRoute::DeterminantNotUnit { word, determinant } => {
                let value = word_value(self.n, &self.generators, word)
                    .ok_or(RationalGroupFailure::WordOutOfRange)?;
                let det = det_q(&value);
                if det != *determinant || det.abs() == one() {
                    return Err(RationalGroupFailure::RouteInequalityFails);
                }
                Ok(())
            }
            InfiniteRoute::TraceExceedsDimension { word, trace } => {
                let value = word_value(self.n, &self.generators, word)
                    .ok_or(RationalGroupFailure::WordOutOfRange)?;
                let tr = trace_q(&value);
                if tr != *trace || tr.abs() <= n_as_rational {
                    return Err(RationalGroupFailure::RouteInequalityFails);
                }
                Ok(())
            }
            InfiniteRoute::ReducedOrderNotDividingMinkowski {
                prime,
                reduced_order,
                minkowski_bound: bound,
            } => {
                verify_reduction(self.n, &self.generators, *prime, *reduced_order)?;
                if *bound != minkowski_bound(self.n) {
                    return Err(RationalGroupFailure::MinkowskiBoundWrong);
                }
                if (bound % BigInt::from(*reduced_order)) == BigInt::from(0) {
                    return Err(RationalGroupFailure::RouteInequalityFails);
                }
                Ok(())
            }
            InfiniteRoute::MinkowskiOverflow {
                prime,
                reduced_order,
                witnesses,
            } => {
                verify_reduction(self.n, &self.generators, *prime, *reduced_order)?;
                let mut values: BTreeSet<QMatrix> = BTreeSet::new();
                for word in witnesses {
                    let value = word_value(self.n, &self.generators, word)
                        .ok_or(RationalGroupFailure::WordOutOfRange)?;
                    if !values.insert(value) {
                        return Err(RationalGroupFailure::WitnessesNotDistinct);
                    }
                }
                let distinct = values.len();
                if u128::try_from(distinct).unwrap_or(u128::MAX) <= *reduced_order {
                    return Err(RationalGroupFailure::WitnessCountTooSmall {
                        distinct,
                        reduced_order: *reduced_order,
                    });
                }
                Ok(())
            }
        }
    }
}

/// What [`classify_rational_matrix_group`] decided.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RationalGroupVerdict {
    /// The group is finite, with the listed elements.
    Finite(FiniteRationalGroupCertificate),
    /// The group is infinite, by the carried route.
    Infinite(InfiniteRationalGroupCertificate),
    /// Neither was established. A decline claims nothing.
    Declined(RationalGroupDecline),
}

impl RationalGroupVerdict {
    /// Re-derives whatever this verdict claims.
    ///
    /// A [`RationalGroupVerdict::Declined`] claims nothing, so it verifies
    /// vacuously — the point of a decline is that it is never wrong.
    ///
    /// # Errors
    ///
    /// [`RationalGroupFailure`] from the underlying certificate.
    pub fn verify(&self) -> Result<(), RationalGroupFailure> {
        match self {
            RationalGroupVerdict::Finite(cert) => cert.verify(),
            RationalGroupVerdict::Infinite(cert) => cert.verify(),
            RationalGroupVerdict::Declined(_) => Ok(()),
        }
    }

    /// The group's order when this verdict is
    /// [`RationalGroupVerdict::Finite`], else `None`.
    pub fn order(&self) -> Option<u128> {
        match self {
            RationalGroupVerdict::Finite(cert) => Some(cert.order()),
            _ => None,
        }
    }

    /// Whether this verdict is [`RationalGroupVerdict::Finite`].
    pub fn is_finite(&self) -> bool {
        matches!(self, RationalGroupVerdict::Finite(_))
    }

    /// Whether this verdict is [`RationalGroupVerdict::Infinite`].
    pub fn is_infinite(&self) -> bool {
        matches!(self, RationalGroupVerdict::Infinite(_))
    }
}

// ---------------------------------------------------------------------------
// The entry point
// ---------------------------------------------------------------------------

/// The determinant and trace tests applied to each generator on its own —
/// the two infiniteness routes that need no reduction modulus at all.
fn generator_infinite_route(n: usize, generators: &[QMatrix]) -> Option<InfiniteRoute> {
    let n_as_rational = BigRational::new(BigInt::from(n), BigInt::from(1));
    for (gi, g) in generators.iter().enumerate() {
        let det = det_q(g);
        if det.abs() != one() {
            return Some(InfiniteRoute::DeterminantNotUnit {
                word: vec![gi],
                determinant: det,
            });
        }
        let tr = trace_q(g);
        if tr.abs() > n_as_rational {
            return Some(InfiniteRoute::TraceExceedsDimension {
                word: vec![gi],
                trace: tr,
            });
        }
    }
    None
}

/// Decides whether the subgroup of `GL(n, ℚ)` generated by `generators` is
/// finite, and computes its order when it is — see the module doc for the
/// Minkowski route and the two cheap infiniteness tests that precede it.
///
/// ```
/// use axeyum_cas::matgroup_q::{classify_rational_matrix_group, rational_matrix};
///
/// // The quarter turn generates a cyclic group of order 4.
/// let r = rational_matrix(&[&[(0, 1), (-1, 1)], &[(1, 1), (0, 1)]]).unwrap();
/// let verdict = classify_rational_matrix_group(2, vec![r]).unwrap();
/// assert_eq!(verdict.order(), Some(4));
/// assert!(verdict.verify().is_ok());
///
/// // A unipotent shear generates an infinite group.
/// let u = rational_matrix(&[&[(1, 1), (1, 1)], &[(0, 1), (1, 1)]]).unwrap();
/// let verdict = classify_rational_matrix_group(2, vec![u]).unwrap();
/// assert!(verdict.is_infinite());
/// assert!(verdict.verify().is_ok());
/// ```
///
/// # Errors
///
/// [`RationalMatrixGroupError`] for a malformed or singular generator list,
/// or for the unreachable contradiction described on
/// [`RationalMatrixGroupError::MinkowskiContradiction`].
pub fn classify_rational_matrix_group(
    n: usize,
    generators: Vec<QMatrix>,
) -> Result<RationalGroupVerdict, RationalMatrixGroupError> {
    check_shape(n, &generators)?;
    let bound = minkowski_bound(n);
    // Route 1: a generator whose determinant or trace already rules out
    // finite order. Checked before any prime is chosen because it is free.
    if let Some(route) = generator_infinite_route(n, &generators) {
        return Ok(RationalGroupVerdict::Infinite(
            InfiniteRationalGroupCertificate {
                n,
                generators,
                route,
            },
        ));
    }
    let ChosenPrime {
        prime,
        group: fp_group,
    } = match choose_prime(n, &generators) {
        Ok(found) => found,
        Err(tried) => {
            return Ok(RationalGroupVerdict::Declined(
                RationalGroupDecline::NoUsablePrime { tried },
            ));
        }
    };
    let reduced_order = fp_group.order();
    // Route 2: the reduced order does not divide the Minkowski bound.
    if (&bound % BigInt::from(reduced_order)) != BigInt::from(0) {
        return Ok(RationalGroupVerdict::Infinite(
            InfiniteRationalGroupCertificate {
                n,
                generators,
                route: InfiniteRoute::ReducedOrderNotDividingMinkowski {
                    prime,
                    reduced_order,
                    minkowski_bound: bound,
                },
            },
        ));
    }
    let budget = match usize::try_from(reduced_order) {
        Ok(budget) if budget <= MAX_ELEMENTS => budget,
        _ => {
            return Ok(RationalGroupVerdict::Declined(
                RationalGroupDecline::ReducedOrderTooLarge {
                    prime,
                    reduced_order,
                    budget: MAX_ELEMENTS,
                },
            ));
        }
    };
    match closure_walk(n, &generators, budget) {
        Closure::InfiniteOrderElement(route) => Ok(RationalGroupVerdict::Infinite(
            InfiniteRationalGroupCertificate {
                n,
                generators,
                route,
            },
        )),
        Closure::Exceeded(witnesses) => Ok(RationalGroupVerdict::Infinite(
            InfiniteRationalGroupCertificate {
                n,
                generators,
                route: InfiniteRoute::MinkowskiOverflow {
                    prime,
                    reduced_order,
                    witnesses,
                },
            },
        )),
        Closure::Closed(elements) => {
            if u128::try_from(elements.len()).unwrap_or(u128::MAX) != reduced_order {
                // Minkowski's lemma forbids this. Fail loudly.
                return Err(RationalMatrixGroupError::MinkowskiContradiction {
                    prime,
                    reduced_order,
                    closure_size: elements.len(),
                });
            }
            Ok(RationalGroupVerdict::Finite(
                FiniteRationalGroupCertificate {
                    n,
                    generators,
                    prime,
                    reduced_order,
                    elements,
                    minkowski_bound: bound,
                },
            ))
        }
    }
}

/// Builds a [`QMatrix`] from `(numerator, denominator)` pairs, row-major.
///
/// `None` when a denominator is zero or the rows have unequal lengths.
///
/// ```
/// use axeyum_cas::matgroup_q::rational_matrix;
/// let half_turn = rational_matrix(&[&[(-1, 1), (0, 1)], &[(0, 1), (-1, 1)]]).unwrap();
/// assert_eq!(half_turn.len(), 2);
/// ```
pub fn rational_matrix(rows: &[&[(i64, i64)]]) -> Option<QMatrix> {
    let width = rows.first()?.len();
    let mut out = Vec::with_capacity(rows.len());
    for row in rows {
        if row.len() != width {
            return None;
        }
        let mut new_row = Vec::with_capacity(width);
        for &(num, den) in *row {
            if den == 0 {
                return None;
            }
            new_row.push(BigRational::new(BigInt::from(num), BigInt::from(den)));
        }
        out.push(new_row);
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn m(rows: &[&[(i64, i64)]]) -> QMatrix {
        rational_matrix(rows).expect("well-formed literal")
    }

    /// The quarter turn: order 4 in `GL(2, ℚ)`.
    fn quarter_turn() -> QMatrix {
        m(&[&[(0, 1), (-1, 1)], &[(1, 1), (0, 1)]])
    }

    /// The unipotent shear: infinite order.
    fn shear() -> QMatrix {
        m(&[&[(1, 1), (1, 1)], &[(0, 1), (1, 1)]])
    }

    fn finite_cert(n: usize, gens: Vec<QMatrix>) -> FiniteRationalGroupCertificate {
        match classify_rational_matrix_group(n, gens).expect("well-formed") {
            RationalGroupVerdict::Finite(cert) => cert,
            other => panic!("expected a finite verdict, got {other:?}"),
        }
    }

    fn infinite_cert(n: usize, gens: Vec<QMatrix>) -> InfiniteRationalGroupCertificate {
        match classify_rational_matrix_group(n, gens).expect("well-formed") {
            RationalGroupVerdict::Infinite(cert) => cert,
            other => panic!("expected an infinite verdict, got {other:?}"),
        }
    }

    // -----------------------------------------------------------------------
    // The bound
    // -----------------------------------------------------------------------

    #[test]
    fn minkowski_bound_matches_the_classical_values() {
        // 1, 2, 24, 48, 5760, 11520, 2903040 -- Minkowski's own table.
        let expected = [1u64, 2, 24, 48, 5760, 11520, 2_903_040];
        for (n, want) in expected.iter().enumerate() {
            assert_eq!(
                minkowski_bound(n),
                BigInt::from(*want),
                "M({n}) should be {want}"
            );
        }
    }

    #[test]
    fn every_finite_group_this_module_finds_has_order_dividing_the_bound() {
        for (n, gens) in [
            (2usize, vec![quarter_turn()]),
            (
                2,
                vec![
                    m(&[&[(0, 1), (1, 1)], &[(1, 1), (0, 1)]]),
                    m(&[&[(1, 1), (0, 1)], &[(0, 1), (-1, 1)]]),
                ],
            ),
            (
                3,
                vec![
                    m(&[
                        &[(0, 1), (0, 1), (1, 1)],
                        &[(1, 1), (0, 1), (0, 1)],
                        &[(0, 1), (1, 1), (0, 1)],
                    ]),
                    m(&[
                        &[(0, 1), (1, 1), (0, 1)],
                        &[(1, 1), (0, 1), (0, 1)],
                        &[(0, 1), (0, 1), (1, 1)],
                    ]),
                ],
            ),
        ] {
            let cert = finite_cert(n, gens);
            assert_eq!(
                &minkowski_bound(n) % BigInt::from(cert.order()),
                BigInt::from(0),
                "order {} should divide M({n})",
                cert.order()
            );
        }
    }

    // -----------------------------------------------------------------------
    // Finite groups
    // -----------------------------------------------------------------------

    #[test]
    fn the_quarter_turn_generates_a_cyclic_group_of_order_four() {
        let cert = finite_cert(2, vec![quarter_turn()]);
        assert_eq!(cert.order(), 4);
        assert_eq!(cert.elements.len(), 4);
        assert_eq!(cert.verify(), Ok(()));
        // Independent cross-check: the least k with R^k = I, by repeated
        // multiplication, sharing no code with the closure walk.
        let r = quarter_turn();
        let mut power = identity(2);
        let mut k = 0u32;
        loop {
            power = mat_mul(&power, &r);
            k += 1;
            if power == identity(2) {
                break;
            }
            assert!(k < 100, "the quarter turn should have small order");
        }
        assert_eq!(k, 4);
    }

    #[test]
    fn the_signed_permutations_of_the_plane_form_a_group_of_order_eight() {
        // The swap and a reflection generate the dihedral group of the
        // square, order 8 -- the full signed-permutation group in dimension 2.
        let swap = m(&[&[(0, 1), (1, 1)], &[(1, 1), (0, 1)]]);
        let flip = m(&[&[(1, 1), (0, 1)], &[(0, 1), (-1, 1)]]);
        let cert = finite_cert(2, vec![swap, flip]);
        assert_eq!(cert.order(), 8);
        assert_eq!(cert.verify(), Ok(()));
    }

    #[test]
    fn the_permutation_matrices_of_s3_have_order_six() {
        let three_cycle = m(&[
            &[(0, 1), (0, 1), (1, 1)],
            &[(1, 1), (0, 1), (0, 1)],
            &[(0, 1), (1, 1), (0, 1)],
        ]);
        let transposition = m(&[
            &[(0, 1), (1, 1), (0, 1)],
            &[(1, 1), (0, 1), (0, 1)],
            &[(0, 1), (0, 1), (1, 1)],
        ]);
        let cert = finite_cert(3, vec![three_cycle, transposition]);
        assert_eq!(cert.order(), 6);
        assert_eq!(cert.verify(), Ok(()));
    }

    #[test]
    fn a_non_integral_conjugate_of_the_quarter_turn_still_has_order_four() {
        // The quarter turn conjugated by diag(1, 2): the entries carry a
        // denominator, so this only works because the reduction is p-adic
        // rather than integral.
        let conjugate = m(&[&[(0, 1), (-1, 2)], &[(2, 1), (0, 1)]]);
        let cert = finite_cert(2, vec![conjugate]);
        assert_eq!(cert.order(), 4);
        assert_eq!(cert.prime, 3);
        assert_eq!(cert.verify(), Ok(()));
    }

    #[test]
    fn the_trivial_group_is_finite_of_order_one() {
        let cert = finite_cert(2, vec![identity(2)]);
        assert_eq!(cert.order(), 1);
        assert_eq!(cert.verify(), Ok(()));
    }

    #[test]
    fn an_empty_generator_list_is_the_trivial_group() {
        let cert = finite_cert(2, Vec::new());
        assert_eq!(cert.order(), 1);
        assert_eq!(cert.elements, vec![identity(2)]);
        assert_eq!(cert.verify(), Ok(()));
    }

    // -----------------------------------------------------------------------
    // Infinite groups, one test per route
    // -----------------------------------------------------------------------

    #[test]
    fn the_shear_is_infinite_by_overflowing_the_minkowski_budget() {
        let cert = infinite_cert(2, vec![shear()]);
        match &cert.route {
            InfiniteRoute::MinkowskiOverflow {
                prime,
                reduced_order,
                witnesses,
            } => {
                assert_eq!(*prime, 3);
                assert_eq!(*reduced_order, 3, "the shear has order 3 mod 3");
                assert_eq!(witnesses.len(), 4);
            }
            other => panic!("expected the overflow route, got {other:?}"),
        }
        assert_eq!(cert.verify(), Ok(()));
    }

    #[test]
    fn scaling_by_two_is_infinite_because_its_determinant_is_not_a_unit() {
        let cert = infinite_cert(2, vec![m(&[&[(2, 1), (0, 1)], &[(0, 1), (1, 1)]])]);
        assert!(matches!(
            cert.route,
            InfiniteRoute::DeterminantNotUnit { .. }
        ));
        assert_eq!(cert.verify(), Ok(()));
    }

    #[test]
    fn the_two_elementary_matrices_are_infinite_by_a_trace_above_the_dimension() {
        // Their product is [[2,1],[1,1]], trace 3 > 2 -- a word of length 2,
        // found by the closure walk rather than by a separate search.
        let lower = m(&[&[(1, 1), (0, 1)], &[(1, 1), (1, 1)]]);
        let cert = infinite_cert(2, vec![shear(), lower]);
        match &cert.route {
            InfiniteRoute::TraceExceedsDimension { word, trace } => {
                assert_eq!(word.len(), 2);
                assert_eq!(*trace, BigRational::new(BigInt::from(3), BigInt::from(1)));
            }
            other => panic!("expected the trace route, got {other:?}"),
        }
        assert_eq!(cert.verify(), Ok(()));
    }

    #[test]
    fn a_shear_with_a_denominator_of_three_is_infinite_by_the_bound_alone() {
        // 3 is unusable (the entry is not 3-integral), so the reduction runs
        // at 5, where the shear has order 5 -- and 5 does not divide 24. No
        // closure is ever built.
        let cert = infinite_cert(2, vec![m(&[&[(1, 1), (1, 3)], &[(0, 1), (1, 1)]])]);
        match &cert.route {
            InfiniteRoute::ReducedOrderNotDividingMinkowski {
                prime,
                reduced_order,
                minkowski_bound: bound,
            } => {
                assert_eq!(*prime, 5);
                assert_eq!(*reduced_order, 5);
                assert_eq!(*bound, BigInt::from(24));
            }
            other => panic!("expected the bound route, got {other:?}"),
        }
        assert_eq!(cert.verify(), Ok(()));
    }

    // -----------------------------------------------------------------------
    // Declines and refusals
    // -----------------------------------------------------------------------

    #[test]
    fn a_denominator_divisible_by_every_candidate_prime_declines() {
        let product: i64 = CANDIDATE_PRIMES
            .iter()
            .map(|&p| i64::try_from(p).expect("small"))
            .product();
        let verdict = classify_rational_matrix_group(
            2,
            vec![m(&[&[(1, 1), (1, product)], &[(0, 1), (1, 1)]])],
        )
        .expect("well-formed");
        match &verdict {
            RationalGroupVerdict::Declined(RationalGroupDecline::NoUsablePrime { tried }) => {
                assert_eq!(tried.len(), CANDIDATE_PRIMES.len());
                assert!(
                    tried.iter().all(|(_, reason)| matches!(
                        reason,
                        PrimeRejection::NonIntegralEntry { .. }
                    )),
                    "every candidate should be rejected for non-integrality: {tried:?}"
                );
            }
            other => panic!("expected a decline, got {other:?}"),
        }
        // A decline claims nothing, and is not a verdict either way.
        assert_eq!(verdict.order(), None);
        assert!(!verdict.is_finite() && !verdict.is_infinite());
    }

    #[test]
    fn a_zero_dimension_is_refused() {
        assert_eq!(
            classify_rational_matrix_group(0, Vec::new()),
            Err(RationalMatrixGroupError::InvalidDimension)
        );
    }

    #[test]
    fn a_singular_generator_is_refused() {
        assert_eq!(
            classify_rational_matrix_group(2, vec![m(&[&[(1, 1), (1, 1)], &[(1, 1), (1, 1)]])]),
            Err(RationalMatrixGroupError::SingularGenerator { generator_index: 0 })
        );
    }

    #[test]
    fn a_ragged_generator_is_refused() {
        let ragged = vec![vec![zero(), one()], vec![one()]];
        assert_eq!(
            classify_rational_matrix_group(2, vec![ragged]),
            Err(RationalMatrixGroupError::DimensionMismatch {
                generator_index: 0,
                expected: 2,
                rows: 2,
                cols: 1,
            })
        );
    }

    // -----------------------------------------------------------------------
    // Guard tests: each corrupts exactly one field of a valid certificate
    // -----------------------------------------------------------------------

    #[test]
    fn verify_rejects_an_even_reduction_modulus() {
        let mut cert = finite_cert(2, vec![quarter_turn()]);
        cert.prime = 2;
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::PrimeNotOdd { prime: 2 })
        );
    }

    #[test]
    fn an_overflow_certificate_at_the_even_prime_is_refused() {
        // The soundness-negative case for the oddness guard. `-I` generates a
        // group of order 2 -- FINITE -- but it lies in the kernel of the
        // reduction mod 2, so the reduced group is trivial and two distinct
        // elements over Q "overflow" a reduced order of 1. That is a wrong
        // verdict, and the only thing between it and the caller is the
        // requirement that the modulus be odd.
        let minus = m(&[&[(-1, 1), (0, 1)], &[(0, 1), (-1, 1)]]);
        let cert = InfiniteRationalGroupCertificate {
            n: 2,
            generators: vec![minus.clone()],
            route: InfiniteRoute::MinkowskiOverflow {
                prime: 2,
                reduced_order: 1,
                witnesses: vec![Vec::new(), vec![0]],
            },
        };
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::PrimeNotOdd { prime: 2 })
        );
        // ...and the group really is finite, of order 2.
        let verdict = classify_rational_matrix_group(2, vec![minus]).expect("well-formed");
        assert_eq!(verdict.order(), Some(2));
        assert_eq!(verdict.verify(), Ok(()));
    }

    #[test]
    fn verify_rejects_a_modulus_the_generators_do_not_reduce_at() {
        let mut cert = infinite_cert(2, vec![m(&[&[(1, 1), (1, 3)], &[(0, 1), (1, 1)]])]);
        if let InfiniteRoute::ReducedOrderNotDividingMinkowski { prime, .. } = &mut cert.route {
            *prime = 3;
        }
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::ReductionUndefined { generator_index: 0 })
        );
    }

    #[test]
    fn verify_rejects_a_tampered_reduced_order() {
        let mut cert = finite_cert(2, vec![quarter_turn()]);
        cert.reduced_order = 8;
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::ReducedOrderWrong {
                claimed: 8,
                recomputed: 4
            })
        );
    }

    #[test]
    fn verify_rejects_a_tampered_minkowski_bound() {
        let mut cert = finite_cert(2, vec![quarter_turn()]);
        cert.minkowski_bound = BigInt::from(48);
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::MinkowskiBoundWrong)
        );
    }

    #[test]
    fn verify_rejects_an_order_that_does_not_divide_the_bound() {
        // A hand-built certificate claiming the order-5 reduction is the
        // order of a finite rational group. No finite subgroup of GL(2, Q)
        // has order 5, and the divisibility guard is what says so.
        let generator = m(&[&[(1, 1), (1, 3)], &[(0, 1), (1, 1)]]);
        let cert = FiniteRationalGroupCertificate {
            n: 2,
            generators: vec![generator.clone()],
            prime: 5,
            reduced_order: 5,
            elements: vec![identity(2), generator],
            minkowski_bound: minkowski_bound(2),
        };
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::OrderDoesNotDivideMinkowskiBound)
        );
    }

    #[test]
    fn verify_rejects_an_element_list_that_is_not_sorted_and_distinct() {
        let mut cert = finite_cert(2, vec![quarter_turn()]);
        cert.elements.swap(0, 1);
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::ElementsNotDistinct)
        );
    }

    #[test]
    fn verify_rejects_an_element_list_of_the_wrong_length() {
        let mut cert = finite_cert(2, vec![quarter_turn()]);
        cert.elements.pop();
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::ElementCountWrong {
                claimed: 4,
                listed: 3
            })
        );
    }

    #[test]
    fn verify_rejects_an_element_list_without_the_identity() {
        // Order 2: {I, -I}. Replace the identity with 2I, keeping the count,
        // the sortedness and the generator.
        let minus = m(&[&[(-1, 1), (0, 1)], &[(0, 1), (-1, 1)]]);
        let mut elements = vec![minus.clone(), m(&[&[(2, 1), (0, 1)], &[(0, 1), (2, 1)]])];
        elements.sort();
        let cert = FiniteRationalGroupCertificate {
            n: 2,
            generators: vec![minus],
            prime: 3,
            reduced_order: 2,
            elements,
            minkowski_bound: minkowski_bound(2),
        };
        assert_eq!(cert.verify(), Err(RationalGroupFailure::IdentityMissing));
    }

    #[test]
    fn verify_rejects_an_element_list_missing_a_generator() {
        let minus = m(&[&[(-1, 1), (0, 1)], &[(0, 1), (-1, 1)]]);
        let mut elements = vec![identity(2), m(&[&[(2, 1), (0, 1)], &[(0, 1), (2, 1)]])];
        elements.sort();
        let cert = FiniteRationalGroupCertificate {
            n: 2,
            generators: vec![minus],
            prime: 3,
            reduced_order: 2,
            elements,
            minkowski_bound: minkowski_bound(2),
        };
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::GeneratorMissing { generator_index: 0 })
        );
    }

    #[test]
    fn verify_rejects_an_element_list_that_is_not_closed() {
        let mut cert = finite_cert(2, vec![quarter_turn()]);
        // Swap out the one element that is neither the identity nor the
        // generator, so the count, the identity and the generator all still
        // check out and only closure can catch it.
        let stray = m(&[&[(3, 1), (0, 1)], &[(0, 1), (3, 1)]]);
        let cube = mat_mul(&mat_mul(&quarter_turn(), &quarter_turn()), &quarter_turn());
        cert.elements.retain(|e| *e != cube);
        cert.elements.push(stray);
        cert.elements.sort();
        assert!(matches!(
            cert.verify(),
            Err(RationalGroupFailure::NotClosed { .. })
        ));
    }

    #[test]
    fn verify_rejects_an_infiniteness_claim_whose_determinant_is_a_unit() {
        let mut cert = infinite_cert(2, vec![m(&[&[(2, 1), (0, 1)], &[(0, 1), (1, 1)]])]);
        cert.generators = vec![quarter_turn()];
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::RouteInequalityFails)
        );
    }

    #[test]
    fn verify_rejects_an_infiniteness_claim_whose_trace_is_within_the_bound() {
        let lower = m(&[&[(1, 1), (0, 1)], &[(1, 1), (1, 1)]]);
        let mut cert = infinite_cert(2, vec![shear(), lower]);
        if let InfiniteRoute::TraceExceedsDimension { word, .. } = &mut cert.route {
            word.clear(); // the identity: trace 2, not above the dimension
        }
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::RouteInequalityFails)
        );
    }

    #[test]
    fn verify_rejects_a_bound_route_whose_claimed_order_is_not_the_reduction() {
        let mut cert = infinite_cert(2, vec![m(&[&[(1, 1), (1, 3)], &[(0, 1), (1, 1)]])]);
        // Claim the order-5 reduction has order 4, which divides 24. The
        // recomputed reduction catches it first -- that is the point: the
        // route inequality alone is not enough, the order has to be real.
        if let InfiniteRoute::ReducedOrderNotDividingMinkowski { reduced_order, .. } =
            &mut cert.route
        {
            *reduced_order = 4;
        }
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::ReducedOrderWrong {
                claimed: 4,
                recomputed: 5
            })
        );
    }

    #[test]
    fn verify_rejects_an_overflow_claim_with_a_repeated_witness() {
        let mut cert = infinite_cert(2, vec![shear()]);
        if let InfiniteRoute::MinkowskiOverflow { witnesses, .. } = &mut cert.route {
            let first = witnesses[0].clone();
            witnesses.push(first);
        }
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::WitnessesNotDistinct)
        );
    }

    #[test]
    fn verify_rejects_an_overflow_claim_with_too_few_witnesses() {
        let mut cert = infinite_cert(2, vec![shear()]);
        if let InfiniteRoute::MinkowskiOverflow { witnesses, .. } = &mut cert.route {
            witnesses.pop();
        }
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::WitnessCountTooSmall {
                distinct: 3,
                reduced_order: 3
            })
        );
    }

    #[test]
    fn verify_rejects_a_witness_word_naming_a_generator_that_does_not_exist() {
        let mut cert = infinite_cert(2, vec![shear()]);
        if let InfiniteRoute::MinkowskiOverflow { witnesses, .. } = &mut cert.route {
            witnesses.push(vec![7]);
        }
        assert_eq!(cert.verify(), Err(RationalGroupFailure::WordOutOfRange));
    }

    #[test]
    fn verify_rejects_a_certificate_whose_generators_are_malformed() {
        let mut cert = finite_cert(2, vec![quarter_turn()]);
        cert.generators = vec![vec![vec![one()]]];
        assert_eq!(
            cert.verify(),
            Err(RationalGroupFailure::MalformedGenerators)
        );
    }

    #[test]
    fn a_declined_verdict_verifies_vacuously() {
        let product: i64 = CANDIDATE_PRIMES
            .iter()
            .map(|&p| i64::try_from(p).expect("small"))
            .product();
        let verdict = classify_rational_matrix_group(
            2,
            vec![m(&[&[(1, 1), (1, product)], &[(0, 1), (1, 1)]])],
        )
        .expect("well-formed");
        assert!(matches!(verdict, RationalGroupVerdict::Declined(_)));
        assert_eq!(verdict.verify(), Ok(()));
    }
}
