//! Real quadratic fields: the regulator, the cycles of reduced indefinite
//! forms, and the narrow and ordinary class numbers.
//!
//! Item 4 of the CAS *Next Ten*, fourth wave. [`super`] gives the class group
//! of an **imaginary** quadratic order as a set, and
//! [`super::numberfield_classgroup`] gives it as a group; both stop at `D < 0`
//! and say so. This module is the `D > 0` half.
//!
//! Everything is exact [`BigInt`]. The one transcendental quantity — the
//! regulator `R = ln ε` — is carried as a **rational enclosure** produced and
//! checked by [`crate::enclosure`], never as a float. No `f64` appears in any
//! certified path here, and no new dependency is introduced.
//!
//! # What this module computes
//!
//! - [`reduced_indefinite_forms`] — every reduced primitive form of a positive
//!   non-square discriminant `D`, by the Gauss/Lagrange condition
//!   `|√D − 2|a|| < b < √D`.
//! - [`rho`] — the reduction step `ρ` on reduced indefinite forms, whose orbits
//!   are the *cycles*.
//! - [`form_cycles`] — the partition of the reduced forms into cycles, with a
//!   [`FormCycleCertificate`]. The number of cycles is the **narrow** class
//!   number `h⁺(D)`.
//! - [`real_class_number`] — the narrow class number, the ordinary class number
//!   `h(D)`, and the two independent cross-checks that pin the relation between
//!   them, as a [`RealClassNumberCertificate`].
//! - [`regulator`] — `R = ln ε` for the certified fundamental unit, as a
//!   [`RegulatorCertificate`] carrying an [`Enclosure`] of stated precision.
//!
//! # Which reduction, and why the cycles are the classes
//!
//! **Gauss (equivalently Lagrange) reduction, not Zagier reduction.** A form
//! `(a, b, c)` of positive non-square discriminant `D = b² − 4ac` is *reduced*
//! when
//!
//! ```text
//!     |√D − 2|a||  <  b  <  √D.
//! ```
//!
//! Zagier's alternative convention (`a > 0`, `c > 0`, `b > a + c`) picks a
//! different set of representatives and a different `ρ`; the two give the same
//! cycle count but not the same forms, so mixing them silently would be a
//! defect. This module is Gauss's throughout, and [`is_reduced_indefinite`] is
//! the only place the condition is written.
//!
//! Every inequality above is tested over ℤ, never over the reals: `b < √D` is
//! `b² < D`, `√D < 2|a| + b` is `D < (2|a| + b)²`, and `2|a| − b < √D` is
//! `2|a| − b ≤ 0` or `(2|a| − b)² < D`. `D` is not a square, so no comparison
//! can land on equality and no tie-breaking convention is needed.
//!
//! The step is
//!
//! ```text
//!     ρ(a, b, c) = (c, b', (b'² − D)/(4c)),
//!     b' ≡ −b (mod 2c),   √D − 2|c| < b' < √D.
//! ```
//!
//! A reduced form always has `|c| < √D`, so that window has length exactly
//! `2|c|` and contains exactly one member of the residue class; with
//! `r = ⌊√D⌋` the representative is `b' = r − ((r + b) mod 2|c|)`, which is
//! integer arithmetic only. `ρ` is a bijection of the reduced forms of `D`, so
//! the reduced forms fall into disjoint cycles, and the classical theorem is
//! that **two reduced forms are properly equivalent exactly when they lie in
//! the same cycle**. The classes of primitive forms of `D > 0` under `SL₂(ℤ)`
//! are the **narrow** class group `Cl⁺(D)`, so
//!
//! ```text
//!     h⁺(D) = the number of cycles.
//! ```
//!
//! # Narrow versus ordinary, and the two cross-checks
//!
//! `Cl⁺(D) → Cl(D)` is surjective with kernel generated by `g`, the class of
//! the negative `(−1, b*, −c*)` of the principal form, and `g² = 1`. So
//! `h(D) = h⁺(D)` when `g` is trivial and `h(D) = h⁺(D)/2` otherwise. Two
//! statements of *when*, computed by disjoint routes, are both recorded and
//! required to agree:
//!
//! 1. **The cycle route (certified).** Any form `(1, b, c)` is properly
//!    equivalent to `(1, b', c')` for every `b' ≡ b (mod 2)`, because the
//!    translation `(x, y) ↦ (x + k·y, y)` sends `b ↦ b + 2k` when `a = 1`.
//!    There is exactly one integer `b*` of the parity of `D` in
//!    `(√D − 2, √D)`, and `(1, b*, c*)` and `(−1, b*, −c*)` are both reduced.
//!    So the principal class is the cycle of `(1, b*, c*)`, `g` is the class of
//!    `(−1, b*, −c*)`, and `g` is trivial exactly when those two forms lie in
//!    the **same cycle** — a lookup in data the certificate already carries,
//!    needing no reduction algorithm and no unit.
//! 2. **The unit route (cross-check).** `g` is trivial exactly when the
//!    fundamental unit has norm `−1`. The certificate carries a
//!    [`FundamentalUnitCertificate`] from
//!    [`QuadraticField::fundamental_unit`], re-verifies it, and refuses when
//!    its norm disagrees with route 1.
//!
//! A note on which order that unit belongs to, because it matters and is easy
//! to get wrong: [`QuadraticField::fundamental_unit`] certifies the fundamental
//! unit of `ℤ[√d]`, which for `d ≡ 1 (mod 4)` is a *proper* suborder of
//! `O_K = ℤ[(1+√d)/2]`. The index of the unit groups for that conductor-2 order
//! is `1` or `3` — never even — so the **norm sign** is the same for both,
//! which is all route 2 uses. The *value* is not: see the regulator section.
//!
//! # The third route: reduction of ideals
//!
//! The certificate also carries an ideal-side count that uses neither route
//! above. Each reduced form `(a, b, c)` is mapped to the [`super::Ideal`]
//! Hermite triple
//!
//! ```text
//!     I = ℤ·|a| + ℤ·(B + ω),    B = −(b + t)/2  mod |a|,
//! ```
//!
//! with `ω = (t + √D)/2` the generator [`super::QuadraticOrder`] already
//! carries. This is [`super::numberfield_classgroup::ideal_of_form`]'s
//! correspondence with `|a|` in place of `a`, which is exactly right: the
//! ℤ-module `ℤ·a + ℤ·(−b + √D)/2` does not see the sign of `a`, and *forgetting
//! that sign is precisely the map `Cl⁺ → Cl`*. So the set of ideals attached to
//! a cycle depends only on the cycle's **ordinary** class, and
//!
//! ```text
//!     h(D) = the number of distinct ideal sets the cycles produce.
//! ```
//!
//! Every ideal is run through [`super::Ideal::admissible_in`] and its norm
//! recomputed, so a triple that is not an ideal of the order cannot pass. This
//! count is compared against route 1's answer; disagreement is a refusal.
//!
//! # The regulator
//!
//! `R = ln ε`. [`regulator`] builds the [`CasExpr`] `ln(a + b·√d)` from the
//! certificate's own `(d, a, b)` — the radical is enclosed first, then the sum,
//! then the logarithm — and hands it to [`crate::enclosure::enclose`] at the
//! requested precision, so the result is an interval of rational endpoints with
//! width at most `2^(−precision)` plus the per-step evidence
//! [`Enclosure::verify`] re-derives. [`RegulatorCertificate::verify`] rebuilds
//! the expression from `(d, a, b)` rather than trusting a stored one, which is
//! what stops a valid enclosure of a *different* number being pasted in.
//!
//! **Whose regulator.** It is the regulator of `ℤ[√d]`, the order whose unit
//! [`QuadraticField::fundamental_unit`] certifies. For `d ≡ 2, 3 (mod 4)` that
//! is the maximal order and this is `R_K`. For `d ≡ 1 (mod 4)` it is `m · R_K`
//! with `m ∈ {1, 3}` the unit index above — `d = 5` gives
//! `ln(2 + √5) = 3 · ln((1+√5)/2)`. Computing `m` is not done here; the
//! certificate reports the unit it used and nothing more.
//!
//! # What is NOT certified here
//!
//! - **Non-fundamental discriminants.** [`form_cycles`] is happy with any
//!   non-square `D ≡ 0, 1 (mod 4)` and counts `h⁺` of the order of that
//!   discriminant. [`real_class_number`] takes a [`super::QuadraticOrder`],
//!   which is always maximal, so the ideal cross-check is available only there.
//! - **The analytic class number formula.** `h·R = (√D/2)·L(1, χ_D)` is not
//!   exactly computable — `L(1, χ_D)` is a transcendental limit with no finite
//!   exact form — so it is not used as a check anywhere in this module. The
//!   ideal-side recount is the cross-check that replaces it.
//! - **The class group as a group** in the real case. Composition of the cycle
//!   representatives is Dirichlet's same formula, and
//!   [`super::numberfield_classgroup::compose`] declines on `D > 0` only
//!   because it reduces through the definite algorithm. Wiring that to the
//!   indefinite reduction is the next slice; this wave ships the counts and the
//!   regulator, not the Cayley table.
//! - **Degree > 2**, ray class groups, and the unit index `m` above.
//!
//! # Cost profile
//!
//! **ADVISORY.** The enumeration is `Θ(D)` outer steps each doing a `Θ(√D)`
//! divisor scan, so it is `Θ(D^{3/2})` bignum operations; the cycle walk is one
//! [`rho`] per reduced form; `verify` re-runs the enumeration, so checking
//! costs about what producing does. The regulator's cost is the enclosure's,
//! which grows quickly in the requested precision. Measured numbers, the host
//! and the load are in the lane report that landed this module.

use core::fmt;

use std::collections::BTreeSet;

use num_bigint::BigInt;
use num_traits::{One, Signed, Zero};

use crate::CasExpr;
use crate::enclosure::{
    BigInterval, DeclineReason as EncloseDecline, Enclosure, enclose_with_reason,
};
use crate::numberfield::{
    CertificateError, DeclineReason as UnitDecline, FundamentalUnitCertificate, Minimality,
    QuadraticField,
};

use super::{
    BinaryQuadraticForm, Ideal, IdealCertificateError, QuadraticOrder, big_isqrt,
    big_mod_positive, big_one, to_i128,
};

/// Largest discriminant [`reduced_indefinite_forms`] will enumerate.
///
/// The enumeration is `Θ(D^{3/2})`, so a large `D` would hang a gate rather
/// than answer. Above this the producer declines with
/// [`RealDecline::DiscriminantTooLarge`].
pub const REAL_DISCRIMINANT_BOUND: i64 = 100_000;

/// Largest number of `ρ` steps [`form_cycles`] will take before giving up on a
/// cycle closing.
///
/// `ρ` is a bijection of a finite set, so every orbit closes and this bound is
/// never reached for a genuine discriminant; it exists so a malformed input
/// declines instead of looping.
pub const CYCLE_STEP_BOUND: usize = 1_000_000;

/// Largest precision [`regulator`] will ask [`crate::enclosure::enclose`] for.
///
/// The enclosure cost grows quickly in the denominator sizes of the rational
/// series kernels; this keeps a mistyped precision from becoming a hang.
pub const REGULATOR_PRECISION_BOUND: u32 = 512;

// ---------------------------------------------------------------------------
// Refusals and declines
// ---------------------------------------------------------------------------

/// Why a real-quadratic certificate was refused.
///
/// Each variant names a distinct, independently reachable guard.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RealCertificateError {
    /// `D ≤ 0`, so there are no indefinite forms of this discriminant.
    DiscriminantNotPositive,
    /// `D ≢ 0, 1 (mod 4)`, so no integral form has this discriminant.
    DiscriminantNotAdmissible,
    /// `D` is a perfect square: the forms factor over ℚ and the theory does not
    /// apply.
    DiscriminantIsSquare,
    /// A listed form does not have the recorded discriminant.
    FormDiscriminantMismatch {
        /// Index of the cycle.
        cycle: usize,
        /// Index within the cycle.
        index: usize,
    },
    /// A listed form is imprimitive, so it is a multiple of a form of smaller
    /// discriminant and does not count towards `h⁺(D)`.
    FormNotPrimitive {
        /// Index of the cycle.
        cycle: usize,
        /// Index within the cycle.
        index: usize,
    },
    /// A listed form is not reduced.
    FormNotReduced {
        /// Index of the cycle.
        cycle: usize,
        /// Index within the cycle.
        index: usize,
    },
    /// The same form appears twice, so the cycles are not disjoint (or one
    /// cycle repeats itself).
    FormListedTwice {
        /// Index of the cycle the repeat was found in.
        cycle: usize,
        /// Index within that cycle.
        index: usize,
    },
    /// A cycle carries no forms.
    CycleEmpty {
        /// Index of the cycle.
        cycle: usize,
    },
    /// `ρ` applied to a cycle member is not the next member (cyclically), so
    /// the cycle is not closed under the reduction step.
    CycleNotClosed {
        /// Index of the cycle.
        cycle: usize,
        /// Index within the cycle whose successor is wrong.
        index: usize,
    },
    /// The checker's own enumeration of the reduced forms of `D` disagrees with
    /// the union of the listed cycles.
    CycleRecountMismatch {
        /// How many distinct forms the cycles carry.
        listed: usize,
        /// How many the checker found.
        recounted: usize,
    },
    /// The recorded narrow class number is not the number of cycles.
    NarrowClassNumberMismatch {
        /// What the certificate claims.
        claimed: usize,
        /// The number of cycles.
        cycles: usize,
    },
    /// The recorded order parameters are not the ones the radicand determines.
    OrderParametersMismatch,
    /// The recorded discriminant is not the order's.
    DiscriminantMismatch,
    /// The recorded index of the principal cycle, or of the cycle of the
    /// negative principal form, is not where the checker finds it.
    PrincipalCycleMismatch,
    /// The recorded ordinary class number does not follow from the narrow one
    /// and the principal-cycle criterion.
    OrdinaryClassNumberMismatch {
        /// What the certificate claims.
        claimed: usize,
        /// What the criterion gives.
        derived: usize,
    },
    /// `h⁺` is odd but the criterion says `h = h⁺/2`, which is impossible.
    NarrowClassNumberNotEven {
        /// The narrow class number.
        narrow: usize,
    },
    /// The fundamental unit's norm disagrees with the cycle criterion: norm
    /// `−1` must hold exactly when the principal form and its negative share a
    /// cycle.
    UnitNormDisagreesWithCycles {
        /// The unit's norm.
        norm: BigInt,
        /// Whether the two forms share a cycle.
        shares_cycle: bool,
    },
    /// The unit certificate did not verify.
    UnitCertificate(CertificateError),
    /// The unit certificate is for a different radicand.
    UnitRadicandMismatch,
    /// An ideal attached to a cycle is not an ideal of the order.
    IdealNotAdmissible {
        /// Index of the ideal class.
        class: usize,
        /// Why the Hermite triple was refused.
        reason: IdealCertificateError,
    },
    /// An ideal's norm is not the `|a|` of the form it came from.
    IdealNormMismatch {
        /// Index of the ideal class.
        class: usize,
    },
    /// The recorded ideal classes are not the distinct ideal sets the cycles
    /// produce.
    IdealClassesMismatch,
    /// The recorded cycle-to-ideal-class map is not the one the ideals give.
    IdealClassMapMismatch,
    /// The ideal-side count of ordinary classes disagrees with the
    /// principal-cycle criterion.
    IdealClassCountMismatch {
        /// The ideal-side count.
        ideal_side: usize,
        /// The cycle-side count.
        cycle_side: usize,
    },
    /// The regulator's `(d, a, b)` could not be lifted into a [`CasExpr`],
    /// whose integer constructor is `i128`.
    RegulatorMagnitudeOutOfRange,
    /// The recorded precision is not the enclosure's own.
    RegulatorPrecisionMismatch {
        /// What the certificate claims.
        claimed: u32,
        /// What the enclosure carries.
        enclosure: u32,
    },
    /// [`Enclosure::verify`] rejected the evidence against the expression
    /// rebuilt from `(d, a, b)`.
    RegulatorEnclosureRejected(String),
    /// The certificate's `fundamental_certified` label does not match whether
    /// the unit's minimality was actually proved.
    RegulatorMinimalityLabelMismatch {
        /// What the certificate claims.
        claimed: bool,
        /// What the unit certificate supports.
        supported: bool,
    },
}

impl fmt::Display for RealCertificateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RealCertificateError::DiscriminantNotPositive => {
                write!(f, "discriminant is not positive")
            }
            RealCertificateError::DiscriminantNotAdmissible => {
                write!(f, "discriminant is not 0 or 1 mod 4")
            }
            RealCertificateError::DiscriminantIsSquare => write!(f, "discriminant is a square"),
            RealCertificateError::FormDiscriminantMismatch { cycle, index } => write!(
                f,
                "form {index} of cycle {cycle} has the wrong discriminant"
            ),
            RealCertificateError::FormNotPrimitive { cycle, index } => {
                write!(f, "form {index} of cycle {cycle} is imprimitive")
            }
            RealCertificateError::FormNotReduced { cycle, index } => {
                write!(f, "form {index} of cycle {cycle} is not reduced")
            }
            RealCertificateError::FormListedTwice { cycle, index } => {
                write!(f, "form {index} of cycle {cycle} is listed twice")
            }
            RealCertificateError::CycleEmpty { cycle } => write!(f, "cycle {cycle} is empty"),
            RealCertificateError::CycleNotClosed { cycle, index } => write!(
                f,
                "rho of form {index} of cycle {cycle} is not the next form"
            ),
            RealCertificateError::CycleRecountMismatch { listed, recounted } => write!(
                f,
                "the cycles carry {listed} reduced forms but the recount found {recounted}"
            ),
            RealCertificateError::NarrowClassNumberMismatch { claimed, cycles } => write!(
                f,
                "narrow class number claimed {claimed} but there are {cycles} cycles"
            ),
            RealCertificateError::OrderParametersMismatch => {
                write!(f, "recorded order parameters are not the radicand's")
            }
            RealCertificateError::DiscriminantMismatch => {
                write!(f, "recorded discriminant is not the order's")
            }
            RealCertificateError::PrincipalCycleMismatch => {
                write!(f, "recorded principal cycle index is wrong")
            }
            RealCertificateError::OrdinaryClassNumberMismatch { claimed, derived } => write!(
                f,
                "ordinary class number claimed {claimed} but the criterion gives {derived}"
            ),
            RealCertificateError::NarrowClassNumberNotEven { narrow } => write!(
                f,
                "narrow class number {narrow} is odd but h = h+/2 was claimed"
            ),
            RealCertificateError::UnitNormDisagreesWithCycles { norm, shares_cycle } => write!(
                f,
                "fundamental unit norm {norm} disagrees with the cycle criterion \
                 (shares_cycle = {shares_cycle})"
            ),
            RealCertificateError::UnitCertificate(inner) => {
                write!(f, "fundamental unit certificate: {inner}")
            }
            RealCertificateError::UnitRadicandMismatch => {
                write!(f, "unit certificate is for a different radicand")
            }
            RealCertificateError::IdealNotAdmissible { class, reason } => {
                write!(f, "ideal class {class} carries a non-ideal: {reason}")
            }
            RealCertificateError::IdealNormMismatch { class } => {
                write!(f, "ideal class {class} carries an ideal of the wrong norm")
            }
            RealCertificateError::IdealClassesMismatch => {
                write!(f, "recorded ideal classes are not the ones the cycles give")
            }
            RealCertificateError::IdealClassMapMismatch => {
                write!(f, "recorded cycle-to-ideal-class map is wrong")
            }
            RealCertificateError::IdealClassCountMismatch {
                ideal_side,
                cycle_side,
            } => write!(
                f,
                "the ideal side counts {ideal_side} ordinary classes, the cycle side {cycle_side}"
            ),
            RealCertificateError::RegulatorMagnitudeOutOfRange => {
                write!(f, "the unit is past the i128 range of CasExpr::int")
            }
            RealCertificateError::RegulatorPrecisionMismatch { claimed, enclosure } => write!(
                f,
                "precision claimed {claimed} but the enclosure carries {enclosure}"
            ),
            RealCertificateError::RegulatorEnclosureRejected(message) => {
                write!(f, "enclosure rejected: {message}")
            }
            RealCertificateError::RegulatorMinimalityLabelMismatch { claimed, supported } => {
                write!(
                    f,
                    "fundamental_certified claimed {claimed} but the unit supports {supported}"
                )
            }
        }
    }
}

impl From<CertificateError> for RealCertificateError {
    fn from(value: CertificateError) -> RealCertificateError {
        RealCertificateError::UnitCertificate(value)
    }
}

/// Why a real-quadratic producer declined.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RealDecline {
    /// `D ≤ 0`.
    DiscriminantNotPositive,
    /// `D ≢ 0, 1 (mod 4)`.
    DiscriminantNotAdmissible,
    /// `D` is a perfect square.
    DiscriminantIsSquare,
    /// `D` is past [`REAL_DISCRIMINANT_BOUND`].
    DiscriminantTooLarge {
        /// The bound.
        bound: i64,
    },
    /// A value did not fit the `i128` range a reused routine needs.
    MagnitudeOutOfRange,
    /// The form handed to [`rho`] is not reduced, so `ρ` is not defined on it.
    FormNotReduced,
    /// A division that the theory says is exact was not.
    NonExactDivision,
    /// A cycle did not close within [`CYCLE_STEP_BOUND`] steps.
    CycleDidNotClose {
        /// The bound.
        bound: usize,
    },
    /// The fundamental-unit producer declined.
    Unit(UnitDecline),
    /// The requested precision is past [`REGULATOR_PRECISION_BOUND`].
    PrecisionTooLarge {
        /// The bound.
        bound: u32,
    },
    /// [`crate::enclosure::enclose`] declined.
    Enclosure(EncloseDecline),
}

impl fmt::Display for RealDecline {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RealDecline::DiscriminantNotPositive => write!(f, "discriminant is not positive"),
            RealDecline::DiscriminantNotAdmissible => {
                write!(f, "discriminant is not 0 or 1 mod 4")
            }
            RealDecline::DiscriminantIsSquare => write!(f, "discriminant is a square"),
            RealDecline::DiscriminantTooLarge { bound } => {
                write!(f, "discriminant is past the enumeration bound {bound}")
            }
            RealDecline::MagnitudeOutOfRange => write!(f, "value is past the i128 range"),
            RealDecline::FormNotReduced => write!(f, "rho needs a reduced form"),
            RealDecline::NonExactDivision => write!(f, "a division that must be exact was not"),
            RealDecline::CycleDidNotClose { bound } => {
                write!(f, "a cycle did not close within {bound} steps")
            }
            RealDecline::Unit(inner) => write!(f, "fundamental unit: {inner}"),
            RealDecline::PrecisionTooLarge { bound } => {
                write!(f, "precision is past the bound {bound}")
            }
            RealDecline::Enclosure(inner) => write!(f, "enclosure: {inner}"),
        }
    }
}

impl From<UnitDecline> for RealDecline {
    fn from(value: UnitDecline) -> RealDecline {
        RealDecline::Unit(value)
    }
}

impl From<EncloseDecline> for RealDecline {
    fn from(value: EncloseDecline) -> RealDecline {
        RealDecline::Enclosure(value)
    }
}

// ---------------------------------------------------------------------------
// Small exact helpers
// ---------------------------------------------------------------------------

/// `left / right`, refusing a non-exact division.
fn exact_div(left: &BigInt, right: &BigInt) -> Result<BigInt, RealDecline> {
    if right.is_zero() || !(left % right).is_zero() {
        return Err(RealDecline::NonExactDivision);
    }
    Ok(left / right)
}

/// `D > 0`, `D ≡ 0, 1 (mod 4)`, `D` not a square — the standing hypothesis of
/// everything in this module, as a producer-side check. Returns `⌊√D⌋`.
fn admissible_discriminant(discriminant: &BigInt) -> Result<BigInt, RealDecline> {
    if !discriminant.is_positive() {
        return Err(RealDecline::DiscriminantNotPositive);
    }
    let residue = big_mod_positive(discriminant, &BigInt::from(4));
    if !(residue.is_zero() || residue.is_one()) {
        return Err(RealDecline::DiscriminantNotAdmissible);
    }
    let root = big_isqrt(discriminant);
    if &root * &root == *discriminant {
        return Err(RealDecline::DiscriminantIsSquare);
    }
    Ok(root)
}

/// The same hypothesis, as a checker-side refusal.
fn admissible_discriminant_checked(discriminant: &BigInt) -> Result<BigInt, RealCertificateError> {
    // A1: D > 0.
    if !discriminant.is_positive() {
        return Err(RealCertificateError::DiscriminantNotPositive);
    }
    // A2: D ≡ 0 or 1 (mod 4).
    let residue = big_mod_positive(discriminant, &BigInt::from(4));
    if !(residue.is_zero() || residue.is_one()) {
        return Err(RealCertificateError::DiscriminantNotAdmissible);
    }
    // A3: D is not a square.
    let root = big_isqrt(discriminant);
    if &root * &root == *discriminant {
        return Err(RealCertificateError::DiscriminantIsSquare);
    }
    Ok(root)
}

// ---------------------------------------------------------------------------
// Reduced indefinite forms
// ---------------------------------------------------------------------------

/// Whether `form` is **Gauss-reduced** for the positive non-square
/// discriminant `discriminant`: `|√D − 2|a|| < b < √D`.
///
/// Every comparison is done over ℤ; see the module documentation for the
/// translation. This does **not** check that the form's own discriminant is
/// `discriminant` — callers that need that check it separately, so the two
/// failures stay distinguishable.
#[must_use]
pub fn is_reduced_indefinite(discriminant: &BigInt, form: &BinaryQuadraticForm) -> bool {
    let (a, b, c) = form.coefficients();
    if a.is_zero() || c.is_zero() || !b.is_positive() {
        return false;
    }
    // b < √D.
    if &(b * b) >= discriminant {
        return false;
    }
    let twice = 2u32 * a.abs();
    // √D < 2|a| + b.
    let upper = &twice + b;
    if discriminant >= &(&upper * &upper) {
        return false;
    }
    // 2|a| − b < √D.
    let lower = &twice - b;
    if lower.is_positive() && &(&lower * &lower) >= discriminant {
        return false;
    }
    true
}

/// The positive divisors of `value > 0`, ascending.
fn positive_divisors(value: i128) -> Vec<i128> {
    let mut small: Vec<i128> = Vec::new();
    let mut large: Vec<i128> = Vec::new();
    let mut step = 1i128;
    while step * step <= value {
        if value % step == 0 {
            small.push(step);
            let other = value / step;
            if other != step {
                large.push(other);
            }
        }
        step += 1;
    }
    large.reverse();
    small.extend(large);
    small
}

/// Every reduced primitive form of the positive non-square discriminant `D`,
/// in ascending `(a, b, c)` order.
///
/// The enumeration walks `b` of the parity of `D` with `b² < D`, sets
/// `m = (D − b²)/4 > 0`, and takes `a = ±e` for each positive divisor `e` of
/// `m` with `c = −m/a`, keeping the primitive ones that pass
/// [`is_reduced_indefinite`]. `a·c = −m` is exactly the discriminant condition,
/// so nothing reduced is missed.
///
/// # Errors
///
/// [`RealDecline::DiscriminantNotPositive`],
/// [`RealDecline::DiscriminantNotAdmissible`],
/// [`RealDecline::DiscriminantIsSquare`] for a `D` outside the hypothesis;
/// [`RealDecline::DiscriminantTooLarge`] past [`REAL_DISCRIMINANT_BOUND`]; and
/// [`RealDecline::MagnitudeOutOfRange`] if `D` will not fit `i128`.
pub fn reduced_indefinite_forms(
    discriminant: &BigInt,
) -> Result<Vec<BinaryQuadraticForm>, RealDecline> {
    admissible_discriminant(discriminant)?;
    if discriminant > &BigInt::from(REAL_DISCRIMINANT_BOUND) {
        return Err(RealDecline::DiscriminantTooLarge {
            bound: REAL_DISCRIMINANT_BOUND,
        });
    }
    let small = to_i128(discriminant).ok_or(RealDecline::MagnitudeOutOfRange)?;
    let mut forms: Vec<BinaryQuadraticForm> = Vec::new();
    let mut b = if small % 2 == 0 { 2i128 } else { 1i128 };
    while b * b < small {
        let numerator = small - b * b;
        if numerator % 4 != 0 {
            b += 2;
            continue;
        }
        let m = numerator / 4;
        for divisor in positive_divisors(m) {
            for sign in [1i128, -1i128] {
                let a = sign * divisor;
                let c = -m / a;
                let form =
                    BinaryQuadraticForm::new(BigInt::from(a), BigInt::from(b), BigInt::from(c));
                if !is_reduced_indefinite(discriminant, &form) {
                    continue;
                }
                if !form.is_primitive() {
                    continue;
                }
                forms.push(form);
            }
        }
        b += 2;
    }
    forms.sort();
    Ok(forms)
}

/// The reduction step `ρ(a, b, c) = (c, b', (b'² − D)/(4c))`.
///
/// `b'` is the unique integer congruent to `−b` modulo `2c` with
/// `√D − 2|c| < b' < √D`; with `r = ⌊√D⌋` that is `r − ((r + b) mod 2|c|)`.
/// `ρ` maps reduced forms to reduced forms and is a bijection on them.
///
/// # Errors
///
/// The discriminant declines of [`reduced_indefinite_forms`] (without the size
/// bound — `ρ` is `O(1)`), [`RealDecline::FormNotReduced`] when `form` is not
/// reduced for `discriminant` or does not have that discriminant, and
/// [`RealDecline::NonExactDivision`] if `4c` does not divide `b'² − D`.
pub fn rho(
    discriminant: &BigInt,
    form: &BinaryQuadraticForm,
) -> Result<BinaryQuadraticForm, RealDecline> {
    let root = admissible_discriminant(discriminant)?;
    if &form.discriminant() != discriminant || !is_reduced_indefinite(discriminant, form) {
        return Err(RealDecline::FormNotReduced);
    }
    let (_, b, c) = form.coefficients();
    let modulus = 2u32 * c.abs();
    let next_b = &root - big_mod_positive(&(&root + b), &modulus);
    let next_c = exact_div(&(&next_b * &next_b - discriminant), &(4u32 * c))?;
    Ok(BinaryQuadraticForm::new(c.clone(), next_b, next_c))
}

/// The cycles of reduced forms of a positive non-square discriminant.
///
/// Each cycle is one orbit of [`rho`], rotated so its `(a, b, c)`-least form is
/// first; the cycles are listed in ascending order of that first form. Both
/// choices are producer-fixed, so the output is deterministic.
///
/// `verify` re-derives everything: each form's discriminant, primitivity and
/// reducedness; that no form is listed twice; that `ρ` of each member is the
/// next member; and — with a traversal the producer never runs — that the union
/// of the cycles is exactly the reduced forms of `D`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FormCycleCertificate {
    /// The discriminant `D > 0`, non-square, `≡ 0` or `1 (mod 4)`.
    pub discriminant: BigInt,
    /// One entry per cycle.
    pub cycles: Vec<Vec<BinaryQuadraticForm>>,
    /// The narrow class number `h⁺(D)`, which is the number of cycles.
    pub narrow_class_number: usize,
}

impl FormCycleCertificate {
    /// `h⁺(D)`.
    #[must_use]
    pub fn narrow_class_number(&self) -> usize {
        self.narrow_class_number
    }

    /// The total number of reduced forms across all cycles.
    #[must_use]
    pub fn form_count(&self) -> usize {
        self.cycles.iter().map(Vec::len).sum()
    }

    /// Re-derive the whole partition from `D` alone.
    ///
    /// # Errors
    ///
    /// [`RealCertificateError::DiscriminantNotPositive`],
    /// [`RealCertificateError::DiscriminantNotAdmissible`] and
    /// [`RealCertificateError::DiscriminantIsSquare`] for a `D` outside the
    /// hypothesis; [`RealCertificateError::CycleEmpty`],
    /// [`RealCertificateError::FormDiscriminantMismatch`],
    /// [`RealCertificateError::FormNotPrimitive`],
    /// [`RealCertificateError::FormNotReduced`] and
    /// [`RealCertificateError::FormListedTwice`] naming the offending form;
    /// [`RealCertificateError::CycleNotClosed`] when `ρ` disagrees;
    /// [`RealCertificateError::CycleRecountMismatch`] when the independent
    /// enumeration disagrees; and
    /// [`RealCertificateError::NarrowClassNumberMismatch`].
    pub fn verify(&self) -> Result<(), RealCertificateError> {
        admissible_discriminant_checked(&self.discriminant)?;
        let mut seen: BTreeSet<BinaryQuadraticForm> = BTreeSet::new();
        for (cycle, forms) in self.cycles.iter().enumerate() {
            // F1: a cycle is an orbit, so it has at least one member.
            if forms.is_empty() {
                return Err(RealCertificateError::CycleEmpty { cycle });
            }
            for (index, form) in forms.iter().enumerate() {
                // F2: the form has the recorded discriminant.
                if form.discriminant() != self.discriminant {
                    return Err(RealCertificateError::FormDiscriminantMismatch { cycle, index });
                }
                // F3: primitive, or it is not a class of this discriminant.
                if !form.is_primitive() {
                    return Err(RealCertificateError::FormNotPrimitive { cycle, index });
                }
                // F4: reduced.
                if !is_reduced_indefinite(&self.discriminant, form) {
                    return Err(RealCertificateError::FormNotReduced { cycle, index });
                }
                // F5: no repeats anywhere, which is disjointness of the cycles
                // and non-repetition within one.
                if !seen.insert(form.clone()) {
                    return Err(RealCertificateError::FormListedTwice { cycle, index });
                }
            }
            // F6: closed under rho, recomputed here and compared cyclically.
            for index in 0..forms.len() {
                let next = rho(&self.discriminant, &forms[index])
                    .map_err(|_| RealCertificateError::CycleNotClosed { cycle, index })?;
                if next != forms[(index + 1) % forms.len()] {
                    return Err(RealCertificateError::CycleNotClosed { cycle, index });
                }
            }
        }
        // F7: the union is ALL of the reduced forms, by an enumeration the
        // producer's cycle walk never performs.
        let recount = reduced_indefinite_forms(&self.discriminant).map_err(|_| {
            RealCertificateError::CycleRecountMismatch {
                listed: seen.len(),
                recounted: 0,
            }
        })?;
        let recounted: BTreeSet<BinaryQuadraticForm> = recount.into_iter().collect();
        if recounted != seen {
            return Err(RealCertificateError::CycleRecountMismatch {
                listed: seen.len(),
                recounted: recounted.len(),
            });
        }
        // F8: the headline number is the cycle count.
        if self.narrow_class_number != self.cycles.len() {
            return Err(RealCertificateError::NarrowClassNumberMismatch {
                claimed: self.narrow_class_number,
                cycles: self.cycles.len(),
            });
        }
        Ok(())
    }
}

/// Partition the reduced forms of `D` into `ρ`-cycles.
///
/// # Errors
///
/// The declines of [`reduced_indefinite_forms`] and [`rho`], plus
/// [`RealDecline::CycleDidNotClose`] at [`CYCLE_STEP_BOUND`].
pub fn form_cycles(discriminant: &BigInt) -> Result<FormCycleCertificate, RealDecline> {
    let forms = reduced_indefinite_forms(discriminant)?;
    let all: BTreeSet<BinaryQuadraticForm> = forms.iter().cloned().collect();
    let mut seen: BTreeSet<BinaryQuadraticForm> = BTreeSet::new();
    let mut cycles: Vec<Vec<BinaryQuadraticForm>> = Vec::new();
    for start in &forms {
        if seen.contains(start) {
            continue;
        }
        let mut orbit: Vec<BinaryQuadraticForm> = Vec::new();
        let mut current = start.clone();
        let mut budget = CYCLE_STEP_BOUND;
        loop {
            if !all.contains(&current) || !seen.insert(current.clone()) {
                break;
            }
            orbit.push(current.clone());
            if budget == 0 {
                return Err(RealDecline::CycleDidNotClose {
                    bound: CYCLE_STEP_BOUND,
                });
            }
            budget -= 1;
            current = rho(discriminant, &current)?;
        }
        if &current != start {
            // rho is a bijection of the reduced forms, so an orbit that walks
            // into an already-seen form other than its own start is impossible;
            // refuse rather than emit a partition that is not one.
            return Err(RealDecline::CycleDidNotClose {
                bound: CYCLE_STEP_BOUND,
            });
        }
        // Rotate so the least form leads, so the output does not depend on
        // which member the outer loop reached first.
        if let Some(pivot) = orbit
            .iter()
            .enumerate()
            .min_by(|left, right| left.1.cmp(right.1))
            .map(|(index, _)| index)
        {
            orbit.rotate_left(pivot);
        }
        cycles.push(orbit);
    }
    cycles.sort();
    let narrow_class_number = cycles.len();
    Ok(FormCycleCertificate {
        discriminant: discriminant.clone(),
        cycles,
        narrow_class_number,
    })
}

// ---------------------------------------------------------------------------
// Narrow versus ordinary, and the ideal-side recount
// ---------------------------------------------------------------------------

/// The unique integer `b*` of the parity of `D` with `√D − 2 < b* < √D`, and
/// the `c*` that makes `(1, b*, c*)` a form of discriminant `D`.
fn principal_reduced_pair(
    discriminant: &BigInt,
    root: &BigInt,
) -> Result<(BigInt, BigInt), RealDecline> {
    // The window `(√D − 2, √D)` is open, of length 2, with irrational
    // endpoints, so it holds exactly one integer of each parity. `r = ⌊√D⌋` is
    // the larger of the two; step down by one when its parity is wrong.
    let parity = big_mod_positive(discriminant, &BigInt::from(2));
    let mut b = root.clone();
    if big_mod_positive(&b, &BigInt::from(2)) != parity {
        b -= big_one();
    }
    let c = exact_div(&(&b * &b - discriminant), &BigInt::from(4))?;
    Ok((b, c))
}

/// `I = ℤ·|a| + ℤ·(B + ω)` with `B = −(b + t)/2 mod |a|`, the ideal of a
/// reduced indefinite form.
///
/// The sign of `a` is dropped on purpose: the ℤ-module does not see it, and
/// forgetting it is exactly the map `Cl⁺(D) → Cl(D)`.
fn ideal_of_indefinite_form(
    order: &QuadraticOrder,
    form: &BinaryQuadraticForm,
) -> Result<Ideal, RealDecline> {
    let (a, b, _) = form.coefficients();
    let leading = a.abs();
    if leading.is_zero() {
        return Err(RealDecline::NonExactDivision);
    }
    let half = exact_div(&(b + order.omega_trace()), &BigInt::from(2))?;
    let offset = big_mod_positive(&(-half), &leading);
    Ok(Ideal::from_hermite(leading, offset, big_one()))
}

/// The distinct ideal sets a cycle partition produces, ascending, together with
/// the per-cycle index into them.
fn ideal_sides(
    order: &QuadraticOrder,
    cycles: &[Vec<BinaryQuadraticForm>],
) -> Result<(Vec<BTreeSet<Ideal>>, Vec<usize>), RealDecline> {
    let mut sets: Vec<BTreeSet<Ideal>> = Vec::with_capacity(cycles.len());
    for cycle in cycles {
        let mut set: BTreeSet<Ideal> = BTreeSet::new();
        for form in cycle {
            set.insert(ideal_of_indefinite_form(order, form)?);
        }
        sets.push(set);
    }
    let mut ordered = sets.clone();
    ordered.sort();
    ordered.dedup();
    let mut map: Vec<usize> = Vec::with_capacity(sets.len());
    for set in &sets {
        let index = ordered
            .iter()
            .position(|other| other == set)
            .ok_or(RealDecline::NonExactDivision)?;
        map.push(index);
    }
    Ok((ordered, map))
}

/// The narrow and ordinary class numbers of a real quadratic order, with all
/// three routes recorded.
///
/// See the module documentation for what the three routes are and why they are
/// independent. `verify` re-derives every one of them and refuses on any
/// disagreement.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RealClassNumberCertificate {
    /// The squarefree `d` of `K = ℚ(√d)`.
    pub radicand: BigInt,
    /// `D = disc(O_K)`.
    pub discriminant: BigInt,
    /// The cycle partition, with its own certificate.
    pub cycles: FormCycleCertificate,
    /// The fundamental unit of `ℤ[√d]`, with its own certificate.
    pub unit: FundamentalUnitCertificate,
    /// Index into `cycles.cycles` of the cycle containing `(1, b*, c*)`.
    pub principal_cycle: usize,
    /// Index into `cycles.cycles` of the cycle containing `(−1, b*, −c*)`.
    pub negative_principal_cycle: usize,
    /// The distinct sets of primitive ideals the cycles produce, each sorted,
    /// the outer list sorted.
    pub ideal_classes: Vec<Vec<Ideal>>,
    /// For each cycle, the index into `ideal_classes` of its ideal set.
    pub cycle_ideal_class: Vec<usize>,
    /// `h⁺(D)`.
    pub narrow_class_number: usize,
    /// `h(D)`.
    pub class_number: usize,
}

impl RealClassNumberCertificate {
    /// `h(D)`.
    #[must_use]
    pub fn class_number(&self) -> usize {
        self.class_number
    }

    /// `h⁺(D)`.
    #[must_use]
    pub fn narrow_class_number(&self) -> usize {
        self.narrow_class_number
    }

    /// Whether the fundamental unit has norm `−1`, which is equivalent to
    /// `h = h⁺`.
    #[must_use]
    pub fn unit_norm_is_negative(&self) -> bool {
        self.unit.norm.is_negative()
    }

    /// Re-derive everything from `d` alone.
    ///
    /// # Errors
    ///
    /// Everything [`FormCycleCertificate::verify`] can refuse, plus
    /// [`RealCertificateError::OrderParametersMismatch`],
    /// [`RealCertificateError::DiscriminantMismatch`],
    /// [`RealCertificateError::UnitCertificate`],
    /// [`RealCertificateError::UnitRadicandMismatch`],
    /// [`RealCertificateError::PrincipalCycleMismatch`],
    /// [`RealCertificateError::NarrowClassNumberNotEven`],
    /// [`RealCertificateError::OrdinaryClassNumberMismatch`],
    /// [`RealCertificateError::UnitNormDisagreesWithCycles`],
    /// [`RealCertificateError::IdealNotAdmissible`],
    /// [`RealCertificateError::IdealNormMismatch`],
    /// [`RealCertificateError::IdealClassesMismatch`],
    /// [`RealCertificateError::IdealClassMapMismatch`] and
    /// [`RealCertificateError::IdealClassCountMismatch`].
    #[allow(clippy::too_many_lines)]
    pub fn verify(&self) -> Result<(), RealCertificateError> {
        // N1: the cycles stand on their own.
        self.cycles.verify()?;
        // N2: the order is the one the radicand determines, and D is its
        // discriminant.
        let order = QuadraticOrder::new(&self.radicand)
            .map_err(|_| RealCertificateError::OrderParametersMismatch)?;
        if order.discriminant() != &self.discriminant
            || self.cycles.discriminant != self.discriminant
        {
            return Err(RealCertificateError::DiscriminantMismatch);
        }
        // N3: the unit certificate stands on its own, and is for this field.
        self.unit.verify()?;
        if self.unit.radicand != self.radicand {
            return Err(RealCertificateError::UnitRadicandMismatch);
        }
        // N4: locate the principal form and its negative, both recomputed from
        // D rather than read from the certificate.
        let root = admissible_discriminant_checked(&self.discriminant)?;
        let (star_b, star_c) = principal_reduced_pair(&self.discriminant, &root)
            .map_err(|_| RealCertificateError::PrincipalCycleMismatch)?;
        let principal = BinaryQuadraticForm::new(big_one(), star_b.clone(), star_c.clone());
        let negative = BinaryQuadraticForm::new(-big_one(), star_b, -star_c);
        let locate = |target: &BinaryQuadraticForm| -> Option<usize> {
            self.cycles
                .cycles
                .iter()
                .position(|cycle| cycle.contains(target))
        };
        let found_principal =
            locate(&principal).ok_or(RealCertificateError::PrincipalCycleMismatch)?;
        let found_negative =
            locate(&negative).ok_or(RealCertificateError::PrincipalCycleMismatch)?;
        if found_principal != self.principal_cycle
            || found_negative != self.negative_principal_cycle
        {
            return Err(RealCertificateError::PrincipalCycleMismatch);
        }
        // N5: h+ is the cycle count and matches the top-level field.
        if self.narrow_class_number != self.cycles.cycles.len() {
            return Err(RealCertificateError::NarrowClassNumberMismatch {
                claimed: self.narrow_class_number,
                cycles: self.cycles.cycles.len(),
            });
        }
        // N6: h follows from the criterion.
        let shares_cycle = found_principal == found_negative;
        let derived = if shares_cycle {
            self.narrow_class_number
        } else {
            if self.narrow_class_number % 2 != 0 {
                return Err(RealCertificateError::NarrowClassNumberNotEven {
                    narrow: self.narrow_class_number,
                });
            }
            self.narrow_class_number / 2
        };
        if derived != self.class_number {
            return Err(RealCertificateError::OrdinaryClassNumberMismatch {
                claimed: self.class_number,
                derived,
            });
        }
        // N7: cross-check one — the unit's norm must agree with the criterion.
        if self.unit.norm.is_negative() != shares_cycle {
            return Err(RealCertificateError::UnitNormDisagreesWithCycles {
                norm: self.unit.norm.clone(),
                shares_cycle,
            });
        }
        // N8: cross-check two — the ideal side, recomputed from the cycles.
        let (ordered, expected_map) = ideal_sides(&order, &self.cycles.cycles)
            .map_err(|_| RealCertificateError::IdealClassesMismatch)?;
        // N9: every ideal really is one, with the norm its form says.
        for (class, set) in ordered.iter().enumerate() {
            for ideal in set {
                ideal
                    .admissible_in(&order)
                    .map_err(|reason| RealCertificateError::IdealNotAdmissible { class, reason })?;
                if ideal.norm() != *ideal.leading() {
                    return Err(RealCertificateError::IdealNormMismatch { class });
                }
            }
        }
        // N10: the recorded classes are those sets.
        let recorded: Vec<BTreeSet<Ideal>> = self
            .ideal_classes
            .iter()
            .map(|class| class.iter().cloned().collect())
            .collect();
        if recorded != ordered {
            return Err(RealCertificateError::IdealClassesMismatch);
        }
        // N11: and the recorded map is the one the ideals give.
        if expected_map != self.cycle_ideal_class {
            return Err(RealCertificateError::IdealClassMapMismatch);
        }
        // N12: the ideal-side count of ordinary classes is the cycle side's.
        if ordered.len() != self.class_number {
            return Err(RealCertificateError::IdealClassCountMismatch {
                ideal_side: ordered.len(),
                cycle_side: self.class_number,
            });
        }
        Ok(())
    }
}

/// `h⁺(D)` and `h(D)` for the maximal order of a real quadratic field.
///
/// # Errors
///
/// The declines of [`form_cycles`] and of
/// [`QuadraticField::fundamental_unit`], plus
/// [`RealDecline::DiscriminantNotPositive`] when the order is imaginary and
/// [`RealDecline::FormNotReduced`] if the principal form is somehow not among
/// the reduced ones.
pub fn real_class_number(order: &QuadraticOrder) -> Result<RealClassNumberCertificate, RealDecline> {
    let discriminant = order.discriminant().clone();
    let root = admissible_discriminant(&discriminant)?;
    let cycles = form_cycles(&discriminant)?;
    let field =
        QuadraticField::new(order.radicand()).map_err(|_| RealDecline::MagnitudeOutOfRange)?;
    let unit = field.fundamental_unit()?;
    let (star_b, star_c) = principal_reduced_pair(&discriminant, &root)?;
    let principal = BinaryQuadraticForm::new(big_one(), star_b.clone(), star_c.clone());
    let negative = BinaryQuadraticForm::new(-big_one(), star_b, -star_c);
    let locate = |target: &BinaryQuadraticForm| {
        cycles
            .cycles
            .iter()
            .position(|cycle| cycle.contains(target))
            .ok_or(RealDecline::FormNotReduced)
    };
    let principal_cycle = locate(&principal)?;
    let negative_principal_cycle = locate(&negative)?;
    let (ordered, cycle_ideal_class) = ideal_sides(order, &cycles.cycles)?;
    let narrow_class_number = cycles.narrow_class_number;
    let class_number = if principal_cycle == negative_principal_cycle {
        narrow_class_number
    } else {
        narrow_class_number / 2
    };
    Ok(RealClassNumberCertificate {
        radicand: order.radicand().clone(),
        discriminant,
        cycles,
        unit,
        principal_cycle,
        negative_principal_cycle,
        ideal_classes: ordered
            .into_iter()
            .map(|set| set.into_iter().collect())
            .collect(),
        cycle_ideal_class,
        narrow_class_number,
        class_number,
    })
}

impl QuadraticOrder {
    /// [`real_class_number`] on this order.
    ///
    /// # Errors
    ///
    /// See [`real_class_number`].
    pub fn real_class_number(&self) -> Result<RealClassNumberCertificate, RealDecline> {
        real_class_number(self)
    }
}

// ---------------------------------------------------------------------------
// The regulator
// ---------------------------------------------------------------------------

/// `ln(a + b·√d)` as a [`CasExpr`], or `None` when a coefficient is past the
/// `i128` range of [`CasExpr::int`].
fn regulator_expression(radicand: &BigInt, a: &BigInt, b: &BigInt) -> Option<CasExpr> {
    let d = to_i128(radicand)?;
    let a = to_i128(a)?;
    let b = to_i128(b)?;
    let root = CasExpr::int(d).sqrt();
    let scaled = CasExpr::Mul(vec![CasExpr::int(b), root]);
    Some(CasExpr::Add(vec![CasExpr::int(a), scaled]).ln())
}

/// `R = ln ε` for a certified fundamental unit, as a rational enclosure.
///
/// The certificate carries no float and no decimal rendering: the answer is the
/// [`Enclosure`]'s interval of exact rational endpoints, of width at most
/// `2^(−precision)`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RegulatorCertificate {
    /// The squarefree `d`.
    pub radicand: BigInt,
    /// The unit whose logarithm this is.
    pub unit: FundamentalUnitCertificate,
    /// The requested precision: the width bound is `2^(−precision)`.
    pub precision: u32,
    /// The enclosure of `ln(a + b√d)` with its per-step evidence.
    pub enclosure: Enclosure,
    /// Whether the unit's *fundamental* claim was proved (not merely labelled),
    /// and hence whether this is `R` rather than `k·R` for an unknown `k ≥ 1`.
    pub fundamental_certified: bool,
}

impl RegulatorCertificate {
    /// The enclosing interval.
    #[must_use]
    pub fn interval(&self) -> &BigInterval {
        &self.enclosure.interval
    }

    /// The expression `ln(a + b√d)` this certificate is about, rebuilt from
    /// `(d, a, b)`. `None` when a coefficient is past `i128`.
    #[must_use]
    pub fn expression(&self) -> Option<CasExpr> {
        regulator_expression(&self.radicand, &self.unit.a, &self.unit.b)
    }

    /// Re-derive the unit, rebuild the expression from `(d, a, b)`, and re-run
    /// the enclosure's evidence against it.
    ///
    /// # Errors
    ///
    /// [`RealCertificateError::UnitCertificate`] when the unit does not stand
    /// up; [`RealCertificateError::UnitRadicandMismatch`] when the unit is for
    /// a different field;
    /// [`RealCertificateError::RegulatorMagnitudeOutOfRange`];
    /// [`RealCertificateError::RegulatorPrecisionMismatch`];
    /// [`RealCertificateError::RegulatorEnclosureRejected`]; and
    /// [`RealCertificateError::RegulatorMinimalityLabelMismatch`].
    pub fn verify(&self) -> Result<(), RealCertificateError> {
        // G1: the unit stands on its own — the norm is recomputed and, when the
        // certificate claims one, the minimality search is re-run.
        self.unit.verify()?;
        // G2: and it is a unit of THIS field.
        if self.unit.radicand != self.radicand {
            return Err(RealCertificateError::UnitRadicandMismatch);
        }
        // G3: the subject is rebuilt from (d, a, b), never read from the
        // certificate, so an enclosure of some other number cannot be pasted
        // in.
        let expr = self
            .expression()
            .ok_or(RealCertificateError::RegulatorMagnitudeOutOfRange)?;
        // G4: the claimed precision is the enclosure's own, so the width bound
        // the verifier enforces is the one the certificate advertises.
        if self.precision != self.enclosure.precision {
            return Err(RealCertificateError::RegulatorPrecisionMismatch {
                claimed: self.precision,
                enclosure: self.enclosure.precision,
            });
        }
        self.enclosure
            .verify(&expr, &[])
            .map_err(RealCertificateError::RegulatorEnclosureRejected)?;
        // G5: "this is THE regulator" is only true when the unit's minimality
        // was proved; the label may not outrun the unit certificate.
        let supported = matches!(self.unit.minimality, Minimality::ExhaustiveBelow { .. });
        if self.fundamental_certified != supported {
            return Err(RealCertificateError::RegulatorMinimalityLabelMismatch {
                claimed: self.fundamental_certified,
                supported,
            });
        }
        Ok(())
    }
}

/// `R = ln ε` for an already-certified unit.
///
/// # Errors
///
/// [`RealDecline::PrecisionTooLarge`] past [`REGULATOR_PRECISION_BOUND`],
/// [`RealDecline::MagnitudeOutOfRange`] when the unit is past the `i128` range
/// of [`CasExpr::int`], and [`RealDecline::Enclosure`] when
/// [`crate::enclosure::enclose`] declines.
pub fn regulator_of_unit(
    unit: &FundamentalUnitCertificate,
    precision: u32,
) -> Result<RegulatorCertificate, RealDecline> {
    if precision > REGULATOR_PRECISION_BOUND {
        return Err(RealDecline::PrecisionTooLarge {
            bound: REGULATOR_PRECISION_BOUND,
        });
    }
    let expr = regulator_expression(&unit.radicand, &unit.a, &unit.b)
        .ok_or(RealDecline::MagnitudeOutOfRange)?;
    let enclosure = enclose_with_reason(&expr, &[], precision)?;
    Ok(RegulatorCertificate {
        radicand: unit.radicand.clone(),
        unit: unit.clone(),
        precision,
        enclosure,
        fundamental_certified: matches!(unit.minimality, Minimality::ExhaustiveBelow { .. }),
    })
}

/// `R = ln ε` for the fundamental unit of `ℤ[√d]`.
///
/// # Errors
///
/// The declines of [`QuadraticField::fundamental_unit`] and of
/// [`regulator_of_unit`].
pub fn regulator(
    field: &QuadraticField,
    precision: u32,
) -> Result<RegulatorCertificate, RealDecline> {
    let unit = field.fundamental_unit()?;
    regulator_of_unit(&unit, precision)
}

/// `ln` of the fundamental solution of `x² − d·y² = 1`, which is `R` when the
/// fundamental unit has norm `+1` and `2R` when it has norm `−1`.
///
/// The `fundamental_certified` flag on the result is always `false`: see
/// [`QuadraticField::pell_unit`] for why minimality is not certified there.
///
/// # Errors
///
/// The declines of [`QuadraticField::pell_unit`] and of
/// [`regulator_of_unit`].
pub fn pell_regulator(
    field: &QuadraticField,
    precision: u32,
) -> Result<RegulatorCertificate, RealDecline> {
    let unit = field.pell_unit()?;
    regulator_of_unit(&unit, precision)
}
