//! The **characterization of `Int`**.
//!
//! Ordered-ring laws alone do not pin `ℤ`: `ℚ` and `ℝ` satisfy every one of
//! them, and the lexicographically ordered `ℤ[x]` satisfies them *and* is
//! discretely ordered. What the constructed `Int` additionally has, and what is
//! declared here, is:
//!
//! * **no junk** — every element is `Int.ofNat n` or `Int.negSucc n`
//!   ([`IntCharacterization::cases`]), equivalently `±` a natural number
//!   ([`IntCharacterization::of_nat_or_neg`]);
//! * **generation by `1`** — the `+1` / `−1` induction principle
//!   ([`IntCharacterization::induction`]), which is what `ℤ[x]` fails;
//! * **discreteness** — nothing strictly between `0` and `1`
//!   ([`IntCharacterization::discrete`]), which is what `ℚ` fails;
//! * **totality** of the order and **non-triviality** (`0 ≠ 1`);
//! * the **uniqueness half of the universal property**
//!   ([`IntCharacterization::rec_unique`]): two maps out of `Int` that agree at
//!   `0` and satisfy the same `+1` and `−1` recurrences are equal.
//!
//! The other half — the *existence* of a map `Int → R` out of an arbitrary
//! target and the categoricity theorem that follows from it — is in
//! [`super::int_categoricity`], which declares into this same namespace.

// Proof scripts are long, straight-line term constructions over short
// mathematical names; splitting them would obscure the derivation they mirror,
// and the near-identical binder names (`hzs`/`hsi`, `f_up`/`g_up`) are the
// statement's own vocabulary.
#![allow(
    clippy::many_single_char_names,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::type_complexity
)]

use crate::KernelError;
use crate::expr::ExprId;
use crate::name::NameId;
use crate::nat_prelude::NatOps;

use super::Weakening;
use super::ops::CharDev;

/// The interned names of the `Int.Characterization` package.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct IntCharacterization {
    /// The `Int.Characterization` namespace root.
    pub root: NameId,
    /// The universe parameter `u` shared by the carrier-generic declarations.
    pub uparam: NameId,
    /// `∀ (P : Int → Prop), (∀ n, P (ofNat n)) → (∀ n, P (negSucc n)) → ∀ t, P t`
    /// — no junk: every integer comes from a constructor.
    pub cases: NameId,
    /// `∀ t, Or (∃ n, t = ofNat n) (∃ n, t = neg (ofNat n))` — every integer is
    /// `±` a natural number.
    pub of_nat_or_neg: NameId,
    /// `∀ (P : Int → Prop), P 0 → (∀ t, P t → P (t+1)) → (∀ t, P t → P (t−1)) → ∀ t, P t`
    /// — `Int` is generated by `0` under `+1` and `−1`.
    pub induction: NameId,
    /// The uniqueness half of the universal property.
    pub rec_unique: NameId,
    /// `∀ t, Not (And (0 < t) (t < 1))` — discreteness at the origin.
    pub discrete: NameId,
    /// `∀ a t, Not (And (a < t) (t < a+1))` — discreteness **everywhere**,
    /// derived from [`Self::discrete`] by translating through `−a`.
    pub discrete_everywhere: NameId,
    /// `∀ a b, Or (a ≤ b) (b ≤ a)` — the order is total.
    pub le_total: NameId,
    /// `0 < 1`.
    pub zero_lt_one: NameId,
    /// `Not (Eq Int 0 1)` — non-triviality.
    pub zero_ne_one: NameId,
}

/// `Int.add a b`.
pub(super) fn iadd(dev: &mut CharDev<'_>, a: ExprId, b: ExprId) -> ExprId {
    let name = dev.int_prelude().add;
    dev.const_app(name, &[a, b])
}

/// `Int.neg a`.
pub(super) fn ineg(dev: &mut CharDev<'_>, a: ExprId) -> ExprId {
    let name = dev.int_prelude().neg;
    dev.const_app(name, &[a])
}

/// `Int.ofNat n`.
pub(super) fn of_nat(dev: &mut CharDev<'_>, n: ExprId) -> ExprId {
    let name = dev.int_prelude().of_nat;
    dev.const_app(name, &[n])
}

/// `Int.negSucc n`.
pub(super) fn neg_succ(dev: &mut CharDev<'_>, n: ExprId) -> ExprId {
    let name = dev.int_prelude().neg_succ;
    dev.const_app(name, &[n])
}

/// `Int.zero`.
pub(super) fn izero(dev: &mut CharDev<'_>) -> ExprId {
    let name = dev.int_prelude().zero;
    dev.kernel().const_(name, vec![])
}

/// `Int.one`.
pub(super) fn ione(dev: &mut CharDev<'_>) -> ExprId {
    let name = dev.int_prelude().one;
    dev.kernel().const_(name, vec![])
}

/// The successor `t + 1`.
pub(super) fn plus_one(dev: &mut CharDev<'_>, t: ExprId) -> ExprId {
    let one = ione(dev);
    iadd(dev, t, one)
}

/// The predecessor `t + (−1)`.
pub(super) fn minus_one(dev: &mut CharDev<'_>, t: ExprId) -> ExprId {
    let one = ione(dev);
    let negated = ineg(dev, one);
    iadd(dev, t, negated)
}

/// Declare the whole `Int.Characterization` package.
///
/// # Errors
///
/// Returns the trusted gate's rejection. Every `Err` here means the kernel
/// **refused** one of the characterization proofs.
#[allow(clippy::too_many_lines)]
pub(super) fn declare(
    dev: &mut CharDev<'_>,
    weaken: Weakening,
) -> Result<IntCharacterization, KernelError> {
    let anon = dev.anon_name();
    let int_name = dev.int_prelude().z;
    let root = dev.kernel().name_str(int_name, "Characterization");
    let names = IntCharacterization {
        root,
        uparam: dev.kernel().name_str(anon, "u"),
        cases: dev.kernel().name_str(root, "cases"),
        of_nat_or_neg: dev.kernel().name_str(root, "of_nat_or_neg"),
        induction: dev.kernel().name_str(root, "induction"),
        rec_unique: dev.kernel().name_str(root, "rec_unique"),
        discrete: dev.kernel().name_str(root, "discrete"),
        discrete_everywhere: dev.kernel().name_str(root, "discrete_everywhere"),
        le_total: dev.kernel().name_str(root, "le_total"),
        zero_lt_one: dev.kernel().name_str(root, "zero_lt_one"),
        zero_ne_one: dev.kernel().name_str(root, "zero_ne_one"),
    };

    let nat = dev.nat_ty();
    let int_ty = dev.int_ty();
    let prop = dev.prop_ty();
    let one_lvl = dev.level_one();
    let zero_lvl = dev.level_zero();
    let u_lvl = dev.level_of(names.uparam);
    let sort_u = dev.sort_at(u_lvl);
    let int_rec_name = dev.int_prelude().rec;
    let nat_rec_name = dev.prelude().rec;
    let true_ty = dev.true_ty();

    // ---- no junk: exhaustive constructor case analysis ----------------------
    {
        let p_ty = dev.arrow(int_ty, prop);
        let p_fv = dev.fresh_fvar();
        let p = dev.kernel().fvar(p_fv);
        let of_nat_ty = {
            let n_fv = dev.fresh_fvar();
            let n = dev.kernel().fvar(n_fv);
            let value = of_nat(dev, n);
            let body = dev.apply(p, &[value]);
            dev.pi_fv(n_fv, nat, body)
        };
        let neg_succ_ty = {
            let n_fv = dev.fresh_fvar();
            let n = dev.kernel().fvar(n_fv);
            let value = neg_succ(dev, n);
            let body = dev.apply(p, &[value]);
            dev.pi_fv(n_fv, nat, body)
        };
        let of_nat_fv = dev.fresh_fvar();
        let of_nat_case = dev.kernel().fvar(of_nat_fv);
        let neg_succ_fv = dev.fresh_fvar();
        let neg_succ_case = dev.kernel().fvar(neg_succ_fv);
        let t_fv = dev.fresh_fvar();
        let t = dev.kernel().fvar(t_fv);
        let binders = [
            (p_fv, p_ty),
            (of_nat_fv, of_nat_ty),
            (neg_succ_fv, neg_succ_ty),
            (t_fv, int_ty),
        ];
        let conclusion = dev.apply(p, &[t]);
        let statement = dev.close_pi(&binders, conclusion);
        let rec = dev.kernel().const_(int_rec_name, vec![zero_lvl]);
        let body = dev.apply(rec, &[p, of_nat_case, neg_succ_case, t]);
        let value = dev.close_lam(&binders, body);
        dev.declare_theorem_u(names.cases, vec![], statement, value)?;
    }

    // ---- every integer is + or - a natural ----------------------------------
    {
        // `fun t => Or (∃ n, t = ofNat n) (∃ n, t = neg (ofNat n))`
        let disjunction = |d: &mut CharDev<'_>, t: ExprId| {
            let positive = {
                let n_fv = d.fresh_fvar();
                let n = d.kernel().fvar(n_fv);
                let value = of_nat(d, n);
                let equation = d.eq_at(one_lvl, int_ty, t, value);
                let predicate = d.lam_fv(n_fv, nat, equation);
                d.exists_at(one_lvl, nat, predicate)
            };
            let negative = {
                let n_fv = d.fresh_fvar();
                let n = d.kernel().fvar(n_fv);
                let value = of_nat(d, n);
                let value = ineg(d, value);
                let equation = d.eq_at(one_lvl, int_ty, t, value);
                let predicate = d.lam_fv(n_fv, nat, equation);
                d.exists_at(one_lvl, nat, predicate)
            };
            (positive, negative)
        };
        let positive_predicate = |d: &mut CharDev<'_>, t: ExprId| {
            let n_fv = d.fresh_fvar();
            let n = d.kernel().fvar(n_fv);
            let value = of_nat(d, n);
            let equation = d.eq_at(one_lvl, int_ty, t, value);
            d.lam_fv(n_fv, nat, equation)
        };
        let negative_predicate = |d: &mut CharDev<'_>, t: ExprId| {
            let n_fv = d.fresh_fvar();
            let n = d.kernel().fvar(n_fv);
            let value = of_nat(d, n);
            let value = ineg(d, value);
            let equation = d.eq_at(one_lvl, int_ty, t, value);
            d.lam_fv(n_fv, nat, equation)
        };

        let t_fv = dev.fresh_fvar();
        let t = dev.kernel().fvar(t_fv);
        let (positive, negative) = disjunction(dev, t);
        let conclusion = dev.or_of(positive, negative);
        let statement = dev.pi_fv(t_fv, int_ty, conclusion);

        let motive = {
            let x_fv = dev.fresh_fvar();
            let x = dev.kernel().fvar(x_fv);
            let (positive, negative) = disjunction(dev, x);
            let body = dev.or_of(positive, negative);
            dev.lam_fv(x_fv, int_ty, body)
        };
        let of_nat_case = {
            let n_fv = dev.fresh_fvar();
            let n = dev.kernel().fvar(n_fv);
            let value = of_nat(dev, n);
            let (positive, negative) = disjunction(dev, value);
            let predicate = positive_predicate(dev, value);
            let witness = dev.refl_at(one_lvl, int_ty, value);
            let existential = dev.exists_intro_at(one_lvl, nat, predicate, n, witness);
            let body = dev.or_inl(positive, negative, existential);
            dev.lam_fv(n_fv, nat, body)
        };
        let neg_succ_case = {
            let n_fv = dev.fresh_fvar();
            let n = dev.kernel().fvar(n_fv);
            let value = neg_succ(dev, n);
            let (positive, negative) = disjunction(dev, value);
            let predicate = negative_predicate(dev, value);
            // `neg (ofNat (succ n))` ι-reduces to `negSucc n`, so reflexivity
            // is the whole proof.
            let succ_n = dev.succ(n);
            let witness = dev.refl_at(one_lvl, int_ty, value);
            let existential = dev.exists_intro_at(one_lvl, nat, predicate, succ_n, witness);
            let body = dev.or_inr(positive, negative, existential);
            dev.lam_fv(n_fv, nat, body)
        };
        let rec = dev.kernel().const_(int_rec_name, vec![zero_lvl]);
        let body = dev.apply(rec, &[motive, of_nat_case, neg_succ_case, t]);
        let value = dev.lam_fv(t_fv, int_ty, body);
        dev.declare_theorem_u(names.of_nat_or_neg, vec![], statement, value)?;
    }

    // ---- generation by 1: the +1 / -1 induction principle -------------------
    //
    // Both steps are definitional: `ofNat n + 1` reduces to `ofNat (succ n)`,
    // `0 + (-1)` to `negSucc 0`, and `negSucc n + (-1)` to `negSucc (succ n)`,
    // so each branch is `Nat.rec` applied to the hypotheses with no rewriting.
    {
        let p_ty = dev.arrow(int_ty, prop);
        let p_fv = dev.fresh_fvar();
        let p = dev.kernel().fvar(p_fv);
        let zero = izero(dev);
        let base_ty = dev.apply(p, &[zero]);
        let successor_ty = {
            let t_fv = dev.fresh_fvar();
            let t = dev.kernel().fvar(t_fv);
            let p_t = dev.apply(p, &[t]);
            let next = plus_one(dev, t);
            let p_next = dev.apply(p, &[next]);
            let body = dev.arrow(p_t, p_next);
            dev.pi_fv(t_fv, int_ty, body)
        };
        let predecessor_ty = {
            let t_fv = dev.fresh_fvar();
            let t = dev.kernel().fvar(t_fv);
            let p_t = dev.apply(p, &[t]);
            let previous = minus_one(dev, t);
            let p_previous = dev.apply(p, &[previous]);
            let body = dev.arrow(p_t, p_previous);
            dev.pi_fv(t_fv, int_ty, body)
        };
        let successor_ty = if weaken == Weakening::IntInductionDropSuccStep {
            true_ty
        } else {
            successor_ty
        };
        let predecessor_ty = if weaken == Weakening::IntInductionDropPredStep {
            true_ty
        } else {
            predecessor_ty
        };
        let base_fv = dev.fresh_fvar();
        let base = dev.kernel().fvar(base_fv);
        let successor_fv = dev.fresh_fvar();
        let successor = dev.kernel().fvar(successor_fv);
        let predecessor_fv = dev.fresh_fvar();
        let predecessor = dev.kernel().fvar(predecessor_fv);
        let t_fv = dev.fresh_fvar();
        let t = dev.kernel().fvar(t_fv);
        let binders = [
            (p_fv, p_ty),
            (base_fv, base_ty),
            (successor_fv, successor_ty),
            (predecessor_fv, predecessor_ty),
            (t_fv, int_ty),
        ];
        let conclusion = dev.apply(p, &[t]);
        let statement = dev.close_pi(&binders, conclusion);

        let of_nat_branch = {
            let n_fv = dev.fresh_fvar();
            let n = dev.kernel().fvar(n_fv);
            let motive = {
                let k_fv = dev.fresh_fvar();
                let k = dev.kernel().fvar(k_fv);
                let value = of_nat(dev, k);
                let body = dev.apply(p, &[value]);
                dev.lam_fv(k_fv, nat, body)
            };
            let step = {
                let k_fv = dev.fresh_fvar();
                let k = dev.kernel().fvar(k_fv);
                let value = of_nat(dev, k);
                let ih_ty = dev.apply(p, &[value]);
                let ih_fv = dev.fresh_fvar();
                let ih = dev.kernel().fvar(ih_fv);
                let body = dev.apply(successor, &[value, ih]);
                let inner = dev.lam_fv(ih_fv, ih_ty, body);
                dev.lam_fv(k_fv, nat, inner)
            };
            let rec = dev.kernel().const_(nat_rec_name, vec![zero_lvl]);
            let body = dev.apply(rec, &[motive, base, step, n]);
            dev.lam_fv(n_fv, nat, body)
        };
        let neg_succ_branch = {
            let n_fv = dev.fresh_fvar();
            let n = dev.kernel().fvar(n_fv);
            let motive = {
                let k_fv = dev.fresh_fvar();
                let k = dev.kernel().fvar(k_fv);
                let value = neg_succ(dev, k);
                let body = dev.apply(p, &[value]);
                dev.lam_fv(k_fv, nat, body)
            };
            let branch_base = dev.apply(predecessor, &[zero, base]);
            let step = {
                let k_fv = dev.fresh_fvar();
                let k = dev.kernel().fvar(k_fv);
                let value = neg_succ(dev, k);
                let ih_ty = dev.apply(p, &[value]);
                let ih_fv = dev.fresh_fvar();
                let ih = dev.kernel().fvar(ih_fv);
                let body = dev.apply(predecessor, &[value, ih]);
                let inner = dev.lam_fv(ih_fv, ih_ty, body);
                dev.lam_fv(k_fv, nat, inner)
            };
            let rec = dev.kernel().const_(nat_rec_name, vec![zero_lvl]);
            let body = dev.apply(rec, &[motive, branch_base, step, n]);
            dev.lam_fv(n_fv, nat, body)
        };
        let rec = dev.kernel().const_(int_rec_name, vec![zero_lvl]);
        let body = dev.apply(rec, &[p, of_nat_branch, neg_succ_branch, t]);
        let value = dev.close_lam(&binders, body);
        dev.declare_theorem_u(names.induction, vec![], statement, value)?;
    }

    // ---- uniqueness of maps out of Int --------------------------------------
    {
        let r_fv = dev.fresh_fvar();
        let r_ty = dev.kernel().fvar(r_fv);
        let map_ty = dev.arrow(int_ty, r_ty);
        let endo_ty = dev.arrow(r_ty, r_ty);
        let f_fv = dev.fresh_fvar();
        let f = dev.kernel().fvar(f_fv);
        let g_fv = dev.fresh_fvar();
        let g = dev.kernel().fvar(g_fv);
        let up_fv = dev.fresh_fvar();
        let up = dev.kernel().fvar(up_fv);
        let down_fv = dev.fresh_fvar();
        let down = dev.kernel().fvar(down_fv);

        let zero = izero(dev);
        let agree_zero_ty = {
            let left = dev.apply(f, &[zero]);
            let right = dev.apply(g, &[zero]);
            dev.eq_at(u_lvl, r_ty, left, right)
        };
        // `∀ t, m (t + delta) = e (m t)`
        let recurrence = |d: &mut CharDev<'_>, m: ExprId, e: ExprId, upward: bool| {
            let t_fv = d.fresh_fvar();
            let t = d.kernel().fvar(t_fv);
            let shifted = if upward {
                plus_one(d, t)
            } else {
                minus_one(d, t)
            };
            let left = d.apply(m, &[shifted]);
            let inner = d.apply(m, &[t]);
            let right = d.apply(e, &[inner]);
            let body = d.eq_at(u_lvl, r_ty, left, right);
            d.pi_fv(t_fv, int_ty, body)
        };
        let f_up_ty = recurrence(dev, f, up, true);
        let g_up_ty = recurrence(dev, g, up, true);
        let f_down_ty = recurrence(dev, f, down, false);
        let g_down_ty = recurrence(dev, g, down, false);
        let g_down_ty = if weaken == Weakening::IntRecUniqueDropPredRecurrence {
            true_ty
        } else {
            g_down_ty
        };

        let agree_zero_fv = dev.fresh_fvar();
        let agree_zero = dev.kernel().fvar(agree_zero_fv);
        let f_up_fv = dev.fresh_fvar();
        let f_up = dev.kernel().fvar(f_up_fv);
        let g_up_fv = dev.fresh_fvar();
        let g_up = dev.kernel().fvar(g_up_fv);
        let f_down_fv = dev.fresh_fvar();
        let f_down = dev.kernel().fvar(f_down_fv);
        let g_down_fv = dev.fresh_fvar();
        let g_down = dev.kernel().fvar(g_down_fv);
        let t_fv = dev.fresh_fvar();
        let t = dev.kernel().fvar(t_fv);

        let binders = [
            (r_fv, sort_u),
            (f_fv, map_ty),
            (g_fv, map_ty),
            (up_fv, endo_ty),
            (down_fv, endo_ty),
            (agree_zero_fv, agree_zero_ty),
            (f_up_fv, f_up_ty),
            (g_up_fv, g_up_ty),
            (f_down_fv, f_down_ty),
            (g_down_fv, g_down_ty),
            (t_fv, int_ty),
        ];
        let conclusion = {
            let left = dev.apply(f, &[t]);
            let right = dev.apply(g, &[t]);
            dev.eq_at(u_lvl, r_ty, left, right)
        };
        let statement = dev.close_pi(&binders, conclusion);

        let motive = {
            let x_fv = dev.fresh_fvar();
            let x = dev.kernel().fvar(x_fv);
            let left = dev.apply(f, &[x]);
            let right = dev.apply(g, &[x]);
            let body = dev.eq_at(u_lvl, r_ty, left, right);
            dev.lam_fv(x_fv, int_ty, body)
        };
        // One induction step: `f (t ± 1) = e (f t) = e (g t) = g (t ± 1)`.
        let shift_step =
            |d: &mut CharDev<'_>, endo: ExprId, f_rule: ExprId, g_rule: ExprId, upward: bool| {
                let x_fv = d.fresh_fvar();
                let x = d.kernel().fvar(x_fv);
                let f_x = d.apply(f, &[x]);
                let g_x = d.apply(g, &[x]);
                let ih_ty = d.eq_at(u_lvl, r_ty, f_x, g_x);
                let ih_fv = d.fresh_fvar();
                let ih = d.kernel().fvar(ih_fv);
                let shifted = if upward {
                    plus_one(d, x)
                } else {
                    minus_one(d, x)
                };
                let f_shifted = d.apply(f, &[shifted]);
                let g_shifted = d.apply(g, &[shifted]);
                let e_f = d.apply(endo, &[f_x]);
                let e_g = d.apply(endo, &[g_x]);
                let first = d.apply(f_rule, &[x]);
                let middle = d.congr_at(u_lvl, r_ty, u_lvl, r_ty, f_x, g_x, ih, &|d2, y| {
                    d2.apply(endo, &[y])
                });
                let last_flipped = d.apply(g_rule, &[x]);
                let last = d.symm_at(u_lvl, r_ty, g_shifted, e_g, last_flipped);
                let prefix = d.trans_at(u_lvl, r_ty, f_shifted, e_f, e_g, first, middle);
                let body = d.trans_at(u_lvl, r_ty, f_shifted, e_g, g_shifted, prefix, last);
                let inner = d.lam_fv(ih_fv, ih_ty, body);
                d.lam_fv(x_fv, int_ty, inner)
            };
        let successor_step = shift_step(dev, up, f_up, g_up, true);
        let predecessor_step = shift_step(dev, down, f_down, g_down, false);
        let head = dev.kernel().const_(names.induction, vec![]);
        let body = dev.apply(
            head,
            &[motive, agree_zero, successor_step, predecessor_step, t],
        );
        let value = dev.close_lam(&binders, body);
        dev.declare_theorem_u(names.rec_unique, vec![names.uparam], statement, value)?;
    }

    // ---- discreteness, totality, and non-triviality -------------------------
    //
    // These three are stated here and discharged by the `Int` prelude's own
    // theorems, on the `arith_model` discipline: the obligation is computed in
    // this module, so a prelude statement that drifts is a kernel rejection
    // rather than a silently different claim.
    let lt_name = dev.int_prelude().lt;
    let le_name = dev.int_prelude().le;
    {
        let t_fv = dev.fresh_fvar();
        let t = dev.kernel().fvar(t_fv);
        let zero = izero(dev);
        let one = ione(dev);
        let lower = dev.const_app(lt_name, &[zero, t]);
        let upper = dev.const_app(lt_name, &[t, one]);
        let both = dev.and_of(lower, upper);
        let negated = dev.not_of(both);
        let statement = dev.pi_fv(t_fv, int_ty, negated);
        let existing = dev.int_prelude().no_int_between;
        let value = dev.kernel().const_(existing, vec![]);
        dev.declare_theorem_u(names.discrete, vec![], statement, value)?;
    }
    {
        let a_fv = dev.fresh_fvar();
        let a = dev.kernel().fvar(a_fv);
        let b_fv = dev.fresh_fvar();
        let b = dev.kernel().fvar(b_fv);
        let forward = dev.const_app(le_name, &[a, b]);
        let backward = dev.const_app(le_name, &[b, a]);
        let body = dev.or_of(forward, backward);
        let statement = dev.close_pi(&[(a_fv, int_ty), (b_fv, int_ty)], body);
        let existing = dev.int_prelude().le_total;
        let value = dev.kernel().const_(existing, vec![]);
        dev.declare_theorem_u(names.le_total, vec![], statement, value)?;
    }
    {
        let zero = izero(dev);
        let one = ione(dev);
        let statement = dev.const_app(lt_name, &[zero, one]);
        let existing = dev.int_prelude().zero_lt_one;
        let value = dev.kernel().const_(existing, vec![]);
        dev.declare_theorem_u(names.zero_lt_one, vec![], statement, value)?;
    }
    {
        // Discreteness everywhere, by translating the interval `(a, a+1)` down
        // to `(0, 1)`: adding `-a` to both sides of each strict inequality is
        // `add_lt_add_of_le_of_lt` with `le_refl` on the left, and the two
        // resulting endpoints normalise to `0` and `1` by the ring laws.
        let prelude = dev.int_prelude();
        let zero = izero(dev);
        let one = ione(dev);
        let a_fv = dev.fresh_fvar();
        let a = dev.kernel().fvar(a_fv);
        let t_fv = dev.fresh_fvar();
        let t = dev.kernel().fvar(t_fv);
        let a_plus_one = iadd(dev, a, one);
        let lower = dev.const_app(lt_name, &[a, t]);
        let upper = dev.const_app(lt_name, &[t, a_plus_one]);
        let both = dev.and_of(lower, upper);
        let negated = dev.not_of(both);
        let statement = dev.close_pi(&[(a_fv, int_ty), (t_fv, int_ty)], negated);

        let h_fv = dev.fresh_fvar();
        let h = dev.kernel().fvar(h_fv);
        let h_lower = dev.and_left(lower, upper, h);
        let h_upper = dev.and_right(lower, upper, h);

        let negated_a = ineg(dev, a);
        let shifted_a = iadd(dev, negated_a, a);
        let shifted_t = iadd(dev, negated_a, t);
        let shifted_a_plus_one = iadd(dev, negated_a, a_plus_one);

        let reflexive = dev.const_app(prelude.le_refl, &[negated_a]);
        let translated_lower = dev.const_app(
            prelude.add_lt_add_of_le_of_lt,
            &[negated_a, negated_a, a, t, reflexive, h_lower],
        );
        let translated_upper = dev.const_app(
            prelude.add_lt_add_of_le_of_lt,
            &[negated_a, negated_a, t, a_plus_one, reflexive, h_upper],
        );

        // `(-a) + a = 0`
        let left_is_zero = {
            let commuted = dev.const_app(prelude.add_comm, &[negated_a, a]);
            let cancelled = dev.const_app(prelude.add_neg, &[a]);
            let flipped = iadd(dev, a, negated_a);
            dev.trans_at(
                one_lvl, int_ty, shifted_a, flipped, zero, commuted, cancelled,
            )
        };
        // `(-a) + (a + 1) = 1`
        let right_is_one = {
            let regrouped = dev.const_app(prelude.add_assoc, &[negated_a, a, one]);
            let grouped = iadd(dev, shifted_a, one);
            let ungrouped = dev.symm_at(one_lvl, int_ty, grouped, shifted_a_plus_one, regrouped);
            let zero_plus_one = iadd(dev, zero, one);
            let normalised = dev.congr_at(
                one_lvl,
                int_ty,
                one_lvl,
                int_ty,
                shifted_a,
                zero,
                left_is_zero,
                &|d, x| iadd(d, x, one),
            );
            let one_plus_zero = iadd(dev, one, zero);
            let commuted = dev.const_app(prelude.add_comm, &[zero, one]);
            let absorbed = dev.const_app(prelude.add_zero, &[one]);
            let tail = dev.trans_at(
                one_lvl,
                int_ty,
                zero_plus_one,
                one_plus_zero,
                one,
                commuted,
                absorbed,
            );
            let head = dev.trans_at(
                one_lvl,
                int_ty,
                shifted_a_plus_one,
                grouped,
                zero_plus_one,
                ungrouped,
                normalised,
            );
            dev.trans_at(
                one_lvl,
                int_ty,
                shifted_a_plus_one,
                zero_plus_one,
                one,
                head,
                tail,
            )
        };

        let normalised_lower = {
            let motive = dev.eq_motive_at(one_lvl, int_ty, shifted_a, &|d, x| {
                d.const_app(lt_name, &[x, shifted_t])
            });
            dev.transport_at(
                one_lvl,
                int_ty,
                shifted_a,
                motive,
                translated_lower,
                zero,
                left_is_zero,
            )
        };
        let normalised_upper = {
            let motive = dev.eq_motive_at(one_lvl, int_ty, shifted_a_plus_one, &|d, x| {
                d.const_app(lt_name, &[shifted_t, x])
            });
            dev.transport_at(
                one_lvl,
                int_ty,
                shifted_a_plus_one,
                motive,
                translated_upper,
                one,
                right_is_one,
            )
        };
        let inner_lower = dev.const_app(lt_name, &[zero, shifted_t]);
        let inner_upper = dev.const_app(lt_name, &[shifted_t, one]);
        let witness = dev.and_intro(inner_lower, inner_upper, normalised_lower, normalised_upper);
        let contradiction = dev.const_app(prelude.no_int_between, &[shifted_t, witness]);
        let body = dev.lam_fv(h_fv, both, contradiction);
        let value = dev.close_lam(&[(a_fv, int_ty), (t_fv, int_ty)], body);
        dev.declare_theorem_u(names.discrete_everywhere, vec![], statement, value)?;
    }

    {
        // `0 = 1` would transport `0 < 1` into `0 < 0`, which `lt_irrefl` refutes.
        let zero = izero(dev);
        let one = ione(dev);
        let equation = dev.eq_at(one_lvl, int_ty, zero, one);
        let statement = dev.not_of(equation);
        let h_fv = dev.fresh_fvar();
        let h = dev.kernel().fvar(h_fv);
        let flipped = dev.symm_at(one_lvl, int_ty, zero, one, h);
        let motive = dev.eq_motive_at(one_lvl, int_ty, one, &|d, x| {
            d.const_app(lt_name, &[zero, x])
        });
        let witness = {
            let name = dev.int_prelude().zero_lt_one;
            dev.kernel().const_(name, vec![])
        };
        let strict = dev.transport_at(one_lvl, int_ty, one, motive, witness, zero, flipped);
        let irrefl = dev.int_prelude().lt_irrefl;
        let contradiction = dev.const_app(irrefl, &[zero, strict]);
        let value = dev.lam_fv(h_fv, equation, contradiction);
        dev.declare_theorem_u(names.zero_ne_one, vec![], statement, value)?;
    }

    Ok(names)
}
