//! The LaTeX emitter: a `.tex` fragment plus a minimal `axeyum.sty`.
//!
//! Total and dumb, per the contract in the crate documentation.
//!
//! The primary output is a FRAGMENT -- no `\documentclass`, no `\begin
//! {document}` -- so it drops into an existing paper's `latex/generated/`
//! directory, which is the whole point of the strand: the paper's claim-bearing
//! content stops being transcribed. Two side files come with it:
//! `axeyum.sty` (the five macros the fragment uses) and
//! `<doc_id>-standalone.tex` (a two-line wrapper so the fragment can be compiled
//! on its own by the P0 compile gate).
//!
//! Verbosity for LaTeX is configurable through `meta.options.latex.detail`:
//! `inline` (default), `appendix` (detail blocks move to the end behind a
//! reference), or `drop-with-href` (detail blocks become links, like `archive`).
//!
//! # On not depending on a CommonMark parser
//!
//! Prose arrives as CommonMark-flavoured text and has to become LaTeX. This file
//! does that with a scanner over four span types -- `$math$`, `` `code` ``,
//! `**bold**`, plain -- escaping the plain and code spans and passing math
//! through untouched. That is deliberately less than a Markdown parser can do,
//! and it is the whole reason `pulldown-cmark` is not a dependency: what a
//! parser would buy is nested inline structure, which no producer emits, at the
//! cost of a large surface whose behaviour on TeX metacharacters we would have
//! to test anyway. A `RichText` that needs more carries an explicit `latex`
//! override, which is exact by construction.

use std::fmt::Write as _;

use crate::assemble::{
    ResolvedBlock, ResolvedDocument, ResolvedEvidence, ResolvedFormal, ResolvedKind, ResolvedStep,
};
use crate::ir::{Align, FigureSpec, RenderHint, RichText, StatementField, Verbosity};
use crate::{EmitOutput, Emitter};

/// Renders a resolved document as a LaTeX fragment.
#[derive(Debug, Clone, Copy, Default)]
pub struct LatexEmitter;

/// How `detail`-tier blocks are placed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DetailMode {
    Inline,
    Appendix,
    DropWithHref,
}

impl DetailMode {
    fn from_options(doc: &ResolvedDocument) -> Self {
        match doc.options.get_str("latex", "detail") {
            Some("appendix") => Self::Appendix,
            Some("drop-with-href") => Self::DropWithHref,
            _ => Self::Inline,
        }
    }
}

impl Emitter for LatexEmitter {
    fn format_name(&self) -> &'static str {
        "tex"
    }

    fn primary_extension(&self) -> &'static str {
        "tex"
    }

    fn emit(&self, doc: &ResolvedDocument) -> EmitOutput {
        let mode = DetailMode::from_options(doc);
        let mut out = EmitOutput::default();
        let mut s = String::new();
        let mut appendix: Vec<(usize, String, String)> = Vec::new();

        s.push_str("% Generated by axeyum-render from Doc-IR. Do not edit.\n");
        s.push_str("% Requires \\usepackage{axeyum} (shipped alongside this fragment).\n");
        let _ = writeln!(s, "\\section*{{{}}}", tex(&doc.title));
        if let Some(sub) = &doc.subtitle {
            let _ = writeln!(s, "\\noindent\\textit{{{}}}\\par\\medskip", tex(sub));
        }
        if !doc.authors.is_empty() {
            let names: Vec<String> = doc.authors.iter().map(|a| tex(a)).collect();
            let _ = writeln!(
                s,
                "\\noindent\\small Authors: {}\\par\\medskip",
                names.join(", ")
            );
        }
        if let Some(a) = &doc.abstract_text {
            let _ = writeln!(s, "\\begin{{quote}}\n{}\n\\end{{quote}}\n", rich(a));
        }

        for block in &doc.blocks {
            let body = render_block(doc, block, &mut out);
            match (block.tag, mode) {
                (Verbosity::Essential, _) | (Verbosity::Detail, DetailMode::Inline) => {
                    s.push_str(&body);
                }
                (Verbosity::Detail, DetailMode::Appendix) => {
                    let n = appendix.len() + 1;
                    let _ = writeln!(s, "\\axdetailref{{{n}}}{{{}}}\n", tex(&fold_summary(block)));
                    appendix.push((n, fold_summary(block), body));
                }
                (Verbosity::Detail, DetailMode::DropWithHref) | (Verbosity::Archive, _) => {
                    let target = archive_target(block).unwrap_or_default();
                    let _ = writeln!(
                        s,
                        "\\axarchive{{{}}}{{{}}}\n",
                        tex(&fold_summary(block)),
                        link(doc, &target)
                    );
                }
            }
        }

        if !appendix.is_empty() {
            s.push_str("\\subsection*{Details}\n\n");
            for (n, summary, body) in &appendix {
                let _ = writeln!(s, "\\axdetail{{{n}}}{{{}}}\n", tex(summary));
                s.push_str(body);
            }
        }

        let _ = writeln!(
            s,
            "\\par\\medskip\\noindent\\footnotesize Rendered from Doc-IR by \\texttt{{axeyum-render}}; \
             epoch {} (source \\texttt{{{}}}){}.",
            doc.epoch_unix,
            tex(&doc.epoch_source),
            match &doc.commit {
                Some(c) => format!(", commit \\texttt{{{}}}", tex(c)),
                None => String::new(),
            }
        );

        out.primary = s;
        out.aux.insert("axeyum.sty".to_string(), STY.to_string());
        out.aux.insert(
            format!("{}-standalone.tex", doc.doc_id),
            standalone_wrapper(&doc.doc_id),
        );
        out
    }
}

#[allow(clippy::too_many_lines)] // one arm per block kind; splitting hides the totality
fn render_block(doc: &ResolvedDocument, block: &ResolvedBlock, out: &mut EmitOutput) -> String {
    let mut s = String::new();
    match &block.kind {
        ResolvedKind::Prose {
            text,
            latex,
            heading_level,
        } => {
            let body = latex.clone().unwrap_or_else(|| rich(text));
            match heading_level {
                Some(1 | 2) => {
                    let _ = writeln!(s, "\\subsection*{{{body}}}\n");
                }
                Some(_) => {
                    let _ = writeln!(s, "\\subsubsection*{{{body}}}\n");
                }
                None => {
                    let _ = writeln!(s, "{body}\n");
                }
            }
        }
        ResolvedKind::Claim {
            label,
            statement,
            status,
            evidence,
            note,
            ..
        } => {
            s.push_str("\\begin{axclaimbox}\n");
            // The cross-format anchor. `render/tests/cross_format.rs` parses
            // exactly `\axclaim{label}{STATUS}` out of the emitted bytes.
            let _ = writeln!(s, "\\axclaim{{{}}}{{{}}}", tex(label), status.badge());
            let body = statement
                .latex
                .clone()
                .unwrap_or_else(|| tex(&statement.text));
            let _ = writeln!(s, "{body}\\par");
            if let Some(from) = &statement.from_ref {
                let _ = writeln!(
                    s,
                    "\\par\\noindent\\small Statement of record: \\texttt{{{}}}",
                    tex(from)
                );
            }
            s.push_str("\\begin{itemize}\n");
            for e in evidence {
                s.push_str(&evidence_item(e));
            }
            s.push_str("\\end{itemize}\n");
            if let Some(n) = note {
                let _ = writeln!(s, "{}\\par", rich(n));
            }
            s.push_str("\\end{axclaimbox}\n\n");
        }
        ResolvedKind::Statement { show, formal, note } => {
            s.push_str(&statement_block(show, formal));
            if let Some(n) = note {
                let _ = writeln!(s, "{}\n", rich(n));
            }
        }
        ResolvedKind::Steps { caption, steps } => {
            if let Some(c) = caption {
                let _ = writeln!(s, "{}\n", rich(c));
            }
            s.push_str("\\begin{enumerate}\n");
            for step in steps {
                s.push_str(&step_item(step));
            }
            s.push_str("\\end{enumerate}\n\n");
        }
        ResolvedKind::Table {
            caption,
            columns,
            rows,
            source,
        } => {
            let spec: String = columns
                .iter()
                .map(|c| match c.align {
                    Some(Align::Right) => 'r',
                    Some(Align::Center) => 'c',
                    _ => 'l',
                })
                .collect();
            let cap = caption.as_ref().map_or_else(String::new, rich);
            let src = format!(
                "\\texttt{{{}}} (exit {}), {} input(s) hashed",
                tex(&source.command),
                source.exit_status,
                source.inputs.len()
            );
            let _ = writeln!(s, "\\begin{{axtable}}{{{cap}}}{{{src}}}");
            let _ = writeln!(s, "\\begin{{tabular}}{{{spec}}}");
            s.push_str("\\hline\n");
            let headers: Vec<String> = columns
                .iter()
                .map(|c| format!("\\textbf{{{}}}", tex(&c.header)))
                .collect();
            let _ = writeln!(s, "{} \\\\", headers.join(" & "));
            s.push_str("\\hline\n");
            for row in rows {
                let cells: Vec<String> = row.iter().map(|c| body_cell(c)).collect();
                let _ = writeln!(s, "{} \\\\", cells.join(" & "));
            }
            s.push_str("\\hline\n\\end{tabular}\n\\end{axtable}\n\n");
        }
        ResolvedKind::Certificate {
            cert_kind,
            summary,
            artifact_refs,
            replay,
            evidence,
            no_exit_reason,
        } => {
            let _ = writeln!(
                s,
                "\\axcert{{{}}}{{{}}}",
                tex(cert_kind.label()),
                rich(summary)
            );
            if !artifact_refs.is_empty() {
                s.push_str("\\begin{itemize}\n");
                for a in artifact_refs {
                    let label = a.label.clone().unwrap_or_else(|| a.path.clone());
                    let _ = writeln!(
                        s,
                        "\\item \\href{{{}}}{{{}}}",
                        link(doc, &a.path),
                        tex(&label)
                    );
                }
                s.push_str("\\end{itemize}\n");
            }
            let _ = writeln!(s, "\\axreplay{{{}}}", tex(&replay.line));
            // Why there is no exit status, when there is none. Printed in
            // every format for the same reason the HTML emitter reports its
            // absence as a diagnostic: a certificate box that is silent about
            // whether anything ran implies a run nothing records.
            if let Some(r) = no_exit_reason {
                let _ = writeln!(
                    s,
                    "\\noindent\\textit{{No run was recorded: {}}}\\par",
                    tex(r)
                );
            }
            if !evidence.is_empty() {
                s.push_str("\\begin{itemize}\n");
                for e in evidence {
                    s.push_str(&evidence_item(e));
                }
                s.push_str("\\end{itemize}\n");
            }
            s.push('\n');
        }
        ResolvedKind::Figure { caption, alt, spec } => {
            let alt = alt.clone().unwrap_or_else(|| "figure".to_string());
            match spec {
                FigureSpec::Svg { svg, src, .. } => {
                    let path = match (src, svg) {
                        (Some(src), _) => src.clone(),
                        (None, Some(svg)) => {
                            let name = format!("{}-{}.svg", doc.doc_id, block.id);
                            out.aux.insert(name.clone(), svg.clone());
                            name
                        }
                        (None, None) => String::new(),
                    };
                    let _ = writeln!(s, "\\axfigure{{{}}}{{{}}}", tex(&alt), link(doc, &path));
                }
                other => {
                    let _ = writeln!(s, "\\axfiguredata{{{}}}", tex(&alt));
                    s.push_str("\\begin{verbatim}\n");
                    s.push_str(&figure_data(other));
                    s.push_str("\n\\end{verbatim}\n");
                }
            }
            if let Some(c) = caption {
                let _ = writeln!(s, "\\par\\noindent\\textit{{{}}}\\par\\medskip\n", rich(c));
            }
        }
        ResolvedKind::Include {
            path,
            render_hint,
            caption,
            inline,
            bytes,
            ..
        } => {
            if let Some(c) = caption {
                let _ = writeln!(s, "{}\n", rich(c));
            }
            match (render_hint, inline) {
                (RenderHint::Code | RenderHint::Json | RenderHint::Text, Some(body)) => {
                    s.push_str("\\begin{verbatim}\n");
                    s.push_str(body.trim_end());
                    s.push_str("\n\\end{verbatim}\n\n");
                }
                _ => {
                    let _ = writeln!(
                        s,
                        "\\noindent\\href{{{}}}{{\\texttt{{{}}}}} ({bytes} bytes)\\par\n",
                        link(doc, path),
                        tex(path)
                    );
                }
            }
        }
    }
    s
}

fn statement_block(show: &[StatementField], f: &ResolvedFormal) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "\\axstatement{{{}}}{{{}}}", tex(&f.key), tex(&f.title));
    for field in show {
        match field {
            StatementField::Title => {}
            StatementField::Prose => {
                let _ = writeln!(s, "{}\\par", tex(&f.prose));
            }
            StatementField::Formal => {
                let _ = writeln!(
                    s,
                    "\\par\\noindent\\small Language \\texttt{{{}}}:",
                    tex(&f.language)
                );
                s.push_str("\\begin{verbatim}\n");
                s.push_str(&f.formal);
                s.push_str("\n\\end{verbatim}\n");
            }
            StatementField::Status => {
                let _ = writeln!(
                    s,
                    "\\par\\noindent Status: established here \\texttt{{{}}}; externally \\texttt{{{}}}.\\par",
                    tex(&f.epistemic_status),
                    tex(f.external_status.as_deref().unwrap_or("not recorded"))
                );
            }
            StatementField::AxiomFootprint => match &f.axiom_footprint {
                Some(list) if list.is_empty() => {
                    s.push_str(
                        "\\par\\noindent Axiom footprint: empty (axiom-free on this route).\\par\n",
                    );
                }
                Some(list) => {
                    let items: Vec<String> = list
                        .iter()
                        .map(|a| format!("\\texttt{{{}}}", tex(a)))
                        .collect();
                    let _ = writeln!(
                        s,
                        "\\par\\noindent Axiom footprint ({}): {}.\\par",
                        list.len(),
                        items.join(", ")
                    );
                }
                None => {
                    s.push_str("\\par\\noindent Axiom footprint: not recorded.\\par\n");
                }
            },
            StatementField::ProofRoute => {
                let _ = writeln!(
                    s,
                    "\\par\\noindent Proof route: \\texttt{{{}}}.\\par",
                    tex(f.proof_route.as_deref().unwrap_or("none"))
                );
            }
            StatementField::DependsOn => {
                if f.depends_on.is_empty() {
                    s.push_str("\\par\\noindent Depends on: nothing (foundational).\\par\n");
                } else {
                    let items: Vec<String> = f
                        .depends_on
                        .iter()
                        .map(|d| format!("\\texttt{{{}}}", tex(d)))
                        .collect();
                    let _ = writeln!(s, "\\par\\noindent Depends on: {}.\\par", items.join(", "));
                }
            }
            StatementField::EvidenceCount => {
                let _ = writeln!(
                    s,
                    "\\par\\noindent Evidence rows in the ledger: {}.\\par",
                    f.evidence_count
                );
            }
        }
    }
    s.push('\n');
    s
}

fn evidence_item(e: &ResolvedEvidence) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "\\item Evidence \\texttt{{{}}} ({}): {} --- \\texttt{{{}}} exited {}, {} input(s) re-hashed.",
        tex(&e.record_id),
        tex(e.role.label()),
        tex(&e.summary),
        tex(&e.command),
        e.exit_status,
        e.inputs_verified
    );
    if let (Some(key), Some(st)) = (&e.claim_key, &e.claim_status) {
        let _ = writeln!(
            s,
            "  \\newline run claim \\texttt{{{}}} \\axbadge{{{}}}: {}",
            tex(key),
            st.badge(),
            tex(e.claim_statement.as_deref().unwrap_or(""))
        );
    }
    if let Some(r) = &e.replay {
        let _ = writeln!(s, "  \\newline replay: \\texttt{{{}}}", tex(&r.line));
    }
    s
}

fn step_item(step: &ResolvedStep) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "\\item \\textbf{{{}}}", tex(&step.op));
    if let Some(i) = &step.input {
        let _ = writeln!(s, "  \\newline in: {}", rich(i));
    }
    let _ = writeln!(s, "  \\newline out: {}", rich(&step.output));
    if let Some(j) = &step.justification {
        let _ = writeln!(
            s,
            "  \\newline by: \\texttt{{{}}} ({})",
            tex(&j.key),
            tex(&j.title)
        );
    }
    if let Some(n) = &step.note {
        let _ = writeln!(s, "  \\newline note: {}", rich(n));
    }
    s
}

fn fold_summary(block: &ResolvedBlock) -> String {
    if let Some(t) = &block.title {
        return t.clone();
    }
    match &block.kind {
        ResolvedKind::Claim { label, .. } => format!("Claim -- {label}"),
        ResolvedKind::Statement { formal, .. } => format!("Statement -- {}", formal.title),
        ResolvedKind::Steps { .. } => "Derivation".to_string(),
        ResolvedKind::Table { .. } => "Table".to_string(),
        ResolvedKind::Certificate { cert_kind, .. } => {
            format!("Certificate -- {}", cert_kind.label())
        }
        ResolvedKind::Figure { .. } => "Figure".to_string(),
        ResolvedKind::Include { path, .. } => path.clone(),
        ResolvedKind::Prose { .. } => "Detail".to_string(),
    }
}

fn archive_target(block: &ResolvedBlock) -> Option<String> {
    match &block.kind {
        ResolvedKind::Include { path, .. } => Some(path.clone()),
        ResolvedKind::Figure {
            spec: FigureSpec::Svg { src: Some(src), .. },
            ..
        } => Some(src.clone()),
        ResolvedKind::Certificate { artifact_refs, .. } => {
            artifact_refs.first().map(|a| a.path.clone())
        }
        _ => block
            .provenance
            .as_ref()
            .and_then(|p| p.inputs.first())
            .map(|i| i.path.clone()),
    }
}

fn link(doc: &ResolvedDocument, path: &str) -> String {
    match (&doc.repo_url, &doc.commit) {
        (Some(url), Some(commit)) => format!("{}/blob/{commit}/{path}", url.trim_end_matches('/')),
        _ => path.to_string(),
    }
}

fn figure_data(spec: &FigureSpec) -> String {
    serde_json::to_string_pretty(&serde_json::to_value(spec).unwrap_or(serde_json::Value::Null))
        .unwrap_or_else(|_| "{}".to_string())
}

/// A `RichText` as LaTeX: the explicit override if there is one, else the
/// mechanical conversion.
fn rich(r: &RichText) -> String {
    r.latex.clone().unwrap_or_else(|| tex(&r.text))
}

/// CommonMark-flavoured text to LaTeX.
///
/// Four span types, scanned left to right: `$math$` passes through untouched,
/// `` `code` `` becomes `\texttt{...}`, `**bold**` becomes `\textbf{...}`, and
/// everything else is escaped. Unterminated delimiters are treated as literal
/// characters, so no input can make this function lose text.
/// A body cell, with the card-link convention applied.
///
/// The Markdown emitter's `body_cell` states the reasoning; this is the same
/// rule, so the three formats put the reader in the same place.
fn body_cell(s: &str) -> String {
    let trimmed = s.trim();
    match crate::doc_link_target(trimmed) {
        Some(page) => {
            let stem = trimmed
                .rsplit('/')
                .next()
                .unwrap_or(trimmed)
                .strip_suffix(".doc.json")
                .unwrap_or(trimmed);
            format!("\\href{{{}}}{{\\texttt{{{}}}}}", page, tex(stem))
        }
        None => tex(s),
    }
}

pub fn tex(input: &str) -> String {
    let b: Vec<char> = input.chars().collect();
    let mut out = String::with_capacity(input.len() + 16);
    let mut plain = String::new();
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if c == '$' {
            if let Some(end) = find_from(&b, i + 1, '$') {
                flush(&mut out, &mut plain);
                out.push('$');
                out.extend(&b[i + 1..end]);
                out.push('$');
                i = end + 1;
                continue;
            }
        } else if c == '`' {
            if let Some(end) = find_from(&b, i + 1, '`') {
                flush(&mut out, &mut plain);
                let inner: String = b[i + 1..end].iter().collect();
                out.push_str("\\texttt{");
                out.push_str(&escape(&inner));
                out.push('}');
                i = end + 1;
                continue;
            }
        } else if c == '*'
            && i + 1 < b.len()
            && b[i + 1] == '*'
            && let Some(end) = find_pair_from(&b, i + 2)
        {
            flush(&mut out, &mut plain);
            let inner: String = b[i + 2..end].iter().collect();
            out.push_str("\\textbf{");
            out.push_str(&escape(&inner));
            out.push('}');
            i = end + 2;
            continue;
        }
        plain.push(c);
        i += 1;
    }
    flush(&mut out, &mut plain);
    out
}

fn flush(out: &mut String, plain: &mut String) {
    if !plain.is_empty() {
        out.push_str(&escape(plain));
        plain.clear();
    }
}

fn find_from(b: &[char], start: usize, target: char) -> Option<usize> {
    (start..b.len()).find(|&j| b[j] == target)
}

fn find_pair_from(b: &[char], start: usize) -> Option<usize> {
    (start..b.len().saturating_sub(1)).find(|&j| b[j] == '*' && b[j + 1] == '*')
}

/// Escape TeX metacharacters in a plain span.
fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\textbackslash{}"),
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            '#' => out.push_str("\\#"),
            '$' => out.push_str("\\$"),
            '%' => out.push_str("\\%"),
            '&' => out.push_str("\\&"),
            '_' => out.push_str("\\_"),
            '~' => out.push_str("\\textasciitilde{}"),
            '^' => out.push_str("\\textasciicircum{}"),
            other => out.push(other),
        }
    }
    out
}

fn standalone_wrapper(doc_id: &str) -> String {
    format!(
        "% Generated by axeyum-render. A minimal wrapper so the fragment can be\n\
         % compiled on its own; a real paper \\input{{}}s the fragment instead.\n\
         \\documentclass[11pt]{{article}}\n\
         \\usepackage[margin=1in]{{geometry}}\n\
         \\usepackage{{axeyum}}\n\
         \\begin{{document}}\n\
         \\input{{{doc_id}.tex}}\n\
         \\end{{document}}\n"
    )
}

/// The style package the fragment requires.
///
/// Minimal on purpose: five semantic macros plus the three helpers they need.
/// A paper may redefine any of them to match its own design -- that is what
/// makes this a fragment and not a document -- but the ARGUMENTS are fixed,
/// because `\axclaim{label}{STATUS}` is what the cross-format property test
/// recovers from the bytes.
const STY: &str = r"% axeyum.sty -- generated by axeyum-render; safe to redefine, do not rename.
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{axeyum}[2026/08/21 Axeyum rendered-evidence macros]
\RequirePackage{hyperref}
\RequirePackage{xcolor}

% \axbadge{STATUS} -- the epistemic-status badge. The token is rendered
% verbatim; it is data from the fact ledger and must not be paraphrased.
\newcommand{\axbadge}[1]{\textsc{\footnotesize[#1]}}

% \axclaim{label}{STATUS} -- a claim header. Use inside axclaimbox.
\newcommand{\axclaim}[2]{\par\noindent\textbf{Claim --- #1}\quad\axbadge{#2}\par\nopagebreak}
\newenvironment{axclaimbox}{\par\medskip\begin{quote}}{\end{quote}\par\medskip}

% \axstatement{key}{title} -- a statement of record pulled by checked reference.
\newcommand{\axstatement}[2]{\par\medskip\noindent\textbf{#2}\quad\texttt{\footnotesize #1}\par\nopagebreak}

% axtable{caption}{source} -- a table with the provenance of the run behind it.
\newenvironment{axtable}[2]{%
  \par\medskip\noindent\textbf{#1}\par\nopagebreak
  \def\axtablesource{#2}%
  \centering
}{%
  \par\noindent\footnotesize Source: \axtablesource.\par\medskip
}

% \axcert{kind}{summary} -- a checkable artifact presented as such.
\newcommand{\axcert}[2]{\par\medskip\noindent\textbf{Certificate --- #1}\par\nopagebreak #2\par}
\newcommand{\axreplay}[1]{\par\noindent\footnotesize Replay: \texttt{#1}\par\medskip}

% \axfigure{alt}{path}, \axfiguredata{alt} -- figures.
\newcommand{\axfigure}[2]{\par\medskip\noindent\framebox{\parbox{0.9\linewidth}{Figure: #1\par\href{#2}{\texttt{#2}}}}\par\medskip}
\newcommand{\axfiguredata}[1]{\par\medskip\noindent\textit{Figure (#1) --- data:}\par\nopagebreak}

% \axarchive{label}{url} -- archive tier: the content is not in the document.
\newcommand{\axarchive}[2]{\par\noindent\textit{Archived --- \href{#2}{#1} (not shown here).}\par\medskip}

% \axdetailref{n}{summary}, \axdetail{n}{summary} -- appendix detail mode.
\newcommand{\axdetailref}[2]{\par\noindent\footnotesize Detail #1 (#2) appears at the end.\par\medskip}
\newcommand{\axdetail}[2]{\par\medskip\noindent\textbf{Detail #1 --- #2}\par\nopagebreak}
\endinput
";

#[cfg(test)]
mod tests {
    use super::tex;

    #[test]
    fn metacharacters_are_escaped_outside_math() {
        assert_eq!(tex("100% of a_b"), "100\\% of a\\_b");
        assert_eq!(tex("cost #1 & #2"), "cost \\#1 \\& \\#2");
    }

    #[test]
    fn math_spans_pass_through_untouched() {
        assert_eq!(
            tex("bound $d(k) \\le 2^k$ holds"),
            "bound $d(k) \\le 2^k$ holds"
        );
    }

    #[test]
    fn code_and_bold_become_macros_with_escaped_interiors() {
        assert_eq!(tex("`a_b`"), "\\texttt{a\\_b}");
        assert_eq!(tex("**x&y**"), "\\textbf{x\\&y}");
    }

    #[test]
    fn an_unterminated_delimiter_loses_no_text() {
        assert_eq!(tex("a $ b"), "a \\$ b");
        assert_eq!(tex("a ` b"), "a ` b");
        assert_eq!(tex("50%"), "50\\%");
    }
}
