# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum._native import cas
import builtins
import typing
__all__ = [
    "AnsatzCheckReport",
    "AnsatzLimits",
    "AnsatzOutcome",
    "LinearBlock",
    "LinearElimination",
    "LinearEliminationCheckReport",
    "cofactors_by_ansatz",
    "combination",
    "detect_linear_blocks",
    "eliminate",
    "eliminate_blocks",
]

@typing.final
class AnsatzCheckReport:
    r"""
    What the ansatz re-expansion established.
    """
    @property
    def identity_holds(self) -> builtins.bool:
        r"""
        Whether `sum(cofactors[i] * generators[i])` re-expanded to the target.
        """
    @property
    def nonzero_cofactors(self) -> builtins.int:
        r"""
        How many cofactors are nonzero — the size of the certificate.
        
        Zero with `identity_holds` true means the target was itself zero: the
        identity is vacuous and nothing was established.
        """
    @property
    def attempted(self) -> builtins.bool:
        r"""
        Whether there were cofactors to check at all.
        """
    def accepted(self) -> builtins.bool:
        r"""
        Whether the check both ran and established something non-vacuous.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class AnsatzLimits:
    r"""
    Explicit ceilings for a bounded-degree membership search.
    
    Only `max_cofactor_degree` is a mathematical parameter — the slice of the
    ideal being searched. The other two exist so a pathological generator list
    cannot allocate an enormous matrix before anyone notices.
    """
    @property
    def max_cofactor_degree(self) -> builtins.int:
        r"""
        The largest total degree an individual cofactor may have.
        """
    @property
    def max_columns(self) -> builtins.int:
        r"""
        The largest number of unknowns admitted.
        """
    @property
    def max_rows(self) -> builtins.int:
        r"""
        The largest number of equations admitted.
        """
    def __new__(cls, max_cofactor_degree: builtins.int = 3, max_columns: builtins.int = 20000, max_rows: builtins.int = 200000) -> AnsatzLimits:
        r"""
        Ceilings, defaulting to the Rust `AnsatzLimits::geometry()` verbatim:
        `max_cofactor_degree=3`, `max_columns=20_000`, `max_rows=200_000`.
        """
    @staticmethod
    def geometry() -> AnsatzLimits:
        r"""
        The ceilings sized for the geometry corpus.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class AnsatzOutcome:
    r"""
    The result of a bounded-degree membership search.
    
    Tier C — outcome. `kind` is one of three genuinely different answers:
    
    * `"Solved"` — cofactors exist at `degree`, and the producer re-expanded them
      before returning, so a wrong solve cannot leave the Rust module;
    * `"NotInDegree"` — **decided**: no representation exists with every cofactor
      of degree at most `bound`. A statement about the degree slice, not about
      the ideal;
    * `"Declined"` — no system was built at all, with the budget that refused.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        `"Solved"`, `"NotInDegree"` or `"Declined"`.
        """
    @property
    def cofactors(self) -> typing.Optional[builtins.list[cas.MvPoly]]:
        r"""
        The cofactors, positionally aligned with the generators, or `None`.
        """
    @property
    def degree(self) -> typing.Optional[builtins.int]:
        r"""
        The degree at which the system became solvable, or `None`.
        """
    @property
    def bound(self) -> typing.Optional[builtins.int]:
        r"""
        The degree bound the search decided against, or `None`.
        
        Present only for `"NotInDegree"`, and reading it is how a caller states
        the decision correctly: *not in the ideal at cofactor degree at most
        this*, which is weaker than *not in the ideal*.
        """
    @property
    def decline(self) -> typing.Optional[builtins.str]:
        r"""
        `"Columns"`, `"Rows"` or `"Overflow"` for a decline, else `None`.
        """
    @property
    def generators(self) -> builtins.list[cas.MvPoly]:
        r"""
        The generators the search was run against.
        """
    @property
    def target(self) -> cas.MvPoly:
        r"""
        The target the search was run against.
        """
    def check(self) -> AnsatzCheckReport:
        r"""
        Re-expands the cofactors and compares with the target, returning the
        report.
        
        The count is the number of nonzero cofactors the identity rests on, and
        it is reported separately from the verdict for a measured reason: the
        geometry corpus contains conclusions that are identically zero with an
        **empty** cofactor list, where "the identity holds" is true and
        establishes nothing.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class LinearBlock:
    r"""
    One square subsystem of the generators, solved by Cramer's rule.
    """
    @property
    def unknowns(self) -> builtins.list[builtins.str]:
        r"""
        The variables this block eliminates, ascending.
        """
    @property
    def rows(self) -> builtins.list[builtins.int]:
        r"""
        Indices into the caller's generator list.
        """
    @property
    def determinant(self) -> cas.MvPoly:
        r"""
        `det(M)`, never the zero polynomial.
        """
    def __new__(cls, unknowns: typing.Sequence[builtins.str], rows: typing.Sequence[builtins.int], determinant: cas.MvPoly) -> LinearBlock:
        r"""
        A block from its parts, so a caller can pin a decomposition rather than
        inherit the heuristic.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LinearElimination:
    r"""
    The identity produced by `eliminate`.
    
    Tier C — certificate. The invariant, and the only thing to rely on:
    
    ```text
    multiplier * target == residue + sum(cofactors[i] * generators[i])
    ```
    
    with `residue` free of every eliminated unknown and `multiplier` the product
    of `blocks[i].determinant ** powers[i]`. `check` re-derives exactly that.
    """
    @property
    def blocks(self) -> builtins.list[LinearBlock]:
        r"""
        The subsystems inverted, in application order.
        """
    @property
    def powers(self) -> builtins.list[builtins.int]:
        r"""
        The determinant power each block contributed to `multiplier`.
        """
    @property
    def multiplier(self) -> cas.MvPoly:
        r"""
        `prod(blocks[i].determinant ** powers[i])`.
        """
    @property
    def cofactors(self) -> builtins.list[cas.MvPoly]:
        r"""
        One cofactor per generator, positionally aligned.
        """
    @property
    def residue(self) -> cas.MvPoly:
        r"""
        What linear algebra could not remove.
        """
    @property
    def generators(self) -> builtins.list[cas.MvPoly]:
        r"""
        The generators the elimination ran against.
        """
    @property
    def target(self) -> cas.MvPoly:
        r"""
        The target the elimination ran against.
        """
    def check(self) -> LinearEliminationCheckReport:
        r"""
        Re-derives `multiplier * target == residue + combination(...)` without
        trusting the producer, returning the report.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class LinearEliminationCheckReport:
    r"""
    What the linear-elimination re-derivation established.
    """
    @property
    def identity_holds(self) -> builtins.bool:
        r"""
        Whether `multiplier * target == residue + combination(...)`.
        """
    @property
    def multiplier_matches(self) -> builtins.bool:
        r"""
        Whether `multiplier` really is the product of the block determinants
        raised to the reported powers.
        
        Checked separately because the identity alone would accept a multiplier
        the blocks do not justify.
        """
    @property
    def nonzero_cofactors(self) -> builtins.int:
        r"""
        How many cofactors are nonzero.
        """
    @property
    def blocks(self) -> builtins.int:
        r"""
        How many blocks were inverted.
        """
    def accepted(self) -> builtins.bool:
        r"""
        Whether both obligations held.
        """
    def __repr__(self) -> builtins.str: ...

def cofactors_by_ansatz(generators: typing.Any, target: cas.MvPoly, limits: typing.Optional[AnsatzLimits] = None) -> AnsatzOutcome:
    r"""
    Searches for `target == sum(u[i] * generators[i])` with every `deg(u[i])` at
    most `d`, for the least `d` that admits one.
    
    Tier C — producer. Degrees are tried ascending, so the representation found
    is the one of least cofactor degree.
    
    # Errors
    
    Propagates the per-element extraction error.
    """

def combination(cofactors: typing.Any, generators: typing.Any) -> typing.Optional[cas.MvPoly]:
    r"""
    `sum(cofactors[i] * generators[i])`, expanded — the re-expansion checker.
    
    Tier R: a pure function, and the public form of the bookkeeping invariant.
    `None` is exact `i128` overflow.
    
    # Errors
    
    Propagates the per-element extraction error.
    """

def detect_linear_blocks(generators: typing.Any, target: cas.MvPoly) -> builtins.list[LinearBlock]:
    r"""
    The heuristic block decomposition of `generators` for `target`.
    
    Tier R: a pure function.
    
    # Errors
    
    Propagates the per-element extraction error.
    """

def eliminate(generators: typing.Any, target: cas.MvPoly) -> typing.Optional[LinearElimination]:
    r"""
    The linear-elimination identity for `target` against `generators`, or `None`.
    
    Tier C — producer. `None` is *no block decomposition applied* or exact
    overflow.
    
    # Errors
    
    Propagates the per-element extraction error.
    """

def eliminate_blocks(generators: typing.Any, target: cas.MvPoly, blocks: typing.Sequence[LinearBlock]) -> typing.Optional[LinearElimination]:
    r"""
    `eliminate` against a caller-chosen block decomposition.
    
    Tier C — producer. Exposed so a caller can pin the decomposition rather than
    inherit the heuristic, and so the heuristic itself is testable against a
    hand-written answer.
    
    # Errors
    
    Propagates the per-element extraction error.
    """

