//! Deterministic markdown rendering of a corpus run into the committed
//! `docs/consumer-track/property/SCOREBOARD.md`.

use std::fmt::Write as _;

use crate::harness::{Aggregate, CaseResult};

/// Render the per-case table + aggregate block as a committed scoreboard.
///
/// Output is fully deterministic when `include_timing` is `false`: cases appear in
/// the corpus' fixed order and no wall-clock number is embedded, so re-running and
/// re-committing is a no-op unless a verdict or certificate fact actually changed.
/// Pass `include_timing = true` for the human stdout summary (which shows the mean
/// solve time); the *committed* `SCOREBOARD.md` is rendered with it `false`.
// A linear sequence of `push_str`/`writeln!` calls building one document; the
// length is inherent to the table, not branching complexity.
#[allow(clippy::too_many_lines)]
#[must_use]
pub fn render_scoreboard(rows: &[CaseResult], agg: &Aggregate, include_timing: bool) -> String {
    let mut s = String::new();

    s.push_str("# App B — property SDK SCOREBOARD\n\n");
    s.push_str(
        "> Self-contained, construction-known bounded-property scoreboard for the\n\
         > `axeyum-property` SDK (App B), generated by `axeyum-consumer-bench` (App D).\n\
         > Ground truth is **by construction** (each property is authored with a known\n\
         > true status), so **no external oracle is needed**. The hard soundness floor\n\
         > is **DISAGREE = 0**: axeyum's verdict must never *contradict* the\n\
         > construction-known status (`Unknown` is allowed, never a contradiction).\n\
         >\n\
         > Regenerate with `scripts/gen-property-scoreboard.py` (re-runs the binary).\n\n",
    );

    // ---- aggregate block ----
    s.push_str("## Aggregate\n\n");
    s.push_str("| metric | value |\n");
    s.push_str("| --- | --- |\n");
    push_row(&mut s, "cases", &agg.total.to_string());
    push_row(
        &mut s,
        "proved",
        &format!("{} ({})", agg.proved, pct(agg.proved_rate())),
    );
    push_row(
        &mut s,
        "counterexample",
        &format!(
            "{} ({})",
            agg.counterexample,
            pct(agg.counterexample_rate())
        ),
    );
    push_row(
        &mut s,
        "unknown",
        &format!("{} ({})", agg.unknown, pct(agg.unknown_rate())),
    );
    push_row(
        &mut s,
        "cert re-verified (of proved)",
        &format!("{}/{}", agg.cert_verified, agg.proved),
    );
    push_row(
        &mut s,
        "**Lean-cert coverage** (verified Lean module / proved)",
        &format!(
            "{}/{} ({})",
            agg.lean_certified,
            agg.proved,
            pct(agg.lean_cert_coverage())
        ),
    );
    if include_timing {
        push_row(&mut s, "mean solve time", &fmt_millis(agg));
    }
    push_row(
        &mut s,
        "**DISAGREE** (hard soundness floor)",
        &agg.disagree.to_string(),
    );
    s.push('\n');

    if agg.disagree == 0 {
        s.push_str(
            "**DISAGREE = 0** — no axeyum verdict contradicts a construction-known status.\n\n",
        );
    } else {
        let _ = write!(
            s,
            "**DISAGREE = {} — SOUNDNESS ALARM.** See contradicting rows below.\n\n",
            agg.disagree
        );
    }

    // ---- per-case table ----
    s.push_str("## Per-property results\n\n");
    s.push_str("| property | construction-known | axeyum verdict | match | cert re-checked | Lean module |\n");
    s.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for r in rows {
        let matched = if r.is_disagreement() {
            "DISAGREE"
        } else if r.verdict.matches(r.status) {
            "yes"
        } else {
            // Unknown: honest non-result.
            "unknown"
        };
        let cert = match r.cert_verified {
            Some(true) => "yes",
            Some(false) => "no",
            None => "-",
        };
        let lean = match r.lean_module {
            Some(true) => "yes",
            Some(false) => "no",
            None => "-",
        };
        let _ = writeln!(
            s,
            "| `{}` | {} | {} | {} | {} | {} |",
            r.name,
            r.status.label(),
            r.verdict.label(),
            matched,
            cert,
            lean
        );
    }
    s.push('\n');

    // ---- legend ----
    s.push_str("### Notes\n\n");
    s.push_str(
        "- *construction-known*: the authored true status — `should-prove` (a valid\n\
         identity) or `should-find-ce` (a deliberate bug with a named witness).\n\
         - *match*: `yes` = axeyum's decided verdict equals the known status;\n\
         `unknown` = axeyum honestly did not decide (allowed); `DISAGREE` = a\n\
         contradiction (a hard failure — must never appear).\n\
         - *cert re-checked*: for a `proved` row, `Certificate::verify()` independently\n\
         re-validated the evidence.\n\
         - *Lean module*: for a `proved` row, `Certificate::to_lean_module()` emitted a\n\
         standalone Lean module (the differentiator; `no` is honest, never faked).\n",
    );

    s
}

fn push_row(s: &mut String, k: &str, v: &str) {
    let _ = writeln!(s, "| {k} | {v} |");
}

/// Percentage with one decimal, e.g. `66.7%`.
fn pct(x: f64) -> String {
    format!("{:.1}%", x * 100.0)
}

/// Mean solve time in milliseconds, rounded to whole ms for determinism across
/// re-runs (sub-ms jitter would otherwise churn the committed file).
fn fmt_millis(agg: &Aggregate) -> String {
    let ms = agg.mean_time().as_millis();
    format!("~{ms} ms")
}
