//! **Characterization theorems**: machine-checked evidence that the `Nat` and
//! `Int` this kernel constructs are *the* natural numbers and *the* integers,
//! rather than two bespoke inductive types that happen to carry familiar law
//! names.
//!
//! ## The gap this closes
//!
//! `nat_axiom_inventory` reports `nat: axiom=0` and `integer: axiom=0`, and the
//! `Int` prelude proves the full ordered-ring law set. None of that says the
//! objects are the standard ones. A theorem about an inductive type named `Int`
//! is only as meaningful as that type being what everyone means by `ℤ`: if
//! `Int.lt` were subtly wrong every module would still typecheck, still report
//! an empty axiom footprint, and still be worthless. Rendered Lean modules make
//! the gap concrete — they run in `prelude` mode and **re-declare** their own
//! `Nat`, `Int`, `Eq` and `False`, so official Lean accepting one certifies
//! "this proof typechecks against *these* definitions", not that they are the
//! standard ones.
//!
//! The remedy is not inspection but **proof**: state the properties that
//! determine the object up to isomorphism, and have the kernel check them.
//!
//! ## What is proved
//!
//! ### `Nat` — pinned up to unique isomorphism
//!
//! [`NatCharacterization`] declares the three Peano axioms
//! (`zero_ne_succ`, `succ_injective`, `induction`), the universal property of
//! `Nat` as the initial iteration algebra (`iter`, `iter_zero`, `iter_succ`,
//! `iter_unique`), and — the payload — `categorical`:
//!
//! ```text
//! ∀ (N : Sort u) (z : N) (s : N → N),
//!   (∀ n, z ≠ s n) → (∀ m n, s m = s n → m = n) →
//!   (∀ (P : N → Prop), P z → (∀ n, P n → P (s n)) → ∀ n, P n) →
//!   ((iter N z s 0 = z ∧ ∀ k, iter N z s (k+1) = s (iter N z s k))
//!    ∧ ((∀ k m, iter N z s k = iter N z s m → k = m)
//!       ∧ (∀ y, ∃ k, iter N z s k = y)))
//! ```
//!
//! That is second-order categoricity, stated *inside* the kernel: **any**
//! structure satisfying the Peano axioms is in structure-preserving bijection
//! with our `Nat`, and `iter_unique` says the bijection is the only such map.
//! It is universe-polymorphic, so it is not a statement about one chosen
//! universe. This is strictly stronger than a bridge lemma to a specific other
//! definition of `ℕ`: it quantifies over every possible one.
//!
//! ### `Int` — pinned by no-junk, generation, discreteness and order
//!
//! Ordered-ring laws do **not** pin `ℤ` (`ℚ` satisfies all of them; so does
//! lexicographic `ℤ[x]`, which is even discretely ordered).
//! [`IntCharacterization`] adds the properties that do the separating: `cases`
//! and `of_nat_or_neg` (no junk — every element is `±` a natural), `induction`
//! (generation by `0` under `±1`, which `ℤ[x]` fails), `discrete` (nothing
//! strictly between `0` and `1`, which `ℚ` fails), `le_total`, `zero_lt_one`,
//! `discrete_everywhere` (the same at every `a`), `le_total`, `zero_lt_one`,
//! `zero_ne_one`, and `rec_unique` (the uniqueness half of the universal
//! property: two maps out of `Int` agreeing at `0` with the same `±1`
//! recurrences are equal).
//!
//! ### What is **not** proved — read this before quoting the above
//!
//! * The `Int` package has no internal categoricity theorem matching the `Nat`
//!   one. Proving "every discretely ordered ring generated by `1` is isomorphic
//!   to `Int`" needs the *existence* half of the universal property for an
//!   arbitrary target — a map `Int → R` built from `R`'s own data — and every
//!   such construction needs `R` to come with more structure than a bare
//!   hypothesis list makes convenient. `rec_unique` is the uniqueness half
//!   only. Stated precisely: **`Int` is proved to be a discretely ordered,
//!   totally ordered, non-trivial commutative ring generated by `1`, on which
//!   maps out are unique; it is not proved that those properties determine it
//!   up to isomorphism.**
//! * Discreteness *is* proved at every point, not only at the origin:
//!   `discrete_everywhere` translates the interval `(a, a+1)` down to `(0, 1)`
//!   through `−a` and lands in `discrete`. What is still absent is the step
//!   from "these properties hold" to "these properties determine `Int`".
//! * `Nat`'s `categorical` hypothesises a `Prop`-valued induction principle on
//!   the other structure. That is the second-order Peano axiom, and it is what
//!   makes categoricity true at all — first-order `PA` is *not* categorical.
//!   Surjectivity is proved from it; injectivity from the other two axioms.
//!
//! ## Discipline
//!
//! Every statement in this module is **built here** and handed to
//! [`Kernel::add_declaration`](crate::Kernel::add_declaration) together with
//! its proof, exactly as [`build_int_model_of_arith`](crate::build_int_model_of_arith)
//! computes its obligations from the axioms as they stand in the environment.
//! Three consequences: a prelude theorem whose statement drifts makes the
//! matching restatement here **fail** rather than silently weaken; a proof that
//! stops working is a rejection, not a skipped row; and [`Weakening`] injects
//! deliberate defects into the same code path so the negative-control tests
//! prove each hypothesis is load-bearing.

mod int;
mod nat;
mod ops;

pub use int::IntCharacterization;
pub use nat::NatCharacterization;

use crate::int_prelude::{IntPrelude, build_int_prelude};
use crate::name::NameId;
use crate::{Kernel, KernelError};

use ops::CharDev;

/// A deliberate defect injected into one characterization statement.
///
/// Every variant other than [`Weakening::None`] must make
/// [`build_characterization_with`] **fail**: that is what makes the
/// corresponding hypothesis provably load-bearing rather than decorative. The
/// variants run through the same builder as the real package, so they test the
/// shipped code path and not a reimplementation of it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Weakening {
    /// Build the real package.
    #[default]
    None,
    /// State Peano 1 as `succ n ≠ zero` while keeping the oriented transport.
    ZeroNeSuccReversed,
    /// Demand the induction base case at `succ zero` instead of `zero`.
    InductionBaseAtOne,
    /// Replace `iter_unique`'s `h zero = a` hypothesis with `True`.
    IterUniqueDropZeroHypothesis,
    /// Replace `injective`'s `z ≠ s n` hypothesis with `True`.
    InjectiveDropZeroNeSucc,
    /// Replace `injective`'s successor-injectivity hypothesis with `True`.
    InjectiveDropSuccInjective,
    /// Replace `surjective`'s induction hypothesis with `True`.
    SurjectiveDropInduction,
    /// Replace the `Int` induction principle's `+1` step with `True`.
    IntInductionDropSuccStep,
    /// Replace the `Int` induction principle's `−1` step with `True`.
    IntInductionDropPredStep,
    /// Replace `rec_unique`'s `g`-side `−1` recurrence with `True`.
    IntRecUniqueDropPredRecurrence,
}

impl Weakening {
    /// The declaration this defect must make the kernel **refuse**, as a dotted
    /// name.
    ///
    /// Asserting only "the build failed" would pass if the defect broke some
    /// earlier, unrelated declaration; the negative controls check that the
    /// build got as far as this declaration and died *there*.
    #[must_use]
    pub fn refused_declaration(self) -> Option<&'static str> {
        match self {
            Weakening::None => None,
            Weakening::ZeroNeSuccReversed => Some("Nat.Peano.zero_ne_succ"),
            Weakening::InductionBaseAtOne => Some("Nat.Peano.induction"),
            Weakening::IterUniqueDropZeroHypothesis => Some("Nat.Peano.iter_unique"),
            Weakening::InjectiveDropZeroNeSucc | Weakening::InjectiveDropSuccInjective => {
                Some("Nat.Peano.injective")
            }
            Weakening::SurjectiveDropInduction => Some("Nat.Peano.surjective"),
            Weakening::IntInductionDropSuccStep | Weakening::IntInductionDropPredStep => {
                Some("Int.Characterization.induction")
            }
            Weakening::IntRecUniqueDropPredRecurrence => Some("Int.Characterization.rec_unique"),
        }
    }

    /// Every injected defect, for the negative-control sweep.
    #[must_use]
    pub fn defects() -> &'static [Weakening] {
        &[
            Weakening::ZeroNeSuccReversed,
            Weakening::InductionBaseAtOne,
            Weakening::IterUniqueDropZeroHypothesis,
            Weakening::InjectiveDropZeroNeSucc,
            Weakening::InjectiveDropSuccInjective,
            Weakening::SurjectiveDropInduction,
            Weakening::IntInductionDropSuccStep,
            Weakening::IntInductionDropPredStep,
            Weakening::IntRecUniqueDropPredRecurrence,
        ]
    }
}

/// What a characterization theorem contributes to pinning its object.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CharacterizationKind {
    /// One of the three Peano axioms for `Nat`.
    PeanoAxiom,
    /// Part of the universal property (initiality) of `Nat`.
    NatUniversalProperty,
    /// Part of the categoricity theorem for `Nat`.
    NatCategoricity,
    /// `Int` has no elements beyond its constructors.
    IntNoJunk,
    /// `Int` is generated by `0` under `±1`.
    IntGeneration,
    /// The uniqueness half of `Int`'s universal property.
    IntUniversalProperty,
    /// `Int` is discretely ordered, totally ordered, and non-trivial.
    IntOrder,
}

impl CharacterizationKind {
    /// A short stable label for reports.
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            CharacterizationKind::PeanoAxiom => "peano-axiom",
            CharacterizationKind::NatUniversalProperty => "nat-universal-property",
            CharacterizationKind::NatCategoricity => "nat-categoricity",
            CharacterizationKind::IntNoJunk => "int-no-junk",
            CharacterizationKind::IntGeneration => "int-generation",
            CharacterizationKind::IntUniversalProperty => "int-universal-property",
            CharacterizationKind::IntOrder => "int-order",
        }
    }
}

/// One admitted characterization declaration and what it establishes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CharacterizationEntry {
    /// The admitted declaration.
    pub name: NameId,
    /// What it contributes.
    pub kind: CharacterizationKind,
}

/// The result of [`build_characterization`]: the underlying `Int` development
/// and both characterization packages.
#[derive(Debug, Clone)]
pub struct Characterization {
    /// The constructed integer prelude everything rests on.
    pub int_prelude: IntPrelude,
    /// The `Nat.Peano` package.
    pub nat: NatCharacterization,
    /// The `Int.Characterization` package.
    pub int: IntCharacterization,
    /// Every admitted theorem, in declaration order, with its role.
    pub entries: Vec<CharacterizationEntry>,
}

/// Build the `Int` development and admit every characterization theorem.
///
/// # Errors
///
/// Returns the trusted gate's rejection. An `Err` here means the kernel
/// **refused** a characterization proof — the claim is not established.
pub fn build_characterization(kernel: &mut Kernel) -> Result<Characterization, KernelError> {
    build_characterization_with(kernel, Weakening::None)
}

/// [`build_characterization`] with a deliberate defect injected.
///
/// # Errors
///
/// Returns the trusted gate's rejection. For every
/// [`Weakening`] other than [`Weakening::None`] an `Err` is the **expected**
/// outcome and an `Ok` is a test failure: it would mean the weakened hypothesis
/// was never load-bearing.
pub fn build_characterization_with(
    kernel: &mut Kernel,
    weakening: Weakening,
) -> Result<Characterization, KernelError> {
    let int_prelude = build_int_prelude(kernel)?;
    let mut dev = CharDev::new(kernel, int_prelude);
    let nat = nat::declare(&mut dev, weakening)?;
    let int = int::declare(&mut dev, weakening)?;
    let entries = vec![
        CharacterizationEntry {
            name: nat.zero_ne_succ,
            kind: CharacterizationKind::PeanoAxiom,
        },
        CharacterizationEntry {
            name: nat.succ_injective,
            kind: CharacterizationKind::PeanoAxiom,
        },
        CharacterizationEntry {
            name: nat.induction,
            kind: CharacterizationKind::PeanoAxiom,
        },
        CharacterizationEntry {
            name: nat.iter_zero,
            kind: CharacterizationKind::NatUniversalProperty,
        },
        CharacterizationEntry {
            name: nat.iter_succ,
            kind: CharacterizationKind::NatUniversalProperty,
        },
        CharacterizationEntry {
            name: nat.iter_unique,
            kind: CharacterizationKind::NatUniversalProperty,
        },
        CharacterizationEntry {
            name: nat.injective,
            kind: CharacterizationKind::NatCategoricity,
        },
        CharacterizationEntry {
            name: nat.surjective,
            kind: CharacterizationKind::NatCategoricity,
        },
        CharacterizationEntry {
            name: nat.categorical,
            kind: CharacterizationKind::NatCategoricity,
        },
        CharacterizationEntry {
            name: int.cases,
            kind: CharacterizationKind::IntNoJunk,
        },
        CharacterizationEntry {
            name: int.of_nat_or_neg,
            kind: CharacterizationKind::IntNoJunk,
        },
        CharacterizationEntry {
            name: int.induction,
            kind: CharacterizationKind::IntGeneration,
        },
        CharacterizationEntry {
            name: int.rec_unique,
            kind: CharacterizationKind::IntUniversalProperty,
        },
        CharacterizationEntry {
            name: int.discrete,
            kind: CharacterizationKind::IntOrder,
        },
        CharacterizationEntry {
            name: int.discrete_everywhere,
            kind: CharacterizationKind::IntOrder,
        },
        CharacterizationEntry {
            name: int.le_total,
            kind: CharacterizationKind::IntOrder,
        },
        CharacterizationEntry {
            name: int.zero_lt_one,
            kind: CharacterizationKind::IntOrder,
        },
        CharacterizationEntry {
            name: int.zero_ne_one,
            kind: CharacterizationKind::IntOrder,
        },
    ];
    Ok(Characterization {
        int_prelude,
        nat,
        int,
        entries,
    })
}

#[cfg(test)]
mod characterization_tests;
