//! Cross-prelude declaration-name collision gate.
//!
//! # The incident this exists for
//!
//! A lane once added `Nat.inverseIndex` for a new bijection on `[0,n)`. That
//! name was already taken -- by
//! `crates/axeyum-lean-kernel/src/int_prelude/wilson.rs`, which declares
//! `Nat.inverseIndex` (and eight lemmas about it) into the `Nat` namespace
//! from the *Int* prelude module, for the modular-inverse index Wilson's
//! theorem needs. Nothing about that collision was visible where it mattered:
//!
//! - `nat_prelude/` (the whole directory) never mentions the name, because
//!   the clash was with a DIFFERENT prelude's file.
//! - `cargo test --lib nat_prelude::` was green: the `nat` prelude builds
//!   fine alone. The collision only fires once `int` (which builds `nat`
//!   first, then adds `wilson.rs`'s declarations on top) shares a kernel with
//!   whatever else declared the name.
//! - The failure that finally surfaced it named neither string nor either
//!   declaring site: `the Int model must build: DeclarationExists { name:
//!   NameId(457) }`, 230 failures deep in `arith_model`/`characterization`.
//!
//! This module turns that into a same-sweep, named-string, named-preludes
//! failure, run BEFORE any of those 230 tests get a chance to hit it.
//!
//! # "Declared under `Nat.`" vs. "declared by the `nat` prelude"
//!
//! These are different questions and this module answers the second one.
//! [`own_declarations`] attributes a name to the prelude MODULE whose build
//! call actually put it in the environment -- computed by diffing each
//! prelude's full declaration set against the one immediately below it in the
//! dependency chain ([`DEPENDS_ON`]), never by looking at the name's own
//! namespace prefix. `Nat.inverseIndex` and its siblings are attributed to
//! `integer` (the module that calls `wilson::declare_wilson`), even though
//! every one of those names lives under the `Nat.` namespace string, because
//! `integer` is what put them in the environment; they are not attributed to
//! `nat` just because their name starts with `Nat.`.
//!
//! # Why a diff, not an actual combined build
//!
//! Two prelude trees only collide for real once both are built into ONE
//! kernel (e.g. [`crate::build_int_model_of_arith`], which builds `axreal`
//! then `integer` in the same kernel). We don't need to enumerate every
//! combiner to catch this: if prelude A and prelude B each introduce (i.e.
//! are the first to declare) the same name, combining ANY two trees that
//! include both A's and B's own contribution will hit
//! [`crate::KernelError::DeclarationExists`] on whichever is added second.
//! So the real invariant is simpler than "every combiner still builds": no
//! two preludes may *introduce* the same name in the first place. That is
//! what [`cross_prelude_collisions`] checks, over every prelude this crate
//! ships.

use std::collections::{BTreeMap, BTreeSet};

use crate::{
    Declaration, Kernel, build_arith_prelude, build_characterization, build_complex_prelude,
    build_cpoint_prelude, build_creal_prelude, build_int_prelude, build_ipc_soundness_prelude,
    build_list_nat_bridge, build_list_perm, build_logic_prelude, build_nat_prelude,
    build_rat_prelude, build_string_prelude, on_a_deep_stack,
};

/// Every declaration name currently in `kernel`'s environment, in canonical
/// dotted form (`kernel.display_name`, the RAW interned name -- not the
/// `lean_pp` export rename, which is a distinct, non-shadowing rendering used
/// only for Lean text output; see the `AxNat` gotcha in `CLAUDE.md`).
fn declared_names(kernel: &Kernel) -> BTreeSet<String> {
    kernel
        .environment()
        .iter()
        .map(|(name, _)| kernel.display_name(*name).to_string())
        .collect()
}

/// How a declaration was admitted, recorded while its kernel was still alive.
///
/// The distinction that matters here is [`DeclKind::Trusted`] versus the other
/// two: an `Axiom`/`Opaque`/`Quotient` is admitted with **no checked proof
/// body**, so it is a thing every proof reaching it rests on. `Inductive`/
/// `Constructor`/`Recursor` are [`DeclKind::Structural`] -- generated by the
/// kernel from a checked inductive declaration, with no proof term for
/// `Kernel::axiom_footprint` to inspect the way a `Definition`'s value or a
/// `Theorem`'s proof has one.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
enum DeclKind {
    /// `Definition` or `Theorem`: admitted with a checked body.
    Checked,
    /// `Inductive`, `Constructor` or `Recursor`.
    Structural,
    /// `Axiom`, `Opaque` or `Quotient`: admitted WITHOUT a checked body.
    Trusted,
}

fn decl_kind(declaration: &Declaration) -> DeclKind {
    match declaration {
        Declaration::Definition { .. } | Declaration::Theorem { .. } => DeclKind::Checked,
        Declaration::Inductive { .. }
        | Declaration::Constructor { .. }
        | Declaration::Recursor { .. } => DeclKind::Structural,
        Declaration::Axiom { .. } | Declaration::Opaque { .. } | Declaration::Quotient { .. } => {
            DeclKind::Trusted
        }
    }
}

/// One prelude group: its label, its full (transitive) declaration set, and --
/// recorded while the kernel was alive, because [`build_groups`] drops each
/// kernel as soon as it moves to the next prelude -- how each of those
/// declarations was admitted, plus the axiom footprint of every `Checked` one
/// **when this prelude's environment carries anything trusted at all**.
///
/// # Why the footprints are conditional
///
/// `Kernel::axiom_footprint` walks the whole transitive declaration closure
/// from scratch on every call: over `creal`'s 2,261 declarations that is
/// quadratic, and this file already builds ten preludes in one test. It is
/// also, for nine of those ten, an expensive way to recompute a constant.
/// If an environment contains **no** `Axiom`/`Opaque`/`Quotient` declaration
/// anywhere, then no closure from anything in it can reach one, so every
/// footprint in it is empty -- by construction, not by measurement. That is
/// the same argument `prelude_tests.rs`'s
/// `logic_prelude_with_accessibility_declares_no_axioms` rests on; here it is
/// **asserted per prelude** ([`Group::trusted`] is checked against an
/// allowlist) rather than assumed, and the moment a prelude does carry a
/// trusted declaration this field stops being empty and the real per-
/// declaration footprints are measured instead.
struct Group {
    label: &'static str,
    all: BTreeSet<String>,
    kinds: BTreeMap<String, DeclKind>,
    /// Populated only when this prelude's environment holds a `Trusted`
    /// declaration; see the type doc. Maps a `Checked` declaration's name to
    /// the trusted names its proof reaches (empty vector = axiom-free).
    footprints: BTreeMap<String, Vec<String>>,
}

impl Group {
    /// Snapshot `kernel` under `label`: names, admission kinds, and -- only if
    /// something in it is [`DeclKind::Trusted`] -- the per-declaration axiom
    /// footprints.
    fn of(label: &'static str, kernel: &Kernel) -> Self {
        let all = declared_names(kernel);
        let kinds: BTreeMap<String, DeclKind> = kernel
            .environment()
            .iter()
            .map(|(name, declaration)| {
                (
                    kernel.display_name(*name).to_string(),
                    decl_kind(declaration),
                )
            })
            .collect();
        let any_trusted = kinds.values().any(|k| *k == DeclKind::Trusted);
        let footprints = if any_trusted {
            kernel
                .environment()
                .iter()
                .filter(|(_, declaration)| decl_kind(declaration) == DeclKind::Checked)
                .map(|(name, _)| {
                    (
                        kernel.display_name(*name).to_string(),
                        kernel
                            .axiom_footprint(*name)
                            .into_iter()
                            .map(|a| kernel.display_name(a).to_string())
                            .collect::<Vec<_>>(),
                    )
                })
                .collect()
        } else {
            BTreeMap::new()
        };
        Self {
            label,
            all,
            kinds,
            footprints,
        }
    }

    /// Whether this prelude's environment carries any declaration admitted
    /// without a checked proof body.
    fn any_trusted(&self) -> bool {
        self.kinds.values().any(|k| *k == DeclKind::Trusted)
    }
}

/// Build every prelude this crate ships, each in its own fresh kernel, and
/// collect the full (transitive) declaration set each one ends up with.
///
/// Mirrors `examples/prelude_theorem_inventory.rs`'s `build_groups`: same
/// prelude list, same dependency order, same "always include `--include
/// -constructed`'s groups" choice -- `creal`/`complex`/`cpoint` cost real
/// kernel type-checking, but this gate exists precisely to catch a collision
/// wherever one can occur, and skipping the constructed carriers would leave
/// exactly the kind of blind spot this file is about.
fn build_groups() -> Vec<Group> {
    let mut groups = Vec::new();

    let mut logic = Kernel::new();
    build_logic_prelude(&mut logic).expect("logic prelude must build");
    groups.push(Group::of("logic", &logic));

    let mut nat = Kernel::new();
    build_nat_prelude(&mut nat).expect("Nat prelude must build");
    groups.push(Group::of("nat", &nat));

    // `list`: built via the full bridge + `Perm` package so the group matches
    // `kernel_declaration_projection` and `prelude_theorem_inventory`, which
    // `scripts/check-theorem-inventory-completeness.py` requires to agree.
    let mut list = Kernel::new();
    let (list_prelude, list_nat, list_bridge) =
        build_list_nat_bridge(&mut list).expect("List/Nat bridge must build");
    let _ = build_list_perm(&mut list, &list_prelude, &list_nat, &list_bridge)
        .expect("List.Perm must build");
    groups.push(Group::of("list", &list));

    let mut axreal = Kernel::new();
    build_arith_prelude(&mut axreal).expect("AxReal prelude must build");
    groups.push(Group::of("axreal", &axreal));

    let mut integer = Kernel::new();
    build_int_prelude(&mut integer).expect("Int prelude must build");
    groups.push(Group::of("integer", &integer));

    // The Peano/initiality characterization package (`Nat.Peano.*`,
    // `Int.Characterization.*`). Built after `integer`, before `rat` -- the
    // same dependency-order position `prelude_theorem_inventory.rs` and
    // `kernel_declaration_projection.rs` use. This is the group whose
    // omission from THIS file's `build_groups` motivated
    // `docs/plan/status/146-collision-gap.md`: identical to the gap fixed in
    // `prelude_theorem_inventory.rs` (32 theorems silently invisible), except
    // here the missing coverage was a cross-prelude COLLISION check rather
    // than a theorem count -- 32 declarations that had never been checked
    // for a name clash against any other prelude.
    let mut characterization = Kernel::new();
    build_characterization(&mut characterization).expect("Nat/Int characterization must build");
    groups.push(Group::of("characterization", &characterization));

    // The IPC package. `build_ipc_soundness_prelude` transitively builds
    // provable -> heyting -> nat, so one group covers the whole
    // intuitionistic-logic surface. Unconditional, for `characterization`'s
    // reason: it is `build_nat_prelude` plus the IPC declarations, so it costs
    // no more than the already-unconditional `nat` group.
    //
    // Absent from all three tools until 2026-08-31, and the omission had a
    // measured cost outside the kernel: `scripts/check-trust-closure.py` read
    // `F:excluded-middle-not-intuitionistic` and
    // `F:heyting-3-chain-refutes-excluded-middle` as having no identifiable
    // subject, and a census wrote them down as "umbrella facts" -- about
    // several theorems at once. Each is about exactly one theorem
    // (`ipc_excluded_middle_not_provable`, `ipc_heyting_join_not_ne_top`,
    // both verified byte-for-byte against the fact's `formal.statement`).
    // A prelude group no tool builds is indistinguishable from declarations
    // that do not exist.
    let mut ipc = Kernel::new();
    build_ipc_soundness_prelude(&mut ipc).expect("IPC soundness prelude must build");
    groups.push(Group::of("ipc", &ipc));

    let mut rat = Kernel::new();
    build_rat_prelude(&mut rat).expect("Rat prelude must build");
    groups.push(Group::of("rat", &rat));

    let mut string = Kernel::new();
    let logic_handle = build_logic_prelude(&mut string).expect("logic prelude must build");
    build_string_prelude(&mut string, logic_handle, 2).expect("string prelude must build");
    groups.push(Group::of("string", &string));

    let mut creal = Kernel::new();
    build_creal_prelude(&mut creal).expect("CReal prelude must build");
    groups.push(Group::of("creal", &creal));

    let mut complex = Kernel::new();
    build_complex_prelude(&mut complex).expect("Complex prelude must build");
    groups.push(Group::of("complex", &complex));

    let mut cpoint = Kernel::new();
    build_cpoint_prelude(&mut cpoint).expect("CPoint prelude must build");
    groups.push(Group::of("cpoint", &cpoint));

    groups
}

/// Each prelude's immediate dependency, matching the internal `build_…`
/// calls each module makes on itself (`nat_prelude.rs` calls
/// `build_logic_prelude`, `int_prelude.rs` calls `build_nat_prelude`, …).
/// `None` for `logic`, the base of the chain. This is what lets
/// [`own_declarations`] tell "introduced by this module" apart from
/// "inherited from the dependency this module builds on top of".
const DEPENDS_ON: &[(&str, Option<&str>)] = &[
    ("logic", None),
    ("nat", Some("logic")),
    ("axreal", Some("logic")),
    ("integer", Some("nat")),
    // `build_characterization` builds `Int` internally (`build_int_prelude`,
    // which itself builds `Nat`/`logic`) before admitting the Peano/
    // initiality theorems, so its OWN contribution is what it adds beyond
    // `integer` -- never `integer`'s own declarations.
    ("characterization", Some("integer")),
    ("rat", Some("integer")),
    ("string", Some("logic")),
    ("creal", Some("rat")),
    ("complex", Some("creal")),
    ("cpoint", Some("creal")),
];

/// For each prelude PRESENT in `groups`, the names it introduces ITSELF:
/// present in its own full declaration set but absent from the dependency it
/// builds on top of. See the module doc for why this -- not the name's
/// namespace prefix -- is what "declared by prelude X" means here.
///
/// A label in [`DEPENDS_ON`] with no matching entry in `groups` is skipped
/// rather than an error: [`cross_prelude_declaration_names_are_disjoint`]
/// always passes the full [`build_groups`] output (every label present), but
/// the negative control below deliberately runs this over a partial `groups`
/// (only `logic`/`nat`/`axreal`) to keep the injected-collision test cheap,
/// and that must not be treated as `build_groups` missing a prelude.
///
/// # Panics
///
/// Panics if a label present in `groups` names a dependency (via
/// [`DEPENDS_ON`]) that is absent from `groups` -- an inconsistent `groups`
/// value, never a data condition.
fn own_declarations(groups: &[Group]) -> BTreeMap<&'static str, BTreeSet<String>> {
    let by_label: BTreeMap<&str, &BTreeSet<String>> =
        groups.iter().map(|g| (g.label, &g.all)).collect();
    let mut own = BTreeMap::new();
    for &(label, dep) in DEPENDS_ON {
        let Some(&all) = by_label.get(label) else {
            continue;
        };
        let names = match dep {
            None => all.clone(),
            Some(dep_label) => {
                let dep_all = *by_label.get(dep_label).unwrap_or_else(|| {
                    panic!("{label:?} is present but its dependency {dep_label:?} is not")
                });
                all.difference(dep_all).cloned().collect()
            }
        };
        own.insert(label, names);
    }
    own
}

/// Every name introduced by more than one prelude, each paired with the full
/// list of preludes that introduce it (deterministic order: alphabetical by
/// label, from the `BTreeSet` this is built over -- NOT a claim about which
/// declaration is chronologically newer; see [`collision_report`] for why
/// this function does not attempt to guess that).
fn cross_prelude_collisions(
    own: &BTreeMap<&'static str, BTreeSet<String>>,
) -> Vec<(String, Vec<&'static str>)> {
    let mut owners: BTreeMap<String, Vec<&'static str>> = BTreeMap::new();
    for (&label, names) in own {
        for name in names {
            owners.entry(name.clone()).or_default().push(label);
        }
    }
    owners
        .into_iter()
        .filter(|(_, labels)| labels.len() > 1)
        .collect()
}

/// Render [`cross_prelude_collisions`]'s findings as the failure message a
/// lane can act on: the exact string, and every prelude that declares it.
fn collision_report(collisions: &[(String, Vec<&'static str>)]) -> String {
    let mut lines: Vec<String> = collisions
        .iter()
        .map(|(name, owners)| format!("  {name}  <- declared by: {}", owners.join(", ")))
        .collect();
    lines.sort();
    format!(
        "cross-prelude declaration-name collision(s): the name(s) below are each \
         introduced by MORE THAN ONE prelude module. Building both preludes into \
         one kernel (e.g. `build_int_model_of_arith`, or any future combiner) hits \
         `KernelError::DeclarationExists` on whichever is admitted second -- often \
         far from either declaring site, and reported only as an opaque interned \
         id with no string and no owning prelude attached. \
         Rename whichever of the two conflicting declarations is the more recent \
         addition (check `git log -p` on each declaring site) -- the older one may \
         already be load-bearing elsewhere, which is exactly what made the \
         `Nat.inverseIndex` collision this gate is named for expensive to diagnose:\n{}",
        lines.join("\n")
    )
}

/// **The gate.** Every prelude this crate ships must introduce a disjoint set
/// of declaration names. See the module doc for the incident this replaces
/// and why "introduces" is computed by diffing against each prelude's
/// dependency rather than by namespace prefix.
#[test]
fn cross_prelude_declaration_names_are_disjoint() {
    // `build_groups` builds `complex` and `cpoint`, and both overflow the
    // default 2 MiB test-thread stack in a DEBUG build (same reason
    // `complex_tests.rs`/`creal_point_tests.rs` run on a deep-stack thread: the
    // recursion is in the kernel's own type checker over a genuinely large
    // term, not a bug). Without this, `cargo test -p axeyum-lean-kernel --lib`
    // (the ordinary, debug-mode sweep every lane runs) aborts the whole test
    // binary with SIGABRT before any assertion here -- or anywhere else in the
    // same binary -- runs.
    let groups = on_a_deep_stack(build_groups);
    let own = own_declarations(&groups);
    let collisions = cross_prelude_collisions(&own);
    assert!(collisions.is_empty(), "{}", collision_report(&collisions));
}

// --------------------------------------------------------------------------
// The ownership-derived inventory gate.
//
// # The deficiency this closes
//
// Every prelude in this crate has an "every X is checked and axiom-free" test,
// and each was fixed once already: `creal_tests.rs`'s version looped over a
// hand-maintained array, its name promised *every* `CReal` declaration, and one
// assertion against `kernel.environment()` found TWELVE unchecked declarations
// -- seven of them long-standing, including the whole Bishop-completeness
// `limit` family. `nat`, `integer`, `rat`, `complex` and `cpoint` all grew the
// same environment-derived `unlisted` assertion afterwards.
//
// **They all filter the environment by NAMESPACE PREFIX**, and that prefix is
// itself a hand-written literal. So the fix stopped one level short of the rule
// it was applied for: a declaration a prelude introduces OUTSIDE its own
// namespace is invisible to its own completeness guard, and adding a new one is
// invisible too. Measured 2026-08-31 over all ten preludes, 27 introduced
// `Definition`/`Theorem` declarations sit outside their introducing prelude's
// filter:
//
// - `nat` introduces `Max.max`, `Min.min`, `Squarefree`, `instMinNat` --
//   `every_nat_declaration_is_checked_and_axiom_free` filters `Nat.`, and its
//   per-declaration loop `continue`s past all four.
// - `cpoint` introduces `CReal.add_right_cancel` -- `CPoint`-filtered there,
//   and `creal`'s own guard cannot see it because `creal` never declares it.
// - `characterization` introduces `Nat.Peano.iter` and
//   `Int.Characterization.iter`, the two `Definition`s in that package;
//   `the_characterization_package_builds_and_every_witness_is_axiom_free`
//   iterates `package.entries`, which is 32 THEOREMS.
// - `integer` introduces 14 `Nat.*` (Wilson/Bezout) and 8 `Rat.*` names. Those
//   are the only ones already covered across a namespace boundary, by
//   `nat_namespace_declarations_made_by_the_int_prelude_are_axiom_free` and by
//   `rat`'s own guard respectively.
//
// This file already computes the authority-derived answer to "which prelude
// introduced this name" -- [`own_declarations`], by diffing against the
// dependency in [`DEPENDS_ON`], written for the collision gate. The gate below
// reuses it, so no prelude, module or file has to know what it owns and no
// namespace string appears anywhere in the check.
//
// # Why NOT a per-file owned-prefix set
//
// The obvious alternative -- give `rat_prelude/matrix_det.rs` an owned-prefix
// set (`Rat.det`, `Rat.mat`, `Rat.altSign`) and assert it exhaustive -- makes
// the prefix list the hand-maintained literal instead of the name list. It is
// the same defect one level up, and it fails in the direction that reads as
// safe: a declaration matching no owned prefix is silently owned by nobody.
// Recovering the declaring FILE mechanically is not available either -- the
// `Kernel` stores name/type/value/kind and no provenance, and scanning Rust
// source for `declare_*` sites was measured at 76.7% attribution (57.3% with
// 628 ambiguities once `.lemma` is counted, because `.lemma` builds a term
// reference rather than a declaration). Prelude granularity is what the kernel
// can actually answer, and it is enough: every declaration belongs to exactly
// one prelude's introduced set, by construction.
// --------------------------------------------------------------------------

/// The preludes allowed to introduce a declaration admitted WITHOUT a checked
/// proof body (`Axiom`/`Opaque`/`Quotient`), and how many.
///
/// `axreal` is the legacy AXIOMATIZED ordered field and its 30 axioms are the
/// point of it -- an opaque carrier makes every operation and law unavoidably
/// assumed, so 30 is a floor rather than a choice (ADR-0509/ADR-0515). It is
/// this repository's only nonzero row; `logic`, `nat`, `integer`,
/// `characterization`, `rat`, `string`, `creal`, `complex` and `cpoint` each
/// measure zero, which is the headline claim this gate now checks from the
/// authority rather than from any list.
///
/// The count is exact, not a ceiling: an axiom LEAVING `axreal` is as much a
/// change to the trusted base as one arriving, and a `>=` here would hide it.
const ASSUMED_BY: &[(&str, usize)] = &[("axreal", 30)];

/// Non-vacuity floor for [`inventory_report`]'s `checked` count.
///
/// Measured 2026-08-31: 2,576 `Definition`/`Theorem` declarations across the
/// ten preludes (`logic` 43, `nat` 902, `axreal` 0, `integer` 311,
/// `characterization` 34, `rat` 360, `string` 86, `creal` 580, `complex` 146,
/// `cpoint` 114). A floor rather than a pin, so ordinary growth never touches
/// it -- but a `build_groups` that silently stopped building preludes, or an
/// `own_declarations` diff that started returning empty sets, could not pass.
const CHECKED_FLOOR: usize = 2_000;

/// What [`inventory_report`] found. Every field is derived from the
/// environments in `groups`; nothing here is read from a literal name list.
#[derive(Debug, Default)]
struct Inventory {
    /// `(label, checked, structural, trusted)` for each prelude, in
    /// [`DEPENDS_ON`] order -- printed so a passing run states its coverage
    /// instead of asserting it silently.
    per_label: Vec<(&'static str, usize, usize, usize)>,
    /// Total introduced `Definition`/`Theorem` declarations across all
    /// preludes.
    checked: usize,
    /// Introduced declarations whose proof reaches something assumed, as
    /// `"<label>: <name> rests on [..]"`.
    resting_on_axioms: Vec<String>,
    /// Introduced `Axiom`/`Opaque`/`Quotient` names in a prelude that
    /// [`ASSUMED_BY`] does not license, as `"<label>: <name>"`.
    unexpected_trusted: Vec<String>,
    /// Preludes whose introduced trusted count disagrees with [`ASSUMED_BY`].
    trusted_count_moved: Vec<String>,
    /// Preludes whose environment carries nothing trusted, so every footprint
    /// in them is empty by construction rather than by measurement (see
    /// [`Group`]'s type doc). Recorded, not assumed.
    axiom_free_environments: Vec<&'static str>,
    /// **The exhaustiveness finding.** A declaration present in some prelude's
    /// environment that NO prelude on that prelude's own [`DEPENDS_ON`] chain
    /// introduces -- i.e. one this gate inspected under no owner at all.
    ///
    /// The partition is exhaustive by construction (every chain bottoms out at
    /// `logic`, whose dependency is `None`, so its introduced set is its whole
    /// environment), but "by construction" is exactly the kind of reasoning
    /// this file exists to distrust: a `DEPENDS_ON` edge pointing at something
    /// that is not an ancestor would silently leave a hole, and the gate would
    /// still print a large, reassuring `checked` count. Recorded as
    /// `"<label>: <name>"`.
    unattributed: Vec<String>,
    /// A declaration introduced by more than one prelude on one chain. Cannot
    /// happen for a linear diff, and is checked rather than assumed for the
    /// same reason as [`Inventory::unattributed`].
    doubly_attributed: Vec<String>,
}

/// The `label`, its dependency, its dependency's dependency, ... down to the
/// base of [`DEPENDS_ON`]. Every declaration in `label`'s environment must be
/// introduced by exactly one member.
fn dependency_chain(label: &'static str) -> Vec<&'static str> {
    let dep_of: BTreeMap<&str, Option<&'static str>> = DEPENDS_ON.iter().copied().collect();
    let mut chain = vec![label];
    let mut cursor = label;
    while let Some(Some(dep)) = dep_of.get(cursor) {
        chain.push(dep);
        cursor = dep;
    }
    chain
}

/// Walk every prelude's INTRODUCED declaration set and report what is there.
///
/// Split out of the test so the negative controls can drive the identical code
/// over deliberately mutated kernels: a guard only asserted inside a `#[test]`
/// body is a guard no control can reach.
fn inventory_report(groups: &[Group], own: &BTreeMap<&'static str, BTreeSet<String>>) -> Inventory {
    let by_label: BTreeMap<&str, &Group> = groups.iter().map(|g| (g.label, g)).collect();
    let mut report = Inventory::default();
    for &(label, _) in DEPENDS_ON {
        let (Some(group), Some(names)) = (by_label.get(label), own.get(label)) else {
            // Not in this `groups` value. `own_declarations` skips such labels
            // for the same reason -- the controls below run over a partial set
            // deliberately, and that must not read as a missing prelude.
            continue;
        };
        if !group.any_trusted() {
            report.axiom_free_environments.push(label);
        }
        let allowed = ASSUMED_BY
            .iter()
            .find(|(l, _)| *l == label)
            .map_or(0, |(_, n)| *n);
        let (mut checked, mut structural, mut trusted) = (0usize, 0usize, 0usize);
        for name in names {
            match group.kinds.get(name) {
                Some(DeclKind::Checked) => {
                    checked += 1;
                    // Empty by construction when the environment holds nothing
                    // trusted; measured per declaration the moment it does.
                    if let Some(footprint) = group.footprints.get(name)
                        && !footprint.is_empty()
                    {
                        report
                            .resting_on_axioms
                            .push(format!("{label}: {name} rests on {footprint:?}"));
                    }
                }
                Some(DeclKind::Structural) => structural += 1,
                Some(DeclKind::Trusted) => {
                    trusted += 1;
                    if allowed == 0 {
                        report.unexpected_trusted.push(format!("{label}: {name}"));
                    }
                }
                None => {
                    unreachable!("{label} introduces {name}, which is not in its own environment")
                }
            }
        }
        if trusted != allowed {
            report.trusted_count_moved.push(format!(
                "{label} introduces {trusted} trusted declaration(s), ASSUMED_BY says {allowed}"
            ));
        }
        report.checked += checked;
        report.per_label.push((label, checked, structural, trusted));

        // EXHAUSTIVENESS. Everything in this prelude's environment must be
        // introduced by exactly one prelude on its own dependency chain, or
        // this gate inspected it under no owner and its large `checked` count
        // would be describing a partial partition.
        for name in &group.all {
            let owners: Vec<&'static str> = dependency_chain(label)
                .into_iter()
                .filter(|l| own.get(l).is_some_and(|names| names.contains(name)))
                .collect();
            match owners.len() {
                1 => {}
                0 => {
                    // Only a real hole when every chain member was built; a
                    // partial `groups` (the controls) legitimately omits some.
                    if dependency_chain(label).iter().all(|l| own.contains_key(l)) {
                        report.unattributed.push(format!("{label}: {name}"));
                    }
                }
                _ => report
                    .doubly_attributed
                    .push(format!("{label}: {name} introduced by {owners:?}")),
            }
        }
    }
    report
}

/// **The inventory gate.** Every declaration each prelude INTRODUCES is
/// admitted with a checked proof body and rests on no axiom -- with ownership
/// derived from the build-order diff, so no namespace prefix and no
/// hand-maintained name list stands between the environment and the assertion.
///
/// See the block comment above for the 27 declarations the namespace-filtered
/// per-prelude guards structurally cannot reach, and why per-file ownership was
/// not the mechanism chosen.
#[test]
fn every_declaration_a_prelude_introduces_is_checked_and_axiom_free() {
    // Same deep stack `cross_prelude_declaration_names_are_disjoint` needs, and
    // for the same reason: `build_groups` builds `complex` and `cpoint`, whose
    // type-checking recursion overflows the default 2 MiB test-thread stack in
    // a debug build and would abort the WHOLE test binary.
    let groups = on_a_deep_stack(build_groups);
    let own = own_declarations(&groups);
    let report = inventory_report(&groups, &own);

    // A passing run states its coverage rather than asserting it silently.
    for (label, checked, structural, trusted) in &report.per_label {
        println!(
            "introduced by {label}: {checked} checked, {structural} structural, \
             {trusted} trusted"
        );
    }
    println!(
        "environments with nothing assumed anywhere: {:?}",
        report.axiom_free_environments
    );

    // Coverage, both directions: every prelude in the dependency chain must
    // have been built AND diffed, and the population must be the real one.
    let seen: BTreeSet<&str> = report.per_label.iter().map(|(l, ..)| *l).collect();
    let missing: Vec<&str> = DEPENDS_ON
        .iter()
        .map(|(l, _)| *l)
        .filter(|l| !seen.contains(l))
        .collect();
    assert!(
        missing.is_empty(),
        "these preludes are in DEPENDS_ON but were never built or never diffed, \
         so this gate says nothing about them: {missing:?}"
    );
    assert!(
        report.checked >= CHECKED_FLOOR,
        "only {} introduced definitions/theorems were inspected, below the {CHECKED_FLOOR} \
         floor -- `build_groups` or the `own_declarations` diff has stopped \
         covering the tree, and a passing run would prove nothing",
        report.checked
    );

    assert!(
        report.unexpected_trusted.is_empty(),
        "these declarations were admitted WITHOUT a checked proof body by a \
         prelude that ASSUMED_BY does not license: {:?}. Every prelude but \
         `axreal` measures zero, and that is the headline claim -- if this is \
         deliberate, ADR it and add the prelude to ASSUMED_BY.",
        report.unexpected_trusted
    );
    assert!(
        report.trusted_count_moved.is_empty(),
        "the assumed surface moved: {:?}. ASSUMED_BY is exact in both \
         directions -- an axiom leaving `axreal` changes the trusted base as \
         much as one arriving.",
        report.trusted_count_moved
    );
    assert!(
        report.resting_on_axioms.is_empty(),
        "these introduced declarations rest on something assumed: {:?}",
        report.resting_on_axioms
    );

    // The partition really is exhaustive -- asserted, not argued. Without this
    // a wrong `DEPENDS_ON` edge would leave declarations owned by nobody while
    // the counts above stayed large and reassuring.
    assert!(
        report.unattributed.is_empty(),
        "these declarations are in a prelude's environment but introduced by no \
         prelude on its dependency chain, so this gate checked them under no \
         owner: {:?}. A DEPENDS_ON edge is pointing somewhere that is not an \
         ancestor.",
        report.unattributed
    );
    assert!(
        report.doubly_attributed.is_empty(),
        "these declarations are introduced by more than one prelude on one \
         chain, which a set difference cannot produce: {:?}",
        report.doubly_attributed
    );
}

#[cfg(test)]
mod negative_control {
    use super::{
        Declaration, Group, Kernel, build_arith_prelude, build_nat_prelude,
        cross_prelude_collisions, own_declarations,
    };

    /// Declare one throwaway `AxReal.__collision_probe : True` axiom into
    /// `kernel`, reusing whatever `True` that kernel's own logic prelude
    /// declared. A real declaration through the real trusted gate
    /// (`Kernel::add_declaration`), not a string fixture -- this is genuinely
    /// indistinguishable, from the gate's point of view, from two prelude
    /// modules that happen to pick the same name for two different things.
    fn inject_collision_probe(kernel: &mut Kernel, true_: crate::NameId) {
        let anon = kernel.anon();
        let ns = kernel.name_str(anon, "AxReal");
        let probe = kernel.name_str(ns, "__collision_probe");
        let true_ty = kernel.const_(true_, vec![]);
        kernel
            .add_declaration(Declaration::Axiom {
                name: probe,
                uparams: vec![],
                ty: true_ty,
            })
            .expect(
                "injecting the probe axiom must itself succeed (fresh name, no real clash yet)",
            );
    }

    /// **The negative control.** Build `nat` and `axreal` for real, then
    /// inject the SAME name into both independently -- through the real
    /// trusted gate, not a synthetic map -- and confirm
    /// [`cross_prelude_collisions`] catches it. Also confirms directly that
    /// combining the two mutated kernels for real hits
    /// `KernelError::DeclarationExists`, and NOT the message this gate emits
    /// -- i.e. that the gate's job is to pre-empt exactly that failure mode
    /// with something a lane can act on.
    #[test]
    fn cross_prelude_collision_is_detected_and_named() {
        let mut nat = Kernel::new();
        let nat_prelude = build_nat_prelude(&mut nat).expect("Nat prelude must build");
        inject_collision_probe(&mut nat, nat_prelude.logic.true_);

        let mut axreal = Kernel::new();
        let axreal_prelude = build_arith_prelude(&mut axreal).expect("AxReal prelude must build");
        inject_collision_probe(&mut axreal, axreal_prelude.logic.true_);

        // Run the real pipeline (`build_groups` + diff), with these two
        // mutated kernels swapped in for the pristine ones.
        let groups = vec![
            Group::of("logic", &{
                let mut logic = Kernel::new();
                crate::build_logic_prelude(&mut logic).expect("logic prelude must build");
                logic
            }),
            Group::of("nat", &nat),
            Group::of("axreal", &axreal),
        ];
        let own = own_declarations(&groups);
        let collisions = cross_prelude_collisions(&own);

        assert_eq!(
            collisions.len(),
            1,
            "expected exactly one injected collision, found {collisions:?}"
        );
        let (name, owners) = &collisions[0];
        assert_eq!(name, "AxReal.__collision_probe");
        assert_eq!(owners, &vec!["axreal", "nat"]);

        let report = super::collision_report(&collisions);
        assert!(
            report.contains("AxReal.__collision_probe"),
            "gate message must name the colliding string:\n{report}"
        );
        assert!(
            report.contains("nat") && report.contains("axreal"),
            "gate message must name both declaring preludes:\n{report}"
        );
        // The report is allowed to MENTION `KernelError::DeclarationExists`
        // (it does, explaining what this gate pre-empts) -- what it must never
        // do is degrade to the raw, unreadable form the incident actually hit:
        // an opaque interned id with no string and no owning prelude attached.
        assert!(
            !report.contains("NameId("),
            "the gate's OWN failure message must never regress to the raw \
             `NameId(<n>)` form it exists to replace:\n{report}"
        );

        // And: confirm the failure mode this gate replaces really does occur.
        // Combine the two mutated trees into ONE kernel for real (`nat` first,
        // then `axreal`'s declarations replayed on top) and check the SECOND
        // admission of the probe is rejected as `DeclarationExists` -- the raw,
        // unnamed failure the incident this module documents actually hit.
        let mut combined = Kernel::new();
        let combined_nat = build_nat_prelude(&mut combined).expect("Nat prelude must build");
        inject_collision_probe(&mut combined, combined_nat.logic.true_);
        let anon = combined.anon();
        let ns = combined.name_str(anon, "AxReal");
        let probe = combined.name_str(ns, "__collision_probe");
        let true_ty = combined.const_(combined_nat.logic.true_, vec![]);
        let second_admission = combined.add_declaration(Declaration::Axiom {
            name: probe,
            uparams: vec![],
            ty: true_ty,
        });
        assert!(
            matches!(
                second_admission,
                Err(crate::KernelError::DeclarationExists { .. })
            ),
            "expected the raw kernel error this gate pre-empts, got {second_admission:?}"
        );
    }
}

/// Negative controls for [`every_declaration_a_prelude_introduces_is_checked_and_axiom_free`].
///
/// Both drive the REAL [`inventory_report`] over kernels mutated through the
/// REAL trusted gate (`Kernel::add_declaration`), never over a synthetic map --
/// so a guard that stopped looking at the environment would fail here.
///
/// They are deliberately cheap: `logic` + `nat` only, no `creal`/`complex`/
/// `cpoint`, so the mutation harness can run them in seconds rather than paying
/// the ten-prelude build the gate itself needs.
#[cfg(test)]
mod inventory_control {
    use std::collections::BTreeMap;

    use super::{
        Declaration, Group, Kernel, build_nat_prelude, inventory_report, own_declarations,
    };

    /// `nat` and `logic`, with `nat` carrying whatever `mutate` adds. Returns
    /// the groups in the order [`super::DEPENDS_ON`] expects.
    fn groups_with_mutated_nat(mutate: impl FnOnce(&mut Kernel, crate::NameId)) -> Vec<Group> {
        let mut logic = Kernel::new();
        crate::build_logic_prelude(&mut logic).expect("logic prelude must build");

        let mut nat = Kernel::new();
        let prelude = build_nat_prelude(&mut nat).expect("Nat prelude must build");
        mutate(&mut nat, prelude.logic.true_);

        vec![Group::of("logic", &logic), Group::of("nat", &nat)]
    }

    /// Declare `Nat.__probe_axiom : True` -- an admission with no checked proof
    /// body, indistinguishable from a real one at the gate.
    fn inject_axiom(kernel: &mut Kernel, true_: crate::NameId) -> crate::NameId {
        let anon = kernel.anon();
        let ns = kernel.name_str(anon, "Nat");
        let probe = kernel.name_str(ns, "__probe_axiom");
        let true_ty = kernel.const_(true_, vec![]);
        kernel
            .add_declaration(Declaration::Axiom {
                name: probe,
                uparams: vec![],
                ty: true_ty,
            })
            .expect("the probe axiom must be admitted");
        probe
    }

    /// A prelude that introduces something admitted without a checked proof
    /// body is named, with its prelude.
    #[test]
    fn an_introduced_axiom_is_reported_as_unexpectedly_trusted() {
        let clean = groups_with_mutated_nat(|_, _| {});
        let clean_report = inventory_report(&clean, &own_declarations(&clean));
        assert!(
            clean_report.unexpected_trusted.is_empty(),
            "the UNMUTATED baseline must be clean, or the control below proves \
             nothing: {:?}",
            clean_report.unexpected_trusted
        );
        assert!(
            clean_report.checked > 0,
            "the baseline must actually inspect declarations"
        );
        assert!(
            clean_report.axiom_free_environments.contains(&"nat"),
            "the clean `nat` environment carries nothing trusted, which is what \
             makes its footprints empty by construction"
        );

        let groups = groups_with_mutated_nat(|k, t| {
            inject_axiom(k, t);
        });
        let report = inventory_report(&groups, &own_declarations(&groups));
        assert_eq!(
            report.unexpected_trusted,
            vec!["nat: Nat.__probe_axiom".to_string()],
            "the injected axiom must be named with its introducing prelude"
        );
        assert!(
            !report.axiom_free_environments.contains(&"nat"),
            "an environment holding an axiom must no longer be recorded as \
             carrying nothing trusted -- that record is what licenses skipping \
             the per-declaration footprints"
        );
    }

    /// A theorem whose proof reaches an injected axiom is named, with the axiom
    /// it rests on. This is the guard that would be vacuous if the conditional
    /// footprint computation ever stopped firing.
    #[test]
    fn a_theorem_resting_on_an_injected_axiom_is_reported() {
        let groups = groups_with_mutated_nat(|k, true_| {
            let axiom = inject_axiom(k, true_);
            let anon = k.anon();
            let ns = k.name_str(anon, "Nat");
            let thm = k.name_str(ns, "__probe_theorem");
            let true_ty = k.const_(true_, vec![]);
            let proof = k.const_(axiom, vec![]);
            k.add_declaration(Declaration::Theorem {
                name: thm,
                uparams: vec![],
                ty: true_ty,
                value: proof,
            })
            .expect("the probe theorem must type-check against the probe axiom");
        });
        let report = inventory_report(&groups, &own_declarations(&groups));
        assert_eq!(
            report.resting_on_axioms.len(),
            1,
            "expected exactly the injected theorem, found {:?}",
            report.resting_on_axioms
        );
        let found = &report.resting_on_axioms[0];
        assert!(
            found.contains("Nat.__probe_theorem") && found.contains("Nat.__probe_axiom"),
            "the report must name BOTH the resting declaration and what it \
             rests on: {found}"
        );
        assert!(
            found.starts_with("nat:"),
            "the report must name the INTRODUCING prelude: {found}"
        );
    }

    /// The count is exact in both directions: an axiom LEAVING a prelude that
    /// [`super::ASSUMED_BY`] licenses is as much a change to the trusted base
    /// as one arriving, and a `>=` comparison would not see it.
    #[test]
    fn a_licensed_prelude_that_sheds_an_axiom_is_reported() {
        // `nat` is not in `ASSUMED_BY`, so the licensed count for it is 0 and a
        // single injected axiom is a one-off move. The same arithmetic is what
        // catches `axreal` dropping from 30.
        let groups = groups_with_mutated_nat(|k, t| {
            inject_axiom(k, t);
        });
        let report = inventory_report(&groups, &own_declarations(&groups));
        assert_eq!(
            report.trusted_count_moved.len(),
            1,
            "expected the moved-count guard to fire once, found {:?}",
            report.trusted_count_moved
        );
        assert!(
            report.trusted_count_moved[0].contains("nat introduces 1 trusted"),
            "the message must say which prelude and how many: {:?}",
            report.trusted_count_moved
        );
    }

    /// A prelude present in `groups` but absent from the diff -- or the other
    /// way round -- must not silently read as "checked". The gate asserts every
    /// [`super::DEPENDS_ON`] label appears in `per_label`; this pins that
    /// `inventory_report` really does omit a label it was not given, so that
    /// assertion has something to catch.
    #[test]
    fn a_prelude_absent_from_the_groups_is_absent_from_the_report() {
        let groups = groups_with_mutated_nat(|_, _| {});
        let report = inventory_report(&groups, &own_declarations(&groups));
        let labels: Vec<&str> = report.per_label.iter().map(|(l, ..)| *l).collect();
        assert_eq!(
            labels,
            vec!["logic", "nat"],
            "only the preludes actually built may appear"
        );
        let by_label: BTreeMap<&str, usize> = report
            .per_label
            .iter()
            .map(|(l, checked, ..)| (*l, *checked))
            .collect();
        assert!(
            by_label["nat"] > 100,
            "the `nat` diff must be the real introduced set, found {}",
            by_label["nat"]
        );
    }

    /// A declaration owned by nobody is NAMED, rather than quietly dropped
    /// while the `checked` count stays large.
    ///
    /// The hole is injected into the ownership map, which is what a wrong
    /// `DEPENDS_ON` edge produces: `own_declarations` returns a set difference,
    /// so the only way to reach this state for real is an edge pointing at
    /// something that is not an ancestor -- and that is unreachable from a
    /// two-prelude fixture, which is exactly why the guard needs a control.
    #[test]
    fn a_declaration_no_prelude_introduces_is_reported() {
        let groups = groups_with_mutated_nat(|_, _| {});
        let honest = own_declarations(&groups);
        let baseline = inventory_report(&groups, &honest);
        assert!(
            baseline.unattributed.is_empty() && baseline.doubly_attributed.is_empty(),
            "the UNMUTATED partition must be exhaustive, or the control proves \
             nothing: {:?} / {:?}",
            baseline.unattributed,
            baseline.doubly_attributed
        );

        let mut holed = honest.clone();
        let dropped = holed
            .get_mut("nat")
            .expect("nat is in the diff")
            .iter()
            .next()
            .expect("nat introduces something")
            .clone();
        holed
            .get_mut("nat")
            .expect("nat is in the diff")
            .remove(&dropped);
        let report = inventory_report(&groups, &holed);
        assert_eq!(
            report.unattributed,
            vec![format!("nat: {dropped}")],
            "the orphaned declaration must be named with the environment it was \
             found in"
        );

        // And the opposite hole: a name claimed by two preludes on one chain.
        // Take one `logic` INTRODUCES and let `nat` claim it too -- `nat`'s
        // environment really does contain it (`nat` builds `logic` first), so
        // this is a double claim rather than a claim about a name nobody has.
        let mut doubled = honest.clone();
        let shared = honest["logic"]
            .iter()
            .next()
            .expect("logic introduces something")
            .clone();
        doubled
            .get_mut("nat")
            .expect("nat is in the diff")
            .insert(shared.clone());
        let report = inventory_report(&groups, &doubled);
        assert!(
            report
                .doubly_attributed
                .iter()
                .any(|row| row.contains(&shared)),
            "a name introduced by two preludes on one chain must be named: {:?}",
            report.doubly_attributed
        );
    }
}
