//! Render kernel terms to Lean 4 source syntax — a readable, externally-checkable
//! projection of the in-tree kernel's `Expr`/`Name`/`Level`.
//!
//! This is the first slice of a full Lean export: it renders proof *terms* (the
//! trusted-checking witnesses produced by `axeyum-solver`'s reconstruction) into
//! the surface syntax a real Lean 4 kernel reads, so a refutation the in-tree
//! [`Kernel`](crate::Kernel) accepts can also be inspected, diffed, and (with the
//! declaration prelude, a later slice) re-checked by an independent Lean toolchain.
//! It is pure pretty-printing — it never affects type checking.

use std::fmt::Write as _;

use crate::{Declaration, ExprId, ExprNode, Kernel, LevelId, LevelNode, Lit, NameId, NameNode};

impl Kernel {
    /// Render `expr` as a Lean 4 source string. De Bruijn variables are resolved to
    /// their binder names (anonymous binders get generated `x<depth>` names); the
    /// output is parenthesized enough to re-parse with Lean's standard precedence.
    #[must_use]
    pub fn render_lean(&self, expr: ExprId) -> String {
        let mut binders: Vec<String> = Vec::new();
        self.render_expr(expr, &mut binders)
    }

    /// Render a [`Declaration`] as a Lean 4 top-level command. The directly-emittable
    /// kinds (`axiom`/`def`/`theorem`/`opaque`) render verbatim; an
    /// `Inductive`/`Constructor`/`Recursor` renders as a comment, since Lean
    /// regenerates those from a single `inductive` command (a later export slice).
    #[must_use]
    pub fn render_lean_decl(&self, decl: &Declaration) -> String {
        match decl {
            Declaration::Axiom { name, uparams, ty } => format!(
                "axiom {}{} : {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty)
            ),
            Declaration::Definition {
                name,
                uparams,
                ty,
                value,
                ..
            } => format!(
                "def {}{} : {} :=\n  {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty),
                self.render_lean(*value)
            ),
            Declaration::Theorem {
                name,
                uparams,
                ty,
                value,
            } => format!(
                "theorem {}{} : {} :=\n  {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty),
                self.render_lean(*value)
            ),
            Declaration::Opaque {
                name,
                uparams,
                ty,
                value,
            } => format!(
                "opaque {}{} : {} :=\n  {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty),
                self.render_lean(*value)
            ),
            Declaration::Inductive { name, .. }
            | Declaration::Constructor { name, .. }
            | Declaration::Recursor { name, .. } => format!(
                "-- `{}` is regenerated by Lean's `inductive` command (export slice TODO)",
                self.render_name(*name)
            ),
        }
    }

    /// Render a **self-contained Lean 4 module** that re-checks a reconstructed
    /// refutation: every environment declaration reachable from `goal`/`proof`,
    /// in dependency order, followed by `theorem <theorem_name> : <goal> := <proof>`
    /// and a `#print axioms <theorem_name>` audit command.
    ///
    /// The module opens with `prelude` (no `import Init`), so the re-declared
    /// logical constants (`True`/`False`/`And`/`Eq`/…) do not clash with Lean's
    /// core: it is checked against *axeyum's own* declarations, exactly the
    /// obligation the in-tree [`Kernel`] discharged. Inductives, their
    /// constructors, and their generated recursors are emitted as `axiom`s carrying
    /// the kernel's stored types (so Lean re-checks the proof term against those
    /// signatures); definitions/theorems/opaques and the uninterpreted/`em` axioms
    /// render verbatim. A real `lean` binary that accepts this module — and reports
    /// (via `#print axioms`) only the expected uninterpreted/`em`/`propext`-class
    /// axioms — independently confirms the refutation.
    ///
    /// `theorem_name` must be a valid Lean identifier (e.g. `axeyum_refutation`).
    #[must_use]
    pub fn render_lean_module(&self, theorem_name: &str, goal: ExprId, proof: ExprId) -> String {
        let order = self.reachable_decl_order(&[goal, proof]);
        let mut out = String::from(
            "-- Auto-generated by axeyum-lean-kernel: a self-contained re-check of a\n\
             -- reconstructed refutation. `prelude` avoids clashing with Lean core.\n\
             prelude\n\
             set_option linter.unusedVariables false\n\n",
        );
        for name in &order {
            if let Some(decl) = self.environment().get(*name) {
                out.push_str(&self.render_decl_command(decl));
                out.push('\n');
            }
        }
        let _ = write!(
            out,
            "\ntheorem {theorem_name} : {} :=\n  {}\n\n#print axioms {theorem_name}\n",
            self.render_lean(goal),
            self.render_lean(proof)
        );
        out
    }

    /// Render a declaration as a self-contained `prelude`-mode command: inductives,
    /// constructors, and recursors become `axiom`s (carrying their kernel type),
    /// since `prelude` mode has no `inductive`-generated recursors to rely on; all
    /// other kinds render through [`Self::render_lean_decl`].
    fn render_decl_command(&self, decl: &Declaration) -> String {
        match decl {
            Declaration::Inductive {
                name, uparams, ty, ..
            }
            | Declaration::Constructor {
                name, uparams, ty, ..
            }
            | Declaration::Recursor {
                name, uparams, ty, ..
            } => format!(
                "axiom {}{} : {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty)
            ),
            _ => self.render_lean_decl(decl),
        }
    }

    /// The environment declarations reachable from `roots` (transitively through
    /// each declaration's type and — for definitions/theorems/opaques — value),
    /// in dependency order (a declaration appears after every declaration it
    /// references). Names not present in the environment are skipped.
    fn reachable_decl_order(&self, roots: &[ExprId]) -> Vec<NameId> {
        // Reachability closure over constant references.
        let mut needed: std::collections::BTreeSet<NameId> = std::collections::BTreeSet::new();
        let mut work: Vec<NameId> = Vec::new();
        let mut seed = Vec::new();
        for &r in roots {
            self.collect_const_deps(r, &mut seed);
        }
        for n in seed {
            if needed.insert(n) {
                work.push(n);
            }
        }
        while let Some(n) = work.pop() {
            for d in self.decl_deps(n) {
                if needed.insert(d) {
                    work.push(d);
                }
            }
        }
        // Deterministic post-order DFS topological sort over the reachable set.
        let mut visited: std::collections::BTreeSet<NameId> = std::collections::BTreeSet::new();
        let mut order: Vec<NameId> = Vec::new();
        for &n in &needed {
            self.topo_visit(n, &needed, &mut visited, &mut order);
        }
        order
    }

    /// The constants a declaration references (in its type, plus its value for
    /// `Definition`/`Theorem`/`Opaque`).
    fn decl_deps(&self, name: NameId) -> Vec<NameId> {
        let mut deps = Vec::new();
        if let Some(decl) = self.environment().get(name) {
            self.collect_const_deps(decl.ty(), &mut deps);
            match decl {
                Declaration::Definition { value, .. }
                | Declaration::Theorem { value, .. }
                | Declaration::Opaque { value, .. } => {
                    self.collect_const_deps(*value, &mut deps);
                }
                _ => {}
            }
        }
        deps
    }

    fn topo_visit(
        &self,
        name: NameId,
        needed: &std::collections::BTreeSet<NameId>,
        visited: &mut std::collections::BTreeSet<NameId>,
        order: &mut Vec<NameId>,
    ) {
        if !visited.insert(name) {
            return;
        }
        for d in self.decl_deps(name) {
            if needed.contains(&d) {
                self.topo_visit(d, needed, visited, order);
            }
        }
        order.push(name);
    }

    /// Collect (iteratively, to avoid deep recursion on large proof terms) every
    /// `Const` name referenced anywhere inside `root`.
    fn collect_const_deps(&self, root: ExprId, out: &mut Vec<NameId>) {
        let mut stack = vec![root];
        while let Some(e) = stack.pop() {
            match self.expr_node(e) {
                ExprNode::Const(n, _) => out.push(*n),
                ExprNode::App(f, a) => {
                    stack.push(*f);
                    stack.push(*a);
                }
                ExprNode::Lam(_, t, b, _) | ExprNode::Pi(_, t, b, _) => {
                    stack.push(*t);
                    stack.push(*b);
                }
                ExprNode::Let(_, t, v, b) => {
                    stack.push(*t);
                    stack.push(*v);
                    stack.push(*b);
                }
                ExprNode::BVar(_) | ExprNode::FVar(_) | ExprNode::Sort(_) | ExprNode::Lit(_) => {}
            }
        }
    }

    /// The universe-parameter suffix `.{u, v}` for a declaration head (empty when
    /// the declaration is universe-monomorphic).
    fn render_uparams(&self, uparams: &[NameId]) -> String {
        if uparams.is_empty() {
            String::new()
        } else {
            let names: Vec<String> = uparams.iter().map(|n| self.render_name(*n)).collect();
            format!(".{{{}}}", names.join(", "))
        }
    }

    /// A hierarchical [`NameId`] as a dotted Lean name (`a.b.1`); the anonymous root
    /// renders empty.
    fn render_name(&self, id: NameId) -> String {
        match self.name_node(id) {
            NameNode::Anonymous => String::new(),
            NameNode::Str(parent, s) => {
                let p = self.render_name(*parent);
                if p.is_empty() {
                    s.clone()
                } else {
                    format!("{p}.{s}")
                }
            }
            NameNode::Num(parent, n) => {
                // A numeric name component is not a legal Lean identifier component
                // on its own (`foo.0` parses as projection); prefix it with `_` so
                // generated names like `axeyum.reconstruct.atom.0` export as the
                // valid hierarchical name `axeyum.reconstruct.atom._0`.
                let p = self.render_name(*parent);
                if p.is_empty() {
                    format!("_{n}")
                } else {
                    format!("{p}._{n}")
                }
            }
        }
    }

    /// A universe [`LevelId`] in Lean level syntax. A `Succ` chain over a base is
    /// collapsed into the `base+n` (or a bare numeral `n` when the base is `Zero`)
    /// form Lean's level grammar expects — e.g. `Sort 1` rather than `Sort (0+1)`.
    fn render_level(&self, id: LevelId) -> String {
        let mut offset: u32 = 0;
        let mut cur = id;
        while let LevelNode::Succ(l) = self.level_node(cur) {
            offset += 1;
            cur = *l;
        }
        let base = match self.level_node(cur) {
            LevelNode::Zero => return offset.to_string(),
            LevelNode::Param(n) => self.render_name(*n),
            LevelNode::Max(a, b) => {
                format!("(max {} {})", self.render_level(*a), self.render_level(*b))
            }
            LevelNode::IMax(a, b) => {
                format!("(imax {} {})", self.render_level(*a), self.render_level(*b))
            }
            LevelNode::Succ(_) => unreachable!("Succ chain already consumed"),
        };
        if offset == 0 {
            base
        } else {
            format!("{base}+{offset}")
        }
    }

    /// The binder name to print for a binder declared with [`NameId`] `name` opened
    /// at de Bruijn `depth`; anonymous binders become a generated `x<depth>`.
    fn binder_name(&self, name: NameId, depth: usize) -> String {
        let rendered = self.render_name(name);
        if rendered.is_empty() {
            format!("x{depth}")
        } else {
            rendered
        }
    }

    /// Render an expression, wrapping it in parentheses when it is a compound form
    /// (so it can sit as a function head or argument without re-association).
    fn render_expr_atom(&self, id: ExprId, binders: &mut Vec<String>) -> String {
        match self.expr_node(id) {
            ExprNode::BVar(_)
            | ExprNode::FVar(_)
            | ExprNode::Const(_, _)
            | ExprNode::Sort(_)
            | ExprNode::Lit(_) => self.render_expr(id, binders),
            ExprNode::App(_, _) | ExprNode::Lam(..) | ExprNode::Pi(..) | ExprNode::Let(..) => {
                format!("({})", self.render_expr(id, binders))
            }
        }
    }

    fn render_expr(&self, id: ExprId, binders: &mut Vec<String>) -> String {
        match self.expr_node(id) {
            ExprNode::BVar(i) => binders
                .len()
                .checked_sub(1 + *i as usize)
                .map_or_else(|| format!("#{i}"), |k| binders[k].clone()),
            ExprNode::FVar(fid) => format!("_fvar.{fid}"),
            ExprNode::Sort(l) => {
                let ls = self.render_level(*l);
                if ls == "0" {
                    "Prop".to_owned()
                } else {
                    format!("Sort ({ls})")
                }
            }
            ExprNode::Const(name, levels) => {
                let n = self.render_name(*name);
                if levels.is_empty() {
                    n
                } else {
                    let ls: Vec<String> = levels.iter().map(|l| self.render_level(*l)).collect();
                    format!("{n}.{{{}}}", ls.join(", "))
                }
            }
            ExprNode::App(f, a) => {
                let fs = self.render_expr_atom(*f, binders);
                let as_ = self.render_expr_atom(*a, binders);
                format!("{fs} {as_}")
            }
            ExprNode::Lam(name, ty, body, _) => {
                let bn = self.binder_name(*name, binders.len());
                let tys = self.render_expr(*ty, binders);
                binders.push(bn.clone());
                let bs = self.render_expr(*body, binders);
                binders.pop();
                format!("fun ({bn} : {tys}) => {bs}")
            }
            ExprNode::Pi(name, ty, body, _) => {
                let bn = self.binder_name(*name, binders.len());
                let tys = self.render_expr(*ty, binders);
                binders.push(bn.clone());
                let bs = self.render_expr(*body, binders);
                binders.pop();
                format!("(({bn} : {tys}) -> {bs})")
            }
            ExprNode::Let(name, ty, val, body) => {
                let bn = self.binder_name(*name, binders.len());
                let tys = self.render_expr(*ty, binders);
                let vs = self.render_expr(*val, binders);
                binders.push(bn.clone());
                let bs = self.render_expr(*body, binders);
                binders.pop();
                format!("let {bn} : {tys} := {vs}; {bs}")
            }
            ExprNode::Lit(Lit::Nat(n)) => n.to_string(),
            ExprNode::Lit(Lit::Str(s)) => format!("{s:?}"),
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::Kernel;

    /// `fun (p : Prop) => p` renders to readable Lean with the de Bruijn variable
    /// resolved to its binder name, and the round-trip parses structurally.
    #[test]
    fn renders_identity_on_prop() {
        let mut k = Kernel::new();
        let prop = {
            let zero = k.level_zero();
            k.sort(zero)
        };
        let anon = k.anon();
        let p = k.name_str(anon, "p");
        let body = k.bvar(0);
        let lam = k.lam(p, prop, body, crate::BinderInfo::Default);
        assert_eq!(k.render_lean(lam), "fun (p : Prop) => p");
    }

    /// A `Pi` (dependent arrow) and a nested application render with the binder name
    /// and parenthesized argument.
    #[test]
    fn renders_pi_and_application() {
        let mut k = Kernel::new();
        let prop = {
            let zero = k.level_zero();
            k.sort(zero)
        };
        let anon = k.anon();
        let a = k.name_str(anon, "a");
        // (a : Prop) -> a
        let body = k.bvar(0);
        let pi = k.pi(a, prop, body, crate::BinderInfo::Default);
        assert_eq!(k.render_lean(pi), "((a : Prop) -> a)");
    }

    /// Declarations render as Lean top-level commands: a plain `axiom`, a
    /// universe-polymorphic `axiom h.{u} : Sort (u)`, and a `theorem` carrying a
    /// proof value.
    #[test]
    fn renders_declarations_as_commands() {
        use crate::Declaration;

        let mut k = Kernel::new();
        let prop = {
            let zero = k.level_zero();
            k.sort(zero)
        };
        let anon = k.anon();
        let h = k.name_str(anon, "h");
        let t = k.name_str(anon, "t");
        let u = k.name_str(anon, "u");

        let ax = Declaration::Axiom {
            name: h,
            uparams: vec![],
            ty: prop,
        };
        assert_eq!(k.render_lean_decl(&ax), "axiom h : Prop");

        let sort_u = {
            let lvl = k.level_param(u);
            k.sort(lvl)
        };
        let ax_poly = Declaration::Axiom {
            name: h,
            uparams: vec![u],
            ty: sort_u,
        };
        assert_eq!(k.render_lean_decl(&ax_poly), "axiom h.{u} : Sort (u)");

        let thm = Declaration::Theorem {
            name: t,
            uparams: vec![],
            ty: prop,
            value: prop,
        };
        assert_eq!(k.render_lean_decl(&thm), "theorem t : Prop :=\n  Prop");
    }

    /// A self-contained module renders the `prelude` header, only the declarations
    /// reachable from the goal/proof (here `False` and the hypothesis axiom — not
    /// the unrelated `And`/`Or`/… prelude inductives), the `theorem`, and the
    /// `#print axioms` audit; every referenced declaration precedes the theorem.
    #[test]
    fn renders_self_contained_module() {
        use crate::{Declaration, build_logic_prelude};

        let mut k = Kernel::new();
        let prelude = build_logic_prelude(&mut k);
        let anon = k.anon();
        // axiom h : False, then `theorem g : False := h`.
        let false_const = k.const_(prelude.false_, vec![]);
        let h = k.name_str(anon, "h");
        k.add_declaration(Declaration::Axiom {
            name: h,
            uparams: vec![],
            ty: false_const,
        })
        .expect("h : False admits");
        let proof = k.const_(h, vec![]);

        let module = k.render_lean_module("g", false_const, proof);

        assert!(module.starts_with("-- Auto-generated"), "{module}");
        assert!(module.contains("\nprelude\n"), "{module}");
        // `False` and `h` are reachable and declared.
        assert!(module.contains("axiom False : Prop"), "{module}");
        assert!(module.contains("axiom h : False"), "{module}");
        // Unrelated prelude inductives are NOT pulled in.
        assert!(!module.contains("axiom And "), "{module}");
        // The theorem and audit close the module.
        assert!(module.contains("theorem g : False :=\n  h"), "{module}");
        assert!(module.trim_end().ends_with("#print axioms g"), "{module}");
        // `False` is declared before the theorem that uses it.
        let false_at = module.find("axiom False").unwrap();
        let thm_at = module.find("theorem g").unwrap();
        assert!(
            false_at < thm_at,
            "False must precede the theorem\n{module}"
        );
    }
}
