//! Render kernel terms to Lean 4 source syntax — a readable, externally-checkable
//! projection of the in-tree kernel's `Expr`/`Name`/`Level`.
//!
//! This is the first slice of a full Lean export: it renders proof *terms* (the
//! trusted-checking witnesses produced by `axeyum-solver`'s reconstruction) into
//! the surface syntax a real Lean 4 kernel reads, so a refutation the in-tree
//! [`Kernel`](crate::Kernel) accepts can also be inspected, diffed, and (with the
//! declaration prelude, a later slice) re-checked by an independent Lean toolchain.
//! It is pure pretty-printing — it never affects type checking.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::{Declaration, ExprId, ExprNode, Kernel, LevelId, LevelNode, Lit, NameId, NameNode};

const COMPACT_SHARE_MIN_TREE_NODES: u64 = 8;
const COMPACT_SHARE_CAP: usize = 16_384;

#[derive(Debug, Default)]
struct LeanSharePlan {
    names: BTreeMap<ExprId, String>,
    order: Vec<ExprId>,
}

impl Kernel {
    /// Render `expr` as a Lean 4 source string. De Bruijn variables are resolved to
    /// their binder names (anonymous binders get generated `x<depth>` names); the
    /// output is parenthesized enough to re-parse with Lean's standard precedence.
    #[must_use]
    pub fn render_lean(&self, expr: ExprId) -> String {
        let mut binders: Vec<String> = Vec::new();
        self.render_expr(expr, &mut binders, &std::collections::BTreeSet::new())
    }

    /// Like [`Self::render_lean`], but every `Const` whose name is in `at_consts` is
    /// rendered with a leading `@` (explicit-argument application). This is needed
    /// for the recursors of **real Lean inductives**, whose `motive` argument Lean
    /// makes *implicit*: `@I.rec.{u} motive minors… major` applies the
    /// kernel's explicit-motive term positionally. For axioms (no implicit args)
    /// `@f` and `f` are identical, so this only ever affects the listed recursors.
    #[must_use]
    fn render_lean_with_at(
        &self,
        expr: ExprId,
        at_consts: &std::collections::BTreeSet<NameId>,
    ) -> String {
        let mut binders: Vec<String> = Vec::new();
        self.render_expr(expr, &mut binders, at_consts)
    }

    /// Render a [`Declaration`] as a Lean 4 top-level command. The directly-emittable
    /// kinds (`axiom`/`def`/`theorem`/`opaque`) render verbatim; an
    /// `Inductive`/`Constructor`/`Recursor` renders as a comment, since Lean
    /// regenerates those from a single `inductive` command (a later export slice).
    #[must_use]
    pub fn render_lean_decl(&self, decl: &Declaration) -> String {
        match decl {
            Declaration::Axiom { name, uparams, ty } => format!(
                "axiom {}{} : {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty)
            ),
            Declaration::Definition {
                name,
                uparams,
                ty,
                value,
                ..
            } => format!(
                "def {}{} : {} :=\n  {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty),
                self.render_lean(*value)
            ),
            Declaration::Theorem {
                name,
                uparams,
                ty,
                value,
            } => format!(
                "theorem {}{} : {} :=\n  {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty),
                self.render_lean(*value)
            ),
            Declaration::Opaque {
                name,
                uparams,
                ty,
                value,
            } => format!(
                "opaque {}{} : {} :=\n  {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty),
                self.render_lean(*value)
            ),
            Declaration::Inductive { name, .. }
            | Declaration::Constructor { name, .. }
            | Declaration::Recursor { name, .. } => format!(
                "-- `{}` is regenerated by Lean's `inductive` command (export slice TODO)",
                self.render_name(*name)
            ),
        }
    }

    /// Render a **self-contained Lean 4 module** that re-checks a reconstructed
    /// refutation: every environment declaration reachable from `goal`/`proof`,
    /// in dependency order, followed by `theorem <theorem_name> : <goal> := <proof>`
    /// and a `#print axioms <theorem_name>` audit command.
    ///
    /// The module opens with `prelude` (no `import Init`), so the re-declared
    /// logical constants (`True`/`False`/`And`/`Eq`/…) do not clash with Lean's
    /// core: it is checked against *axeyum's own* declarations, exactly the
    /// obligation the in-tree [`Kernel`] discharged. Inductives, their
    /// constructors, and their generated recursors are emitted as `axiom`s carrying
    /// the kernel's stored types (so Lean re-checks the proof term against those
    /// signatures); definitions/theorems/opaques and the uninterpreted/`em` axioms
    /// render verbatim. A real `lean` binary that accepts this module — and reports
    /// (via `#print axioms`) only the expected uninterpreted/`em`/`propext`-class
    /// axioms — independently confirms the refutation.
    ///
    /// `theorem_name` must be a valid Lean identifier (e.g. `axeyum_refutation`).
    #[must_use]
    pub fn render_lean_module(&self, theorem_name: &str, goal: ExprId, proof: ExprId) -> String {
        self.render_lean_module_with_inductives(theorem_name, goal, proof, &[])
    }

    /// Render a self-contained module while preserving repeated **closed** proof
    /// DAG nodes as deterministic top-level definitions.
    ///
    /// This is semantically equivalent to [`Self::render_lean_module`], but can
    /// be substantially smaller for hash-consed proofs whose ordinary source
    /// rendering expands shared subterms as a tree. Expressions containing loose
    /// de Bruijn variables or free variables are never hoisted.
    #[must_use]
    pub fn render_lean_module_compact(
        &self,
        theorem_name: &str,
        goal: ExprId,
        proof: ExprId,
    ) -> String {
        self.render_lean_module_compact_with_inductives(theorem_name, goal, proof, &[])
    }

    /// Like [`Self::render_lean_module`], but renders each inductive named in
    /// `real_inductives` as a **real Lean `inductive` command** (so Lean
    /// regenerates its constructors and recursor, *with* their ι-reduction rules),
    /// instead of opaque `axiom`s. The auto-generated constructor/recursor
    /// declarations of those inductives are then **skipped** (Lean provides them).
    ///
    /// This is required when the reconstructed proof relies on **Lean-side
    /// ι-reduction** of a custom inductive's recursor — e.g. the `QF_DT` is-tester
    /// fold `is_C (C x) ≡ Bool.true`, whose `Eq.refl` proof only type-checks if
    /// Lean can compute the recursor application. Inductives *not* listed keep the
    /// axiom rendering byte-for-byte (so the logical-prelude connectives — whose
    /// proofs never need their recursors to *compute* in Lean — are unchanged).
    ///
    /// Only **non-parametric, non-indexed** inductives (enums / flat datatype
    /// families) are emitted as real `inductive`s; a listed inductive that is
    /// parametric or indexed falls back to the axiom rendering (a defensive guard —
    /// the is-tester families are always flat).
    ///
    /// `theorem_name` must be a valid Lean identifier.
    #[must_use]
    pub fn render_lean_module_with_inductives(
        &self,
        theorem_name: &str,
        goal: ExprId,
        proof: ExprId,
        real_inductives: &[NameId],
    ) -> String {
        self.render_lean_module_impl(theorem_name, goal, proof, real_inductives, false)
    }

    /// Compact counterpart of [`Self::render_lean_module_with_inductives`].
    /// Repeated closed proof nodes are hoisted, while listed inductives retain
    /// Lean-side recursor computation.
    #[must_use]
    pub fn render_lean_module_compact_with_inductives(
        &self,
        theorem_name: &str,
        goal: ExprId,
        proof: ExprId,
        real_inductives: &[NameId],
    ) -> String {
        self.render_lean_module_impl(theorem_name, goal, proof, real_inductives, true)
    }

    fn render_lean_module_impl(
        &self,
        theorem_name: &str,
        goal: ExprId,
        proof: ExprId,
        real_inductives: &[NameId],
        compact: bool,
    ) -> String {
        let order = self.reachable_decl_order(&[goal, proof]);
        let mut out = String::from(
            "-- Auto-generated by axeyum-lean-kernel: a self-contained re-check of a\n\
             -- reconstructed refutation. `prelude` avoids clashing with Lean core.\n\
             prelude\n\
             set_option linter.unusedVariables false\n\n",
        );
        // The constructor/recursor names Lean will auto-generate for the real
        // inductives — emit nothing for them (Lean owns them). The recursor names
        // are also the `@`-application set: Lean makes their `motive` implicit, so
        // the kernel's explicit-motive recursor term must apply them with `@`.
        let mut owned_by_lean: std::collections::BTreeSet<NameId> =
            std::collections::BTreeSet::new();
        let mut at_consts: std::collections::BTreeSet<NameId> = std::collections::BTreeSet::new();
        for &ind in real_inductives {
            if let Some(Declaration::Inductive { ctor_names, .. }) = self.environment().get(ind) {
                for &c in ctor_names {
                    owned_by_lean.insert(c);
                }
                let rec = self.name_of_rec(ind);
                owned_by_lean.insert(rec);
                at_consts.insert(rec);
            }
        }
        for name in &order {
            if owned_by_lean.contains(name) {
                continue;
            }
            if real_inductives.contains(name)
                && let Some(block) = self.render_real_inductive(*name)
            {
                out.push_str(&block);
                out.push('\n');
                continue;
            }
            if let Some(decl) = self.environment().get(*name) {
                out.push_str(&self.render_decl_command_with_at(decl, &at_consts));
                out.push('\n');
            }
        }
        let shares = if compact {
            self.compact_share_plan(&[goal, proof], theorem_name)
        } else {
            LeanSharePlan::default()
        };
        for &expression in &shares.order {
            let name = &shares.names[&expression];
            let body = self.render_lean_with_shares(
                expression,
                &at_consts,
                &shares.names,
                Some(expression),
            );
            let _ = write!(out, "\ndef {name} :=\n  {body}\n");
        }
        let rendered_goal = if compact {
            self.render_lean_with_shares(goal, &at_consts, &shares.names, None)
        } else {
            self.render_lean_with_at(goal, &at_consts)
        };
        let rendered_proof = if compact {
            self.render_lean_with_shares(proof, &at_consts, &shares.names, None)
        } else {
            self.render_lean_with_at(proof, &at_consts)
        };
        let _ = write!(
            out,
            "\ntheorem {theorem_name} : {rendered_goal} :=\n  {rendered_proof}\n\n#print axioms {theorem_name}\n"
        );
        out
    }

    /// The recursor name `I.rec` an inductive `I` generates: the `Recursor`
    /// declaration whose name's parent is `ind`. Falls back to `ind` itself if no
    /// recursor is registered (then nothing extra is skipped).
    fn name_of_rec(&self, ind: NameId) -> NameId {
        self.environment()
            .iter()
            .find_map(|(&n, decl)| {
                if matches!(decl, Declaration::Recursor { .. })
                    && matches!(self.name_node(n), NameNode::Str(parent, s)
                        if *parent == ind && s == "rec")
                {
                    Some(n)
                } else {
                    None
                }
            })
            .unwrap_or(ind)
    }

    /// Render a **non-parametric, non-indexed** inductive `I` as a real Lean
    /// `inductive I : <ty> where | c₀ : <ty₀> | … | c_{k-1} : <ty_{k-1}>` command,
    /// so Lean regenerates its recursor (with ι). Returns [`None`] if `I` is not a
    /// flat inductive (parametric/indexed), in which case the caller keeps the
    /// axiom rendering.
    fn render_real_inductive(&self, ind: NameId) -> Option<String> {
        let Some(Declaration::Inductive {
            name,
            uparams,
            ty,
            ctor_names,
        }) = self.environment().get(ind).cloned()
        else {
            return None;
        };
        // Only flat (no params, no indices) inductives: every constructor must be a
        // `Constructor` whose type telescopes to the bare inductive (no indices).
        let mut block = format!(
            "inductive {}{} : {} where",
            self.render_name(name),
            self.render_uparams(&uparams),
            self.render_lean(ty)
        );
        for &cn in &ctor_names {
            let Some(Declaration::Constructor {
                ty: ctor_ty,
                num_fields: _,
                ..
            }) = self.environment().get(cn)
            else {
                return None;
            };
            let _ = write!(
                block,
                "\n  | {} : {}",
                self.render_short_ctor_name(cn),
                self.render_lean(*ctor_ty)
            );
        }
        Some(block)
    }

    /// A constructor's **leaf** name (the last `.`-segment), as Lean's `inductive`
    /// syntax expects (`| true : …`, not `| Bool.true : …`).
    fn render_short_ctor_name(&self, ctor: NameId) -> String {
        match self.name_node(ctor) {
            NameNode::Str(_, s) => s.clone(),
            _ => self.render_name(ctor),
        }
    }

    /// Render a declaration as a self-contained `prelude`-mode command: inductives,
    /// constructors, and recursors become `axiom`s (carrying their kernel type),
    /// since `prelude` mode has no `inductive`-generated recursors to rely on; all
    /// other kinds render through [`Self::render_lean_decl`].
    fn render_decl_command(&self, decl: &Declaration) -> String {
        match decl {
            Declaration::Inductive {
                name, uparams, ty, ..
            }
            | Declaration::Constructor {
                name, uparams, ty, ..
            }
            | Declaration::Recursor {
                name, uparams, ty, ..
            } => format!(
                "axiom {}{} : {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean(*ty)
            ),
            _ => self.render_lean_decl(decl),
        }
    }

    /// Like [`Self::render_decl_command`], but renders the declaration's type (and
    /// a definition/theorem/opaque value) with the `@`-application set `at_consts`,
    /// so any reference to a real-inductive recursor inside an axiom *type* (e.g.
    /// the is-tester hypothesis `h : ¬(Eq Bool (is_C …) true)`, whose `is_C` is a
    /// recursor application) applies it positionally with `@` — matching Lean's
    /// implicit-motive recursor. When `at_consts` is empty this is byte-identical to
    /// [`Self::render_decl_command`].
    fn render_decl_command_with_at(
        &self,
        decl: &Declaration,
        at_consts: &std::collections::BTreeSet<NameId>,
    ) -> String {
        if at_consts.is_empty() {
            return self.render_decl_command(decl);
        }
        match decl {
            // Inductives/constructors/recursors keep the `axiom` rendering (carrying
            // their kernel type); a plain `Axiom` renders the same way. The only
            // difference from [`Self::render_decl_command`] is `@`-aware type rendering.
            Declaration::Inductive {
                name, uparams, ty, ..
            }
            | Declaration::Constructor {
                name, uparams, ty, ..
            }
            | Declaration::Recursor {
                name, uparams, ty, ..
            }
            | Declaration::Axiom { name, uparams, ty } => format!(
                "axiom {}{} : {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean_with_at(*ty, at_consts)
            ),
            Declaration::Definition {
                name,
                uparams,
                ty,
                value,
                ..
            } => format!(
                "def {}{} : {} :=\n  {}",
                self.render_name(*name),
                self.render_uparams(uparams),
                self.render_lean_with_at(*ty, at_consts),
                self.render_lean_with_at(*value, at_consts)
            ),
            Declaration::Theorem {
                name,
                uparams,
                ty,
                value,
            }
            | Declaration::Opaque {
                name,
                uparams,
                ty,
                value,
            } => {
                let kw = if matches!(decl, Declaration::Opaque { .. }) {
                    "opaque"
                } else {
                    "theorem"
                };
                format!(
                    "{kw} {}{} : {} :=\n  {}",
                    self.render_name(*name),
                    self.render_uparams(uparams),
                    self.render_lean_with_at(*ty, at_consts),
                    self.render_lean_with_at(*value, at_consts)
                )
            }
        }
    }

    /// The environment declarations reachable from `roots` (transitively through
    /// each declaration's type and — for definitions/theorems/opaques — value),
    /// in dependency order (a declaration appears after every declaration it
    /// references). Names not present in the environment are skipped.
    fn reachable_decl_order(&self, roots: &[ExprId]) -> Vec<NameId> {
        // Reachability closure over constant references.
        let mut needed: std::collections::BTreeSet<NameId> = std::collections::BTreeSet::new();
        let mut work: Vec<NameId> = Vec::new();
        let mut seed = Vec::new();
        for &r in roots {
            self.collect_const_deps(r, &mut seed);
        }
        for n in seed {
            if needed.insert(n) {
                work.push(n);
            }
        }
        while let Some(n) = work.pop() {
            for d in self.decl_deps(n) {
                if needed.insert(d) {
                    work.push(d);
                }
            }
        }
        // Deterministic post-order DFS topological sort over the reachable set.
        let mut visited: std::collections::BTreeSet<NameId> = std::collections::BTreeSet::new();
        let mut order: Vec<NameId> = Vec::new();
        for &n in &needed {
            self.topo_visit(n, &needed, &mut visited, &mut order);
        }
        order
    }

    /// The constants a declaration references (in its type, plus its value for
    /// `Definition`/`Theorem`/`Opaque`).
    fn decl_deps(&self, name: NameId) -> Vec<NameId> {
        let mut deps = Vec::new();
        if let Some(decl) = self.environment().get(name) {
            self.collect_const_deps(decl.ty(), &mut deps);
            match decl {
                Declaration::Definition { value, .. }
                | Declaration::Theorem { value, .. }
                | Declaration::Opaque { value, .. } => {
                    self.collect_const_deps(*value, &mut deps);
                }
                _ => {}
            }
        }
        deps
    }

    fn topo_visit(
        &self,
        name: NameId,
        needed: &std::collections::BTreeSet<NameId>,
        visited: &mut std::collections::BTreeSet<NameId>,
        order: &mut Vec<NameId>,
    ) {
        if !visited.insert(name) {
            return;
        }
        for d in self.decl_deps(name) {
            if needed.contains(&d) {
                self.topo_visit(d, needed, visited, order);
            }
        }
        order.push(name);
    }

    /// Collect (iteratively, to avoid deep recursion on large proof terms) every
    /// `Const` name referenced anywhere inside `root`.
    fn collect_const_deps(&self, root: ExprId, out: &mut Vec<NameId>) {
        let mut stack = vec![root];
        while let Some(e) = stack.pop() {
            match self.expr_node(e) {
                ExprNode::Const(n, _) => out.push(*n),
                ExprNode::App(f, a) => {
                    stack.push(*f);
                    stack.push(*a);
                }
                ExprNode::Lam(_, t, b, _) | ExprNode::Pi(_, t, b, _) => {
                    stack.push(*t);
                    stack.push(*b);
                }
                ExprNode::Let(_, t, v, b) => {
                    stack.push(*t);
                    stack.push(*v);
                    stack.push(*b);
                }
                ExprNode::BVar(_) | ExprNode::FVar(_) | ExprNode::Sort(_) | ExprNode::Lit(_) => {}
            }
        }
    }

    /// The universe-parameter suffix `.{u, v}` for a declaration head (empty when
    /// the declaration is universe-monomorphic).
    fn render_uparams(&self, uparams: &[NameId]) -> String {
        if uparams.is_empty() {
            String::new()
        } else {
            let names: Vec<String> = uparams.iter().map(|n| self.render_name(*n)).collect();
            format!(".{{{}}}", names.join(", "))
        }
    }

    /// A hierarchical [`NameId`] as a dotted Lean name (`a.b.1`); the anonymous root
    /// renders empty.
    ///
    /// The kernel's **computational `Nat`** (root segment `Nat`, with children
    /// `Nat.zero`/`Nat.succ`/`Nat.rec`/…) is rendered under the non-shadowing root
    /// **`AxNat`** instead. Lean's builtin `Nat` has special kernel support (literal
    /// `OfNat`/`HAdd` elaboration, `Nat.casesOn`/`T.ctorIdx` codegen); emitting our
    /// own `inductive Nat` *shadows* that builtin and a real `lean` binary rejects it
    /// (`failed to construct T.ctorIdx for Nat`, `Unknown constant HAdd.hAdd`). A
    /// user datatype never carries the bare root name `Nat` (datatype families render
    /// as `axeyum.reconstruct.dtrec._N`), so remapping the root `Nat` segment is
    /// unambiguous and affects only the prelude's computational naturals — the
    /// in-tree kernel and its stored names are untouched (this is pure rendering).
    fn render_name(&self, id: NameId) -> String {
        match self.name_node(id) {
            NameNode::Anonymous => String::new(),
            NameNode::Str(parent, s) => {
                let p = self.render_name(*parent);
                if p.is_empty() {
                    if s == "Nat" {
                        // Non-shadowing root for the kernel's computational naturals.
                        "AxNat".to_owned()
                    } else {
                        s.clone()
                    }
                } else {
                    format!("{p}.{s}")
                }
            }
            NameNode::Num(parent, n) => {
                // A numeric name component is not a legal Lean identifier component
                // on its own (`foo.0` parses as projection); prefix it with `_` so
                // generated names like `axeyum.reconstruct.atom.0` export as the
                // valid hierarchical name `axeyum.reconstruct.atom._0`.
                let p = self.render_name(*parent);
                if p.is_empty() {
                    format!("_{n}")
                } else {
                    format!("{p}._{n}")
                }
            }
        }
    }

    /// A universe [`LevelId`] in Lean level syntax. A `Succ` chain over a base is
    /// collapsed into the `base+n` (or a bare numeral `n` when the base is `Zero`)
    /// form Lean's level grammar expects — e.g. `Sort 1` rather than `Sort (0+1)`.
    fn render_level(&self, id: LevelId) -> String {
        let mut offset: u32 = 0;
        let mut cur = id;
        while let LevelNode::Succ(l) = self.level_node(cur) {
            offset += 1;
            cur = *l;
        }
        let base = match self.level_node(cur) {
            LevelNode::Zero => return offset.to_string(),
            LevelNode::Param(n) => self.render_name(*n),
            LevelNode::Max(a, b) => {
                format!("(max {} {})", self.render_level(*a), self.render_level(*b))
            }
            LevelNode::IMax(a, b) => {
                format!("(imax {} {})", self.render_level(*a), self.render_level(*b))
            }
            LevelNode::Succ(_) => unreachable!("Succ chain already consumed"),
        };
        if offset == 0 {
            base
        } else {
            format!("{base}+{offset}")
        }
    }

    /// The binder name to print for a binder declared with [`NameId`] `name` opened
    /// at de Bruijn `depth`; anonymous binders become a generated `x<depth>`.
    fn binder_name(&self, name: NameId, depth: usize) -> String {
        let rendered = self.render_name(name);
        if rendered.is_empty() {
            format!("x{depth}")
        } else {
            rendered
        }
    }

    fn expr_children(&self, id: ExprId) -> Vec<ExprId> {
        match self.expr_node(id) {
            ExprNode::App(function, argument) => vec![*function, *argument],
            ExprNode::Lam(_, ty, body, _) | ExprNode::Pi(_, ty, body, _) => {
                vec![*ty, *body]
            }
            ExprNode::Let(_, ty, value, body) => vec![*ty, *value, *body],
            ExprNode::BVar(_)
            | ExprNode::FVar(_)
            | ExprNode::Sort(_)
            | ExprNode::Const(_, _)
            | ExprNode::Lit(_) => Vec::new(),
        }
    }

    fn expr_postorder(&self, roots: &[ExprId]) -> Vec<ExprId> {
        let mut visited = BTreeSet::new();
        let mut order = Vec::new();
        let mut stack = roots
            .iter()
            .rev()
            .copied()
            .map(|root| (root, false))
            .collect::<Vec<_>>();
        while let Some((expression, expanded)) = stack.pop() {
            if expanded {
                order.push(expression);
                continue;
            }
            if !visited.insert(expression) {
                continue;
            }
            stack.push((expression, true));
            let children = self.expr_children(expression);
            for child in children.into_iter().rev() {
                stack.push((child, false));
            }
        }
        order
    }

    fn compact_share_plan(&self, roots: &[ExprId], theorem_name: &str) -> LeanSharePlan {
        let postorder = self.expr_postorder(roots);
        let mut occurrences = BTreeMap::<ExprId, u64>::new();
        for &root in roots {
            *occurrences.entry(root).or_default() = occurrences
                .get(&root)
                .copied()
                .unwrap_or_default()
                .saturating_add(1);
        }
        for &expression in postorder.iter().rev() {
            let count = occurrences.get(&expression).copied().unwrap_or_default();
            if count == 0 {
                continue;
            }
            for child in self.expr_children(expression) {
                let current = occurrences.get(&child).copied().unwrap_or_default();
                occurrences.insert(child, current.saturating_add(count));
            }
        }

        let mut tree_sizes = BTreeMap::<ExprId, u64>::new();
        for &expression in &postorder {
            let mut size = 1_u64;
            for child in self.expr_children(expression) {
                size = size.saturating_add(tree_sizes.get(&child).copied().unwrap_or(1));
            }
            tree_sizes.insert(expression, size);
        }

        let mut candidates = postorder
            .iter()
            .copied()
            .filter(|&expression| {
                occurrences.get(&expression).copied().unwrap_or_default() >= 2
                    && tree_sizes.get(&expression).copied().unwrap_or_default()
                        >= COMPACT_SHARE_MIN_TREE_NODES
                    && self.num_loose_bvars(expression) == 0
                    && !self.has_fvars(expression)
                    && matches!(
                        self.expr_node(expression),
                        ExprNode::App(_, _)
                            | ExprNode::Lam(..)
                            | ExprNode::Pi(..)
                            | ExprNode::Let(..)
                    )
            })
            .collect::<Vec<_>>();
        candidates.sort_by_key(|expression| {
            let count = occurrences[expression];
            let size = tree_sizes[expression];
            (
                std::cmp::Reverse(count.saturating_sub(1).saturating_mul(size)),
                expression.index(),
            )
        });
        candidates.truncate(COMPACT_SHARE_CAP);
        let selected = candidates.into_iter().collect::<BTreeSet<_>>();

        let mut reserved = self
            .environment()
            .iter()
            .map(|(&name, _)| self.render_name(name))
            .collect::<BTreeSet<_>>();
        reserved.insert(theorem_name.to_owned());
        let mut names = BTreeMap::new();
        let mut order = Vec::new();
        let mut suffix = 0_u64;
        for expression in postorder {
            if !selected.contains(&expression) {
                continue;
            }
            let name = loop {
                let candidate = format!("axeyum_proof_share_{suffix}");
                suffix += 1;
                if reserved.insert(candidate.clone()) {
                    break candidate;
                }
            };
            names.insert(expression, name);
            order.push(expression);
        }
        LeanSharePlan { names, order }
    }

    fn render_lean_with_shares(
        &self,
        expression: ExprId,
        at_consts: &BTreeSet<NameId>,
        shares: &BTreeMap<ExprId, String>,
        expand_root: Option<ExprId>,
    ) -> String {
        let mut binders = Vec::new();
        self.render_expr_with_shares(expression, &mut binders, at_consts, shares, expand_root)
    }

    fn render_expr_with_shares_atom(
        &self,
        expression: ExprId,
        binders: &mut Vec<String>,
        at_consts: &BTreeSet<NameId>,
        shares: &BTreeMap<ExprId, String>,
        expand_root: Option<ExprId>,
    ) -> String {
        if expand_root != Some(expression)
            && let Some(name) = shares.get(&expression)
        {
            return name.clone();
        }
        match self.expr_node(expression) {
            ExprNode::BVar(_)
            | ExprNode::FVar(_)
            | ExprNode::Const(_, _)
            | ExprNode::Sort(_)
            | ExprNode::Lit(_) => {
                self.render_expr_with_shares(expression, binders, at_consts, shares, expand_root)
            }
            ExprNode::App(_, _) | ExprNode::Lam(..) | ExprNode::Pi(..) | ExprNode::Let(..) => {
                format!(
                    "({})",
                    self.render_expr_with_shares(
                        expression,
                        binders,
                        at_consts,
                        shares,
                        expand_root,
                    )
                )
            }
        }
    }

    fn render_expr_with_shares(
        &self,
        expression: ExprId,
        binders: &mut Vec<String>,
        at_consts: &BTreeSet<NameId>,
        shares: &BTreeMap<ExprId, String>,
        expand_root: Option<ExprId>,
    ) -> String {
        if expand_root != Some(expression)
            && let Some(name) = shares.get(&expression)
        {
            return name.clone();
        }
        match self.expr_node(expression) {
            ExprNode::BVar(index) => binders
                .len()
                .checked_sub(1 + *index as usize)
                .map_or_else(|| format!("#{index}"), |position| binders[position].clone()),
            ExprNode::FVar(id) => format!("_fvar.{id}"),
            ExprNode::Sort(level) => {
                let rendered = self.render_level(*level);
                if rendered == "0" {
                    "Prop".to_owned()
                } else {
                    format!("Sort ({rendered})")
                }
            }
            ExprNode::Const(name, levels) => {
                let at = if at_consts.contains(name) { "@" } else { "" };
                let rendered = format!("{at}{}", self.render_name(*name));
                if levels.is_empty() {
                    rendered
                } else {
                    let levels = levels
                        .iter()
                        .map(|level| self.render_level(*level))
                        .collect::<Vec<_>>();
                    format!("{rendered}.{{{}}}", levels.join(", "))
                }
            }
            ExprNode::App(function, argument) => {
                let function = self.render_expr_with_shares_atom(
                    *function,
                    binders,
                    at_consts,
                    shares,
                    expand_root,
                );
                let argument = self.render_expr_with_shares_atom(
                    *argument,
                    binders,
                    at_consts,
                    shares,
                    expand_root,
                );
                format!("{function} {argument}")
            }
            ExprNode::Lam(name, ty, body, _) => {
                let binder = self.binder_name(*name, binders.len());
                let ty = self.render_expr_with_shares(*ty, binders, at_consts, shares, expand_root);
                binders.push(binder.clone());
                let body =
                    self.render_expr_with_shares(*body, binders, at_consts, shares, expand_root);
                binders.pop();
                format!("fun ({binder} : {ty}) => {body}")
            }
            ExprNode::Pi(name, ty, body, _) => {
                let binder = self.binder_name(*name, binders.len());
                let ty = self.render_expr_with_shares(*ty, binders, at_consts, shares, expand_root);
                binders.push(binder.clone());
                let body =
                    self.render_expr_with_shares(*body, binders, at_consts, shares, expand_root);
                binders.pop();
                format!("(({binder} : {ty}) -> {body})")
            }
            ExprNode::Let(name, ty, value, body) => {
                let binder = self.binder_name(*name, binders.len());
                let ty = self.render_expr_with_shares(*ty, binders, at_consts, shares, expand_root);
                let value =
                    self.render_expr_with_shares(*value, binders, at_consts, shares, expand_root);
                binders.push(binder.clone());
                let body =
                    self.render_expr_with_shares(*body, binders, at_consts, shares, expand_root);
                binders.pop();
                format!("let {binder} : {ty} := {value}; {body}")
            }
            ExprNode::Lit(Lit::Nat(value)) => value.to_string(),
            ExprNode::Lit(Lit::Str(value)) => format!("{value:?}"),
        }
    }

    /// Render an expression, wrapping it in parentheses when it is a compound form
    /// (so it can sit as a function head or argument without re-association).
    fn render_expr_atom(
        &self,
        id: ExprId,
        binders: &mut Vec<String>,
        at_consts: &std::collections::BTreeSet<NameId>,
    ) -> String {
        match self.expr_node(id) {
            ExprNode::BVar(_)
            | ExprNode::FVar(_)
            | ExprNode::Const(_, _)
            | ExprNode::Sort(_)
            | ExprNode::Lit(_) => self.render_expr(id, binders, at_consts),
            ExprNode::App(_, _) | ExprNode::Lam(..) | ExprNode::Pi(..) | ExprNode::Let(..) => {
                format!("({})", self.render_expr(id, binders, at_consts))
            }
        }
    }

    fn render_expr(
        &self,
        id: ExprId,
        binders: &mut Vec<String>,
        at_consts: &std::collections::BTreeSet<NameId>,
    ) -> String {
        match self.expr_node(id) {
            ExprNode::BVar(i) => binders
                .len()
                .checked_sub(1 + *i as usize)
                .map_or_else(|| format!("#{i}"), |k| binders[k].clone()),
            ExprNode::FVar(fid) => format!("_fvar.{fid}"),
            ExprNode::Sort(l) => {
                let ls = self.render_level(*l);
                if ls == "0" {
                    "Prop".to_owned()
                } else {
                    format!("Sort ({ls})")
                }
            }
            ExprNode::Const(name, levels) => {
                let at = if at_consts.contains(name) { "@" } else { "" };
                let n = format!("{at}{}", self.render_name(*name));
                if levels.is_empty() {
                    n
                } else {
                    let ls: Vec<String> = levels.iter().map(|l| self.render_level(*l)).collect();
                    format!("{n}.{{{}}}", ls.join(", "))
                }
            }
            ExprNode::App(f, a) => {
                let fs = self.render_expr_atom(*f, binders, at_consts);
                let as_ = self.render_expr_atom(*a, binders, at_consts);
                format!("{fs} {as_}")
            }
            ExprNode::Lam(name, ty, body, _) => {
                let bn = self.binder_name(*name, binders.len());
                let tys = self.render_expr(*ty, binders, at_consts);
                binders.push(bn.clone());
                let bs = self.render_expr(*body, binders, at_consts);
                binders.pop();
                format!("fun ({bn} : {tys}) => {bs}")
            }
            ExprNode::Pi(name, ty, body, _) => {
                let bn = self.binder_name(*name, binders.len());
                let tys = self.render_expr(*ty, binders, at_consts);
                binders.push(bn.clone());
                let bs = self.render_expr(*body, binders, at_consts);
                binders.pop();
                format!("(({bn} : {tys}) -> {bs})")
            }
            ExprNode::Let(name, ty, val, body) => {
                let bn = self.binder_name(*name, binders.len());
                let tys = self.render_expr(*ty, binders, at_consts);
                let vs = self.render_expr(*val, binders, at_consts);
                binders.push(bn.clone());
                let bs = self.render_expr(*body, binders, at_consts);
                binders.pop();
                format!("let {bn} : {tys} := {vs}; {bs}")
            }
            ExprNode::Lit(Lit::Nat(n)) => n.to_string(),
            ExprNode::Lit(Lit::Str(s)) => format!("{s:?}"),
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::Kernel;

    /// `fun (p : Prop) => p` renders to readable Lean with the de Bruijn variable
    /// resolved to its binder name, and the round-trip parses structurally.
    #[test]
    fn renders_identity_on_prop() {
        let mut k = Kernel::new();
        let prop = {
            let zero = k.level_zero();
            k.sort(zero)
        };
        let anon = k.anon();
        let p = k.name_str(anon, "p");
        let body = k.bvar(0);
        let lam = k.lam(p, prop, body, crate::BinderInfo::Default);
        assert_eq!(k.render_lean(lam), "fun (p : Prop) => p");
    }

    /// A `Pi` (dependent arrow) and a nested application render with the binder name
    /// and parenthesized argument.
    #[test]
    fn renders_pi_and_application() {
        let mut k = Kernel::new();
        let prop = {
            let zero = k.level_zero();
            k.sort(zero)
        };
        let anon = k.anon();
        let a = k.name_str(anon, "a");
        // (a : Prop) -> a
        let body = k.bvar(0);
        let pi = k.pi(a, prop, body, crate::BinderInfo::Default);
        assert_eq!(k.render_lean(pi), "((a : Prop) -> a)");
    }

    /// Declarations render as Lean top-level commands: a plain `axiom`, a
    /// universe-polymorphic `axiom h.{u} : Sort (u)`, and a `theorem` carrying a
    /// proof value.
    #[test]
    fn renders_declarations_as_commands() {
        use crate::Declaration;

        let mut k = Kernel::new();
        let prop = {
            let zero = k.level_zero();
            k.sort(zero)
        };
        let anon = k.anon();
        let h = k.name_str(anon, "h");
        let t = k.name_str(anon, "t");
        let u = k.name_str(anon, "u");

        let ax = Declaration::Axiom {
            name: h,
            uparams: vec![],
            ty: prop,
        };
        assert_eq!(k.render_lean_decl(&ax), "axiom h : Prop");

        let sort_u = {
            let lvl = k.level_param(u);
            k.sort(lvl)
        };
        let ax_poly = Declaration::Axiom {
            name: h,
            uparams: vec![u],
            ty: sort_u,
        };
        assert_eq!(k.render_lean_decl(&ax_poly), "axiom h.{u} : Sort (u)");

        let thm = Declaration::Theorem {
            name: t,
            uparams: vec![],
            ty: prop,
            value: prop,
        };
        assert_eq!(k.render_lean_decl(&thm), "theorem t : Prop :=\n  Prop");
    }

    /// A self-contained module renders the `prelude` header, only the declarations
    /// reachable from the goal/proof (here `False` and the hypothesis axiom — not
    /// the unrelated `And`/`Or`/… prelude inductives), the `theorem`, and the
    /// `#print axioms` audit; every referenced declaration precedes the theorem.
    #[test]
    fn renders_self_contained_module() {
        use crate::{Declaration, build_logic_prelude};

        let mut k = Kernel::new();
        let prelude = build_logic_prelude(&mut k);
        let anon = k.anon();
        // axiom h : False, then `theorem g : False := h`.
        let false_const = k.const_(prelude.false_, vec![]);
        let h = k.name_str(anon, "h");
        k.add_declaration(Declaration::Axiom {
            name: h,
            uparams: vec![],
            ty: false_const,
        })
        .expect("h : False admits");
        let proof = k.const_(h, vec![]);

        let module = k.render_lean_module("g", false_const, proof);

        assert!(module.starts_with("-- Auto-generated"), "{module}");
        assert!(module.contains("\nprelude\n"), "{module}");
        // `False` and `h` are reachable and declared.
        assert!(module.contains("axiom False : Prop"), "{module}");
        assert!(module.contains("axiom h : False"), "{module}");
        // Unrelated prelude inductives are NOT pulled in.
        assert!(!module.contains("axiom And "), "{module}");
        // The theorem and audit close the module.
        assert!(module.contains("theorem g : False :=\n  h"), "{module}");
        assert!(module.trim_end().ends_with("#print axioms g"), "{module}");
        // `False` is declared before the theorem that uses it.
        let false_at = module.find("axiom False").unwrap();
        let thm_at = module.find("theorem g").unwrap();
        assert!(
            false_at < thm_at,
            "False must precede the theorem\n{module}"
        );
    }

    #[test]
    fn compact_module_shares_repeated_closed_proof_terms() {
        use crate::{Declaration, build_logic_prelude};

        let mut k = Kernel::new();
        let logic = build_logic_prelude(&mut k);
        let anon = k.anon();
        let prop = k.sort_zero();
        let p_name = k.name_str(anon, "P");
        k.add_declaration(Declaration::Axiom {
            name: p_name,
            uparams: Vec::new(),
            ty: prop,
        })
        .unwrap();
        let p = k.const_(p_name, Vec::new());
        let h_name = k.name_str(anon, "h");
        k.add_declaration(Declaration::Axiom {
            name: h_name,
            uparams: Vec::new(),
            ty: p,
        })
        .unwrap();
        let h = k.const_(h_name, Vec::new());

        let and = k.const_(logic.and, Vec::new());
        let pair_prop = {
            let expression = k.app(and, p);
            k.app(expression, p)
        };
        let pair = {
            let intro = k.const_(logic.and_intro, Vec::new());
            let expression = k.app(intro, p);
            let expression = k.app(expression, p);
            let expression = k.app(expression, h);
            k.app(expression, h)
        };
        let goal = {
            let expression = k.app(and, pair_prop);
            k.app(expression, pair_prop)
        };
        let proof = {
            let intro = k.const_(logic.and_intro, Vec::new());
            let expression = k.app(intro, pair_prop);
            let expression = k.app(expression, pair_prop);
            let expression = k.app(expression, pair);
            k.app(expression, pair)
        };
        let inferred = k.infer(proof).unwrap();
        assert!(k.def_eq(inferred, goal));

        let ordinary = k.render_lean_module("closed_pair", goal, proof);
        let compact = k.render_lean_module_compact("closed_pair", goal, proof);
        assert!(
            compact.contains("def axeyum_proof_share_0 :=\n"),
            "{compact}"
        );
        let repeated = "(((And.intro P) P) h) h";
        assert_eq!(ordinary.matches(repeated).count(), 2, "{ordinary}");
        assert_eq!(compact.matches(repeated).count(), 1, "{compact}");
        assert_eq!(
            compact,
            k.render_lean_module_compact("closed_pair", goal, proof)
        );
        assert_eq!(ordinary, k.render_lean_module("closed_pair", goal, proof));
    }

    #[test]
    fn compact_plan_never_hoists_open_binder_dependent_terms() {
        use crate::{BinderInfo, Declaration, build_logic_prelude};

        let mut k = Kernel::new();
        let logic = build_logic_prelude(&mut k);
        let anon = k.anon();
        let prop = k.sort_zero();
        let function_ty = k.pi(anon, prop, prop, BinderInfo::Default);
        let function_name = k.name_str(anon, "F");
        k.add_declaration(Declaration::Axiom {
            name: function_name,
            uparams: Vec::new(),
            ty: function_ty,
        })
        .unwrap();
        let function = k.const_(function_name, Vec::new());
        let bound = k.bvar(0);
        let once = k.app(function, bound);
        let repeated_open = k.app(function, once);
        let and = k.const_(logic.and, Vec::new());
        let body = {
            let expression = k.app(and, repeated_open);
            k.app(expression, repeated_open)
        };
        let lambda = k.lam(anon, prop, body, BinderInfo::Default);
        assert_eq!(k.num_loose_bvars(repeated_open), 1);

        let plan = k.compact_share_plan(&[lambda], "open_term");
        assert!(plan.names.is_empty(), "open terms must not be hoisted");
    }
}
