# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum import _native
from axeyum._native import kernel
import builtins
import typing
__all__ = [
    "APPLICATION_MAX_BINDERS",
    "APPLICATION_MAX_DEPTH",
    "APPLICATION_MAX_TERMS",
    "ApplicationCandidate",
    "AxiomIdentity",
    "Candidate",
    "CandidateTransport",
    "CandidateTransportError",
    "CircularityAudit",
    "DeclarationDependency",
    "DeclarationIdentity",
    "DeclineReason",
    "Declined",
    "FORMAT_VERSION",
    "IDENTITY_VERSION",
    "ImportLimits",
    "ImportReport",
    "MAX_BINDERS",
    "MAX_INDUCTIONS",
    "MAX_RETRIEVED_DECLARATIONS",
    "MODEQ_MAX_BINDERS",
    "ModEqCandidate",
    "StatementImport",
    "StatementImportError",
    "audit_circularity",
    "import_candidate_statement_ndjson",
    "import_statement_ndjson",
    "propose_bounded_application",
    "propose_bounded_induction",
    "propose_bounded_induction_with_rewrites",
    "propose_modeq_family",
    "transport_native_candidate",
]

APPLICATION_MAX_BINDERS: builtins.int
APPLICATION_MAX_DEPTH: builtins.int
APPLICATION_MAX_TERMS: builtins.int
FORMAT_VERSION: builtins.str
IDENTITY_VERSION: builtins.str
MAX_BINDERS: builtins.int
MAX_INDUCTIONS: builtins.int
MAX_RETRIEVED_DECLARATIONS: builtins.int
MODEQ_MAX_BINDERS: builtins.int
@typing.final
class ApplicationCandidate:
    r"""
    A bounded-application candidate over an explicit retrieved declaration set.
    """
    @property
    def proof(self) -> kernel.ExprId:
        r"""
        Proposed proof term, untrusted until kernel admission.
        """
    @property
    def binders_used(self) -> builtins.int:
        r"""
        Leading goal binders introduced by the search.
        """
    @property
    def application_depth(self) -> builtins.int:
        r"""
        Application-closure rounds consumed.
        """
    @property
    def terms_considered(self) -> builtins.int:
        r"""
        Distinct terms present when the proof was found.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class AxiomIdentity:
    r"""
    One imported axiom bound to TL0.4-compatible name and type identities.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Exact displayed hierarchical declaration name.
        """
    @property
    def name_sha256(self) -> builtins.str:
        r"""
        SHA-256 of the UTF-8 displayed name.
        """
    @property
    def type_sha256(self) -> builtins.str:
        r"""
        SHA-256 of `render_lean(declaration.ty())`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Candidate:
    r"""
    A bounded-induction candidate: a proposed proof term plus the search shape
    that produced it.

    `inductions_used == 0` means the goal closed by plain reflexivity. Nothing
    here is checked: `proof` is untrusted until `Kernel.add_declaration` accepts
    it as the value of a theorem whose type is the goal.
    """
    @property
    def proof(self) -> kernel.ExprId:
        r"""
        The proposed proof term. Untrusted until the kernel re-checks it.
        """
    @property
    def binders_used(self) -> builtins.int:
        r"""
        Leading `Pi` binders peeled, out of `MAX_BINDERS`.
        """
    @property
    def inductions_used(self) -> builtins.int:
        r"""
        Structural inductions performed, out of `MAX_INDUCTIONS`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CandidateTransport:
    r"""
    Checked evidence that one retrieved native theorem is executable in an
    imported goal kernel.
    """
    @property
    def candidate(self) -> kernel.NameId:
        r"""
        Candidate handle belonging to the statement import's same kernel.
        """
    @property
    def disposition(self) -> builtins.str:
        r"""
        `"added"` for checked composition or `"reused"` for checked reuse.
        """
    @property
    def source_closure_size(self) -> builtins.int:
        r"""
        Root-selected native declaration closure size (zero for reuse).
        """
    @property
    def added_theorems(self) -> builtins.int:
        r"""
        Theorems newly admitted by this transport.
        """
    @property
    def added_definitions(self) -> builtins.int:
        r"""
        Definitions newly admitted by this transport.
        """
    @property
    def receipt_sha256(self) -> typing.Optional[builtins.str]:
        r"""
        Digest of an added composition receipt; reuse has no aggregate receipt.
        """
    def __repr__(self) -> builtins.str: ...

class CandidateTransportError(_native.AxeyumError):
    r"""
    A retrieved native theorem could not be checked into the imported goal kernel.
    """
    @property
    def variant(self) -> builtins.str:
        r"""
        The Rust composition error variant name. Never match on the message text.
        """
    @property
    def debug(self) -> builtins.str:
        r"""
        The full Rust `Debug` rendering of the failure.
        """

@typing.final
class CircularityAudit:
    r"""
    The mechanical circularity/trust audit an admitted candidate must pass.

    Computed **only** from `declaration_dependency_closure`, `axiom_footprint`
    and `theorem_dependencies` — never from a doc comment, never from a
    head-symbol text match on a rendered name. The three counts are exposed
    individually and `passes()` is derived from them, so a caller can see *why*
    an audit failed rather than reading a bare `False`.
    """
    @property
    def target_dependency(self) -> builtins.bool:
        r"""
        Whether the candidate's transitive closure contains the target itself —
        the direct self-citation this guard exists for.
        """
    @property
    def axiom_footprint(self) -> builtins.int:
        r"""
        How many `Axiom`/`Opaque`/`Quotient` declarations the candidate reaches.

        Zero is this project's headline claim, so it is reported as a count and
        never collapsed into `passes()` alone.
        """
    @property
    def theorem_dependencies(self) -> builtins.int:
        r"""
        How many other already-proved theorems the candidate cites.
        """
    def passes(self) -> builtins.bool:
        r"""
        No self-citation, no axiom/opaque/quotient reached, no borrowed theorem.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DeclarationDependency:
    r"""
    One direct dependency bound to the dependency's structural content.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Exact displayed hierarchical dependency name.
        """
    @property
    def content_sha256(self) -> builtins.str:
        r"""
        Structural content SHA-256 of the admitted dependency declaration.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DeclarationIdentity:
    r"""
    Canonical identity for one independently admitted declaration.

    `content_sha256` is what a family manifest's `target_content_sha256` pins:
    it is arena-independent, so two imports of the same bytes agree.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Exact displayed hierarchical declaration name.
        """
    @property
    def kind(self) -> builtins.str:
        r"""
        Stable declaration variant.
        """
    @property
    def content_sha256(self) -> builtins.str:
        r"""
        Domain-separated structural SHA-256 of the complete checked content.
        """
    @property
    def dependency_sha256(self) -> builtins.str:
        r"""
        Domain-separated SHA-256 of the sorted direct-dependency bindings.
        """
    @property
    def dependencies(self) -> builtins.list[DeclarationDependency]:
        r"""
        Sorted, deduplicated direct-dependency bindings.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DeclineReason:
    r"""
    Why a bounded producer declined, as its own typed enum variant.

    `kind` is the Rust variant name verbatim (`"BinderBudgetExceeded"`,
    `"NotEqualityGoal"`, …) and `detail` its payload, or `None` for a variant
    that carries none. `producer` says which producer's vocabulary `kind` comes
    from: the two enums overlap but are **not** the same type and do not have
    the same variants.
    """
    @property
    def producer(self) -> builtins.str:
        r"""
        Which producer's vocabulary `kind` belongs to.
        """
    @property
    def kind(self) -> builtins.str:
        r"""
        The Rust variant name, verbatim. Branch on this, never on the message.
        """
    @property
    def detail(self) -> typing.Optional[builtins.str]:
        r"""
        The variant's payload, or `None` for a variant that carries none.
        """
    @property
    def message(self) -> builtins.str:
        r"""
        The Rust `Display` rendering.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...

class Declined(_native.AxeyumError):
    r"""
    A producer declined the goal. `unknown` and `declined` are values, and this is how the value crosses a `raise`.
    """
    @property
    def reason(self) -> DeclineReason:
        r"""
        The typed refusal: which producer, which kind, and its detail.
        """

@typing.final
class ImportLimits:
    r"""
    Resource limits applied before a stream can grow the kernel arenas without
    bound.

    The defaults are the Rust `ImportLimits::default()` values quoted:
    `max_line_bytes = 16 * 1024 * 1024` (16 MiB) and `max_records = 2_000_000`.
    `producers::tests::binding_defaults_match_rust` pins them, so a drift on
    either side fails a test rather than silently changing what Python imports
    under.
    """
    @property
    def max_line_bytes(self) -> builtins.int:
        r"""
        Maximum bytes in one NDJSON record, including its trailing newline.
        """
    @property
    def max_records(self) -> builtins.int:
        r"""
        Maximum number of records, including the metadata record.
        """
    def __new__(cls, max_line_bytes: builtins.int = 16777216, max_records: builtins.int = 2000000) -> ImportLimits:
        r"""
        Limits with the Rust defaults, or the given overrides.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class ImportReport:
    r"""
    Counts and provenance for a successfully admitted stream.

    `substituted_theorems` is the field that tells "our own re-derivation" apart
    from "an admitted trusted declaration": every name in it still reports
    `kind == "theorem"` in `declaration_identities`, which is structurally true
    and would otherwise be indistinguishable.
    """
    @property
    def format_version(self) -> builtins.str:
        r"""
        Export-format version from the first record.
        """
    @property
    def lean_version(self) -> builtins.str:
        r"""
        Official Lean version recorded by the exporter.
        """
    @property
    def lean_githash(self) -> builtins.str:
        r"""
        Official Lean source hash recorded by the exporter.
        """
    @property
    def exporter_version(self) -> builtins.str:
        r"""
        Exporter version recorded by the stream.
        """
    @property
    def names(self) -> builtins.int:
        r"""
        Number of non-anonymous exported names.
        """
    @property
    def levels(self) -> builtins.int:
        r"""
        Number of nonzero exported universe-level records.
        """
    @property
    def expressions(self) -> builtins.int:
        r"""
        Number of exported expression records.
        """
    @property
    def declaration_records(self) -> builtins.int:
        r"""
        Number of exported declaration records; an inductive group is one.
        """
    @property
    def admitted_declarations(self) -> builtins.int:
        r"""
        Number of kernel declarations admitted.
        """
    @property
    def axioms(self) -> builtins.list[builtins.str]:
        r"""
        Imported axiom names. Their types were checked; their propositions
        remain assumptions until discharged separately.
        """
    @property
    def identity_version(self) -> builtins.str:
        r"""
        Identity schema for the two manifests below.
        """
    @property
    def axiom_identities(self) -> builtins.list[AxiomIdentity]:
        r"""
        Imported axiom name/type identities.
        """
    @property
    def declaration_identities(self) -> builtins.list[DeclarationIdentity]:
        r"""
        Canonical identities for every admitted declaration.
        """
    @property
    def substituted_theorems(self) -> builtins.list[builtins.str]:
        r"""
        Theorems this crate reconstructed and independently re-checked itself,
        in place of the untrusted wire-supplied type/value.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ModEqCandidate:
    r"""
    A `ModEq`-family candidate: a proposed proof term plus the binder depth the
    search reached.

    Deliberately **not** the same class as [`PyCandidate`]. The two producers
    measure different quantities against different budgets, and a single class
    with `inductions_used = None` would make "this producer performs no
    inductions" indistinguishable from "nobody measured".
    """
    @property
    def proof(self) -> kernel.ExprId:
        r"""
        The proposed proof term. Untrusted until the kernel re-checks it.
        """
    @property
    def binders_used(self) -> builtins.int:
        r"""
        Leading `Pi` binders peeled, out of `MODEQ_MAX_BINDERS`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class StatementImport:
    r"""
    One proof-isolated proposition imported as the value of a transparent
    `definition : Prop`.

    The kernel, the goal and the target name are one unit: the handles are
    indices into *this* import's kernel and mean nothing anywhere else. So
    `kernel()` returns the **same** `Kernel` object every time — a producer
    mutates it (interning the proof term, admitting the candidate) and the goal
    stays valid across that. Getting a fresh copy each call would silently
    invalidate every handle already handed out.

    The Rust `into_parts` is deliberately not bound: it consumes the import, and
    the four non-consuming accessors give the same values.
    """
    def goal(self) -> kernel.ExprId:
        r"""
        The checked proposition to hand to an untrusted proof producer.
        """
    def target_name(self) -> kernel.NameId:
        r"""
        The target definition name in this import's kernel.
        """
    def report(self) -> ImportReport:
        r"""
        The completed import inventory and canonical declaration identities.
        """
    def kernel(self) -> kernel.Kernel:
        r"""
        The independently checked environment holding the goal's definitional
        dependencies and no proof of the goal.

        The same object on every call: handles stay valid across a producer's
        mutations.
        """
    def __repr__(self) -> builtins.str: ...

class StatementImportError(_native.AxeyumError):
    r"""
    A `lean4export` statement could not be imported.
    """
    @property
    def variant(self) -> builtins.str:
        r"""
        The Rust error variant name. Never match on the message text.
        """
    @property
    def debug(self) -> builtins.str:
        r"""
        The full Rust `Debug` rendering of the failure.
        """

def audit_circularity(kernel: kernel.Kernel, candidate: kernel.NameId, target: kernel.NameId) -> CircularityAudit:
    r"""
    Audits an already-admitted `candidate` against its `target`.

    A pure function of the kernel's own dependency graph: the same check the
    `modeq_family_operation` driver runs, and the same one the adversarial
    fixture in `tests/modeq_family_operation.rs` proves actually rejects a
    candidate built to cite its own target.

    # Errors

    Raises `EpochError` if either name was interned by another kernel.
    """

def import_candidate_statement_ndjson(source: typing.Any, limits: typing.Optional[ImportLimits], target: builtins.str, candidates: typing.Sequence[builtins.str]) -> StatementImport:
    r"""
    Imports a proof-free target plus an exact axiom-free theorem candidate set.

    Unlike [`import_statement_ndjson`], this capsule may carry proof-bearing
    declarations, but only those whose exact names occur in `candidates`; every
    one is independently kernel-checked and must have an empty measured axiom
    footprint. The target remains a transparent `definition : Prop`, never a
    theorem. The bounded-application producer must still receive the same names
    explicitly and cannot scan the returned environment.

    `source` is a path (`str` / `os.PathLike`) or the NDJSON `bytes`. `limits`
    of `None` uses the Rust `ImportLimits::default()`.

    # Errors

    Raises `TypeError` for an invalid source, `OSError` for an unreadable path,
    and `StatementImportError` for any wire, target-isolation, candidate-identity
    or axiom-footprint failure.
    """

def import_statement_ndjson(source: typing.Any, limits: typing.Optional[ImportLimits], target: builtins.str) -> StatementImport:
    r"""
    Imports one proof-isolated proposition from a `lean4export` NDJSON stream.

    This is the front door for "hand an untrusted producer a goal". It rejects
    every axiom, theorem, opaque and quotient declaration in the stream except
    the ones this import itself reconstructed (`report.substituted_theorems`),
    so the returned kernel can define the goal but cannot prove it.

    `source` is a path (`str` / `os.PathLike`) or the NDJSON `bytes`. `limits`
    of `None` uses the Rust `ImportLimits::default()`.

    # Errors

    Raises `TypeError` for a `source` that is neither, `OSError` if the file
    cannot be opened, and `StatementImportError` if the stream fails the
    proof-isolation contract.
    """

def propose_bounded_application(kernel: kernel.Kernel, goal: kernel.ExprId, declarations: typing.Sequence[kernel.NameId]) -> ApplicationCandidate:
    r"""
    Proposes a bounded type-directed application proof from exact declarations.

    `declarations` is the retrieval boundary: the producer does not scan the
    environment. Do not include the target theorem. The returned proof remains
    untrusted until the same kernel admits it as a theorem of `goal`.

    # Errors

    Raises `EpochError` for a foreign goal/name handle and `Declined` with a
    typed bounded-application reason when the fixed search budget finds no term.
    """

def propose_bounded_induction(kernel: kernel.Kernel, goal: kernel.ExprId) -> Candidate:
    r"""
    Proposes a bounded structural-induction proof of `goal`.

    `Eq.refl`, and where that is stuck, a bounded induction over a discovered
    zero/succ-shaped binder plus congruence rewrites driven by the induction
    hypothesis. Target-agnostic: it never dispatches on a declaration name or a
    fact id, and every structural fact it uses is discovered from `kernel`'s own
    declarations.

    The returned proof is **untrusted**. Admit it with
    `Kernel.add_declaration(Declaration.theorem(name, [], goal, candidate.proof))`
    and read `Kernel.axiom_footprint` afterwards; the kernel, not this call, is
    what decides.

    # Errors

    Raises `EpochError` if `goal` was interned by another kernel, and `Declined`
    carrying a typed `.reason` when the bounded search does not close the goal.
    """

def propose_bounded_induction_with_rewrites(kernel: kernel.Kernel, goal: kernel.ExprId, declarations: typing.Sequence[kernel.NameId]) -> Candidate:
    r"""
    Proposes bounded induction with exact retrieved declarations available for
    typed equality rewriting in the current induction scope.

    `declarations` is an explicit retrieval boundary, not proof authority. The
    producer preserves caller order, ignores unusable candidates, applies fixed
    Rust-side budgets, and returns an untrusted term for same-kernel admission.

    # Errors

    Raises `EpochError` for a foreign goal/name handle and `Declined` with the
    bounded-induction reason when the combined grammar cannot close the goal.
    """

def propose_modeq_family(kernel: kernel.Kernel, goal: kernel.ExprId) -> ModEqCandidate:
    r"""
    Proposes a bounded `Eq`/`Iff`-combinator proof of `goal`.

    The `ModEq` definitional-equivalence family: `ModEq n a b` unfolds
    transparently to `a % n = b % n`, so every lemma this schema targets is a
    plain `Eq`/`Iff` combinator once that unfolding is taken. The producer never
    names `Int`, `Nat`, `ModEq`, `%`, or any target or sibling declaration.

    The returned proof is **untrusted**; see
    [`propose_bounded_induction`](fn.propose_bounded_induction.html).

    # Errors

    Raises `EpochError` if `goal` was interned by another kernel, and `Declined`
    carrying a typed `.reason` when the bounded search does not close the goal.
    """

def transport_native_candidate(statement: StatementImport, candidate: builtins.str) -> CandidateTransport:
    r"""
    Check one retrieved native theorem into an imported goal's private kernel.

    The candidate namespace deterministically selects the independently rebuilt
    native prelude (`Nat`, `Int`, `Rat`, `CReal`, or `Complex`). Existing target
    theorems are compatibility-checked; absent ones go through checked theorem
    composition. The target proof remains absent, and no fact or operation
    authority is granted. The statement import keeps the same Python `Kernel`
    object and epoch because composition clones and only extends its arenas, so
    all previously issued goal/name handles remain valid.

    # Errors

    Raises `CandidateTransportError` with `.variant` and `.debug` when the
    namespace is unsupported or the exact source root cannot be safely reused
    or composed. A failure never changes the statement import's kernel.
    """
