# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Word",
]

@typing.final
class Word:
    r"""
    A fixed-width A0 word with arithmetic values reduced modulo `2**width`.
    """
    @property
    def width(self) -> builtins.int:
        r"""
        Width in bits.
        """
    @property
    def unsigned(self) -> builtins.int:
        r"""
        Unsigned reading of the stored bit pattern.
        """
    @property
    def signed(self) -> builtins.int:
        r"""
        Signed two's-complement reading of the stored bit pattern.
        """
    @property
    def high_bit(self) -> builtins.bool:
        r"""
        Whether the most-significant bit is one.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, width: builtins.int, value: builtins.int) -> Word:
        r"""
        Construct a word, reducing `value` modulo `2**width`.
        """
    @staticmethod
    def from_little_endian(bytes: typing.Sequence[builtins.int]) -> Word:
        r"""
        Construct a word by joining least-significant byte first.
        """
    def little_endian_bytes(self) -> bytes:
        r"""
        Bytes from least significant to most significant.
        """
    def zero_extend(self, new_width: builtins.int) -> Word:
        r"""
        Return the same pattern widened with zero high bits.
        """
    def sign_extend(self, new_width: builtins.int) -> Word:
        r"""
        Return the same signed value widened by repeating the sign bit.
        """
    def truncate(self, new_width: builtins.int) -> Word:
        r"""
        Keep only the least-significant `new_width` bits.
        """
    def __repr__(self) -> builtins.str: ...
    def __int__(self) -> builtins.int: ...

