-- Auto-generated by axeyum-lean-kernel: a self-contained re-check of a
-- reconstructed refutation. `prelude` avoids clashing with Lean core.
prelude
set_option linter.unusedVariables false
-- These declarations are proofs, not programs: a recursor-based `def`
-- has no compiled code and Lean's code generator declines it
-- ("code generator does not support recursor `T.rec` yet"). The section
-- suppresses codegen only; it does not weaken type checking.
noncomputable section

inductive False : Prop where
def Not : ((x0 : Prop) -> Prop) :=
  fun (x0 : Prop) => ((x1 : x0) -> False)
axiom Real : Sort (1)
axiom Real.mul : ((x0 : Real) -> ((x1 : Real) -> Real))
axiom Real.zero : Real
axiom Real.le : ((x0 : Real) -> ((x1 : Real) -> Prop))
axiom Real.lt : ((x0 : Real) -> ((x1 : Real) -> Prop))
axiom Real.lt_irrefl : ((x0 : Real) -> Not (Real.lt x0 x0))
axiom Real.lt_of_le_of_lt : ((x0 : Real) -> ((x1 : Real) -> ((x2 : Real) -> ((x3 : Real.le x0 x1) -> ((x4 : Real.lt x1 x2) -> Real.lt x0 x2)))))
axiom Real.sq_nonneg : ((x0 : Real) -> Real.le Real.zero (Real.mul x0 x0))
axiom axeyum.reconstruct.lra.x._0 : Real
axiom axeyum.reconstruct.lra.hyp._1 : Real.lt (Real.mul axeyum.reconstruct.lra.x._0 axeyum.reconstruct.lra.x._0) Real.zero

theorem axeyum_refutation : False :=
  Real.lt_irrefl Real.zero (Real.lt_of_le_of_lt Real.zero (Real.mul axeyum.reconstruct.lra.x._0 axeyum.reconstruct.lra.x._0) Real.zero (Real.sq_nonneg axeyum.reconstruct.lra.x._0) axeyum.reconstruct.lra.hyp._1)

#print axioms axeyum_refutation
