-- Auto-generated by axeyum-lean-kernel: a self-contained re-check of a
-- reconstructed refutation. `prelude` avoids clashing with Lean core.
prelude
set_option linter.unusedVariables false
-- These declarations are proofs, not programs: a recursor-based `def`
-- has no compiled code and Lean's code generator declines it
-- ("code generator does not support recursor `T.rec` yet"). The section
-- suppresses codegen only; it does not weaken type checking.
noncomputable section

-- Lean's own compiler-internal constants, which `Init.Prelude` declares
-- (`unsafe axiom lcErased : Type`) and `prelude` mode therefore omits.
-- Lean 4.34 runs code generation over a Prop-valued inductive that
-- carries data -- `Or`, `Exists`, `Nat.le` -- and its IR names these, so
-- without them the module dies on `Unknown constant lcErased` before any
-- proof is checked. Measured 2026-08-17: 21 of 77 crosscheck families were
-- rejected by 4.34.0-rc1 and accepted by 4.30.0, which is why the gate's
-- verdict depended on which toolchain happened to be installed.
--
-- They are compiler-only: no proof term mentions them, so they do NOT
-- enter any `#print axioms` footprint. Asserted, not assumed, by
-- `codegen_constants_are_declared_but_never_in_the_footprint`.
unsafe axiom lcErased : Type
unsafe axiom lcAny : Type
unsafe axiom lcVoid : Type

inductive False : Prop where
inductive And (x0 : Prop) (x1 : Prop) : Prop where
  | intro : ((x2 : x0) -> ((x3 : x1) -> And x0 x1))
inductive Or (x0 : Prop) (x1 : Prop) : Prop where
  | inl : ((x2 : x0) -> Or x0 x1)
  | inr : ((x2 : x1) -> Or x0 x1)
inductive Iff (x0 : Prop) (x1 : Prop) : Prop where
  | intro : ((x2 : ((x2 : x0) -> x1)) -> ((x3 : ((x3 : x1) -> x0)) -> Iff x0 x1))
def Not : ((x0 : Prop) -> Prop) :=
  fun (x0 : Prop) => ((x1 : x0) -> False)
axiom axeyum.reconstruct.prop._0 : Prop
axiom axeyum.reconstruct.prop._1 : Prop
axiom axeyum.reconstruct.em._2 : ((x0 : Prop) -> Or x0 (Not x0))
axiom axeyum.reconstruct.hyp._3 : Iff (And axeyum.reconstruct.prop._0 axeyum.reconstruct.prop._1) axeyum.reconstruct.prop._0
axiom axeyum.reconstruct.hyp._4 : Not (Iff (And axeyum.reconstruct.prop._0 axeyum.reconstruct.prop._1) axeyum.reconstruct.prop._0)

def axeyum_proof_share_0 :=
  Iff (And axeyum.reconstruct.prop._0 axeyum.reconstruct.prop._1) axeyum.reconstruct.prop._0

def axeyum_proof_share_1 :=
  Not axeyum_proof_share_0

def axeyum_proof_share_2 :=
  Or axeyum_proof_share_0

def axeyum_proof_share_3 :=
  axeyum_proof_share_2 axeyum_proof_share_1

def axeyum_proof_share_4 :=
  axeyum.reconstruct.em._2 axeyum_proof_share_0

def axeyum_proof_share_5 :=
  Or axeyum_proof_share_1

def axeyum_proof_share_6 :=
  axeyum_proof_share_5 axeyum_proof_share_0

theorem axeyum_refutation : False :=
  @False.rec.{0} (fun (x0 : False) => False) (@Or.rec axeyum_proof_share_0 axeyum_proof_share_1 (fun (x0 : axeyum_proof_share_3) => axeyum_proof_share_1) (fun (x0 : axeyum_proof_share_0) => @False.rec.{0} (fun (x1 : False) => axeyum_proof_share_1) (axeyum.reconstruct.hyp._4 x0)) (fun (x0 : axeyum_proof_share_1) => x0) (@Or.rec axeyum_proof_share_0 axeyum_proof_share_1 (fun (x0 : axeyum_proof_share_3) => axeyum_proof_share_3) (fun (x0 : axeyum_proof_share_0) => @Or.inl axeyum_proof_share_0 axeyum_proof_share_1 x0) (fun (x0 : axeyum_proof_share_1) => @Or.inr axeyum_proof_share_0 axeyum_proof_share_1 x0) axeyum_proof_share_4) (@Or.rec axeyum_proof_share_1 axeyum_proof_share_0 (fun (x0 : axeyum_proof_share_6) => axeyum_proof_share_0) (fun (x0 : axeyum_proof_share_1) => @False.rec.{0} (fun (x1 : False) => axeyum_proof_share_0) (x0 axeyum.reconstruct.hyp._3)) (fun (x0 : axeyum_proof_share_0) => x0) (@Or.rec axeyum_proof_share_0 axeyum_proof_share_1 (fun (x0 : axeyum_proof_share_3) => axeyum_proof_share_6) (fun (x0 : axeyum_proof_share_0) => @Or.inr axeyum_proof_share_1 axeyum_proof_share_0 x0) (fun (x0 : axeyum_proof_share_1) => @Or.inl axeyum_proof_share_1 axeyum_proof_share_0 x0) axeyum_proof_share_4)))

#print axioms axeyum_refutation
