-- Auto-generated by axeyum-lean-kernel: a self-contained re-check of a
-- reconstructed refutation. `prelude` avoids clashing with Lean core.
prelude
set_option linter.unusedVariables false
-- These declarations are proofs, not programs: a recursor-based `def`
-- has no compiled code and Lean's code generator declines it
-- ("code generator does not support recursor `T.rec` yet"). The section
-- suppresses codegen only; it does not weaken type checking.
noncomputable section

-- Lean's own compiler-internal constants, which `Init.Prelude` declares
-- (`unsafe axiom lcErased : Type`) and `prelude` mode therefore omits.
-- Lean 4.34 runs code generation over a Prop-valued inductive that
-- carries data -- `Or`, `Exists`, `Nat.le` -- and its IR names these, so
-- without them the module dies on `Unknown constant lcErased` before any
-- proof is checked. Measured 2026-08-17: 21 of 77 crosscheck families were
-- rejected by 4.34.0-rc1 and accepted by 4.30.0, which is why the gate's
-- verdict depended on which toolchain happened to be installed.
--
-- They are compiler-only: no proof term mentions them, so they do NOT
-- enter any `#print axioms` footprint. Asserted, not assumed, by
-- `codegen_constants_are_declared_but_never_in_the_footprint`.
unsafe axiom lcErased : Type
unsafe axiom lcAny : Type
unsafe axiom lcVoid : Type

inductive False : Prop where
inductive Eq.{u} (x0 : Sort (u)) (x1 : x0) : ((x2 : x0) -> Prop) where
  | refl : Eq x0 x1 x1
def Not : ((x0 : Prop) -> Prop) :=
  fun (x0 : Prop) => ((x1 : x0) -> False)
axiom α : Sort (1)
inductive axeyum.reconstruct.dtfam._0 : Sort (1) where
  | c0 : ((x0 : α) -> ((x1 : α) -> axeyum.reconstruct.dtfam._0))
axiom axeyum.reconstruct.fld_0._1 : α
axiom axeyum.reconstruct.fld_1._2 : α
axiom axeyum.reconstruct.fld_0._3 : α
axiom axeyum.reconstruct.fld_1._4 : α
axiom axeyum.reconstruct.hyp._6 : Eq.{1} axeyum.reconstruct.dtfam._0 (@axeyum.reconstruct.dtfam._0.c0 axeyum.reconstruct.fld_0._1 axeyum.reconstruct.fld_1._2) (@axeyum.reconstruct.dtfam._0.c0 axeyum.reconstruct.fld_0._3 axeyum.reconstruct.fld_1._4)
axiom axeyum.reconstruct.hyp._7 : Not (Eq.{1} α axeyum.reconstruct.fld_0._1 axeyum.reconstruct.fld_0._3)

theorem axeyum_refutation : False :=
  axeyum.reconstruct.hyp._7 (@Eq.rec.{0, 1} axeyum.reconstruct.dtfam._0 (@axeyum.reconstruct.dtfam._0.c0 axeyum.reconstruct.fld_0._1 axeyum.reconstruct.fld_1._2) (fun (x0 : axeyum.reconstruct.dtfam._0) => fun (x1 : Eq.{1} axeyum.reconstruct.dtfam._0 (@axeyum.reconstruct.dtfam._0.c0 axeyum.reconstruct.fld_0._1 axeyum.reconstruct.fld_1._2) x0) => Eq.{1} α ((fun (x2 : axeyum.reconstruct.dtfam._0) => @axeyum.reconstruct.dtfam._0.rec.{1} (fun (x3 : axeyum.reconstruct.dtfam._0) => α) (fun (x3 : α) => fun (x4 : α) => x3) x2) (@axeyum.reconstruct.dtfam._0.c0 axeyum.reconstruct.fld_0._1 axeyum.reconstruct.fld_1._2)) ((fun (x2 : axeyum.reconstruct.dtfam._0) => @axeyum.reconstruct.dtfam._0.rec.{1} (fun (x3 : axeyum.reconstruct.dtfam._0) => α) (fun (x3 : α) => fun (x4 : α) => x3) x2) x0)) (@Eq.refl.{1} α ((fun (x0 : axeyum.reconstruct.dtfam._0) => @axeyum.reconstruct.dtfam._0.rec.{1} (fun (x1 : axeyum.reconstruct.dtfam._0) => α) (fun (x1 : α) => fun (x2 : α) => x1) x0) (@axeyum.reconstruct.dtfam._0.c0 axeyum.reconstruct.fld_0._1 axeyum.reconstruct.fld_1._2))) (@axeyum.reconstruct.dtfam._0.c0 axeyum.reconstruct.fld_0._3 axeyum.reconstruct.fld_1._4) axeyum.reconstruct.hyp._6)

#print axioms axeyum_refutation
