# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum._native import cas
import builtins
import fractions
import typing
__all__ = [
    "Interval",
    "SetInterval",
    "approximate_real_roots",
    "count_real_roots_in",
    "evaluate_polynomial_over",
    "isolate_real_roots",
]

@typing.final
class Interval:
    r"""
    A closed real interval with exact rational endpoints.
    """
    @property
    def lower(self) -> fractions.Fraction:
        r"""
        The lower endpoint.
        
        # Errors
        
        Propagates any Python error raised while building the fraction.
        """
    @property
    def upper(self) -> fractions.Fraction:
        r"""
        The upper endpoint.
        
        # Errors
        
        Propagates any Python error raised while building the fraction.
        """
    def __new__(cls, a: builtins.int  |  fractions.Fraction  |  cas.Rational, b: builtins.int  |  fractions.Fraction  |  cas.Rational) -> typing.Optional[Interval]:
        r"""
        `[a, b]`, or `None` when `a > b`.
        
        # Errors
        
        Raises `ValueError` when an endpoint is not an exact rational.
        """
    @staticmethod
    def degenerate(a: builtins.int  |  fractions.Fraction  |  cas.Rational) -> Interval:
        r"""
        The single-point interval `[a, a]`.
        
        # Errors
        
        Raises `ValueError` when `a` is not an exact rational.
        """
    def width(self) -> fractions.Fraction:
        r"""
        `upper - lower`.
        
        # Errors
        
        Propagates any Python error raised while building the fraction.
        """
    def midpoint(self) -> fractions.Fraction:
        r"""
        The midpoint.
        
        # Errors
        
        Propagates any Python error raised while building the fraction.
        """
    def contains(self, x: builtins.int  |  fractions.Fraction  |  cas.Rational) -> builtins.bool:
        r"""
        Whether `x` lies in the interval.
        
        # Errors
        
        Raises `ValueError` when `x` is not an exact rational.
        """
    def contains_interval(self, other: Interval) -> builtins.bool:
        r"""
        Whether `other` is contained in this interval.
        """
    def add(self, other: Interval) -> typing.Optional[Interval]:
        r"""
        The sum enclosure, or `None` on overflow.
        """
    def sub(self, other: Interval) -> typing.Optional[Interval]:
        r"""
        The difference enclosure, or `None` on overflow.
        """
    def mul(self, other: Interval) -> typing.Optional[Interval]:
        r"""
        The product enclosure, or `None` on overflow.
        """
    def neg(self) -> typing.Optional[Interval]:
        r"""
        The negation enclosure, or `None` on overflow.
        """
    def div(self, other: Interval) -> typing.Optional[Interval]:
        r"""
        The quotient enclosure, or `None`.
        
        **`None` when the divisor straddles zero is the soundness guard, not an
        error.** No finite interval encloses `1/[-1, 1]`, so returning anything
        there would be a wrong enclosure; declining is the only sound answer, and
        the same `None` also covers an overflow.
        """
    def pow(self, n: builtins.int) -> typing.Optional[Interval]:
        r"""
        The `n`-th power enclosure, or `None` on overflow.
        """
    def intersection(self, other: Interval) -> typing.Optional[Interval]:
        r"""
        The intersection, or `None` when the intervals are disjoint.
        """
    def hull(self, other: Interval) -> typing.Optional[Interval]:
        r"""
        The convex hull, or `None` on overflow.
        """
    def abs(self) -> typing.Optional[Interval]:
        r"""
        The absolute-value enclosure, or `None` on overflow.
        """
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SetInterval:
    r"""
    An interval from `axeyum_cas::sets`, with open/closed bounds.
    
    Named apart from [`Interval`] deliberately: the two are different types with
    different guarantees, and the crate's own inventory flags the collision.
    """
    @staticmethod
    def closed(a: builtins.int  |  fractions.Fraction  |  cas.Rational, b: builtins.int  |  fractions.Fraction  |  cas.Rational) -> SetInterval:
        r"""
        `[a, b]`.
        
        # Errors
        
        Raises `ValueError` when an endpoint is not an exact rational.
        """
    @staticmethod
    def open(a: builtins.int  |  fractions.Fraction  |  cas.Rational, b: builtins.int  |  fractions.Fraction  |  cas.Rational) -> SetInterval:
        r"""
        `(a, b)`.
        
        # Errors
        
        Raises `ValueError` when an endpoint is not an exact rational.
        """
    @staticmethod
    def universe() -> SetInterval:
        r"""
        All of the reals.
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Whether the interval contains no points.
        """
    def contains(self, x: builtins.int  |  fractions.Fraction  |  cas.Rational) -> builtins.bool:
        r"""
        Whether `x` lies in the interval.
        
        # Errors
        
        Raises `ValueError` when `x` is not an exact rational.
        """
    def __repr__(self) -> builtins.str: ...

def approximate_real_roots(p: typing.Sequence[builtins.int  |  fractions.Fraction  |  cas.Rational], width: builtins.int  |  fractions.Fraction  |  cas.Rational) -> typing.Optional[builtins.list[fractions.Fraction]]:
    r"""
    Rational approximations of every real root, each within `width`.
    
    `width` is the caller's explicit resource limit; there is no hidden default.
    
    # Errors
    
    Raises `ValueError` when a coefficient or `width` is not an exact rational.
    """

def count_real_roots_in(p: typing.Sequence[builtins.int  |  fractions.Fraction  |  cas.Rational], lower: builtins.int  |  fractions.Fraction  |  cas.Rational, upper: builtins.int  |  fractions.Fraction  |  cas.Rational) -> typing.Optional[builtins.int]:
    r"""
    The exact number of distinct real roots of `p` in `[lower, upper]`.
    
    `p` is dense, lowest degree first. `None` means the exact arithmetic left
    `i128` — an honest undecided, never a zero.
    
    # Errors
    
    Raises `ValueError` when a coefficient or endpoint is not an exact rational.
    """

def evaluate_polynomial_over(coeffs: typing.Sequence[builtins.int  |  fractions.Fraction  |  cas.Rational], x: Interval) -> typing.Optional[Interval]:
    r"""
    The interval enclosure of a dense polynomial over `x`.
    
    # Errors
    
    Raises `ValueError` when a coefficient is not an exact rational.
    """

def isolate_real_roots(p: typing.Sequence[builtins.int  |  fractions.Fraction  |  cas.Rational]) -> typing.Optional[builtins.list[tuple[fractions.Fraction, fractions.Fraction]]]:
    r"""
    Isolating intervals, one per distinct real root, ascending.
    
    # Errors
    
    Raises `ValueError` when a coefficient is not an exact rational.
    """

