//! `AlgS.Subgroup.*` — the residue of roadmap W1-11: subgroups of an
//! **abstract** `AlgS.Group`, and the meet-semilattice they form, built by the
//! setoid route (ADR-1595, ADR-1609). W1-11's homomorphism/kernel/image half
//! landed with `AlgS.Hom.*`; this is the subobject half, and it closes back
//! onto that one with `AlgS.Subgroup.ker_isSub`.
//!
//! # A subgroup is a predicate, and the setoid adds exactly one obligation
//!
//! This kernel has no `Subtype` and no `Sigma` (both verified ABSENT,
//! ADR-1595), so a subgroup cannot be a carrier. It is a **predicate**
//! `S : G.carrier -> Prop` together with closure conditions — the same shape
//! `AlgS.Hom.ker` and `AlgS.Hom.image` already use.
//!
//! `AlgS.Subgroup.IsSub` has **four** conjuncts where the `Eq`-flavored
//! version would have three:
//!
//! | conjunct | free under `Eq`? |
//! |---|---|
//! | `forall a b, G.equiv a b -> S a -> S b` | **YES** — `Eq.subst` gives it |
//! | `S G.e` | no |
//! | `forall a b, S a -> S b -> S (G.op a b)` | no |
//! | `forall a, S a -> S (G.inv a)` | no |
//!
//! So the measured setoid cost of the whole subobject layer is **one field**,
//! and it is not decoration: `AlgS.Subgroup.bot_le` cannot be proved without
//! it, because the trivial subgroup over a setoid is the equivalence CLASS of
//! `G.e` (`fun a => G.equiv a G.e`), not the singleton — and showing it sits
//! inside every subgroup is exactly a transport along `G.equiv`.
//!
//! # The lattice
//!
//! Order is implication (`le S T := forall a, S a -> T a`), meet is
//! intersection, `top` is `fun _ => True`, `bot` is the class of the
//! identity. `inter_le_left`/`inter_le_right`/`le_inter` are the
//! greatest-lower-bound property, so this is a bounded meet-semilattice with
//! `IsSub` closed under all three constructions. The JOIN is not here: the
//! subgroup generated by a union needs a word/closure construction, which
//! needs an inductive family over `G.carrier` — sized in ADR-1609.

use crate::Kernel;
use crate::KernelError;
use crate::LogicPrelude;
use crate::env::Declaration;
use crate::env::ReducibilityHint;
use crate::expr::ExprId;
use crate::name::NameId;

use super::structures::{RecordNames, app2, arrow, lam_over, pi_over, sel};
use super::structures_setoid::idx;

// ---------------------------------------------------------------------------
// Free-variable block, disjoint from 21_xxx / 22_xxx / 23_xxx.
// ---------------------------------------------------------------------------

const G_FV: u64 = 24_000;
const S_FV: u64 = 24_001;
const T_FV: u64 = 24_002;
const U_FV: u64 = 24_003;
const A_FV: u64 = 24_010;
const B_FV: u64 = 24_011;
const H1_FV: u64 = 24_020;
const H2_FV: u64 = 24_021;
const HS_FV: u64 = 24_030;
const HT_FV: u64 = 24_031;
// Homomorphism binders for `ker_isSub`.
const KH_FV: u64 = 24_040;
const KF_FV: u64 = 24_041;
const KFC_FV: u64 = 24_042;
const KFM_FV: u64 = 24_043;

fn t_app(k: &mut Kernel, f: ExprId, xs: &[ExprId]) -> ExprId {
    let mut e = f;
    for x in xs {
        e = k.app(e, *x);
    }
    e
}

// ---------------------------------------------------------------------------
// The ambient group's selectors.
// ---------------------------------------------------------------------------

struct GCtx {
    g: ExprId,
    group_ty: ExprId,
    carrier: ExprId,
    equiv: ExprId,
    refl: ExprId,
    symm: ExprId,
    trans: ExprId,
    op: ExprId,
    op_congr: ExprId,
    e: ExprId,
    inv: ExprId,
    inv_congr: ExprId,
    ident_l: ExprId,
    ident_r: ExprId,
    inv_l: ExprId,
    /// `G.carrier -> Prop`, the type of a subgroup predicate.
    sub_ty: ExprId,
}

fn gctx(k: &mut Kernel, group: &RecordNames, fv: u64) -> GCtx {
    use idx::group::{
        CARRIER, E, EQUIV, EQUIV_REFL, EQUIV_SYMM, EQUIV_TRANS, IDENT_L, IDENT_R, INV, INV_CONGR,
        INV_L, OP, OP_CONGR,
    };
    let group_ty = k.const_(group.ind, vec![]);
    let g = k.fvar(fv);
    let carrier = sel(k, group, CARRIER, g);
    let l0 = k.level_zero();
    let prop = k.sort(l0);
    let sub_ty = arrow(k, carrier, prop);
    GCtx {
        g,
        group_ty,
        carrier,
        equiv: sel(k, group, EQUIV, g),
        refl: sel(k, group, EQUIV_REFL, g),
        symm: sel(k, group, EQUIV_SYMM, g),
        trans: sel(k, group, EQUIV_TRANS, g),
        op: sel(k, group, OP, g),
        op_congr: sel(k, group, OP_CONGR, g),
        e: sel(k, group, E, g),
        inv: sel(k, group, INV, g),
        inv_congr: sel(k, group, INV_CONGR, g),
        ident_l: sel(k, group, IDENT_L, g),
        ident_r: sel(k, group, IDENT_R, g),
        inv_l: sel(k, group, INV_L, g),
        sub_ty,
    }
}

impl GCtx {
    fn eqv(&self, k: &mut Kernel, a: ExprId, b: ExprId) -> ExprId {
        app2(k, self.equiv, a, b)
    }
    fn tr(
        &self,
        k: &mut Kernel,
        a: ExprId,
        b: ExprId,
        c: ExprId,
        h1: ExprId,
        h2: ExprId,
    ) -> ExprId {
        t_app(k, self.trans, &[a, b, c, h1, h2])
    }
    fn sy(&self, k: &mut Kernel, a: ExprId, b: ExprId, h: ExprId) -> ExprId {
        t_app(k, self.symm, &[a, b, h])
    }
}

// ---------------------------------------------------------------------------
// The four closure statements, and the `And` plumbing over them.
// ---------------------------------------------------------------------------

/// `forall a b, G.equiv a b -> S a -> S b` — **the setoid-only obligation**.
fn respects_stmt(k: &mut Kernel, c: &GCtx, s: ExprId) -> ExprId {
    let a = k.fvar(A_FV);
    let b = k.fvar(B_FV);
    let hyp1 = c.eqv(k, a, b);
    let hyp2 = k.app(s, a);
    let concl = k.app(s, b);
    let t = pi_over(k, H2_FV, hyp2, concl);
    let t = pi_over(k, H1_FV, hyp1, t);
    let t = pi_over(k, B_FV, c.carrier, t);
    pi_over(k, A_FV, c.carrier, t)
}

/// `S G.e`.
fn mem_e_stmt(k: &mut Kernel, c: &GCtx, s: ExprId) -> ExprId {
    k.app(s, c.e)
}

/// `forall a b, S a -> S b -> S (G.op a b)`.
fn closed_op_stmt(k: &mut Kernel, c: &GCtx, s: ExprId) -> ExprId {
    let a = k.fvar(A_FV);
    let b = k.fvar(B_FV);
    let hyp1 = k.app(s, a);
    let hyp2 = k.app(s, b);
    let ab = app2(k, c.op, a, b);
    let concl = k.app(s, ab);
    let t = pi_over(k, H2_FV, hyp2, concl);
    let t = pi_over(k, H1_FV, hyp1, t);
    let t = pi_over(k, B_FV, c.carrier, t);
    pi_over(k, A_FV, c.carrier, t)
}

/// `forall a, S a -> S (G.inv a)`.
fn closed_inv_stmt(k: &mut Kernel, c: &GCtx, s: ExprId) -> ExprId {
    let a = k.fvar(A_FV);
    let hyp = k.app(s, a);
    let ia = k.app(c.inv, a);
    let concl = k.app(s, ia);
    let t = pi_over(k, H1_FV, hyp, concl);
    pi_over(k, A_FV, c.carrier, t)
}

fn four_stmts(k: &mut Kernel, c: &GCtx, s: ExprId) -> [ExprId; 4] {
    [
        respects_stmt(k, c, s),
        mem_e_stmt(k, c, s),
        closed_op_stmt(k, c, s),
        closed_inv_stmt(k, c, s),
    ]
}

/// `And p0 (And p1 (And p2 p3))`.
fn nest_and(k: &mut Kernel, lg: &LogicPrelude, props: &[ExprId; 4]) -> ExprId {
    let and_c = k.const_(lg.and, vec![]);
    let mut acc = props[3];
    for p in props[..3].iter().rev() {
        acc = app2(k, and_c, *p, acc);
    }
    acc
}

/// The `And.intro` chain matching [`nest_and`].
fn intro_and(
    k: &mut Kernel,
    lg: &LogicPrelude,
    props: &[ExprId; 4],
    proofs: &[ExprId; 4],
) -> ExprId {
    let and_c = k.const_(lg.and, vec![]);
    let mut tail_prop = props[3];
    let mut tail_val = proofs[3];
    for i in (0..3).rev() {
        let and_intro = k.const_(lg.and_intro, vec![]);
        tail_val = t_app(k, and_intro, &[props[i], tail_prop, proofs[i], tail_val]);
        tail_prop = app2(k, and_c, props[i], tail_prop);
    }
    tail_val
}

/// Project conjunct `which` (0..3) out of a proof of [`nest_and`].
fn project_and(
    k: &mut Kernel,
    lg: &LogicPrelude,
    props: &[ExprId; 4],
    h: ExprId,
    which: usize,
) -> ExprId {
    let and_c = k.const_(lg.and, vec![]);
    // `tails[i]` is what remains after `i` `And.right`s.
    let mut tails = vec![props[3]];
    for p in props[..3].iter().rev() {
        let last = *tails.last().expect("non-empty");
        tails.push(app2(k, and_c, *p, last));
    }
    tails.reverse();

    let mut cur = h;
    for (i, prop) in props.iter().enumerate().take(which) {
        let and_right = k.const_(lg.and_right, vec![]);
        cur = t_app(k, and_right, &[*prop, tails[i + 1], cur]);
    }
    if which == 3 {
        cur
    } else {
        let and_left = k.const_(lg.and_left, vec![]);
        t_app(k, and_left, &[props[which], tails[which + 1], cur])
    }
}

// ---------------------------------------------------------------------------
// The five definitions.
// ---------------------------------------------------------------------------

/// `AlgS.Subgroup.IsSub : forall (G : AlgS.Group), (G.carrier -> Prop) -> Prop`.
fn declare_is_sub(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let props = four_stmts(k, &c, s);
    let body = nest_and(k, lg, &props);
    let value = lam_over(k, S_FV, c.sub_ty, body);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let l0 = k.level_zero();
    let prop = k.sort(l0);
    let ty = arrow(k, c.sub_ty, prop);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "IsSub");
    k.add_declaration(Declaration::Definition {
        name,
        uparams: vec![],
        ty,
        value,
        hint: ReducibilityHint::Regular(1),
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.le G S T := forall a, S a -> T a` — the lattice order.
fn declare_le(k: &mut Kernel, group: &RecordNames, ns: NameId) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let t = k.fvar(T_FV);
    let a = k.fvar(A_FV);
    let sa = k.app(s, a);
    let ta = k.app(t, a);
    let body = pi_over(k, H1_FV, sa, ta);
    let body = pi_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, T_FV, c.sub_ty, body);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let l0 = k.level_zero();
    let prop = k.sort(l0);
    let ty = arrow(k, c.sub_ty, prop);
    let ty = arrow(k, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "le");
    k.add_declaration(Declaration::Definition {
        name,
        uparams: vec![],
        ty,
        value,
        hint: ReducibilityHint::Regular(1),
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.inter G S T := fun a => And (S a) (T a)` — the meet.
fn declare_inter(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let t = k.fvar(T_FV);
    let a = k.fvar(A_FV);
    let sa = k.app(s, a);
    let ta = k.app(t, a);
    let and_c = k.const_(lg.and, vec![]);
    let body = app2(k, and_c, sa, ta);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, T_FV, c.sub_ty, body);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let ty = arrow(k, c.sub_ty, c.sub_ty);
    let ty = arrow(k, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "inter");
    k.add_declaration(Declaration::Definition {
        name,
        uparams: vec![],
        ty,
        value,
        hint: ReducibilityHint::Regular(1),
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.top G := fun _ => True`.
fn declare_top(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let true_c = k.const_(lg.true_, vec![]);
    let body = lam_over(k, A_FV, c.carrier, true_c);
    let value = lam_over(k, G_FV, c.group_ty, body);
    let ty = pi_over(k, G_FV, c.group_ty, c.sub_ty);

    let name = k.name_str(ns, "top");
    k.add_declaration(Declaration::Definition {
        name,
        uparams: vec![],
        ty,
        value,
        hint: ReducibilityHint::Regular(1),
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.bot G := fun a => G.equiv a G.e` — the trivial subgroup.
///
/// **Not the singleton `{G.e}`**: over a setoid the smallest subgroup is the
/// equivalence CLASS of the identity, because a subgroup must be closed under
/// `G.equiv` (`IsSub`'s first conjunct). `fun a => Eq a G.e` would not be a
/// subgroup of a carrier whose equality is a defined relation.
fn declare_bot(k: &mut Kernel, group: &RecordNames, ns: NameId) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let a = k.fvar(A_FV);
    let body = c.eqv(k, a, c.e);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, G_FV, c.group_ty, body);
    let ty = pi_over(k, G_FV, c.group_ty, c.sub_ty);

    let name = k.name_str(ns, "bot");
    k.add_declaration(Declaration::Definition {
        name,
        uparams: vec![],
        ty,
        value,
        hint: ReducibilityHint::Regular(1),
    })?;
    Ok(name)
}

// ---------------------------------------------------------------------------
// The four accessors.
// ---------------------------------------------------------------------------

fn declare_accessor(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    is_sub: NameId,
    which: usize,
    suffix: &str,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let props = four_stmts(k, &c, s);
    let hyp_ty = {
        let t = k.const_(is_sub, vec![]);
        app2(k, t, c.g, s)
    };
    let h = k.fvar(HS_FV);
    let proof = project_and(k, lg, &props, h, which);

    let value = lam_over(k, HS_FV, hyp_ty, proof);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let ty = pi_over(k, HS_FV, hyp_ty, props[which]);
    let ty = pi_over(k, S_FV, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, suffix);
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

// ---------------------------------------------------------------------------
// The order theorems.
// ---------------------------------------------------------------------------

/// `AlgS.Subgroup.le_refl : forall G S, le G S S`, by `fun a h => h`.
fn declare_le_refl(
    k: &mut Kernel,
    group: &RecordNames,
    le: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let a = k.fvar(A_FV);
    let sa = k.app(s, a);
    let h = k.fvar(H1_FV);
    let body = lam_over(k, H1_FV, sa, h);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, S_FV, c.sub_ty, body);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let concl = {
        let t = k.const_(le, vec![]);
        t_app(k, t, &[c.g, s, s])
    };
    let ty = pi_over(k, S_FV, c.sub_ty, concl);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "le_refl");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.le_trans : forall G S T U, le G S T -> le G T U -> le G S U`.
fn declare_le_trans(
    k: &mut Kernel,
    group: &RecordNames,
    le: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let t = k.fvar(T_FV);
    let u = k.fvar(U_FV);
    let le_st = {
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, s, t])
    };
    let le_tu = {
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, t, u])
    };
    let le_su = {
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, s, u])
    };
    let h1 = k.fvar(HS_FV);
    let h2 = k.fvar(HT_FV);
    let a = k.fvar(A_FV);
    let sa = k.app(s, a);
    let ha = k.fvar(H1_FV);
    let step1 = {
        let f = k.app(h1, a);
        k.app(f, ha)
    };
    let step2 = {
        let f = k.app(h2, a);
        k.app(f, step1)
    };
    let body = lam_over(k, H1_FV, sa, step2);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, HT_FV, le_tu, body);
    let value = lam_over(k, HS_FV, le_st, value);
    let value = lam_over(k, U_FV, c.sub_ty, value);
    let value = lam_over(k, T_FV, c.sub_ty, value);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let ty = pi_over(k, HT_FV, le_tu, le_su);
    let ty = pi_over(k, HS_FV, le_st, ty);
    let ty = pi_over(k, U_FV, c.sub_ty, ty);
    let ty = pi_over(k, T_FV, c.sub_ty, ty);
    let ty = pi_over(k, S_FV, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "le_trans");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.inter_le_left` / `..._right`: the meet is below both sides.
fn declare_inter_le(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    le: NameId,
    inter: NameId,
    left: bool,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let t = k.fvar(T_FV);
    let a = k.fvar(A_FV);
    let sa = k.app(s, a);
    let ta = k.app(t, a);
    let and_c = k.const_(lg.and, vec![]);
    let hyp = app2(k, and_c, sa, ta);
    let h = k.fvar(H1_FV);
    let proj = if left {
        let al = k.const_(lg.and_left, vec![]);
        t_app(k, al, &[sa, ta, h])
    } else {
        let ar = k.const_(lg.and_right, vec![]);
        t_app(k, ar, &[sa, ta, h])
    };
    let body = lam_over(k, H1_FV, hyp, proj);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, T_FV, c.sub_ty, body);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let concl = {
        let i = k.const_(inter, vec![]);
        let st = t_app(k, i, &[c.g, s, t]);
        let l = k.const_(le, vec![]);
        let target = if left { s } else { t };
        t_app(k, l, &[c.g, st, target])
    };
    let ty = pi_over(k, T_FV, c.sub_ty, concl);
    let ty = pi_over(k, S_FV, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let suffix = if left {
        "inter_le_left"
    } else {
        "inter_le_right"
    };
    let name = k.name_str(ns, suffix);
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.le_inter : forall G S T U, le G U S -> le G U T ->
/// le G U (inter G S T)` — the greatest-lower-bound half.
fn declare_le_inter(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    le: NameId,
    inter: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let t = k.fvar(T_FV);
    let u = k.fvar(U_FV);
    let le_us = {
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, u, s])
    };
    let le_ut = {
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, u, t])
    };
    let h1 = k.fvar(HS_FV);
    let h2 = k.fvar(HT_FV);
    let a = k.fvar(A_FV);
    let ua = k.app(u, a);
    let hu = k.fvar(H1_FV);
    let sa = k.app(s, a);
    let ta = k.app(t, a);
    let p1 = {
        let f = k.app(h1, a);
        k.app(f, hu)
    };
    let p2 = {
        let f = k.app(h2, a);
        k.app(f, hu)
    };
    let and_intro = k.const_(lg.and_intro, vec![]);
    let body = t_app(k, and_intro, &[sa, ta, p1, p2]);
    let body = lam_over(k, H1_FV, ua, body);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, HT_FV, le_ut, body);
    let value = lam_over(k, HS_FV, le_us, value);
    let value = lam_over(k, U_FV, c.sub_ty, value);
    let value = lam_over(k, T_FV, c.sub_ty, value);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let concl = {
        let i = k.const_(inter, vec![]);
        let st = t_app(k, i, &[c.g, s, t]);
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, u, st])
    };
    let ty = pi_over(k, HT_FV, le_ut, concl);
    let ty = pi_over(k, HS_FV, le_us, ty);
    let ty = pi_over(k, U_FV, c.sub_ty, ty);
    let ty = pi_over(k, T_FV, c.sub_ty, ty);
    let ty = pi_over(k, S_FV, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "le_inter");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.le_top : forall G S, le G S (top G)`.
fn declare_le_top(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    le: NameId,
    top: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let a = k.fvar(A_FV);
    let sa = k.app(s, a);
    let intro = k.const_(lg.true_intro, vec![]);
    let body = lam_over(k, H1_FV, sa, intro);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, S_FV, c.sub_ty, body);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let concl = {
        let tp = k.const_(top, vec![]);
        let tg = k.app(tp, c.g);
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, s, tg])
    };
    let ty = pi_over(k, S_FV, c.sub_ty, concl);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "le_top");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.bot_le : forall G S, IsSub G S -> le G (bot G) S`.
///
/// **This is the theorem that spends the setoid's extra conjunct.** From
/// `h : G.equiv a G.e` we must produce `S a` out of `S G.e`, and the only
/// route is `IsSub`'s `respects` field applied to `G.equivSymm h`. Under `Eq`
/// this step would be `Eq.subst` and the field would not exist.
#[allow(clippy::too_many_arguments)]
fn declare_bot_le(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    is_sub: NameId,
    le: NameId,
    bot: NameId,
    respects: NameId,
    mem_e: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let hyp_ty = {
        let t = k.const_(is_sub, vec![]);
        app2(k, t, c.g, s)
    };
    let hs = k.fvar(HS_FV);
    let a = k.fvar(A_FV);
    let ha_ty = c.eqv(k, a, c.e);
    let ha = k.fvar(H1_FV);
    let sym = c.sy(k, a, c.e, ha); // G.equiv G.e a
    let mem = {
        let t = k.const_(mem_e, vec![]);
        t_app(k, t, &[c.g, s, hs])
    };
    let body = {
        let t = k.const_(respects, vec![]);
        let r = t_app(k, t, &[c.g, s, hs]);
        t_app(k, r, &[c.e, a, sym, mem])
    };
    let body = lam_over(k, H1_FV, ha_ty, body);
    let body = lam_over(k, A_FV, c.carrier, body);
    let value = lam_over(k, HS_FV, hyp_ty, body);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let concl = {
        let b = k.const_(bot, vec![]);
        let bg = k.app(b, c.g);
        let l = k.const_(le, vec![]);
        t_app(k, l, &[c.g, bg, s])
    };
    let ty = pi_over(k, HS_FV, hyp_ty, concl);
    let ty = pi_over(k, S_FV, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);
    let _ = lg;

    let name = k.name_str(ns, "bot_le");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

// ---------------------------------------------------------------------------
// Closure of `IsSub` under the three lattice constructions, and the kernel.
// ---------------------------------------------------------------------------

/// Accessor names, so the closure theorems can take conjuncts apart by name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct AccNames {
    respects: NameId,
    mem_e: NameId,
    closed_op: NameId,
    closed_inv: NameId,
}

/// `AlgS.Subgroup.inter_isSub : forall G S T, IsSub G S -> IsSub G T ->
/// IsSub G (inter G S T)` — the meet of two subgroups is a subgroup.
#[allow(clippy::too_many_arguments, clippy::too_many_lines)]
fn declare_inter_is_sub(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    is_sub: NameId,
    inter: NameId,
    acc: AccNames,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let s = k.fvar(S_FV);
    let t = k.fvar(T_FV);
    let hyp_s = {
        let x = k.const_(is_sub, vec![]);
        app2(k, x, c.g, s)
    };
    let hyp_t = {
        let x = k.const_(is_sub, vec![]);
        app2(k, x, c.g, t)
    };
    let hs = k.fvar(HS_FV);
    let ht = k.fvar(HT_FV);

    let use_acc = |k: &mut Kernel, name: NameId, sub: ExprId, h: ExprId| {
        let x = k.const_(name, vec![]);
        t_app(k, x, &[c.g, sub, h])
    };
    let and_intro_at = |k: &mut Kernel, pa: ExprId, pb: ExprId, va: ExprId, vb: ExprId| {
        let ai = k.const_(lg.and_intro, vec![]);
        t_app(k, ai, &[pa, pb, va, vb])
    };
    let and_l = |k: &mut Kernel, pa: ExprId, pb: ExprId, h: ExprId| {
        let al = k.const_(lg.and_left, vec![]);
        t_app(k, al, &[pa, pb, h])
    };
    let and_r = |k: &mut Kernel, pa: ExprId, pb: ExprId, h: ExprId| {
        let ar = k.const_(lg.and_right, vec![]);
        t_app(k, ar, &[pa, pb, h])
    };

    let inter_st = {
        let i = k.const_(inter, vec![]);
        t_app(k, i, &[c.g, s, t])
    };
    let props = four_stmts(k, &c, inter_st);

    // 0. respects
    let p_respects = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let hab_ty = c.eqv(k, a, b);
        let hab = k.fvar(H1_FV);
        let sa = k.app(s, a);
        let ta = k.app(t, a);
        let sb = k.app(s, b);
        let tb = k.app(t, b);
        let and_c = k.const_(lg.and, vec![]);
        let hyp = app2(k, and_c, sa, ta);
        let h = k.fvar(H2_FV);
        let hl = and_l(k, sa, ta, h);
        let hr = and_r(k, sa, ta, h);
        let rs = use_acc(k, acc.respects, s, hs);
        let rt = use_acc(k, acc.respects, t, ht);
        let vs = t_app(k, rs, &[a, b, hab, hl]);
        let vt = t_app(k, rt, &[a, b, hab, hr]);
        let body = and_intro_at(k, sb, tb, vs, vt);
        let body = lam_over(k, H2_FV, hyp, body);
        let body = lam_over(k, H1_FV, hab_ty, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    // 1. mem_e
    let p_mem_e = {
        let se = k.app(s, c.e);
        let te = k.app(t, c.e);
        let vs = use_acc(k, acc.mem_e, s, hs);
        let vt = use_acc(k, acc.mem_e, t, ht);
        and_intro_at(k, se, te, vs, vt)
    };
    // 2. closed_op
    let p_closed_op = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let sa = k.app(s, a);
        let ta = k.app(t, a);
        let sb = k.app(s, b);
        let tb = k.app(t, b);
        let and_c = k.const_(lg.and, vec![]);
        let hyp_a = app2(k, and_c, sa, ta);
        let and_c2 = k.const_(lg.and, vec![]);
        let hyp_b = app2(k, and_c2, sb, tb);
        let hva = k.fvar(H1_FV);
        let hvb = k.fvar(H2_FV);
        let sa_l = and_l(k, sa, ta, hva);
        let ta_r = and_r(k, sa, ta, hva);
        let sb_l = and_l(k, sb, tb, hvb);
        let tb_r = and_r(k, sb, tb, hvb);
        let cs = use_acc(k, acc.closed_op, s, hs);
        let ct = use_acc(k, acc.closed_op, t, ht);
        let vs = t_app(k, cs, &[a, b, sa_l, sb_l]);
        let vt = t_app(k, ct, &[a, b, ta_r, tb_r]);
        let ab = app2(k, c.op, a, b);
        let sab = k.app(s, ab);
        let tab = k.app(t, ab);
        let body = and_intro_at(k, sab, tab, vs, vt);
        let body = lam_over(k, H2_FV, hyp_b, body);
        let body = lam_over(k, H1_FV, hyp_a, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    // 3. closed_inv
    let p_closed_inv = {
        let a = k.fvar(A_FV);
        let sa = k.app(s, a);
        let ta = k.app(t, a);
        let and_c = k.const_(lg.and, vec![]);
        let hyp = app2(k, and_c, sa, ta);
        let h = k.fvar(H1_FV);
        let hl = and_l(k, sa, ta, h);
        let hr = and_r(k, sa, ta, h);
        let cs = use_acc(k, acc.closed_inv, s, hs);
        let ct = use_acc(k, acc.closed_inv, t, ht);
        let vs = t_app(k, cs, &[a, hl]);
        let vt = t_app(k, ct, &[a, hr]);
        let ia = k.app(c.inv, a);
        let sia = k.app(s, ia);
        let tia = k.app(t, ia);
        let body = and_intro_at(k, sia, tia, vs, vt);
        let body = lam_over(k, H1_FV, hyp, body);
        lam_over(k, A_FV, c.carrier, body)
    };

    let proofs = [p_respects, p_mem_e, p_closed_op, p_closed_inv];
    let body = intro_and(k, lg, &props, &proofs);
    let value = lam_over(k, HT_FV, hyp_t, body);
    let value = lam_over(k, HS_FV, hyp_s, value);
    let value = lam_over(k, T_FV, c.sub_ty, value);
    let value = lam_over(k, S_FV, c.sub_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let concl = {
        let x = k.const_(is_sub, vec![]);
        app2(k, x, c.g, inter_st)
    };
    let ty = pi_over(k, HT_FV, hyp_t, concl);
    let ty = pi_over(k, HS_FV, hyp_s, ty);
    let ty = pi_over(k, T_FV, c.sub_ty, ty);
    let ty = pi_over(k, S_FV, c.sub_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "inter_isSub");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.top_isSub : forall G, IsSub G (top G)` — every conjunct is
/// `True.intro`.
fn declare_top_is_sub(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    is_sub: NameId,
    top: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let top_g = {
        let t = k.const_(top, vec![]);
        k.app(t, c.g)
    };
    let props = four_stmts(k, &c, top_g);
    let intro = k.const_(lg.true_intro, vec![]);
    let true_c = k.const_(lg.true_, vec![]);

    let p0 = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let hab = c.eqv(k, a, b);
        let body = lam_over(k, H2_FV, true_c, intro);
        let body = lam_over(k, H1_FV, hab, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    let p1 = intro;
    let p2 = {
        let body = lam_over(k, H2_FV, true_c, intro);
        let body = lam_over(k, H1_FV, true_c, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    let p3 = {
        let body = lam_over(k, H1_FV, true_c, intro);
        lam_over(k, A_FV, c.carrier, body)
    };
    let proofs = [p0, p1, p2, p3];
    let body = intro_and(k, lg, &props, &proofs);
    let value = lam_over(k, G_FV, c.group_ty, body);

    let concl = {
        let x = k.const_(is_sub, vec![]);
        app2(k, x, c.g, top_g)
    };
    let ty = pi_over(k, G_FV, c.group_ty, concl);

    let name = k.name_str(ns, "top_isSub");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.bot_isSub : forall G, IsSub G (bot G)` — the identity's
/// equivalence class is a subgroup. `respects` is `equivTrans ∘ equivSymm`,
/// `closedOp` is `opCongr` then `identL`, and `closedInv` needs
/// `G.equiv (G.inv G.e) G.e`, which is `identR` symm'd against `invL`.
#[allow(clippy::too_many_lines)]
fn declare_bot_is_sub(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    is_sub: NameId,
    bot: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    let c = gctx(k, group, G_FV);
    let bot_g = {
        let t = k.const_(bot, vec![]);
        k.app(t, c.g)
    };
    let props = four_stmts(k, &c, bot_g);

    // 0. respects : a ~ b -> a ~ e -> b ~ e
    let p0 = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let hab_ty = c.eqv(k, a, b);
        let hab = k.fvar(H1_FV);
        let hae_ty = c.eqv(k, a, c.e);
        let hae = k.fvar(H2_FV);
        let hba = c.sy(k, a, b, hab); // b ~ a
        let body = c.tr(k, b, a, c.e, hba, hae);
        let body = lam_over(k, H2_FV, hae_ty, body);
        let body = lam_over(k, H1_FV, hab_ty, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    // 1. mem_e : e ~ e
    let p1 = k.app(c.refl, c.e);
    // 2. closedOp : a ~ e -> b ~ e -> a*b ~ e
    let p2 = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let ha_ty = c.eqv(k, a, c.e);
        let hb_ty = c.eqv(k, b, c.e);
        let ha = k.fvar(H1_FV);
        let hb = k.fvar(H2_FV);
        let ab = app2(k, c.op, a, b);
        let ee = app2(k, c.op, c.e, c.e);
        let congr = t_app(k, c.op_congr, &[a, c.e, b, c.e, ha, hb]);
        let idl = k.app(c.ident_l, c.e); // op e e ~ e
        let body = c.tr(k, ab, ee, c.e, congr, idl);
        let body = lam_over(k, H2_FV, hb_ty, body);
        let body = lam_over(k, H1_FV, ha_ty, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    // 3. closedInv : a ~ e -> inv a ~ e
    let p3 = {
        let a = k.fvar(A_FV);
        let ha_ty = c.eqv(k, a, c.e);
        let ha = k.fvar(H1_FV);
        let ia = k.app(c.inv, a);
        let ie = k.app(c.inv, c.e);
        let congr = t_app(k, c.inv_congr, &[a, c.e, ha]); // inv a ~ inv e
        // inv e ~ e : identR (inv e) symm'd, then invL e.
        let ie_e = app2(k, c.op, ie, c.e);
        let idr = k.app(c.ident_r, ie); // op (inv e) e ~ inv e
        let idr_s = c.sy(k, ie_e, ie, idr); // inv e ~ op (inv e) e
        let invl = k.app(c.inv_l, c.e); // op (inv e) e ~ e
        let inv_e_e = c.tr(k, ie, ie_e, c.e, idr_s, invl);
        let body = c.tr(k, ia, ie, c.e, congr, inv_e_e);
        let body = lam_over(k, H1_FV, ha_ty, body);
        lam_over(k, A_FV, c.carrier, body)
    };

    let proofs = [p0, p1, p2, p3];
    let body = intro_and(k, lg, &props, &proofs);
    let value = lam_over(k, G_FV, c.group_ty, body);

    let concl = {
        let x = k.const_(is_sub, vec![]);
        app2(k, x, c.g, bot_g)
    };
    let ty = pi_over(k, G_FV, c.group_ty, concl);

    let name = k.name_str(ns, "bot_isSub");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

/// `AlgS.Subgroup.ker_isSub : forall G H f fCongr fMul,
/// IsSub G (AlgS.Hom.ker G H f)` — **the kernel of a homomorphism is a
/// subgroup**, which is what joins this half of W1-11 to the half that landed
/// with `AlgS.Hom.firstIso`.
///
/// `respects` is `fCongr` symm'd and composed; `mem_e` is `AlgS.Hom.mapOne`
/// verbatim; `closedOp` is `fMul` then `H.opCongr` then `H.identL`;
/// `closedInv` is `AlgS.Hom.mapInv` then `H.invCongr` then
/// `H.equiv (H.inv H.e) H.e`.
#[allow(clippy::too_many_arguments, clippy::too_many_lines)]
fn declare_ker_is_sub(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    is_sub: NameId,
    ker: NameId,
    map_one: NameId,
    map_inv: NameId,
    ns: NameId,
) -> Result<NameId, KernelError> {
    use idx::group::{
        CARRIER, E, EQUIV, EQUIV_SYMM, EQUIV_TRANS, IDENT_L, IDENT_R, INV, INV_CONGR, INV_L, OP,
        OP_CONGR,
    };
    let c = gctx(k, group, G_FV);
    let h = k.fvar(KH_FV);
    let hc = sel(k, group, CARRIER, h);
    let heq_sel = sel(k, group, EQUIV, h);
    let hsymm = sel(k, group, EQUIV_SYMM, h);
    let htrans = sel(k, group, EQUIV_TRANS, h);
    let hop = sel(k, group, OP, h);
    let hop_congr = sel(k, group, OP_CONGR, h);
    let he = sel(k, group, E, h);
    let hinv = sel(k, group, INV, h);
    let hinv_congr = sel(k, group, INV_CONGR, h);
    let hident_l = sel(k, group, IDENT_L, h);
    let hident_r = sel(k, group, IDENT_R, h);
    let hinv_l = sel(k, group, INV_L, h);

    let f = k.fvar(KF_FV);
    let f_ty = arrow(k, c.carrier, hc);
    let fc_ty = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let hyp = c.eqv(k, a, b);
        let fa = k.app(f, a);
        let fb = k.app(f, b);
        let concl = app2(k, heq_sel, fa, fb);
        let t = pi_over(k, H1_FV, hyp, concl);
        let t = pi_over(k, B_FV, c.carrier, t);
        pi_over(k, A_FV, c.carrier, t)
    };
    let fc = k.fvar(KFC_FV);
    let fm_ty = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let ab = app2(k, c.op, a, b);
        let f_ab = k.app(f, ab);
        let fa = k.app(f, a);
        let fb = k.app(f, b);
        let rhs = app2(k, hop, fa, fb);
        let concl = app2(k, heq_sel, f_ab, rhs);
        let t = pi_over(k, B_FV, c.carrier, concl);
        pi_over(k, A_FV, c.carrier, t)
    };
    let fm = k.fvar(KFM_FV);

    let ker_s = {
        let t = k.const_(ker, vec![]);
        t_app(k, t, &[c.g, h, f])
    };
    let props = four_stmts(k, &c, ker_s);

    let htr = |k: &mut Kernel, x: ExprId, y: ExprId, z: ExprId, p: ExprId, q: ExprId| {
        t_app(k, htrans, &[x, y, z, p, q])
    };

    // 0. respects : a ~ b -> f a ~ H.e -> f b ~ H.e
    let p0 = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let hab_ty = c.eqv(k, a, b);
        let hab = k.fvar(H1_FV);
        let fa = k.app(f, a);
        let fb = k.app(f, b);
        let ka_ty = app2(k, heq_sel, fa, he);
        let ka = k.fvar(H2_FV);
        let fab = t_app(k, fc, &[a, b, hab]); // f a ~ f b
        let fba = t_app(k, hsymm, &[fa, fb, fab]); // f b ~ f a
        let body = htr(k, fb, fa, he, fba, ka);
        let body = lam_over(k, H2_FV, ka_ty, body);
        let body = lam_over(k, H1_FV, hab_ty, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    // 1. mem_e : f G.e ~ H.e — `AlgS.Hom.mapOne` verbatim.
    let p1 = {
        let t = k.const_(map_one, vec![]);
        t_app(k, t, &[c.g, h, f, fc, fm])
    };
    // 2. closedOp
    let p2 = {
        let a = k.fvar(A_FV);
        let b = k.fvar(B_FV);
        let fa = k.app(f, a);
        let fb = k.app(f, b);
        let ka_ty = app2(k, heq_sel, fa, he);
        let kb_ty = app2(k, heq_sel, fb, he);
        let ka = k.fvar(H1_FV);
        let kb = k.fvar(H2_FV);
        let ab = app2(k, c.op, a, b);
        let f_ab = k.app(f, ab);
        let prod = app2(k, hop, fa, fb);
        let ee = app2(k, hop, he, he);
        let s1 = t_app(k, fm, &[a, b]); // f(a*b) ~ f a * f b
        let s2 = t_app(k, hop_congr, &[fa, he, fb, he, ka, kb]); // ~ e*e
        let s3 = k.app(hident_l, he); // e*e ~ e
        let step = htr(k, prod, ee, he, s2, s3);
        let body = htr(k, f_ab, prod, he, s1, step);
        let body = lam_over(k, H2_FV, kb_ty, body);
        let body = lam_over(k, H1_FV, ka_ty, body);
        let body = lam_over(k, B_FV, c.carrier, body);
        lam_over(k, A_FV, c.carrier, body)
    };
    // 3. closedInv
    let p3 = {
        let a = k.fvar(A_FV);
        let fa = k.app(f, a);
        let ka_ty = app2(k, heq_sel, fa, he);
        let ka = k.fvar(H1_FV);
        let ia = k.app(c.inv, a);
        let f_ia = k.app(f, ia);
        let inv_fa = k.app(hinv, fa);
        let inv_e = k.app(hinv, he);
        let s1 = {
            let t = k.const_(map_inv, vec![]);
            let m = t_app(k, t, &[c.g, h, f, fc, fm]);
            k.app(m, a)
        }; // f (inv a) ~ H.inv (f a)
        let s2 = t_app(k, hinv_congr, &[fa, he, ka]); // H.inv (f a) ~ H.inv H.e
        // H.inv H.e ~ H.e
        let ie_e = app2(k, hop, inv_e, he);
        let idr = k.app(hident_r, inv_e);
        let idr_s = t_app(k, hsymm, &[ie_e, inv_e, idr]);
        let invl = k.app(hinv_l, he);
        let s3 = htr(k, inv_e, ie_e, he, idr_s, invl);
        let step = htr(k, inv_fa, inv_e, he, s2, s3);
        let body = htr(k, f_ia, inv_fa, he, s1, step);
        let body = lam_over(k, H1_FV, ka_ty, body);
        lam_over(k, A_FV, c.carrier, body)
    };

    let proofs = [p0, p1, p2, p3];
    let body = intro_and(k, lg, &props, &proofs);
    let value = lam_over(k, KFM_FV, fm_ty, body);
    let value = lam_over(k, KFC_FV, fc_ty, value);
    let value = lam_over(k, KF_FV, f_ty, value);
    let value = lam_over(k, KH_FV, c.group_ty, value);
    let value = lam_over(k, G_FV, c.group_ty, value);

    let concl = {
        let x = k.const_(is_sub, vec![]);
        app2(k, x, c.g, ker_s)
    };
    let ty = pi_over(k, KFM_FV, fm_ty, concl);
    let ty = pi_over(k, KFC_FV, fc_ty, ty);
    let ty = pi_over(k, KF_FV, f_ty, ty);
    let ty = pi_over(k, KH_FV, c.group_ty, ty);
    let ty = pi_over(k, G_FV, c.group_ty, ty);

    let name = k.name_str(ns, "ker_isSub");
    k.add_declaration(Declaration::Theorem {
        name,
        uparams: vec![],
        ty,
        value,
    })?;
    Ok(name)
}

// ---------------------------------------------------------------------------
// Assembly.
// ---------------------------------------------------------------------------

/// Every name this module declares.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SubgroupNames {
    pub is_sub: NameId,
    pub le: NameId,
    pub inter: NameId,
    pub top: NameId,
    pub bot: NameId,
    pub respects: NameId,
    pub mem_e: NameId,
    pub closed_op: NameId,
    pub closed_inv: NameId,
    pub le_refl: NameId,
    pub le_trans: NameId,
    pub inter_le_left: NameId,
    pub inter_le_right: NameId,
    pub le_inter: NameId,
    pub inter_is_sub: NameId,
    pub top_is_sub: NameId,
    pub bot_is_sub: NameId,
    pub le_top: NameId,
    pub bot_le: NameId,
    pub ker_is_sub: NameId,
}

/// `#[cfg(test)]` for the same reason `PolyNames::all` is.
#[cfg(test)]
impl SubgroupNames {
    #[must_use]
    pub fn all(&self) -> [NameId; 20] {
        [
            self.is_sub,
            self.le,
            self.inter,
            self.top,
            self.bot,
            self.respects,
            self.mem_e,
            self.closed_op,
            self.closed_inv,
            self.le_refl,
            self.le_trans,
            self.inter_le_left,
            self.inter_le_right,
            self.le_inter,
            self.inter_is_sub,
            self.top_is_sub,
            self.bot_is_sub,
            self.le_top,
            self.bot_le,
            self.ker_is_sub,
        ]
    }
}

/// What this module needs from `structures_setoid`'s `AlgS.Hom.*`. The shared
/// `hom_` prefix names the source namespace and is deliberate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(clippy::struct_field_names)]
pub struct SubgroupDeps {
    pub hom_ker: NameId,
    pub hom_map_one: NameId,
    pub hom_map_inv: NameId,
}

/// Declare the whole `AlgS.Subgroup.*` namespace.
///
/// # Errors
///
/// Returns the trusted gate's rejection — an `Err` means
/// [`Kernel::add_declaration`] **refused** a proof term.
pub(crate) fn declare_subgroup_setoid(
    k: &mut Kernel,
    lg: &LogicPrelude,
    group: &RecordNames,
    deps: SubgroupDeps,
    algs_p: NameId,
) -> Result<SubgroupNames, KernelError> {
    let ns = k.name_str(algs_p, "Subgroup");

    let is_sub = declare_is_sub(k, lg, group, ns)?;
    let le = declare_le(k, group, ns)?;
    let inter = declare_inter(k, lg, group, ns)?;
    let top = declare_top(k, lg, group, ns)?;
    let bot = declare_bot(k, group, ns)?;

    let respects = declare_accessor(k, lg, group, is_sub, 0, "respects", ns)?;
    let mem_e = declare_accessor(k, lg, group, is_sub, 1, "mem_e", ns)?;
    let closed_op = declare_accessor(k, lg, group, is_sub, 2, "closedOp", ns)?;
    let closed_inv = declare_accessor(k, lg, group, is_sub, 3, "closedInv", ns)?;
    let acc = AccNames {
        respects,
        mem_e,
        closed_op,
        closed_inv,
    };

    let le_refl = declare_le_refl(k, group, le, ns)?;
    let le_trans = declare_le_trans(k, group, le, ns)?;
    let inter_le_left = declare_inter_le(k, lg, group, le, inter, true, ns)?;
    let inter_le_right = declare_inter_le(k, lg, group, le, inter, false, ns)?;
    let le_inter = declare_le_inter(k, lg, group, le, inter, ns)?;
    let inter_is_sub = declare_inter_is_sub(k, lg, group, is_sub, inter, acc, ns)?;
    let top_is_sub = declare_top_is_sub(k, lg, group, is_sub, top, ns)?;
    let bot_is_sub = declare_bot_is_sub(k, lg, group, is_sub, bot, ns)?;
    let le_top = declare_le_top(k, lg, group, le, top, ns)?;
    let bot_le = declare_bot_le(k, lg, group, is_sub, le, bot, respects, mem_e, ns)?;
    let ker_is_sub = declare_ker_is_sub(
        k,
        lg,
        group,
        is_sub,
        deps.hom_ker,
        deps.hom_map_one,
        deps.hom_map_inv,
        ns,
    )?;

    Ok(SubgroupNames {
        is_sub,
        le,
        inter,
        top,
        bot,
        respects,
        mem_e,
        closed_op,
        closed_inv,
        le_refl,
        le_trans,
        inter_le_left,
        inter_le_right,
        le_inter,
        inter_is_sub,
        top_is_sub,
        bot_is_sub,
        le_top,
        bot_le,
        ker_is_sub,
    })
}

// ---------------------------------------------------------------------------
// Tests. Every assertion reads the KERNEL.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod subgroup_setoid_tests {
    use super::*;
    use crate::build_logic_prelude;
    use crate::nat_prelude::structures as algeq;
    use crate::nat_prelude::structures_setoid::{
        StructuresSExtraNames, StructuresSNames, StructuresSRecordNames, declare_structures_s_all,
        declare_structures_s_extra, intern_structures_s_names,
    };

    struct Fixture {
        lg: LogicPrelude,
        st: StructuresSRecordNames,
        p: StructuresSNames,
        extra: StructuresSExtraNames,
        sg: SubgroupNames,
    }

    fn build(k: &mut Kernel) -> Fixture {
        let lg = build_logic_prelude(k).expect("logic prelude must build");
        let alg_p = algeq::intern_structures_names(k);
        let alg_st = algeq::declare_structures_all(k, &alg_p, &lg).expect("Alg spine builds");
        let p = intern_structures_s_names(k);
        let st = declare_structures_s_all(k, &p, &lg).expect("AlgS spine builds");
        let extra = declare_structures_s_extra(k, &lg, &p, &st, &alg_p, &alg_st)
            .expect("AlgS extras must admit");
        let deps = SubgroupDeps {
            hom_ker: extra.hom_ker,
            hom_map_one: extra.hom_map_one,
            hom_map_inv: extra.hom_map_inv,
        };
        let sg = declare_subgroup_setoid(k, &lg, &st.group, deps, p.algs)
            .expect("the subgroup lattice over an abstract AlgS.Group must admit");
        Fixture {
            lg,
            st,
            p,
            extra,
            sg,
        }
    }

    #[test]
    fn the_subgroup_lattice_admits_by_the_setoid_route() {
        let mut k = Kernel::new();
        let f = build(&mut k);
        for name in f.sg.all() {
            assert!(
                k.environment().get(name).is_some(),
                "declaration missing from the environment"
            );
        }
    }

    /// **The headline claim**, read from `Kernel::axiom_footprint`.
    #[test]
    fn the_subgroup_lattice_is_axiom_free() {
        let mut k = Kernel::new();
        let f = build(&mut k);
        for name in f.sg.all() {
            let footprint = k.axiom_footprint(name);
            assert!(
                footprint.is_empty(),
                "axiom footprint must be empty, got {} entries",
                footprint.len()
            );
        }
    }

    /// The lattice laws and the three closure results are `Theorem`s, so the
    /// kernel checked their proof terms.
    #[test]
    fn the_lattice_laws_and_closure_results_are_checked_theorems() {
        let mut k = Kernel::new();
        let f = build(&mut k);
        for name in [
            f.sg.le_refl,
            f.sg.le_trans,
            f.sg.inter_le_left,
            f.sg.inter_le_right,
            f.sg.le_inter,
            f.sg.inter_is_sub,
            f.sg.top_is_sub,
            f.sg.bot_is_sub,
            f.sg.le_top,
            f.sg.bot_le,
            f.sg.ker_is_sub,
        ] {
            let d = k
                .environment()
                .get(name)
                .expect("theorem must exist")
                .clone();
            assert!(
                matches!(d, Declaration::Theorem { .. }),
                "must be a checked Theorem"
            );
        }
    }

    /// **Evaluation test for the three lattice definitions.** With `G`, `S`,
    /// `T` and `a` free, each must reduce to the hand-written body, and the
    /// negative twins (`inter` as a disjunction-shaped pair with the sides
    /// swapped, `bot` as the class of a different element) must not.
    #[test]
    fn the_lattice_definitions_reduce_to_their_bodies() {
        let mut k = Kernel::new();
        let f = build(&mut k);
        let c = gctx(&mut k, &f.st.group, G_FV);
        let s = k.fvar(S_FV);
        let t = k.fvar(T_FV);
        let a = k.fvar(A_FV);

        // inter G S T a  ==  And (S a) (T a), and NOT And (T a) (S a).
        {
            let i = k.const_(f.sg.inter, vec![]);
            let lhs = t_app(&mut k, i, &[c.g, s, t, a]);
            let sa = k.app(s, a);
            let ta = k.app(t, a);
            let and_c = k.const_(f.lg.and, vec![]);
            let rhs = app2(&mut k, and_c, sa, ta);
            assert!(k.def_eq(lhs, rhs), "inter G S T a must be And (S a) (T a)");
            let and_c2 = k.const_(f.lg.and, vec![]);
            let swapped = app2(&mut k, and_c2, ta, sa);
            assert!(
                !k.def_eq(lhs, swapped),
                "inter must NOT be And (T a) (S a) -- S and T are distinct free \
                 predicates, so the order is observable"
            );
        }
        // top G a  ==  True, and NOT the group's own equivalence at a.
        {
            let tp = k.const_(f.sg.top, vec![]);
            let lhs = t_app(&mut k, tp, &[c.g, a]);
            let true_c = k.const_(f.lg.true_, vec![]);
            assert!(k.def_eq(lhs, true_c), "top G a must be True");
            let botlike = c.eqv(&mut k, a, c.e);
            assert!(
                !k.def_eq(lhs, botlike),
                "top must NOT collapse to the identity's equivalence class"
            );
        }
        // bot G a  ==  G.equiv a G.e, and NOT G.equiv G.e a.
        {
            let b = k.const_(f.sg.bot, vec![]);
            let lhs = t_app(&mut k, b, &[c.g, a]);
            let rhs = c.eqv(&mut k, a, c.e);
            assert!(k.def_eq(lhs, rhs), "bot G a must be G.equiv a G.e");
            let reversed = c.eqv(&mut k, c.e, a);
            assert!(
                !k.def_eq(lhs, reversed),
                "bot must NOT be G.equiv G.e a -- `equiv` is an abstract \
                 relation field, not a symmetric primitive"
            );
        }
    }

    /// **`IsSub` really has four conjuncts, and the first is the setoid one.**
    /// The statement is checked against the hand-built nesting, and against a
    /// three-conjunct version with `respects` dropped, which must NOT be
    /// definitionally equal. This is what pins the "one extra field" cost
    /// claim in ADR-1609 to the kernel rather than to a comment.
    #[test]
    fn is_sub_carries_the_equivalence_respecting_conjunct() {
        let mut k = Kernel::new();
        let f = build(&mut k);
        let c = gctx(&mut k, &f.st.group, G_FV);
        let s = k.fvar(S_FV);

        let is_sub_c = k.const_(f.sg.is_sub, vec![]);
        let lhs = app2(&mut k, is_sub_c, c.g, s);

        let props = four_stmts(&mut k, &c, s);
        let rhs = nest_and(&mut k, &f.lg, &props);
        assert!(
            k.def_eq(lhs, rhs),
            "IsSub must unfold to the four-fold conjunction"
        );

        let without_respects = {
            let and_c = k.const_(f.lg.and, vec![]);
            let inner = app2(&mut k, and_c, props[2], props[3]);
            let and_c2 = k.const_(f.lg.and, vec![]);
            app2(&mut k, and_c2, props[1], inner)
        };
        assert!(
            !k.def_eq(lhs, without_respects),
            "IsSub must NOT be the three-conjunct `Eq`-flavored version -- the \
             `forall a b, G.equiv a b -> S a -> S b` field is real, and \
             `bot_le` needs it"
        );
    }

    /// **Negative control for `bot_le`.** Its proof is re-declared against the
    /// statement with `IsSub` weakened away -- `forall G S, le G (bot G) S`,
    /// with the `IsSub` hypothesis simply removed. The kernel must refuse it,
    /// which is the precise sense in which the setoid's extra conjunct is
    /// load-bearing: without `respects` and `mem_e` there is no proof.
    ///
    /// The positive twin is the re-declaration against the honest statement.
    #[test]
    fn bot_le_is_rejected_without_the_is_sub_hypothesis() {
        let mut k = Kernel::new();
        let f = build(&mut k);
        let c = gctx(&mut k, &f.st.group, G_FV);
        let s = k.fvar(S_FV);

        let value = match k.environment().get(f.sg.bot_le).expect("bot_le must exist") {
            Declaration::Theorem { value, .. } => *value,
            other => panic!("expected a Theorem, got {other:?}"),
        };

        let concl = {
            let b = k.const_(f.sg.bot, vec![]);
            let bg = k.app(b, c.g);
            let l = k.const_(f.sg.le, vec![]);
            t_app(&mut k, l, &[c.g, bg, s])
        };
        let hyp_ty = {
            let t = k.const_(f.sg.is_sub, vec![]);
            app2(&mut k, t, c.g, s)
        };
        let honest = {
            let t = pi_over(&mut k, HS_FV, hyp_ty, concl);
            let t = pi_over(&mut k, S_FV, c.sub_ty, t);
            pi_over(&mut k, G_FV, c.group_ty, t)
        };
        let weakened = {
            let t = pi_over(&mut k, S_FV, c.sub_ty, concl);
            pi_over(&mut k, G_FV, c.group_ty, t)
        };

        let ok_name = k.name_str(f.p.algs, "botLeRestatedControl");
        assert!(
            k.add_declaration(Declaration::Theorem {
                name: ok_name,
                uparams: vec![],
                ty: honest,
                value,
            })
            .is_ok(),
            "the honest restatement must admit"
        );
        let bad_name = k.name_str(f.p.algs, "botLeWithoutIsSub");
        assert!(
            k.add_declaration(Declaration::Theorem {
                name: bad_name,
                uparams: vec![],
                ty: weakened,
                value,
            })
            .is_err(),
            "bot_le must NOT hold for an arbitrary predicate: the proof \
             consumes IsSub's `respects` and `mem_e` conjuncts"
        );
    }

    /// **Negative control for `ker_isSub`.** Its proof is re-declared against
    /// the claim that the IMAGE (`AlgS.Hom.image`, a predicate on `H.carrier`)
    /// is a subgroup of the SOURCE -- a well-formed statement in the same
    /// shape that is not what the proof establishes. The kernel must refuse
    /// it; the honest restatement admits in the same test.
    #[test]
    fn ker_is_sub_does_not_prove_the_image_is_a_subgroup_of_the_source() {
        use idx::group::CARRIER;
        let mut k = Kernel::new();
        let f = build(&mut k);
        let c = gctx(&mut k, &f.st.group, G_FV);
        let h = k.fvar(KH_FV);
        let hc = sel(&mut k, &f.st.group, CARRIER, h);
        let fv = k.fvar(KF_FV);
        let f_ty = arrow(&mut k, c.carrier, hc);

        let value = match k
            .environment()
            .get(f.sg.ker_is_sub)
            .expect("ker_isSub must exist")
        {
            Declaration::Theorem { value, .. } => *value,
            other => panic!("expected a Theorem, got {other:?}"),
        };
        let honest_ty = match k
            .environment()
            .get(f.sg.ker_is_sub)
            .expect("ker_isSub must exist")
        {
            Declaration::Theorem { ty, .. } => *ty,
            other => panic!("expected a Theorem, got {other:?}"),
        };

        let ok_name = k.name_str(f.p.algs, "kerIsSubRestatedControl");
        assert!(
            k.add_declaration(Declaration::Theorem {
                name: ok_name,
                uparams: vec![],
                ty: honest_ty,
                value,
            })
            .is_ok(),
            "the honest restatement must admit"
        );

        // The mutant: swap `AlgS.Hom.ker` for `AlgS.Hom.image` and claim it is
        // a subgroup of `G` -- the image lives on `H.carrier`, so this is a
        // different (and ill-typed) subject even before the proof is checked.
        let image_pred = {
            let t = k.const_(f.extra.hom_image, vec![]);
            t_app(&mut k, t, &[c.g, h, fv])
        };
        let bad_ty = {
            let t = k.const_(f.sg.is_sub, vec![]);
            let body = app2(&mut k, t, c.g, image_pred);
            let t2 = pi_over(&mut k, KF_FV, f_ty, body);
            let t3 = pi_over(&mut k, KH_FV, c.group_ty, t2);
            pi_over(&mut k, G_FV, c.group_ty, t3)
        };
        let bad_name = k.name_str(f.p.algs, "kerIsSubAtImage");
        assert!(
            k.add_declaration(Declaration::Theorem {
                name: bad_name,
                uparams: vec![],
                ty: bad_ty,
                value,
            })
            .is_err(),
            "the kernel's subgroup proof must NOT check against a claim about \
             the image, which is a predicate on the CODOMAIN"
        );
    }
}
