# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum._native import ir
import builtins
import typing
from . import cnf
from . import proofs
__all__ = [
    "ASSURANCES",
    "BackendCapabilities",
    "CHECKED_BY",
    "Capability",
    "CheckResult",
    "Config",
    "EvidenceCheck",
    "EvidenceReport",
    "IR_STATUSES",
    "Incremental",
    "PARSER_STATUSES",
    "PROOF_STATUSES",
    "ProofOutcome",
    "RouteTrace",
    "SOLVER_STATUSES",
    "STRATEGIES",
    "SatBvBackend",
    "SolveStats",
    "SupportRow",
    "TrustStep",
    "UNKNOWN_KINDS",
    "capabilities",
    "capability_rows",
    "check_auto_explained",
    "cnf",
    "produce_evidence",
    "proofs",
    "prove",
    "recommended_portfolio",
    "solve",
    "solve_with_portfolio",
    "solve_with_strategy",
    "support_matrix",
    "support_matrix_rows",
    "trust_ids",
    "trust_ledger",
    "trust_ledger_rows",
    "unsat_core",
]

ASSURANCES: builtins.list[builtins.str]
CHECKED_BY: builtins.list[builtins.str]
IR_STATUSES: builtins.list[builtins.str]
PARSER_STATUSES: builtins.list[builtins.str]
PROOF_STATUSES: builtins.list[builtins.str]
SOLVER_STATUSES: builtins.list[builtins.str]
STRATEGIES: builtins.list[builtins.str]
UNKNOWN_KINDS: builtins.list[builtins.str]
@typing.final
class BackendCapabilities:
    r"""
    What a backend can do (`backend::Capabilities`).
    
    Tier **R**. Not uniform across backends — this is the backend's own report,
    not a promise about the stack.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable backend name and version.
        """
    @property
    def produces_models(self) -> builtins.bool:
        r"""
        Whether `sat` results carry models.
        """
    @property
    def complete(self) -> builtins.bool:
        r"""
        Whether the backend is refutation-complete for the M0 fragment.
        
        `False` is honest, not broken: a model-finding-only engine reports it.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Capability:
    r"""
    One row of the capability ledger (`capabilities::CAPABILITIES`).
    
    Tier **R** — read-only data. Nothing here decides anything; it is what this
    build says it can do and how much of that is checked.
    """
    @property
    def id(self) -> builtins.str:
        r"""
        The row identity: `"<area> | <feature>"`.
        
        The Rust `Capability` struct has no id field — `(area, feature)` is the
        composite key — and this is that pair rendered exactly as the first two
        cells of the Markdown row, so `f"| {cap.id} |"` is a substring of
        [`capabilities()`](axeyum.solver.capabilities).
        """
    @property
    def area(self) -> builtins.str:
        r"""
        The logic fragment / theory area (`"QF_BV"`, `"QF_FP"`, …).
        """
    @property
    def feature(self) -> builtins.str:
        r"""
        The specific capability within the area.
        """
    @property
    def assurance(self) -> builtins.str:
        r"""
        How much to trust a result: `"checked"`, `"validated"`,
        `"sound, incomplete"` or `"experimental"`.
        """
    @property
    def checked_by(self) -> builtins.str:
        r"""
        WHO reads the artifact — the axis `assurance` does not carry.
        
        `"external-artifact-checker"` is the only value that answers "can a
        third party check this without trusting us?"; `"differential-only"`
        tests the verdict and not our artifact, and `"argument-only"` means
        decided, not certified.
        """
    @property
    def evidence(self) -> builtins.str:
        r"""
        What backs a result — the checkable artifact or validation basis.
        """
    @property
    def reference(self) -> builtins.str:
        r"""
        The governing architecture-decision record.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CheckResult:
    r"""
    The verdict of one satisfiability check.
    
    A tagged value with three shapes: `Sat` (with a model), `Unsat`, and
    `Unknown` (with a classified `kind` and a `detail`). **`Unknown` is never
    an exception** — a budget-exhausted or incomplete run is a first-class
    answer, and reading it as `unsat` is the mistake the structure exists to
    prevent.
    """
    @property
    def status(self) -> builtins.str:
        r"""
        `"sat"`, `"unsat"` or `"unknown"`.
        """
    @property
    def unknown_kind(self) -> typing.Optional[builtins.str]:
        r"""
        The classified `Unknown` cause, or `None` for a decided query.
        """
    @property
    def unknown_detail(self) -> typing.Optional[builtins.str]:
        r"""
        The backend detail behind an `Unknown`, or `None`.
        """
    def is_sat(self) -> builtins.bool:
        r"""
        Whether this is a `sat`.
        """
    def is_unsat(self) -> builtins.bool:
        r"""
        Whether this is an `unsat`.
        """
    def is_unknown(self) -> builtins.bool:
        r"""
        Whether this is an `unknown`.
        """
    def model(self, arena: ir.Arena) -> dict:
        r"""
        `{declared name: value}` in declaration order; empty unless `sat`.
        
        Symbols the solver left unconstrained are omitted rather than
        defaulted; inventing a value would be a claim the solver did not make.
        """
    def functions(self, arena: ir.Arena) -> dict:
        r"""
        `{declared function name: FuncValue}`; empty unless `sat`.
        """
    def to_assignment(self, arena: ir.Arena) -> ir.Assignment:
        r"""
        The model as an [`Assignment`](axeyum.ir.Assignment) for `ir.eval`.
        """
    def replay(self, arena: ir.Arena, assertions: typing.Sequence[ir.Term]) -> builtins.bool:
        r"""
        Re-checks the model against `assertions` with `axeyum_solver::check_model`.
        
        This is the canonical replay: `True` means the model genuinely
        satisfies the ORIGINAL terms. Raises `ValueError` on a non-`sat`
        verdict rather than returning `False`, because "there was nothing to
        replay" and "the replay disagreed" are different findings and only the
        second is a soundness signal.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Config:
    r"""
    Per-query solver configuration.
    
    Eighteen plain fields; the two `mpsc`-backed progress sinks
    (`proof_progress`, `check_progress`) are deliberately **not** bound — they
    are what make `SolverConfig` `!Sync`, and draining a Rust channel from
    Python needs a design this slice does not have.
    
    Every budget exhaustion surfaces as an `unknown`
    [`CheckResult`](axeyum.solver.CheckResult), never as an exception.
    """
    @property
    def timeout_ms(self) -> typing.Optional[builtins.int]:
        r"""
        The wall-clock budget in milliseconds, or `None`.
        """
    @property
    def prove_unsat(self) -> builtins.bool:
        r"""
        Whether `unsat` must carry a checked DRAT proof.
        """
    @property
    def preprocess(self) -> builtins.bool:
        r"""
        Whether the word-level canonicalizer runs before dispatch.
        """
    @property
    def node_budget(self) -> typing.Optional[builtins.int]:
        r"""
        The translation node budget, or `None`.
        """
    def __new__(cls, *, timeout_ms: typing.Optional[builtins.int] = None, resource_limit: typing.Optional[builtins.int] = None, memory_limit_mb: typing.Optional[builtins.int] = None, node_budget: typing.Optional[builtins.int] = None, cnf_variable_budget: typing.Optional[builtins.int] = None, cnf_clause_budget: typing.Optional[builtins.int] = None, prove_unsat: builtins.bool = False, cnf_inprocessing: builtins.bool = False, cnf_vivify: builtins.bool = False, preprocess: builtins.bool = True, profile_bit_demand: builtins.bool = False, profile_cnf_construction: builtins.bool = False, bit_lowering_mode: builtins.str = 'eager', incremental_positive_and_flattening: builtins.bool = False, xor_cdcl_fallback: builtins.bool = False, lazy_bv: builtins.bool = False, native_cdcl: builtins.bool = False, lazy_bv_abstract_ite: builtins.bool = False) -> Config:
        r"""
        Builds a configuration. Every argument defaults to the Rust default.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class EvidenceCheck:
    r"""
    The result of independently re-validating an [`Evidence`].
    
    Three-valued on purpose. A `bool` cannot tell "I re-derived the
    certificate" from "there was no certificate", and collapsing the second
    into a pass is exactly the checker-that-cannot-fail defect. There is no
    `__bool__` on this class for the same reason.
    """
    @property
    def status(self) -> builtins.str:
        r"""
        `"verified"`, `"nothing-to-check"` or `"failed"`.
        """
    @property
    def reason(self) -> typing.Optional[builtins.str]:
        r"""
        Why nothing was re-validated (`"uncertified-unsat"`, `"undecided"`,
        `"empty-subject"`, `"unfaithful-subject"`), else `None`.
        """
    def is_verified(self) -> builtins.bool:
        r"""
        Whether a certificate was present and re-derived THIS RUN. The only
        value that licenses trusting the result on the evidence alone.
        """
    def is_nothing_to_check(self) -> builtins.bool:
        r"""
        Whether the checker had nothing to re-validate. **Not a pass.**
        """
    def is_failed(self) -> builtins.bool:
        r"""
        Whether a present certificate FAILED re-validation — a soundness alarm.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class EvidenceReport:
    r"""
    A verdict together with its checkable justification and provenance.
    
    The primary "give me a checkable answer" API. `check_outcome` is what is
    bound; the `bool`-returning `Evidence::check` is not, because it collapses
    `NothingToCheck` into a pass.
    """
    @property
    def verdict(self) -> builtins.str:
        r"""
        `"sat"`, `"unsat"` or `"unknown"`.
        """
    @property
    def evidence_kind(self) -> builtins.str:
        r"""
        The stable label of the evidence variant (`"sat"`, `"unsat-drat"`,
        `"unsat-farkas"`, …) — what KIND of justification this is.
        """
    @property
    def result(self) -> CheckResult:
        r"""
        The verdict as a [`CheckResult`](axeyum.solver.CheckResult).
        """
    @property
    def proof(self) -> typing.Optional[proofs.UnsatProof]:
        r"""
        The DRAT certificate, when the evidence is a plain proved `unsat`.
        """
    @property
    def provenance(self) -> dict:
        r"""
        Version and budget provenance, as a plain dict.
        """
    @property
    def trusted_steps(self) -> builtins.list[tuple[builtins.str, builtins.bool]]:
        r"""
        The trusted reductions this result depended on, as
        `(label, certified_this_run)` in canonical order.
        
        `certified == False` names a reduction that was TRUSTED, not checked.
        """
    @property
    def trust_steps(self) -> builtins.list[TrustStep]:
        r"""
        The trusted reductions this result depended on, as structured
        [`TrustStep`](axeyum.solver.TrustStep) records in canonical order.
        
        The same list as `trusted_steps`, with the reduction's meaning,
        pedantic level, ADR and LEDGER-wide `is_certified()` bit alongside the
        PER-RUN `certified` one. Read `certified` to know what this result
        carried; `ledger_certified` answers a different question and a row
        where the two disagree is the normal case, not an anomaly.
        """
    def is_certified(self) -> builtins.bool:
        r"""
        Whether the evidence carries a transferable certificate at all.
        
        `False` on a bare `unsat` means the verdict is the deciding engine's
        with nothing re-derived — sound if the engine is, but unchecked.
        """
    def check_outcome(self, arena: ir.Arena, assertions: typing.Sequence[ir.Term]) -> EvidenceCheck:
        r"""
        Independently re-validates the evidence against `(arena, assertions)`.
        
        Returns the three-valued [`EvidenceCheck`](axeyum.solver.EvidenceCheck).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Incremental:
    r"""
    A warm, push/pop-capable bit-vector solver over ONE arena.
    
    The Rust solver reuses arena-stable term ids and a persistent lowering, so
    it is bound to a single arena for its whole life. Every method takes the
    arena and asserts it is that one; a foreign arena raises `EpochError`.
    """
    @property
    def epoch(self) -> builtins.int:
        r"""
        The arena epoch this solver is bound to.
        """
    @property
    def scope_depth(self) -> builtins.int:
        r"""
        The current scope depth (`0` at the base frame).
        """
    @property
    def encoded_clause_count(self) -> builtins.int:
        r"""
        Retained CNF clause count.
        """
    @property
    def encoded_variable_count(self) -> builtins.int:
        r"""
        Retained CNF variable count.
        """
    @property
    def lowered_aig_node_count(self) -> builtins.int:
        r"""
        Retained AIG node count.
        """
    def __new__(cls, arena: ir.Arena, config: typing.Optional[Config] = None) -> Incremental:
        r"""
        Creates a warm solver bound to `arena`.
        """
    def assert_(self, arena: ir.Arena, term: ir.Term) -> None:
        r"""
        Adds an assertion at the current scope.
        """
    def push(self) -> None:
        r"""
        Opens a new scope.
        """
    def pop(self) -> builtins.bool:
        r"""
        Closes the innermost scope. Returns `False` at the base frame — that is
        the Rust contract and it is NOT an error.
        """
    def check(self, arena: ir.Arena) -> CheckResult:
        r"""
        Decides the current assertion stack.
        """
    def check_assuming(self, arena: ir.Arena, assumptions: typing.Sequence[ir.Term]) -> CheckResult:
        r"""
        Decides the current stack plus `assumptions`, without asserting them.
        """
    def stats(self) -> dict:
        r"""
        Retained-encoding and timing counters.
        """
    def enable_replay_checked_sat_cache(self, max_entries: builtins.int = 128, max_values: builtins.int = 4096, max_bits: builtins.int = 65536) -> None:
        r"""
        Turns on the replay-checked `sat` model cache.
        
        Only models that REPLAYED against the original terms are ever served
        from it; `unsat` without a source-bound proof is deliberately not
        cached at all.
        """
    def disable_replay_checked_sat_cache(self) -> None:
        r"""
        Turns the replay-checked `sat` model cache off.
        """
    def replay_checked_sat_cache_stats(self) -> dict:
        r"""
        Cache counters, including every DECLINE class.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ProofOutcome:
    r"""
    The outcome of proving `goal` from `hypotheses`.
    """
    @property
    def status(self) -> builtins.str:
        r"""
        `"proved"`, `"disproved"` or `"unknown"`.
        """
    @property
    def report(self) -> typing.Optional[EvidenceReport]:
        r"""
        The refutation of `hypotheses AND NOT goal`, when `proved`.
        
        `proved` alone is not "independently verified" — ask the report's
        `is_certified()` or re-run `check_outcome()`.
        """
    @property
    def countermodel(self) -> typing.Optional[CheckResult]:
        r"""
        The counter-model satisfying the hypotheses and falsifying the goal.
        """
    @property
    def unknown_kind(self) -> typing.Optional[builtins.str]:
        r"""
        The classified reason the attempt was undecided, or `None`.
        """
    @property
    def unknown_detail(self) -> typing.Optional[builtins.str]:
        r"""
        The backend detail behind an undecided attempt, or `None`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RouteTrace:
    r"""
    The record of which routes the auto-dispatcher tried, and what each said.
    
    Verdict-invariant with the un-traced dispatch: the recorder never
    participates in a branch.
    """
    def to_json(self) -> builtins.str:
        r"""
        The trace as JSON — the one native serializer in the solver surface.
        """
    def __len__(self) -> builtins.int:
        r"""
        Number of recorded route attempts.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SatBvBackend:
    r"""
    The pure-Rust `QF_BV` backend, monomorphized.
    
    `SolverBackend` is a Rust trait and is deliberately NOT implementable from
    Python; this is the concrete default backend, bound so that its
    `capabilities()` and `last_stats()` are reachable. It is the only place the
    stack reports [`SolveStats`](axeyum.solver.SolveStats): the SMT-LIB front
    door returns an `SmtLibOutcome`, which carries no telemetry, and
    [`Incremental.stats()`](axeyum.solver.Incremental) is a different
    (retained-encoding) counter set.
    """
    def __new__(cls) -> SatBvBackend:
        r"""
        Creates a fresh backend. It reports no stats until it has checked.
        """
    def capabilities(self) -> BackendCapabilities:
        r"""
        What this backend can do.
        """
    def check(self, arena: ir.Arena, assertions: typing.Sequence[ir.Term], config: typing.Optional[Config] = None) -> CheckResult:
        r"""
        Decides the conjunction of `assertions`.
        
        `unknown` is a value here too. Constructs outside the scalar `QF_BV`
        fragment raise `AxeyumError` (the Rust `Unsupported`) — there is no
        oracle fallback on this backend.
        """
    def last_stats(self) -> typing.Optional[SolveStats]:
        r"""
        Measurements from the most recent [`check`](Self::check).
        
        `None` before the first check — a value, not an error, and NOT an empty
        `SolveStats` (which would read as "the check took no time").
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SolveStats:
    r"""
    Layer-attributed measurements from one backend check (`backend::SolveStats`).
    
    Tier **R** — telemetry is returned data, not a log. Every duration is
    exposed BOTH as whole nanoseconds and as seconds: a benchmark that silently
    rounds is worse than one that is awkward to read.
    """
    @property
    def translate_ns(self) -> builtins.int:
        r"""
        Nanoseconds spent translating Axeyum terms to the backend form.
        """
    @property
    def translate_seconds(self) -> builtins.float:
        r"""
        Seconds spent translating, as a float (lossy — prefer `translate_ns`).
        """
    @property
    def solve_ns(self) -> builtins.int:
        r"""
        Nanoseconds spent inside the backend's check.
        """
    @property
    def solve_seconds(self) -> builtins.float:
        r"""
        Seconds spent solving, as a float (lossy — prefer `solve_ns`).
        """
    @property
    def model_lift_ns(self) -> builtins.int:
        r"""
        Nanoseconds spent lifting a backend model into Axeyum-owned values.
        """
    @property
    def model_lift_seconds(self) -> builtins.float:
        r"""
        Seconds spent lifting the model (lossy — prefer `model_lift_ns`).
        """
    @property
    def terms_translated(self) -> builtins.int:
        r"""
        Unique DAG nodes translated.
        """
    @property
    def assertion_count(self) -> builtins.int:
        r"""
        Number of top-level assertions.
        """
    @property
    def backend(self) -> builtins.list[tuple[builtins.str, builtins.float]]:
        r"""
        Backend-reported `(name, value)` counters, in the backend's own order.
        
        Backend-specific and **not a contract** — for post-mortems. An empty
        list is a normal answer, not a missing one.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SupportRow:
    r"""
    One row of the four-axis support matrix (`support_matrix::SUPPORT_MATRIX`).
    
    Tier **R**. The four axes are INDEPENDENT on purpose: "the parser accepts
    it" is not "the solver decides it" and neither is "the `unsat` carries a
    proof".
    """
    @property
    def fragment(self) -> builtins.str:
        r"""
        The logic fragment / feature — the row key.
        """
    @property
    def parser(self) -> builtins.str:
        r"""
        parser-accepts: `"accepted"`, `"accepted-but-ignored"`,
        `"accepted (bounded)"` or `"rejected"`.
        """
    @property
    def ir(self) -> builtins.str:
        r"""
        IR-semantics: `"modeled"`, `"partial"`, `"lowered (no IR sort)"` or
        `"absent"`.
        """
    @property
    def solver(self) -> builtins.str:
        r"""
        solver-decides: `"decides"`, `"unsat decided; sat→unknown"`,
        `"sound, incomplete (unknown-safe)"` or `"unsupported"`.
        
        `"unsat decided; sat→unknown"` is a first-class honest answer, not a
        weaker form of `"decides"`.
        """
    @property
    def proof(self) -> builtins.str:
        r"""
        proof-supports: `"checked"`, `"partial-trust"` or `"none"`.
        """
    @property
    def note(self) -> builtins.str:
        r"""
        A short note grounding the four cells in real code paths.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TrustStep:
    r"""
    One reduction of the trust ledger.
    
    Tier **R**. Mirrors `trust::TrustStep` (`id` + the per-run `certified`
    bit) and carries the `TrustId` metadata alongside it.
    
    **`certified` and `ledger_certified` are different questions.**
    `ledger_certified` is `TrustId::is_certified()`: *every* result relying on
    this reduction has an independent per-query checker today. `certified` is
    what a particular run carried. For the static
    [`trust_ledger_rows()`](axeyum.solver.trust_ledger_rows) they are equal by
    construction; on an
    [`EvidenceReport.trust_steps`](axeyum.solver.EvidenceReport) they can
    differ, and reading the ledger bit as an answer about one `unsat` is the
    mistake `TrustId::is_certified`'s own doc comment warns about.
    """
    @property
    def id(self) -> builtins.str:
        r"""
        The reduction's stable label (`"bit-blast"`, `"farkas"`, …).
        """
    @property
    def meaning(self) -> builtins.str:
        r"""
        One-line meaning of the reduction.
        """
    @property
    def pedantic_level(self) -> builtins.int:
        r"""
        cvc5-style grade: 0 = hard fail (unsound if wrong) … 10 = minor.
        """
    @property
    def certified(self) -> builtins.bool:
        r"""
        Whether THIS row carried an independent certificate.
        """
    @property
    def ledger_certified(self) -> builtins.bool:
        r"""
        `TrustId::is_certified()` — whether every result relying on this
        reduction has a per-query checker. A `False` here is a trust hole.
        """
    @property
    def status(self) -> builtins.str:
        r"""
        The ledger status word, `"certified"` or `"trust hole"`.
        """
    @property
    def reference(self) -> builtins.str:
        r"""
        The governing architecture-decision record.
        """
    def __repr__(self) -> builtins.str: ...

def capabilities() -> builtins.str:
    r"""
    The capability matrix, as Markdown. Read-only data, not a log.
    """

def capability_rows() -> builtins.list[Capability]:
    r"""
    The capability ledger as structured rows, in `CAPABILITIES` source order.
    
    The same data [`capabilities()`](axeyum.solver.capabilities) renders as
    Markdown, with `assurance` and `checked_by` as separate fields.
    """

def check_auto_explained(arena: ir.Arena, assertions: typing.Sequence[ir.Term], config: typing.Optional[Config] = None) -> tuple[CheckResult, RouteTrace]:
    r"""
    Decides `assertions` and returns the route trace alongside the verdict.
    
    The two are verdict-invariant with [`solve`]. **Read the trace as a record
    of what was tried, not as "what axeyum answers for this script"** — the
    SMT-LIB front door reaches routes this flat-term dispatcher does not.
    """

def produce_evidence(arena: ir.Arena, assertions: typing.Sequence[ir.Term], config: typing.Optional[Config] = None) -> EvidenceReport:
    r"""
    Decides `assertions` and returns the verdict WITH its justification.
    """

def prove(arena: ir.Arena, hypotheses: typing.Sequence[ir.Term], goal: ir.Term, config: typing.Optional[Config] = None) -> ProofOutcome:
    r"""
    Proves `goal` from `hypotheses` by refuting `hypotheses AND NOT goal`.
    """

def recommended_portfolio(arena: ir.Arena, assertions: typing.Sequence[ir.Term]) -> builtins.list[builtins.str]:
    r"""
    The strategy order this query's shape recommends. Pure; decides nothing.
    """

def solve(arena: ir.Arena, assertions: typing.Sequence[ir.Term], config: typing.Optional[Config] = None) -> CheckResult:
    r"""
    Decides `assertions` with the multi-theory dispatcher.
    
    `unknown` comes back as a [`CheckResult`](axeyum.solver.CheckResult), never
    as an exception.
    """

def solve_with_portfolio(arena: ir.Arena, assertions: typing.Sequence[ir.Term], strategies: typing.Sequence[builtins.str], config: typing.Optional[Config] = None) -> CheckResult:
    r"""
    Runs a portfolio of strategies in order and returns the first decision.
    """

def solve_with_strategy(arena: ir.Arena, assertions: typing.Sequence[ir.Term], strategy: builtins.str, config: typing.Optional[Config] = None) -> CheckResult:
    r"""
    Decides `assertions` with one named strategy.
    """

def support_matrix() -> builtins.str:
    r"""
    The parser/IR/solver/proof support matrix, as Markdown.
    """

def support_matrix_rows() -> builtins.list[SupportRow]:
    r"""
    The four-axis support matrix as structured rows, in `SUPPORT_MATRIX` order.
    """

def trust_ids() -> builtins.list[builtins.str]:
    r"""
    Every trust-step label, in canonical order.
    """

def trust_ledger() -> builtins.str:
    r"""
    The trust ledger — which reductions are certified and which are trusted.
    """

def trust_ledger_rows() -> builtins.list[TrustStep]:
    r"""
    The trust ledger as structured rows, in `ALL_TRUST_IDS` canonical order.
    
    Each row's `certified` is the LEDGER-wide `TrustId::is_certified()`, so it
    equals `ledger_certified`. A per-run bit lives on
    `EvidenceReport.trust_steps`.
    """

def unsat_core(arena: ir.Arena, assertions: typing.Sequence[ir.Term], config: typing.Optional[Config] = None) -> typing.Optional[builtins.list[builtins.int]]:
    r"""
    A deletion-minimized unsatisfiable core, as INDICES into `assertions`.
    
    `None` when the query is not `unsat` (or the core could not be minimized).
    """

