//! Soundness-negative fuzzer for the bounded-completeness detector (task #75,
//! Hard Rule). `axeyum_smtlib::is_bounded_complete` gates a no-model→UNSAT
//! upgrade, so a wrong `true` on a query that is real-SAT-but-bounded-no-model
//! is a wrong-unsat (the worst bug class). This fuzz DELIBERATELY emits the
//! dangerous classes — a free unbounded Int, an unbounded String probed past the
//! cap, `str.to_int`, a large Int literal, a nonlinear product, a hidden binder —
//! and asserts the detector REJECTS every one (`is_bounded_complete == false`).
//! A positive-control loop confirms it still ACCEPTS genuinely bounded-complete
//! queries (so it is not vacuously always-false).
#![cfg(feature = "full")]
#![allow(
    clippy::many_single_char_names,
    clippy::similar_names,
    clippy::cast_possible_truncation
)]

use axeyum_smtlib::is_bounded_complete;

const STRING_MAX_LEN: u64 = 12;

/// Seeds swept by `detector_rejects_all_unsound_upgrades` and regenerated by
/// its coverage guard `the_generator_reaches_the_bound_one_past_the_cap`.
const DANGEROUS_SEEDS: u64 = 500;

struct Lcg(u64);
impl Lcg {
    fn new(seed: u64) -> Self {
        Lcg(seed
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407))
    }
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        // The raw state is never handed out: bit `k` of an LCG modulo 2^64
        // has period 2^(k+1), so `state & 1` alternates on every draw and a
        // decision made at a fixed draw offset is a constant, not a coin.
        // Measured 2026-09-16 (lane ax-proptest, bench-results/proptest-box-
        // audit-20260916): the above-cap arm `STRING_MAX_LEN + 1 + below(20)`
        // sat at a parity-locked draw and only produced bounds in
        // {15, 19, 23, 27, 31}, so the off-by-one bound 13 that the detector's
        // `k <= STRING_MAX_LEN` compares against appeared in 0/500 queries.
        // SplitMix64's finalizer makes every output bit depend on the state.
        let z = (self.0 ^ (self.0 >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        let z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
}

/// A short escape-free string literal.
fn lit(rng: &mut Lcg) -> String {
    const A: &[u8] = b"ABxyz";
    let n = rng.below(4);
    (0..n)
        .map(|_| A[rng.below(A.len() as u64) as usize] as char)
        .collect()
}

/// Build a query carrying exactly one DANGEROUS construct (real-sat but
/// bounded-no-model, or otherwise unsound to upgrade). All must be rejected.
fn dangerous(rng: &mut Lcg) -> String {
    let l = lit(rng);
    match rng.below(7) {
        // C1: a free unbounded Int (even alongside a bounded string).
        0 => format!(
            "(set-logic QF_SLIA)\n(declare-fun x () Int)\n(declare-fun s () String)\n\
             (assert (<= (str.len s) 5))\n(assert (> x {}))\n(check-sat)\n",
            rng.below(9)
        ),
        // C2: unbounded String probed past the cap with a constant index.
        1 => format!(
            "(set-logic QF_S)\n(declare-fun s () String)\n\
             (assert (= (str.at s {}) \"{l}\"))\n(check-sat)\n",
            50 + rng.below(200)
        ),
        // C2: unbounded String with a LOWER length bound only.
        2 => format!(
            "(set-logic QF_S)\n(declare-fun s () String)\n\
             (assert (>= (str.len s) {}))\n(check-sat)\n",
            1 + rng.below(50)
        ),
        // C2: String var with NO bound at all.
        3 => format!(
            "(set-logic QF_S)\n(declare-fun s () String)\n\
             (assert (str.contains s \"{l}\"))\n(check-sat)\n"
        ),
        // C3: str.to_int can reach 10^len ≥ 2^31.
        4 => format!(
            "(set-logic QF_SLIA)\n(declare-fun s () String)\n\
             (assert (<= (str.len s) 8))\n(assert (> (str.to_int s) {}))\n(check-sat)\n",
            rng.below(5)
        ),
        // C3: a large Int literal (≥ 2^20) can wrap the width-32 int-blast.
        5 => format!(
            "(set-logic QF_SLIA)\n(declare-fun s () String)\n\
             (assert (<= (str.len s) 8))\n(assert (< (str.len s) {}))\n(check-sat)\n",
            2_000_000 + rng.below(1_000_000)
        ),
        // C2: a length bound ABOVE the cap does not guarantee representability.
        _ => format!(
            "(set-logic QF_S)\n(declare-fun s () String)\n\
             (assert (<= (str.len s) {}))\n(assert (str.contains s \"{l}\"))\n(check-sat)\n",
            STRING_MAX_LEN + 1 + rng.below(20)
        ),
    }
}

/// Build a genuinely bounded-complete query (positive control) — must be accepted.
fn safe(rng: &mut Lcg) -> String {
    let l = lit(rng);
    let k = rng.below(STRING_MAX_LEN + 1);
    match rng.below(3) {
        0 => format!(
            "(set-logic QF_S)\n(declare-fun s () String)\n\
             (assert (<= (str.len s) {k}))\n(assert (str.contains s \"{l}\"))\n(check-sat)\n"
        ),
        1 => format!(
            "(set-logic QF_S)\n(declare-fun s () String)\n\
             (assert (< (str.len s) {}))\n(assert (not (= (str.at s 0) \"{l}\")))\n(check-sat)\n",
            k + 1
        ),
        // Ground (no free var) → bounded-complete vacuously.
        _ => format!(
            "(set-logic QF_S)\n(assert (= (str.++ \"{l}\" \"{l}\") \"{l}\"))\n(check-sat)\n"
        ),
    }
}

#[test]
fn detector_rejects_all_unsound_upgrades() {
    const SEEDS: u64 = DANGEROUS_SEEDS;
    for seed in 0..SEEDS {
        let mut rng = Lcg::new(seed);
        let q = dangerous(&mut rng);
        assert!(
            !is_bounded_complete(&q),
            "seed {seed}: detector must NOT sanction an unsound upgrade:\n{q}"
        );
    }
}

#[test]
fn detector_still_accepts_bounded_complete() {
    const SEEDS: u64 = 300;
    let mut accepted = 0u32;
    for seed in 0..SEEDS {
        let mut rng = Lcg::new(seed ^ 0xB0);
        if is_bounded_complete(&safe(&mut rng)) {
            accepted += 1;
        }
    }
    assert!(
        accepted >= 250,
        "positive control: detector must accept genuinely bounded-complete queries (got {accepted}/300)"
    );
}

/// Coverage guard for the generator box (lane ax-proptest, 2026-09-16).
///
/// Under the raw-state LCG the audit measured **0/500** dangerous queries whose
/// `str.len` upper bound is exactly one past the cap
/// (`(assert (<= (str.len s) 13))` with `STRING_MAX_LEN = 12`): the above-cap
/// arm draws `STRING_MAX_LEN + 1 + below(20)` at a parity-locked offset, so
/// only the residues {2, 6, 10, 14, 18} occurred and the bound was always one
/// of {15, 19, 23, 27, 31}. The off-by-one is the value the detector's
/// `k <= STRING_MAX_LEN` comparison is closest to getting wrong, so it must be
/// in the population. This regenerates the same population without calling
/// the detector.
///
/// Structural gaps NOT widened here (they are the box, not the PRNG): the
/// strict form `(< (str.len s) 14)` (no dangerous arm uses `<`), an Int
/// literal exactly at the 2^20 boundary (arm 5 is `2_000_000 + below(1e6)`),
/// a nonlinear product or hidden binder (no arm emits one, although the module
/// doc claims both), and `\u{...}` escapes / code points above 0xFF (the
/// alphabet literal `b"ABxyz"`; CLAUDE.md: string fuzz generators must cover
/// the full SMT-LIB literal grammar, ba0d9149).
#[test]
fn the_generator_reaches_the_bound_one_past_the_cap() {
    let one_past = format!("(assert (<= (str.len s) {}))", STRING_MAX_LEN + 1);
    let mut at_one_past = 0u64;
    let mut above_cap_arm = 0u64;
    let mut distinct_bounds = std::collections::BTreeSet::new();
    for seed in 0..DANGEROUS_SEEDS {
        let q = dangerous(&mut Lcg::new(seed));
        // The above-cap arm is the only dangerous arm that emits `<=` on
        // `str.len` together with a `str.contains`.
        if q.contains("(assert (<= (str.len s) ") && q.contains("(assert (str.contains s ") {
            above_cap_arm += 1;
            let bound: u64 = q
                .split("(assert (<= (str.len s) ")
                .nth(1)
                .and_then(|rest| rest.split(')').next())
                .and_then(|n| n.parse().ok())
                .expect("above-cap arm carries a numeric bound");
            distinct_bounds.insert(bound);
        }
        at_one_past += u64::from(q.contains(&one_past));
    }
    eprintln!(
        "bounded-completeness generator coverage over {DANGEROUS_SEEDS} seeds: above-cap arm \
         {above_cap_arm} | bound exactly {} {at_one_past} | distinct above-cap bounds {} of 20",
        STRING_MAX_LEN + 1,
        distinct_bounds.len()
    );
    // Old generator: 0 at the one-past bound and 5 distinct bounds. New
    // generator measured 2026-09-16: 3 at the one-past bound (80 draws of the
    // arm, 1 in 20 each) and 19 distinct bounds; floors are a quarter, rounded.
    assert!(
        at_one_past >= 1,
        "the bound {} (one past the cap) reached only {at_one_past}/{DANGEROUS_SEEDS} queries (old generator: 0)",
        STRING_MAX_LEN + 1
    );
    assert!(
        distinct_bounds.len() >= 10,
        "the above-cap arm produced only {} distinct bounds (old generator: 5 of 20)",
        distinct_bounds.len()
    );
}
