//! Every committed generated-module fixture must be accepted by the **real
//! Lean binary**, and must depend on no more than the axioms it declares.
//!
//! `reconstruct::tests`'s family gates assert that each proof family still
//! generates its committed `.lean` fixture. That is a *stability* claim: on its
//! own it says only that the printer did not change, and a stability claim can
//! be satisfied by a module nothing would accept. (Its predecessor was a
//! `(length, fnv1a)` pin, which could not even show a reader *what* changed —
//! that instrument once carried a hand-written note blessing a moved number.)
//!
//! This suite supplies the missing half: the fixtures are checked, by Lean
//! 4.30, to be modules that elaborate, type-check, and prove their theorem from
//! the axioms they declare inline. A printer change is then legible in two
//! directions — the fixture diff shows *what* moved, and this suite shows
//! whether the result is still something Lean accepts.
//!
//! Lean is optional locally and mandatory under `AXEYUM_REQUIRE_LEAN=1`, like
//! the other cross-checks. The fixture inventory is asserted *without* Lean, so
//! a missing or emptied fixture directory fails even on a machine with no
//! toolchain — a green run over zero fixtures is this repository's signature
//! failure mode.

use std::path::{Path, PathBuf};
use std::process::Command;

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/lean-modules")
}

fn fixtures() -> Vec<(String, String)> {
    let mut found: Vec<(String, String)> = std::fs::read_dir(fixture_dir())
        .expect("the generated-module fixture directory must exist")
        .map(|entry| entry.expect("readable fixture entry").path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "lean")
        })
        .map(|path| {
            let name = path
                .file_stem()
                .expect("fixture file name")
                .to_string_lossy()
                .into_owned();
            (
                name,
                std::fs::read_to_string(&path).expect("readable fixture"),
            )
        })
        .collect();
    found.sort();
    found
}

// Real-Lean toolchain discovery and skip accounting, shared with the other
// Lean-gated suites. The replaced local copy searched only `AXEYUM_LEAN_BIN`
// and `PATH`, so an elan-installed toolchain (which elan does NOT put on
// `PATH`) was invisible and all 15 fixtures went unchecked behind an `ok`.
#[path = "../../axeyum-lean-kernel/tests/support/lean_probe.rs"]
mod lean_probe;

/// The theorem a module exports, taken from its own `#print axioms` command.
fn exported_theorem(source: &str) -> &str {
    source
        .lines()
        .find_map(|line| line.strip_prefix("#print axioms "))
        .expect("every generated module ends in a #print axioms audit")
        .trim()
}

#[test]
fn every_family_gate_has_a_committed_module_fixture() {
    let fixtures = fixtures();
    assert!(
        fixtures.len() >= 15,
        "expected one fixture per generated-module gate, found {}",
        fixtures.len()
    );
    for (name, source) in &fixtures {
        assert!(!source.is_empty(), "{name}: empty fixture");
        assert!(
            source.starts_with("-- Auto-generated by axeyum-lean-kernel"),
            "{name}: not a generated module"
        );
        assert!(!source.contains("sorry"), "{name}: contains sorry");
        assert!(
            source.contains(&format!("theorem {}", exported_theorem(source))),
            "{name}: the audited theorem is not declared"
        );
    }
    // Each family the reconstruction gates cover must be represented, so a
    // deleted fixture cannot quietly delete its gate.
    for family in [
        "arithmetic",
        "bitblast",
        "cnf",
        "datatype",
        "equality",
        "quantifier",
        "resolution",
    ] {
        assert!(
            fixtures.iter().any(|(name, _)| name.starts_with(family)),
            "no committed fixture for the {family} family"
        );
    }
}

#[test]
fn every_committed_module_fixture_is_accepted_by_real_lean() {
    let fixtures = fixtures();
    let Some(lean) = lean_probe::lean_bin_or_skip("module-fixtures", fixtures.len()) else {
        return;
    };

    let directory = std::env::temp_dir().join(format!(
        "axeyum_lean_module_fixtures_{}",
        std::process::id()
    ));
    std::fs::create_dir_all(&directory).expect("create fixture check directory");
    let mut checked = 0usize;
    for (name, source) in &fixtures {
        let file = directory.join(format!("{name}.lean"));
        std::fs::write(&file, source).expect("write fixture");
        let output = Command::new(&lean)
            .arg(&file)
            .output()
            .expect("run Lean on a committed fixture");
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            output.status.success(),
            "Lean rejected the committed fixture {name}\nstdout:\n{stdout}\nstderr:\n{stderr}"
        );
        // The audit command must actually have run, and must not report a
        // `sorry`-shaped hole.
        let theorem = exported_theorem(source);
        assert!(
            stdout.contains(theorem),
            "{name}: #print axioms produced no output naming {theorem}: {stdout}"
        );
        assert!(!stdout.contains("sorryAx"), "{name}: {stdout}");
        checked += 1;
    }
    assert_eq!(checked, fixtures.len(), "every fixture must be checked");
    assert!(
        checked >= 15,
        "a green run over {checked} fixtures is not a gate"
    );
    let _ = std::fs::remove_dir_all(directory);
    println!("real Lean accepted {checked} committed generated-module fixtures");
    lean_probe::report_checked("module-fixtures", checked);
}

/// Negative control: the check above must be able to fail. A fixture whose
/// proof term is given the wrong assumed hypothesis has to be rejected by the
/// same binary, or acceptance means nothing.
#[test]
fn a_mutated_fixture_is_rejected_by_real_lean() {
    let Some(lean) = lean_probe::lean_bin_or_skip("mutated-fixture-control", 1) else {
        return;
    };
    let (name, source) = fixtures()
        .into_iter()
        .find(|(name, _)| name == "equality-transitivity")
        .expect("the equality transitivity fixture must exist");
    // Substitute one assumed hypothesis for another *inside the proof term*.
    // Both are declared and both are equations, so the module still parses and
    // every name resolves; only a type checker can tell that the equation no
    // longer matches the eliminator's motive. The hypothesis names are read out
    // of the fixture rather than hard-coded, so re-blessing cannot silently
    // turn this control into a no-op.
    let hypotheses: Vec<&str> = source
        .lines()
        .filter_map(|line| line.strip_prefix("axiom "))
        .filter_map(|line| line.split_once(" :").map(|(name, _)| name))
        .filter(|name| name.starts_with("axeyum.reconstruct.hyp."))
        .collect();
    assert!(
        hypotheses.len() >= 2,
        "{name}: the control needs two distinct hypotheses, found {hypotheses:?}"
    );
    let (head, proof) = source
        .split_once("\ntheorem ")
        .expect("a generated module declares its theorem");
    let mutated = format!(
        "{head}\ntheorem {}",
        proof.replacen(hypotheses[0], hypotheses[1], 1)
    );
    assert_ne!(mutated, source, "{name}: the mutation must change bytes");

    let directory = std::env::temp_dir().join(format!(
        "axeyum_lean_module_mutation_{}",
        std::process::id()
    ));
    std::fs::create_dir_all(&directory).expect("create mutation directory");
    let file = directory.join("mutated.lean");
    std::fs::write(&file, &mutated).expect("write mutated fixture");
    let output = Command::new(&lean)
        .arg(&file)
        .output()
        .expect("run Lean on the mutated fixture");
    assert!(
        !output.status.success(),
        "Lean accepted a mutated refutation; the fixture check proves nothing:\n{}",
        String::from_utf8_lossy(&output.stdout)
    );
    let _ = std::fs::remove_dir_all(directory);
    lean_probe::report_checked("mutated-fixture-control", 1);
}
