//! Field tables for the nine `*Prelude` packages -- GENERATED, do not edit.
//!
//! Regenerate with `python3 scripts/gen-py-prelude-fields.py`; the same script
//! with `--check` fails when this file is stale. Rust has no reflection, so the
//! binding's flat `{field name -> NameId}` view of a prelude package has to name
//! every field, and a hand-written list rots into a MISSING attribute -- which
//! reads exactly like `that theorem does not exist`.

use axeyum_lean_kernel::{
    ArithPrelude, CPointPrelude, CRealPrelude, ComplexPrelude, IntPrelude, LogicPrelude, NameId,
    NatPrelude, RatPrelude, StringPrelude,
};

/// One package's flattened contents: scalar names, name lists, and the
/// sub-packages it was built on top of.
pub(super) struct Fields {
    /// `(field name, interned name)`, in struct declaration order.
    pub(super) names: Vec<(&'static str, NameId)>,
    /// `(field name, interned names)` for the one `Vec<NameId>` field.
    pub(super) lists: Vec<(&'static str, Vec<NameId>)>,
}

/// The `LogicPrelude` field table (84 names,
/// 0 name lists, 0 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn logic(p: &LogicPrelude) -> Fields {
    Fields {
        names: vec![
            ("true_", p.true_),
            ("true_intro", p.true_intro),
            ("true_rec", p.true_rec),
            ("false_", p.false_),
            ("false_rec", p.false_rec),
            ("and", p.and),
            ("and_intro", p.and_intro),
            ("and_rec", p.and_rec),
            ("and_left", p.and_left),
            ("and_right", p.and_right),
            ("or", p.or),
            ("or_inl", p.or_inl),
            ("or_inr", p.or_inr),
            ("or_rec", p.or_rec),
            ("or_elim", p.or_elim),
            ("or_resolve_left", p.or_resolve_left),
            ("or_resolve_right", p.or_resolve_right),
            ("iff", p.iff),
            ("iff_intro", p.iff_intro),
            ("iff_rec", p.iff_rec),
            ("iff_mp", p.iff_mp),
            ("iff_mpr", p.iff_mpr),
            ("eq", p.eq),
            ("eq_refl", p.eq_refl),
            ("eq_rec", p.eq_rec),
            ("eq_uparam", p.eq_uparam),
            ("eq_symm", p.eq_symm),
            ("congr_fun_prime", p.congr_fun_prime),
            ("exists_", p.exists_),
            ("exists_intro", p.exists_intro),
            ("exists_rec", p.exists_rec),
            ("exists_uparam", p.exists_uparam),
            ("acc", p.acc),
            ("acc_intro", p.acc_intro),
            ("acc_rec", p.acc_rec),
            ("acc_inv", p.acc_inv),
            ("acc_uparam", p.acc_uparam),
            ("well_founded", p.well_founded),
            ("well_founded_fix", p.well_founded_fix),
            ("well_founded_fix_eq", p.well_founded_fix_eq),
            ("well_founded_fix_vparam", p.well_founded_fix_vparam),
            ("not", p.not),
            ("absurd", p.absurd),
            ("absurd_vparam", p.absurd_vparam),
            ("mt", p.mt),
            ("not_not_intro", p.not_not_intro),
            ("noncontradiction", p.noncontradiction),
            ("not_not_not", p.not_not_not),
            ("demorgan_not_or", p.demorgan_not_or),
            ("demorgan_not_or_converse", p.demorgan_not_or_converse),
            ("demorgan_or_not_and", p.demorgan_or_not_and),
            ("not_not_em", p.not_not_em),
            ("dne_of_em", p.dne_of_em),
            ("em_of_dne", p.em_of_dne),
            ("peirce_of_em", p.peirce_of_em),
            ("em_of_peirce", p.em_of_peirce),
            ("not_not_not_intro", p.not_not_not_intro),
            ("not_not_and", p.not_not_and),
            ("not_not_imp", p.not_not_imp),
            ("bool_false_ne_true", p.bool_false_ne_true),
            ("bool_true_ne_false", p.bool_true_ne_false),
            ("decidable", p.decidable),
            ("decidable_is_false", p.decidable_is_false),
            ("decidable_is_true", p.decidable_is_true),
            ("decidable_rec", p.decidable_rec),
            ("decide", p.decide),
            ("of_decide_eq_true", p.of_decide_eq_true),
            ("of_decide_eq_false", p.of_decide_eq_false),
            ("decidable_em", p.decidable_em),
            ("decidable_by_cases", p.decidable_by_cases),
            ("decidable_by_cases_vparam", p.decidable_by_cases_vparam),
            ("decidable_of_bool", p.decidable_of_bool),
            ("decidable_and", p.decidable_and),
            ("decidable_or", p.decidable_or),
            ("decidable_not", p.decidable_not),
            (
                "decidable_decide_eq_true_iff",
                p.decidable_decide_eq_true_iff,
            ),
            ("bool_", p.bool_),
            ("bool_true", p.bool_true),
            ("bool_false", p.bool_false),
            ("bool_rec", p.bool_rec),
            ("nat", p.nat),
            ("nat_zero", p.nat_zero),
            ("nat_succ", p.nat_succ),
            ("nat_rec", p.nat_rec),
        ],
        lists: Vec::new(),
    }
}

/// The `NatPrelude` field table (244 names,
/// 0 name lists, 1 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn nat(p: &NatPrelude) -> Fields {
    Fields {
        names: vec![
            ("nat", p.nat),
            ("zero", p.zero),
            ("succ", p.succ),
            ("rec", p.rec),
            ("add", p.add),
            ("mul", p.mul),
            ("pow", p.pow),
            ("beq", p.beq),
            ("beq_refl", p.beq_refl),
            ("eq_of_beq_eq_true", p.eq_of_beq_eq_true),
            ("beq_eq_true_of_eq", p.beq_eq_true_of_eq),
            ("beq_eq_true_iff", p.beq_eq_true_iff),
            ("div_mod_state", p.div_mod_state),
            ("div", p.div),
            ("mod_", p.mod_),
            ("gcd", p.gcd),
            ("sum_range", p.sum_range),
            ("factorial", p.factorial),
            ("pred", p.pred),
            ("sub", p.sub),
            ("no_confusion_type", p.no_confusion_type),
            ("no_confusion", p.no_confusion),
            ("succ_ne_zero", p.succ_ne_zero),
            ("not_lt_zero", p.not_lt_zero),
            ("div_zero", p.div_zero),
            ("mod_zero", p.mod_zero),
            ("zero_div", p.zero_div),
            ("zero_mod", p.zero_mod),
            ("div_succ", p.div_succ),
            ("mod_succ", p.mod_succ),
            ("add_zero", p.add_zero),
            ("add_succ", p.add_succ),
            ("mul_zero", p.mul_zero),
            ("mul_succ", p.mul_succ),
            ("pow_zero", p.pow_zero),
            ("pow_add", p.pow_add),
            ("pow_succ", p.pow_succ),
            ("pred_zero", p.pred_zero),
            ("pred_succ", p.pred_succ),
            ("sub_zero", p.sub_zero),
            ("sub_succ", p.sub_succ),
            ("succ_sub_succ", p.succ_sub_succ),
            ("sub_self", p.sub_self),
            ("add_sub_cancel_left", p.add_sub_cancel_left),
            ("sum_range_zero", p.sum_range_zero),
            ("sum_range_succ", p.sum_range_succ),
            ("sum_range_congr", p.sum_range_congr),
            ("mul_sum_range", p.mul_sum_range),
            ("mul_sum_range_pow", p.mul_sum_range_pow),
            ("factorial_zero", p.factorial_zero),
            ("factorial_succ", p.factorial_succ),
            ("zero_add", p.zero_add),
            ("succ_add", p.succ_add),
            ("add_comm", p.add_comm),
            ("add_assoc", p.add_assoc),
            ("add_right_comm", p.add_right_comm),
            ("succ_injective", p.succ_injective),
            ("add_right_cancel", p.add_right_cancel),
            ("add_left_cancel", p.add_left_cancel),
            ("zero_mul", p.zero_mul),
            ("succ_mul", p.succ_mul),
            ("mul_comm", p.mul_comm),
            ("left_distrib", p.left_distrib),
            ("right_distrib", p.right_distrib),
            ("mul_assoc", p.mul_assoc),
            ("one_mul", p.one_mul),
            ("mul_one", p.mul_one),
            ("le", p.le),
            ("lt", p.lt),
            ("in_closed_interval", p.in_closed_interval),
            ("le_refl", p.le_refl),
            ("le_step", p.le_step),
            ("le_rec", p.le_rec),
            ("zero_le", p.zero_le),
            ("le_succ_succ", p.le_succ_succ),
            ("le_of_succ_le_succ", p.le_of_succ_le_succ),
            ("le_trans", p.le_trans),
            ("lt_or_eq_of_le", p.lt_or_eq_of_le),
            ("lt_of_lt_of_le", p.lt_of_lt_of_le),
            ("lt_of_le_of_lt", p.lt_of_le_of_lt),
            ("lt_irrefl", p.lt_irrefl),
            ("lt_well_founded", p.lt_well_founded),
            ("le_total", p.le_total),
            ("not_succ_le_zero", p.not_succ_le_zero),
            ("le_antisymm", p.le_antisymm),
            ("le_intro", p.le_intro),
            ("le_dest", p.le_dest),
            ("le_add_right", p.le_add_right),
            ("add_le_add_left", p.add_le_add_left),
            ("add_lt_add_left", p.add_lt_add_left),
            ("add_le_add_right", p.add_le_add_right),
            ("le_of_add_le_add_left", p.le_of_add_le_add_left),
            ("le_of_add_le_add_right", p.le_of_add_le_add_right),
            ("mul_le_mul_left", p.mul_le_mul_left),
            ("le_of_mul_le_mul_left_succ", p.le_of_mul_le_mul_left_succ),
            ("le_of_mul_le_mul_left", p.le_of_mul_le_mul_left),
            ("mul_left_cancel_of_pos", p.mul_left_cancel_of_pos),
            ("sub_add_cancel", p.sub_add_cancel),
            ("sub_eq_zero_of_le", p.sub_eq_zero_of_le),
            ("sub_le_iff_le_add", p.sub_le_iff_le_add),
            ("mul_sub_left_distrib", p.mul_sub_left_distrib),
            ("mul_sub_left_distrib_total", p.mul_sub_left_distrib_total),
            ("le_refl_thm", p.le_refl_thm),
            ("le_succ", p.le_succ),
            ("succ_le_succ", p.succ_le_succ),
            ("le_of_lt_succ", p.le_of_lt_succ),
            ("lt_succ_self", p.lt_succ_self),
            ("lt_succ_of_le", p.lt_succ_of_le),
            ("lt_add_one", p.lt_add_one),
            ("not_succ_le_self", p.not_succ_le_self),
            ("le_succ_of_le", p.le_succ_of_le),
            ("zero_lt_succ", p.zero_lt_succ),
            ("pred_le", p.pred_le),
            ("pred_le_pred", p.pred_le_pred),
            ("sub_le", p.sub_le),
            ("sub_lt", p.sub_lt),
            ("succ_sub_succ_eq_sub", p.succ_sub_succ_eq_sub),
            ("lt_of_not_le", p.lt_of_not_le),
            ("lt_or_ge", p.lt_or_ge),
            ("le_of_lt_add_one", p.le_of_lt_add_one),
            ("zero_lt_of_ne_zero", p.zero_lt_of_ne_zero),
            ("ne_of_beq_eq_false", p.ne_of_beq_eq_false),
            ("ble", p.ble),
            ("ble_self_eq_true", p.ble_self_eq_true),
            ("ble_succ_eq_true", p.ble_succ_eq_true),
            ("ble_eq_true_of_le", p.ble_eq_true_of_le),
            ("le_of_ble_eq_true", p.le_of_ble_eq_true),
            ("not_le_of_not_ble_eq_true", p.not_le_of_not_ble_eq_true),
            ("div_mod", p.div_mod),
            ("div_mod_exists", p.div_mod_exists),
            ("div_mod_unique", p.div_mod_unique),
            ("div_mod_bounds", p.div_mod_bounds),
            ("div_mod_mul_le_iff", p.div_mod_mul_le_iff),
            ("div_mod_lt_mul_iff", p.div_mod_lt_mul_iff),
            ("div_mod_add_multiple", p.div_mod_add_multiple),
            ("dvd", p.dvd),
            (
                "div_mod_remainder_eq_zero_iff_dvd",
                p.div_mod_remainder_eq_zero_iff_dvd,
            ),
            ("div_mod_exact_exists", p.div_mod_exact_exists),
            ("div_mod_exec", p.div_mod_exec),
            ("mod_lt", p.mod_lt),
            ("gcd_zero_left", p.gcd_zero_left),
            ("gcd_succ", p.gcd_succ),
            ("gcd_dvd", p.gcd_dvd),
            ("gcd_dvd_left", p.gcd_dvd_left),
            ("gcd_dvd_right", p.gcd_dvd_right),
            ("dvd_gcd", p.dvd_gcd),
            ("dvd_gcd_iff", p.dvd_gcd_iff),
            ("bezout", p.bezout),
            ("gcd_bezout", p.gcd_bezout),
            ("mod_eq", p.mod_eq),
            ("mod_eq_refl", p.mod_eq_refl),
            ("mod_eq_symm", p.mod_eq_symm),
            ("mod_eq_trans", p.mod_eq_trans),
            ("mod_eq_add_left", p.mod_eq_add_left),
            ("mod_eq_add_right", p.mod_eq_add_right),
            ("mod_eq_add", p.mod_eq_add),
            ("mod_eq_mul_left", p.mod_eq_mul_left),
            ("mod_eq_mul_right", p.mod_eq_mul_right),
            ("mod_eq_mul", p.mod_eq_mul),
            (
                "div_mod_same_remainder_mod_eq",
                p.div_mod_same_remainder_mod_eq,
            ),
            (
                "div_mod_remainder_eq_of_mod_eq",
                p.div_mod_remainder_eq_of_mod_eq,
            ),
            (
                "mod_eq_iff_div_mod_remainder_eq",
                p.mod_eq_iff_div_mod_remainder_eq,
            ),
            ("mod_eq_zero_of_dvd", p.mod_eq_zero_of_dvd),
            ("dvd_of_mod_eq_zero_of_pos", p.dvd_of_mod_eq_zero_of_pos),
            ("mod_eq_zero_iff_dvd", p.mod_eq_zero_iff_dvd),
            ("valuation_at", p.valuation_at),
            ("dvd_mul", p.dvd_mul),
            ("dvd_refl", p.dvd_refl),
            ("dvd_zero", p.dvd_zero),
            ("dvd_trans", p.dvd_trans),
            ("dvd_mul_right_of_dvd", p.dvd_mul_right_of_dvd),
            ("dvd_add_iff_right", p.dvd_add_iff_right),
            ("dvd_mod_iff", p.dvd_mod_iff),
            ("dvd_add", p.dvd_add),
            ("dvd_add_right_cancel_of_pos", p.dvd_add_right_cancel_of_pos),
            ("euclid_lemma", p.euclid_lemma),
            ("prime_dvd_choose", p.prime_dvd_choose),
            ("one_le_factorial", p.one_le_factorial),
            ("exists_prime_gt", p.exists_prime_gt),
            ("not_dvd_one_of_two_le", p.not_dvd_one_of_two_le),
            ("eq_one_of_dvd_one", p.eq_one_of_dvd_one),
            ("coprime_of_bezout_one", p.coprime_of_bezout_one),
            ("bezout_of_scaled", p.bezout_of_scaled),
            ("gcd_cofactors_coprime", p.gcd_cofactors_coprime),
            ("div_mul_cancel_of_dvd", p.div_mul_cancel_of_dvd),
            ("one_le_right_of_mul", p.one_le_right_of_mul),
            ("one_le_left_of_mul", p.one_le_left_of_mul),
            ("one_le_of_dvd_pos", p.one_le_of_dvd_pos),
            ("one_le_mul", p.one_le_mul),
            ("mul_eq_zero", p.mul_eq_zero),
            ("dvd_factorial_of_le", p.dvd_factorial_of_le),
            (
                "not_dvd_one_add_mul_of_two_le",
                p.not_dvd_one_add_mul_of_two_le,
            ),
            ("valuation_at_two_mul_sq", p.valuation_at_two_mul_sq),
            ("le_of_dvd", p.le_of_dvd),
            ("two_le_succ_or_eq_one", p.two_le_succ_or_eq_one),
            ("least_divisor_search", p.least_divisor_search),
            ("exists_prime_dvd", p.exists_prime_dvd),
            ("coprime_of_lt_prime", p.coprime_of_lt_prime),
            ("choose", p.choose),
            ("choose_zero_right", p.choose_zero_right),
            ("choose_succ_succ", p.choose_succ_succ),
            ("zero_choose_succ", p.zero_choose_succ),
            ("choose_succ_self_eq_zero", p.choose_succ_self_eq_zero),
            ("choose_self", p.choose_self),
            ("choose_symm", p.choose_symm),
            ("sum_range_add", p.sum_range_add),
            ("sum_range_shift_front", p.sum_range_shift_front),
            ("sum_range_congr_lt", p.sum_range_congr_lt),
            ("add_pow_zero", p.add_pow_zero),
            ("add_pow_one", p.add_pow_one),
            ("add_pow", p.add_pow),
            ("one_pow", p.one_pow),
            ("le_sum_range_of_lt", p.le_sum_range_of_lt),
            ("sum_choose_row", p.sum_choose_row),
            ("choose_le_two_pow", p.choose_le_two_pow),
            ("succ_sub_of_le", p.succ_sub_of_le),
            ("succ_mul_choose_eq", p.succ_mul_choose_eq),
            ("mod_eq_pow", p.mod_eq_pow),
            ("dvd_sum_range_of_forall_lt", p.dvd_sum_range_of_forall_lt),
            ("add_pow_modeq_prime", p.add_pow_modeq_prime),
            ("pow_prime_modeq_self", p.pow_prime_modeq_self),
            ("fin", p.fin),
            ("fin_mk", p.fin_mk),
            ("fin_rec", p.fin_rec),
            ("fin_val", p.fin_val),
            ("fin_is_lt", p.fin_is_lt),
            ("fin_val_mk", p.fin_val_mk),
            ("injective_on", p.injective_on),
            ("surjective_on", p.surjective_on),
            ("maps_into", p.maps_into),
            (
                "injective_on_imp_surjective_on",
                p.injective_on_imp_surjective_on,
            ),
            ("restrict_injective", p.restrict_injective),
            ("restrict_maps_into", p.restrict_maps_into),
            ("transposition", p.transposition),
            ("transposition_involutive", p.transposition_involutive),
            ("transposition_injective", p.transposition_injective),
            ("transposition_maps_into", p.transposition_maps_into),
            ("conjugate_injective", p.conjugate_injective),
            ("conjugate_maps_into", p.conjugate_maps_into),
            ("setwise_fixed", p.setwise_fixed),
            ("add_sub_cancel_of_le", p.add_sub_cancel_of_le),
            ("sum_range_diagonal", p.sum_range_diagonal),
            ("restrict_pair_injective", p.restrict_pair_injective),
            ("restrict_pair_maps_into", p.restrict_pair_maps_into),
        ],
        lists: Vec::new(),
    }
}

/// The sub-packages `NatPrelude` carries, by field name.
#[must_use]
pub(super) fn nat_sub(p: &NatPrelude) -> Vec<(&'static str, Sub)> {
    vec![("logic", Sub::Logic(Box::new(p.logic)))]
}

/// The `IntPrelude` field table (172 names,
/// 0 name lists, 2 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn int(p: &IntPrelude) -> Fields {
    Fields {
        names: vec![
            ("z", p.z),
            ("of_nat", p.of_nat),
            ("neg_succ", p.neg_succ),
            ("rec", p.rec),
            ("neg_of_nat", p.neg_of_nat),
            ("sub_nat_nat", p.sub_nat_nat),
            ("sub_nat_nat_succ_succ", p.sub_nat_nat_succ_succ),
            ("sub_nat_nat_add_add", p.sub_nat_nat_add_add),
            ("sub_nat_nat_add_add_left", p.sub_nat_nat_add_add_left),
            ("sub_nat_nat_zero", p.sub_nat_nat_zero),
            ("zero_sub_nat_nat", p.zero_sub_nat_nat),
            ("sub_nat_nat_add_left", p.sub_nat_nat_add_left),
            ("sub_nat_nat_add_right", p.sub_nat_nat_add_right),
            ("sub_nat_nat_elim", p.sub_nat_nat_elim),
            ("of_nat_add_sub_nat_nat", p.of_nat_add_sub_nat_nat),
            ("sub_nat_nat_add_of_nat", p.sub_nat_nat_add_of_nat),
            ("sub_nat_nat_add_neg_succ", p.sub_nat_nat_add_neg_succ),
            ("neg_succ_add_sub_nat_nat", p.neg_succ_add_sub_nat_nat),
            ("of_nat_add_neg_of_nat", p.of_nat_add_neg_of_nat),
            ("neg_of_nat_add_of_nat", p.neg_of_nat_add_of_nat),
            ("neg_of_nat_add_neg_of_nat", p.neg_of_nat_add_neg_of_nat),
            ("neg_of_nat_add_sub_nat_nat", p.neg_of_nat_add_sub_nat_nat),
            ("mul_of_nat_neg_of_nat", p.mul_of_nat_neg_of_nat),
            ("mul_neg_of_nat_of_nat", p.mul_neg_of_nat_of_nat),
            ("mul_neg_succ_neg_of_nat", p.mul_neg_succ_neg_of_nat),
            ("mul_neg_of_nat_neg_succ", p.mul_neg_of_nat_neg_succ),
            ("of_nat_mul_sub_nat_nat", p.of_nat_mul_sub_nat_nat),
            ("neg_succ_mul_sub_nat_nat", p.neg_succ_mul_sub_nat_nat),
            ("le_of_nat_add", p.le_of_nat_add),
            ("le_dest", p.le_dest),
            ("lt_of_nat_add", p.lt_of_nat_add),
            ("lt_dest", p.lt_dest),
            ("add", p.add),
            ("mul", p.mul),
            ("neg", p.neg),
            ("sub", p.sub),
            ("zero", p.zero),
            ("one", p.one),
            ("le", p.le),
            ("lt", p.lt),
            ("le_refl", p.le_refl),
            ("le_trans", p.le_trans),
            ("lt_irrefl", p.lt_irrefl),
            ("lt_trans", p.lt_trans),
            ("lt_of_lt_of_le", p.lt_of_lt_of_le),
            ("lt_of_le_of_lt", p.lt_of_le_of_lt),
            ("le_of_lt", p.le_of_lt),
            ("add_le_add", p.add_le_add),
            ("add_comm", p.add_comm),
            ("add_assoc", p.add_assoc),
            ("add_zero", p.add_zero),
            ("add_neg", p.add_neg),
            ("add_neg_cancel_right", p.add_neg_cancel_right),
            ("add_lt_add_of_le_of_lt", p.add_lt_add_of_le_of_lt),
            ("mul_le_mul_of_nonneg_left", p.mul_le_mul_of_nonneg_left),
            ("zero_lt_one", p.zero_lt_one),
            ("mul_comm", p.mul_comm),
            ("mul_assoc", p.mul_assoc),
            ("mul_one", p.mul_one),
            ("one_mul", p.one_mul),
            ("neg_one_mul", p.neg_one_mul),
            ("mul_zero", p.mul_zero),
            ("left_distrib", p.left_distrib),
            ("mul_neg", p.mul_neg),
            ("mul_sub", p.mul_sub),
            ("mul_nonneg", p.mul_nonneg),
            ("mul_pos", p.mul_pos),
            ("sq_nonneg", p.sq_nonneg),
            ("pow", p.pow),
            ("pow_zero", p.pow_zero),
            ("pow_succ", p.pow_succ),
            ("pow_add", p.pow_add),
            ("pow_mul", p.pow_mul),
            ("prod_range", p.prod_range),
            ("prod_range_zero", p.prod_range_zero),
            ("prod_range_succ", p.prod_range_succ),
            ("prod_range_congr", p.prod_range_congr),
            ("prod_range_congr_lt", p.prod_range_congr_lt),
            ("prod_range_swap_adjacent", p.prod_range_swap_adjacent),
            ("prod_range_swap", p.prod_range_swap),
            ("prod_range_permute", p.prod_range_permute),
            ("prod_range_mul", p.prod_range_mul),
            ("no_int_between", p.no_int_between),
            ("le_total", p.le_total),
            ("lt_of_le_of_ne", p.lt_of_le_of_ne),
            ("le_antisymm", p.le_antisymm),
            ("euclidean_decomposition", p.euclidean_decomposition),
            ("euclid_of_nat", p.euclid_of_nat),
            ("euclid_neg_succ", p.euclid_neg_succ),
            ("ediv", p.ediv),
            ("emod", p.emod),
            ("ediv_add_emod", p.ediv_add_emod),
            ("emod_nonneg", p.emod_nonneg),
            ("emod_lt_of_pos", p.emod_lt_of_pos),
            ("ediv_emod_unique", p.ediv_emod_unique),
            ("dvd", p.dvd),
            ("dvd_refl", p.dvd_refl),
            ("dvd_trans", p.dvd_trans),
            ("dvd_add", p.dvd_add),
            ("dvd_mul_right", p.dvd_mul_right),
            ("dvd_mul_left", p.dvd_mul_left),
            ("emod_eq_zero_iff_dvd", p.emod_eq_zero_iff_dvd),
            ("mod_eq", p.mod_eq),
            ("mod_eq_refl", p.mod_eq_refl),
            ("mod_eq_symm", p.mod_eq_symm),
            ("mod_eq_trans", p.mod_eq_trans),
            ("mod_eq_iff_dvd", p.mod_eq_iff_dvd),
            ("mod_eq_of_nat_mod_eq", p.mod_eq_of_nat_mod_eq),
            ("mod_eq_add_right", p.mod_eq_add_right),
            ("mod_eq_add_left", p.mod_eq_add_left),
            ("mod_eq_mul_left", p.mod_eq_mul_left),
            ("mod_eq_mul_right", p.mod_eq_mul_right),
            ("mod_eq_mul", p.mod_eq_mul),
            ("mod_eq_cancel", p.mod_eq_cancel),
            ("mod_eq_inverse_exists", p.mod_eq_inverse_exists),
            ("mod_eq_inverse_unique", p.mod_eq_inverse_unique),
            ("mod_eq_pow", p.mod_eq_pow),
            ("mod_eq_prod_range", p.mod_eq_prod_range),
            ("mod_eq_prod_range_lt", p.mod_eq_prod_range_lt),
            ("emod_neg", p.emod_neg),
            ("mod_eq_of_neg_modulus", p.mod_eq_of_neg_modulus),
            ("mod_eq_neg_modulus", p.mod_eq_neg_modulus),
            ("mod_eq_one", p.mod_eq_one),
            ("nat_abs", p.nat_abs),
            ("of_nat_nat_abs_of_nonneg", p.of_nat_nat_abs_of_nonneg),
            ("nat_abs_neg_of_nat", p.nat_abs_neg_of_nat),
            ("nat_abs_neg", p.nat_abs_neg),
            ("nat_abs_pow", p.nat_abs_pow),
            ("gcd", p.gcd),
            ("nat_abs_mul", p.nat_abs_mul),
            ("dvd_of_nat_abs_dvd", p.dvd_of_nat_abs_dvd),
            ("nat_abs_dvd_nat_abs_of_dvd", p.nat_abs_dvd_nat_abs_of_dvd),
            ("gcd_dvd_left", p.gcd_dvd_left),
            ("gcd_dvd_right", p.gcd_dvd_right),
            ("gcd_comm", p.gcd_comm),
            ("gcd_one_right", p.gcd_one_right),
            ("gcd_zero_right", p.gcd_zero_right),
            ("dvd_gcd", p.dvd_gcd),
            ("gcd_eq_gcd_ab", p.gcd_eq_gcd_ab),
            ("coprime", p.coprime),
            ("coprime_of_bezout_one", p.coprime_of_bezout_one),
            ("gauss_lemma", p.gauss_lemma),
            ("euclid_lemma", p.euclid_lemma),
            ("euclid_infinitude", p.euclid_infinitude),
            ("crt_exists", p.crt_exists),
            ("crt_unique", p.crt_unique),
            ("rat", p.rat),
            ("rat_mk", p.rat_mk),
            ("rat_normalize", p.rat_normalize),
            ("rat_rec", p.rat_rec),
            ("rat_num", p.rat_num),
            ("rat_den", p.rat_den),
            ("rat_den_pos", p.rat_den_pos),
            ("rat_mul", p.rat_mul),
            ("rat_reduced", p.rat_reduced),
            ("rat_neg", p.rat_neg),
            ("rat_add", p.rat_add),
            ("eq_em", p.eq_em),
            ("factorial", p.factorial),
            ("factorial_zero", p.factorial_zero),
            ("factorial_succ", p.factorial_succ),
            ("self_inverse_mod_prime", p.self_inverse_mod_prime),
            ("factorial_pos", p.factorial_pos),
            ("of_nat_pow", p.of_nat_pow),
            ("pow_prime_sub_one_modeq_one", p.pow_prime_sub_one_modeq_one),
            ("mul_inv_of_pow", p.mul_inv_of_pow),
            ("inverse_index", p.inverse_index),
            ("inverse_index_maps_into", p.inverse_index_maps_into),
            ("inverse_index_injective", p.inverse_index_injective),
            ("inverse_index_fixed_point", p.inverse_index_fixed_point),
            ("inverse_index_involutive", p.inverse_index_involutive),
            ("factorial_sq_modeq_one", p.factorial_sq_modeq_one),
        ],
        lists: Vec::new(),
    }
}

/// The sub-packages `IntPrelude` carries, by field name.
#[must_use]
pub(super) fn int_sub(p: &IntPrelude) -> Vec<(&'static str, Sub)> {
    vec![
        ("logic", Sub::Logic(Box::new(p.logic))),
        ("nat", Sub::Nat(Box::new(p.nat))),
    ]
}

/// The `RatPrelude` field table (197 names,
/// 0 name lists, 1 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn rat(p: &RatPrelude) -> Fields {
    Fields {
        names: vec![
            ("zero", p.zero),
            ("one", p.one),
            ("le", p.le),
            ("lt", p.lt),
            ("mul_inv_cancel", p.mul_inv_cancel),
            ("mul_inv_cancel_of_neg", p.mul_inv_cancel_of_neg),
            ("mul_pos", p.mul_pos),
            ("nat_div_succ_pos", p.nat_div_succ_pos),
            ("sub_mul", p.sub_mul),
            ("mul_inv_sub_one", p.mul_inv_sub_one),
            ("inv_sub_inv", p.inv_sub_inv),
            ("inv_le_of_pos_le", p.inv_le_of_pos_le),
            ("inv_nat_div_succ", p.inv_nat_div_succ),
            ("inv_pos", p.inv_pos),
            ("inv", p.inv),
            ("sub", p.sub),
            ("div", p.div),
            ("gcd_one_right", p.gcd_one_right),
            ("nat_gauss", p.nat_gauss),
            ("nat_dvd_antisymm_pos", p.nat_dvd_antisymm_pos),
            ("nat_mul_right_cancel", p.nat_mul_right_cancel),
            ("nat_div_cross", p.nat_div_cross),
            ("nat_abs_mul_of_nat", p.nat_abs_mul_of_nat),
            ("of_nat_inj", p.of_nat_inj),
            ("not_zero_le_neg_of_nat", p.not_zero_le_neg_of_nat),
            ("int_mul_right_cancel", p.int_mul_right_cancel),
            ("int_le_of_mul_le_mul_right", p.int_le_of_mul_le_mul_right),
            ("int_lt_of_mul_lt_mul_right", p.int_lt_of_mul_lt_mul_right),
            ("int_mul_le_mul_right", p.int_mul_le_mul_right),
            ("int_mul_lt_mul_right", p.int_mul_lt_mul_right),
            ("int_right_distrib", p.int_right_distrib),
            ("int_zero_mul", p.int_zero_mul),
            ("eq_zero_of_num_zero", p.eq_zero_of_num_zero),
            ("int_nonneg_of_nonneg", p.int_nonneg_of_nonneg),
            ("nonneg_of_int_nonneg", p.nonneg_of_int_nonneg),
            ("int_zero_le_of_nat", p.int_zero_le_of_nat),
            ("int_of_nat_pos", p.int_of_nat_pos),
            ("mk_congr", p.mk_congr),
            ("eta", p.eta),
            ("ext", p.ext),
            ("eq_of_cross", p.eq_of_cross),
            ("cross_of_eq", p.cross_of_eq),
            ("normalize_cross", p.normalize_cross),
            ("normalize_congr", p.normalize_congr),
            ("self_normalize", p.self_normalize),
            ("normalize_add_normalize", p.normalize_add_normalize),
            ("normalize_mul_normalize", p.normalize_mul_normalize),
            ("add_cross", p.add_cross),
            ("mul_cross", p.mul_cross),
            ("le_refl", p.le_refl),
            ("le_trans", p.le_trans),
            ("lt_irrefl", p.lt_irrefl),
            ("lt_trans", p.lt_trans),
            ("lt_of_lt_of_le", p.lt_of_lt_of_le),
            ("lt_of_le_of_lt", p.lt_of_le_of_lt),
            ("le_of_lt", p.le_of_lt),
            ("add_le_add", p.add_le_add),
            ("add_comm", p.add_comm),
            ("add_assoc", p.add_assoc),
            ("add_zero", p.add_zero),
            ("add_neg", p.add_neg),
            ("mul_le_mul_of_nonneg_left", p.mul_le_mul_of_nonneg_left),
            ("zero_lt_one", p.zero_lt_one),
            ("add_lt_add_of_le_of_lt", p.add_lt_add_of_le_of_lt),
            ("mul_comm", p.mul_comm),
            ("mul_assoc", p.mul_assoc),
            ("mul_one", p.mul_one),
            ("mul_zero", p.mul_zero),
            ("left_distrib", p.left_distrib),
            ("mul_nonneg", p.mul_nonneg),
            ("sq_nonneg", p.sq_nonneg),
            ("le_total", p.le_total),
            ("lt_of_not_le", p.lt_of_not_le),
            ("le_antisymm", p.le_antisymm),
            ("lt_trichotomy", p.lt_trichotomy),
            ("mul_eq_zero", p.mul_eq_zero),
            ("right_distrib", p.right_distrib),
            ("nat_div_succ", p.nat_div_succ),
            ("int_le_or_lt", p.int_le_or_lt),
            ("le_or_lt", p.le_or_lt),
            ("int_pos_of_pos", p.int_pos_of_pos),
            ("int_one_le_of_pos", p.int_one_le_of_pos),
            ("nat_div_succ_lt_of_pos", p.nat_div_succ_lt_of_pos),
            ("le_of_le_add_nat_div_succ", p.le_of_le_add_nat_div_succ),
            ("zero_add", p.zero_add),
            ("neg_add_cancel", p.neg_add_cancel),
            ("neg_eq_of_add_eq_zero", p.neg_eq_of_add_eq_zero),
            ("neg_neg", p.neg_neg),
            ("neg_zero", p.neg_zero),
            ("neg_add", p.neg_add),
            ("neg_le_neg", p.neg_le_neg),
            ("sub_self", p.sub_self),
            ("neg_sub", p.neg_sub),
            ("sub_neg_sub", p.sub_neg_sub),
            ("sub_add_add", p.sub_add_add),
            ("sub_add_sub", p.sub_add_sub),
            ("bounds_add", p.bounds_add),
            ("nat_div_succ_add", p.nat_div_succ_add),
            ("nat_div_succ_halve", p.nat_div_succ_halve),
            ("nat_div_succ_scale", p.nat_div_succ_scale),
            ("nat_div_succ_le_add_left", p.nat_div_succ_le_add_left),
            ("zero_le_nat_div_succ", p.zero_le_nat_div_succ),
            ("neg_nonpos_of_nonneg", p.neg_nonpos_of_nonneg),
            ("bounds_neg", p.bounds_neg),
            ("add_nonneg", p.add_nonneg),
            ("mul_neg", p.mul_neg),
            ("neg_mul", p.neg_mul),
            ("mul_le_mul_of_nonneg_right", p.mul_le_mul_of_nonneg_right),
            ("mul_sub_mul", p.mul_sub_mul),
            ("bounds_mul", p.bounds_mul),
            ("neg_mul_le_of_bounds", p.neg_mul_le_of_bounds),
            ("nat_div_succ_mul", p.nat_div_succ_mul),
            ("nat_index_compose", p.nat_index_compose),
            ("nat_index_symm", p.nat_index_symm),
            ("nat_div_succ_le_scaled", p.nat_div_succ_le_scaled),
            ("nat_div_succ_le_one", p.nat_div_succ_le_one),
            ("int_le_nat_abs", p.int_le_nat_abs),
            ("int_neg_nat_abs_le", p.int_neg_nat_abs_le),
            ("max", p.max),
            ("min", p.min),
            ("max_cases", p.max_cases),
            ("min_cases", p.min_cases),
            ("le_max_left", p.le_max_left),
            ("le_max_right", p.le_max_right),
            ("max_le", p.max_le),
            ("min_le_left", p.min_le_left),
            ("min_le_right", p.min_le_right),
            ("le_min", p.le_min),
            ("le_of_sub_le", p.le_of_sub_le),
            ("sub_le_of_le", p.sub_le_of_le),
            ("sub_max_le", p.sub_max_le),
            ("sub_min_le", p.sub_min_le),
            ("zero_le_max_neg", p.zero_le_max_neg),
            ("bounds_num", p.bounds_num),
            ("abs", p.abs),
            ("abs_nonneg", p.abs_nonneg),
            ("le_abs_self", p.le_abs_self),
            ("neg_le_abs", p.neg_le_abs),
            ("abs_zero", p.abs_zero),
            ("abs_neg", p.abs_neg),
            ("abs_add", p.abs_add),
            ("abs_mul", p.abs_mul),
            ("abs_le_of_le_of_neg_le", p.abs_le_of_le_of_neg_le),
            ("le_of_abs_le", p.le_of_abs_le),
            ("neg_le_of_abs_le", p.neg_le_of_abs_le),
            ("abs_sub_comm", p.abs_sub_comm),
            ("ble", p.ble),
            ("ble_eq_true_of_le", p.ble_eq_true_of_le),
            ("le_of_ble_eq_true", p.le_of_ble_eq_true),
            ("ble_refl", p.ble_refl),
            ("ble_trans", p.ble_trans),
            ("ble_total", p.ble_total),
            ("decidable_le", p.decidable_le),
            ("sum_range", p.sum_range),
            ("sum_range_zero", p.sum_range_zero),
            ("sum_range_succ", p.sum_range_succ),
            ("sum_range_congr", p.sum_range_congr),
            ("sum_range_add", p.sum_range_add),
            ("mul_sum_range", p.mul_sum_range),
            ("sum_range_le", p.sum_range_le),
            ("sum_range_nonneg", p.sum_range_nonneg),
            ("sum_range_congr_lt", p.sum_range_congr_lt),
            ("sum_range_eq_zero_of_lt", p.sum_range_eq_zero_of_lt),
            ("is_distribution", p.is_distribution),
            ("prob_le_one", p.prob_le_one),
            ("prob_complement", p.prob_complement),
            ("expectation", p.expectation),
            ("expectation_add", p.expectation_add),
            ("expectation_smul", p.expectation_smul),
            ("expectation_const", p.expectation_const),
            ("uniform", p.uniform),
            ("uniform_is_distribution", p.uniform_is_distribution),
            ("expectation_nonneg", p.expectation_nonneg),
            ("expectation_le", p.expectation_le),
            ("markov_inequality", p.markov_inequality),
            (
                "expectation_indicator_le_one",
                p.expectation_indicator_le_one,
            ),
            ("variance", p.variance),
            ("variance_nonneg", p.variance_nonneg),
            ("variance_eq", p.variance_eq),
            ("variance_smul", p.variance_smul),
            ("covariance", p.covariance),
            ("covariance_comm", p.covariance_comm),
            ("variance_add_eq", p.variance_add_eq),
            (
                "variance_add_of_uncorrelated",
                p.variance_add_of_uncorrelated,
            ),
            ("indicator", p.indicator),
            ("indicator_nonneg", p.indicator_nonneg),
            ("indicator_le", p.indicator_le),
            ("markov_constructed", p.markov_constructed),
            ("chebyshev_inequality", p.chebyshev_inequality),
            ("covariance_add_right", p.covariance_add_right),
            ("sum_vars", p.sum_vars),
            ("expectation_sum_vars", p.expectation_sum_vars),
            ("covariance_sum_vars_left", p.covariance_sum_vars_left),
            ("pairwise_uncorrelated", p.pairwise_uncorrelated),
            ("variance_sum_vars", p.variance_sum_vars),
            ("variance_scaled_mean", p.variance_scaled_mean),
            (
                "chebyshev_sample_mean_uncorrelated",
                p.chebyshev_sample_mean_uncorrelated,
            ),
        ],
        lists: Vec::new(),
    }
}

/// The sub-packages `RatPrelude` carries, by field name.
#[must_use]
pub(super) fn rat_sub(p: &RatPrelude) -> Vec<(&'static str, Sub)> {
    vec![("int", Sub::Int(Box::new(p.int)))]
}

/// The `ArithPrelude` field table (30 names,
/// 0 name lists, 1 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn arith(p: &ArithPrelude) -> Fields {
    Fields {
        names: vec![
            ("r", p.r),
            ("add", p.add),
            ("mul", p.mul),
            ("neg", p.neg),
            ("zero", p.zero),
            ("one", p.one),
            ("le", p.le),
            ("lt", p.lt),
            ("le_refl", p.le_refl),
            ("le_trans", p.le_trans),
            ("lt_irrefl", p.lt_irrefl),
            ("lt_trans", p.lt_trans),
            ("lt_of_lt_of_le", p.lt_of_lt_of_le),
            ("lt_of_le_of_lt", p.lt_of_le_of_lt),
            ("le_of_lt", p.le_of_lt),
            ("add_le_add", p.add_le_add),
            ("add_comm", p.add_comm),
            ("add_assoc", p.add_assoc),
            ("add_zero", p.add_zero),
            ("add_neg", p.add_neg),
            ("mul_le_mul_of_nonneg_left", p.mul_le_mul_of_nonneg_left),
            ("zero_lt_one", p.zero_lt_one),
            ("add_lt_add_of_le_of_lt", p.add_lt_add_of_le_of_lt),
            ("mul_comm", p.mul_comm),
            ("mul_assoc", p.mul_assoc),
            ("mul_one", p.mul_one),
            ("mul_zero", p.mul_zero),
            ("left_distrib", p.left_distrib),
            ("mul_nonneg", p.mul_nonneg),
            ("sq_nonneg", p.sq_nonneg),
        ],
        lists: Vec::new(),
    }
}

/// The sub-packages `ArithPrelude` carries, by field name.
#[must_use]
pub(super) fn arith_sub(p: &ArithPrelude) -> Vec<(&'static str, Sub)> {
    vec![("logic", Sub::Logic(Box::new(p.logic)))]
}

/// The `CRealPrelude` field table (179 names,
/// 0 name lists, 1 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn creal(p: &CRealPrelude) -> Fields {
    Fields {
        names: vec![
            ("within", p.within),
            ("regular_pred", p.regular_pred),
            ("creal", p.creal),
            ("mk", p.mk),
            ("rec", p.rec),
            ("seq", p.seq),
            ("regular", p.regular),
            ("equiv", p.equiv),
            ("equiv_refl", p.equiv_refl),
            ("equiv_symm", p.equiv_symm),
            ("equiv_trans", p.equiv_trans),
            ("of_rat", p.of_rat),
            ("not_zero_one", p.not_zero_one),
            ("zero", p.zero),
            ("one", p.one),
            ("equiv_of_pointwise", p.equiv_of_pointwise),
            ("neg", p.neg),
            ("neg_congr", p.neg_congr),
            ("neg_le_neg", p.neg_le_neg),
            ("add", p.add),
            ("add_congr", p.add_congr),
            ("add_comm", p.add_comm),
            ("add_neg", p.add_neg),
            ("add_zero", p.add_zero),
            ("le", p.le),
            ("le_refl", p.le_refl),
            ("le_trans", p.le_trans),
            ("add_le_add", p.add_le_add),
            ("le_of_equiv", p.le_of_equiv),
            ("equiv_of_le_le", p.equiv_of_le_le),
            ("not_le_one_zero", p.not_le_one_zero),
            ("add_assoc", p.add_assoc),
            ("of_rat_add", p.of_rat_add),
            ("of_rat_neg", p.of_rat_neg),
            ("of_rat_sub", p.of_rat_sub),
            ("le_add_of_nonneg", p.le_add_of_nonneg),
            ("lt", p.lt),
            ("lt_irrefl", p.lt_irrefl),
            ("lt_trans", p.lt_trans),
            ("lt_of_lt_of_le", p.lt_of_lt_of_le),
            ("lt_of_le_of_lt", p.lt_of_le_of_lt),
            ("le_of_lt", p.le_of_lt),
            ("zero_lt_one", p.zero_lt_one),
            ("add_lt_add_of_le_of_lt", p.add_lt_add_of_le_of_lt),
            ("le_congr", p.le_congr),
            ("lt_congr", p.lt_congr),
            ("bound", p.bound),
            ("bound_within", p.bound_within),
            ("mul_shift", p.mul_shift),
            ("mul", p.mul),
            ("equiv_of_bounded", p.equiv_of_bounded),
            ("mul_congr", p.mul_congr),
            ("of_rat_mul", p.of_rat_mul),
            ("mul_comm", p.mul_comm),
            ("mul_one", p.mul_one),
            ("mul_zero", p.mul_zero),
            ("mul_assoc", p.mul_assoc),
            ("mul_le_mul_of_nonneg_left", p.mul_le_mul_of_nonneg_left),
            ("left_distrib", p.left_distrib),
            ("mul_nonneg", p.mul_nonneg),
            ("sq_nonneg", p.sq_nonneg),
            ("neg_mul_neg", p.neg_mul_neg),
            ("not_equiv_mul_one_one_zero", p.not_equiv_mul_one_one_zero),
            ("apart", p.apart),
            ("apart_symm", p.apart_symm),
            ("apart_irrefl", p.apart_irrefl),
            ("apart_congr", p.apart_congr),
            ("not_equiv_of_apart", p.not_equiv_of_apart),
            ("apart_zero_one", p.apart_zero_one),
            ("no_total_inverse", p.no_total_inverse),
            ("of_rat_le", p.of_rat_le),
            ("pos_bound", p.pos_bound),
            ("pos_of_pos_bound", p.pos_of_pos_bound),
            ("pos_bound_of_lt", p.pos_bound_of_lt),
            ("of_rat_pos", p.of_rat_pos),
            ("mul_pos", p.mul_pos),
            ("inv_shift", p.inv_shift),
            ("inv", p.inv),
            ("mul_inv_cancel", p.mul_inv_cancel),
            ("inv_congr", p.inv_congr),
            ("inv_index_irrelevant", p.inv_index_irrelevant),
            ("max", p.max),
            ("min", p.min),
            ("abs", p.abs),
            ("le_max_left", p.le_max_left),
            ("le_max_right", p.le_max_right),
            ("max_le", p.max_le),
            ("min_le_left", p.min_le_left),
            ("min_le_right", p.min_le_right),
            ("le_min", p.le_min),
            ("max_congr", p.max_congr),
            ("min_congr", p.min_congr),
            ("abs_congr", p.abs_congr),
            ("le_abs_self", p.le_abs_self),
            ("neg_le_abs", p.neg_le_abs),
            ("abs_le", p.abs_le),
            ("abs_nonneg", p.abs_nonneg),
            ("not_le_zero_neg_one", p.not_le_zero_neg_one),
            ("not_equiv_abs_neg_one", p.not_equiv_abs_neg_one),
            ("of_nat", p.of_nat),
            ("archimedean", p.archimedean),
            ("rat_approx_upper", p.rat_approx_upper),
            ("rat_approx_lower", p.rat_approx_lower),
            ("density", p.density),
            ("lt_cotrans", p.lt_cotrans),
            ("apart_cotrans", p.apart_cotrans),
            ("regular_seq", p.regular_seq),
            ("limit_seq", p.limit_seq),
            ("limit_seq_regular", p.limit_seq_regular),
            ("limit", p.limit),
            ("limit_dist", p.limit_dist),
            ("converges", p.converges),
            ("converges_unique", p.converges_unique),
            ("converges_of_const", p.converges_of_const),
            ("cauchy", p.cauchy),
            ("converges_cauchy", p.converges_cauchy),
            ("converges_add", p.converges_add),
            ("converges_neg", p.converges_neg),
            ("converges_sub", p.converges_sub),
            ("bounded", p.bounded),
            ("converges_bounded", p.converges_bounded),
            ("converges_mul", p.converges_mul),
            ("continuous_at", p.continuous_at),
            ("continuous_id", p.continuous_id),
            ("continuous_const", p.continuous_const),
            ("continuous_add", p.continuous_add),
            ("continuous_mul", p.continuous_mul),
            ("continuous_comp", p.continuous_comp),
            ("uniformly_continuous_on", p.uniformly_continuous_on),
            ("uc_mk", p.uc_mk),
            ("uc_rec", p.uc_rec),
            ("uc_modulus", p.uc_modulus),
            ("uc_spec", p.uc_spec),
            ("uniformly_continuous_id", p.uniformly_continuous_id),
            ("uniformly_continuous_const", p.uniformly_continuous_const),
            ("rat_sq_le", p.rat_sq_le),
            ("rat_sq_sandwich", p.rat_sq_sandwich),
            ("rat_index_ratio_le_one", p.rat_index_ratio_le_one),
            ("rat_unit_eq_one", p.rat_unit_eq_one),
            ("eq_zero_of_mul_self_zero", p.eq_zero_of_mul_self_zero),
            (
                "eq_zero_of_add_eq_zero_of_nonneg",
                p.eq_zero_of_add_eq_zero_of_nonneg,
            ),
            ("nat_sqrt", p.nat_sqrt),
            ("nat_sqrt_spec", p.nat_sqrt_spec),
            ("nat_sqrt_le", p.nat_sqrt_le),
            ("nat_sqrt_lt", p.nat_sqrt_lt),
            ("sqrt_approx", p.sqrt_approx),
            ("k_regular_pred", p.k_regular_pred),
            ("speedup", p.speedup),
            ("regular_of_kregular", p.regular_of_kregular),
            ("speedup_close", p.speedup_close),
            ("sum_range", p.sum_range),
            ("sum_range_zero", p.sum_range_zero),
            ("sum_range_succ", p.sum_range_succ),
            ("sum_range_congr", p.sum_range_congr),
            ("sum_range_add", p.sum_range_add),
            ("mul_sum_range", p.mul_sum_range),
            ("sum_range_le", p.sum_range_le),
            ("abs_sum_range_le", p.abs_sum_range_le),
            ("sum_range_telescope", p.sum_range_telescope),
            ("sum_range_split", p.sum_range_split),
            ("sum_range_tail_le", p.sum_range_tail_le),
            ("pow", p.pow),
            ("pow_zero", p.pow_zero),
            ("pow_succ", p.pow_succ),
            ("pow_add", p.pow_add),
            ("pow_congr", p.pow_congr),
            ("pow_nonneg", p.pow_nonneg),
            ("pow_le_one", p.pow_le_one),
            ("mul_sub_one_geom", p.mul_sub_one_geom),
            ("geom_sum_bounded", p.geom_sum_bounded),
            ("pow_le_pow_of_le_one", p.pow_le_pow_of_le_one),
            ("mul_sub_one_geom_tail", p.mul_sub_one_geom_tail),
            ("geom_tail_bounded", p.geom_tail_bounded),
            ("one_le_pow_of_one_le", p.one_le_pow_of_one_le),
            ("pow_le_pow_of_one_le", p.pow_le_pow_of_one_le),
            ("pow_pos", p.pow_pos),
            ("pow_succ_lt_one", p.pow_succ_lt_one),
            ("pow_succ_gt_one", p.pow_succ_gt_one),
            (
                "not_apart_one_of_pow_succ_eq_one",
                p.not_apart_one_of_pow_succ_eq_one,
            ),
        ],
        lists: Vec::new(),
    }
}

/// The sub-packages `CRealPrelude` carries, by field name.
#[must_use]
pub(super) fn creal_sub(p: &CRealPrelude) -> Vec<(&'static str, Sub)> {
    vec![("rat", Sub::Rat(Box::new(p.rat)))]
}

/// The `ComplexPrelude` field table (102 names,
/// 0 name lists, 1 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn complex(p: &ComplexPrelude) -> Fields {
    Fields {
        names: vec![
            ("complex", p.complex),
            ("mk", p.mk),
            ("rec", p.rec),
            ("re", p.re),
            ("im", p.im),
            ("re_congr", p.re_congr),
            ("im_congr", p.im_congr),
            ("equiv", p.equiv),
            ("equiv_refl", p.equiv_refl),
            ("equiv_symm", p.equiv_symm),
            ("equiv_trans", p.equiv_trans),
            ("of_real", p.of_real),
            ("i", p.i),
            ("zero", p.zero),
            ("one", p.one),
            ("add", p.add),
            ("neg", p.neg),
            ("mul", p.mul),
            ("add_congr", p.add_congr),
            ("neg_congr", p.neg_congr),
            ("mul_congr", p.mul_congr),
            ("conj_congr", p.conj_congr),
            ("add_comm", p.add_comm),
            ("add_assoc", p.add_assoc),
            ("add_zero", p.add_zero),
            ("add_neg", p.add_neg),
            ("mul_comm", p.mul_comm),
            ("mul_assoc", p.mul_assoc),
            ("mul_one", p.mul_one),
            ("mul_zero", p.mul_zero),
            ("left_distrib", p.left_distrib),
            ("of_real_add", p.of_real_add),
            ("of_real_mul", p.of_real_mul),
            ("i_sq", p.i_sq),
            ("not_zero_one", p.not_zero_one),
            ("not_zero_i", p.not_zero_i),
            ("re_add_im", p.re_add_im),
            ("conj", p.conj),
            ("conj_conj", p.conj_conj),
            ("conj_add", p.conj_add),
            ("conj_mul", p.conj_mul),
            ("conj_sub", p.conj_sub),
            ("conj_of_real", p.conj_of_real),
            ("conj_i", p.conj_i),
            ("eq_conj_iff_real", p.eq_conj_iff_real),
            ("norm_sq", p.norm_sq),
            ("mul_conj", p.mul_conj),
            ("norm_sq_nonneg", p.norm_sq_nonneg),
            ("norm_sq_conj", p.norm_sq_conj),
            ("norm_sq_mul", p.norm_sq_mul),
            ("norm_sq_pow", p.norm_sq_pow),
            ("norm_sq_eq_zero_of_eq_zero", p.norm_sq_eq_zero_of_eq_zero),
            ("eq_zero_of_norm_sq_eq_zero", p.eq_zero_of_norm_sq_eq_zero),
            ("norm_sq_eq_zero_iff", p.norm_sq_eq_zero_iff),
            ("norm_sq_add", p.norm_sq_add),
            ("norm_sq_add_le", p.norm_sq_add_le),
            ("no_compatible_order", p.no_compatible_order),
            ("inv", p.inv),
            ("mul_inv_cancel", p.mul_inv_cancel),
            ("inv_congr", p.inv_congr),
            ("div", p.div),
            ("div_self", p.div_self),
            ("apart", p.apart),
            ("apart_irrefl", p.apart_irrefl),
            ("apart_symm", p.apart_symm),
            ("apart_of_normsq_pos", p.apart_of_normsq_pos),
            ("mul_apart_zero", p.mul_apart_zero),
            (
                "mul_eq_zero_not_both_apart_zero",
                p.mul_eq_zero_not_both_apart_zero,
            ),
            ("inv_mul_cancel", p.inv_mul_cancel),
            ("pos_bound_conj", p.pos_bound_conj),
            ("conj_inv", p.conj_inv),
            ("pow", p.pow),
            ("pow_zero", p.pow_zero),
            ("pow_succ", p.pow_succ),
            ("pow_add", p.pow_add),
            ("sum_range", p.sum_range),
            ("sum_range_zero", p.sum_range_zero),
            ("sum_range_succ", p.sum_range_succ),
            ("sum_range_congr", p.sum_range_congr),
            ("mul_sum_range", p.mul_sum_range),
            ("sum_range_mul", p.sum_range_mul),
            ("sum_range_mul_double", p.sum_range_mul_double),
            ("mul_sub_one_geom", p.mul_sub_one_geom),
            ("geom_series_div", p.geom_series_div),
            ("of_nat", p.of_nat),
            ("of_nat_zero", p.of_nat_zero),
            ("of_nat_succ", p.of_nat_succ),
            ("of_nat_add", p.of_nat_add),
            ("of_nat_mul", p.of_nat_mul),
            ("sum_range_add", p.sum_range_add),
            ("sum_range_shift_front", p.sum_range_shift_front),
            ("sum_range_congr_lt", p.sum_range_congr_lt),
            ("sum_range_split", p.sum_range_split),
            ("sum_range_swap", p.sum_range_swap),
            ("add_pow", p.add_pow),
            ("is_root_of_unity", p.is_root_of_unity),
            ("one_is_root_of_unity", p.one_is_root_of_unity),
            ("i_is_fourth_root", p.i_is_fourth_root),
            ("pow_mul", p.pow_mul),
            (
                "geom_sum_eq_zero_of_root_of_unity",
                p.geom_sum_eq_zero_of_root_of_unity,
            ),
            ("root_of_unity_mul", p.root_of_unity_mul),
            ("root_of_unity_pow", p.root_of_unity_pow),
        ],
        lists: Vec::new(),
    }
}

/// The sub-packages `ComplexPrelude` carries, by field name.
#[must_use]
pub(super) fn complex_sub(p: &ComplexPrelude) -> Vec<(&'static str, Sub)> {
    vec![("creal", Sub::CReal(Box::new(p.creal)))]
}

/// The `CPointPrelude` field table (106 names,
/// 0 name lists, 1 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn cpoint(p: &CPointPrelude) -> Fields {
    Fields {
        names: vec![
            ("point", p.point),
            ("mk", p.mk),
            ("rec", p.rec),
            ("x", p.x),
            ("y", p.y),
            ("point_equiv", p.point_equiv),
            ("two", p.two),
            ("two_pos_bound", p.two_pos_bound),
            ("inv2", p.inv2),
            ("one_sub_inv2", p.one_sub_inv2),
            ("midpoint", p.midpoint),
            ("midpoint_comm", p.midpoint_comm),
            ("midpoint_self", p.midpoint_self),
            ("sum_perm", p.sum_perm),
            ("midpoint_diag_core", p.midpoint_diag_core),
            ("point_midpoint", p.point_midpoint),
            ("varignon_diagonals_bisect", p.varignon_diagonals_bisect),
            ("add_right_cancel", p.add_right_cancel),
            ("sum_of_midpoints_perm", p.sum_of_midpoints_perm),
            ("midpoint_vector_swap", p.midpoint_vector_swap),
            ("point_sub", p.point_sub),
            ("varignon_vector_parallel", p.varignon_vector_parallel),
            ("point_add", p.point_add),
            ("point_neg", p.point_neg),
            ("dot", p.dot),
            ("dot_congr", p.dot_congr),
            ("dot_comm", p.dot_comm),
            ("dot_add_left", p.dot_add_left),
            ("dot_add_right", p.dot_add_right),
            ("dot_sub_left", p.dot_sub_left),
            ("dot_sub_right", p.dot_sub_right),
            ("dot_neg_left", p.dot_neg_left),
            ("pythagoras", p.pythagoras),
            ("thales", p.thales),
            ("orthocentre_identity", p.orthocentre_identity),
            ("orthocentre_third_altitude", p.orthocentre_third_altitude),
            ("dist_sq", p.dist_sq),
            ("dist_sq_congr", p.dist_sq_congr),
            ("dist_sq_comm", p.dist_sq_comm),
            ("dist_sq_self_zero", p.dist_sq_self_zero),
            ("pythagoras_dist_sq", p.pythagoras_dist_sq),
            (
                "parallelogram_diagonals_bisect",
                p.parallelogram_diagonals_bisect,
            ),
            (
                "parallelogram_opposite_sides_eq",
                p.parallelogram_opposite_sides_eq,
            ),
            ("dot_self_add", p.dot_self_add),
            ("dot_self_sub", p.dot_self_sub),
            ("dot_self_add3", p.dot_self_add3),
            ("parallelogram_law", p.parallelogram_law),
            ("euler_quadrilateral", p.euler_quadrilateral),
            ("apollonius_median", p.apollonius_median),
            ("three", p.three),
            ("three_pos_bound", p.three_pos_bound),
            ("inv3", p.inv3),
            ("centroid_scalar", p.centroid_scalar),
            ("centroid_scalar_self", p.centroid_scalar_self),
            ("centroid", p.centroid),
            ("centroid_median", p.centroid_median),
            ("centroid_ratio", p.centroid_ratio),
            ("centroid_dist_sq", p.centroid_dist_sq),
            ("lerp_scalar", p.lerp_scalar),
            ("point_lerp", p.point_lerp),
            ("lerp_zero", p.lerp_zero),
            ("lerp_one", p.lerp_one),
            ("lerp_half_is_midpoint", p.lerp_half_is_midpoint),
            ("lerp_dist_sq", p.lerp_dist_sq),
            ("stewart", p.stewart),
            ("stewart_median", p.stewart_median),
            ("circumcentre_identity", p.circumcentre_identity),
            ("circumcentre_third_distance", p.circumcentre_third_distance),
            (
                "circumcentre_orthocentre_construction",
                p.circumcentre_orthocentre_construction,
            ),
            ("euler_line", p.euler_line),
            ("midpoint_dist_sq_quarter", p.midpoint_dist_sq_quarter),
            ("apollonius_from_stewart", p.apollonius_from_stewart),
            ("dot_self_nonneg", p.dot_self_nonneg),
            ("lagrange_identity", p.lagrange_identity),
            ("cauchy_schwarz", p.cauchy_schwarz),
            ("dist_sq_double_sum_bound", p.dist_sq_double_sum_bound),
            ("dot_self_zero_of_eq_zero", p.dot_self_zero_of_eq_zero),
            ("eq_zero_of_dot_self_zero", p.eq_zero_of_dot_self_zero),
            ("dot_self_zero_iff", p.dot_self_zero_iff),
            ("dist_sq_eq_zero_of_equiv", p.dist_sq_eq_zero_of_equiv),
            ("eq_zero_of_dist_sq_eq_zero", p.eq_zero_of_dist_sq_eq_zero),
            ("dist_sq_eq_zero_iff", p.dist_sq_eq_zero_iff),
            ("on_perp_bisector", p.on_perp_bisector),
            ("perp_bisector_midpoint", p.perp_bisector_midpoint),
            ("perp_bisector_iff_dot", p.perp_bisector_iff_dot),
            ("on_circle", p.on_circle),
            (
                "circumcentre_on_perp_bisectors",
                p.circumcentre_on_perp_bisectors,
            ),
            ("thales_converse", p.thales_converse),
            ("cross", p.cross),
            ("cross_self_left", p.cross_self_left),
            ("cross_self_right", p.cross_self_right),
            ("cross_swap_bc", p.cross_swap_bc),
            ("non_collinear", p.non_collinear),
            (
                "circumcentre_difference_dots",
                p.circumcentre_difference_dots,
            ),
            (
                "cross_annihilates_difference",
                p.cross_annihilates_difference,
            ),
            ("circumcentre_unique", p.circumcentre_unique),
            ("power", p.power),
            ("power_zero_iff_on_circle", p.power_zero_iff_on_circle),
            ("power_of_centre", p.power_of_centre),
            ("radical_axis_iff_dot", p.radical_axis_iff_dot),
            ("power_difference_linear", p.power_difference_linear),
            (
                "two_circles_meet_on_radical_axis",
                p.two_circles_meet_on_radical_axis,
            ),
            (
                "nine_point_centre_on_euler_line",
                p.nine_point_centre_on_euler_line,
            ),
            ("nine_point_radius_bc", p.nine_point_radius_bc),
            ("nine_point_radius_ab", p.nine_point_radius_ab),
            (
                "nine_point_centre_equidistant",
                p.nine_point_centre_equidistant,
            ),
        ],
        lists: Vec::new(),
    }
}

/// The sub-packages `CPointPrelude` carries, by field name.
#[must_use]
pub(super) fn cpoint_sub(p: &CPointPrelude) -> Vec<(&'static str, Sub)> {
    vec![("creal", Sub::CReal(Box::new(p.creal)))]
}

/// The `StringPrelude` field table (93 names,
/// 1 name lists, 1 sub-packages).
#[must_use]
#[allow(clippy::too_many_lines)] // a generated field table; length is the point.
pub(super) fn string(p: &StringPrelude) -> Fields {
    Fields {
        names: vec![
            ("char_ind", p.char_ind),
            ("char_rec", p.char_rec),
            ("char_beq", p.char_beq),
            ("char_beq_refl", p.char_beq_refl),
            ("char_eq_of_beq_eq_true", p.char_eq_of_beq_eq_true),
            ("char_beq_eq_true_of_eq", p.char_beq_eq_true_of_eq),
            ("char_decidable_eq", p.char_decidable_eq),
            ("str_ind", p.str_ind),
            ("str_nil", p.str_nil),
            ("str_cons", p.str_cons),
            ("str_rec", p.str_rec),
            ("str_beq", p.str_beq),
            ("str_beq_refl", p.str_beq_refl),
            ("str_eq_of_beq_eq_true", p.str_eq_of_beq_eq_true),
            ("str_beq_eq_true_of_eq", p.str_beq_eq_true_of_eq),
            ("str_decidable_eq", p.str_decidable_eq),
            ("append", p.append),
            ("nil_append", p.nil_append),
            ("cons_append", p.cons_append),
            ("append_nil", p.append_nil),
            ("append_assoc", p.append_assoc),
            ("length", p.length),
            ("length_nil", p.length_nil),
            ("length_cons", p.length_cons),
            ("foldr", p.foldr),
            ("foldr_uparam", p.foldr_uparam),
            ("foldr_nil", p.foldr_nil),
            ("foldr_cons", p.foldr_cons),
            ("length_eq_foldr", p.length_eq_foldr),
            ("append_eq_foldr", p.append_eq_foldr),
            ("reverse", p.reverse),
            ("reverse_nil", p.reverse_nil),
            ("reverse_append", p.reverse_append),
            ("reverse_reverse", p.reverse_reverse),
            ("map", p.map),
            ("map_nil", p.map_nil),
            ("map_cons", p.map_cons),
            ("map_append", p.map_append),
            ("map_reverse", p.map_reverse),
            ("map_id", p.map_id),
            ("map_map", p.map_map),
            ("length_map", p.length_map),
            ("append_left_cancel", p.append_left_cancel),
            ("take", p.take),
            ("drop", p.drop),
            ("take_zero", p.take_zero),
            ("take_succ_nil", p.take_succ_nil),
            ("take_succ_cons", p.take_succ_cons),
            ("drop_zero", p.drop_zero),
            ("drop_succ_nil", p.drop_succ_nil),
            ("drop_succ_cons", p.drop_succ_cons),
            ("take_append_drop", p.take_append_drop),
            ("substr", p.substr),
            ("substr_zero_zero", p.substr_zero_zero),
            ("substr_zero_len", p.substr_zero_len),
            ("substr_nil", p.substr_nil),
            ("at", p.at),
            ("at_nil", p.at_nil),
            ("at_cons_zero", p.at_cons_zero),
            ("is_prefix", p.is_prefix),
            ("is_prefix_nil", p.is_prefix_nil),
            ("is_prefix_refl", p.is_prefix_refl),
            ("is_prefix_append", p.is_prefix_append),
            ("is_prefix_trans", p.is_prefix_trans),
            ("is_prefix_take", p.is_prefix_take),
            ("is_suffix", p.is_suffix),
            ("is_suffix_nil", p.is_suffix_nil),
            ("is_suffix_refl", p.is_suffix_refl),
            ("is_suffix_drop", p.is_suffix_drop),
            ("is_suffix_reverse_mp", p.is_suffix_reverse_mp),
            ("is_suffix_reverse_mpr", p.is_suffix_reverse_mpr),
            ("contains", p.contains),
            ("contains_nil", p.contains_nil),
            ("contains_refl", p.contains_refl),
            ("contains_of_is_prefix", p.contains_of_is_prefix),
            ("contains_of_is_suffix", p.contains_of_is_suffix),
            ("contains_substr", p.contains_substr),
            ("all_", p.all_),
            ("all_nil", p.all_nil),
            ("all_append", p.all_append),
            ("all_of_is_prefix", p.all_of_is_prefix),
            ("all_bool", p.all_bool),
            ("all_iff_all", p.all_iff_all),
            ("is_prefix_bool", p.is_prefix_bool),
            ("is_prefix_bool_nil", p.is_prefix_bool_nil),
            (
                "is_prefix_bool_eq_true_of_is_prefix",
                p.is_prefix_bool_eq_true_of_is_prefix,
            ),
            (
                "is_prefix_of_is_prefix_bool_eq_true",
                p.is_prefix_of_is_prefix_bool_eq_true,
            ),
            ("str_decidable_is_prefix", p.str_decidable_is_prefix),
            ("is_suffix_bool", p.is_suffix_bool),
            (
                "is_suffix_bool_eq_true_of_is_suffix",
                p.is_suffix_bool_eq_true_of_is_suffix,
            ),
            (
                "is_suffix_of_is_suffix_bool_eq_true",
                p.is_suffix_of_is_suffix_bool_eq_true,
            ),
            ("contains_bool", p.contains_bool),
            (
                "contains_of_contains_bool_eq_true",
                p.contains_of_contains_bool_eq_true,
            ),
        ],
        lists: vec![("char_ctors", p.char_ctors.clone())],
    }
}

/// The sub-packages `StringPrelude` carries, by field name.
#[must_use]
pub(super) fn string_sub(p: &StringPrelude) -> Vec<(&'static str, Sub)> {
    vec![("logic", Sub::Logic(Box::new(p.logic)))]
}

/// A sub-package carried inside another package.
pub(super) enum Sub {
    /// A nested [`LogicPrelude`].
    Logic(Box<LogicPrelude>),
    /// A nested [`NatPrelude`].
    Nat(Box<NatPrelude>),
    /// A nested [`IntPrelude`].
    Int(Box<IntPrelude>),
    /// A nested [`RatPrelude`].
    Rat(Box<RatPrelude>),
    /// A nested [`CRealPrelude`].
    CReal(Box<CRealPrelude>),
}
