#!/usr/bin/env bash
#
# Build the render strand's deliverables into render/out/.
#
# P1 (2026-08-21) made this a SITE rather than a set of pages: the atlas, the
# two pilots and all 324 fact cards are emitted together, and they link to each
# other. Two rules make those links resolve, and both are load-bearing:
#
#   * every facts document is named after its SOURCE FILE (`--name-by source`),
#     because Doc-IR carries a cross-reference as the relative path of the
#     referenced document's source and every emitter resolves it by swapping
#     the extension. Naming by `doc_id` (the default, and what P0 used with a
#     rename afterwards) would break every one of them.
#   * the cards land in `out/cards/`, which is where the atlas's hrefs say they
#     are and where a card's own sibling hrefs resolve.
#
# What checks it: `render/tests/link_integrity.rs` renders the whole site and
# fails if any relative link does not resolve to a file that was emitted, and
# `render/check.sh` runs it by name.
#
# render/out/ IS THE DELIVERABLE: the documents a reader is handed. Everything
# in it is generated by this script from committed manifests and committed run
# records; nothing in it is edited by hand, and re-running this script over an
# unchanged tree reproduces it byte for byte (the PDF included -- see
# SOURCE_DATE_EPOCH below).
#
# The CLI names its output after the document's `doc_id`. The deliverables are
# named after what they ARE, so this script renames -- and rewrites the LaTeX
# wrapper's \input line to match, because a wrapper pointing at a file that was
# renamed under it is exactly the kind of quiet breakage this strand exists to
# stop.
#
# Exit status depends on findings: any render, any diagnostic, or any pdflatex
# failure fails the script, and the outputs are written to a staging directory
# and only swapped in at the end, so a failed run cannot leave a half-built
# deliverable behind that looks finished.
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
cd "$root" || exit 2

out="$here/out"
stage="$(mktemp -d)"
work="$stage/work"
mkdir -p "$work" "$stage/out"
fail=0

cargo_flags="--manifest-path $here/Cargo.toml"
offline=""
cargo metadata $cargo_flags --offline --format-version 1 >/dev/null 2>&1 && offline="--offline"

render() { # manifest format
  if ! cargo run $cargo_flags $offline --all-features -q -- render \
       --manifest "$1" --repo-root . --format "$2" --out "$work" \
       --fail-on-diagnostics >/dev/null; then
    printf 'FAILED to render %s as %s\n' "$1" "$2"
    fail=$((fail + 1))
  fi
}

CERT=render/examples-input/cert/certificate.doc.json
FACTS=render/examples-input/facts

render "$CERT" md
render "$CERT" tex
render "$CERT" html

# The facts site. `--name-by source` so `facts-atlas.doc.json` emits
# `facts-atlas.html` -- which is both the deliverable's name and what every
# card's "up" link resolves to.
render_named() { # manifest format
  if ! cargo run $cargo_flags $offline --all-features -q -- render \
       --manifest "$1" --repo-root . --format "$2" --out "$work" \
       --name-by source --fail-on-diagnostics >/dev/null; then
    printf 'FAILED to render %s as %s\n' "$1" "$2"
    fail=$((fail + 1))
  fi
}
render_named "$FACTS/facts-atlas.doc.json" md
render_named "$FACTS/facts-atlas.doc.json" html
render_named "$FACTS/facts-pilot.doc.json" html
render_named "$FACTS/facts-pilot-arith.doc.json" html

# THE 324 CARDS, in one process. Batch is a loop over the same assembler with
# the same fail-closed rules -- see cmd_render_batch -- not a fast path that
# skips anything; a card that would be refused on its own is refused here.
mkdir -p "$work/cards"
card_start=$(date +%s.%N)
if ! cargo run $cargo_flags $offline --all-features -q -- render \
     --manifest-dir "$FACTS/cards" --repo-root . --format html \
     --out "$work/cards" --fail-on-diagnostics >/dev/null; then
  printf 'FAILED to render the fact cards\n'
  fail=$((fail + 1))
fi
card_end=$(date +%s.%N)
n_cards=$(find "$work/cards" -name '*.html' | wc -l)
printf 'cards: %s pages in %.1fs\n' "$n_cards" "$(echo "$card_end - $card_start" | bc)"

cp "$work/noh-p2-weight-certificate.md" "$stage/out/certificate.md"
cp "$work/noh-p2-weight-certificate.html" "$stage/out/certificate.html"
cp "$work/noh-p2-weight-certificate.tex" "$stage/out/certificate.tex"
cp "$work/axeyum.sty" "$stage/out/axeyum.sty"
sed 's/noh-p2-weight-certificate\.tex/certificate.tex/' \
  "$work/noh-p2-weight-certificate-standalone.tex" > "$stage/out/certificate-standalone.tex"
cp "$work/facts-atlas.md" "$stage/out/facts.md"
cp "$work/facts-atlas.html" "$stage/out/facts-atlas.html"
cp "$work/facts-pilot.html" "$stage/out/facts-pilot.html"
cp "$work/facts-pilot-arith.html" "$stage/out/facts-pilot-arith.html"
mkdir -p "$stage/out/cards"
cp "$work"/cards/*.html "$stage/out/cards/"

# The PDF. SOURCE_DATE_EPOCH + FORCE_SOURCE_DATE stop pdflatex stamping a wall
# clock into /CreationDate, which would make the deliverable differ on every
# build for no reason anyone can act on. The epoch is the document's own, read
# out of the manifest -- the same number every other output carries.
if command -v pdflatex >/dev/null 2>&1; then
  epoch="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["meta"]["epoch"]["unix"])' "$CERT")"
  if (cd "$stage/out" && SOURCE_DATE_EPOCH="$epoch" FORCE_SOURCE_DATE=1 \
        pdflatex -interaction=nonstopmode -halt-on-error certificate-standalone.tex \
        >"$stage/latex.log" 2>&1) && [ -s "$stage/out/certificate-standalone.pdf" ]; then
    mv "$stage/out/certificate-standalone.pdf" "$stage/out/certificate.pdf"
  else
    grep -E '^!' "$stage/latex.log" | head -10
    printf 'FAILED to compile certificate.pdf\n'
    fail=$((fail + 1))
  fi
  rm -f "$stage/out"/certificate-standalone.{aux,log,out,toc}
else
  printf 'NO pdflatex on this host: certificate.pdf was NOT built (this is not a pass)\n'
  fail=$((fail + 1))
fi

if [ "$fail" -ne 0 ]; then
  printf '\nbuild-outputs: %d failure(s); %s was NOT updated\n' "$fail" "$out"
  rm -rf "$stage"
  exit 1
fi

mkdir -p "$out" "$out/cards"
# Replace only the files this script produces; never `rm -rf` a constructed
# path. Cards are copied by name too, so a card whose fact left the ledger is
# left behind rather than deleted -- a stale page is visible, a deletion by a
# build script is not, and `link_integrity` is what would catch a missing one.
for f in "$stage/out"/*; do [ -f "$f" ] && cp "$f" "$out/$(basename "$f")"; done
cp "$stage/out"/cards/*.html "$out/cards/"
rm -rf "$stage"

printf '\nbuild-outputs: wrote %s\n' "$out"
ls -l "$out" | tail -n +2 | grep -v '^d' | awk '{printf "  %9d  %s\n", $5, $9}'
printf '  %9d  cards/ (%s pages)\n' \
  "$(du -sb "$out/cards" | cut -f1)" "$(find "$out/cards" -name '*.html' | wc -l)"
exit 0
