# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum._native import ir
import builtins
import typing
__all__ = [
    "Query",
    "QueryPlan",
    "StructuralCacheKey",
]

@typing.final
class Query:
    r"""
    A scoped query: assertions, assumptions and labels over one arena.
    """
    @property
    def assertions(self) -> builtins.list[tuple[ir.Term, builtins.int, typing.Optional[builtins.str]]]:
        r"""
        `(term, scope index, label)` for each assertion.
        """
    @property
    def assumptions(self) -> builtins.list[tuple[ir.Term, builtins.int, typing.Optional[builtins.str]]]:
        r"""
        `(term, scope index, label)` for each assumption.
        """
    def __new__(cls, arena: ir.Arena, assertions: typing.Sequence[tuple[builtins.int, ir.Term, typing.Optional[builtins.str]]], assumptions: typing.Sequence[tuple[builtins.int, ir.Term, typing.Optional[builtins.str]]] = [], scope_parents: typing.Sequence[tuple[builtins.int, typing.Optional[builtins.str]]] = []) -> Query:
        r"""
        Builds a query from `(scope, term, label)` triples in one Rust call.
        
        `scope` is a scope index (`0` is the root scope, and further scopes are
        created in order by `scope_parents`); `label` may be `None`.
        Assumptions use the same shape and are supplied separately.
        """
    def __len__(self) -> builtins.int:
        r"""
        Number of terms a backend would receive.
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Whether the query has no terms at all.
        """
    def structural_cache_key(self, arena: ir.Arena) -> StructuralCacheKey:
        r"""
        The structural identity of this query.
        """
    def plan_full(self, arena: ir.Arena) -> QueryPlan:
        r"""
        The unsliced plan (every term kept).
        """
    def slice_for_targets(self, arena: ir.Arena, targets: typing.Sequence[ir.Term]) -> QueryPlan:
        r"""
        A plan keeping only what the `targets` structurally depend on.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class QueryPlan:
    r"""
    A planned (possibly sliced) view of a query.
    """
    @property
    def planned_terms(self) -> builtins.list[tuple[builtins.str, builtins.int, ir.Term]]:
        r"""
        `(role, role index, term)` for each term the plan keeps.
        """
    @property
    def dropped_terms(self) -> builtins.list[tuple[builtins.str, builtins.int, ir.Term, builtins.str]]:
        r"""
        `(role, role index, term, reason)` for each term the plan dropped.
        """
    @property
    def solver_terms(self) -> builtins.list[ir.Term]:
        r"""
        The terms a backend would actually receive.
        """
    @property
    def original_cache_key(self) -> StructuralCacheKey:
        r"""
        The structural key of the whole original query.
        """
    @property
    def solver_cache_key(self) -> StructuralCacheKey:
        r"""
        The structural key of the sliced view handed to the backend.
        """
    @property
    def target_support(self) -> builtins.list[ir.Symbol]:
        r"""
        The symbols the slice targets.
        """
    def is_sliced(self) -> builtins.bool:
        r"""
        Whether the planner dropped anything. When this is `True`, a `sat`
        answer over the plan is only about the SLICE — call
        [`replay_original`](Self::replay_original) before accepting it.
        """
    def replay_original(self, arena: ir.Arena, assignment: ir.Assignment) -> typing.Optional[tuple[builtins.str, builtins.str, builtins.int, ir.Term]]:
        r"""
        Re-checks every DROPPED term against `assignment`.
        
        **Mandatory before accepting a `sat` from a sliced plan.** Returns
        `None` on success; otherwise a `(kind, role, term)` triple naming the
        first failure — `"unsatisfied"`, `"evaluation"` or `"non-boolean"`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class StructuralCacheKey:
    r"""
    The structural identity of a query.
    
    Deterministic and independent of arena-local `TermId` allocation and of
    labels, which is exactly what makes [`hex`](Self::hex) a safe cache key.
    """
    @property
    def digest(self) -> builtins.int:
        r"""
        The 64-bit structural digest.
        """
    @property
    def assertions(self) -> builtins.int:
        r"""
        Number of assertions covered.
        """
    @property
    def assumptions(self) -> builtins.int:
        r"""
        Number of assumptions covered.
        """
    @property
    def dag_nodes(self) -> builtins.int:
        r"""
        Distinct DAG nodes covered.
        """
    @property
    def tree_nodes(self) -> builtins.int:
        r"""
        Nodes the same formula would have with no sharing.
        """
    def hex(self) -> builtins.str:
        r"""
        The whole key as a hex string — a safe, portable cache key.
        """
    def __repr__(self) -> builtins.str: ...

