"""Composition library for L2 phase G5 -- graph selection as the ordinary
dispatcher (docs/plan/graph-directed-library-roadmap-2026-08-30.md, G5).

Three layers, composed in this order, never merged into one score:

  1. CURRICULUM chooses the DESTINATION.
     Source: docs/curriculum/curriculum.toml.
  2. The INFRASTRUCTURE FRONTIER chooses the CAPABILITY (ADR-0845).
     Source: artifacts/infrastructure-frontier/*.frontier.json -- READ ONLY,
     never edited or regenerated by this module.
  3. `scripts/check-dispatchable-frontier.py` chooses the specific LEGAL
     TARGET inside that cluster -- READ ONLY, invoked as a subprocess with
     `--json` and never edited, mutated, or reimplemented here.

ADR-0865 is the evidence bound on what this composition may claim. G4 ran
TWO pilots, not three (the third category -- a destination bridge toward
linear algebra, polynomials, or analysis -- had zero candidates in the only
joined population and was declared not-yet-evaluable, not manufactured).
Both run pilots moved their preregistered metric with zero added trust
surface, over exactly one population: `mathlib-group-defs-v1`, restricted to
the `language-infrastructure` and `proof-producers` queues (a bounded
substrate probe and a shared-producer probe). `docs/plan/global/
50-planning-rules.md` says graph rank is advisory until its authority is
complete. So `authority_level()` below returns `"authoritative"` ONLY for
that exact (population, queue) pair, and `"advisory"` for everything else --
a different population, `theorem-dominators`, `dependency-ready-leaves`, or
a legal target reached only by the unlinked fallback (see
`match_legal_target`). Promoting authority beyond that scope is the one
mistake this module exists to make structurally impossible.

"Legal" is the load-bearing word in the roadmap's own G5 sentence. The
legal-target layer NEVER proposes a held-out fact, a mutation negative
control, or a structurally blocked fact: `select_legal_target` and
`match_legal_target` are only ever handed the `dispatchable` list that
`check-dispatchable-frontier.py --json` already computed (135 held-out, 12
mutation controls, 11 blocked, 10 dispatchable as of 2026-08-30) -- the other
three buckets are read by `forbidden_fact_ids()` ONLY far enough to prove a
proposed override is not drawn from them.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

CURRICULUM_PATH = REPO_ROOT / "docs" / "curriculum" / "curriculum.toml"
FRONTIER_DIR = REPO_ROOT / "artifacts" / "infrastructure-frontier"
DISPATCHABLE_SCRIPT = REPO_ROOT / "scripts" / "check-dispatchable-frontier.py"
FACTS_DIR = REPO_ROOT / "artifacts" / "facts"

# The exact (population, queue) scope ADR-0865 measured. Nothing outside this
# pair may be labeled "authoritative" -- see the module docstring.
PILOTED_POPULATION = "mathlib-group-defs-v1"
PILOTED_QUEUES = frozenset({"language-infrastructure", "proof-producers"})

ADR_0865 = "docs/research/09-decisions/adr-0865-two-of-three-g4-pilots-retain-the-graph-ranking-one-category-untested.md"
ADR_0845 = "docs/research/09-decisions/adr-0845-the-infrastructure-frontier-curates-candidates-and-validates-them-live.md"
PLANNING_RULES = "docs/plan/global/50-planning-rules.md"

# Priority function tiers 2-5 from the roadmap
# (docs/plan/graph-directed-library-roadmap-2026-08-30.md): a missing
# definition/datatype/operation outranks a shared producer, which outranks a
# graph dominator, which outranks an individual dependency-ready fact. Queue
# names are the infrastructure frontier's own (ADR-0845).
QUEUE_TIER_ORDER = [
    "language-infrastructure",
    "proof-producers",
    "theorem-dominators",
    "dependency-ready-leaves",
]

MIN_EVIDENCE_NOTE_CHARS = 20


class DispatcherError(Exception):
    """A layer produced no answer, or an upstream artifact could not be read.

    Every raise site names which layer failed and why -- the "fail on
    absence, name the reason" requirement is structural, not a convention
    callers have to remember.
    """


# ---------------------------------------------------------------------------
# Layer 1: curriculum chooses the destination
# ---------------------------------------------------------------------------

def load_curriculum_nodes(path: Path = CURRICULUM_PATH) -> dict[str, dict[str, Any]]:
    """`{node_id: {"layer", "area", "status", "title", "path"}}`.

    `path` is DERIVED from `layer`/`area`/`id` (`docs/curriculum/curriculum.toml`'s
    own documented convention: `path = "<area-folder>/<id>.md"`, and the
    area-folder is `f"{layer:02d}-{area}"` -- verified against every node in
    the committed file, e.g. layer=2/area="structures" -> "02-structures").
    """
    if not path.is_file():
        raise DispatcherError(f"layer1:curriculum -- missing {path}")
    try:
        doc = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise DispatcherError(f"layer1:curriculum -- {path} unreadable: {exc}") from exc
    nodes: dict[str, dict[str, Any]] = {}
    for node in doc.get("node", []):
        node_id = node.get("id")
        layer = node.get("layer")
        area = node.get("area")
        if not node_id or layer is None or not area:
            continue
        folder = f"{layer:02d}-{area}"
        nodes[node_id] = {
            "node_id": node_id,
            "layer": layer,
            "area": area,
            "status": node.get("status"),
            "title": node.get("title"),
            "path": f"docs/curriculum/{folder}/{node_id}.md",
        }
    if not nodes:
        raise DispatcherError(f"layer1:curriculum -- {path} declares zero nodes")
    return nodes


# ---------------------------------------------------------------------------
# Layer 2: the infrastructure frontier chooses the capability
# ---------------------------------------------------------------------------

def load_frontier_documents(frontier_dir: Path = FRONTIER_DIR) -> dict[str, dict[str, Any]]:
    """`{population_id: frontier_dict}` for every `*.frontier.json` under
    `frontier_dir`. Never writes, never regenerates -- ADR-0845 owns that."""
    if not frontier_dir.is_dir():
        raise DispatcherError(
            f"layer2:infrastructure-frontier -- no directory at {frontier_dir}")
    docs: dict[str, dict[str, Any]] = {}
    for path in sorted(frontier_dir.glob("*.frontier.json")):
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise DispatcherError(
                f"layer2:infrastructure-frontier -- {path} unreadable: {exc}") from exc
        pop = doc.get("population_id")
        if not pop:
            raise DispatcherError(
                f"layer2:infrastructure-frontier -- {path} has no population_id")
        docs[pop] = doc
    if not docs:
        raise DispatcherError(
            f"layer2:infrastructure-frontier -- {frontier_dir} publishes zero "
            "frontier documents")
    return docs


def destination_candidates(
    nodes: dict[str, dict[str, Any]],
    frontier_docs: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    """Every curriculum node, annotated with how many published frontier rows
    (any population, any queue) name its doc path in `destination_paths`.

    Ranking a destination by curriculum status alone would be fabricating
    priority the data does not support: as of 2026-08-30 every curriculum
    node is `covered` or `lean-horizon` (no `planned` rows exist), and only
    ONE node (`groups`) is referenced by any published frontier row at all.
    So the real, checkable signal is "does a G3 population already say this
    destination has a capability queued" -- ordered by (-row_count, layer,
    node_id) for a deterministic, reproducible pick.
    """
    counts: dict[str, int] = {node_id: 0 for node_id in nodes}
    for doc in frontier_docs.values():
        for queue in doc.get("queues", {}).values():
            for row in queue.get("rows", []):
                for dpath in row.get("destination_paths") or []:
                    for node_id, node in nodes.items():
                        if node["path"] == dpath:
                            counts[node_id] += 1
    candidates = [
        {
            "node_id": node_id,
            "path": nodes[node_id]["path"],
            "layer": nodes[node_id]["layer"],
            "title": nodes[node_id]["title"],
            "row_count": counts[node_id],
        }
        for node_id in nodes
    ]
    candidates.sort(key=lambda c: (-c["row_count"], c["layer"], c["node_id"]))
    return candidates


def select_destination(
    nodes: dict[str, dict[str, Any]],
    frontier_docs: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """Pick the top-ranked destination with at least one supporting row.

    Raises `DispatcherError` (never returns a placeholder) if no curriculum
    destination is referenced by any published frontier row -- "the frontier
    could not be read" and "a layer produced no answer" are the SAME failure
    from the caller's point of view, and both must fail loudly.
    """
    candidates = destination_candidates(nodes, frontier_docs)
    servable = [c for c in candidates if c["row_count"] > 0]
    if not servable:
        raise DispatcherError(
            "layer1:curriculum -- no curriculum destination is referenced by "
            "any published infrastructure-frontier row; nothing for layer 2 "
            "to attach a capability to")
    top = servable[0]
    return {
        **top,
        "selection_reason": (
            f"{top['row_count']} published infrastructure-frontier row(s) "
            f"name {top['path']} in destination_paths; highest among "
            f"{len(servable)} servable destination(s)"
        ),
        "candidates_considered": servable[:10],
    }


def capability_candidates(
    destination: dict[str, Any],
    frontier_docs: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    """Every row (any population) whose `destination_paths` names this
    destination, ordered by the roadmap's own priority tiers
    (`QUEUE_TIER_ORDER`), then by `row_id` for a deterministic tie-break."""
    out: list[dict[str, Any]] = []
    for population_id, doc in frontier_docs.items():
        queues = doc.get("queues", {})
        for queue_name in QUEUE_TIER_ORDER:
            qd = queues.get(queue_name)
            if not qd:
                continue
            for row in qd.get("rows", []):
                if destination["path"] in (row.get("destination_paths") or []):
                    out.append({
                        "population_id": population_id,
                        "queue": queue_name,
                        "row": row,
                    })
    tier_index = {name: i for i, name in enumerate(QUEUE_TIER_ORDER)}
    out.sort(key=lambda c: (tier_index[c["queue"]], c["row"]["row_id"]))
    return out


def select_capability(
    destination: dict[str, Any],
    frontier_docs: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """Pick the highest-tier capability row for `destination`.

    Raises `DispatcherError` if the destination has zero rows across every
    published population/queue -- this can legitimately happen (a
    destination surfaced by `destination_candidates` in a future population
    whose queues later empty out); the caller must fail rather than
    fabricate a capability.
    """
    candidates = capability_candidates(destination, frontier_docs)
    if not candidates:
        raise DispatcherError(
            f"layer2:infrastructure-frontier -- destination {destination['path']} "
            "has zero capability rows across every published population/queue")
    top = candidates[0]
    authoritative = (
        top["population_id"] == PILOTED_POPULATION
        and top["queue"] in PILOTED_QUEUES
    )
    return {
        "population_id": top["population_id"],
        "queue": top["queue"],
        "row": top["row"],
        "authority": "authoritative" if authoritative else "advisory",
        "authority_reason": (
            f"ADR-0865 ran a pilot over population {PILOTED_POPULATION!r}, "
            f"queues {sorted(PILOTED_QUEUES)}, and retained the ranking there"
            if authoritative else
            f"ADR-0865 did not test population {top['population_id']!r} / "
            f"queue {top['queue']!r} (its pilots covered only "
            f"{PILOTED_POPULATION!r} / {sorted(PILOTED_QUEUES)}); this "
            "candidate is advisory, not dispatcher-authoritative"
        ),
        "candidates_considered": [
            {"population_id": c["population_id"], "queue": c["queue"],
             "row_id": c["row"]["row_id"]}
            for c in candidates[:10]
        ],
    }


# ---------------------------------------------------------------------------
# Layer 3: fact-frontier.py (via check-dispatchable-frontier.py) chooses the
# legal target
# ---------------------------------------------------------------------------

def run_dispatchable_frontier(python: str | None = None) -> dict[str, Any]:
    """Invoke `scripts/check-dispatchable-frontier.py --json` and return its
    parsed JSON plus the process exit code. Never edits, never reimplements
    its classification -- this is composition, not reinvention.

    Raises `DispatcherError` if the script cannot be found, cannot be run, or
    does not emit parseable JSON on stdout regardless of its exit code (a
    guard exit of 1 still emits full JSON with `guard_failures` populated --
    see check-dispatchable-frontier.py's own module doc for why `--json`
    keeps stdout pure).
    """
    if not DISPATCHABLE_SCRIPT.is_file():
        raise DispatcherError(
            f"layer3:fact-frontier -- {DISPATCHABLE_SCRIPT} does not exist")
    exe = python or sys.executable
    try:
        proc = subprocess.run(
            [exe, str(DISPATCHABLE_SCRIPT), "--json"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=120,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise DispatcherError(
            f"layer3:fact-frontier -- failed to run {DISPATCHABLE_SCRIPT}: {exc}"
        ) from exc
    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise DispatcherError(
            f"layer3:fact-frontier -- {DISPATCHABLE_SCRIPT} --json did not "
            f"emit parseable JSON on stdout (exit {proc.returncode}): {exc}. "
            f"stderr: {proc.stderr.strip()[:500]}"
        ) from exc
    payload["_exit_code"] = proc.returncode
    return payload


def forbidden_fact_ids(dispatch_result: dict[str, Any]) -> set[str]:
    """Every fact id this composition must never propose: held-out (blind
    evaluation, ADR-0542), mutation negative controls, and structurally
    blocked facts. This is the set an override request is checked against."""
    forbidden: set[str] = set(dispatch_result.get("held_out", []))
    forbidden |= set(dispatch_result.get("mutation", []))
    forbidden |= {b["fact"] for b in dispatch_result.get("blocked", [])}
    return forbidden


_PROPOSITION_RE = re.compile(r"proposition\s+(\S+)\s*$")


def load_fact(fact_id: str) -> dict[str, Any] | None:
    """Read `artifacts/facts/F-<slug>.json` for a `F:<slug>` fact id."""
    if not fact_id.startswith("F:"):
        return None
    path = FACTS_DIR / f"F-{fact_id[len('F:'):]}.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def mathlib_identifier(fact: dict[str, Any]) -> str | None:
    """The dotted Mathlib identifier a `ml430` mirror's title names, e.g.
    "Mathlib v4.30 source proposition Nat.dist.triangle_inequality" ->
    "Nat.dist.triangle_inequality". Returns None if the title does not carry
    this exact, well-known suffix shape (never guesses)."""
    m = _PROPOSITION_RE.search(fact.get("title", ""))
    return m.group(1) if m else None


def match_legal_target(
    capability_row: dict[str, Any],
    dispatchable_ids: list[str],
) -> dict[str, Any]:
    """Pick a legal target for `capability_row` from `dispatchable_ids` ONLY
    (never held-out/mutation/blocked -- callers must pass the dispatchable
    list, not the full classification).

    A "linked" match requires an EXACT (case-insensitive) match between one
    of the capability row's `subject_declarations` and one dot-separated
    component of a dispatchable fact's own Mathlib identifier -- the same
    bare-name-identity discipline ADR-0835/ADR-0845 apply elsewhere in this
    pipeline, deliberately NOT a fuzzy token-overlap heuristic (which would
    spuriously match on stopword-shaped fragments like "left"/"one"/"two"
    that both populations happen to share).

    If nothing links, falls back to the lexicographically smallest
    dispatchable id -- the same "best local-ready alternative" pattern
    ADR-0865's own pilots used when graph selection had nothing to offer.
    The fallback is ALWAYS labeled advisory by the caller
    (`legal_target_authority`), because it is not actually derived from the
    capability at all.
    """
    if not dispatchable_ids:
        return {"fact_id": None, "match_kind": "empty", "matched_identifier": None}
    subjects = {s.lower() for s in capability_row.get("subject_declarations", [])}
    for fact_id in sorted(dispatchable_ids):
        fact = load_fact(fact_id)
        if fact is None:
            continue
        ident = mathlib_identifier(fact)
        if not ident:
            continue
        parts = {p.lower() for p in ident.split(".")}
        parts.add(ident.lower())
        hit = subjects & parts
        if hit:
            return {
                "fact_id": fact_id,
                "match_kind": "linked",
                "matched_identifier": ident,
                "matched_subject": sorted(hit)[0],
            }
    fallback = sorted(dispatchable_ids)[0]
    return {"fact_id": fallback, "match_kind": "fallback", "matched_identifier": None}


def legal_target_authority(capability_authority: str, match_kind: str) -> tuple[str, str]:
    """The legal target inherits the capability's authority ONLY on a genuine
    link; a fallback pick is never authoritative, whatever the capability's
    own scope, because it was not actually selected BY the capability."""
    if match_kind == "linked" and capability_authority == "authoritative":
        return "authoritative", (
            "legal target's Mathlib identifier matches the capability row's "
            "own subject_declarations, and the capability is within "
            "ADR-0865's tested (population, queue) scope"
        )
    if match_kind == "linked":
        return "advisory", (
            "legal target links to the capability row, but the capability "
            "itself is outside ADR-0865's tested scope"
        )
    return "advisory", (
        "no dispatchable fact links to this capability row's subject_declarations "
        "(the two populations are largely disjoint -- ADR-0845's own cross-check "
        "finding); this is the unlinked local-ready fallback, never authoritative"
    )


def build_recommendation(python: str | None = None) -> dict[str, Any]:
    """Run all three layers and assemble the full, citable recommendation.
    Raises `DispatcherError` naming the failing layer on any absence -- there
    is no code path that returns a recommendation with a silently empty
    layer."""
    nodes = load_curriculum_nodes()
    frontier_docs = load_frontier_documents()
    destination = select_destination(nodes, frontier_docs)
    capability = select_capability(destination, frontier_docs)
    dispatch_result = run_dispatchable_frontier(python=python)
    guard_failures = dispatch_result.get("guard_failures") or []
    if dispatch_result.get("_exit_code") not in (0,) or guard_failures:
        raise DispatcherError(
            "layer3:fact-frontier -- check-dispatchable-frontier.py reported "
            f"exit={dispatch_result.get('_exit_code')} guard_failures="
            f"{guard_failures!r}; refusing to compose a recommendation on top "
            "of a failing upstream gate"
        )
    dispatchable_ids = dispatch_result.get("dispatchable") or []
    if not dispatchable_ids:
        raise DispatcherError(
            "layer3:fact-frontier -- the dispatchable set is empty; the "
            "composition has nothing legal left to propose")
    match = match_legal_target(capability["row"], dispatchable_ids)
    lt_authority, lt_reason = legal_target_authority(capability["authority"], match["match_kind"])

    row = capability["row"]
    recommendation = {
        "schema_version": 1,
        "kind": "graph-dispatcher-recommendation",
        "generated_by": "scripts/gen-graph-dispatcher.py",
        "adr_citations": [ADR_0865, ADR_0845, PLANNING_RULES],
        "advisory_notice": (
            "This recommendation is authoritative ONLY where the "
            "'authority' field on the capability and legal_target sections "
            "says 'authoritative' -- ADR-0865 bounds that to population "
            f"{PILOTED_POPULATION!r}, queues {sorted(PILOTED_QUEUES)}, and a "
            "genuinely linked legal target. Every other combination is "
            "advisory: visible, ranked, and overridable, never binding."
        ),
        "destination": {
            "node_id": destination["node_id"],
            "title": destination["title"],
            "layer": destination["layer"],
            "path": destination["path"],
            "selection_reason": destination["selection_reason"],
            "candidates_considered": destination["candidates_considered"],
        },
        "capability": {
            "population_id": capability["population_id"],
            "queue": capability["queue"],
            "row_id": row["row_id"],
            "title": row["title"],
            "subject_declarations": row["subject_declarations"],
            "gain_kind": row["gain_kind"],
            "preregistered_metric": row["preregistered_metric"],
            "authority": capability["authority"],
            "authority_reason": capability["authority_reason"],
            "candidates_considered": capability["candidates_considered"],
        },
        "legal_target": {
            "fact_id": match["fact_id"],
            "match_kind": match["match_kind"],
            "matched_identifier": match.get("matched_identifier"),
            "authority": lt_authority,
            "authority_reason": lt_reason,
        },
        "dispatchable_frontier_check": {
            "exit_code": dispatch_result.get("_exit_code"),
            "guard_failures": guard_failures,
            "open_mirrors": dispatch_result.get("open_mirrors"),
            "held_out_count": len(dispatch_result.get("held_out") or []),
            "mutation_count": len(dispatch_result.get("mutation") or []),
            "blocked_count": len(dispatch_result.get("blocked") or []),
            "dispatchable_count": len(dispatchable_ids),
            "dispatchable_floor": dispatch_result.get("dispatchable_floor"),
        },
        "override": None,
    }
    return recommendation
