//! Gaussian elimination and watched-row propagation over GF(2) —
//! [`IncrementalXorMatrix`].
//!
//! # Why this bench exists, and what it is for
//!
//! It was added by the `micro-opt-matrix` lane
//! (`docs/research/12-performance/micro-opt-matrix-2026-09-07.md`) to close a
//! measured hole in the bench set, not to profile the XOR route for its own
//! sake.
//!
//! That lane set out to measure what building for baseline `x86-64` (the
//! workspace default: SSE2 only, no POPCNT, no BMI1/BMI2) costs against
//! `x86-64-v3`, on the assumption — stated in its brief — that clause-quality
//! (LBD) computation and the watch-list scans are bit-counting code. Checked
//! against the source, they are not. `Cdcl::compute_lbd` collects decision
//! levels into a `Vec<usize>`, sorts and dedups; and grepping `count_ones` /
//! `trailing_zeros` / `leading_zeros` across `axeyum-cnf`, `axeyum-aig`,
//! `axeyum-bv` and `axeyum-ir`, **not one call is in the CDCL core**. They are
//! all here, in the XOR/GF(2) path — `xor_matrix.rs`, `xor_extract.rs`,
//! `gf2.rs`, `xor_dpll.rs`, `xor_propagate.rs`, `xor_cdcl.rs` — which had no
//! bench at all.
//!
//! So this file is the **positive control for the `target-cpu` axis**: the one
//! place in the crate where those instructions are actually reachable. A
//! `target-cpu` measurement taken only on the CDCL core would be a null result
//! from code that structurally cannot show the effect, which is not the same
//! finding as "the effect is small".
//!
//! # What each group proxies
//!
//! - **`xor_matrix_rref`** — `IncrementalXorMatrix::new`, which reduces the
//!   input system to RREF. The inner loop is word-at-a-time `^=` over row
//!   bitsets (`Vec<u64>`), the shape an auto-vectorizer can widen from 64-bit
//!   to 256-bit under AVX2. This is the arm where `x86-64-v3` has the most to
//!   gain in this crate.
//!
//! - **`xor_matrix_assign_backtrack`** — the incremental search step: assign,
//!   read the implied literals, backtrack. Its hot loops are
//!   `while b != 0 { let tz = b.trailing_zeros(); …; b &= b - 1; }` over row
//!   bitsets (`choose_watched`, `row_lowest_free`, `row_free_vars`,
//!   `row_effective_parity`). That idiom is `tzcnt` + `blsr` under BMI1 and
//!   `bsf` + a two-instruction sequence on baseline. Note the ceiling is low by
//!   construction: `b != 0` is a loop invariant, so LLVM can already use bare
//!   `bsf` with no zero-handling on baseline, and each iteration also does a
//!   bounds-checked load from `self.assignment` — a dependent load that is
//!   likely to dominate either encoding.
//!
//! # The fixture, and the axis on which it is a poor proxy
//!
//! The constraints are generated by a fixed-seed LCG: `rows` XOR constraints of
//! 3–6 variables each over `vars` variables, which is the length distribution
//! Tseitin-encoded XOR chains (CRC, block-cipher key schedules, parity
//! circuits) actually produce, and the density at which Gaussian elimination
//! fills rows in rather than leaving them sparse.
//!
//! It is a **synthetic** fixture: no corpus instance is driven through it. The
//! honest limitation is therefore the one this repository keeps rediscovering —
//! a microbenchmark that does not predict the real workload is worse than none.
//! What this file supports is a *relative* claim between two builds of the same
//! code on the same fixture, which is exactly what the optimisation-matrix
//! question is. It does **not** support a claim about how much of any real
//! query's time is spent in GF(2) elimination; that would need the XOR route
//! driven from a corpus instance, and it is not measured here.
//!
//! The width sweep (2,048 / 8,192 variables) exists so the two shapes are
//! separable: RREF cost is superlinear in the variable count (rows get longer
//! *and* there are more of them to eliminate against), while the per-assign
//! cost is proportional to the number of rows watching one variable and should
//! stay far flatter.

#![allow(missing_docs)] // criterion_group!/criterion_main! expand to undocumented items; see module doc.

use std::hint::black_box;

use axeyum_cnf::{IncrementalXorMatrix, XorMatrixStep};
use criterion::{Criterion, criterion_group, criterion_main};

/// A fixed-seed LCG. Determinism is a public API promise in this repository and
/// a benchmark fixture that varies run to run cannot support a ratio between
/// two builds, so no system randomness is used.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        self.0 >> 11
    }

    fn below(&mut self, n: usize) -> usize {
        // `n` is a benchmark constant (4, 2_048, 8_192), so the remainder is
        // below it and the conversion cannot truncate; `expect` rather than
        // `as` keeps that an assertion instead of a silent wrap.
        usize::try_from(self.next() % (n as u64)).expect("remainder below n fits usize")
    }
}

/// `rows` XOR constraints of 3–6 distinct variables each over `vars` variables.
fn system(vars: usize, rows: usize, seed: u64) -> Vec<(Vec<usize>, bool)> {
    let mut rng = Lcg(seed);
    let mut out = Vec::with_capacity(rows);
    for _ in 0..rows {
        let len = 3 + rng.below(4);
        let mut vs: Vec<usize> = Vec::with_capacity(len);
        while vs.len() < len {
            let v = rng.below(vars);
            if !vs.contains(&v) {
                vs.push(v);
            }
        }
        let parity = rng.next() & 1 == 1;
        out.push((vs, parity));
    }
    out
}

fn bench_rref(c: &mut Criterion) {
    let mut group = c.benchmark_group("xor_matrix_rref");
    for &(vars, rows) in &[(2_048usize, 1_024usize), (8_192, 4_096)] {
        let constraints = system(vars, rows, 0x5eed_1234);
        group.bench_function(format!("vars{vars}_rows{rows}"), |b| {
            b.iter(|| {
                let m = IncrementalXorMatrix::new(black_box(&constraints), black_box(vars));
                black_box(m.num_vars())
            });
        });
    }
    group.finish();
}

fn bench_assign_backtrack(c: &mut Criterion) {
    let mut group = c.benchmark_group("xor_matrix_assign_backtrack");
    for &(vars, rows) in &[(2_048usize, 1_024usize), (8_192, 4_096)] {
        let constraints = system(vars, rows, 0x5eed_1234);
        // The descent order is fixed and precomputed so the measured loop does
        // no work the benchmark is not trying to measure.
        // 64 assigns, not 256. `assign` journals the whole row and watch state
        // so `backtrack_to` can restore it exactly, which makes each assign
        // O(rows x words) of copying; at 256 the large fixture took 400 ms per
        // iteration, which is a criterion sample count of a few and a sweep
        // measured in hours. Measured before choosing: 52 ms / 403 ms at 256.
        let mut rng = Lcg(0xa5a5_0f0f);
        let descent: Vec<(usize, bool)> = (0..64)
            .map(|_| (rng.below(vars), rng.next() & 1 == 1))
            .collect();
        group.bench_function(format!("vars{vars}_rows{rows}"), |b| {
            b.iter_batched(
                || IncrementalXorMatrix::new(&constraints, vars),
                |mut m| {
                    let base = m.trail_len();
                    let mut implied = 0usize;
                    // `assign` panics on an already-assigned variable and the
                    // matrix exposes no per-variable accessor, so the set is
                    // tracked here: every variable this loop assigns, plus
                    // every variable the matrix reports as implied by one.
                    let mut on_trail = vec![false; vars];
                    for &(v, val) in &descent {
                        if m.in_conflict() || on_trail[v] {
                            continue;
                        }
                        on_trail[v] = true;
                        match m.assign(v, val) {
                            XorMatrixStep::Implied { implied: lits } => {
                                implied += lits.len();
                                for l in &lits {
                                    on_trail[l.var] = true;
                                }
                            }
                            XorMatrixStep::Conflict { reason } => {
                                implied += reason.len();
                                break;
                            }
                            XorMatrixStep::Ok => {}
                        }
                    }
                    m.backtrack_to(base);
                    black_box(implied)
                },
                criterion::BatchSize::SmallInput,
            );
        });
    }
    group.finish();
}

criterion_group!(benches, bench_rref, bench_assign_backtrack);
criterion_main!(benches);
