//! ADR-1631 (roadmap W3-12): the Bernoulli distribution as a **constructed**
//! two-point model on the generic finite-probability carrier, its mean and
//! its variance.
//!
//! `rat_prelude/probability_s.rs` (ADR-1616) states the finite probability
//! layer once over `(R : AlgS.OrderedRing)`: `sumRange`, `IsDistribution`,
//! `expectation`, `variance`, `covariance`, `Independent`. Everything there
//! is stated for an ARBITRARY weight function `p` and an arbitrary variable
//! `X`. Nothing in the shelf is a *named distribution*: no `p` is ever built,
//! so no `IsDistribution` is ever discharged from a construction rather than
//! assumed.
//!
//! This module builds the first one. On the two-outcome index range `{0, 1}`:
//!
//! * `bernoulliVar R : Nat → R.carrier` is the indicator `0 ↦ 0`,
//!   `succ _ ↦ 1`;
//! * `bernoulliMass R q : Nat → R.carrier` is the mass `0 ↦ 1 − q`,
//!   `succ _ ↦ q`.
//!
//! Both are `Nat.rec` over the record's own `zero`/`one`/`add`/`neg`, so at
//! `R := AlgS.Rat.orderedRingS` they δι-reduce to `ℚ` terms and the three
//! theorems below become `ℚ` theorems by instantiation, not by analogy.
//!
//! **What the record costs here.** `AlgS.OrderedRing` carries no `mulComm`
//! (ADR-1592 §2). The variance identity `E[(X−q)²] ≃ q·(1−q)` is
//! nevertheless provable without it, because the subring generated by a
//! single element is commutative — but that fact has to be *supplied*, and
//! it is supplied as exactly one lemma: [`declare_bernoulli_variance`]'s
//! `hcomm : (1−q)·q ≃ q·(1−q)`, proved by expanding both sides to
//! `q + −(q·q)` with `distribL`/`distribR`. Once `q·(1−q)` and `(1−q)·q` are
//! interchangeable the whole computation collapses in four steps:
//! `q·(q·u) + u·(q·u) ≃ (q + u)·(q·u) ≃ 1·(q·u) ≃ q·u`, since `q + u ≃ 1`.
//! That is the entire content of "the Bernoulli variance is `p(1−p)`" once
//! the shelf is doing the work.
//!
//! Two generic ring lemmas the spine did not carry are declared first:
//! [`declare_mul_neg`] (`a·(−b) ≃ −(a·b)` — the spine has only the LEFT
//! side, `AlgS.OrderedRing.neg_mul`) and [`declare_zero_add`] (`0 + a ≃ a` —
//! the record's additive unit law is right-handed).
//!
//! Every theorem in this file is proved from the record's fields and the
//! already-declared `AlgS.*` ring calculus: no axiom, no classical
//! principle, no carrier-specific step.

use super::RatPrelude;
use crate::Kernel;
use crate::KernelError;
use crate::env::{Declaration, ReducibilityHint};
use crate::expr::ExprId;
use crate::int_prelude::ops::IntDev;
use crate::name::NameId;
use crate::nat_prelude::NatOps;
use crate::nat_prelude::structures::{RecordNames, sel};
use crate::nat_prelude::structures_setoid::idx::ordered_ring as oidx;

/// The names this module declares, all under the `AlgS.OrderedRing` root
/// (the same root ADR-1616's probability layer uses, since every one of them
/// takes the record as its leading argument).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BinomialSNames {
    pub mul_neg: NameId,
    pub zero_add: NameId,
    pub bernoulli_var: NameId,
    pub bernoulli_mass: NameId,
    pub bernoulli_mass_nonneg: NameId,
    pub bernoulli_is_distribution: NameId,
    pub bernoulli_expectation: NameId,
    pub bernoulli_variance: NameId,
}

/// Intern every name this module declares.
pub(crate) fn intern_binomial_s(k: &mut Kernel) -> BinomialSNames {
    let anon = k.anon();
    let algs = k.name_str(anon, "AlgS");
    let root = k.name_str(algs, "OrderedRing");
    BinomialSNames {
        mul_neg: k.name_str(root, "mul_neg"),
        zero_add: k.name_str(root, "zero_add"),
        bernoulli_var: k.name_str(root, "bernoulliVar"),
        bernoulli_mass: k.name_str(root, "bernoulliMass"),
        bernoulli_mass_nonneg: k.name_str(root, "bernoulliMass_nonneg"),
        bernoulli_is_distribution: k.name_str(root, "bernoulli_isDistribution"),
        bernoulli_expectation: k.name_str(root, "bernoulli_expectation"),
        bernoulli_variance: k.name_str(root, "bernoulli_variance"),
    }
}

// ---------------------------------------------------------------------------
// Projections.
// ---------------------------------------------------------------------------

/// The `AlgS.OrderedRing` fields this file uses, projected once at a record
/// value `r`.
///
/// Deliberately a private copy of `probability_s`'s `Rec` rather than a
/// re-export of it: this file needs three fields that one does not
/// (`mulOneL`, `negCongr`, `distribL`-side unit laws), and widening a struct
/// another module's twenty proofs read is exactly the shared append point
/// this repository's multi-agent rules warn about.
#[derive(Clone, Copy)]
struct Rec {
    carrier: ExprId,
    equiv: ExprId,
    erefl: ExprId,
    esymm: ExprId,
    etrans: ExprId,
    zero: ExprId,
    one: ExprId,
    add: ExprId,
    mul: ExprId,
    add_congr: ExprId,
    mul_congr: ExprId,
    add_assoc: ExprId,
    add_comm: ExprId,
    add_zero: ExprId,
    mul_assoc: ExprId,
    mul_one_l: ExprId,
    mul_one_r: ExprId,
    distrib_l: ExprId,
    distrib_r: ExprId,
    neg: ExprId,
    neg_congr: ExprId,
    neg_add: ExprId,
    le: ExprId,
}

fn proj_one(d: &mut IntDev<'_>, rn: &RecordNames, i: usize, r: ExprId) -> ExprId {
    let k = d.kernel();
    sel(k, rn, i, r)
}

fn proj(d: &mut IntDev<'_>, rn: &RecordNames, r: ExprId) -> Rec {
    Rec {
        carrier: proj_one(d, rn, oidx::CARRIER, r),
        equiv: proj_one(d, rn, oidx::EQUIV, r),
        erefl: proj_one(d, rn, oidx::EQUIV_REFL, r),
        esymm: proj_one(d, rn, oidx::EQUIV_SYMM, r),
        etrans: proj_one(d, rn, oidx::EQUIV_TRANS, r),
        zero: proj_one(d, rn, oidx::ZERO, r),
        one: proj_one(d, rn, oidx::ONE, r),
        add: proj_one(d, rn, oidx::ADD, r),
        mul: proj_one(d, rn, oidx::MUL, r),
        add_congr: proj_one(d, rn, oidx::ADD_CONGR, r),
        mul_congr: proj_one(d, rn, oidx::MUL_CONGR, r),
        add_assoc: proj_one(d, rn, oidx::ADD_ASSOC, r),
        add_comm: proj_one(d, rn, oidx::ADD_COMM, r),
        add_zero: proj_one(d, rn, oidx::ADD_ZERO, r),
        mul_assoc: proj_one(d, rn, oidx::MUL_ASSOC, r),
        mul_one_l: proj_one(d, rn, oidx::MUL_ONE_L, r),
        mul_one_r: proj_one(d, rn, oidx::MUL_ONE_R, r),
        distrib_l: proj_one(d, rn, oidx::DISTRIB_L, r),
        distrib_r: proj_one(d, rn, oidx::DISTRIB_R, r),
        neg: proj_one(d, rn, oidx::NEG, r),
        neg_congr: proj_one(d, rn, oidx::NEG_CONGR, r),
        neg_add: proj_one(d, rn, oidx::NEG_ADD, r),
        le: proj_one(d, rn, oidx::LE, r),
    }
}

// --- term shorthands -------------------------------------------------------

fn eqv(d: &mut IntDev<'_>, c: Rec, a: ExprId, b: ExprId) -> ExprId {
    d.apply(c.equiv, &[a, b])
}
fn radd(d: &mut IntDev<'_>, c: Rec, a: ExprId, b: ExprId) -> ExprId {
    d.apply(c.add, &[a, b])
}
fn rmul(d: &mut IntDev<'_>, c: Rec, a: ExprId, b: ExprId) -> ExprId {
    d.apply(c.mul, &[a, b])
}
fn rneg(d: &mut IntDev<'_>, c: Rec, a: ExprId) -> ExprId {
    d.apply(c.neg, &[a])
}
fn rle(d: &mut IntDev<'_>, c: Rec, a: ExprId, b: ExprId) -> ExprId {
    d.apply(c.le, &[a, b])
}
fn refl(d: &mut IntDev<'_>, c: Rec, a: ExprId) -> ExprId {
    d.apply(c.erefl, &[a])
}
fn symm(d: &mut IntDev<'_>, c: Rec, a: ExprId, b: ExprId, h: ExprId) -> ExprId {
    d.apply(c.esymm, &[a, b, h])
}
fn trans(
    d: &mut IntDev<'_>,
    c: Rec,
    a: ExprId,
    b: ExprId,
    e: ExprId,
    h1: ExprId,
    h2: ExprId,
) -> ExprId {
    d.apply(c.etrans, &[a, b, e, h1, h2])
}
#[allow(clippy::too_many_arguments)]
fn acongr(
    d: &mut IntDev<'_>,
    c: Rec,
    a: ExprId,
    a2: ExprId,
    b: ExprId,
    b2: ExprId,
    h1: ExprId,
    h2: ExprId,
) -> ExprId {
    d.apply(c.add_congr, &[a, a2, b, b2, h1, h2])
}
#[allow(clippy::too_many_arguments)]
fn mcongr(
    d: &mut IntDev<'_>,
    c: Rec,
    a: ExprId,
    a2: ExprId,
    b: ExprId,
    b2: ExprId,
    h1: ExprId,
    h2: ExprId,
) -> ExprId {
    d.apply(c.mul_congr, &[a, a2, b, b2, h1, h2])
}
fn ncongr(d: &mut IntDev<'_>, c: Rec, a: ExprId, b: ExprId, h: ExprId) -> ExprId {
    d.apply(c.neg_congr, &[a, b, h])
}

/// `equivTrans`-fold a chain of steps, mirroring `NatOps::chain` for the
/// record's setoid equality: `steps[i] = (next_rhs, proof_of(cur ≃ next))`.
fn chain(d: &mut IntDev<'_>, c: Rec, start: ExprId, steps: &[(ExprId, ExprId)]) -> ExprId {
    let mut cur = start;
    let mut acc: Option<ExprId> = None;
    for &(next, step) in steps {
        acc = Some(match acc {
            None => step,
            Some(prev) => trans(d, c, start, cur, next, prev, step),
        });
        cur = next;
    }
    acc.expect("chain needs at least one step")
}

/// The record's own type, `AlgS.OrderedRing`.
fn rec_ty(d: &mut IntDev<'_>, rn: &RecordNames) -> ExprId {
    d.kernel().const_(rn.ind, vec![])
}

// ---------------------------------------------------------------------------
// Two generic ring lemmas the spine did not carry.
// ---------------------------------------------------------------------------

/// `AlgS.OrderedRing.mul_neg : ∀ R a b, equiv (mul a (neg b)) (neg (mul a
/// b))` — the RIGHT-handed twin of `AlgS.OrderedRing.neg_mul` (ADR-1616).
///
/// Without `mulComm` the two are genuinely different statements, and only
/// the left one was proved. This one goes through `AlgS.mul_neg_one`
/// (ADR-1590, over `AlgS.Ring`, reached by `toRingS`) rather than through a
/// second `add_left_cancel` argument: `a·(−b) ≃ a·(b·(−1)) ≃ (a·b)·(−1) ≃
/// −(a·b)`, three steps, of which the middle one is just `mulAssoc`.
fn declare_mul_neg(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
    to_ring_s: NameId,
    mul_neg_one: NameId,
) -> Result<(), KernelError> {
    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);
    let ring_r = d.const_app(to_ring_s, &[r]);

    let a_fv = d.fresh_fvar();
    let a = d.kernel().fvar(a_fv);
    let b_fv = d.fresh_fvar();
    let b = d.kernel().fvar(b_fv);

    let nb = rneg(d, c, b);
    let none = rneg(d, c, c.one);
    let ab = rmul(d, c, a, b);
    let n_ab = rneg(d, c, ab);
    let a_nb = rmul(d, c, a, nb);
    let b_none = rmul(d, c, b, none);
    let a_b_none = rmul(d, c, a, b_none);
    let ab_none = rmul(d, c, ab, none);

    // s1 : equiv (neg b) (mul b (neg one))
    let mno_b = d.const_app(mul_neg_one, &[ring_r, b]);
    let s1 = symm(d, c, b_none, nb, mno_b);
    // s2 : equiv (mul a (neg b)) (mul a (mul b (neg one)))
    let refl_a = refl(d, c, a);
    let s2 = mcongr(d, c, a, a, nb, b_none, refl_a, s1);
    // s3 : equiv (mul a (mul b (neg one))) (mul (mul a b) (neg one))
    let assoc = d.apply(c.mul_assoc, &[a, b, none]);
    let s3 = symm(d, c, ab_none, a_b_none, assoc);
    // s4 : equiv (mul (mul a b) (neg one)) (neg (mul a b))
    let s4 = d.const_app(mul_neg_one, &[ring_r, ab]);

    let core = chain(d, c, a_nb, &[(a_b_none, s2), (ab_none, s3), (n_ab, s4)]);

    let stmt = eqv(d, c, a_nb, n_ab);
    let ord_ty = rec_ty(d, rn);
    let ty = {
        let over_b = d.pi_fv(b_fv, c.carrier, stmt);
        let over_a = d.pi_fv(a_fv, c.carrier, over_b);
        d.pi_fv(r_fv, ord_ty, over_a)
    };
    let value = {
        let over_b = d.lam_fv(b_fv, c.carrier, core);
        let over_a = d.lam_fv(a_fv, c.carrier, over_b);
        d.lam_fv(r_fv, ord_ty, over_a)
    };
    d.declare_theorem(names.mul_neg, ty, value)
}

/// `AlgS.OrderedRing.zero_add : ∀ R a, equiv (add zero a) a`.
///
/// The record's additive unit law `addZero` is right-handed; every sum this
/// file reduces out of `sumRange` starts with a literal `zero` on the LEFT,
/// so the left law is needed once per summand. `addComm` then `addZero`.
fn declare_zero_add(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
) -> Result<(), KernelError> {
    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);
    let a_fv = d.fresh_fvar();
    let a = d.kernel().fvar(a_fv);

    let za = radd(d, c, c.zero, a);
    let az = radd(d, c, a, c.zero);
    let s1 = d.apply(c.add_comm, &[c.zero, a]);
    let s2 = d.apply(c.add_zero, &[a]);
    let core = trans(d, c, za, az, a, s1, s2);

    let stmt = eqv(d, c, za, a);
    let ord_ty = rec_ty(d, rn);
    let ty = {
        let over_a = d.pi_fv(a_fv, c.carrier, stmt);
        d.pi_fv(r_fv, ord_ty, over_a)
    };
    let value = {
        let over_a = d.lam_fv(a_fv, c.carrier, core);
        d.lam_fv(r_fv, ord_ty, over_a)
    };
    d.declare_theorem(names.zero_add, ty, value)
}

// ---------------------------------------------------------------------------
// The construction.
// ---------------------------------------------------------------------------

/// `AlgS.OrderedRing.bernoulliVar R`, the partial application at `R`.
fn bvar(d: &mut IntDev<'_>, names: &BinomialSNames, r: ExprId) -> ExprId {
    d.const_app(names.bernoulli_var, &[r])
}

/// `AlgS.OrderedRing.bernoulliMass R q`, the partial application at `R`, `q`.
fn bmass(d: &mut IntDev<'_>, names: &BinomialSNames, r: ExprId, q: ExprId) -> ExprId {
    d.const_app(names.bernoulli_mass, &[r, q])
}

/// `AlgS.OrderedRing.bernoulliVar : ∀ (R : AlgS.OrderedRing), Nat →
/// R.carrier := fun R k => Nat.rec R.zero (fun _ _ => R.one) k`.
///
/// The success indicator on the two-outcome range: `bernoulliVar R 0 ≡
/// R.zero` and `bernoulliVar R 1 ≡ R.one`, both by ι alone, which is what
/// makes every statement below reduce without an equation lemma.
fn declare_bernoulli_var(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
) -> Result<(), KernelError> {
    let nat = d.nat_ty();
    let anon = d.anon_name();
    let l1 = d.level_one();

    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);

    let motive = d
        .kernel()
        .lam(anon, nat, c.carrier, crate::BinderInfo::Default);
    let minor_succ = {
        let j_fv = d.fresh_fvar();
        let ih_fv = d.fresh_fvar();
        let inner = d.lam_fv(ih_fv, c.carrier, c.one);
        d.lam_fv(j_fv, nat, inner)
    };
    let k_fv = d.fresh_fvar();
    let kv = d.kernel().fvar(k_fv);
    let rec_name = d.prelude().rec;
    let rec = d.kernel().const_(rec_name, vec![l1]);
    let body = d.apply(rec, &[motive, c.zero, minor_succ, kv]);

    let value = {
        let with_k = d.lam_fv(k_fv, nat, body);
        let ord_ty = rec_ty(d, rn);
        d.lam_fv(r_fv, ord_ty, with_k)
    };
    let ty = {
        let over_k = d.arrow(nat, c.carrier);
        let ord_ty = rec_ty(d, rn);
        d.pi_fv(r_fv, ord_ty, over_k)
    };
    d.kernel().add_declaration(Declaration::Definition {
        name: names.bernoulli_var,
        uparams: vec![],
        ty,
        value,
        hint: ReducibilityHint::Regular(1),
    })
}

/// `AlgS.OrderedRing.bernoulliMass : ∀ (R : AlgS.OrderedRing), R.carrier →
/// Nat → R.carrier := fun R q k => Nat.rec (R.add R.one (R.neg q)) (fun _ _
/// => q) k`.
///
/// The mass function of the two-outcome model: `bernoulliMass R q 0 ≡ 1 − q`
/// (failure) and `bernoulliMass R q 1 ≡ q` (success). Written `add one (neg
/// q)` rather than through `AlgS.sub` so it is the same shape
/// `sub_nonneg_of_le` (ADR-1616) already produces — the nonnegativity proof
/// is then that theorem applied, with no rewriting at all.
fn declare_bernoulli_mass(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
) -> Result<(), KernelError> {
    let nat = d.nat_ty();
    let anon = d.anon_name();
    let l1 = d.level_one();

    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);
    let q_fv = d.fresh_fvar();
    let q = d.kernel().fvar(q_fv);

    let nq = rneg(d, c, q);
    let one_minus_q = radd(d, c, c.one, nq);

    let motive = d
        .kernel()
        .lam(anon, nat, c.carrier, crate::BinderInfo::Default);
    let minor_succ = {
        let j_fv = d.fresh_fvar();
        let ih_fv = d.fresh_fvar();
        let inner = d.lam_fv(ih_fv, c.carrier, q);
        d.lam_fv(j_fv, nat, inner)
    };
    let k_fv = d.fresh_fvar();
    let kv = d.kernel().fvar(k_fv);
    let rec_name = d.prelude().rec;
    let rec = d.kernel().const_(rec_name, vec![l1]);
    let body = d.apply(rec, &[motive, one_minus_q, minor_succ, kv]);

    let value = {
        let with_k = d.lam_fv(k_fv, nat, body);
        let with_q = d.lam_fv(q_fv, c.carrier, with_k);
        let ord_ty = rec_ty(d, rn);
        d.lam_fv(r_fv, ord_ty, with_q)
    };
    let ty = {
        let over_k = d.arrow(nat, c.carrier);
        let over_q = d.arrow(c.carrier, over_k);
        let ord_ty = rec_ty(d, rn);
        d.pi_fv(r_fv, ord_ty, over_q)
    };
    d.kernel().add_declaration(Declaration::Definition {
        name: names.bernoulli_mass,
        uparams: vec![],
        ty,
        value,
        hint: ReducibilityHint::Regular(1),
    })
}

/// `AlgS.OrderedRing.bernoulliMass_nonneg : ∀ R q, le zero q → le q one → ∀
/// k, le zero (bernoulliMass R q k)` — for EVERY `k`, not only `k < 2`.
///
/// `Nat.rec` on `k`: the base case is `sub_nonneg_of_le R q one` (ADR-1616)
/// applied to `q ≤ 1`, whose conclusion `le zero (add one (neg q))` is
/// literally the ι-reduct of `bernoulliMass R q 0`; every successor case is
/// the `0 ≤ q` hypothesis unchanged. Stating it unbounded is what lets
/// [`declare_bernoulli_is_distribution`] discharge `∀ i, i < 2 → …` with
/// `fun i _ => …` and never invert a `Nat.lt`.
fn declare_bernoulli_mass_nonneg(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
    sub_nonneg_of_le: NameId,
) -> Result<(), KernelError> {
    let nat = d.nat_ty();
    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);
    let q_fv = d.fresh_fvar();
    let q = d.kernel().fvar(q_fv);

    let h0_ty = rle(d, c, c.zero, q);
    let h0_fv = d.fresh_fvar();
    let h0 = d.kernel().fvar(h0_fv);
    let h1_ty = rle(d, c, q, c.one);
    let h1_fv = d.fresh_fvar();
    let h1 = d.kernel().fvar(h1_fv);

    let mass = bmass(d, names, r, q);
    let k_fv = d.fresh_fvar();
    let kv = d.kernel().fvar(k_fv);

    let motive = |d: &mut IntDev<'_>, x: ExprId| -> ExprId {
        let mx = d.apply(mass, &[x]);
        rle(d, c, c.zero, mx)
    };
    let core = d.induct(
        &motive,
        &|d| d.const_app(sub_nonneg_of_le, &[r, q, c.one, h1]),
        &|_d, _j, _ih| h0,
        kv,
    );

    let concl = motive(d, kv);
    let ord_ty = rec_ty(d, rn);
    let ty = {
        let over_k = d.pi_fv(k_fv, nat, concl);
        let over_h1 = d.arrow(h1_ty, over_k);
        let over_h0 = d.arrow(h0_ty, over_h1);
        let over_q = d.pi_fv(q_fv, c.carrier, over_h0);
        d.pi_fv(r_fv, ord_ty, over_q)
    };
    let value = {
        let over_k = d.lam_fv(k_fv, nat, core);
        let over_h1 = d.lam_fv(h1_fv, h1_ty, over_k);
        let over_h0 = d.lam_fv(h0_fv, h0_ty, over_h1);
        let over_q = d.lam_fv(q_fv, c.carrier, over_h0);
        d.lam_fv(r_fv, ord_ty, over_q)
    };
    d.declare_theorem(names.bernoulli_mass_nonneg, ty, value)
}

/// `AlgS.OrderedRing.bernoulli_isDistribution : ∀ R q, le zero q → le q one →
/// IsDistribution R (bernoulliMass R q) 2`.
///
/// **The first `IsDistribution` in the repository discharged from a
/// construction rather than assumed.** Its two halves are
/// [`declare_bernoulli_mass_nonneg`] (weakened to `i < 2` by ignoring the
/// bound) and `sumRange R (bernoulliMass R q) 2 ≃ 1`, which ι-reduces to
/// `(0 + (1 + −q)) + q ≃ 1` and is then four record laws: `zero_add`,
/// `addAssoc`, `addComm`/`negAdd`, `addZero`.
fn declare_bernoulli_is_distribution(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
    is_distribution: NameId,
    sum_range: NameId,
) -> Result<(), KernelError> {
    let nat = d.nat_ty();
    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);
    let q_fv = d.fresh_fvar();
    let q = d.kernel().fvar(q_fv);

    let h0_ty = rle(d, c, c.zero, q);
    let h0_fv = d.fresh_fvar();
    let h0 = d.kernel().fvar(h0_fv);
    let h1_ty = rle(d, c, q, c.one);
    let h1_fv = d.fresh_fvar();
    let h1 = d.kernel().fvar(h1_fv);

    let two = d.num(2);
    let mass = bmass(d, names, r, q);

    // Left half: forall i, Nat.lt i 2 -> le zero (mass i).
    let nonneg_part = {
        let i_fv = d.fresh_fvar();
        let i = d.kernel().fvar(i_fv);
        let hyp = d.lt(i, two);
        let mi = d.apply(mass, &[i]);
        let nonneg = rle(d, c, c.zero, mi);
        let body = d.arrow(hyp, nonneg);
        d.pi_fv(i_fv, nat, body)
    };
    let nonneg_proof = {
        let i_fv = d.fresh_fvar();
        let i = d.kernel().fvar(i_fv);
        let hyp = d.lt(i, two);
        let hi_fv = d.fresh_fvar();
        let at_i = d.const_app(names.bernoulli_mass_nonneg, &[r, q, h0, h1, i]);
        let with_hi = d.lam_fv(hi_fv, hyp, at_i);
        d.lam_fv(i_fv, nat, with_hi)
    };

    // Right half: sumRange R mass 2 ~ one, i.e. (0 + (1 + -q)) + q ~ 1.
    let nq = rneg(d, c, q);
    let u = radd(d, c, c.one, nq);
    let zu = radd(d, c, c.zero, u);
    let zu_q = radd(d, c, zu, q);
    let u_q = radd(d, c, u, q);
    let nq_q = radd(d, c, nq, q);
    let q_nq = radd(d, c, q, nq);
    let one_nq_q = radd(d, c, c.one, nq_q);
    let one_zero = radd(d, c, c.one, c.zero);

    let refl_q = refl(d, c, q);
    let s1 = {
        let za = d.const_app(names.zero_add, &[r, u]);
        acongr(d, c, zu, u, q, q, za, refl_q)
    };
    let s2 = d.apply(c.add_assoc, &[c.one, nq, q]);
    let s3 = {
        let comm = d.apply(c.add_comm, &[nq, q]);
        let na = d.apply(c.neg_add, &[q]);
        let inner = trans(d, c, nq_q, q_nq, c.zero, comm, na);
        let refl_one = refl(d, c, c.one);
        acongr(d, c, c.one, c.one, nq_q, c.zero, refl_one, inner)
    };
    let s4 = d.apply(c.add_zero, &[c.one]);
    let sum_proof = chain(
        d,
        c,
        zu_q,
        &[(u_q, s1), (one_nq_q, s2), (one_zero, s3), (c.one, s4)],
    );
    let sum_part = {
        let sum = d.const_app(sum_range, &[r, mass, two]);
        eqv(d, c, sum, c.one)
    };

    let and_intro = d.int().logic.and_intro;
    let core = d.const_app(and_intro, &[nonneg_part, sum_part, nonneg_proof, sum_proof]);

    let stmt = d.const_app(is_distribution, &[r, mass, two]);
    let ord_ty = rec_ty(d, rn);
    let ty = {
        let over_h1 = d.arrow(h1_ty, stmt);
        let over_h0 = d.arrow(h0_ty, over_h1);
        let over_q = d.pi_fv(q_fv, c.carrier, over_h0);
        d.pi_fv(r_fv, ord_ty, over_q)
    };
    let value = {
        let over_h1 = d.lam_fv(h1_fv, h1_ty, core);
        let over_h0 = d.lam_fv(h0_fv, h0_ty, over_h1);
        let over_q = d.lam_fv(q_fv, c.carrier, over_h0);
        d.lam_fv(r_fv, ord_ty, over_q)
    };
    d.declare_theorem(names.bernoulli_is_distribution, ty, value)
}

/// `AlgS.OrderedRing.bernoulli_expectation : ∀ R q, equiv (expectation R
/// (bernoulliVar R) (bernoulliMass R q) 2) q` — **the parameter IS the
/// mean**, with no hypothesis on `q` at all.
///
/// `expectation` at `n = 2` ι-reduces to `(0 + (0 · (1 − q))) + (1 · q)`;
/// `zero_mul` (ADR-1616) kills the failure term, `mulOneL` and
/// [`declare_zero_add`] strip the success term. Note that `0 ≤ q ≤ 1` is
/// nowhere needed: the identity is algebraic, and only
/// [`declare_bernoulli_is_distribution`] cares whether the weights are a
/// distribution.
fn declare_bernoulli_expectation(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
    expectation: NameId,
    zero_mul: NameId,
) -> Result<(), KernelError> {
    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);
    let q_fv = d.fresh_fvar();
    let q = d.kernel().fvar(q_fv);

    let two = d.num(2);
    let var = bvar(d, names, r);
    let mass = bmass(d, names, r, q);

    let nq = rneg(d, c, q);
    let u = radd(d, c, c.one, nq);
    let zero_u = rmul(d, c, c.zero, u);
    let one_q = rmul(d, c, c.one, q);
    let head = radd(d, c, c.zero, zero_u);
    let lhs = radd(d, c, head, one_q);
    let zero_plus_q = radd(d, c, c.zero, q);

    // head ~ zero : zero_add then zero_mul.
    let head_zero = {
        let za = d.const_app(names.zero_add, &[r, zero_u]);
        let zm = d.const_app(zero_mul, &[r, u]);
        trans(d, c, head, zero_u, c.zero, za, zm)
    };
    let mol = d.apply(c.mul_one_l, &[q]);
    let s1 = acongr(d, c, head, c.zero, one_q, q, head_zero, mol);
    let s2 = d.const_app(names.zero_add, &[r, q]);
    let core = chain(d, c, lhs, &[(zero_plus_q, s1), (q, s2)]);

    let expectation_term = d.const_app(expectation, &[r, var, mass, two]);
    let stmt = eqv(d, c, expectation_term, q);
    let ord_ty = rec_ty(d, rn);
    let ty = {
        let over_q = d.pi_fv(q_fv, c.carrier, stmt);
        d.pi_fv(r_fv, ord_ty, over_q)
    };
    let value = {
        let over_q = d.lam_fv(q_fv, c.carrier, core);
        d.lam_fv(r_fv, ord_ty, over_q)
    };
    d.declare_theorem(names.bernoulli_expectation, ty, value)
}

/// `AlgS.OrderedRing.bernoulli_variance : ∀ R q, equiv (variance R
/// (bernoulliVar R) (bernoulliMass R q) 2) (mul q (add one (neg q)))` —
/// `Var[X] = q·(1 − q)`.
///
/// **This is the theorem that says what the record can and cannot do.**
/// `variance` is the CENTRED form `E[(X − μ)²]` with `μ` the expectation
/// term itself, so the proof is in three movements:
///
/// 1. rewrite `μ` to `q` inside both summands, by `negCongr`/`addCongr`/
///    `mulCongr` against [`declare_bernoulli_expectation`] — no
///    `sumRange_congr` is needed because at `n = 2` the sum has already
///    ι-reduced to two named terms;
/// 2. collapse the failure summand `((0 + −q)·(0 + −q))·(1 − q)` to
///    `(q·q)·(1 − q)`, which needs `zero_add`, `neg_mul` (ADR-1616),
///    [`declare_mul_neg`] and `AlgS.neg_neg`;
/// 3. prove `(q·q)·u + (u·u)·q ≃ q·u` where `u := 1 − q`.
///
/// Movement 3 is where the missing `mulComm` would normally stop the
/// argument, and it does not, because the ONE instance of commutativity the
/// identity actually needs is `u·q ≃ q·u` — and both sides expand to
/// `q + −(q·q)` by `distribR`/`distribL` with `mulOneL`/`mulOneR` and the two
/// negation-through-multiplication lemmas. With that in hand: `mulAssoc`
/// twice gives `q·(q·u) + u·(q·u)`, `distribR` factors it to `(q + u)·(q·u)`,
/// `q + u ≃ 1` by `addAssoc`/`addComm`/`negAdd`/`addZero`, and `mulOneL`
/// finishes. No trichotomy, no field inverse, no commutative ring.
#[allow(clippy::too_many_lines)]
fn declare_bernoulli_variance(
    d: &mut IntDev<'_>,
    rn: &RecordNames,
    names: &BinomialSNames,
    variance: NameId,
    expectation: NameId,
    neg_mul: NameId,
    algs_neg_neg: NameId,
    to_ring_s: NameId,
) -> Result<(), KernelError> {
    let r_fv = d.fresh_fvar();
    let r = d.kernel().fvar(r_fv);
    let c = proj(d, rn, r);
    let ring_r = d.const_app(to_ring_s, &[r]);
    let q_fv = d.fresh_fvar();
    let q = d.kernel().fvar(q_fv);

    let two = d.num(2);
    let var = bvar(d, names, r);
    let mass = bmass(d, names, r, q);
    let mu = d.const_app(expectation, &[r, var, mass, two]);
    let hmu = d.const_app(names.bernoulli_expectation, &[r, q]);

    let nq = rneg(d, c, q);
    let u = radd(d, c, c.one, nq);
    let nmu = rneg(d, c, mu);

    // --- movement 1: mu ~> q inside both centred factors -------------------
    let d0 = radd(d, c, c.zero, nmu);
    let d0p = radd(d, c, c.zero, nq);
    let d1 = radd(d, c, c.one, nmu);
    let d1p = u;

    let hnm = ncongr(d, c, mu, q, hmu);
    let refl_zero = refl(d, c, c.zero);
    let refl_one = refl(d, c, c.one);
    let hd0 = acongr(d, c, c.zero, c.zero, nmu, nq, refl_zero, hnm);
    let hd1 = acongr(d, c, c.one, c.one, nmu, nq, refl_one, hnm);

    let sq0 = rmul(d, c, d0, d0);
    let sq0p = rmul(d, c, d0p, d0p);
    let sq1 = rmul(d, c, d1, d1);
    let sq1p = rmul(d, c, d1p, d1p);
    let t0 = rmul(d, c, sq0, u);
    let t0p = rmul(d, c, sq0p, u);
    let t1 = rmul(d, c, sq1, q);
    let t1p = rmul(d, c, sq1p, q);

    let refl_u = refl(d, c, u);
    let refl_q = refl(d, c, q);
    let hsq0 = mcongr(d, c, d0, d0p, d0, d0p, hd0, hd0);
    let hsq1 = mcongr(d, c, d1, d1p, d1, d1p, hd1, hd1);
    let ht0 = mcongr(d, c, sq0, sq0p, u, u, hsq0, refl_u);
    let ht1 = mcongr(d, c, sq1, sq1p, q, q, hsq1, refl_q);

    let head = radd(d, c, c.zero, t0);
    let headp = radd(d, c, c.zero, t0p);
    let lhs = radd(d, c, head, t1);
    let lhs1 = radd(d, c, headp, t1p);
    let hhead = acongr(d, c, c.zero, c.zero, t0, t0p, refl_zero, ht0);
    let step1 = acongr(d, c, head, headp, t1, t1p, hhead, ht1);

    // --- movement 2: (0 + -q)^2 * u  ~>  (q*q) * u -------------------------
    let qq = rmul(d, c, q, q);
    let nqq = rneg(d, c, qq);
    let q_nq = rmul(d, c, q, nq);
    let nq_nq = rmul(d, c, nq, nq);
    let n_q_nq = rneg(d, c, q_nq);
    let n_nqq = rneg(d, c, nqq);
    let t0pp = rmul(d, c, qq, u);
    let headpp = radd(d, c, c.zero, t0pp);
    let lhs2 = radd(d, c, headpp, t1p);

    let hz = d.const_app(names.zero_add, &[r, nq]);
    let hsq0p = mcongr(d, c, d0p, nq, d0p, nq, hz, hz);
    // (-q)*(-q) ~ -(q*(-q)) ~ -(-(q*q)) ~ q*q
    let e1 = d.const_app(neg_mul, &[r, q, nq]);
    let e2 = d.const_app(names.mul_neg, &[r, q, q]);
    let e3 = ncongr(d, c, q_nq, nqq, e2);
    let e4 = d.const_app(algs_neg_neg, &[ring_r, qq]);
    let hneg_sq = chain(d, c, nq_nq, &[(n_q_nq, e1), (n_nqq, e3), (qq, e4)]);
    let hsq0_full = trans(d, c, sq0p, nq_nq, qq, hsq0p, hneg_sq);
    let step2 = {
        let inner = mcongr(d, c, sq0p, qq, u, u, hsq0_full, refl_u);
        let refl_t1p = refl(d, c, t1p);
        let hh = acongr(d, c, c.zero, c.zero, t0p, t0pp, refl_zero, inner);
        acongr(d, c, headp, headpp, t1p, t1p, hh, refl_t1p)
    };

    // strip the leading `zero +`
    let lhs3 = radd(d, c, t0pp, t1p);
    let step3 = {
        let za = d.const_app(names.zero_add, &[r, t0pp]);
        let refl_t1p = refl(d, c, t1p);
        acongr(d, c, headpp, t0pp, t1p, t1p, za, refl_t1p)
    };

    // --- movement 3: (q*q)*u + (u*u)*q ~ q*u -------------------------------
    let qu = rmul(d, c, q, u);
    let uq = rmul(d, c, u, q);
    let q_plus_nqq = radd(d, c, q, nqq);

    // hcomm : u*q ~ q*u, both sides expanding to q + -(q*q).
    let hcomm = {
        // u*q = (1 + -q)*q ~ 1*q + (-q)*q ~ q + -(q*q)
        let one_q = rmul(d, c, c.one, q);
        let nq_q = rmul(d, c, nq, q);
        let l1 = d.apply(c.distrib_r, &[c.one, nq, q]);
        let sum_l = radd(d, c, one_q, nq_q);
        let mol = d.apply(c.mul_one_l, &[q]);
        let nm = d.const_app(neg_mul, &[r, q, q]);
        let l2 = acongr(d, c, one_q, q, nq_q, nqq, mol, nm);
        let left = trans(d, c, uq, sum_l, q_plus_nqq, l1, l2);

        // q*u = q*(1 + -q) ~ q*1 + q*(-q) ~ q + -(q*q)
        let q_one = rmul(d, c, q, c.one);
        let r1 = d.apply(c.distrib_l, &[q, c.one, nq]);
        let sum_r = radd(d, c, q_one, q_nq);
        let mor = d.apply(c.mul_one_r, &[q]);
        let mn = d.const_app(names.mul_neg, &[r, q, q]);
        let r2 = acongr(d, c, q_one, q, q_nq, nqq, mor, mn);
        let right = trans(d, c, qu, sum_r, q_plus_nqq, r1, r2);
        let right_s = symm(d, c, qu, q_plus_nqq, right);
        trans(d, c, uq, q_plus_nqq, qu, left, right_s)
    };

    let q_qu = rmul(d, c, q, qu);
    let u_uq = rmul(d, c, u, uq);
    let u_qu = rmul(d, c, u, qu);
    let q_plus_u = radd(d, c, q, u);
    let qu_uq = rmul(d, c, q_plus_u, qu);
    let one_qu = rmul(d, c, c.one, qu);
    let lhs4 = radd(d, c, q_qu, u_qu);

    let a1 = d.apply(c.mul_assoc, &[q, q, u]); // (q*q)*u ~ q*(q*u)
    let a2 = d.apply(c.mul_assoc, &[u, u, q]); // (u*u)*q ~ u*(u*q)
    let a3 = mcongr(d, c, u, u, uq, qu, refl_u, hcomm); // u*(u*q) ~ u*(q*u)
    let a23 = trans(d, c, t1p, u_uq, u_qu, a2, a3);
    let step4 = acongr(d, c, t0pp, q_qu, t1p, u_qu, a1, a23);

    let step5 = {
        let dr = d.apply(c.distrib_r, &[q, u, qu]); // (q+u)*(q*u) ~ q*(q*u) + u*(q*u)
        symm(d, c, qu_uq, lhs4, dr)
    };

    // q + u ~ one
    let hqu1 = {
        let q_one = radd(d, c, q, c.one);
        let one_q = radd(d, c, c.one, q);
        let q_one_nq = radd(d, c, q_one, nq);
        let one_q_nq = radd(d, c, one_q, nq);
        let q_nq_add = radd(d, c, q, nq);
        let one_inner = radd(d, c, c.one, q_nq_add);
        let one_zero = radd(d, c, c.one, c.zero);

        let s1 = {
            let assoc = d.apply(c.add_assoc, &[q, c.one, nq]);
            symm(d, c, q_one_nq, q_plus_u, assoc)
        };
        let s2 = {
            let comm = d.apply(c.add_comm, &[q, c.one]);
            let refl_nq = refl(d, c, nq);
            acongr(d, c, q_one, one_q, nq, nq, comm, refl_nq)
        };
        let s3 = d.apply(c.add_assoc, &[c.one, q, nq]);
        let s4 = {
            let na = d.apply(c.neg_add, &[q]);
            acongr(d, c, c.one, c.one, q_nq_add, c.zero, refl_one, na)
        };
        let s5 = d.apply(c.add_zero, &[c.one]);
        chain(
            d,
            c,
            q_plus_u,
            &[
                (q_one_nq, s1),
                (one_q_nq, s2),
                (one_inner, s3),
                (one_zero, s4),
                (c.one, s5),
            ],
        )
    };
    let refl_qu = refl(d, c, qu);
    let step6 = mcongr(d, c, q_plus_u, c.one, qu, qu, hqu1, refl_qu);
    let step7 = d.apply(c.mul_one_l, &[qu]);

    let core = chain(
        d,
        c,
        lhs,
        &[
            (lhs1, step1),
            (lhs2, step2),
            (lhs3, step3),
            (lhs4, step4),
            (qu_uq, step5),
            (one_qu, step6),
            (qu, step7),
        ],
    );

    let variance_term = d.const_app(variance, &[r, var, mass, two]);
    let stmt = eqv(d, c, variance_term, qu);
    let ord_ty = rec_ty(d, rn);
    let ty = {
        let over_q = d.pi_fv(q_fv, c.carrier, stmt);
        d.pi_fv(r_fv, ord_ty, over_q)
    };
    let value = {
        let over_q = d.lam_fv(q_fv, c.carrier, core);
        d.lam_fv(r_fv, ord_ty, over_q)
    };
    d.declare_theorem(names.bernoulli_variance, ty, value)
}

// ---------------------------------------------------------------------------
// Assembly.
// ---------------------------------------------------------------------------

/// Declare the generic Bernoulli layer.
///
/// # Errors
///
/// Returns the trusted gate's rejection — an `Err` means the kernel
/// **refused** a proof, not that a script gave up.
pub(crate) fn declare_binomial_s_all(
    d: &mut IntDev<'_>,
    p: &RatPrelude,
) -> Result<(), KernelError> {
    let st = p.int.nat.structures_s;
    let rn = st.ordered_ring;
    let extra = p.int.nat.structures_s_extra;
    let prob = p.probability_s;
    let names = p.binomial_s;

    declare_mul_neg(d, &rn, &names, prob.to_ring_s, extra.mul_neg_one)?;
    declare_zero_add(d, &rn, &names)?;
    declare_bernoulli_var(d, &rn, &names)?;
    declare_bernoulli_mass(d, &rn, &names)?;
    declare_bernoulli_mass_nonneg(d, &rn, &names, prob.sub_nonneg_of_le)?;
    declare_bernoulli_is_distribution(d, &rn, &names, prob.is_distribution, prob.sum_range)?;
    declare_bernoulli_expectation(d, &rn, &names, prob.expectation, prob.zero_mul)?;
    declare_bernoulli_variance(
        d,
        &rn,
        &names,
        prob.variance,
        prob.expectation,
        prob.neg_mul,
        extra.neg_neg,
        prob.to_ring_s,
    )?;
    Ok(())
}
