# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum._native import kernel
import builtins
__all__ = [
    "canonical_alpha_expression_sha256",
    "canonical_declaration_sha256",
    "canonical_expression_sha256",
    "canonical_kernel_type_shape_sha256",
    "canonical_level_sha256",
]

def canonical_alpha_expression_sha256(kernel: kernel.Kernel, expression: kernel.ExprId) -> builtins.str:
    r"""
    An expression identity that ignores cosmetic binder names, so expressions
    from independently constructed kernels can be compared for alpha
    equivalence.
    
    # Errors
    
    Raises `EpochError` for a foreign handle and `AxeyumError` if the expression
    DAG cannot be hashed completely.
    """

def canonical_declaration_sha256(kernel: kernel.Kernel, name: builtins.str  |  kernel.NameId) -> builtins.str:
    r"""
    The canonical arena-independent SHA-256 identity of one declaration.
    
    # Errors
    
    Raises `EpochError` for a foreign handle, `KeyError` if the name is not
    declared, and `AxeyumError` if the declaration cannot be hashed completely.
    """

def canonical_expression_sha256(kernel: kernel.Kernel, expression: kernel.ExprId) -> builtins.str:
    r"""
    The canonical arena-independent SHA-256 identity of one expression.
    
    # Errors
    
    Raises `EpochError` for a foreign handle and `AxeyumError` if the expression
    DAG cannot be hashed completely.
    """

def canonical_kernel_type_shape_sha256(kernel: kernel.Kernel, expression: kernel.ExprId) -> builtins.str:
    r"""
    A conservative cross-kernel *type shape* identity.
    
    It ignores binder names, binder info and universe-parameter spelling, and it
    does **not** unfold definitions. Equality is evidence of that narrow
    structural compatibility only — never general definitional equality, and
    never authority to reuse a declaration.
    
    # Errors
    
    Raises `EpochError` for a foreign handle and `AxeyumError` if the expression
    DAG cannot be hashed completely.
    """

def canonical_level_sha256(kernel: kernel.Kernel, level: kernel.LevelId) -> builtins.str:
    r"""
    The canonical arena-independent SHA-256 identity of one universe level.
    
    # Errors
    
    Raises `EpochError` for a foreign handle.
    """

