# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `axeyum._native`. Regenerate with
#     uv run --no-sync maturin develop
#     uv run --no-sync python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.

from typing import Any

class Outcome:
    """The result of deciding one SMT-LIB script."""

    detail: Any
    expected_status: Any
    logic: Any
    model: Any
    status: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __repr__(self) -> Any: ...
    def replay(self) -> Any: ...

class Response:
    """One response to one SMT-LIB output command."""

    command: Any
    kind: Any
    status: Any
    text: Any
    values: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __repr__(self) -> Any: ...

class Script:
    """A parsed SMT-LIB script, together with the arena it owns."""

    check_sats: Any
    commands: Any
    expected_status: Any
    logic: Any
    model_symbols: Any
    uses_bounded_strings: Any
    word_only_fallback: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __repr__(self) -> Any: ...
    def flat_view(self) -> Any: ...
    def render(self, term: Any) -> Any: ...

class ScriptTerm:
    """A term inside a parsed [`Script`](axeyum.smt.Script)."""

    epoch: Any
    raw: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __eq__(self, value: Any, /) -> Any: ...
    def __ge__(self, value: Any, /) -> Any: ...
    def __gt__(self, value: Any, /) -> Any: ...
    def __hash__(self) -> Any: ...
    def __le__(self, value: Any, /) -> Any: ...
    def __lt__(self, value: Any, /) -> Any: ...
    def __ne__(self, value: Any, /) -> Any: ...
    def __repr__(self) -> Any: ...

def get_assignment(script: Any, *, timeout_ms: Any = 10000) -> Any: ...
def get_proof(script: Any, *, timeout_ms: Any = 10000) -> Any: ...
def get_value(script: Any, *, timeout_ms: Any = 10000) -> Any: ...
def incremental(script: Any, *, timeout_ms: Any = 10000) -> Any: ...
def parse(script: Any, *, timeout_ms: Any = None) -> Any: ...
def session(script: Any, *, timeout_ms: Any = 10000) -> Any: ...
def solve(
    script: Any,
    *,
    timeout_ms: Any = 10000,
    resource_limit: Any = None,
    memory_limit_mb: Any = None,
    node_budget: Any = None,
    cnf_variable_budget: Any = None,
    cnf_clause_budget: Any = None,
    prove_unsat: Any = False,
    preprocess: Any = True,
) -> Any: ...
def unsat_core(script: Any, *, timeout_ms: Any = 10000) -> Any: ...
def write_script(arena: Any, assertions: Any) -> Any: ...
