# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `axeyum._native`. Regenerate with
#     uv run --no-sync maturin develop
#     uv run --no-sync python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.

from typing import Any

class Outcome:
    """The result of deciding one SMT-LIB script."""

    detail: Any
    expected_status: Any
    logic: Any
    model: Any
    status: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __repr__(self) -> Any: ...
    def replay(self) -> Any: ...

def solve(script: Any, *, timeout_ms: Any = 10000) -> Any: ...
