#!/usr/bin/env python3
"""Wire the L0 S6 two-phase-commit engine (`scripts/credit-transaction.py`,
ADR-0785) into the REAL fact ledger under `artifacts/facts/`.

ADR-0785 built and mutation-verified a two-phase-commit engine over a
SELF-CONTAINED FIXTURE ledger, deliberately not wired into `artifacts/facts/`
because that touches `scripts/validate-facts.py` and the real pins file,
owned elsewhere. This module is that wiring, per ADR-0810.

WHAT THIS DOES NOT MODIFY
-------------------------

`scripts/credit-transaction.py` is loaded as-is and reused for everything
generic: the fault-injectable IO primitives (`io_write_new_file`,
`io_replace`), the `Journal`/`WriteOp`/`Inputs` dataclasses, the
applied-transaction registry, `_verify_staged_integrity`, and the four
staleness exception classes. Only the FIXTURE-SPECIFIC orchestration
(`propose_transaction`/`commit`/`apply`/`recover`/`run_transaction`, which
hardcode fixture paths like `facts/<id>.json` and `graph/graph.json`) is
reimplemented here against the real paths. `scripts/validate-facts.py`,
`scripts/check-settled-fact-statements.py`, and `scripts/gen-safety-matrix.py`
are loaded and their existing pure functions reused directly (`validate_one`,
`read_pins`/`rewrite`, `build_fanout`/`classify`/`render_tsv`/
`render_summary`/`run_controls`) -- never reimplemented -- so this wrapper
cannot drift from what those gates actually enforce.

MEASURED REAL WRITE SET (see docs/plan/status/s6-wire-real-ledger.md and
ADR-0810 for the full measurement)
-------------------------------------------------------------------------

Flipping a fact to `proved` today, covered ATOMICALLY by this transaction:

  1. `artifacts/facts/<id>.json`                        -- the fact itself
  2. `artifacts/ontology/settled-fact-statement-pins.json` -- full rebuild,
     via `check-settled-fact-statements.py`'s own `rewrite()`
  3. `artifacts/safety-matrix/safety-matrix.tsv`         -- full rebuild
  4. `artifacts/safety-matrix/safety-matrix-summary.md`  -- full rebuild,
     via `gen-safety-matrix.py`'s own `render_tsv`/`render_summary`, gated by
     its own `run_controls`

Plus this wrapper's own receipt pointer
(`artifacts/.credit-txn/receipts/latest/<id>.sha256`), mirroring the fixture.

NOT covered, named explicitly (CLAUDE.md: "a boundary you skipped and did not
name is the defect this whole phase exists to prevent"):

  - `artifacts/ledger-coverage.json` (`gen-ledger-coverage.py`) invokes
    `cargo run --release -p axeyum-lean-kernel` -- a multi-minute kernel
    build/run. Folding a cargo invocation into a per-fact file transaction
    is a different kind of operation (a measurement, not a write) and would
    make every single fact flip pay a kernel rebuild. Regenerate it
    separately; it is not fact-specific durable ledger state in the sense
    this transaction protects.
  - `artifacts/product-health-v1.json` / `docs/plan/generated/product-health.md`
    (`gen-product-health.py`) depend on unrelated global state (the latest CI
    runtime receipt, autogenesis operation/outcome artifacts, `justfile`/
    `check.sh` content) that has nothing to do with THIS fact. Wiring it in
    would make the transaction fail for reasons unrelated to the fact being
    flipped, and it is a whole-repo health snapshot, not a per-fact dashboard.
  - `PLAN.md` / the ADR index are regenerated by their own `gen-*.py --check`
    scripts on a different cadence (session end), not per fact.

THE "RECEIPT" IN THIS WIRING
-----------------------------

ADR-0717's `theorem-credit` receipt schema (S0-S5) has not landed yet, so
there is no separate receipt artifact to hash. This wrapper treats the
proposed NEW fact's own canonical JSON bytes as the receipt: the caller
already decided the fact's evidence/status content (that is the job of the
checkers this repository's ledger already runs), and this module's only job
is to commit that decision, the pins rebuild, and the safety-matrix rebuild
atomically. When a real receipt schema lands, swap `receipt_bytes` for it;
nothing else in this file's staleness model needs to change.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import shutil
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve().parent
ROOT = _HERE.parent
FACTS = ROOT / "artifacts" / "facts"
TXN_ROOT = ROOT / "artifacts" / ".credit-txn"


def _load(name: str, relpath: str):
    spec = importlib.util.spec_from_file_location(name, _HERE / relpath)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


# Loaded ONCE, at module scope, exactly like check-credit-transaction.py loads
# `credit-transaction.py`: every function below shares these instances, so
# `_LAST_STAGED_JOURNAL`-shaped state (if any of these ever grow it) is not
# silently duplicated across separate importlib loads.
ct = _load("credit_transaction", "credit-transaction.py")
vf = _load("validate_facts_for_ledger_txn", "validate-facts.py")
csfs = _load("check_settled_fact_statements_for_ledger_txn", "check-settled-fact-statements.py")
gsm = _load("gen_safety_matrix_for_ledger_txn", "gen-safety-matrix.py")


class LedgerCascadeError(Exception):
    """The proposed fact content, or its derived cascade, was rejected by one
    of the REAL gates this wrapper reuses (validate-facts.py's validate_one,
    check-settled-fact-statements.py's anti-laundering rewrite() refusal, or
    gen-safety-matrix.py's run_controls). Distinct from the four staleness
    exceptions: this is a REJECTION OF CONTENT, raised at propose() time,
    never a race with a concurrent writer."""


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
def _fact_path(fact_id: str) -> Path:
    return FACTS / (fact_id.replace("F:", "F-") + ".json")


def _relpath(p: Path) -> str:
    return str(p.relative_to(ROOT))


def _receipt_pointer_path(fact_id: str) -> Path:
    return TXN_ROOT / "receipts" / "latest" / (fact_id.replace("F:", "F-") + ".sha256")


def _read_receipt_pointer(fact_id: str) -> str:
    p = _receipt_pointer_path(fact_id)
    if not p.exists():
        return ct.hash_bytes(b"")
    return p.read_text().strip()


# ---------------------------------------------------------------------------
# Staleness dimension 3: "graph" -- the dependency-derived cascade input.
# There is no single `graph.json` for the real ledger (each fact carries its
# own `depends_on`); the two things that actually FEED the cascade this
# transaction rebuilds are (a) which fact ids are currently settled, and
# (b) the current pins manifest. A concurrent lane settling ANOTHER fact, or
# amending the pins manifest, while this transaction is in flight is exactly
# the race this dimension exists to catch.
# ---------------------------------------------------------------------------
def _graph_fingerprint() -> str:
    settled_ids = []
    for p in sorted(FACTS.glob("*.json")):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if data.get("epistemic_status") in csfs.SETTLED:
            settled_ids.append(data.get("id", ""))
    settled_bytes = "\n".join(sorted(settled_ids)).encode()
    pins_bytes = csfs.PINS.read_bytes() if csfs.PINS.exists() else b""
    return ct.hash_bytes(settled_bytes + b"\0" + pins_bytes)


# ---------------------------------------------------------------------------
# Staleness dimension 4: "checker" -- hash the actual checker/generator
# sources this wrapper depends on (plus itself), rather than a hand-maintained
# version string that someone has to remember to bump. A source edit to any
# of these between propose() and commit() means the transaction was staged
# against logic that no longer exists.
# ---------------------------------------------------------------------------
_CHECKER_SOURCES = (
    "validate-facts.py",
    "check-settled-fact-statements.py",
    "gen-safety-matrix.py",
    "credit-transaction-ledger.py",
)


def compute_checker_version() -> str:
    h = hashlib.sha256()
    for name in _CHECKER_SOURCES:
        h.update(name.encode())
        h.update(b"\0")
        h.update((_HERE / name).read_bytes())
    return "credit-transaction-ledger/" + h.hexdigest()[:16]


# ---------------------------------------------------------------------------
# Cascade computation. Everything here is a PURE function of on-disk state at
# call time plus the caller's proposed new fact -- it writes nothing durable.
# Reuses the real gates' own functions rather than re-deriving their logic.
# ---------------------------------------------------------------------------
def _settled_entry(data: dict) -> dict | None:
    """Mirrors check-settled-fact-statements.py's read_facts() per-entry
    computation exactly (same digest(), HEADER, SETTLED), but operating on an
    in-memory fact dict instead of re-reading a file, so it can be applied to
    the PROPOSED post-flip fact without writing it to disk first."""
    if data.get("epistemic_status") not in csfs.SETTLED:
        return None
    formal = data.get("formal") or {}
    statement = formal.get("statement")
    if statement is None:
        return None
    header = csfs.HEADER.match(statement) if isinstance(statement, str) else None
    return {
        "language": formal.get("language"),
        "statement_sha256": csfs.digest(statement),
        "prose_sha256": csfs.digest(data.get("statement")),
        "kernel_theorem": formal.get("kernel_theorem"),
        "header_name": header.group(2) if header else None,
    }


def _compute_new_pins_bytes(current: dict, scratch_dir: Path) -> bytes:
    """Calls check-settled-fact-statements.py's OWN rewrite() unmodified,
    redirected at a scratch copy of the real pins file so nothing durable is
    touched here. Reuses rewrite()'s own anti-laundering refusal (ADR-0763):
    if it refuses (unamended drift), this raises rather than silently
    proceeding."""
    pins, amendments, _floors = csfs.read_pins()
    scratch_pins = scratch_dir / "pins-scratch.json"
    scratch_pins.write_text(csfs.PINS.read_text(encoding="utf-8"), encoding="utf-8")
    original_pins_path = csfs.PINS
    csfs.PINS = scratch_pins
    try:
        rc = csfs.rewrite(current, pins, amendments)
    finally:
        csfs.PINS = original_pins_path
    if rc != 0:
        raise LedgerCascadeError(
            "check-settled-fact-statements.py rewrite() refused the proposed "
            "state (see stderr above) -- likely unamended statement drift"
        )
    return scratch_pins.read_bytes()


def _compute_safety_matrix_bytes(all_facts_after: list[dict], new_pins_bytes: bytes) -> tuple[bytes, bytes]:
    """Calls gen-safety-matrix.py's OWN classify/render/run_controls
    unmodified, against the proposed post-flip fact list and the proposed
    (not-yet-written) new pins bytes."""
    proved = [f for f in all_facts_after if f.get("epistemic_status") in gsm.SETTLED]
    if not proved:
        raise LedgerCascadeError("safety-matrix cascade: no proved facts in proposed state")
    fan = gsm.build_fanout(proved)
    pinned = {row["fact_id"] for row in json.loads(new_pins_bytes).get("pins", []) if "fact_id" in row}
    if not pinned:
        raise LedgerCascadeError("safety-matrix cascade: proposed pins manifest carries no pins")
    rows = [gsm.classify(f, pinned, fan) for f in proved]
    by_id = {r["id"]: r for r in rows}
    if len(by_id) != len(rows):
        raise LedgerCascadeError("safety-matrix cascade: duplicate fact id in proposed census")
    unsettled = {
        f["id"] for f in all_facts_after
        if f.get("epistemic_status") not in gsm.SETTLED | {"computed"}
    }
    failures = gsm.run_controls(by_id, pinned, unsettled)
    if failures:
        raise LedgerCascadeError(
            "safety-matrix cascade controls failed: " + "; ".join(failures)
        )
    tsv = gsm.render_tsv(rows)
    summary = gsm.render_summary(rows, fan, all_facts_after)
    return tsv.encode(), summary.encode()


def compute_cascade(fact_id: str, new_fact: dict) -> dict[str, bytes]:
    """Returns {relpath: desired new bytes} for every target this
    transaction covers. Raises LedgerCascadeError if the proposal is rejected
    by validate-facts.py, the pins rewrite, or the safety-matrix controls."""
    fact_path = _fact_path(fact_id)
    if not fact_path.is_file():
        raise LedgerCascadeError(f"fact does not exist on disk: {fact_path}")
    if new_fact.get("id") != fact_id:
        raise LedgerCascadeError("proposed fact's id does not match the target fact_id")

    all_facts: list[dict] = []
    known_ids: set[str] = set()
    for p in sorted(FACTS.glob("*.json")):
        data = json.loads(p.read_text(encoding="utf-8"))
        known_ids.add(data.get("id", ""))
        all_facts.append(data if data.get("id") != fact_id else new_fact)

    errors = vf.validate_one(fact_path, new_fact, known_ids)
    if errors:
        raise LedgerCascadeError(
            "validate-facts.py rejects the proposed fact: " + "; ".join(errors)
        )

    current = {}
    for data in all_facts:
        entry = _settled_entry(data)
        if entry is not None:
            current[data["id"]] = entry

    with tempfile.TemporaryDirectory(prefix="credit-txn-ledger-cascade-") as scratch:
        new_pins_bytes = _compute_new_pins_bytes(current, Path(scratch))

    new_matrix_tsv, new_matrix_md = _compute_safety_matrix_bytes(all_facts, new_pins_bytes)
    new_fact_bytes = (json.dumps(new_fact, indent=2, sort_keys=True) + "\n").encode()

    return {
        _relpath(fact_path): new_fact_bytes,
        _relpath(csfs.PINS): new_pins_bytes,
        _relpath(gsm.MATRIX_TSV): new_matrix_tsv,
        _relpath(gsm.SUMMARY_MD): new_matrix_md,
    }


# ---------------------------------------------------------------------------
# Two-phase commit over the REAL paths. Reuses ct's generic primitives;
# reimplements only the path-specific orchestration (GUARD comments mark
# every check this module owns and mutation-verifies -- see
# scripts/tests/test-credit-transaction-ledger-mutations.sh).
# ---------------------------------------------------------------------------
def propose(fact_id: str, new_fact: dict):
    cascade_targets = compute_cascade(fact_id, new_fact)  # GUARD: content rejection (validate_one, rewrite refusal, run_controls)

    receipt_bytes = (json.dumps(new_fact, indent=2, sort_keys=True) + "\n").encode()
    cascade_targets[_relpath(_receipt_pointer_path(fact_id))] = ct.hash_bytes(receipt_bytes).encode()

    inputs = ct.Inputs(
        receipt_sha256=ct.hash_bytes(receipt_bytes),
        receipt_pointer_sha256=_read_receipt_pointer(fact_id),
        source_sha256=ct.hash_file(_fact_path(fact_id)),
        graph_sha256=_graph_fingerprint(),
        checker_version=compute_checker_version(),
    )

    txn_id = f"ledger-txn-{inputs.receipt_sha256[:12]}-{time.time_ns()}"
    txn_dir = TXN_ROOT / "_txn" / txn_id
    staged_dir = txn_dir / "staged"

    writes = []
    for relpath in sorted(cascade_targets):
        data = cascade_targets[relpath]
        staged_name = relpath.replace("/", "__")
        ct.io_write_new_file(staged_dir / staged_name, data, label=f"stage:{relpath}")
        writes.append(ct.WriteOp(relpath=relpath, staged_name=staged_name, sha256=ct.hash_bytes(data)))

    journal = ct.Journal(txn_id=txn_id, fact_id=fact_id, status="prepared", inputs=inputs, writes=writes)
    ct._write_journal(txn_dir, journal, label="journal-prepared")
    return txn_id, txn_dir


def commit(txn_dir: Path):
    journal = ct._load_journal_fresh(txn_dir)
    if journal.status != "prepared":  # GUARD: commit status precondition
        raise ct.TransactionStateError(
            f"cannot commit txn {journal.txn_id}: status is {journal.status!r}, expected 'prepared'"
        )
    current_receipt_ptr = _read_receipt_pointer(journal.fact_id)
    if current_receipt_ptr != journal.inputs.receipt_pointer_sha256:  # GUARD: stale receipt
        raise ct.StaleReceiptError(
            f"stale receipt: authoritative receipt for {journal.fact_id} is now "
            f"{current_receipt_ptr[:12]}, this transaction staged against "
            f"{journal.inputs.receipt_pointer_sha256[:12]}"
        )
    current_source = ct.hash_file(_fact_path(journal.fact_id))
    if current_source != journal.inputs.source_sha256:  # GUARD: stale source
        raise ct.StaleSourceError(
            f"stale source: {_fact_path(journal.fact_id)} changed on disk since staging "
            f"(staged against {journal.inputs.source_sha256[:12]}, now {current_source[:12]})"
        )
    current_graph = _graph_fingerprint()
    if current_graph != journal.inputs.graph_sha256:  # GUARD: stale graph
        raise ct.StaleGraphError(
            "stale graph: settled-fact-id-set or pins manifest changed since staging "
            f"(staged against {journal.inputs.graph_sha256[:12]}, now {current_graph[:12]})"
        )
    current_checker = compute_checker_version()
    if current_checker != journal.inputs.checker_version:  # GUARD: stale checker
        raise ct.StaleCheckerError(
            f"stale checker: transaction staged against {journal.inputs.checker_version!r}, "
            f"running checker is {current_checker!r}"
        )
    journal.status = "committed"
    ct._write_journal(txn_dir, journal, label="journal-committed")
    return journal


def apply(txn_dir: Path):
    journal = ct._load_journal_fresh(txn_dir)
    if journal.status not in ("committed", "applied"):  # GUARD: apply status precondition
        raise ct.TransactionStateError(
            f"cannot apply txn {journal.txn_id}: status is {journal.status!r}, "
            "expected 'committed' or 'applied' -- commit() must run first"
        )
    ordered = sorted(journal.writes, key=lambda w: w.relpath)
    pending = [w for w in ordered if ct.hash_file(ROOT / w.relpath) != w.sha256]
    ct._verify_staged_integrity(txn_dir, pending)  # GUARD: corrupt staging (reused from credit_transaction)

    for w in pending:
        target = ROOT / w.relpath
        staged = txn_dir / "staged" / w.staged_name
        ct.io_replace(staged, target, label=f"apply:{w.relpath}")

    registry = ct.load_applied_registry(TXN_ROOT)
    registry[journal.fact_id] = journal.inputs.receipt_sha256
    ct._write_applied_registry(TXN_ROOT, registry)

    if journal.status != "applied":
        journal.status = "applied"
        ct._write_journal(txn_dir, journal, label="journal-applied")
    return journal


def recover():
    txn_root = TXN_ROOT / "_txn"
    actions: list[str] = []
    if not txn_root.exists():
        return actions
    for entry in sorted(txn_root.iterdir()):
        if not entry.is_dir():
            continue
        journal_path = entry / "journal.json"
        if not journal_path.exists():
            shutil.rmtree(entry, ignore_errors=True)
            actions.append(f"rollback (no journal written): {entry.name}")
            continue
        try:
            journal = ct._load_journal_fresh(entry)
        except Exception:
            shutil.rmtree(entry, ignore_errors=True)
            actions.append(f"rollback (unreadable journal): {entry.name}")
            continue
        if journal.status == "prepared":
            shutil.rmtree(entry, ignore_errors=True)
            actions.append(f"rollback (never committed): {entry.name}")
        elif journal.status in ("committed", "applied"):
            apply(entry)
            actions.append(f"roll-forward (applied): {entry.name}")
        else:
            actions.append(f"UNKNOWN status {journal.status!r}: {entry.name}")
    return actions


def run_ledger_transaction(fact_id: str, new_fact: dict) -> str:
    """End-to-end entry point. Idempotence guard lives HERE, before the
    cascade is even recomputed -- mirrors credit-transaction.py's
    run_transaction()."""
    registry = ct.load_applied_registry(TXN_ROOT)
    receipt_bytes = (json.dumps(new_fact, indent=2, sort_keys=True) + "\n").encode()
    receipt_sha = ct.hash_bytes(receipt_bytes)
    if registry.get(fact_id) == receipt_sha:  # GUARD: idempotent replay
        return "noop-already-applied"
    _, txn_dir = propose(fact_id, new_fact)
    commit(txn_dir)
    apply(txn_dir)
    return "applied"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _cli_main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)

    p_run = sub.add_parser("run", help="propose+commit+apply one fact flip")
    p_run.add_argument("fact_id")
    p_run.add_argument("new_fact_file", type=Path, help="JSON file: the proposed new fact content")

    sub.add_parser("recover", help="reconcile any in-flight transactions under artifacts/.credit-txn")

    args = p.parse_args(argv)
    if args.cmd == "run":
        new_fact = json.loads(args.new_fact_file.read_text(encoding="utf-8"))
        try:
            result = run_ledger_transaction(args.fact_id, new_fact)
        except (LedgerCascadeError, ct.SimulatedCrash, ct.TransactionStateError,
                ct.StaleReceiptError, ct.StaleSourceError, ct.StaleGraphError,
                ct.StaleCheckerError, ct.CorruptStagingError) as error:
            print(f"CREDIT_TXN_LEDGER|ERROR|{type(error).__name__}|{error}", file=sys.stderr)
            return 1
        print(f"CREDIT_TXN_LEDGER|run|fact_id={args.fact_id}|result={result}")
        return 0
    if args.cmd == "recover":
        actions = recover()
        for a in actions:
            print(f"CREDIT_TXN_LEDGER|recover|{a}")
        print(f"CREDIT_TXN_LEDGER|recover|actions={len(actions)}")
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(_cli_main(sys.argv[1:]))
