#!/usr/bin/env python3
"""Generate the L2 phase G3 infrastructure frontier
(docs/plan/graph-directed-library-roadmap-2026-08-30.md, section G3;
ADR-0845).

Reads the L1 phase G2 graph join (`artifacts/graph-join/<population>.
join.json`, ADR-0835) and the declaration graph (`artifacts/declaration-
graph/graph/<population>.{rows,edges}.json`, ADR-0820) -- both out of this
lane's edit scope, read-only inputs -- and a small hand-curated candidate
list in `scripts/lib/infrastructure_frontier.py`, and produces FOUR frozen
queues:

  - language-infrastructure    missing language/definition infrastructure
  - proof-producers            missing reusable proof producers
  - theorem-dominators         high-leverage theorem dominators
  - dependency-ready-leaves    local dependency-ready leaves

Two artifacts:

  - `artifacts/infrastructure-frontier/<population>.frontier.json` -- the
    full structured queues, one row per proposed increment, each carrying a
    stable content-hash `row_id` (survives regeneration: see
    `scripts/lib/infrastructure_frontier.py::row_id`'s docstring), its raw
    evidence, current blockers, destination paths, estimated cost, and a
    PREREGISTERED metric with a re-runnable command.
  - `artifacts/infrastructure-frontier/<population>.dashboard.md` -- the
    human-readable summary.

GRAPH RANK IS ADVISORY (docs/plan/global/50-planning-rules.md): this
artifact is a proposal for humans and coordinators to read, never an
automatic dispatcher. Every row must state what its gain actually IS
(statability, dispatchability, proof, or independent_assurance); a row
whose only argument is its in-population degree does not belong here (the
roadmap's own closing line, and this generator enforces it structurally --
see `validate_candidate`).

Needs no Lean toolchain and no cargo run: every input is already-committed
JSON, plus a plain `/usr/bin/grep` over already-committed source for the
non-authoritative name-coincidence caution notes.

Usage:
    python3 scripts/gen-infrastructure-frontier.py
    python3 scripts/gen-infrastructure-frontier.py --population-id mathlib-group-defs-v1
    python3 scripts/gen-infrastructure-frontier.py --check   # like the gate, but via gen
    python3 scripts/gen-infrastructure-frontier.py --with-dispatch-check
        # also re-runs scripts/check-dispatchable-frontier.py (read-only) and
        # embeds its output in the cross_check section
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts" / "lib"))
import infrastructure_frontier as inf  # noqa: E402

OUT_DIR = REPO_ROOT / "artifacts" / "infrastructure-frontier"
DEFAULT_POPULATION = "mathlib-group-defs-v1"


def run_dispatch_check() -> str | None:
    try:
        proc = subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts" / "check-dispatchable-frontier.py")],
            capture_output=True,
            text=True,
            timeout=120,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None
    return proc.stdout


def render_dashboard(frontier: dict) -> str:
    lines: list[str] = []
    lines.append("# Infrastructure frontier dashboard (L2 phase G3)")
    lines.append("")
    lines.append(f"Generated by `{frontier['generated_by']}`. Do not hand-edit.")
    lines.append("")
    lines.append(
        f"Population: `{frontier['population_id']}` "
        f"({frontier['declaration_population_count']} declarations), joined "
        f"from `{frontier['source_join']}`."
    )
    lines.append("")
    lines.append("> " + frontier["advisory_notice"])
    lines.append("")
    lines.append("> " + frontier["raw_input_disclaimer"])
    lines.append("")

    ps = frontier["population_summary"]
    lines.append("## Population summary")
    lines.append("")
    lines.append("| field | value |")
    lines.append("|---|---:|")
    for k, v in ps.items():
        lines.append(f"| {k} | {v} |")
    lines.append("")

    lines.append("## Cross-check against scripts/check-dispatchable-frontier.py")
    lines.append("")
    cc = frontier["cross_check"]["dispatchable_frontier"]
    if cc.get("ran"):
        lines.append(
            f"Ledger-wide open ml430 mirrors: {cc.get('open_ml430_mirrors')}; "
            f"dispatchable: {cc.get('dispatchable_count')} "
            f"({', '.join(cc.get('dispatchable_examples', [])) or 'none named'})."
        )
    else:
        lines.append(cc.get("note", "Not run this generation."))
    lines.append("")
    lines.append(frontier["cross_check"]["population_overlap_note"])
    lines.append("")

    lines.append("## Queues")
    lines.append("")
    lines.append(
        "| queue | rows | row ids |"
    )
    lines.append("|---|---:|---|")
    for q in inf.QUEUES:
        qd = frontier["queues"][q]
        ids = ", ".join(f"`{r['row_id']}`" for r in qd["rows"]) or "--"
        lines.append(f"| {q} | {len(qd['rows'])} | {ids} |")
    lines.append("")

    for q in inf.QUEUES:
        qd = frontier["queues"][q]
        lines.append(f"### {q}")
        lines.append("")
        if not qd["rows"]:
            lines.append(f"**0 rows.** {qd['empty_reason']}")
            lines.append("")
            continue
        for row in qd["rows"]:
            lines.append(f"#### `{row['row_id']}` -- {row['title']}")
            lines.append("")
            lines.append(f"- subject: {', '.join(f'`{n}`' for n in row['subject_declarations'])}")
            lines.append(f"- gain kind: **{row['gain_kind']}**")
            lines.append(f"- gain: {row['gain_explanation']}")
            lines.append(f"- confidence: {row['confidence']}")
            lines.append("- raw evidence (per subject):")
            for ev in row["evidence"]["per_subject"]:
                lines.append(
                    f"  - `{ev['name']}` kind={ev['kind']} "
                    f"indeg={ev['in_degree_within_population']} "
                    f"outdeg={ev['out_degree_within_population']} "
                    f"fact_id_resolved={ev['fact_id_resolved']} "
                    f"vocab_resolved={ev['statement_vocabulary_resolved']} "
                    f"name_coincidence={ev['is_name_coincidence_candidate']}"
                )
            lines.append("- current blockers:")
            for b in row["current_blockers"]:
                lines.append(f"  - {b}")
            if row["destination_paths"]:
                lines.append(
                    "- destination paths: "
                    + ", ".join(f"`{p}`" for p in row["destination_paths"])
                )
            else:
                lines.append(f"- destination paths: none -- {row['destination_note']}")
            lines.append(
                f"- estimated cost: **{row['estimated_cost']['tier']}** -- "
                f"{row['estimated_cost']['rationale']}"
            )
            pm = row["preregistered_metric"]
            lines.append(f"- preregistered metric: {pm['description']}")
            lines.append(f"  - baseline (measured at generation time): `{pm['baseline']!r}`")
            lines.append(f"  - re-check command: `{pm['command']}`")
            if row["not_this"]:
                lines.append("- not classified elsewhere because:")
                for n in row["not_this"]:
                    lines.append(f"  - {n}")
            lines.append("")

    lines.append("## Diagnostics")
    lines.append("")
    lines.append(frontier["diagnostics"]["note"])
    lines.append("")
    lines.append("| name | in-degree | direct type deps |")
    lines.append("|---|---:|---|")
    for c in frontier["diagnostics"]["dependency_ready_leaf_candidates_before_filtering"]:
        lines.append(
            f"| `{c['name']}` | {c['in_degree_within_population']} | "
            + ", ".join(f"`{d}`" for d in c["direct_type_deps"])
            + " |"
        )
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--population-id", default=DEFAULT_POPULATION)
    ap.add_argument("--out-dir", type=Path, default=OUT_DIR)
    ap.add_argument("--check", action="store_true", help="like the gate: fail if output would change")
    ap.add_argument(
        "--with-dispatch-check",
        action="store_true",
        help="re-run scripts/check-dispatchable-frontier.py (read-only) and embed its output",
    )
    args = ap.parse_args()

    dispatch_output = run_dispatch_check() if args.with_dispatch_check else None

    try:
        frontier = inf.build_frontier(args.population_id, dispatch_output=dispatch_output)
    except ValueError as ex:
        print(f"FAIL: candidate validation: {ex}", file=sys.stderr)
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    json_path = args.out_dir / f"{args.population_id}.frontier.json"
    md_path = args.out_dir / f"{args.population_id}.dashboard.md"

    new_json = json.dumps(frontier, indent=2, sort_keys=False) + "\n"
    new_md = render_dashboard(frontier)

    if args.check:
        ok = True
        if not json_path.is_file() or json_path.read_text(encoding="utf-8") != new_json:
            print(f"FAIL: {json_path} is stale or missing", file=sys.stderr)
            ok = False
        if not md_path.is_file() or md_path.read_text(encoding="utf-8") != new_md:
            print(f"FAIL: {md_path} is stale or missing", file=sys.stderr)
            ok = False
        if not ok:
            return 1
        print(f"OK: {json_path} and {md_path} are up to date")
        return 0

    json_path.write_text(new_json, encoding="utf-8")
    md_path.write_text(new_md, encoding="utf-8")
    print(f"wrote {json_path}")
    print(f"wrote {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
