#!/usr/bin/env python3
"""Generate docs/plan/CATALOG.md: one searchable index of historical planning.

PLAN.md carries only the go-forward queue. Everything that used to compete with
it -- archived lane status files, superseded queues, dated result notes, the
August strand documents -- stays in the tree and is listed here, one row per
file, with its status and date where the file states them. Agents search this
(or `rg` the directories it names) instead of reading old plans end to end.

The catalog is a pure function of the tracked files it indexes, so `--check`
is a gate: a moved, added or retitled file must be followed by a regeneration.
`scripts/gen-plan.py` runs this generator too, so the ordinary
"regenerate PLAN.md" step keeps both current.

Usage:
    python3 scripts/gen-planning-catalog.py          # write
    python3 scripts/gen-planning-catalog.py --check  # exit 1 on drift
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/plan/CATALOG.md"
STATUS_TOKEN = re.compile(r"\(\s*`([A-Za-z][A-Za-z -]*)`\s*,\s*[^,()`]+,\s*(\d{4}-\d{2}-\d{2})")
DATE = re.compile(r"(20\d\d-\d\d-\d\d)")
LINK_TEXT = re.compile(r"\[([^\]]*)\]\([^)]*\)")
DONE_PREFIXES = ("DONE", "LANDED", "COMPLETE", "CLOSED", "MERGED", "DECIDED", "PROVED", "SHIPPED")
STATUS_WORD = re.compile(
    r"\b(DONE|Done|LANDED|Landed|landed|COMPLETE|Complete|completed|merged|closed|"
    r"WIP|PAUSED|Paused|BLOCKED|Blocked|TODO|PARTIAL|Partial)\b"
)


def is_done(status: str) -> bool:
    return status.upper().startswith(DONE_PREFIXES)

# Directories of frozen strand / planning material, indexed below the lanes.
STRAND_DIRS = (
    "docs/mathematics-2026-08",
    "docs/formalized-math-2026-08",
    "docs/refactor-2026-08",
    "docs/python-2026-08",
    "docs/math-department",
    "docs/plan/families",
    "docs/plan/exploration-track",
    "docs/plan/smtcomp-full-library-workstream",
)


def tracked(prefix: str) -> list[Path]:
    try:
        out = subprocess.run(
            ["git", "ls-files", "-z", "--", prefix],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout
        files = [ROOT / p for p in out.split("\0") if p]
    except (OSError, subprocess.CalledProcessError):
        files = list((ROOT / prefix).rglob("*"))
    return sorted(p for p in files if p.suffix == ".md" and p.is_file())


def title_of(text: str, path: Path) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            title = line[2:].strip()
            break
    else:
        title = path.stem
    title = LINK_TEXT.sub(r"\1", title)
    title = re.sub(r"^(Lane|lane)\s*:?\s*", "", title)
    title = title.replace("|", "\\|")
    return title if len(title) <= 140 else title[:137].rstrip() + "..."


def lane_row(path: Path) -> tuple[str, str, str, str]:
    text = path.read_text(encoding="utf-8")
    match = STATUS_TOKEN.search(text[:4000])
    if match:
        status, date = match.group(1).strip().upper(), match.group(2)
    else:
        block = text.split("<!-- plan-section: lane-status -->", 1)[-1][:600]
        found = STATUS_WORD.search(block)
        status = found.group(1).strip().upper() + "?" if found else "-"
        dates = DATE.findall(text[:4000])
        date = max(dates) if dates else ""
    return date, path.stem, status, title_of(text, path)


def doc_row(path: Path) -> tuple[str, str, str]:
    text = path.read_text(encoding="utf-8")
    named = DATE.findall(path.name)
    if named:
        date = named[-1]
    else:
        head = DATE.findall(text[:1500])
        date = max(head) if head else ""
    return date, str(path.relative_to(ROOT)), title_of(text, path)


def link(path_rel: str) -> str:
    return Path(path_rel).relative_to("docs/plan").as_posix() if path_rel.startswith("docs/plan/") \
        else "../../" + path_rel


def render() -> str:
    lanes = [lane_row(p) for p in tracked("docs/plan/archive/lanes")]
    lanes.sort(key=lambda r: (r[0], r[1]), reverse=True)
    open_lanes = [r for r in lanes if not is_done(r[2].rstrip("?"))]

    older_archive = [
        doc_row(p) for p in tracked("docs/plan/archive")
        if "archive/lanes/" not in p.as_posix()
    ]
    notes = [
        doc_row(p) for p in tracked("docs/plan")
        if p.parent == ROOT / "docs/plan" and p.name not in ("README.md", "CATALOG.md")
    ]
    lane_notes = [doc_row(p) for p in tracked("docs/plan/notes")]
    strands = [doc_row(p) for d in STRAND_DIRS for p in tracked(d)]
    loose = [
        doc_row(p) for p in tracked("docs")
        if p.parent == ROOT / "docs" and DATE.search(p.name)
    ]

    out: list[str] = []
    w = out.append
    w("# Planning catalog")
    w("")
    w("<!-- Generated by scripts/gen-planning-catalog.py (also run by scripts/gen-plan.py); do not edit. -->")
    w("")
    w("Everything here is **history or evidence, not the queue**. The live plan is")
    w("[`PLAN.md`](../../PLAN.md); its tracks are in")
    w("[`global/20-next-actions.md`](global/20-next-actions.md). Search instead of reading:")
    w("")
    w("```sh")
    w("rg -n 'QF_LRA' docs/plan/archive/lanes/      # every archived lane that mentions it")
    w("rg -n '<lane-or-topic>' docs/plan/CATALOG.md  # find the file, then open it")
    w("```")
    w("")
    w(f"Counts: {len(lanes)} archived lanes ({len(open_lanes)} not DONE when archived), "
      f"{len(older_archive)} older archive files, {len(notes)} dated plan notes, "
      f"{len(lane_notes)} lane notes, {len(strands) + len(loose)} strand and planning documents.")
    w("")

    def lane_table(rows: list[tuple[str, str, str, str]]) -> None:
        w("| Date | Lane | Status | Title |")
        w("|---|---|---|---|")
        for date, name, status, title in rows:
            w(f"| {date} | [{name}](archive/lanes/{name}.md) | {status} | {title} |")
        w("")

    def doc_table(rows: list[tuple[str, str, str]], sort: bool = True) -> None:
        if sort:
            rows = sorted(rows, key=lambda r: (r[0], r[1]), reverse=True)
        w("| Date | File | Title |")
        w("|---|---|---|")
        for date, rel, title in rows:
            w(f"| {date} | [`{rel}`]({link(rel)}) | {title} |")
        w("")

    w("## Lanes that were not DONE when archived")
    w("")
    w("Archived on 2026-10-05 with the rest; each kept its last next action. A queue")
    w("item that resumes one links it from PLAN.md. A trailing `?` marks a status read from")
    w("the block's prose rather than its status token; `-` means the file states none.")
    w("")
    lane_table(open_lanes)
    w("## Superseded and frozen planning documents")
    w("")
    w("Superseded queues and the strand READMEs carry a banner naming what replaced them.")
    w("")
    doc_table(loose + strands)
    w("## Dated plan notes (`docs/plan/*.md`)")
    w("")
    w("Result notes, designs, handoffs and earlier queues. Evidence for claims; never the queue.")
    w("")
    doc_table(notes)
    w("## Lane overflow notes (`docs/plan/notes/`)")
    w("")
    doc_table(lane_notes)
    w("## Earlier archive (`docs/plan/archive/*.md`, `archive/global-2026-09-17/`)")
    w("")
    doc_table(older_archive)
    w("## All archived lanes, newest first")
    w("")
    lane_table(lanes)
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if args.check:
        if current != rendered:
            print("planning-catalog: STALE -- run `python3 scripts/gen-planning-catalog.py`")
            return 1
        print(f"planning-catalog: OK ({rendered.count(chr(10))} lines)")
        return 0
    if current != rendered:
        OUT.write_text(rendered, encoding="utf-8")
    print(f"planning-catalog: wrote {OUT.relative_to(ROOT)} ({rendered.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
