#!/usr/bin/env python3
"""Generate the tactic-catalog dashboard: one table per tactic, plus the census.

The census line is the part that can go red.  It counts DISTINCT PRECONDITION
SHAPES, never targets, because a registry where every entry names one goal
cannot fail to "cover" it (`docs/autogenesis/228-capsule-lane-retrospective.md`).
Rendering is derived entirely from the catalog; nothing here restates a number a
document already claims.

Stdlib only.  `--check` fails when the committed page is stale.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG = ROOT / "artifacts/autogenesis/tactic-catalog-v1.json"
OUTPUT = ROOT / "docs/plan/generated/tactic-catalog.md"


def escape(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def predicate_line(predicate: dict) -> str:
    args = ", ".join(
        f"{key}={json.dumps(value, ensure_ascii=False)}"
        for key, value in sorted(predicate.get("args", {}).items())
    )
    return f"`{predicate.get('kind')}`({args})"


def render(catalog: dict) -> str:
    tactics = catalog["tactics"]
    shapes = {
        json.dumps(
            sorted(
                json.dumps(predicate, sort_keys=True, ensure_ascii=False)
                for predicate in tactic["precondition"]["structural"]["all_of"]
            ),
            ensure_ascii=False,
        )
        for tactic in tactics
    }
    accepted = sum(len(tactic["reach"]["accepted_goals"]) for tactic in tactics)
    declined = sum(len(tactic["reach"]["declined_goals"]) for tactic in tactics)
    capabilities = sorted({tactic["realizes"] for tactic in tactics})
    kinds = Counter(tactic["kind"] for tactic in tactics)
    techniques = sorted({tactic["uses_technique"]["id"] for tactic in tactics})

    lines = [
        "# Tactic catalog",
        "",
        "Generated by `scripts/gen-tactic-catalog-census.py`; do not edit.",
        "Source: [`artifacts/autogenesis/tactic-catalog-v1.json`](../../../artifacts/autogenesis/tactic-catalog-v1.json),",
        "gated by `scripts/validate-tactic-catalog.py`.",
        "See [`docs/python-2026-08/04-tactic-catalog.md`](../../python-2026-08/04-tactic-catalog.md)",
        "for what an entry means and how reach is updated.",
        "",
        "```",
        "TACTIC_CATALOG|"
        f"tactics={len(tactics)}|"
        f"distinct_precondition_shapes={len(shapes)}|"
        f"accepted_goals={accepted}|"
        f"declined_goals={declined}|"
        f"realizes_capabilities={len(capabilities)}",
        "```",
        "",
        "The census counts distinct precondition SHAPES, not targets. A catalog whose",
        "entries each match one goal shape is a dispatch table, and the validator fails",
        "below two; so does a tactic with zero measured reach rows.",
        "",
        "## Overview",
        "",
        "| Tactic | Kind | Realizes | Technique | Accepted | Declined | Assurance |",
        "|---|---|---|---|---:|---:|---|",
    ]
    for tactic in tactics:
        lines.append(
            f"| `{tactic['id']}` | {tactic['kind']} | `{tactic['realizes']}` |"
            f" `{tactic['uses_technique']['id']}` |"
            f" {len(tactic['reach']['accepted_goals'])} |"
            f" {len(tactic['reach']['declined_goals'])} |"
            f" {tactic['assurance']} |"
        )
    lines += [
        "",
        "| Measure | Value |",
        "|---|---:|",
        f"| Tactics | {len(tactics)} |",
        f"| Distinct precondition shapes | {len(shapes)} |",
        f"| Distinct tactic kinds | {len(kinds)} |",
        f"| Capabilities realized | {len(capabilities)} |",
        f"| External techniques used | {len(techniques)} |",
        f"| Measured accepted goals | {accepted} |",
        f"| Measured declined goals | {declined} |",
        "",
        "## Tactics",
        "",
    ]
    for tactic in tactics:
        budget = ", ".join(
            f"`{name}` = {value}" for name, value in sorted(tactic["budget"].items())
        )
        reasons = ", ".join(f"`{reason}`" for reason in tactic["decline_reasons"])
        primitives = ", ".join(f"`{name}`" for name in tactic["move"]["kernel_primitives"])
        predicates = "<br>".join(
            predicate_line(predicate)
            for predicate in tactic["precondition"]["structural"]["all_of"]
        )
        implemented = tactic["implemented_by"]
        lines += [
            f"### `{tactic['id']}` — {tactic['title']}",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| Kind | {tactic['kind']} |",
            f"| Precondition | {predicates} |",
            f"| Move | {escape(tactic['move']['description'])} |",
            f"| Kernel primitives | {primitives} |",
            f"| Residual | {escape(tactic['residual']['shape'])} |",
            f"| Measure | {escape(tactic['residual']['measure'])} |",
            f"| Budget | {budget} |",
            f"| Declines with | {reasons} |",
            f"| Implemented by | `{implemented['crate']}` :: `{implemented['path']}` :: `{implemented['symbol']}` |",
            f"| Realizes | `{tactic['realizes']}` |",
            # `uses_technique` is an UNRESOLVED CITATION LABEL and carries an
            # `id` and nothing else. ADR-0553 removed its `source` and
            # `revision` fields on 2026-08-24 -- they had made a sibling
            # checkout mandatory for every tactic, the strongest form that
            # coupling took anywhere -- and the schema now pins the shape with
            # `required: ["id"]` and `additionalProperties: false`. This line
            # still read `['revision'][:12]`, so it raised KeyError on every
            # run and this census has produced nothing since that day.
            f"| Technique | `{tactic['uses_technique']['id']}` |",
            f"| Assurance / status | {tactic['assurance']} / {tactic['status']} |",
            "",
            "| Reach | Goal | Source |",
            "|---|---|---|",
        ]
        for row in tactic["reach"]["accepted_goals"]:
            cite = row.get("fact_id") or row.get("source", "")
            lines.append(
                f"| accepted | {escape(row['goal'])} | {escape(cite)} — {escape(row['evidence'])} |"
            )
        for row in tactic["reach"]["declined_goals"]:
            cite = row.get("fact_id") or ""
            reason = escape(row["reason"])
            source = escape(row["source"])
            prefix = f"{escape(cite)} — " if cite else ""
            lines.append(f"| declined | {escape(row['goal'])} | {prefix}{reason} ({source}) |")
        if not tactic["reach"]["accepted_goals"] and not tactic["reach"]["declined_goals"]:
            lines.append("| — | no measured reach | — |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads(CATALOG.read_text())
    rendered = render(catalog)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print(
                "TACTIC_CATALOG_CENSUS_ERROR|the generated tactic catalog page is stale;"
                " run scripts/gen-tactic-catalog-census.py",
                file=sys.stderr,
            )
            return 1
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered)
    tactics = catalog["tactics"]
    print(
        "TACTIC_CATALOG_CENSUS|"
        f"tactics={len(tactics)}|"
        f"rows={sum(len(t['reach']['accepted_goals']) + len(t['reach']['declined_goals']) for t in tactics)}|"
        f"output={OUTPUT.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
