#!/usr/bin/env python3
"""Generate Markdown dashboards for the foundational concept atlas."""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
ATLAS = ROOT / "artifacts" / "ontology" / "foundational-concepts.json"
OUT_DIR = ROOT / "docs" / "foundational-resources" / "generated"


def load_rows() -> list[dict[str, Any]]:
    with ATLAS.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    return data["rows"]


def md_list(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) if values else "-"


def pack_list(row: dict[str, Any]) -> str:
    return ", ".join(f"`{pack['id']}` ({pack['status']})" for pack in row["example_packs"])


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def math_coverage(rows: list[dict[str, Any]]) -> str:
    curriculum_rows = [row for row in rows if row["kind"] == "curriculum-node"]
    lines = [
        "# Math Curriculum Coverage",
        "",
        "Generated by `python3 scripts/gen-foundational-dashboards.py`.",
        "",
        "| Curriculum Node | Status | Decidability | Fields | First Pack | Proof Route |",
        "|---|---|---|---|---|---|",
    ]
    for row in curriculum_rows:
        proof = "; ".join(f"{route['status']}: {route['name']}" for route in row["proof_routes"])
        lines.append(
            "| "
            f"`{row['curriculum_node']}` | "
            f"`{row['curriculum_status']}` / `{row['resource_status']}` | "
            f"`{row['decidability']}` | "
            f"{md_list(row['field_ids'])} | "
            f"{pack_list(row)} | "
            f"{proof} |"
        )
    lines.extend(
        [
            "",
            "## Totals",
            "",
        ]
    )
    for key, count in sorted(Counter(row["curriculum_status"] for row in curriculum_rows).items()):
        lines.append(f"- `{key}`: {count}")
    lines.append("")
    return "\n".join(lines)


def field_dashboard(rows: list[dict[str, Any]]) -> str:
    by_field: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        for field_id in row["field_ids"]:
            by_field[field_id].append(row)
    lines = [
        "# Math Field Dashboard",
        "",
        "Generated by `python3 scripts/gen-foundational-dashboards.py`.",
        "",
        "| Field | Rows | Curriculum Nodes | Decidability Classes | Planned Packs |",
        "|---|---:|---|---|---|",
    ]
    for field_id in sorted(by_field):
        field_rows = by_field[field_id]
        curriculum_nodes = [
            row["curriculum_node"] for row in field_rows if row["kind"] == "curriculum-node"
        ]
        decidability = sorted({row["decidability"] for row in field_rows})
        packs = sorted({pack["id"] for row in field_rows for pack in row["example_packs"]})
        lines.append(
            "| "
            f"`{field_id}` | "
            f"{len(field_rows)} | "
            f"{md_list(curriculum_nodes)} | "
            f"{md_list(decidability)} | "
            f"{md_list(packs)} |"
        )
    lines.append("")
    return "\n".join(lines)


def proof_gap_dashboard(rows: list[dict[str, Any]]) -> str:
    proof_rows: list[tuple[str, str, str, str, str]] = []
    for row in rows:
        for route in row["proof_routes"]:
            if route["status"] == "checked":
                continue
            proof_rows.append(
                (
                    route["status"],
                    row["id"],
                    row["decidability"],
                    ",".join(row["field_ids"]),
                    route["name"],
                )
            )
    proof_rows.sort()
    lines = [
        "# Proof Gap Dashboard",
        "",
        "Generated by `python3 scripts/gen-foundational-dashboards.py`.",
        "",
        "| Proof Status | Row | Decidability | Fields | Route |",
        "|---|---|---|---|---|",
    ]
    for status, row_id, decidability, fields, route in proof_rows:
        lines.append(
            "| "
            f"`{status}` | "
            f"`{row_id}` | "
            f"`{decidability}` | "
            f"`{fields}` | "
            f"{route} |"
        )
    lines.extend(
        [
            "",
            "## Status Totals",
            "",
        ]
    )
    for status, count in sorted(Counter(status for status, *_ in proof_rows).items()):
        lines.append(f"- `{status}`: {count}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    rows = load_rows()
    write(OUT_DIR / "math-coverage.md", math_coverage(rows))
    write(OUT_DIR / "math-field-dashboard.md", field_dashboard(rows))
    write(OUT_DIR / "proof-gap-dashboard.md", proof_gap_dashboard(rows))
    print("generated foundational resource dashboards")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
