#!/usr/bin/env python3
"""Generate the honest F1 coverage census for the Autogenesis knowledge overlay.

All counted endpoints resolve inside Axeyum. ADR-0553 removed a sibling-backed
educational namespace; semantic dimensions returned only after Axeyum gained a
small self-contained concept vocabulary with independently validated relation
domains. Missing mappings remain missing rather than being inferred by name.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OVERLAY = ROOT / "artifacts/autogenesis/knowledge-overlay-v1.json"
OPERATIONS = ROOT / "artifacts/autogenesis/operations.json"
OUTPUT = ROOT / "docs/plan/generated/autogenesis-knowledge-coverage.md"


def endpoint(link: dict, side: str) -> tuple[str, str, str]:
    value = link[side]
    return value["namespace"], value["kind"], value["id"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    overlay = json.loads(OVERLAY.read_text())
    operations = json.loads(OPERATIONS.read_text())["operations"]
    multi = [
        operation
        for operation in operations
        if operation["scope"] == "authoritative" and len(operation["applicability"]["fact_ids"]) > 1
    ]
    multi_ids = {operation["id"] for operation in multi}
    applicable = {fact for operation in multi for fact in operation["applicability"]["fact_ids"]}
    links = overlay["links"]
    credited = {
        endpoint(link, "source")[2]
        for link in links
        if link["relation"] == "established-by" and endpoint(link, "target")[2] in multi_ids
    }
    formalizes = [
        link for link in links if link["relation"] == "formalizes" and link["status"] == "active"
    ]
    mapped_facts = {
        endpoint(link, "source")[2] for link in formalizes if endpoint(link, "source")[1] == "fact"
    }
    kernel_anchors = {
        endpoint(link, "source")[2]
        for link in formalizes
        if endpoint(link, "source")[1] == "kernel-declaration"
    }
    local_concepts = {
        endpoint(link, "target")[2]
        for link in formalizes
        if endpoint(link, "target")[:2] == ("axeyum-knowledge", "concept")
    }
    if not applicable:
        print(
            "AUTOGENESIS_KNOWLEDGE_COVERAGE_ERROR|no applicable facts: the census "
            "would be vacuously green",
            file=sys.stderr,
        )
        return 1
    lines = [
        "# Generated Autogenesis knowledge coverage",
        "",
        "> Generated by `scripts/gen-autogenesis-knowledge-coverage.py`. Do not hand-edit.",
        "> This is an overlay census, not theorem admission or complete mathematical coverage.",
        "",
        "## F1: current reusable-producer population",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Authoritative multi-target operations | {len(multi)} |",
        f"| Facts in their applicability sets | {len(applicable)} |",
        f"| Credited facts mapped with `established-by` | {len(credited & applicable)} |",
        f"| Applicable facts with no `established-by` credit | {len(applicable - credited)} |",
        "",
        "## Local semantic vocabulary",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Active qualified `formalizes` links | {len(formalizes)} |",
        f"| Axeyum-owned concepts reached | {len(local_concepts)} |",
        f"| Fact records with qualified formal content | {len(mapped_facts)} |",
        f"| Reviewed empty-footprint kernel theorem anchors | {len(kernel_anchors)} |",
        "",
        "The former sibling-backed namespace remains absent. These rows count only",
        "self-contained Axeyum concept entities and active, human-reviewed links;",
        "they do not resolve or pin another checkout.",
        "",
        "## Interpretation",
        "",
        "The current multi-target operation population is listed from the operation registry,",
        "while credit is read from fact evidence. A fact that was already settled through a",
        "different operation may be in a reusable operation's applicability set without being",
        "credited to that operation; the two counts are deliberately separate.",
        "Semantic links are qualified review metadata and never theorem or admission credit.",
    ]
    rendered = "\n".join(lines) + "\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print("AUTOGENESIS_KNOWLEDGE_COVERAGE_ERROR|coverage census is stale", file=sys.stderr)
            return 1
    else:
        OUTPUT.write_text(rendered)
    print(
        "AUTOGENESIS_KNOWLEDGE_COVERAGE|"
        f"operations={len(multi)}|applicable={len(applicable)}|"
        f"credited={len(credited & applicable)}|concepts={len(local_concepts)}|"
        f"kernel_anchors={len(kernel_anchors)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
