#!/usr/bin/env python3
"""Emit a width-graduated, satisfiable QF_BV corpus with status by construction.

Roadmap item 3.9 (`docs/solver-comparison-2026-09/11-roadmap-and-plan.md`). The
committed QF_BV corpus cannot see the class of satisfiable instance our
bit-blasting path loses: its largest satisfiable file is 1,368 bytes and its
median instance lowers to zero AND gates. The SMT-LIB family that does show it,
`QF_BV/pspace/ndist.b.*` (Froehlich, Kovasznai and Biere, JKU Linz 2013), ships
only widths 20,000-29,980 -- 21 files that are all on the same side of our
threshold, so vendoring them alone pins a class but locates no frontier.

This generator emits the same two shapes across a ladder of widths, so the
measurement is a DECIDE-FRONTIER (the largest width decided) exactly as
`scripts/gen-graduated-nra-nia.py` does for QF_NRA/QF_NIA. A frontier is a
number that can only move one way, which is what makes it usable as a ratchet.

Both families are `:status sat` **by construction**, with an explicit witness
this script evaluates in exact Python integer arithmetic before it writes the
file; a witness that does not satisfy every assertion aborts the run. The status
therefore does not depend on any solver, so a DISAGREE in measurement is a
genuine bug rather than a mislabeled file.

Families
--------

`bvwide-addcmp-wNNNNN` -- the verbatim `ndist.b` body:

    (assert (bvuge x y))
    (assert (bvule (bvadd x (_ bv1 w)) y))

Witness `x = 2**w - 1, y = 0`: `x >= y` holds, `x + 1` wraps to `0`, and
`0 <= 0` holds, at every width. Our eager lowering builds a ripple-carry
incrementer plus two unsigned comparators, so its gate count is ~linear in `w`.

`bvwide-mul-wNNNNN` -- a single wide multiplication:

    (assert (= (bvmul x y) (_ bv15 w)))

Witness `x = 3, y = 5`. Nothing folds, because both operands are symbolic. Our
`lower_mul_op` is shift-and-add, so its gate count is ~quadratic in `w` and this
family crosses the same wall at a much smaller width. Two cost curves over the
same knob is what separates "wide inputs are hard" from "one circuit is hard".

Usage
-----

    python3 scripts/gen-graduated-qfbv-width.py

Writes to `corpus/public-curated/synthetic/QF_BV/width-graduated/`. Output is
deterministic: same widths, same bytes, no RNG.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

# The `ndist.b` ladder brackets the SMT-LIB family's own 20,000-29,980 range on
# both sides, so the frontier can sit inside the ladder rather than at its edge.
ADDCMP_WIDTHS = [
    64, 128, 256, 512, 1024, 2048, 3072, 4096, 6144, 8192,
    12288, 16384, 20000, 24576, 32768,
]

# The multiplier is quadratic, so its ladder is an order of magnitude lower and
# starts small enough that the first few members are certainly decided -- a
# frontier with nothing below it is not a frontier.
MUL_WIDTHS = [8, 16, 32, 64, 96, 128, 192, 256, 384, 512, 768, 1024, 2048, 4096]

PREAMBLE = """(set-info :smt-lib-version 2.6)
(set-logic QF_BV)
(set-info :source |Width-graduated QF_BV, generated by
scripts/gen-graduated-qfbv-width.py for roadmap item 3.9. Shape taken from
SMT-LIB 2024 QF_BV/pspace (Andreas Froehlich, Gergely Kovasznai, Armin Biere,
Institute for Formal Models and Verification, JKU Linz, 2013; "Efficiently
Solving Bit-Vector Problems Using Model Checkers", SMT'13). Only the width
varies along the ladder. :status is established by the witness below, checked
in exact integer arithmetic before emission -- not by any solver.|)
(set-info :category "crafted")
(set-info :status sat)
"""


def mask(width: int) -> int:
    return (1 << width) - 1


def addcmp_body(width: int) -> str:
    return (
        f"(declare-fun x () (_ BitVec {width}))\n"
        f"(declare-fun y () (_ BitVec {width}))\n"
        f"(assert (bvuge x y))\n"
        f"(assert (bvule (bvadd x (_ bv1 {width})) y))\n"
    )


def addcmp_witness(width: int) -> tuple[int, int]:
    return (mask(width), 0)


def addcmp_note(width: int) -> str:
    return f"x = 2**{width} - 1 (all ones), y = 0"


def addcmp_holds(width: int, witness: tuple[int, int]) -> bool:
    x, y = witness
    if not (0 <= x <= mask(width) and 0 <= y <= mask(width)):
        return False
    return x >= y and ((x + 1) & mask(width)) <= y


def mul_body(width: int) -> str:
    return (
        f"(declare-fun x () (_ BitVec {width}))\n"
        f"(declare-fun y () (_ BitVec {width}))\n"
        f"(assert (= (bvmul x y) (_ bv15 {width})))\n"
    )


def mul_witness(_width: int) -> tuple[int, int]:
    return (3, 5)


def mul_note(_width: int) -> str:
    return "x = 3, y = 5"


def mul_holds(width: int, witness: tuple[int, int]) -> bool:
    x, y = witness
    if not (0 <= x <= mask(width) and 0 <= y <= mask(width)):
        return False
    return ((x * y) & mask(width)) == (15 & mask(width))


FAMILIES = [
    ("bvwide-addcmp", ADDCMP_WIDTHS, addcmp_body, addcmp_witness, addcmp_holds, addcmp_note),
    ("bvwide-mul", MUL_WIDTHS, mul_body, mul_witness, mul_holds, mul_note),
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default="corpus/public-curated/synthetic/QF_BV/width-graduated",
        help="output directory (created if absent)",
    )
    args = parser.parse_args()
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    written = 0
    for name, widths, body, witness, holds, note in FAMILIES:
        for width in widths:
            found = witness(width)
            if not holds(width, found):
                # A generation run aborts on a bad witness rather than emitting a
                # file whose `:status sat` nobody checked. This is the guard that
                # makes "status by construction" a fact rather than a claim.
                print(
                    f"ABORT: witness {found} does not satisfy {name} at width {width}",
                    file=sys.stderr,
                )
                return 1
            path = out / f"{name}-w{width:05d}.smt2"
            path.write_text(
                PREAMBLE
                + f"; witness: {note(width)} (checked by the generator)\n"
                + body(width)
                + "(check-sat)\n(exit)\n"
            )
            written += 1
            print(path)

    print(f"wrote {written} files to {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
