#!/usr/bin/env python3
"""Generate the L2 phase G5 graph dispatcher recommendation
(docs/plan/graph-directed-library-roadmap-2026-08-30.md, section G5).

G5's spec, verbatim: "The curriculum chooses the destination, the
infrastructure frontier chooses the capability, and `fact-frontier.py`
chooses the specific legal target inside that cluster. A lane can override
the ordering only with an evidence note."

This script COMPOSES three read-only layers (`scripts/lib/graph_dispatcher.py`
does the actual work; this is the CLI around it) and writes:

  - artifacts/graph-dispatcher/recommendation.json  -- the citable answer:
    destination, capability row_id, legal target, and the authority scope
    ADR-0865 actually earned for each.
  - artifacts/graph-dispatcher/dashboard.md          -- human-readable render.

It NEVER edits `scripts/check-dispatchable-frontier.py`,
`artifacts/infrastructure-frontier/`, `artifacts/graph-join/`,
`artifacts/declaration-graph/`, or `artifacts/module-baseline/` -- those are
read-only inputs owned by other lanes.

Exits nonzero, printing which layer failed and why, if any layer produces no
answer (`scripts/lib/graph_dispatcher.py::DispatcherError`) -- this is
deliberate: a dispatcher that silently recommends nothing and exits 0 is the
failure mode this repository fears most (see the module docstring in
`check-graph-dispatcher.py`).

Override usage -- "a lane can override the ordering only with an evidence
note":

    python3 scripts/gen-graph-dispatcher.py \\
        --override-legal-target F:ml430-nat-and-self-06a84ccc \\
        --evidence-note-file /path/to/note.txt

The override is REFUSED (nonzero exit, no ledger write) if the requested
fact is held-out, a mutation control, structurally blocked, not open, or if
the evidence note is missing, too short, or does not name the fact it
overrides. On success it appends one record to
`artifacts/graph-dispatcher/overrides.jsonl` (append-only; never rewritten)
and reflects the override in the regenerated recommendation.

Usage:
    python3 scripts/gen-graph-dispatcher.py
    python3 scripts/gen-graph-dispatcher.py --check   # exit 1 if writing would change committed files
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts" / "lib"))
import graph_dispatcher as gd  # noqa: E402

OUT_DIR = REPO_ROOT / "artifacts" / "graph-dispatcher"
RECOMMENDATION_JSON = OUT_DIR / "recommendation.json"
DASHBOARD_MD = OUT_DIR / "dashboard.md"
OVERRIDES_JSONL = OUT_DIR / "overrides.jsonl"


def render_dashboard(rec: dict) -> str:
    d = rec["destination"]
    c = rec["capability"]
    lt = rec["legal_target"]
    chk = rec["dispatchable_frontier_check"]
    lines = [
        "# Graph dispatcher recommendation (L2 phase G5)",
        "",
        "Generated by `scripts/gen-graph-dispatcher.py`. Composes three "
        "read-only layers -- never edit this file by hand; edit the layers "
        "or the composition logic in `scripts/lib/graph_dispatcher.py`.",
        "",
        f"> {rec['advisory_notice']}",
        "",
        "## 1. Destination (curriculum)",
        "",
        f"- node: `{d['node_id']}` -- {d['title']}",
        f"- path: `{d['path']}`",
        f"- reason: {d['selection_reason']}",
        "",
        "## 2. Capability (infrastructure frontier, ADR-0845)",
        "",
        f"- row_id: `{c['row_id']}`  (population `{c['population_id']}`, queue `{c['queue']}`)",
        f"- title: {c['title']}",
        f"- subject_declarations: {', '.join(c['subject_declarations'])}",
        f"- gain_kind: {c['gain_kind']}",
        f"- **authority: {c['authority']}** -- {c['authority_reason']}",
        f"- preregistered metric: {c['preregistered_metric']['description']}",
        f"  - command: `{c['preregistered_metric']['command']}`",
        f"  - baseline: `{c['preregistered_metric']['baseline']!r}`  "
        f"expected_change: `{c['preregistered_metric']['expected_change']}`",
        "",
        "## 3. Legal target (fact-frontier.py, via check-dispatchable-frontier.py)",
        "",
        f"- fact_id: `{lt['fact_id']}`",
        f"- match_kind: {lt['match_kind']}"
        + (f" (matched identifier `{lt['matched_identifier']}`)" if lt.get('matched_identifier') else ""),
        f"- **authority: {lt['authority']}** -- {lt['authority_reason']}",
        "",
        "## Dispatchable-frontier check (composed, not reimplemented)",
        "",
        f"- exit_code: {chk['exit_code']}  guard_failures: {chk['guard_failures']}",
        f"- open_mirrors: {chk['open_mirrors']}  held_out: {chk['held_out_count']}  "
        f"mutation: {chk['mutation_count']}  blocked: {chk['blocked_count']}  "
        f"dispatchable: {chk['dispatchable_count']} (floor {chk['dispatchable_floor']})",
        "",
    ]
    if rec.get("override"):
        ov = rec["override"]
        lines += [
            "## Active override",
            "",
            f"- overridden_to: `{ov['overridden_to']}`  "
            f"(default was `{ov['default_legal_target']}`)",
            f"- lane: `{ov['lane']}`  at: {ov['timestamp']}",
            f"- evidence note: {ov['evidence_note']!r}",
            "",
        ]
    lines += [
        "## ADR citations",
        "",
    ] + [f"- `{p}`" for p in rec["adr_citations"]] + [""]
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    """Returns True if the file's content changed (or it was created)."""
    existing = path.read_text(encoding="utf-8") if path.is_file() else None
    if existing == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def do_override(fact_id: str, note_file: Path, rec: dict) -> int:
    """Validate and record an override. Returns a process exit code.

    Refuses (exit 1, no ledger write) when:
      - the fact is held-out, a mutation control, or structurally blocked
        (the "structurally impossible to propose a held-out row" rule,
        applied here to the override path too -- an override is not an
        escape hatch around that rule);
      - the fact is not in the current dispatchable set at all (unknown or
        already settled);
      - the evidence note file is missing, empty, too short, or does not
        name the overridden fact.
    """
    dispatch_result = gd.run_dispatchable_frontier()
    forbidden = gd.forbidden_fact_ids(dispatch_result)
    if fact_id in forbidden:
        bucket = (
            "held-out (blind evaluation population, ADR-0542)" if fact_id in set(dispatch_result.get("held_out", []))
            else "a mutation negative control" if fact_id in set(dispatch_result.get("mutation", []))
            else "structurally blocked by the divergence registry"
        )
        print(f"REFUSED: {fact_id!r} is {bucket} and cannot be dispatched, "
              f"override or not.", file=sys.stderr)
        return 1
    dispatchable = set(dispatch_result.get("dispatchable") or [])
    if fact_id not in dispatchable:
        print(f"REFUSED: {fact_id!r} is not in the current dispatchable set "
              f"({len(dispatchable)} candidate(s)); nothing to override to.",
              file=sys.stderr)
        return 1
    if not note_file.is_file():
        print(f"REFUSED: evidence note file {note_file} does not exist.", file=sys.stderr)
        return 1
    note = note_file.read_text(encoding="utf-8").strip()
    if len(note) < gd.MIN_EVIDENCE_NOTE_CHARS:
        print(f"REFUSED: evidence note is {len(note)} char(s), needs at least "
              f"{gd.MIN_EVIDENCE_NOTE_CHARS} -- 'a lane can override the "
              "ordering only with an evidence note', not a placeholder.",
              file=sys.stderr)
        return 1
    if fact_id not in note:
        print(f"REFUSED: evidence note does not mention {fact_id!r} -- a note "
              "that does not name what it overrides is not an evidence note.",
              file=sys.stderr)
        return 1

    default_target = rec["legal_target"]["fact_id"]
    lane = os.environ.get("AXEYUM_AGENT", "unknown")
    record = {
        "schema_version": 1,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "lane": lane,
        "destination_path": rec["destination"]["path"],
        "capability_row_id": rec["capability"]["row_id"],
        "default_legal_target": default_target,
        "overridden_to": fact_id,
        "evidence_note": note,
        "evidence_note_path": str(note_file),
    }
    with OVERRIDES_JSONL.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, sort_keys=True) + "\n")

    rec["override"] = record
    rec["legal_target"] = {
        "fact_id": fact_id,
        "match_kind": "override",
        "matched_identifier": None,
        "authority": "override",
        "authority_reason": (
            f"lane {lane!r} overrode the dispatcher's default "
            f"{default_target!r} with an evidence note; see "
            "artifacts/graph-dispatcher/overrides.jsonl"
        ),
    }
    print(f"OK: recorded override of {default_target!r} -> {fact_id!r} for lane {lane!r}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                     help="exit 1 if generation would change committed files, without writing")
    ap.add_argument("--override-legal-target", metavar="FACT_ID")
    ap.add_argument("--evidence-note-file", type=Path)
    args = ap.parse_args()

    if bool(args.override_legal_target) != bool(args.evidence_note_file):
        ap.error("--override-legal-target and --evidence-note-file must be given together")
    if args.check and args.override_legal_target:
        ap.error("--check and --override-legal-target are mutually exclusive "
                 "(--check must never write to overrides.jsonl)")

    try:
        rec = gd.build_recommendation()
    except gd.DispatcherError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    if args.override_legal_target:
        status = do_override(args.override_legal_target, args.evidence_note_file, rec)
        if status != 0:
            return status

    rec_json = json.dumps(rec, indent=2, sort_keys=False) + "\n"
    dashboard = render_dashboard(rec)

    if args.check:
        stale = []
        if not RECOMMENDATION_JSON.is_file() or RECOMMENDATION_JSON.read_text(encoding="utf-8") != rec_json:
            stale.append(str(RECOMMENDATION_JSON))
        if not DASHBOARD_MD.is_file() or DASHBOARD_MD.read_text(encoding="utf-8") != dashboard:
            stale.append(str(DASHBOARD_MD))
        if stale:
            print("FAIL: stale (run without --check to regenerate): " + ", ".join(stale))
            return 1
        print("OK: recommendation.json and dashboard.md match a fresh recomputation")
        return 0

    changed_json = write_if_changed(RECOMMENDATION_JSON, rec_json)
    changed_md = write_if_changed(DASHBOARD_MD, dashboard)
    print(f"OK: wrote {RECOMMENDATION_JSON} (changed={changed_json}), "
          f"{DASHBOARD_MD} (changed={changed_md})")
    print(f"  destination: {rec['destination']['node_id']} ({rec['destination']['path']})")
    print(f"  capability:  {rec['capability']['row_id']} [{rec['capability']['authority']}]")
    print(f"  legal target: {rec['legal_target']['fact_id']} [{rec['legal_target']['authority']}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
