#!/usr/bin/env python3
"""Generate the L1 phase G2 join: the Mathlib declaration graph (ADR-0820)
joined against Axeyum's own state -- ledger facts, kernel declarations,
statement vocabulary, destination curriculum nodes, producers, declines, and
trust footprints (docs/plan/graph-directed-library-roadmap-2026-08-30.md,
section G2).

Writes two artifacts:

  - `artifacts/graph-join/join.json`   -- the full structured join, one block
    per dimension, each carrying its own population/resolved/unresolved
    counts and named unresolved members.
  - `artifacts/graph-join/dashboard.md` -- the human-readable summary G2's
    exit criterion asks for ("generated dashboard reports all join
    populations and unresolved counts").

Needs no Lean toolchain and no cargo run: every input is already-committed
JSON (the declaration graph, the fact ledger, the trust-closure/autogenesis/
foundational-concepts artifacts). See `scripts/lib/graph_join.py` for the
join logic and its identity-safety rules.

Usage:
    python3 scripts/gen-graph-join.py
    python3 scripts/gen-graph-join.py --population-id mathlib-group-defs-v1
    python3 scripts/gen-graph-join.py --check   # like the gate, but via gen
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts" / "lib"))
import graph_join as gj  # noqa: E402

OUT_DIR = REPO_ROOT / "artifacts" / "graph-join"


def render_dashboard(join: dict) -> str:
    lines: list[str] = []
    lines.append("# Graph join dashboard (L1 phase G2)")
    lines.append("")
    lines.append(f"Generated by `{join['generated_by']}`. Do not hand-edit.")
    lines.append("")
    lines.append(
        f"Population: `{join['population_id']}` "
        f"({join['declaration_population_count']} declarations, "
        f"{len(join['expected_roots'])} expected roots: "
        f"{', '.join(join['expected_roots'])})."
    )
    lines.append("")
    lines.append(join["notes"]["bounded"])
    lines.append("")
    lines.append(
        "**No theorem-name similarity silently creates an identity**: "
        + join["notes"]["no_name_similarity_creates_identity"]
    )
    lines.append("")
    lines.append("**ADR-0790 limit inherited**: " + join["notes"]["adr_0790_limit_inherited"])
    lines.append("")
    lines.append("## Join dimensions")
    lines.append("")
    lines.append("| dimension | population source | population | resolved | unresolved |")
    lines.append("|---|---|---:|---:|---:|")
    for dim_name, dim in join["dimensions"].items():
        lines.append(
            f"| {dim_name} | {dim['population_source']} | {dim['population_count']} | "
            f"{dim['resolved_count']} | {dim['unresolved_count']} |"
        )
    lines.append("")

    for dim_name, dim in join["dimensions"].items():
        lines.append(f"### {dim_name}")
        lines.append("")
        lines.append(
            f"Population source: `{dim['population_source']}` "
            f"({dim['population_count']} members)."
        )
        lines.append("")
        if dim["resolved"]:
            lines.append(f"Resolved ({dim['resolved_count']}):")
            lines.append("")
            for name, info in sorted(dim["resolved"].items())[:25]:
                basis = info.get("basis", "")
                lines.append(f"- `{name}` -> {json.dumps(info, sort_keys=True)}" if not basis else
                              f"- `{name}` (basis: {basis})")
            if len(dim["resolved"]) > 25:
                lines.append(f"- ... and {len(dim['resolved']) - 25} more")
            lines.append("")
        if dim["unresolved"]:
            lines.append(f"Unresolved ({dim['unresolved_count']}), first 25 by name:")
            lines.append("")
            for name, info in sorted(dim["unresolved"].items())[:25]:
                reason = info.get("reason", "")
                lines.append(f"- `{name}`: {reason}")
            if len(dim["unresolved"]) > 25:
                lines.append(f"- ... and {len(dim['unresolved']) - 25} more")
            lines.append("")

    coincidences = join["name_coincidence_candidates"]
    lines.append("## Name-coincidence candidates (all unresolved, none an identity)")
    lines.append("")
    lines.append(
        f"{len(coincidences)} declaration name(s) with no mirror fact whose bare string "
        "nonetheless equals some OTHER fact's extracted kernel subject elsewhere in the "
        "ledger. Every one stays unresolved; listed here so the coincidence is visible "
        "rather than silently avoided."
    )
    lines.append("")
    if coincidences:
        for name, info in sorted(coincidences.items()):
            lines.append(f"- `{name}` coincides with {info['coincident_fact_ids']}")
    else:
        lines.append("(none found)")
    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--population-id", default=gj.DEFAULT_POPULATION_ID)
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit nonzero if the join could not be computed or is empty",
    )
    args = parser.parse_args(argv)

    join = gj.compute_join(args.population_id)

    if join["declaration_population_count"] == 0:
        print("gen-graph-join: EMPTY declaration population -- refusing to write", file=sys.stderr)
        return 1
    if join["dimensions"]["fact_ids"]["resolved_count"] == 0:
        print(
            "gen-graph-join: ZERO fact_ids resolved -- refusing to write a join that "
            "resolves nothing (this is the vacuous-checker failure mode)",
            file=sys.stderr,
        )
        return 1

    if args.check:
        print(
            f"gen-graph-join --check: OK ({join['declaration_population_count']} declarations, "
            f"{join['dimensions']['fact_ids']['resolved_count']} fact_ids resolved)"
        )
        return 0

    args.out_dir.mkdir(parents=True, exist_ok=True)
    join_path = args.out_dir / f"{args.population_id}.join.json"
    join_path.write_text(json.dumps(join, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    dashboard_path = args.out_dir / "dashboard.md"
    dashboard_path.write_text(render_dashboard(join), encoding="utf-8")

    print(f"wrote {join_path}")
    print(f"wrote {dashboard_path}")
    for dim_name, dim in join["dimensions"].items():
        print(
            f"  {dim_name}: population={dim['population_count']} "
            f"resolved={dim['resolved_count']} unresolved={dim['unresolved_count']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
