#!/usr/bin/env python3
"""Generate the honest F1 coverage census for the Autogenesis knowledge overlay."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[1]
OVERLAY = ROOT / "artifacts/autogenesis/knowledge-overlay-v1.json"
OPERATIONS = ROOT / "artifacts/autogenesis/operations.json"
TRANSPORT = ROOT / "artifacts/autogenesis/transport-projection-v1.json"
OUTPUT = ROOT / "docs/plan/generated/autogenesis-knowledge-coverage.md"


def endpoint(link: dict, side: str) -> tuple[str, str, str]:
    value = link[side]
    return value["namespace"], value["kind"], value["id"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    overlay = json.loads(OVERLAY.read_text())
    operations = json.loads(OPERATIONS.read_text())["operations"]
    multi = [
        operation for operation in operations
        if operation["scope"] == "authoritative"
        and len(operation["applicability"]["fact_ids"]) > 1
    ]
    multi_ids = {operation["id"] for operation in multi}
    applicable = {
        fact for operation in multi for fact in operation["applicability"]["fact_ids"]
    }
    links = overlay["links"]
    credited = {
        endpoint(link, "source")[2]
        for link in links
        if link["relation"] == "established-by"
        and endpoint(link, "target")[2] in multi_ids
    }
    formalizes = [link for link in links if link["relation"] == "formalizes"]
    mapped_facts = {endpoint(link, "source")[2] for link in formalizes}
    mapped_applicable = applicable & mapped_facts
    concepts = {
        endpoint(link, "target")[2]
        for link in formalizes if endpoint(link, "target")[1] == "concept"
    }
    encounters = {
        endpoint(link, "target")[2]
        for link in formalizes if endpoint(link, "target")[1] == "encounter"
    }
    techniques = {
        endpoint(link, "target")[2]
        for link in links if link["relation"] == "uses-technique"
    }
    coverage = Counter(link.get("qualifiers", {}).get("coverage", "unqualified") for link in formalizes)
    complete = sum(
        link.get("qualifiers", {}).get("completeness") == "complete" for link in formalizes
    )
    transport = json.loads(TRANSPORT.read_text())
    transport_complete = {
        row["source_fact_id"] for row in transport["chains"] if row["status"] == "complete"
    }
    exact = sum(link.get("qualifiers", {}).get("coverage") == "exact-formalization" for link in formalizes)
    supporting = sum(link.get("qualifiers", {}).get("coverage") == "supporting-law" for link in formalizes)
    autonomous = mapped_facts & credited
    lines = [
        "# Generated Autogenesis knowledge coverage",
        "",
        "> Generated by `scripts/gen-autogenesis-knowledge-coverage.py`. Do not hand-edit.",
        "> This is an overlay census, not theorem admission or complete mathematical coverage.",
        "",
        "## F1: current reusable-producer population",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Authoritative multi-target operations | {len(multi)} |",
        f"| Facts in their applicability sets | {len(applicable)} |",
        f"| Credited facts mapped with `established-by` | {len(credited & applicable)} |",
        f"| Applicable facts with a `formalizes` mapping | {len(mapped_applicable)} |",
        f"| Applicable facts still unmapped | {len(applicable - mapped_applicable)} |",
        f"| External concepts reached | {len(concepts)} |",
        f"| External encounters reached | {len(encounters)} |",
        f"| Mathematical techniques reached | {len(techniques)} |",
        f"| Single-edge claims of complete concept coverage | {complete} |",
        "",
        "## F5: derived coverage dimensions",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Exact-formalization links | {exact} |",
        f"| Supporting-law links | {supporting} |",
        f"| Facts with qualified formal content | {len(mapped_facts)} |",
        f"| Formally mapped facts credited to a reusable producer | {len(autonomous)} |",
        f"| Formally mapped facts with a complete hash-bound transport chain | {len(mapped_facts & transport_complete)} |",
        f"| Formally mapped facts without a complete transport chain | {len(mapped_facts - transport_complete)} |",
        "",
        "## Formal-content qualifiers",
        "",
        "| Qualifier | Links |",
        "|---|---:|",
    ]
    lines.extend(f"| `{key}` | {coverage[key]} |" for key in sorted(coverage))
    lines += [
        "",
        "## Interpretation",
        "",
        "A fact may support a law, base case, or relation property without covering",
        "an entire educational concept. The overlay validator rejects `completeness: complete`",
        "on an individual `formalizes` edge; completeness can only be a derived census",
        "claim after its population and criteria have been separately specified.",
        "",
        "The current multi-target operation population is listed from the operation registry,",
        "while credit is read from fact evidence. A fact that was already settled through a",
        "different operation may be in a reusable operation's applicability set without being",
        "credited to that operation; the two counts are deliberately separate.",
    ]
    rendered = "\n".join(lines) + "\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print("AUTOGENESIS_KNOWLEDGE_COVERAGE_ERROR|coverage census is stale", file=sys.stderr)
            return 1
    else:
        OUTPUT.write_text(rendered)
    print(
        "AUTOGENESIS_KNOWLEDGE_COVERAGE|"
        f"operations={len(multi)}|applicable={len(applicable)}|"
        f"mapped={len(mapped_applicable)}|credited={len(credited & applicable)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
