#!/usr/bin/env python3
"""Generate the honest F1 coverage census for the Autogenesis knowledge overlay.

ADR-0553 removed ten of this census's fifteen rows. Every one of them counted
`formalizes` or `uses-technique` edges, whose targets were `concept`,
`encounter` and `technique` entities in a namespace resolved against a sibling
repository. With that namespace gone the relations are gone, so those rows could
only ever read zero -- and a census row that cannot move is not a measurement,
it is decoration that makes the report look richer than it is.

What survives measures the operation population, which is local and does move:
how many authoritative multi-target operations exist, how many facts are in
their applicability sets, and how many of those the fact EVIDENCE credits to
them. Restoring the rest requires a concept vocabulary this repository owns.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
OVERLAY = ROOT / "artifacts/autogenesis/knowledge-overlay-v1.json"
OPERATIONS = ROOT / "artifacts/autogenesis/operations.json"
OUTPUT = ROOT / "docs/plan/generated/autogenesis-knowledge-coverage.md"


def endpoint(link: dict, side: str) -> tuple[str, str, str]:
    value = link[side]
    return value["namespace"], value["kind"], value["id"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    overlay = json.loads(OVERLAY.read_text())
    operations = json.loads(OPERATIONS.read_text())["operations"]
    multi = [
        operation for operation in operations
        if operation["scope"] == "authoritative"
        and len(operation["applicability"]["fact_ids"]) > 1
    ]
    multi_ids = {operation["id"] for operation in multi}
    applicable = {
        fact for operation in multi for fact in operation["applicability"]["fact_ids"]
    }
    links = overlay["links"]
    credited = {
        endpoint(link, "source")[2]
        for link in links
        if link["relation"] == "established-by"
        and endpoint(link, "target")[2] in multi_ids
    }
    if not applicable:
        print(
            "AUTOGENESIS_KNOWLEDGE_COVERAGE_ERROR|no applicable facts: the census "
            "would be vacuously green",
            file=sys.stderr,
        )
        return 1
    lines = [
        "# Generated Autogenesis knowledge coverage",
        "",
        "> Generated by `scripts/gen-autogenesis-knowledge-coverage.py`. Do not hand-edit.",
        "> This is an overlay census, not theorem admission or complete mathematical coverage.",
        "",
        "## F1: current reusable-producer population",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Authoritative multi-target operations | {len(multi)} |",
        f"| Facts in their applicability sets | {len(applicable)} |",
        f"| Credited facts mapped with `established-by` | {len(credited & applicable)} |",
        f"| Applicable facts with no `established-by` credit | {len(applicable - credited)} |",
        "",
        "## Removed dimensions",
        "",
        "ADR-0553 removed the `formalizes` / `uses-technique` census: concepts,",
        "encounters and techniques reached, exact-formalization and supporting-law",
        "link counts, facts with qualified formal content, and the reviewed",
        "kernel-theorem anchor population. All ten counted edges into a namespace",
        "resolved against a sibling repository. They are not reported as zero,",
        "because a row pinned at zero reads as a measurement and is not one.",
        "",
        "## Interpretation",
        "",
        "The current multi-target operation population is listed from the operation registry,",
        "while credit is read from fact evidence. A fact that was already settled through a",
        "different operation may be in a reusable operation's applicability set without being",
        "credited to that operation; the two counts are deliberately separate.",
    ]
    rendered = "\n".join(lines) + "\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print("AUTOGENESIS_KNOWLEDGE_COVERAGE_ERROR|coverage census is stale", file=sys.stderr)
            return 1
    else:
        OUTPUT.write_text(rendered)
    print(
        "AUTOGENESIS_KNOWLEDGE_COVERAGE|"
        f"operations={len(multi)}|applicable={len(applicable)}|"
        f"credited={len(credited & applicable)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
