#!/usr/bin/env python3
"""Render the obstruction dashboard and answer Autogenesis F3's scheduling question.

F3 (`docs/autogenesis/243-knowledge-overlay-and-fill-plan.md`) exists for one
question: *which reusable capability removes the largest measured cluster?* This
page answers it twice, because the two readings differ and the difference is the
finding:

* **by cluster** -- the single largest population blocked by one obstruction;
* **by capability** -- the population a single candidate capability would reach
  across every cluster it is named for.

Ranking only by cluster would repeat doc 228's mistake at the capability layer:
a capability named for exactly one cluster is a dispatch entry, and a scheduler
that read only the first table would keep picking one.

Everything rendered here is read from `artifacts/autogenesis/obstruction-graph-v1.json`,
which is itself generated. Nothing in this file restates a number a document
already claims, and nothing computes a new one from raw evidence -- if a count
here is wrong, the generator or the evidence is wrong, and editing this page
would hide that.

Stdlib only. `--check` fails when the committed page is stale.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
GRAPH = ROOT / "artifacts/autogenesis/obstruction-graph-v1.json"
OUTPUT = ROOT / "docs/plan/generated/obstruction-graph.md"

FUNNEL_STAGES = ("goal", "adapter", "producer", "reconstruction", "checker", "obstruction")
STAGE_MEANING = {
    "goal": "a fact was selected and an episode began",
    "adapter": "a tier-C producer was dispatched AND its frozen statement export resolved",
    "producer": "the producer returned a candidate",
    "reconstruction": "a second, independent kernel re-derived it (`python -m axeyum.agent check`)",
    "checker": "the registry/transaction stage accepted it (`prepare-autogenesis-fact-transaction.py` exit 0)",
    "obstruction": "the episode ended without a proof and a typed obstruction was recorded",
}


def escape(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def by_capability(entities: list[dict]) -> list[dict]:
    """Aggregate clusters under the capability each names, ranked by facts reached."""
    rows: dict[str, dict] = {}
    for entity in entities:
        candidate = entity["candidate_capability"]
        row = rows.setdefault(
            candidate["id"],
            {
                "id": candidate["id"],
                "exists": candidate["exists"],
                "reason": candidate["reason"],
                "clusters": [],
                "facts": set(),
                "evidence": 0,
            },
        )
        row["clusters"].append(entity["id"])
        row["facts"].update(entity["population"]["fact_ids"])
        row["evidence"] += len(entity["evidence"])
    ordered = sorted(
        rows.values(),
        key=lambda row: (-len(row["facts"]), -len(row["clusters"]), row["id"]),
    )
    for row in ordered:
        row["clusters"].sort()
    return ordered


def render(graph: dict) -> str:
    entities = graph["entities"]
    funnel = graph["funnel"]
    ranked = sorted(
        entities,
        key=lambda e: (-e["facts_blocked"], -len(e["evidence"]), e["id"]),
    )
    capabilities = by_capability(entities)
    top_cluster = ranked[0]
    top_capability = capabilities[0]
    facts_total = len({f for e in entities for f in e["population"]["fact_ids"]})

    lines = [
        "# Obstruction graph",
        "",
        "Generated by `scripts/gen-obstruction-dashboard.py`; do not edit.",
        "Source: [`artifacts/autogenesis/obstruction-graph-v1.json`](../../../artifacts/autogenesis/obstruction-graph-v1.json),",
        "itself generated by `scripts/gen-obstruction-graph.py` from committed agent",
        "episodes and committed producer decline records. Schema:",
        "[`artifacts/ontology/obstruction-graph.schema.json`](../../../artifacts/ontology/obstruction-graph.schema.json).",
        "",
        "Autogenesis F3 ([doc 243](../../autogenesis/243-knowledge-overlay-and-fill-plan.md)),",
        "slice A5 of [plan 03](../../python-2026-08/03-agentic-layer.md).",
        "",
        "## The answer",
        "",
        f"**By capability:** `{top_capability['id']}`"
        f" ({'already exists' if top_capability['exists'] else 'does not exist yet'})"
        f" — it is named for {len(top_capability['clusters'])} cluster(s) covering"
        f" **{len(top_capability['facts'])} of {facts_total} blocked facts**.",
        "",
        f"**By single cluster:** `{top_cluster['id']}`"
        f" — {top_cluster['facts_blocked']} facts, removed by"
        f" `{top_cluster['candidate_capability']['id']}`"
        f" ({'already exists' if top_cluster['candidate_capability']['exists'] else 'does not exist yet'}).",
        "",
        "Read both. A capability named for exactly one cluster is a dispatch entry, which",
        "is [doc 228](../../autogenesis/228-capsule-lane-retrospective.md)'s finding one",
        "layer up; a cluster whose population was declared by a single decline record is a",
        "larger claim per unit of evidence than one assembled an episode at a time. The",
        "`evidence` column below is what tells those apart, and it is why this page ranks",
        "twice rather than picking a winner.",
        "",
        "## Funnel",
        "",
        "F3's normalization, counted over every committed episode",
        f"({funnel['episodes_read']} read, {funnel['episodes_contributing']} contributed an obstruction).",
        "",
        "| Stage | Episodes | Meaning |",
        "|---|---:|---|",
    ]
    for stage in FUNNEL_STAGES:
        lines.append(f"| `{stage}` | {funnel[stage]} | {escape(STAGE_MEANING[stage])} |")
    lines += [
        "",
        "The drop between `goal` and `adapter` is the whole population, not a rounding",
        "error: it is where an episode ends because no frozen, proof-free statement export",
        "exists for the fact. `checker` counts the registry/transaction stage, which is",
        "**not** the independent kernel re-check — a fact can be kernel-proved with an",
        "empty axiom footprint and still have nowhere to land, and collapsing the two",
        "stages would hide exactly that.",
        "",
        "## Clusters, ranked by facts blocked",
        "",
        "| # | Obstruction | Facts | Evidence | First blocker | Candidate capability | Exists |",
        "|---:|---|---:|---:|---|---|---|",
    ]
    for index, entity in enumerate(ranked, start=1):
        candidate = entity["candidate_capability"]
        lines.append(
            f"| {index} | `{entity['id']}` | {entity['facts_blocked']} | {len(entity['evidence'])} "
            f"| `{escape(entity['first_blocker']['kind'])}` — {escape(entity['first_blocker']['detail'])} "
            f"| `{candidate['id']}` | {'yes' if candidate['exists'] else 'proposed'} |"
        )
    lines += [
        "",
        "## Candidate capabilities, ranked by facts reached",
        "",
        "| # | Capability | Exists | Clusters | Facts | Evidence |",
        "|---:|---|---|---:|---:|---:|",
    ]
    for index, row in enumerate(capabilities, start=1):
        lines.append(
            f"| {index} | `{row['id']}` | {'yes' if row['exists'] else 'proposed'} "
            f"| {len(row['clusters'])} | {len(row['facts'])} | {row['evidence']} |"
        )
    lines += ["", "## Clusters in detail", ""]
    for entity in ranked:
        population = entity["population"]
        partitions = ", ".join(f"{k} {v}" for k, v in sorted(population["partitions"].items())) or "—"
        classes = ", ".join(f"`{c}`" for c in entity["decline_classes"] if c) or "—"
        tactics = ", ".join(f"`{t}`" for t in entity["tactic_ids"]) or "—"
        before = entity["resolution"]["before"]
        lines += [
            f"### `{entity['id']}`",
            "",
            f"`{escape(entity['cluster_key'])}`",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| First blocker | `{escape(entity['first_blocker']['kind'])}` — "
            f"{escape(entity['first_blocker']['detail'])} "
            f"(from `{entity['first_blocker']['source']}`) |",
            f"| Known blockers | {len(entity['known_blockers'])} |",
            f"| Episode decline classes | {classes} |",
            f"| Facts blocked | {entity['facts_blocked']} |",
            f"| Partitions | {escape(partitions)} |",
            f"| Families | {escape(', '.join(population['families']) or '—')} |",
            f"| Tactics in flight | {tactics} |",
            f"| Candidate capability | `{entity['candidate_capability']['id']}` "
            f"({'exists' if entity['candidate_capability']['exists'] else 'proposed'}) |",
            f"| Before funnel | {escape(' / '.join(f'{s} {before[s]}' for s in FUNNEL_STAGES))} |",
            f"| Resolution commit | {entity['resolution']['commit'] or '—'} |",
            f"| Assurance / status | {entity['assurance']} / {entity['status']} |",
            "",
            f"{escape(entity['candidate_capability']['reason'])}",
            "",
            "| Known blocker | Detail | Observed in |",
            "|---|---|---|",
        ]
        for blocker in entity["known_blockers"]:
            lines.append(
                f"| `{escape(blocker['kind'])}` | {escape(blocker['detail'])} "
                f"| `{escape(blocker['observed_in'])}` |"
            )
        lines += ["", "| Evidence | Kind | Fact | Decline class |", "|---|---|---|---|"]
        for row in entity["evidence"]:
            lines.append(
                f"| `{escape(row['path'])}` | {row['kind']} | {escape(row.get('fact_id') or '—')} "
                f"| {escape(row.get('decline_class') or '—')} |"
            )
        lines.append("")
        if population["fact_ids"]:
            lines.append("Blocked facts: " + ", ".join(f"`{f}`" for f in population["fact_ids"]) + ".")
        else:
            lines.append(
                "Blocked facts: none. This cluster's evidence declares no fact-ledger row, "
                "which is a fact about the record rather than about the obstruction: the "
                "producer decline records predate the fact-id convention these episodes use."
            )
        lines.append("")
    lines += [
        "## What this page does not claim",
        "",
        "* An obstruction is evidence that a route did not close a goal. It is never",
        "  evidence that the goal is false, and never evidence that the named capability",
        "  would in fact close it. Every row is `mechanically-observed` and the schema",
        "  cannot express anything higher.",
        "* `exists: yes` on a candidate capability is a **scheduling** finding, not an",
        "  engineering one: the capability is built and has not been aimed at the cluster.",
        "* No population contains a held-out fact. That is asserted by both",
        "  `scripts/gen-obstruction-graph.py` and `scripts/validate-obstruction-graph.py`,",
        "  structurally and again as a generic string walk, and",
        "  `scripts/check-autogenesis-holdout-isolation.py` walks the artifact a third time.",
        "* This graph is **not** the same census as",
        "  [`obstruction-projection-v1.json`](../../../artifacts/autogenesis/obstruction-projection-v1.json).",
        "  That one normalizes the top-level `decline` object in 47 `*-result-v*.json`",
        "  records; this one reads the agent episodes and the 11 `*-decline-v*.json`",
        "  records. The two evidence populations are disjoint (measured: zero files in",
        "  both), and neither reads the other's. Joining them is F3 work that is not done.",
        "* The nine preregistered `must-decline-mutations-v1.json` rows are removed from",
        "  every population before it is counted. A producer declining a false statement is",
        "  the trusted layer working, and counting it as a blocked fact would inflate the",
        "  clusters that happen to contain one.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=pathlib.Path, default=OUTPUT)
    args = parser.parse_args(argv)
    try:
        graph = json.loads(GRAPH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        print(f"OBSTRUCTION_DASHBOARD_ERROR|{GRAPH}: {error}", file=sys.stderr)
        return 1
    if not graph.get("entities"):
        print(
            "OBSTRUCTION_DASHBOARD_ERROR|the obstruction graph declares no cluster; there is "
            "nothing to rank and an empty page would read as a clean frontier",
            file=sys.stderr,
        )
        return 1
    rendered = render(graph)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            print(
                "OBSTRUCTION_DASHBOARD_ERROR|the generated obstruction page is stale; run "
                "scripts/gen-obstruction-dashboard.py",
                file=sys.stderr,
            )
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    capabilities = by_capability(graph["entities"])
    facts = len({f for e in graph["entities"] for f in e["population"]["fact_ids"]})
    top = capabilities[0]
    print(
        "OBSTRUCTION_DASHBOARD|"
        f"clusters={len(graph['entities'])}|"
        f"facts_blocked={facts}|"
        f"capabilities={len(capabilities)}|"
        f"top={top['id']}:{len(top['facts'])}|"
        f"output={args.output.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
