# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum._native import cas
import builtins
import fractions
import typing
__all__ = [
    "CheckReport",
    "Obligation",
    "PsdResult",
    "REPLAY_POINTS",
    "SosArtifact",
    "SosSum",
    "by_id",
    "check",
    "check_unguarded",
    "corpus",
    "is_psd",
    "psd_not_sos_dual",
    "sum_of_variable_squares",
]

REPLAY_POINTS: builtins.int
@typing.final
class CheckReport:
    r"""
    What the SOS checker actually discharged.
    """
    @property
    def obligations(self) -> builtins.list[Obligation]:
        r"""
        The obligations, in the order the checker discharged them.
        """
    @property
    def rate(self) -> typing.Optional[fractions.Fraction]:
        r"""
        The certified exponential decay rate, for a Lyapunov artifact.
        
        # Errors
        
        Propagates any Python error raised while building the fraction.
        """
    def __len__(self) -> builtins.int:
        r"""
        The number of obligations discharged.
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Whether nothing was discharged — the fail signal this route names
        explicitly.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Obligation:
    r"""
    One discharged proof obligation.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The obligation's name.
        """
    @property
    def detail(self) -> builtins.str:
        r"""
        What was established.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PsdResult:
    r"""
    The outcome of the exact rational PSD test.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        `"Yes"`, `"No"`, or `"Overflow"`.
        
        `Overflow` claims **nothing**; it is not a `No`.
        """
    @property
    def pivots(self) -> typing.Optional[builtins.list[fractions.Fraction]]:
        r"""
        The nonzero pivots, in elimination order.
        
        # Errors
        
        Propagates any Python error raised while building the fractions.
        """
    @property
    def zero_pivots(self) -> typing.Optional[builtins.int]:
        r"""
        How many pivots were exactly zero (the corank).
        """
    @property
    def reason(self) -> typing.Optional[builtins.str]:
        r"""
        Why the matrix is not positive semidefinite.
        """
    def is_psd(self) -> builtins.bool:
        r"""
        Whether the matrix was decided positive semidefinite.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SosArtifact:
    r"""
    A sum-of-squares artifact: a problem paired with its certificate.
    """
    @property
    def id(self) -> builtins.str:
        r"""
        The artifact identifier.
        """
    @property
    def kind(self) -> builtins.str:
        r"""
        `"lyapunov"`, `"barrier"` or `"psd-not-sos"`.
        """
    def to_json(self) -> builtins.str:
        r"""
        The deterministic JSON rendering.
        """
    @staticmethod
    def from_json(text: builtins.str) -> SosArtifact:
        r"""
        Parses an artifact from its deterministic JSON rendering.
        
        # Errors
        
        Raises `CasError` when the text is not a well-formed artifact.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SosSum:
    r"""
    A weighted sum of squares `sum(coefficient * square ** 2)`.
    """
    def __new__(cls, squares: typing.Sequence[tuple[builtins.int  |  fractions.Fraction  |  cas.Rational, cas.MvPoly]]) -> SosSum:
        r"""
        A sum from `[(coefficient, polynomial), ...]`.
        
        # Errors
        
        Raises `ValueError` when a coefficient is not an exact rational or the
        crate rejects the list (a negative weight, say).
        """
    def __len__(self) -> builtins.int:
        r"""
        The number of squares.
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Whether the sum has no squares.
        """
    def squares(self) -> builtins.list[tuple[fractions.Fraction, cas.MvPoly]]:
        r"""
        `[(Fraction, MvPoly), ...]`.
        
        # Errors
        
        Propagates any Python error raised while building the fractions.
        """
    def expand(self) -> cas.MvPoly:
        r"""
        The expanded polynomial the sum denotes.
        
        # Errors
        
        Raises `CasError` when the expansion overflows.
        """
    def __repr__(self) -> builtins.str: ...

def by_id(id: builtins.str) -> typing.Optional[SosArtifact]:
    r"""
    One corpus artifact by identifier.
    """

def check(artifact: SosArtifact) -> CheckReport:
    r"""
    Re-derives an SOS artifact, returning what it discharged.
    
    # Errors
    
    Raises `CasError` when the checker rejects the artifact, **and also when the
    report is empty**: a checker that discharged no obligation established
    nothing, and returning that as a pass is the failure mode this route is
    documented against.
    """

def check_unguarded(artifact: SosArtifact) -> CheckReport:
    r"""
    The same check without the empty-report guard, so a caller can see the count
    the guard is about.
    
    # Errors
    
    Raises `CasError` when the checker rejects the artifact.
    """

def corpus() -> builtins.list[SosArtifact]:
    r"""
    The committed SOS corpus.
    """

def is_psd(matrix: typing.Sequence[typing.Sequence[builtins.int  |  fractions.Fraction  |  cas.Rational]]) -> PsdResult:
    r"""
    The exact rational PSD test on a symmetric matrix of rationals.
    
    # Errors
    
    Raises `ValueError` when an entry is not an exact rational.
    """

def psd_not_sos_dual(artifact: SosArtifact) -> typing.Optional[builtins.list[tuple[cas.Monomial, fractions.Fraction]]]:
    r"""
    The dual monomial certificate of a `psd-not-sos` artifact, as
    `[(Monomial, Fraction), ...]`.
    
    Exposed because a dual that is not itself checkable is decoration.
    
    # Errors
    
    Propagates any Python error raised while building the fractions.
    """

def sum_of_variable_squares(variables: typing.Sequence[builtins.str]) -> cas.MvPoly:
    r"""
    `sum(v ** 2 for v in variables)`, the norm the checker builds for itself.
    
    # Errors
    
    Raises `CasError` when the construction overflows.
    """

