#!/usr/bin/env python3
"""Generate type stubs for the compiled ``axeyum._native`` extension.

``axeyum._native`` is a PyO3 ``.so``. Type checkers cannot read it, so every
attribute reached through it -- which is the whole Python surface -- is
invisible without stubs. This script introspects the *built* module and writes
a stub package that mirrors it exactly.

Why introspection and not hand-writing: a hand-written stub drifts silently
and then makes the checker confidently wrong. That is not a hypothetical --
the sibling repository this generator is ported from measured it twice: a
1,532-line hand stub of its native surface accounted for ~1,400 of 2,004
checker diagnostics, and a five-line hand stub of ``pytest`` shadowed the real
one and produced 417 more. Generated output plus a drift test cannot go stale
without a test going red.

Why ``Any`` everywhere: PyO3 exposes ``__text_signature__`` (parameter names,
arity, defaults) but no type information. Emitting ``Any`` for every parameter
and return keeps the stub *sound* -- it reports wrong argument names, wrong
arity and missing arguments, and never invents a type constraint the Rust code
does not actually impose.

Layout written under ``python/axeyum/``::

  _native/__init__.pyi      top-level classes, functions, constants
  _native/<sub>.pyi         one per PyO3 submodule (smt, ir, solver, ...)
  <alias>.pyi               one per submodule that ``axeyum/__init__.py``
                            registers in ``sys.modules`` as ``axeyum.<name>``
                            (none today; emitted automatically if that changes)

Usage::

    uv run --no-sync python tools/gen_native_stub.py            # write
    uv run --no-sync python tools/gen_native_stub.py --check     # exit 1 if stale

``--check`` exits 1 on drift **and** on having compared zero stubs. The second
guard is the one this repository keeps paying for elsewhere: a gate that
examines nothing and exits 0 is worse than no gate (a corpus sweep printed
"running 0 tests ... ok" for 15 days). On success it prints ``STUBS|compared=M``
so the count is visible to whoever reads the log.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import keyword
import sys
import types
from collections.abc import Mapping
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PKG_DIR = REPO_ROOT / "python" / "axeyum"
STUB_PKG = PKG_DIR / "_native"

HEADER = """\
# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `axeyum._native`. Regenerate with
#     uv run --no-sync maturin develop
#     uv run --no-sync python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.
"""

# Dunders NOT to stub. Everything else a `#[pymethods]` block defines is
# emitted, because the operators are how the types are actually used: `a < b`
# is `__lt__`, and omitting it makes the checker reject working code.
#
# `__init__`/`__new__` are excluded because PyO3 leaves them as
# `($type, *args, **kwargs)` and puts the real `#[new]` signature on the
# class's own `__text_signature__`, which `_class_lines` reads directly.
SKIPPED_DUNDERS = frozenset(
    {
        "__init__",
        "__new__",
        "__doc__",
        "__module__",
        "__dict__",
        "__weakref__",
        "__text_signature__",
        "__getattribute__",
        "__setattr__",
        "__delattr__",
        "__init_subclass__",
        "__subclasshook__",
        "__class__",
    }
)

# Reserved words a member name may collide with. Read from the interpreter's
# own tables rather than transcribed: a hand-written list is a second source of
# truth that goes stale the next time Python grows a keyword, and the failure
# would be silent (a stub emitting a name Python cannot parse).
_KEYWORDS = frozenset(keyword.kwlist) | frozenset(keyword.softkwlist)


# Members the extension exports under a name Python cannot spell (a reserved
# keyword). They are unreachable except via `getattr`, cannot be stubbed, and
# are reported so the Rust side can be renamed.
UNSPELLABLE: list[str] = []


def _is_identifier(name: str) -> bool:
    return name.isidentifier() and name not in _KEYWORDS


def _record_unspellable(owner: str, members: Mapping[str, object]) -> None:
    for name in sorted(members):
        if not name.startswith("_") and not _is_identifier(name):
            UNSPELLABLE.append(f"{owner}.{name}")


def _default_literal(text: str) -> str:
    """Keep a default value only when it round-trips as a Python literal."""
    try:
        ast.literal_eval(text)
    except (ValueError, SyntaxError, MemoryError, TypeError):
        return "..."
    return text


def _split_params(inner: str) -> list[str]:
    """Split a signature body on top-level commas."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in inner:
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def _render_params(text_signature: str | None, *, self_name: str | None) -> str:
    """Turn a PyO3 ``__text_signature__`` into an annotated parameter list.

    ``self_name`` is the receiver to prepend (``self``/``cls``), or None for a
    free function or staticmethod. Returns the text between the parentheses.
    """
    lead = [self_name] if self_name else []
    if text_signature is None:
        # PyO3 omits the signature for some constructors and operators. A
        # permissive `*args, **kwargs` never produces a false positive.
        return ", ".join(lead + ["*args: Any", "**kwargs: Any"])

    inner = text_signature.strip()
    if inner.startswith("(") and inner.endswith(")"):
        inner = inner[1:-1]

    out: list[str] = list(lead)
    for raw in _split_params(inner):
        if not raw:
            continue
        if raw in ("/", "*"):
            # A leading `/` only makes sense after a real parameter.
            if raw == "/" and len(out) <= len(lead):
                continue
            out.append(raw)
            continue
        if raw.startswith("$"):
            # `$self` / `$type` / `$cls` -- already handled via `self_name`.
            continue
        star = ""
        body = raw
        while body.startswith("*"):
            star += "*"
            body = body[1:]
        name, _, default = body.partition("=")
        name = name.strip()
        # PyO3 can emit annotations in the text signature; drop them, the stub
        # annotates everything as Any.
        name = name.split(":", 1)[0].strip()
        if not _is_identifier(name):
            # Unparseable -- fall back to something permissive rather than
            # emitting a stub that lies about arity.
            return ", ".join(lead + ["*args: Any", "**kwargs: Any"])
        if star:
            out.append(f"{star}{name}: Any")
        elif default:
            out.append(f"{name}: Any = {_default_literal(default.strip())}")
        else:
            out.append(f"{name}: Any")
    if not out:
        return ""
    return ", ".join(out)


def _receiver(text_signature: str | None) -> str | None:
    """``self``, ``cls``, or None, based on PyO3's ``$self`` / ``$type`` marker."""
    if not text_signature:
        return None
    head = text_signature.lstrip("(").split(",", 1)[0].strip()
    if head == "$self":
        return "self"
    if head in ("$type", "$cls", "$module"):
        return "cls"
    return None


def _func_lines(name: str, obj: object, *, in_class: bool, indent: str) -> list[str]:
    sig = getattr(obj, "__text_signature__", None)
    if in_class:
        recv = _receiver(sig)
        if recv is None:
            if isinstance(obj, staticmethod) or type(obj).__name__ in (
                "builtin_function_or_method",
                "function",
            ):
                lines = [f"{indent}@staticmethod"]
                params = _render_params(sig, self_name=None)
                return lines + [f"{indent}def {name}({params}) -> Any: ..."]
            recv = "self"
        lines = [f"{indent}@classmethod"] if recv == "cls" else []
        params = _render_params(sig, self_name=recv)
        return lines + [f"{indent}def {name}({params}) -> Any: ..."]
    params = _render_params(sig, self_name=None)
    return [f"{indent}def {name}({params}) -> Any: ..."]


def _class_lines(name: str, cls: type, *, level: int = 0) -> list[str]:
    pad = "    " * level
    inner = "    " * (level + 1)
    body: list[str] = []
    doc = inspect.getdoc(cls)
    if doc:
        first = doc.strip().splitlines()[0].replace('"""', "'''")
        body.append(f'{inner}"""{first}"""')
        body.append("")

    members = vars(cls)
    _record_unspellable(name, members)
    # PyO3 enum variants: class attributes whose value is an instance of the
    # class itself. Emit them first, as `Variant: ClassName`.
    variants = sorted(
        k
        for k, v in members.items()
        if not k.startswith("_") and _is_identifier(k) and isinstance(v, cls)
    )
    for k in variants:
        body.append(f"{inner}{k}: {name}")
    if variants:
        body.append("")

    props = sorted(
        k
        for k, v in members.items()
        if not k.startswith("_")
        and _is_identifier(k)
        and type(v).__name__ in ("getset_descriptor", "member_descriptor")
    )
    for k in props:
        body.append(f"{inner}{k}: Any")
    if props:
        body.append("")

    consts = sorted(
        k
        for k, v in members.items()
        if not k.startswith("_")
        and _is_identifier(k)
        and k not in variants
        and isinstance(v, (int, float, str, bytes, bool))
    )
    for k in consts:
        body.append(f"{inner}{k}: {type(members[k]).__name__}")
    if consts:
        body.append("")

    # PyO3 complex enums expose each variant as a nested class whose
    # constructor takes the variant's payload.
    nested = sorted(
        k
        for k, v in members.items()
        if not k.startswith("_") and _is_identifier(k) and inspect.isclass(v)
    )
    for k in nested:
        body.extend(_class_lines(k, members[k], level=level + 1))

    # PyO3 records the `#[new]` signature on the class, not on `__new__`.
    # Without it every constructor call would be checked against
    # `object.__init__` and reported as too many positional arguments.
    ctor = getattr(cls, "__text_signature__", None)
    body.append(f"{inner}def __init__({_render_params(ctor, self_name='self')}) -> None: ...")

    methods = sorted(
        k
        for k, v in members.items()
        if (
            not k.startswith("_")
            or (k.startswith("__") and k.endswith("__") and k not in SKIPPED_DUNDERS)
        )
        and _is_identifier(k)
        and k not in variants
        and k not in props
        and k not in consts
        and k not in nested
        and callable(v)
    )
    for k in methods:
        body.extend(_func_lines(k, members[k], in_class=True, indent=inner))

    if not body:
        body = [f"{inner}..."]
    while body and body[-1] == "":
        body.pop()
    # PyO3 complex-enum variants really are subclasses of the enum and inherit
    # its getters; an exception class really is a subclass of `Exception`.
    # Losing the base makes every inherited attribute read as unresolved.
    bases = [b.__name__ for b in cls.__bases__ if b is not object]
    head = f"{pad}class {name}({', '.join(bases)}):" if bases else f"{pad}class {name}:"
    return [head, *body, ""]


def _module_source(mod: types.ModuleType, submodules: list[str]) -> str:
    members = vars(mod)
    _record_unspellable(mod.__name__, members)
    lines = [HEADER]
    body_start = len(lines)
    for sub in submodules:
        lines.append(f"from . import {sub} as {sub}")
    if submodules:
        lines.append("")

    public = {
        k: v
        for k, v in members.items()
        if not k.startswith("_") and _is_identifier(k) and not isinstance(v, types.ModuleType)
    }
    classes = sorted(k for k, v in public.items() if inspect.isclass(v))
    funcs = sorted(k for k, v in public.items() if k not in classes and callable(v))
    consts = sorted(k for k in public if k not in classes and k not in funcs)

    for k in consts:
        lines.append(f"{k}: {type(members[k]).__name__}")
    if consts:
        lines.append("")
    for k in classes:
        lines.extend(_class_lines(k, members[k]))
    for k in funcs:
        lines.extend(_func_lines(k, members[k], in_class=False, indent=""))
    if funcs:
        lines.append("")
    # `from typing import Any` is emitted only when the body uses it. A
    # submodule the Rust side has registered but not yet populated produces an
    # otherwise empty stub, and an unused import there is a lint failure --
    # which would make `ruff` red on generated output nobody may edit.
    if any("Any" in line for line in lines[body_start:]):
        lines.insert(body_start, "from typing import Any\n")
    return "\n".join(lines).rstrip() + "\n"


def _alias_source(sub: str, mod: types.ModuleType) -> str:
    """A forwarding stub for ``axeyum.<sub>``.

    Emitted only for a submodule that ``axeyum/__init__.py`` puts into
    ``sys.modules`` under that name, so ``import axeyum.<sub>`` works at
    runtime and must type-check.
    """
    names = sorted(k for k in vars(mod) if not k.startswith("_") and _is_identifier(k))
    lines = [
        HEADER.rstrip("\n"),
        f"# `axeyum/__init__.py` registers `axeyum._native.{sub}` in `sys.modules`",
        f"# as `axeyum.{sub}`, so `import axeyum.{sub}` works at runtime and must",
        "# type-check. Each name is listed rather than star-imported, so a name",
        "# vanishing from the extension shows up as a diff in this file.",
        "",
        f"from axeyum._native import {sub} as _mod",
        "",
    ]
    for k in names:
        lines.append(f"{k} = _mod.{k}")
    return "\n".join(lines).rstrip() + "\n"


def _sys_module_aliases(native: types.ModuleType, subs: list[str]) -> list[str]:
    """Submodules published as ``axeyum.<name>`` in ``sys.modules``.

    Derived, never listed by hand: the package decides which submodules it
    re-registers, and a hand-maintained list here would be one more thing that
    can drift from the runtime. None are registered today; if one is, its
    forwarding stub appears without this file changing.
    """
    return [sub for sub in subs if sys.modules.get(f"axeyum.{sub}") is getattr(native, sub, None)]


def _generate(stub_pkg: Path = STUB_PKG, pkg_dir: Path = PKG_DIR) -> dict[Path, str]:
    import axeyum._native as native

    subs = sorted(k for k, v in vars(native).items() if isinstance(v, types.ModuleType))
    out: dict[Path, str] = {
        stub_pkg / "__init__.pyi": _module_source(native, subs),
    }
    for sub in subs:
        out[stub_pkg / f"{sub}.pyi"] = _module_source(getattr(native, sub), [])
    for sub in _sys_module_aliases(native, subs):
        out[pkg_dir / f"{sub}.pyi"] = _alias_source(sub, getattr(native, sub))
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate axeyum._native type stubs.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any stub differs from the built module",
    )
    parser.add_argument(
        "--stub-dir",
        type=Path,
        default=None,
        help=(
            "write/compare stubs under this directory instead of "
            "python/axeyum/_native (used by the drift test and by the negative "
            "controls that demonstrate --check failing)"
        ),
    )
    args = parser.parse_args(argv)

    stub_pkg = args.stub_dir.resolve() if args.stub_dir else STUB_PKG
    pkg_dir = stub_pkg.parent if args.stub_dir else PKG_DIR

    files = _generate(stub_pkg, pkg_dir)
    stale: list[tuple[Path, str]] = []
    # `compared` counts stubs that were actually read off disk and compared
    # byte-for-byte -- NOT how many the generator produced. Those differ
    # exactly when the stubs are missing, which is the case where a count of
    # "files generated" would report a healthy number for a comparison that
    # never happened.
    compared = 0
    for path, text in sorted(files.items()):
        if path.exists():
            compared += 1
            existing = path.read_text()
        else:
            existing = None
        if existing == text:
            continue
        stale.append((path, "missing" if existing is None else "differs"))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)

    # A stub file left behind for a submodule that no longer exists is drift too.
    if stub_pkg.exists():
        for path in sorted(stub_pkg.glob("*.pyi")):
            if path not in files:
                compared += 1
                stale.append((path, "orphan -- no such submodule"))
                if not args.check:
                    path.unlink()

    if not args.check:
        print(f"wrote {len(files)} stub files ({len(stale)} changed)")
        if UNSPELLABLE:
            print(
                "note: exported under a name Python cannot spell "
                "(reachable only via getattr, not stubbed):"
            )
            for entry in sorted(set(UNSPELLABLE)):
                print(f"  {entry}")
        return 0

    failed = False
    if stale:
        print("stale native stubs:", file=sys.stderr)
        for path, why in stale:
            rel = path if not path.is_relative_to(REPO_ROOT) else path.relative_to(REPO_ROOT)
            print(f"  {rel}: {why}", file=sys.stderr)
        print(
            "run: uv run --no-sync maturin develop && "
            "uv run --no-sync python tools/gen_native_stub.py",
            file=sys.stderr,
        )
        failed = True
    if compared == 0:
        # The inert-gate guard. Without it, pointing this at a directory with
        # no stubs in it would report "nothing differed" and exit 0.
        print(
            f"STUBS|FAIL compared=0 -- no stub was read from {stub_pkg}; "
            "a check that compared nothing is not a pass",
            file=sys.stderr,
        )
        failed = True
    if failed:
        print(f"STUBS|FAIL compared={compared} stale={len(stale)}")
        return 1
    print(f"STUBS|compared={compared}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
