# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from axeyum._native import ir
import builtins
import enum
import typing
__all__ = [
    "BF16",
    "F128",
    "F16",
    "F32",
    "F64",
    "FP4_E2M1",
    "FP8_E4M3",
    "FP8_E5M2",
    "FloatFormat",
    "RoundingMode",
    "TF32",
    "abs",
    "add",
    "add_rne",
    "count_leading_zeros",
    "div",
    "div_rne",
    "e2m1_is_normal",
    "e2m1_is_subnormal",
    "e2m1_is_zero",
    "e2m1_to_real",
    "e4m3_is_nan",
    "e4m3_is_normal",
    "e4m3_is_subnormal",
    "e4m3_is_zero",
    "eq",
    "fma",
    "fma_rne",
    "from_real",
    "from_sbv",
    "from_ubv",
    "geq",
    "gt",
    "is_infinite",
    "is_nan",
    "is_negative",
    "is_normal",
    "is_positive",
    "is_subnormal",
    "is_zero",
    "isqrt",
    "leq",
    "lt",
    "max",
    "min",
    "mul",
    "mul_rne",
    "neg",
    "pack_params",
    "pack_value",
    "rem",
    "rem_sym",
    "round_rational_to_format",
    "round_significand",
    "round_to_format",
    "round_to_integral",
    "round_to_integral_sym",
    "round_variable",
    "sbv_to_fp",
    "sqrt",
    "sqrt_rne",
    "sub",
    "sub_rne",
    "to_fp",
    "to_real",
    "to_real_sym",
    "to_sbv",
    "to_sbv_sym",
    "to_ubv",
    "to_ubv_sym",
    "ubv_to_fp",
]

BF16: FloatFormat
F128: FloatFormat
F16: FloatFormat
F32: FloatFormat
F64: FloatFormat
FP4_E2M1: FloatFormat
FP8_E4M3: FloatFormat
FP8_E5M2: FloatFormat
TF32: FloatFormat
@typing.final
class FloatFormat:
    r"""
    An IEEE 754 (or ML) floating-point format: `(exp_bits, sig_bits)`.
    
    `sig_bits` includes the hidden bit, so `F32` is `(8, 24)` and a value of
    this format is `exp_bits + sig_bits` bits wide.
    """
    @property
    def exp_bits(self) -> builtins.int:
        r"""
        Exponent bits.
        """
    @property
    def sig_bits(self) -> builtins.int:
        r"""
        Significand bits, including the hidden bit.
        """
    def __new__(cls, exp_bits: builtins.int, sig_bits: builtins.int) -> FloatFormat: ...
    def width(self) -> builtins.int:
        r"""
        Total bit width of a value in this format.
        """
    def is_ieee(self) -> builtins.bool:
        r"""
        Whether the format follows IEEE conventions.
        
        `FP8_E4M3` and `FP4_E2M1` do not (no infinities, different NaN rules);
        the generic builders are **not** correct for them and their dedicated
        `e4m3_*` / `e2m1_*` helpers must be used instead.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class RoundingMode(enum.Enum):
    r"""
    One of the five SMT-LIB rounding modes.
    """
    NearestTiesToEven = ...
    r"""
    Round to nearest, ties to even (`RNE`).
    """
    NearestTiesToAway = ...
    r"""
    Round to nearest, ties away from zero (`RNA`).
    """
    TowardPositive = ...
    r"""
    Round toward positive infinity (`RTP`).
    """
    TowardNegative = ...
    r"""
    Round toward negative infinity (`RTN`).
    """
    TowardZero = ...
    r"""
    Round toward zero (`RTZ`).
    """

def abs(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def add(arena: ir.Arena, fmt: FloatFormat, a: ir.Term, b: ir.Term, mode: RoundingMode) -> ir.Term: ...

def add_rne(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> typing.Optional[ir.Term]: ...

def count_leading_zeros(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def div(arena: ir.Arena, fmt: FloatFormat, a: ir.Term, b: ir.Term, mode: RoundingMode) -> ir.Term: ...

def div_rne(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> typing.Optional[ir.Term]: ...

def e2m1_is_normal(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def e2m1_is_subnormal(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def e2m1_is_zero(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def e2m1_to_real(arena: ir.Arena, x: ir.Term) -> typing.Optional[ir.Term]: ...

def e4m3_is_nan(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def e4m3_is_normal(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def e4m3_is_subnormal(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def e4m3_is_zero(arena: ir.Arena, x: ir.Term) -> ir.Term: ...

def eq(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def fma(arena: ir.Arena, fmt: FloatFormat, a: ir.Term, b: ir.Term, c: ir.Term, mode: RoundingMode) -> ir.Term:
    r"""
    `axeyum_fp::fma` — fused multiply-add `a * b + c`, one rounding.
    """

def fma_rne(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term, z: ir.Term) -> typing.Optional[ir.Term]:
    r"""
    `axeyum_fp::fma_rne`; `None` = an operand is not constant.
    """

def from_real(arena: ir.Arena, dst: FloatFormat, mode: RoundingMode, num: builtins.int, den: builtins.int) -> typing.Optional[ir.Term]:
    r"""
    `axeyum_fp::from_real` — an exact rational to a float constant;
    `None` = not representable.
    """

def from_sbv(arena: ir.Arena, dst: FloatFormat, mode: RoundingMode, x: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::from_sbv` — signed bit-vector to float.
    """

def from_ubv(arena: ir.Arena, dst: FloatFormat, mode: RoundingMode, x: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::from_ubv` — unsigned bit-vector to float.
    """

def geq(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def gt(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def is_infinite(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def is_nan(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def is_negative(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def is_normal(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def is_positive(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def is_subnormal(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def is_zero(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def isqrt(arena: ir.Arena, n: ir.Term) -> tuple[ir.Term, ir.Term]:
    r"""
    `axeyum_fp::isqrt` — the integer square root gadget, as `(root, remainder)`.
    """

def leq(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def lt(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def max(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def min(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def mul(arena: ir.Arena, fmt: FloatFormat, a: ir.Term, b: ir.Term, mode: RoundingMode) -> ir.Term: ...

def mul_rne(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> typing.Optional[ir.Term]: ...

def neg(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> ir.Term: ...

def pack_params(arena: ir.Arena, m_w: ir.Term, e: ir.Term, sb: builtins.int, bias: builtins.int) -> tuple[ir.Term, ir.Term]:
    r"""
    `axeyum_fp::pack_params` — `(m_w, e)` normalization, as `(m, e)` terms.
    """

def pack_value(arena: ir.Arena, eb: builtins.int, sb: builtins.int, sign: ir.Term, m: ir.Term, e: ir.Term, mode: RoundingMode) -> ir.Term:
    r"""
    `axeyum_fp::pack_value` — assemble a float from sign/significand/exponent.
    """

def rem(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> typing.Optional[ir.Term]: ...

def rem_sym(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> ir.Term: ...

def round_rational_to_format(eb: builtins.int, sb: builtins.int, num: builtins.int, den: builtins.int, mode: RoundingMode) -> typing.Optional[builtins.int]:
    r"""
    `axeyum_fp::round_rational_to_format`; `None` = not representable.
    """

def round_significand(arena: ir.Arena, sig: ir.Term, keep: builtins.int) -> ir.Term:
    r"""
    `axeyum_fp::round_significand` — keep `keep` significand bits.
    """

def round_to_format(eb: builtins.int, sb: builtins.int, value: builtins.float, mode: RoundingMode) -> builtins.int:
    r"""
    `axeyum_fp::round_to_format` — a concrete `f64` rounded into `(eb, sb)`,
    returned as the raw bit pattern.
    """

def round_to_integral(arena: ir.Arena, fmt: FloatFormat, mode: RoundingMode, x: ir.Term) -> typing.Optional[ir.Term]:
    r"""
    `axeyum_fp::round_to_integral`; `None` = argument not constant.
    """

def round_to_integral_sym(arena: ir.Arena, fmt: FloatFormat, mode: RoundingMode, x: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::round_to_integral_sym` — the symbolic (always-a-term) form.
    """

def round_variable(arena: ir.Arena, m: ir.Term, drop: ir.Term, mode: RoundingMode, negative: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::round_variable` — the shared rounding gadget.
    """

def sbv_to_fp(arena: ir.Arena, fmt: FloatFormat, bv: ir.Term, mode: RoundingMode) -> typing.Optional[ir.Term]:
    r"""
    `axeyum_fp::sbv_to_fp`; `None` = argument not constant.
    """

def sqrt(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, mode: RoundingMode) -> ir.Term:
    r"""
    `axeyum_fp::sqrt` with an explicit rounding mode.
    """

def sqrt_rne(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> typing.Optional[ir.Term]: ...

def sub(arena: ir.Arena, fmt: FloatFormat, a: ir.Term, b: ir.Term, mode: RoundingMode) -> ir.Term: ...

def sub_rne(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, y: ir.Term) -> typing.Optional[ir.Term]: ...

def to_fp(arena: ir.Arena, src: FloatFormat, dst: FloatFormat, mode: RoundingMode, x: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::to_fp` — reformat between two float formats.
    """

def to_real(arena: ir.Arena, fmt: FloatFormat, x: ir.Term) -> typing.Optional[ir.Term]: ...

def to_real_sym(arena: ir.Arena, fmt: FloatFormat, x: ir.Term, exceptional: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::to_real_sym` — the symbolic form of the float-to-real bridge.
    """

def to_sbv(arena: ir.Arena, fmt: FloatFormat, mode: RoundingMode, x: ir.Term, width: builtins.int) -> typing.Optional[ir.Term]:
    r"""
    `axeyum_fp::to_sbv`; `None` = argument not constant.
    """

def to_sbv_sym(arena: ir.Arena, fmt: FloatFormat, mode: RoundingMode, x: ir.Term, width: builtins.int, fresh: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::to_sbv_sym` — the symbolic signed form.
    """

def to_ubv(arena: ir.Arena, fmt: FloatFormat, mode: RoundingMode, x: ir.Term, width: builtins.int) -> typing.Optional[ir.Term]:
    r"""
    `axeyum_fp::to_ubv`; `None` = argument not constant.
    """

def to_ubv_sym(arena: ir.Arena, fmt: FloatFormat, mode: RoundingMode, x: ir.Term, width: builtins.int, fresh: ir.Term) -> ir.Term:
    r"""
    `axeyum_fp::to_ubv_sym` — the symbolic form, with the caller's `fresh`
    bit-vector standing for the out-of-range result.
    """

def ubv_to_fp(arena: ir.Arena, fmt: FloatFormat, bv: ir.Term, mode: RoundingMode) -> typing.Optional[ir.Term]:
    r"""
    `axeyum_fp::ubv_to_fp`; `None` = argument not constant.
    """

